### ISSUE TITLE
Accurate fetch download progress

### ISSUE THREAD

**Issue by edubart** [libgit2/libgit2#1054]
Fetching with libgit2 at the moment will only provides **received_objects**, **total_objects** and **received_bytes** in **git_transfer_progress** struct. The proportion **received_objects/total_objects** can be used to calculate fetch download progress, but it's very inaccurate because a git repository  may have large objects about 200mb to be received while small ones too, so when using that proportion the fetch download progress may get stuck at the same value for minutes and is not possible to estimate the time to complete the download neither.

I was wondering if is possible to add a field **total_bytes** so we can accurately calculate fetch download progress using **received_bytes/total_bytes**, the **total_bytes** field would be set to the sum of the size of all objects to be received before actually downloading them.

**Comment by Timmmm** [comment]
I don't see why this wouldn't be possible (with changes to the git protocol). When I run `git fetch` the server works out which objects to send and compresses some (?) of them before sending any objects. Why can't it stat all the objects to send, add up their sizes and send the total size before sending the objects? It should probably be opt in, but I think you are overstating the "server stress". After all it has to *read* all these objects. Just getting their size shouldn't add much overhead.

But anyway this is a git protocol issue not a libgit2 one.
