### ISSUE TITLE
Clone API completionism

### ISSUE THREAD

**Issue by ben** [libgit2/libgit2#1142]
Here's a boiled-down version of the [clone command-line options](http://git-scm.com/docs/git-clone.html). Which of these do we want to support? I'd like to get the changes that break the `git_clone` API out of the way before we hit 1.0.

| Feature | Status | Notes |
| --- | :-: | --- |
| `--local` | local - Done (#2011) | Make file copies of HEAD and everything under refs and objects. Use hardlinks for objects where possible. |
| `--no-hardlinks` | local - Done (#2011) | Same as `--local`, but always copy files. |
| `--depth` | shallow | Shallow clone |
| `--upload-pack` | Done (#2463) transport | (SSH only) Custom command to run on the remote machine |
| `--shared` | Done (#1855) | Instead of copying data, set up `alternates` to share objects with the origin. |
| `--reference <repo>` | Done (#1855) | Set up `alternates` to use `<repo>`, to reduce the amount of data transferred. |
| `--config <key>=<value>` | Done (#1855) | Set values in the local config after initialization, but before fetch |
| `--separate-git-dir=<dir>` | Done (#1855) | Custom placement for `.git` directory |
| `--template` | Done (#1855) |  |
| `--branch` | Done (#1855) | Custom target for HEAD (instead of using the remote's HEAD) |
| `--single-branch` | Done | This is already possible using a `+refs/heads/<branch>:refs/remotes/origin/<branch>` fetch spec. |
| `--mirror` | Done | This is already possible using a `+refs/*:refs/*` fetch spec. |
| `--recursive` | Done | This can be accomplished with `git_submodule_foreach`, though it would be better to have `--separate-git-dir`. |
| `--no-checkout` | Done |  |
| `--bare` | Done |  |
| `--origin` | Done |  |
| `--progress` | Done |  |
| `--quiet`,`--verbose` | N/A | Command-line output |

Key:
- **local** -- An optimized local-filesystem clone should probably get its own `git_clone_local` API.
- **shallow** -- This requires more complete support for shallow clones.
- **transport** -- This probably belongs in a transport-specific options API, which doesn't exist as of yet.

**Comment by aral** [comment]
Use case: minimise size when Git is used in iOS/other mobile app.

Priorities:

```--single-branch
--depth 1```
