### ISSUE TITLE
git_reference_owner

### ISSUE THREAD

**Issue by scunz** [libgit2/libgit2#1161]
1. `git_reference_owner` currently returns `ref->owner` without incrementing the reference counter. As a consequence, calling `git_repository_free` on the resulting pointer brings the reference counter out of balance.
This should either be documented or changed.

2. `git_reflog` internally stores a pointer to its owning repostiory. This pointer is obtained through the above `git_reference_owner`.
However, if for some bad reason this workflow happens:
    * `git_repository_open(&r, ...)`
    * `git_repository_head(&h, r)`
    * `git_reflog_read(&l, h)`
    * `git_repository_free(r)`
    * `git_reflog_write(&l)`

The last call might use a dangling pointer into the `git_repository`.

Do you think, it is worth making the above "rock solid" ( = Keep the repository alive as long as a reflog exists that uses it) or should we just say: This is an unappropiate workflow, undefined behaviour is to be expected?

**Comment by ethomson** [comment]
Appears that this was fixed a while back and this issue has stayed alive!  Closing it.  Thanks!
