### ISSUE TITLE
Remove empty section from config files upon the removal of the last entry

### ISSUE THREAD

**Issue by nulltoken** [libgit2/libgit2#1205]
This relates to libgit2/libgit2Sharp#287

Although quite a cosmetic feature request, git.git does indeed provide a similar feature when a whole branch is dropped. This is a side effect of the [git_config_rename_section_in_file function](https://github.com/git/git/blob/master/config.c#L1570-1654) which regenerates the whole config file.

**Comment by carlosmn** [comment]
> which regenerates the whole config file.

That seems like an odd way of putting it. It simply replaces one section marker with another. Anything else remains exactly the same as it's very hard to actually regenerate the file as it was before reading it in.

But this has nothing to do with removing the section marker when removing the last entry. This gets called when you explicitly ask to remove the whole section, which is something you rarely get to do.

**Comment by apflieger** [comment]
Would it be better to have an explicit git_config_delete_section function ?

**Comment by ethomson** [comment]
If this was something that we wanted to pursue, yes, something similar to `git config --remove-section` seems like the way to approach it.  As it is, git itself does not remove a section when the last entry is removed:

```
% git config --unset foo.bar
% cat .git/config           
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
	ignorecase = true
	precomposeunicode = true
[foo]
```

We're in keeping with this, so this does not seem like a bug, and I'm closing this issue.
