### ISSUE TITLE
Rebase

### ISSUE THREAD

**Issue by Uncommon** [libgit2/libgit2#1415]
I don't see rebase anywhere in the API, and there doesn't seem to be an issue filed already. The only rebase-related thing I can find is `git_repository_state()`.

Basically I'm looking for everything `git rebase` does:
- Simple rebase, or "interactive" given an equivalent of the `rebase -i` text file
- Progress callbacks as each commit is applied
- Skip, continue, and abort

**Comment by carlosmn** [comment]
Added initially in #2253
