### ISSUE TITLE
Fetch for shallow repositories

### ISSUE THREAD

**Issue by edubart** [libgit2/libgit2#1430]
Fetching shallow repostiories with libgit2 does not work, this was tested with latest development branch.

Steps to reproduce:
* Create and clone a repository using depth command:
```git clone --depth 1 git://github.com/user/repo.git```
* Push a new commit to the remote repository

```
echo test > test
git add test
git commit -a -m "test commit" && git push
```
3. Try to fetch using libgit2, this will lead to the following error:

```
./git2 fetch origin master
Fetching origin for repo 0x23e80d0
Bad news:
Object not found - failed to find pack entry
(6ac4fe2857cc4c02cec4364bc956d1da2a85f5a1)
```

Fetching with original git works fine. Is there any workaround to get this kind of fetch to work with libgit2?

**Comment by carlosmn** [comment]
The problem is the same as #2782, it's not about the fetch, but about libgit2 not supporting shallow repositories. We should make an issue which describes the missing support which we'll likely eventually have to support to dedup the questions.

**Comment by carlosmn** [comment]
#3058 explains what we would need to support/do in order for this to work and that should be the main issue if any discussion needs to happen.
