### ISSUE TITLE
git_stash_pop() and git_stash_apply()

### ISSUE THREAD

**Issue by TNick** [libgit2/libgit2#1447]
As far as I can tell git_stash_save() does the following:
+ get last commit
+ create a commit for index - ```commit_index()```
+ if untracked and/or ignored files are requested then create a commit for these - ```commit_untracked()```
+ create a commit for workdir - ```commit_worktree()``` - that will be returned; set previous three commits (base, index, untracked in this order) as parents for this one
+ create a reference with ```update_reflog()``` that points to oid of the commit in previous step
+ reset index and worktree

Based on the model of ```git_stash_drop()``` I suggest [this implementation](https://gist.github.com/TNick/5277132) tested with a repository created as follows:

```
git init
echo "File content 1" > f1.txt
echo "File content 2" > f2.txt
echo "File content 3" > f3.txt
git add f1.txt
git add f2.txt
git ci -m "Added files to repo"
echo "File content 1 changed" > f1.txt
rm f2.txt
git status
# On branch master
# Changes not staged for commit:
#   (use "git add/rm <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working directory)
#
#	modified:   f1.txt
#	deleted:    f2.txt
#
# Untracked files:
#   (use "git add <file>..." to include in what will be committed)
#
#	f3.txt
```

This fails to restore untracked files:

```
git status
# On branch master
# Changes to be committed:
#   (use "git reset HEAD <file>..." to unstage)
#
#	modified:   f1.txt
#	deleted:    f2.txt
#	new file:   f3.txt
```

**Comment by ethomson** [comment]
Closed now that we have some pull requests like #2636 ...!
