### ISSUE TITLE
Ignore rules without a repo

### ISSUE THREAD

**Issue by kevinsawicki** [libgit2/libgit2#1481]
Is there a way to give libgit2 some ignore rules and ask it if a path is ignored given those rules without checking in the `.gitignore`?

If not, could there be a way to expose the rules engine without the need for a repo handle, instead just allowing some sort of structure that can have rules added to it and then be queried for whether paths are ignored.

Thanks!

**Comment by carlosmn** [comment]
This is something I think about every once in a while, but I can't come up with a solution which works reliably but doesn't require a repository handle. The main issue is that whether a path is ignored or not can depend on whether it's in the index or HEAD, which you cannot do without opening up the repository.

@kevinsawicki were you after something like what @arrbee mentions above or were/are you after an authoritative answer on what is ignored? If the latter, I'm afraid we cannot expose this without looking at the repo and the index.

**Comment by carlosmn** [comment]
I'm closing this as there's been no movement, and I believe that the solutions to this have already been enumerated. For an authoritative answer, we do need a repository open, but you can make use of pathspecs to see if something matches whatever rules you have outside of the repository's configuration.

If there's more details on what's needed, we can revisit.
