### ISSUE TITLE
Checking for object existence before writing should be up to each backend

### ISSUE THREAD

**Issue by jwiegley** [libgit2/libgit2#1509]
The attempt to write each new object causes an existence check. Here is the relevant code (in 0.18):

``` c
int git_odb_write(
    git_oid *oid, git_odb *db, const void *data, size_t len, git_otype type)
{
    /* ... */
    git_odb_hash(oid, data, len, type);
    if (git_odb_exists(db, oid))
        return 0;
```

My custom backend (which writes Git objects to S3) needs to assume that the remote object doesn't already exist if you've asked me to write it.  I understand we could argue over that necessity, but I've considered my use case in depth and discovered that it is an anti-optimization for me (on the order of many seconds) to have this check happen before every write request.

My request is that way move this existence check into each particular backend (pack and loose), and let the backend optimize for this question in the way it knows best.  This is necessary because I can't distinguish between a regular existence check, and an existence check that is only happening to prevent duplication of data.  This ends up being a premature optimization for me, since there are cases when duplication is actually cheaper than checking for existence.  It should be each backend's choice to decide this question.

Pinging @snoyberg, my co-worker.

**Comment by carlosmn** [comment]
I believe this was also mentioned in the PR, but adding the option to the function call is not the way we would want to go. It might be doable to add a flag to a backend which says that the frontend should not bother checking for existence when writing, but as there has not been any movement in this area for quite a while, I'm closing the issue.
