### ISSUE TITLE
Function to get the default signature

### ISSUE THREAD

**Issue by joshaber** [libgit2/libgit2#1528]
Git.git uses some reasonable defaults if user.name and user.email aren't set. Libgit2 should be able to give us that default signature.

**Comment by alyssais** [comment]
I use Git with GECOS and the EMAIL environment variable. I think that these would be make sense in virtually all cases, when they’re set. Would it be reasonable for libgit2 to use those? I’d be happy to write the patch.

**Comment by ethomson** [comment]
Hi @alyssais - that's an interesting question.  We're sometimes in the habit of looking at environment variables (when requested by the program, off by default) but not in this case, at least so far.

I think opening a new issue would probably be worthwhile here - in particular, I think that we should probably think about the implementation before we right any code.

(eg: I didn't know that there was a `GECOS` environment variable!)
