### ISSUE TITLE
qsort_r not present on all Linux systems

### ISSUE THREAD

**Issue by thmo** [libgit2/libgit2#1606]
The man page says:

```
qsort_r() was added to glibc in version 2.8.
```

On systems with older glibc, e.g. SLES10 (glibc 2.4) or RHEL5 (glibc 2.5) `qsort_r` is not present, and linking against libgit2 causes an `undefined reference` error.

There are already conditionals in `src/util.c` to use `git__insertsort_r()` instead. Maybe that has to be complemented by a configure test.

**Comment by Kochise** [comment]
Fyi, qsort has been added to Alpine on 2021/09/22

https://gitlab.alpinelinux.org/alpine/aports/-/commit/bf5bbfdbf780092f387b7abe401fbfceda90c84d

Profit.
