### ISSUE TITLE
Staging file from memory in the index

### ISSUE THREAD

**Issue by jessevdk** [libgit2/libgit2#1671]
I was wondering if it would be useful to add an API to the index which allows staging a file while providing the file blob contents as a buffer. I'm looking at implementing staging hunks and single lines (i.e. staging a patch), and as far as I can see the way to do it currently is:

1. Create a new blob with the file contents
2. Fill in a git_index_entry with all the appropriate info
3. Add the git_index_entry to the index using git_index_add

Please correct me if I'm wrong. To make it easier to stage partial changes, it would be helpful to have an API like:

git_index_add_frombuffer (index, path, buffer, buffer_len)

Internally this works just like git_index_add_bypath, except that the file contents blob is created from the provided buffer instead of the actual file contents. Is this a reasonable addition to the index API?

**Comment by carlosmn** [comment]
Implemented in #2876
