### ISSUE TITLE
git_submodule_sync does not update the submodule's gitconfig

### ISSUE THREAD

**Issue by jspahrsummers** [libgit2/libgit2#1682]
Currently, `git_submodule_sync()` will only update the parent repository's `.git/config`, replacing the value of any `url` key for that submodule.

By contrast, `git submodule sync` will _also_ write to the submodule's gitconfig, updating any remote URLs as appropriate. Effectively, it ensures that a submodule will push and pull using the remote URL specified in the parent repo's `.gitmodules`.

**Comment by aswingk** [comment]
I don't see pushUrl is updating? ideally along with remote.<default_remote>.url, the remote.<default_remote>.pushUrl also should get updated
