### ISSUE TITLE
Lookup of the "empty tree" should return a new tree

### ISSUE THREAD

**Issue by jwiegley** [libgit2/libgit2#1713]
The following works with command-line Git:

``` bash
git init
git show 4b825dc642cb6eb9a060e54bf8d69288fbee4904
```

But if you try to `git_tree_lookup` that same SHA in an empty repository with Libgit2, you get:

```
Could not lookup 4b825dc642cb6eb9a060e54bf8d69288fbee4904: Object not found - failed to find pack entry (4b825dc642cb6eb9a060e54bf8d69288fbee4904)
```

I think that looking up the "empty tree" should return a new tree object with an entry count of zero, and that attempting to write a tree with an entry count of 0 should be a no-op.

**Comment by roshan3133** [comment]
http://stackoverflow.com/questions/36546774/gitlab-repository-corrupted-showing-500-error-on-frontend/36599198#36599198
