### ISSUE TITLE
Defer checking for packfile existence until it's actually needed

### ISSUE THREAD

**Issue by jwiegley** [libgit2/libgit2#1737]
I have a situation where I download index files, but not their corresponding pack files, from Amazon S3 because I want to determine which objects live in which pack files, so that I know which one to download without having to download them all.  However, if I call `git_odb_backend_one_pack` with just an index file, it gives me an error right away saying that the pack-file doesn't also exist.

I see no reason why the check for pack-file existence can't be deferred until the time when its actually needs to be opened to get the object data.  This makes it possible for people to do things that only require the index data with just the index.

**Comment by carlosmn** [comment]
This seems to mix together a few different things. The purpose of `git_odb_backend_one_pack()` is to read data from a packfile using the odb functions which are already available generically. If it didn't fail when part of what it needs is missing, I would consider that a bug.

The reason we have for not deferring the check in `odb_pack` is that this is not how git's packed objects work, and that's what we're implementing.

If you have an index file without a corresponding packfile, this is not something which git should consider valid. If you bring in the packfile on-demand, you're implementing a completely different odb backend from what we aim to implement.
