### ISSUE TITLE
libgit2 clone fails on Windows when a file has a long filename

### ISSUE THREAD

**Issue by uluhonolulu** [libgit2/libgit2#1899]
When I try to clone a repository that has a particularly long filename, it fails with the following error:

```
An error was raised by libgit2. Category = Os (Error). Could not open 'D:/websites/3c/86fc4/16739/0x0001/_PublishedWebsites/ChpokkWeb/UserFiles/username_Google/reponame/vNext/Www/lib/wa-cdnhelpers/packages/jQuery.UI.Combined.1.8.11/Content/Content/themes/base/images/ui-bg_flat_0_aaaaaa_40x100.png~51a0892f1c7a2181450dc577e3e20803beafc195' for writing: The system cannot find the path specified.
```

(this is from LibGit2Sharp exception message)

Is there anything that could be done about it? I mean, I know Windows has a limit of 260 chars, but MSDN (http://msdn.microsoft.com/en-us/library/aa365247.aspx#maxpath) suggests you can use extended-lengh paths by just switching to Unicode versions of functions and using the "\?\" prefix.

**Comment by ivstas** [comment]
As of 2017, windows 10 has a setting in registry that allows working with paths longer then 260 symbols. Would you consider re-opening this issue?

**Comment by ethomson** [comment]
@ivstas we have an issue tracking this already at #3053
