### ISSUE TITLE
Deploy to other protocols the reporting of progress transfer when pushing

### ISSUE THREAD

**Issue by nulltoken** [libgit2/libgit2#1902]
#1412 added the basics of progress reporting during push for smart protocol.

The others protocols are a bit jealous and are giving a hard time to smart when no one is watching...

Also see https://github.com/libgit2/libgit2sharp/pull/537#issuecomment-26650431

**Comment by carlosmn** [comment]
Just sent a PR to handle the fetching part of the local transport, which should also send the packing progress to anything listening to it during push.

**Comment by carlosmn** [comment]
With these PRs merged, we now show or report the progress in each direction for local and smart protocol. Feel free to reopen if you notice discrepancies between the reporting and the expectations.

**Comment by nulltoken** [comment]
@dahlbyk IIRC we discussed about this while working on libgit2/libgit2sharp#862. Would you be willing to take a stab at covering it with some test coverage once libgit2/libgit2sharp#1049 is merged?

**Comment by dahlbyk** [comment]
You bet

**Comment by nulltoken** [comment]
@dahlbyk :heart: Have you got already a failing test in mind? :wink:

**Comment by dahlbyk** [comment]
Pretty sure our bug report came out of a test...figured I'd try to bring that back. :grin:
