### ISSUE TITLE
Add support for apply-patch

### ISSUE THREAD

**Issue by ghost** [libgit2/libgit2#1980]
If libgit2 adds support for git's builtin/apply.c, we would be able to use libgit2 (actually I'm more interested in rugged) to apply patches received by email to a git repository.

**Comment by GrahamTheCoder** [comment]
+1

**Comment by epixa** [comment]
+1

For others looking, it looks like https://github.com/libgit2/libgit2/pull/3223 is the latest attempt to get this started.

**Comment by brandonio21** [comment]
Looks like the corresponding PR was closed and this feature is now in master. To close out this task, perhaps add it to the documentation? (I cannot find `git_patch_apply` using the online documentation search function)

**Comment by ethomson** [comment]
#3223 only adds support for reading a patch files into the `git_diff` representation.   There's not yet an API to take a workdir/index/etc and modify it based on that in-memory representation.

**Comment by tiennou** [comment]
Support for this has landed as part of #4705, so this is fixed. Feel free to open issues if you find missing functionality though.
