### ISSUE TITLE
Can not use proxy with password

### ISSUE THREAD

**Issue by Yogu** [libgit2/libgit2#2106]
I have a global config entry like the following:

    http.proxy=http://username:password@proxy.com:8080

libgit2's fetch fails with

> Failed to set proxy: The parameter is incorrect.

The problem is that  [WINHTTP_PROXY_INFO](http://msdn.microsoft.com/en-us/library/aa383912.aspx) does not support authentication for proxies (see also [this question](http://stackoverflow.com/questions/4265427/programmatically-set-proxy-address-port-username-password))

This is bad because official git does support authentication for proxies and thus libgit2 can not perform network operations in perfectly valid git configurations.

**Comment by nulltoken** [comment]
Reopening as it seems that we still **[don't extract the proxy username and password](https://github.com/libgit2/libgit2/blob/master/src/transports/winhttp.c#L318-L349)** from the url that `git_remote__get_http_proxy()` returns

**Comment by fermaem** [comment]
@ethomson Are you still up to take a look at this? This would be a neat addition as currently libgit2 users behind a corporate proxy are compelled to rely on local proxy (eg. cntlm, ntlmaps, ...)

**Comment by nulltoken** [comment]
@ethomson Are you still up to take a look at this? This would be a neat addition as currently libgit2 users behind a corporate proxy are compelled to rely on local proxy (eg. cntlm, ntlmaps, ...)

**Comment by nulltoken** [comment]
@FeodorFitsner In order to ease the implementation of this feature, we were thinking about starting with a failing test. Would you have any idea how we could set up some kind of NTLM proxy during our AppVeyor builds? Would you know any product we could download and install to this purpose?

**Comment by FeodorFitsner** [comment]
Look at this thread: http://help.appveyor.com/discussions/questions/787-simulate-enterprise-proxy

**Comment by nulltoken** [comment]
@FeodorFitsner Awesome! Thanks for the tip

@ethomson There's a chocolatey **[package](https://chocolatey.org/packages/privoxy)** for privoxy (which *looks* like **[supporting](https://www.google.com/?q=privoxy%20ntlm#safe=off&q=privoxy+ntlm)** NTLM). Would that fit our need?

**Comment by nulltoken** [comment]
Hmmm. Not sure Privoxy actually supports user authentication by itself. It supports forwarding up to a parent proxy.

**Comment by nulltoken** [comment]
Another option might be **[DeleGate](http://www.delegate.org/delegate/Manual.htm)** which is also available as a chocolatey **[package](https://chocolatey.org/packages/DeleGate)**.

However, I'd really like someone with proxy skills to take another look at the manual, as I'm a bit out of my depth here.

**Comment by ethomson** [comment]
Right, this is a bullet point that it has session persistence.  NTLM and
Kerberos authenticate the entirety of a kept-alive session.  If you are a
proxy and do not honor this notion, then you will require users to
authenticate for every request (at best).  If you are painfully unaware of
connection affinity, and assume that everything is cookies and basic, then
you will mix up authenticated connections.

It looks like privoxy does not support authentication itself:

> Privoxy itself does not support proxy authentication

says the manual.  Which is a shame.

Does the Appveyor image have a JRE installed?  If so, I may be able to make
something work.

**Comment by nulltoken** [comment]
@ethomson http://www.appveyor.com/docs/installed-software states that the following are installed:

Java SE Development Kit (JDK)
- JDK 1.7 x64 (C:\Program Files\Java\jdk1.7.0\bin - default in PATH)
- JDK 1.7 x86 (C:\Program Files (x86)\Java\jdk1.7.0\bin)
- JDK 1.8 x64 (C:\Program Files\Java\jdk1.8.0)
- JDK 1.8 x86 (C:\Program Files (x86)\Java\jdk1.8.0)

**Comment by ethomson** [comment]
OK, I think I have a proxy that I can bring to the party that I've used for testing previously.

**Comment by voltagex** [comment]
I've also tried setting up squid with ntlm_fakeauth via
http://wiki.squid-cache.org/ConfigExamples/Authenticate/LoggingOnly but
something goes wrong and the connection is terminated (at least with curl)

**Comment by carlosmn** [comment]
I started looking into it, and while we can have a guess that a server will support Basic, it opens up a can of worms about whether people do want to have their password in plaintext or whether a program/user would prefer to be asked for them as needed, possibly using the same cred callbacks we already have for the endpoint.

It also opens up whether we'd like to allow the user to specify the want NTLM auth or what.

**Comment by carlosmn** [comment]
Fixed as part of #3110 we now extract the auth info from caller- or config-provided urls.
