### ISSUE TITLE
apache fork user: Error stat'ing config file '/root/.gitconfig'

### ISSUE THREAD

**Issue by kocian** [libgit2/libgit2#2122]
openning repo under apache fork with the switched user using mod_python ends up with "Error stat'ing config file '/root/.gitconfig'"

example of this problem using mod_python and apache can  be found https://github.com/libgit2/pygit2/issues/339#issuecomment-34852252

c code thanks to @jdavid:

```
#include <git2.h>
#include <stdio.h>

int
main()
{
    git_repository *repo;
    int err;
    const git_error *error;

    setuid(1000);
    err = git_repository_open(&repo, "/path/to/repo");
    if (err < 0) {
        error = giterr_last();
        printf("Error %d: %s\n", err, error->message);
    }
    return err;
}
```

**Comment by b35li** [comment]
@carlosmn  I ran into this issue,  the title of this issue is my error message. So I have to make a local patch for this, but I cannot find the 2bd131b and 2f569c6 in the repo of libgit. Why?

**Comment by carlosmn** [comment]
If those commits aren't there, then they were never integrated into the history. Commits get rewritten often before they reach the mainline.
