### ISSUE TITLE
git_stash_save() considers the whole working directory to be untracked

### ISSUE THREAD

**Issue by jspahrsummers** [libgit2/libgit2#2427]
This doesn't occur consistently, but sometimes invoking `git_stash_save()` with `GIT_STASH_INCLUDE_UNTRACKED` will result in a stash that contains _everything_ from the working directory (recursively). I'm not sure exactly where the breakdown is, but it seems like `git_diff_tree_to_workdir` is considering `HEAD` to be the empty tree.

Looking at the stash commit directly, I can see that:

 * The base commit is correct
 * The index commit is empty (which is correct here)
 * The untracked files commit contains everything in working directory—including tracked files—as additions, like they didn't exist at all before

**Comment by ethomson** [comment]
@jspahrsummers - I've been going through old issues.  Is this still happening for you?

**Comment by jspahrsummers** [comment]
@ethomson I'm not sure, and can't easily get to a state where I could reproduce it. We had to switch to the `git stash` plumbing commands instead, because of this bug. :confused:

**Comment by ethomson** [comment]
I'm going to close this as we've changed a _lot_ since it was reported.  A few other users are using stash and have not reported this behavior, so it may be fixed or it may have been application-specific or specific to Objective Git.
