### ISSUE TITLE
[ANNOUNCE] New Development Rooles

### ISSUE THREAD

**Issue by vmg** [libgit2/libgit2#2433]
HELLO.

0.21.0 has just shipped. Here are two minor changes to the way we're going to work on the next release (0.22.0):

- Enough headaches with `development` already. The `master` branch is now the main branch where development happens. The release has been tagged on that branch; if we need to backport a critical bug for this release, we'll branch `0.21.0-maint` off that.

- I'll be manually merging existing PRs to `master` from the CLI to avoid the hassle of having to re-target them. Please target `master` on your PRs from now on, however.

- There's a CHANGELOG.md in the root of the repository now. All PRs that add major features or change APIs must update it. Because I'm a spoiled kid and I don't want to hunt down the actual changelog between releases.

- I'll be manually updating the changelog for the existing PRs. Please make sure your PRs from now on have a changelog entry or they won't be merged.

Happy developing. Please don't hate me.

cc @arrbee @carlosmn @ethomson @phkelley and so on

**Comment by carlosmn** [comment]
I think it's safe to close this now.
