### ISSUE TITLE
Is libgit2 threadsafe with gcc 4.4 on linux?

### ISSUE THREAD

**Issue by twekel** [libgit2/libgit2#2491]
I am working on an application which is interested in using libgit2 in a multi-threaded C/C++ CentOS 6, gcc 4.4, 64 bit environment.  I found a two year old posting which seems to indicate that libgit2 is stable https://github.com/libgit2/libgit2/issues/477.  Recent commits to GitHub are also related to improved multithreaded behavior.

I have a couple of questions related to libgit2 multithreading:

Is libgit2 version 0.21 100% thread safe in our target environment with the THREADSAFE cmake option turned on?

Are there any limitations or provisos on thread safety?

**Comment by mars-liulin** [comment]
@carlosmn  
Sorry to talk about the closed issue.
I'm reading the libgit2 source, it's grace and concise. 
But I found it may be not threadsafe for refs. I don't find any lock in refs update process. 
I worry about when two concurren requests want to update the same refs, one of both would be overrid.

**Comment by carlosmn** [comment]
libgit2 does not protect against the user using objects from different threads at the same time, this is not something that's reasonable for us to cover. See [the documentation](https://github.com/libgit2/libgit2/blob/master/THREADING.md) for what we do guarantee.

Updating a reference does take a lock on the reference itself, so it is safe to update concurrently from different processes, or even from different threads, as long as you use a different `git_repository` instance on each thread.

**Comment by mars-liulin** [comment]
@carlosmn 
Thanks for your reply.
Sorry, maybe my description is not accurate. I'll explain in detail:
The reference will write to refdb for persistence.
The sample flow: git_reference__update_for_commit => reference__create => git_refdb_write.
When the refdb-backend is fs,  the branch object will write to a file for recoding the last commit sha1, the file would be updated for next commit. (e.g: refs/heads/master)
So the refdb could update and it is mutable. 
If there is no lock for the updating process, it would be occur the overridden case.
For example:
There is git repo named disney.git. 
The commit short sha1 of the disney.git master branch is abc123.
Then Tom want to add a commit to master branch, this new commit sha1 is bcd234 and the parent sha1 is abc123.
At the same time Jerry concurrently want to add a commit to master branch too, this new commit sha1 is cdd345 and the parent sha1 is also abc123.
It‘s possible to occur the case that Tom and Jerry are both success for adding commit to master branch, but master branch updated to cdd345 , Jerry's commit overrode Toms, Tom's commit has lost.(poor Tom)

**Comment by carlosmn** [comment]
This cannot happen. When we update a reference, we take the old value into account (you can do this yourself via [`git_reference_set_target`](https://libgit2.github.com/libgit2/#v0.23.0/group/reference/git_reference_set_target) or [`git_reference_create_matching`](https://libgit2.github.com/libgit2/#v0.23.0/group/reference/git_reference_create_matching) but we do it with the internal methods).

Also note the documentation for [`git_commit_create`](https://libgit2.github.com/libgit2/#v0.23.0/group/commit/git_commit_create) mentions this condition in its description of the reference to update.

**Comment by ethomson** [comment]
Indeed.  Further, if you have questions about how to use libgit2, we recommend [StackOverflow](www.stackoverflow.com) as we like to keep the issues for bug reports.

(In particular, we would prefer it if you did not comment on old, closed issues.)

Thanks!

**Comment by mars-liulin** [comment]
@carlosmn 
Sorry, you are right ! This cannot happen ! It's threadsafe!
I've found the lock and check process in refdb_fs_backend__write.

**Comment by mars-liulin** [comment]
@ethomson 
Sorry, I'll flow the rule later.
