### ISSUE TITLE
Index updates vs. submodules

### ISSUE THREAD

**Issue by tiennou** [libgit2/libgit2#2514]
I'm trying to port GitX index-wrangling code over to Objective-Git, and I'm getting back an error when calling (indirectly) `git_index_update_all` : "Failed to read file into stream: Is a directory". After taking a closer look, that error happens [here](https://github.com/libgit2/libgit2/blob/master/src/index.c#L2520) because the path being processed is actually a changed submodule and not a plain file, so the update fails.

Am I'm doing it wrong, or is it not handled ?

**Comment by carlosmn** [comment]
Is this issue still relevant?

**Comment by tiennou** [comment]
Yep, just checked and it still chokes on submodules.

**Comment by carlosmn** [comment]
Fixed (a while ago) via #3303
