### ISSUE TITLE
Proxy support for non-winhttp connections

### ISSUE THREAD

**Issue by alexcrichton** [libgit2/libgit2#2555]
I noticed today that the winhttp transport backend supports proxying HTTP requests, and I was curious if this was planned to be supported in libgit2 by default. If not, is it possible to get a handle to something like `git_remote__get_http_proxy` and implement a custom transport?

**Comment by carlosmn** [comment]
Once #3183 and #3110 are fleshed out, it should be possible to set exactly what kind of proxy you'd like to use (assuming curl supports it).

**Comment by carlosmn** [comment]
If curl is installed on the system, we now use it by default, so we can support HTTP proxies both from the git configuration or curl will take it fro the environment.

Run-time configuration isn't there yet, but it doesn't look like many programs actually would use that.

**Comment by carlosmn** [comment]
Fixed with #3110 which now lets the caller configure the proxy.
