### ISSUE TITLE
Implement fetch + prune

### ISSUE THREAD

**Issue by calavera** [libgit2/libgit2#2576]
@carlosmn outlined in https://github.com/libgit2/libgit2/issues/1179#issuecomment-12072320 how `update_tips` could be used to prune deleted branches from local on fetching operations. It would make me really happy to see this implemented.

I could try to implemented myself but I'm not super familiar with the source. Although, any help in the form of comments, hints or pseudo-code would also be really appreciated.

/cc @vmg, @arrbee

**Comment by carlosmn** [comment]
Finally implemented with #2761
