### ISSUE TITLE
FTBFS On some archs

### ISSUE THREAD

**Issue by ltworf** [libgit2/libgit2#2580]
On some Linux architectures and on hurd and freebsd, some tests are failing

https://buildd.debian.org/status/package.php?p=libgit2&suite=unstable

I am reporting this because I subsurface in Debian is stuck in unstable, because this library doesn't build on all of the architectures.

**Comment by carlosmn** [comment]
Version 0.21 isn't supported anymore, so I'm closing this issue. There's a few patches which shouldn't present any issues to backport to get more information about the actual errors and allowing for bind-mount points, #3171, #3132 and the fixup #3185
