### ISSUE TITLE
CMake Error: Files In Proper Folder Structure But Still Error

### ISSUE THREAD

**Issue by enemyOfState** [libgit2/libgit2#2602]
trying to make files with suggested line:
cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_SHARED_LIBS=OFF -DBUILD_CLAR=OFF -DCMAKE_C_FLAGS=-fPIC ..

get errors:
CMake Error at CMakeLists.txt:21 (INCLUDE):
include could not find load file:

AddCFlagIfSupported
CMake Error at CMakeLists.txt:124 (FILE):
file STRINGS file
"/php-git-develop/libgit2/include/git2/version.h"
cannot be read.

CMake Error at CMakeLists.txt:131 (FILE):
file STRINGS file
"/php-git-develop/libgit2/include/git2/version.h"
cannot be read.

CMake Warning at CMakeLists.txt:146 (FIND_PACKAGE):
Could not find module FindHTTP_Parser.cmake or a configuration file for
package HTTP_Parser.

Adjust CMAKE_MODULE_PATH to find FindHTTP_Parser.cmake or set
HTTP_Parser_DIR to the directory containing a CMake configuration file for
HTTP_Parser. The file will have one of the following names:

HTTP_ParserConfig.cmake
http_parser-config.cmake
-- http-parser was not found or is too old; using bundled 3rd-party sources.
CMake Warning at CMakeLists.txt:203 (FIND_PACKAGE):
Could not find module FindLIBSSH2.cmake or a configuration file for package
LIBSSH2.

Adjust CMAKE_MODULE_PATH to find FindLIBSSH2.cmake or set LIBSSH2_DIR to
the directory containing a CMake configuration file for LIBSSH2. The file
will have one of the following names:

LIBSSH2Config.cmake
libssh2-config.cmake
CMake Error at CMakeLists.txt:326 (ADD_C_FLAG_IF_SUPPORTED):
Unknown CMake command "ADD_C_FLAG_IF_SUPPORTED".

-- Configuring incomplete, errors occurred!

**Comment by arielb2** [comment]
Hello.
Just for the record.
I had the same error, the solution was to install the development packages.
Fedora:
# dnf -y install openssl-devel
# dnf -y install libssh2-devel
# dnf -y install http-parser-devel
