### ISSUE TITLE
Another CRLF issue

### ISSUE THREAD

**Issue by csware** [libgit2/libgit2#2651]
There seems to be another CRLF issue in 24deacb7ee7d4c77eaa4606afb21988d9fae8aa2.

Take the following file (LANG=JA, EOL=CRLF, ENCODE=UTF8+BOM; encoded in hex here to avoid transfer encoding issues):
EFBBBF4C414E473D4A412C20454F4C3D43524C462C20454E434F44453D555446382B424F4D0D0AE38193E38293E381ABE381A1E381AF0D0AE38193E38293E381B0E38293E381AF0D0A

At best set AUTOCRLF=true, clone https://github.com/csware/crlf-issue.git (and perform reset to HEAD) using libgit2 and you'll see the problem.

(msys)git behaves correctly and applies CRLF to the file when checking out.

**Comment by ethomson** [comment]
I'm going to close this issue, since it's now got a pull request to fix it.  Thanks to both of you for the report and all the fixes!
