### ISSUE TITLE
pushing to non-existing remote branch fails without force flag

### ISSUE THREAD

**Issue by theseion** [libgit2/libgit2#2664]
Pushing to a remote branch that doesn't exist yet with a refspec like `master:refs/heads/foo` raises `GIT_ENONFASTFORWARD` with "Cannot push non-fastforwardable reference" (push.c:373). The same works when using Git. To make it work with libgit2 one has to supply the force flag like so: `+master:refs/heads/foo`.

**Comment by ethomson** [comment]
@theseion do you still believe this to be a problem?  If so, can you provide some failing sample code?  Thanks!

**Comment by theseion** [comment]
@ethomson The bindings are in Smalltalk but I can try to come up with a minimal C program that will demonstrate the issue, if that helps. If this issue still persists (which I can't check right now) then yes, I think it should be fixed. Creating a new branch should not require the force flag (as stated above, Git allows this).

**Comment by theseion** [comment]
Ok, wow. I'm really sorry... I just realised that my test doesn't clean up the branch. So when I run it a second time the branch of course already exists. *face palm*. So much for proper research before submitting a bug report...

**Comment by ethomson** [comment]
No problem, thanks for the update!
