### ISSUE TITLE
Explain how to build libgit2 with libssh2 to enable SSH transport protocol

### ISSUE THREAD

**Issue by swisspol** [libgit2/libgit2#2665]
AFAIK it's not in https://github.com/libgit2/libgit2 or https://libgit2.github.com/docs/guides/build-and-link/: it's just mentioned in passing you need libssh2. It took me some time to figure out.

On OS X at least, one needs to download libssh2 from http://www.libssh2.org/ and build it (static library is best), then follow the instructions to build libgit2 with cmake but do this before calling cmake:
```sh
export CMAKE_INCLUDE_PATH="path/to/libssh2/include"
export CMAKE_LIBRARY_PATH="path/to/libssh2/lib"
```

**Comment by keeth** [comment]
A nit I had trying to build libgit2 with libssh2 on a minimal ubuntu instance, if pkg-config is missing, cmake silently fails to find libssh2, even if it is installed in the right place.

**Comment by swisspol** [comment]
Yes that's a significant problem that libssh2 support can be silently omitted. At the minimum I think the makefile should display if libssh2 is being used or not.
