### ISSUE TITLE
backslashes in .gitmodules path values not handled properly on Windows

### ISSUE THREAD

**Issue by jeffhostetler** [libgit2/libgit2#2706]
Doing a "git submodule add" with a path containing backslashes causes the entry in the .gitmodules file to have backslashes.

The code in libgit2 to populate submodules cache during the first git_submodule_foreach() parses the .gitmodules file and then scans the working directory to build a [name, path] dictionary.

Libgit2 does not normalize the path value (with forward slashes) when reading the .gitmodules file, so the cache/dictionary contains a [name, backslash_path] pair.

When the WD is scanned and the on-disk submodule is observed, a [forward_path, forward_path] pair is *ALSO* added to the cache.

A suggested fix would be in submodule.c in submodule_load_from_config() to normalize the value when the key is "path" before using it to create/update the cache/dictionary.

**Comment by carlosmn** [comment]
I'm going to consider this fixed by #3307; shout if that's not right.
