### ISSUE TITLE
git_libgit2_init in documentation

### ISSUE THREAD

**Issue by cseri** [libgit2/libgit2#2731]
The importance `git_libgit2_init` (or `git_threads_init`) should be mentioned in the documentation, especially now, that the threadsafe build is the default.

e.g. in the [101 samples](https://libgit2.github.com/docs/guides/101-samples/) and/or in `THREADING.md`

**Comment by whyka** [comment]
As in api reference
https://libgit2.github.com/libgit2/#HEAD/group/libgit2/git_libgit2_init
```
returns
int	the number of initializations of the library, or an error code.
```
How to identify when an error occurred?

**Comment by carlosmn** [comment]
The same way as with every other function call. If the return value is negative, that indicates an error.
