### ISSUE TITLE
libgit2 possible crash in pack_entry_find_offset()

### ISSUE THREAD

**Issue by linquize** [libgit2/libgit2#2737]
libgit2: v0.21.0-404-ga6ed1fc, 64-bit
Windows 8.1

Stack trace:
pack_entry_find_offset(__int64 * offset_out, git_oid * found_oid, git_pack_file * p, const git_oid * short_oid, unsigned __int64 len) Line 1311
git_pack_entry_find(git_pack_entry * e, git_pack_file * p, const git_oid * short_oid, unsigned __int64 len) Line 1346
pack_entry_find(git_pack_entry * e, pack_backend * backend, const git_oid * oid) Line 261
pack_backend__read(void * * buffer_p, unsigned __int64 * len_p, git_otype * type_p, git_odb_backend * backend, const git_oid * oid) Line 406
git_odb_read(git_odb_object * * out, git_odb * db, const git_oid * id) Line 776
git_object_lookup_prefix(git_object * * object_out, git_repository * repo, const git_oid * id, unsigned __int64 len, git_otype type) Line 168
git_tree_entry_to_object(git_object * * object_out, git_repository * repo, const git_tree_entry * entry) Line 281

**Comment by ethomson** [comment]
Please feel free to reopen if you have a minidump or something.  Thanks!
