### ISSUE TITLE
Final stage of building on Visual 2012 with libssh2

### ISSUE THREAD

**Issue by TheKingOfAtlantis** [libgit2/libgit2#2754]
# Introduction

I am using Visual Studio Express 2012
The issue occurs during the linking stage it consists of a lot of unresolved external references/symbols mainly related to `ssh.obj`.

I have rebuilt, cleaned and re-downloaded everything multiple times, and i always get the same problem

I have used cmake and I have built libssh2 and zlib myself as well
# Versions used

libgit2: 0.21.2
libssh2: 1.4.3
zlib: 1.2.8
# Log

> 1>------ Skipped Build: Project: RUN_TESTS, Configuration: Debug x64 ------
> 1>Project not selected to build for this solution configuration 
> 2>------ Build started: Project: git2, Configuration: Debug x64 ------
> 3>------ Build started: Project: libgit2_clar, Configuration: Debug x64 ------
> 2>     Creating library C:/Users/sulaiman/Workspace/flowingGit/Libraries/libgit2/build/Debug/git2.lib and object C:/Users/sulaiman/Workspace/flowingGit/Libraries/libgit2/build/Debug/git2.exp
> 2>filebuf.obj : error LNK2019: unresolved external symbol deflate referenced in function write_deflate
> 2>zstream.obj : error LNK2001: unresolved external symbol deflate
> 2>filebuf.obj : error LNK2019: unresolved external symbol deflateEnd referenced in function git_filebuf_cleanup
> 2>zstream.obj : error LNK2001: unresolved external symbol deflateEnd
> 2>filebuf.obj : error LNK2019: unresolved external symbol deflateInit_ referenced in function git_filebuf_open
> 2>zstream.obj : error LNK2001: unresolved external symbol deflateInit_
> 2>indexer.obj : error LNK2019: unresolved external symbol crc32 referenced in function crc_object
> 2>odb_loose.obj : error LNK2019: unresolved external symbol inflate referenced in function start_inflate
> 2>pack.obj : error LNK2001: unresolved external symbol inflate
> 2>odb_loose.obj : error LNK2019: unresolved external symbol inflateEnd referenced in function finish_inflate
> 2>pack.obj : error LNK2001: unresolved external symbol inflateEnd
> 2>odb_loose.obj : error LNK2019: unresolved external symbol inflateInit_ referenced in function start_inflate
> 2>pack.obj : error LNK2001: unresolved external symbol inflateInit_
> 2>zstream.obj : error LNK2019: unresolved external symbol deflateReset referenced in function git_zstream_reset
> 2>ssh.obj : error LNK2019: unresolved external symbol libssh2_session_init_ex referenced in function _git_ssh_session_create
> 2>ssh.obj : error LNK2019: unresolved external symbol libssh2_session_abstract referenced in function _git_ssh_authenticate_session
> 2>ssh.obj : error LNK2019: unresolved external symbol libssh2_session_startup referenced in function _git_ssh_session_create
> 2>ssh.obj : error LNK2019: unresolved external symbol libssh2_session_free referenced in function ssh_stream_free
> 2>ssh.obj : error LNK2019: unresolved external symbol libssh2_session_last_error referenced in function ssh_error
> 2>ssh.obj : error LNK2019: unresolved external symbol libssh2_userauth_password_ex referenced in function _git_ssh_authenticate_session
> 2>ssh.obj : error LNK2019: unresolved external symbol libssh2_userauth_publickey_fromfile_ex referenced in function _git_ssh_authenticate_session
> 2>ssh.obj : error LNK2019: unresolved external symbol libssh2_userauth_publickey referenced in function _git_ssh_authenticate_session
> 2>ssh.obj : error LNK2019: unresolved external symbol libssh2_userauth_keyboard_interactive_ex referenced in function _git_ssh_authenticate_session
> 2>ssh.obj : error LNK2019: unresolved external symbol libssh2_channel_open_ex referenced in function _git_ssh_setup_conn
> 2>ssh.obj : error LNK2019: unresolved external symbol libssh2_channel_process_startup referenced in function send_command
> 2>ssh.obj : error LNK2019: unresolved external symbol libssh2_channel_read_ex referenced in function ssh_stream_read
> 2>ssh.obj : error LNK2019: unresolved external symbol libssh2_channel_write_ex referenced in function ssh_stream_write
> 2>ssh.obj : error LNK2019: unresolved external symbol libssh2_session_set_blocking referenced in function _git_ssh_session_create
> 2>ssh.obj : error LNK2019: unresolved external symbol libssh2_channel_set_blocking referenced in function _git_ssh_setup_conn
> 2>ssh.obj : error LNK2019: unresolved external symbol libssh2_channel_close referenced in function ssh_stream_free
> 2>ssh.obj : error LNK2019: unresolved external symbol libssh2_channel_free referenced in function ssh_stream_free
> 2>ssh.obj : error LNK2019: unresolved external symbol libssh2_agent_init referenced in function ssh_agent_auth
> 2>ssh.obj : error LNK2019: unresolved external symbol libssh2_agent_connect referenced in function ssh_agent_auth
> 2>ssh.obj : error LNK2019: unresolved external symbol libssh2_agent_list_identities referenced in function ssh_agent_auth
> 2>ssh.obj : error LNK2019: unresolved external symbol libssh2_agent_get_identity referenced in function ssh_agent_auth
> 2>ssh.obj : error LNK2019: unresolved external symbol libssh2_agent_userauth referenced in function ssh_agent_auth
> 2>ssh.obj : error LNK2019: unresolved external symbol libssh2_agent_disconnect referenced in function ssh_agent_auth
> 2>ssh.obj : error LNK2019: unresolved external symbol libssh2_agent_free referenced in function ssh_agent_auth
> 2>C:\Users\sulaiman\Workspace\flowingGit\Libraries\libgit2\build\Debug\git2.dll : fatal error LNK1120: 32 unresolved externals
> 3>     Creating library C:/Users/sulaiman/Workspace/flowingGit/Libraries/libgit2/build/Debug/libgit2_clar.lib and object C:/Users/sulaiman/Workspace/flowingGit/Libraries/libgit2/build/Debug/libgit2_clar.exp
> 3>odb_loose.obj : error LNK2019: unresolved external symbol inflate referenced in function start_inflate
> 3>pack.c.obj : error LNK2001: unresolved external symbol inflate
> 3>zstream.c.obj : error LNK2001: unresolved external symbol inflate
> 3>odb_loose.obj : error LNK2019: unresolved external symbol inflateEnd referenced in function finish_inflate
> 3>pack.c.obj : error LNK2001: unresolved external symbol inflateEnd
> 3>zstream.c.obj : error LNK2001: unresolved external symbol inflateEnd
> 3>odb_loose.obj : error LNK2019: unresolved external symbol inflateInit_ referenced in function start_inflate
> 3>pack.c.obj : error LNK2001: unresolved external symbol inflateInit_
> 3>zstream.c.obj : error LNK2001: unresolved external symbol inflateInit_
> 3>ssh.obj : error LNK2019: unresolved external symbol libssh2_session_init_ex referenced in function _git_ssh_session_create
> 3>ssh.obj : error LNK2019: unresolved external symbol libssh2_session_abstract referenced in function _git_ssh_authenticate_session
> 3>ssh.obj : error LNK2019: unresolved external symbol libssh2_session_startup referenced in function _git_ssh_session_create
> 3>ssh.obj : error LNK2019: unresolved external symbol libssh2_session_free referenced in function ssh_stream_free
> 3>ssh.obj : error LNK2019: unresolved external symbol libssh2_session_last_error referenced in function ssh_error
> 3>ssh.obj : error LNK2019: unresolved external symbol libssh2_userauth_password_ex referenced in function _git_ssh_authenticate_session
> 3>ssh.obj : error LNK2019: unresolved external symbol libssh2_userauth_publickey_fromfile_ex referenced in function _git_ssh_authenticate_session
> 3>ssh.obj : error LNK2019: unresolved external symbol libssh2_userauth_publickey referenced in function _git_ssh_authenticate_session
> 3>ssh.obj : error LNK2019: unresolved external symbol libssh2_userauth_keyboard_interactive_ex referenced in function _git_ssh_authenticate_session
> 3>ssh.obj : error LNK2019: unresolved external symbol libssh2_channel_open_ex referenced in function _git_ssh_setup_conn
> 3>ssh.obj : error LNK2019: unresolved external symbol libssh2_channel_process_startup referenced in function send_command
> 3>ssh.obj : error LNK2019: unresolved external symbol libssh2_channel_read_ex referenced in function ssh_stream_read
> 3>ssh.obj : error LNK2019: unresolved external symbol libssh2_channel_write_ex referenced in function ssh_stream_write
> 3>ssh.obj : error LNK2019: unresolved external symbol libssh2_session_set_blocking referenced in function _git_ssh_session_create
> 3>ssh.obj : error LNK2019: unresolved external symbol libssh2_channel_set_blocking referenced in function _git_ssh_setup_conn
> 3>ssh.obj : error LNK2019: unresolved external symbol libssh2_channel_close referenced in function ssh_stream_free
> 3>ssh.obj : error LNK2019: unresolved external symbol libssh2_channel_free referenced in function ssh_stream_free
> 3>ssh.obj : error LNK2019: unresolved external symbol libssh2_agent_init referenced in function ssh_agent_auth
> 3>ssh.obj : error LNK2019: unresolved external symbol libssh2_agent_connect referenced in function ssh_agent_auth
> 3>ssh.obj : error LNK2019: unresolved external symbol libssh2_agent_list_identities referenced in function ssh_agent_auth
> 3>ssh.obj : error LNK2019: unresolved external symbol libssh2_agent_get_identity referenced in function ssh_agent_auth
> 3>ssh.obj : error LNK2019: unresolved external symbol libssh2_agent_userauth referenced in function ssh_agent_auth
> 3>ssh.obj : error LNK2019: unresolved external symbol libssh2_agent_disconnect referenced in function ssh_agent_auth
> 3>ssh.obj : error LNK2019: unresolved external symbol libssh2_agent_free referenced in function ssh_agent_auth
> 3>filebuf.c.obj : error LNK2019: unresolved external symbol deflate referenced in function write_deflate
> 3>zstream.c.obj : error LNK2001: unresolved external symbol deflate
> 3>filebuf.c.obj : error LNK2019: unresolved external symbol deflateEnd referenced in function git_filebuf_cleanup
> 3>zstream.c.obj : error LNK2001: unresolved external symbol deflateEnd
> 3>filebuf.c.obj : error LNK2019: unresolved external symbol deflateInit_ referenced in function git_filebuf_open
> 3>zstream.c.obj : error LNK2001: unresolved external symbol deflateInit_
> 3>indexer.c.obj : error LNK2019: unresolved external symbol crc32 referenced in function crc_object
> 3>zstream.c.obj : error LNK2019: unresolved external symbol deflateReset referenced in function git_zstream_reset
> 3>C:\Users\sulaiman\Workspace\flowingGit\Libraries\libgit2\build\Debug\libgit2_clar.exe : fatal error LNK1120: 32 unresolved externals
> 4>------ Skipped Build: Project: INSTALL, Configuration: Debug x64 ------
> 4>Project not selected to build for this solution configuration 
> ========== Build: 0 succeeded, 2 failed, 2 up-to-date, 2 skipped ==========

I have searched everywhere for answer to solve this problem however i couldn't find one

Thanks

**Comment by jimtut** [comment]
Could you post the cmake command you used?
