### ISSUE TITLE
0.21.3 (and current master) fails to build with mingw

### ISSUE THREAD

**Issue by tkelman** [libgit2/libgit2#2766]
Any flavor, mingw32 or mingw-w64. Here's a log of a cross-compile from Ubuntu 14.04: https://gist.github.com/4f3b42623992fc57a771

Adding `#include <wchar.h>` to `src/win32/path_w32.h` helps, but doesn't resolve the `error: subscripted value is neither array nor pointer nor vector` from `src/win32/findfile.c`.

**Comment by johnhaley81** [comment]
Is there a reason why it's not brought over into the 0.21 branch? This is a blocking issue for us to update nodegit to this version.

**Comment by tkelman** [comment]
@johnhaley81 I did so in #2770, is there more recent breakage?

**Comment by johnhaley81** [comment]
Nope, that's perfect! I was looking specifically at 0.21.3 so I missed that. I'll just wait for the version bump and we'll be good. Thanks!

**Comment by tkelman** [comment]
I don't know whether npm lets you apply patches easily, if so https://github.com/JuliaLang/julia/blob/9d0b866a51f1d10ce78e80692b82dbb2aaf9db43/deps/libgit2-0.21.3-mingw.patch works for 0.21.3 for me (that's in an MIT-licensed repo).

And i thought node-land was all MSVC on Windows?

**Comment by johnhaley81** [comment]
We're manually building libgit2 using node-gyp and msbuild is freaking out about that `wchar_t`. In our setup we can manually point to a commit to pull from so I could do that if I wanted to.

If 0.21.4 is going to land soon though I can wait for that.

**Comment by ethomson** [comment]
I think that 0.21.4 is going to land very soon indeed.  (We haven't had much feedback on the RC, which is a very positive sign.)

**Comment by tkelman** [comment]
Don't know whether this is of use to anyone but me, but figured I'd mention that I've been cross-compiling libgit2 Windows dll's from the openSUSE build service: https://build.opensuse.org/package/show/windows:mingw:win64/mingw64-libgit2
