### ISSUE TITLE
Release v0.22 and v0.21.4

### ISSUE THREAD

**Issue by carlosmn** [libgit2/libgit2#2780]
'This the season for giving, and we really should get a release out. There's some fixes for the current release in the maint branch so we should release those too.

- v0.21.4
  - [x] See if there's anything else we should backport
  - [x] Check for leaks
  - [x] Bump the version number
- v0.22
  - [x] Merge/resolve issues tagged
  - [x] Check for leaks
  - [x] Fill in CHANGELOG if we've missed something
  - [x] Change the header in CHANGELOG and add the new one
  - [x] Choose a release name
  - [x] Bump version and SOVERSION
 - [x] Create the `maint/v0.22` branch

**Comment by carlosmn** [comment]
The first release candidate is out. The release name will be "Las Canteras"

**Comment by jspahrsummers** [comment]
> The release name will be "Las Canteras"

:star2:

**Comment by aspiers** [comment]
ICBW but it looks to me like the `git_describe_*` stuff is missing from the `CHANGELOG` and from the `v0.22.0-rc1` tag.

**Comment by carlosmn** [comment]
This was released yesterday. Thanks to everyone who contributed.
