### ISSUE TITLE
Shallow Clone

### ISSUE THREAD

**Issue by antis81** [libgit2/libgit2#2782]
As discussed in issue #1142, shallow clones are not supported yet by the libgit2 clone API.

One can work around this by initializing a repository, setting the `core.depth` variable in the config, setup a remote etc. But ... it does not work with `git_clone()`.

IMHO the `git_clone_options` struct should be extended by an `unsigned int depth` variable, which in turn is given to `git_clone()` to setup the `--depth` config variable.

Also referencing issue #1430 - just for the record.

Thanks for all the support this far and merry christmas to y'all.

EDIT: The remote alias `"origin"` is also set in `create_and_configure_origin()`. This should be an option as well.

How about adding a `git_remote *remote` member in `git_clone_options`, that would allow to manually setup a customized remote?

**Comment by heavensrevenge** [comment]
The https://github.com/creationix/jsgit tool which uses https://github.com/creationix/js-git as a backend while using node v0.11.5 http://nodejs.org/dist/v0.11.5/ acually does a shallow copy clone of a git repository.
Newer versions of node don't seem to allow the command to succeed and you need to call the command like ```jsgit-fetch --depth 5 git://github.com/creationix/jsgit.git```

It's the only git "reimplementation" I've found which actually succeeds in a shallow clone so maybe you can use it as an example to add the capability in libgit2 as I'm interested in https://github.com/rust-lang/cargo/issues/1171 benefitting from how amazingly useful a shallow clone could be for build purposes.

**Comment by carlosmn** [comment]
#3058 lists what we would need to support/do and is the issue where any discussion on it should happen, rather than an issue asking for the non-existent feature to be exposed.
