### ISSUE TITLE
Issues with git_rebase API

### ISSUE THREAD

**Issue by swisspol** [libgit2/libgit2#2791]
*I'm putting all these in a single issue since they are related and are probably worth looking it at together.*

**1)** `git_rebase_init()` doesn't match the Git CLT parameter behavior which says `If <branch> is specified, git rebase will perform an automatic git checkout <branch> before doing anything else. Otherwise it remains on the current branch.`

With `git_rebase_init()`, you have to pass `branch`, which is the first difference (`NULL` is not accepted unless `onto` is not `NULL` itself which is also different from Git CLT), and then it doesn't check it out, but call instead `git_checkout_head()`.

If you wanted to reproduce the Git CLT behavior, one would need to add extra boilerplate code like this:
- Retrieve the current branch and pass it to `git_rebase_init()` to emulate not specifying `<branch>`
- Call `git_repository_set_head()` to set the HEAD to `<branch>` and pass that same `<branch` to  `git_rebase_init()` which will then do the checkout

**2)** `git_rebase_init()` does a forced checkout with `GIT_CHECKOUT_FORCE` while Git CLT does a regular checkout according to the docs.

**3)** When using the `git_rebase_init()`, the order in the list of commits to apply will not be deterministic considering it's built using `git_revwalk_sorting(revwalk, GIT_SORT_REVERSE | GIT_SORT_TIME)`:
- Time sorting will not work correctly for commits generated on file systems without subsecond resolution (related to #2703).
- The ordering is time based vs being based on the more logical and guaranteed-to-be-stable "ORIG_HEAD -> parent -> grandparent...".

**4)** `rebase_init_operations()` is silently skipping merge commits and there are no comments explaining this behavior: is this what Git CLT does?

@ethomson let me know what you think of all this, happy to be proven wrong :)

**Comment by ethomson** [comment]
1. Yes, that seems reasonable to me.  The library is generally more flexible than the git porcelain commands are.  (Not everybody wants to emulate the command-line interface.)

2. I agree that this should probably simply be `SAFE`, but is this actually causing you problems?  The index and workdir must be clean for us to even do the checkout (see `rebase_ensure_not_dirty`).

3. The granularity of a commit's time is a second, so let's discount (a) as that's talking about a specific issue with status.  It's possible that we're not matching git core here, do you have a repository that is getting sorted differently between the two implementations?

4. Yes, `git-rebase` skips merges without the `--preserve-merges` flag.  We emulate this behavior.

**Comment by swisspol** [comment]
1) When you say "The library is generally more flexible than the git porcelain commands are." I can only agree but would argue this in this very case, libgit2 is striking an odd in-between behavior: either it's low-level and you must pass all 3 parameters and it's the responsibility of the caller to make sure things are in the right state e.g. proper workdir and HEAD or it's more high-level and you can pass none at all exactly like `git rebase` CLT and libgit2 figures out the reasonable defaults.

Like I described in my example above, the fact I have to both call `git_repository_set_head()` with `branch` and then pass `branch` again to `git_rebase_init()` to work around how it's internals work is not "clean" API impedance and more complex than needed IMO.

The other thing is that in absence of documentation pointing out either how the implementation works (like "this API checks out the HEAD then does X and Y") or its differences with `git rebase` CLT, then API users are left to assume it works and behaves like the CLT.

One pattern I find very good in libgit2 is what is done with merge, revert and cherry-pick: one low-level API were you have full control and must specify all parameters and a higher-level wrapper which essentially behaves like git CLT i.e. works in the workdir and HEAD. Similarly here, you could have 2 versions of `git_rebase_init()` instead of the current strange middle ground.

2) Ah I missed `rebase_ensure_not_dirty()`, so I guess it's fine then!

3) I don't have a test, case I was just looking at the code. If you have 2 commits with the same timestamps, the problem is that order returned by the walker may be indeterministic no? And even it would be subject to implementation changes. Any reason why you didn't implement this by simply calling `git_commit_parent()` instead of using a walker?

**Comment by ethomson** [comment]
> Like I described in my example above, the fact I have to both call git_repository_set_head() with branch and then pass branch again to git_rebase_init() to work around how it's internals work is not "clean" API impedance and more complex than needed IMO.

Maybe I'm not understanding why you need to call `git_repository_set_head`.  Is there some reason you need to be on that branch instead of just passing it as the first argument?  We set up the `orig-head` and all that stuff based on the `branch` parameter, not based on `HEAD`, as far as I remember.  That is to say `git_rebase(&rebase, repo, &my_branch, &my_upstream, NULL ...)` should be equivalent to `git checkout my_branch && git rebase my_upstream`.

But I think you're right that `branch` should probably be optional and default to `HEAD`.  I don't see offhand why that would be a problem.

Per (3), we use a revwalker because git.git uses a revwalker and we want to use the same order as they do.  Per the man page:

> All changes made by commits in the current branch but that are not in <upstream> are saved to a temporary area. This is the same set of commits that would be shown by git log <upstream>..HEAD (or git log HEAD, if --root is specified).

(If we start following commits parents, then we're just rewriting a revwalker.)

**Comment by swisspol** [comment]
> Maybe I'm not understanding why you need to call git_repository_set_head.

See the boilerplate steps I described at the very top in order to emulate `git rebase` CLT. Am I not doing it right i.e. I'm not using the best steps?

> we use a revwalker because git.git uses a revwalker and we want to use the same order as they do. Per the man page:

Sounds reasonable but are you configuring it the same way though? You're sorting by time, which might not be stable, instead of say `GIT_SORT_TOPOLOGICAL`.

**Comment by ethomson** [comment]
> See the boilerplate steps I described at the very top in order to emulate git rebase CLT. Am I not doing it right i.e. I'm not using the best steps?

I think that the `git_repository_set_head` is not necessary - I think you only need to create an `annotated_commit` from the branch you want to check out.

But indeed, it would be nicer if you didn't have to specify a `branch` if you were on the branch you anticipated.  I don't see a reason why this is really necessary, but it may be obvious once I get back in there.

> Sounds reasonable but are you configuring it the same way though? You're sorting by time, which might not be stable, instead of say GIT_SORT_TOPOLOGICAL.

Yes, that's a good question.  I'll have to revisit this, I was hoping you had a case that illustrated a problem.

**Comment by ethomson** [comment]
Sorry for the long delay in getting back to this.  I think that #2903 should fix all of these.  (With the exception of the revwalk sorting - I verified that we're compatible with git core.)

**Comment by swisspol** [comment]
Awesome, thanks!
