### ISSUE TITLE
CocoaPods Issue

### ISSUE THREAD

**Issue by wjk** [libgit2/libgit2#2795]
I’m not sure if this is the proper place to discuss this, but I ran into an issue with `libgit2` when installed through [CocoaPods](https://github.com/CocoaPods/CocoaPods). Specifically, [the `libgit2` podspec file](https://github.com/CocoaPods/Specs/blob/master/Specs/libgit2/0.17.0/libgit2.podspec.json) specifies that all `.c` files under `src/` are to be included in the build.

Unfortunately, this causes both the POSIX and the Amiga implementations of the `p_mmap` function to be compiled. Ignoring the fact that the Amiga version doesn’t even compile on OS X without adding a few lines of code, the problem here is that `p_mmap` and `p_munmap` are then defined in two object files, which the linker then complains about. I would think the easiest way to solve this is to add a `#if` statement to the Amiga version of `map.c`, causing its contents to be properly ignored on non-Amiga platforms.

I would prepare a PR, except that the `podspec` file doesn’t appear to be in this repository. Any pointers? Thanks!

**Comment by joshaber** [comment]
We don't use CocoaPods so we're the worst people to try to maintain a podspec. I'd encourage you to open a PR against the [Specs](https://github.com/CocoaPods/Specs/tree/master/Specs/ObjectiveGit) repository.

**Comment by wjk** [comment]
Fair enough. The only reason I opened an issue here is because I don’t know who committed `libgit2.podspec`. As it turns out, CocoaPods is causing other problems, completely unrelated to libgit2. It looks like I will have to use [another solution](https://github.com/Carthage/Carthage) for now.
