### ISSUE TITLE
clone bare repo ended with"Floating point exception"

### ISSUE THREAD

**Issue by qling** [libgit2/libgit2#2812]
The bug had been founded while testing the exampel code, and still seen in the latest v0.22.0-rc1-11-g1646412 release.  Run command:
./git2 clone path_to_bare_repo path

**Comment by linquize** [comment]
what platform?

**Comment by qling** [comment]
The platform that I am testing is:
ubuntu 3.2.0-40-generic #64-Ubuntu SMP Mon Mar 25 21:22:10 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
