### ISSUE TITLE
~ is not expanded in init.templatedir

### ISSUE THREAD

**Issue by alexcrichton** [libgit2/libgit2#2814]
I've used the following setup to generate the error at the end:

```
# ~/.gitconfig
[init]
    templatedir = ~/gittemplate
```

```c
#include <git2.h>
#include <stdio.h>
#include <assert.h>

int main() {
    git_repository_init_options opts;
    git_libgit2_init();
    assert(git_repository_init_init_options(&opts, GIT_REPOSITORY_INIT_OPTIONS_VERSION) == 0);

    opts.flags = GIT_REPOSITORY_INIT_MKDIR | GIT_REPOSITORY_INIT_EXTERNAL_TEMPLATE;

    git_repository *repo;
    if (git_repository_init_ext(&repo, "test", &opts) != 0) {
        printf("%d - %s\n", giterr_last()->klass, giterr_last()->message);
    }
}
```

```
$ mkdir ~/gittemplate
$ gcc foo.c -lgit2 -Iinclude -L build && ./a.out
2 - Could not find '~/gittemplate/' to stat: No such file or directory
```

When compared to the git CLI:

```
$ git init test
Initialized empty Git repository in /Users/acrichton/code/libgit2/test/.git/
```

I noticed that https://github.com/libgit2/libgit2/pull/1608 implemented `~` expansion of some form, but I couldn't track down if there was a way to fetch it through the normal config interface.  The instigation for this issue is https://github.com/rust-lang/cargo/issues/1140.

**Comment by carlosmn** [comment]
I've been meaning to write `git_config_get_path()` for a while, but never got around to it. It shouldn't be too hard to add, since we already store an idea of what the user's home directory is.
