### ISSUE TITLE
clone from OpenShift accounts fail with "Found invalid hex digit in length" error

### ISSUE THREAD

**Issue by palmin** [libgit2/libgit2#2830]
I have trouble cloning from RedHat OpenShift accounts. They require public-key ssh authentication and if this succeeds the cloning stops with the error message:
 `Found invalid hex digit in length`

I have verified that command-line git will clone without problems. 

The following code will trigger the error for v0.16.0-5730-g2136240
````
int cred_acquire_cb(git_cred **cred, const char *url, const char *username_from_url,
				unsigned int allowed_types, void *payload) {
	return git_cred_ssh_key_new(cred, username_from_url, "id_rsa.pub", "id_rsa", NULL);
}

int main() {
	git_libgit2_init();
	git_clone_options clone_options = GIT_CLONE_OPTIONS_INIT;
	clone_options.remote_callbacks.credentials = cred_acquire_cb;

	git_repository *repo = NULL;
	const char *url = ...;
	int error = git_clone(&repo, url, "test.git", &clone_options);
	fprintf(stderr, "error = %d, %s\n", error, giterr_last()->message);
}
````

Accounts can be created free of charge at [OpenShift](http://openshift.redhat.com).

**Comment by linquize** [comment]
Is it reproducible on libgit2 v0.22?

**Comment by palmin** [comment]
Yes.
Just tried on the v0.22.1 release where it is reproducible.

**Comment by palmin** [comment]
While debugging i found out that the hex-digit that cannot be parsed is in response to something like:
    
    "Invalid repository /~/git/test.git/: not in application root"
    
I did not include the full URL which is unfortunate as this was part of the problem. It seems ~ in the clone-URL is not properly translated into the home-directory. Specifying a clone-URL without ~ works without problems.

I will dig a little deeper and see if I can find out why ~ is not properly translated. I can see that home directories on OpenShift are in a non-standard location:

    /var/lib/openshift/

and perhaps the server-end spills a error-message into the ssh transport.

**Comment by palmin** [comment]
I cannot see that libgit2 does anything wrong.

A bug request has been filed at bugzilla.redhat.com regarding OpenShift.

**Comment by ethomson** [comment]
Thanks for the update.

It might be nice for us to include the four characters that we tried to parse as the hex length, since this is likely to be the usual culprit here - the server sending an error message that we're trying to parse as the length.  So it might be a little bit more obvious as to what's wrong if you saw "Failed to parse hex digits 'Erro' or 'Fail'...

**Comment by palmin** [comment]
My users keep getting this error and it always covers up some other problem making debugging very hard. 

How do you feel about a pull-request that improves the error message generated in [parse_len](https://github.com/libgit2/libgit2/blob/master/src/transports/smart_pkt.c#L363)?

I can take the 4 characters and include these, which is also what command-line git does. It outputs something like:
````fatal: protocol error: bad line length character: Inva````

But I would much rather grab the rest of the line, perhaps taking the first 60 characters if the line is longer. We would then get a error message:
````Bad packet length: Invalid path ~/user/repo.git````
that is much more helpful.

Which of the two would you prefer?

**Comment by carlosmn** [comment]
Adding the bytes which we tried to parse as invalid is fine (assuming a server isn't going to send something which messes up a console or other text output) but we can't put the whole string in there. For one it implies we tried to parse the whole thing, which is not true, but we also do not know when the string ends. That's why we're trying to parse a length in the first place.

**Comment by palmin** [comment]
There is now a [pull-request](https://github.com/libgit2/libgit2/issues/3355) that includes the 4 bytes in the error message.
