### ISSUE TITLE
Status adding unwanted duplicates with INCLUDE_UNMODIFIED

### ISSUE THREAD

**Issue by Therzok** [libgit2/libgit2#2833]
See https://github.com/libgit2/libgit2sharp/pull/863 for a more in-depth information.

tldr: Status isn't returning the 'merge' of the two items in one, but two separate items.

**Comment by Therzok** [comment]
Magically fixed.

**Comment by nulltoken** [comment]
Hmmm. In which commit has this been fixed?

/cc @ethomson

**Comment by Therzok** [comment]
No idea, it just magically started working.

https://github.com/libgit2/libgit2/commit/3f8d005 was the last time we tested the PR.

**Comment by Therzok** [comment]
See this: https://travis-ci.org/libgit2/libgit2sharp/jobs/40864391
