### ISSUE TITLE
git_repository_is_empty() implementation doesn't match the doc

### ISSUE THREAD

**Issue by swisspol** [libgit2/libgit2#2838]
Doc says:
```
 * Check if a repository is empty
 *
 * An empty repository has just been initialized and contains
 * no references.
```

Actually if the repo doesn't contain any reference at all (not even `HEAD` like if created using Git CLT `git init --bare`, this API fails and returns -1 because of the failing call to `git_reference_lookup()`.

With the current implementation of `git_repository_is_empty()`, a repo is considered empty if all these conditions are met:
- It has a `HEAD` reference
- The `HEAD` reference is symbolic and points to `heads/master`
- There is no references in the repo (ignoring the special `HEAD` reference)

I'm happy to submit a PR for this to fix either the doc or the implementation or both, but I need to know what is the intent of `git_repository_is_empty()`. IMO this API should ignore `HEAD` entirely.

**Comment by ethomson** [comment]
Hah!  My inclination is that the doc is right, the code is wrong and we should check for `HEAD`s existence before ensuring that it's a symbolic ref to `refs/heads/master`.  (And not error if it doesn't.)

**Comment by swisspol** [comment]
But what if `HEAD` exists and points to `refs/heads/topic` and there are no other references? The API would say the repo is not empty while it is. Why special case `master` (I know that the default set up for a new Git repo but still)? That's why I was asking what's the actual intent of this API: is it to detect a newly initialized repo or an an empty repo? That's not exactly the same.

Personally, when I see this API and its name I expect it to tell me if the repo has any commits in it, which would be equivalent to "does it have any reachable commits through the normal ways" i.e. references and optionally a detached HEAD (but not reflogs).

**Comment by nulltoken** [comment]
It's never been really clear what this function actually ensures. Should we give it a better name?

Related https://github.com/libgit2/libgit2/pull/1360#issuecomment-14083595

**Comment by swisspol** [comment]
If that's a possibility to remove this API entirely, then I would vote for it, as it's one of these things that means different things to different people and the current implementation is not robust anyway.

**Comment by carlosmn** [comment]
It doesn't *ensure* anything, it's a heuristic to guess if the repository is just-initialized (or in some cases was reset completely). We define what it means to be empty for this function in the documentation. We should mention it's a heuristic, but it's a useful function.

The situation you refer to in the issue description is not the result of `git init --bare`, but a corrupt repository. A Git repository must always have HEAD, and it's one of the checks we perform when loading a repository. You would not be able to get a `git_repository` object if HEAD is missing; if you do have a `git_repository` and this function complains about a missing HEAD, then something has corrupted your repository.

**Comment by ethomson** [comment]
Hah, right, that's a good point.  A repo with a `HEAD` is not a repo.

**Comment by nulltoken** [comment]
>It doesn't *ensure* anything

Fair enough

>We should mention it's a heuristic,

:+1:

**Comment by swisspol** [comment]
See PR #2853.
