### ISSUE TITLE
Invalid config file causes assertion failure

### ISSUE THREAD

**Issue by mduggan** [libgit2/libgit2#2851]
A tiny config parsing bug: this config file causes an assertion failure when opened with `git_config_open_ondisk(&cfg, "test_config")`.  Probably should just be a parse error:
```
[a]
 b = \\\;
 x = y
```
Result is:
```
config: /home/mduggan/src/libgit2/src/config_file.c:1684: parse_multiline_variable: Assertion `is_multiline_var(value->ptr)' failed.
Aborted
```
tested on the latest master (1ac5acd).

**Comment by carlosmn** [comment]
Fixed in #3060
