### ISSUE TITLE
Win32 Test crash

### ISSUE THREAD

**Issue by locke12456** [libgit2/libgit2#2863]
[submodules.c]

	/* add file to index in submodule */
	cl_git_pass(git_submodule_open(&smrepo, sm));
	cl_git_pass(git_repository_index(&smindex, smrepo));
	cl_git_pass(git_index_add_bypath(smindex, "file_to_modify"));

test case into the 'git_index_add_bypath'  will crash

and there are call stack
![git-test case crashed](https://cloud.githubusercontent.com/assets/1829977/6015208/99dec09c-abac-11e4-8b89-d03757374f97.png)

[repository.c]

		if (!repo->is_bare) {
			repo->name_8dot3 = git_win32_path_8dot3_name(repo->path_repository);

			/* We anticipate the 8.3 name is "GIT~1", so use a static for
			 * easy testing in the common case */
			if (strcasecmp(repo->name_8dot3, git_repository__8dot3_default) == 0)
				repo->has_8dot3_default = 1;
		}

repo was exist . but 'repo->name_8dot3' is NULL.

**Comment by linquize** [comment]
See #2859
