### ISSUE TITLE
Setting certificate check for HTTP returns error (even if HTTP request redirects to HTTPS)

### ISSUE THREAD

**Issue by johnhaley81** [libgit2/libgit2#2904]
If you try to set the `certificate_check` on the remote callbacks option for a `git_clone` when the protocol is HTTP you'll get `Error: an unencrypted stream does not have a certificate`. And that makes sense but if the HTTP redirects to HTTPS (e.g. GitHub) then you do have a certificate and the check would be nice to have.

**Comment by johnhaley81** [comment]
Anybody have any ideas about this?? It shouldn't be too hard to put in.

**Comment by carlosmn** [comment]
The issue would have to be a different one. The error comes not from setting the callback, but the fact that we don't check beforehand whether the current stream is encrypted before asking for it.

**Comment by johnhaley81** [comment]
Do you mean https://github.com/libgit2/libgit2/blob/1ce9ea3/src/stream.h#L20-L23 ?

**Comment by carlosmn** [comment]
That error is correct where it's generated, the issue is calling that function when we do not have connection capable of having a certificate.

**Comment by johnhaley81** [comment]
Ah so that's called before the HTTPS redirect.

**Comment by calavera** [comment]
yeah, libgit2 checks the scheme before calling that function, without checking the actual connection. I was actually hit by this issue this morning :pensive:
