### ISSUE TITLE
Does libgit2 use GIT_TEMPLATE_DIR when running clone or init?

### ISSUE THREAD

**Issue by CMCDragonkai** [libgit2/libgit2#2910]
When using Cargo in Rust Lang which uses libgit2, when I tried running `cargo build` which runs a `git clone` in the backend it failed to use the `GIT_TEMPLATE_DIR` that I had specified. 

This was on Windows 8.

Can libgit2 recognise the `GIT_TEMPLATE_DIR`?

**Comment by carlosmn** [comment]
In general, libgit2 does not take environment variables into account. It does handle the configuration variable and the caller can provide an explicit path.

But if you're having issues with cargo, you should report it to that project, instead of one of the dependencies.

**Comment by BenWiederhake** [comment]
> libgit2 does not take environment variables into account

I just got bitten by this.  What is the rationale behind this decision?  Why intentionally break compatibility with the "normal" behavior?  The Readme says that all differences with upstream are seen as a "git change" bug, but I can't see any issue for that.  Is there any documentation on this difference?  Where else does libgit2 differ intentionally?

**Comment by neithernut** [comment]
Sane libraries never look at the environment. It's (usually) the library user's responsibility to provide the configuration. There are, for example, valid reasons a program may choose to ignore the environment.

**Comment by neithernut** [comment]
Libraries where dealing with the environment is a core functionality are exceptions, obviously. Also, libraries _may_ provide some convenience functionality for reading stuff from the environment. `git_repository_discover()` and flavours of `git_repository_open_ext()` would fall i nthe latter category.

**Comment by ethomson** [comment]
Thanks, @neithernut, this summarizes our thoughts pretty accurately.  People build a lot of things on top of libgit2 - git clients, of course, but also hosting providers like the one you're reading this message on.  And while it probably make sense to read environment variables in git clients, and it _might_ make sense to read environment variables in the hosting providers, this definitely doesn't extend to all our users.

There are lots of people using libgit2 for lots of different things, like [databases](https://github.com/ioquatix/relaxo), [package managers](https://docs.julialang.org/en/stable/devdocs/libgit2/), [cloud synchronization](https://hackernoon.com/modifying-files-stored-outside-of-postgresql-while-maintaining-full-transaction-safety-and-d8b55327e679) and [storage mechanisms for their applications](https://subsurface-divelog.org).

Reading environment variables like `GIT_DIR` or - yes - `GIT_TEMPLATE_DIR` by default would be poor form.  We do provide mechanisms to read - and apply - these settings, but we do not do so by default.  If your application wants to use them, I would encourage you to enable these settings (eg, via `git_repository_open_ext`).

If there's a way that we could make this easier for your application then we'd be happy to do that, but I do want to be wary to not break users who are using libgit2 for other things.
