### ISSUE TITLE
git_stash_save() doesn't behave like Git CLT for index-deleted but workdir-modified files

### ISSUE THREAD

**Issue by swisspol** [libgit2/libgit2#2912]
This one is for @ethomson I guess :)

I was perusing the implementation of `git_stash_save()` and especially `commit_worktree()` and how it uses `git_diff_tree_to_workdir_with_index()`, which has a peculiar behavior, and was wondering if Git CLT really does this. Turns out it does not, so libgit2's stashing currently does not match Git CLT.

Prepare a dead simple test repo like this with a deleted-in-index-but-modified-in-workdir file:
```sh
$ git init
Initialized empty Git repository in /private/tmp/stash/.git/
$ echo "Hello world" > hello.txt
$ echo "Bonjour monde" > bonjour.txt
$ git add -A
$ git commit -m "Initial commit"
[master (root-commit) c04b8cb] Initial commit
 2 files changed, 2 insertions(+)
 create mode 100644 bonjour.txt
 create mode 100644 hello.txt
$ git rm hello.txt 
rm 'hello.txt'
$ echo "TEST" > hello.txt
$ echo "Au revoir monde" > bonjour.txt 
$ git status
On branch master
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	deleted:    hello.txt

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   bonjour.txt

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	hello.txt
```

Stash with Git CLT and notice how the deleted-in-index-but-modified-in-workdir file is stashed as a **modified** file:
```
$ git stash
Saved working directory and index state WIP on master: 1b971ca Initial commit
HEAD is now at 1b971ca Initial commit

$ git diff-index stash
:100644 100644 682672c4f6391ec89dbb7ae0a4070058df0c2a66 2fd81b86452753fd74b59d93d62ffe562811a8e2 M	bonjour.txt
:100644 100644 2a02d41ce21323b1cdc228c78cec2f81c054bd34 802992c4220de19a90767f3000a79a31b98d0df7 M	hello.txt

$ git stash pop
On branch master
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   bonjour.txt
	modified:   hello.txt

no changes added to commit (use "git add" and/or "git commit -a")
Dropped refs/stash@{0} (9d7d6466523528527b8b6090e9de4437fe857961)
```

Now try the same with `git_stash_save()` and notice how the deleted-in-index-but-modified-in-workdir file is stashed as a **deleted** file:
```sh
# CALL git_stash_save() here
$ git status
On branch master
nothing to commit, working directory clean

$ git diff-index stash
:100644 100644 682672c4f6391ec89dbb7ae0a4070058df0c2a66 2fd81b86452753fd74b59d93d62ffe562811a8e2 M	bonjour.txt
:000000 100644 0000000000000000000000000000000000000000 802992c4220de19a90767f3000a79a31b98d0df7 A	hello.txt

$ git stash pop
Removing hello.txt
On branch master
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   bonjour.txt
	deleted:    hello.txt

no changes added to commit (use "git add" and/or "git commit -a")
Dropped refs/stash@{0} (ec1ca1be2486bbe74fd81b2953eb57bf22a53d0b)
```

**Comment by swisspol** [comment]
For reference the Git CLT implementation is here:
https://github.com/git/git/blob/master/git-stash.sh#L115

If I'm reading this correctly, all it does is a dumb diff between the previously saved index tree and the workdir.

**Comment by swisspol** [comment]
I patched my fork of libgit2 to use `git_diff_tree_to_workdir()` instead and now the behavior matches Git CLT which is what one would expect.

**Comment by swisspol** [comment]
To confirm how Git CLT creates the main stashed commit (see https://github.com/git/git/blob/master/git-stash.sh#L119): it creates a new tree from the index tree previously saved, adding to it the changes between HEAD and the workdir. `git_diff_tree_to_workdir()` is definitely what should be used here, not `git_diff_tree_to_workdir_with_index()`.

**Comment by ethomson** [comment]
@swisspol can you take a look at #2912 and make sure that I have captured the problem appropriately?

**Comment by swisspol** [comment]
Looks good! Thanks for taking care of this - I would have gladly send a PR but it takes more forever to write these unit tests since I'm not super familiar with the fixture system yet.
