### ISSUE TITLE
Don't force use of iconv on Darwin

### ISSUE THREAD

**Issue by techee** [libgit2/libgit2#2918]
When building on osx using jhbuild (and all the jhbuild's gtk dependencies), I get the following error:

```
Undefined symbols for architecture x86_64:
  "_libiconv", referenced from:
      _git_path_iconv in path.c.o
  "_libiconv_close", referenced from:
      _git_path_direach in path.c.o
      _git_path_iconv_clear in path.c.o
      _git_path_dirload in path.c.o
  "_libiconv_open", referenced from:
      _git_path_direach in path.c.o
      _git_path_iconv_init_precompose in path.c.o
      _git_path_dirload in path.c.o
ld: symbol(s) not found for architecture x86_64
```

Unfortunately there's no way right now to disable iconv use because it's hardcoded for Darwin by

```
IF(${CMAKE_SYSTEM_NAME} MATCHES "Darwin")
        SET( USE_ICONV ON )
ENDIF()
```

When these lines are commented-out, everything compiles right.

Would it be possible to have the possibility to set OFF for the iconv settings on Darwin from the commandline? For instance by default the iconv settings could be ON with the possibility to disable it by a configure argument.

Sorry for not providing a patch, unfortunately I'm not familiar with cmake.

**Comment by ethomson** [comment]
I worry that this is a workaround to the actual problem of your build environment not setting up your linker path correctly...  But I'm not particularly familiar with jhbuild.

Not having iconv would be challenging; you would not be able to precompose Unicode.  I don't think that you'd want to build without it.

**Comment by techee** [comment]
JHBuild rebuilds basically the whole linux library stack that is used by GTK so the behaviour of all library calls should correspond to linux, not OS X (iconv is part of the gettext package which is used by the rest of the libraries). So even though the architecture is darwin, the actual architecture is linux-like.

My assumption is that on linux systems you don't use libiconv because the encoding is already "right". The same should happen on Darwin with JHBuild.

**Comment by carlosmn** [comment]
iconv is neecessary to handle the different handling of the HFS+ filesystem wrt unicode character composition. Not using iconv leads to problems recognising which filesnames are the same between Git's record and the name returned by the filesystem, which causes duplicate filenames showing up when a repository is on a linux-style filesystem. You can search for trouble with umlauts on osx with git to see some issues.

A libigt2 without iconv would remove support for HFS+ in all but the most basic filenames and would significantly reduce the cases where libgit2 behaves correctly. Such a build of libgit2 would not be one which we would be able or willing to support.

**Comment by techee** [comment]
Argh, the real problem is somewhere else, here:

https://github.com/libgit2/libgit2/blob/master/cmake/Modules/FindIconv.cmake#L14

and possibly also two lines later. Why does it search under /opt? Both under linux and osx the system libraries should be searched under /usr. The thing is that MacPorts (which I have installed to make my system even funnier) installs all the ports under /opt/local, including GNU iconv. During configure (not sure how "cmake .." is called) the /opt version is found. During compilation, cmake uses the headers from /opt. However, when linking, the standard library path /usr/lib is searched too and libiconv is linked from there (which uses different symbols than the GNU libiconv) which leads to the error.

/opt definitely isn't a standard path for libraries and shouldn't be searched by default.

**Comment by ethomson** [comment]
@techee My inclination is to prefer the system `iconv` over anything in MacPorts or homebrew or anything like that.  Users can and should override if they want those.  Would you mind sending a pull request?  I don't have any machine with MacPorts to test this on.  Thanks!

**Comment by carlosmn** [comment]
With #2997 and #3092 this should no longer be an issue.
