### ISSUE TITLE
Allow to create a remote without a repository

### ISSUE THREAD

**Issue by carlosmn** [libgit2/libgit2#2923]
Every remote constructor we have takes a repository, but you do not always have a repository available. Commands like

```
git ls-remote https://example.com/repo
```

do not require a repository at all. We should be able to lift the requirement of a repository for connecting to a remote and seeing what references there are available.

Performing a fetch would obviously require a repository.

**Comment by wonson** [comment]
libgit2sharp got it solved, how about the c++ lib?? does it go any further now?

**Comment by jzahka** [comment]
+1

**Comment by mathieumg** [comment]
There is a PR (linked above, https://github.com/libgit2/libgit2/pull/3855) but this is marked as "up for grabs". Is something blocking this? I would be glad to help!

**Comment by pks-t** [comment]
I just grabbed #3855, will push it as it's been open for so long and is obviously requested by more than just one person

**Comment by carlosmn** [comment]
Fixed via #4233
