### ISSUE TITLE
Leak testing on Windows in CI

### ISSUE THREAD

**Issue by ethomson** [libgit2/libgit2#2943]
I've used [Dr Memory](http://www.drmemory.org/) with some success on Windows.  It is pretty stable when run as `drmemory -leaks_only libgit2_clar.exe` and this would be useful to add to AppVeyor.

Like we do with Travis, it probably makes sense to only do a single target (x86, I suppose) and allow that to fail.

**Comment by ethomson** [comment]
Thankfully, dr memory is in chocolatey, so this should be as easy as:

    cinst drmemory.install

I think that this is a pretty easy task for somebody and probably just requires some understanding of AppVeyor.

**Comment by nulltoken** [comment]
:+1:

**Comment by ethomson** [comment]
Closed via #3039
