### ISSUE TITLE
We should provide an annotated version for `set_head()` and `set_head_detached()`

### ISSUE THREAD

**Issue by carlosmn** [libgit2/libgit2#2949]
We currently accept an id, which means the message we create is as though a user passed in an exact object id on the command-line. This will often not be the case.

Providing variants of these functions which accept an annotated commit would let us write to the reflog a message which includes the string the user provided.

**Comment by nulltoken** [comment]
Things we maybe should honor as well

```
branch: Created from test
branch: Created from refs/tags/test
branch: Created from be3563a
checkout: moving from 6dcf9bf7541ee10456529833502442f385010c3d to e90810^{}
checkout: moving from master to 6dcf9bf
checkout: moving from master to refs/tags/lw
checkout: moving from master to HEAD~2
```

**Comment by nulltoken** [comment]
Those changes have been discovered while working on https://github.com/libgit2/libgit2sharp/pull/965

**Comment by carlosmn** [comment]
All those checkout ones would be convered by `_set_head_annotated()`
