### ISSUE TITLE
git_push_update_tips() behavior not-deterministic when pushing

### ISSUE THREAD

**Issue by swisspol** [libgit2/libgit2#2956]
First, the context:

- When a remote object is allocated, the active refspecs are copied from the built-in ones
- When you call `git_remote_download()`, the active refspecs are copied from the passed ones if any, or copied from the built-in ones
- When you call `git_remote_upload()`, the active refspecs are left untouched (I assume because they are not used by the push itself?)

Then the problem:

When you call `git_remote_update_tips()` after `git_remote_upload()`, the actual implementation of `git_push_update_tips()` uses the "intersection" of the passed-in refspecs for the push and the active refspecs when figuring out which tips to update.

This means that depending on the state of the active refspecs and what you've done with the remote before, `git_push_update_tips()` may not update some tips while it should have.

**The fix is not hard, but before doing it, there's this higher-level issue that needs to be addressed: when using `git_remote_update_tips()` after a push, why is it even looking at the remote built-in refspecs vs only considering the passed-in ones?**

**Comment by swisspol** [comment]
Who makes the call on changing `git_push_update_tips()` to only look at the passed-in refspecs like 
`git_remote_update_tips()` does when fetching? @ethomson @carlosmn?

Note that if changing this behavior it will affect tag operations. And the user has no control over them since there's no tag update mode when pushing.

Here's one concrete example: if you delete a tag on a remote with `:/ref/tags/foo`, then call `git_remote_update_tips()`, when it attempts to find a built-in refspec matching the RHS as part of finding the tip to update, this fails (since the built-in refspec is most likely `+refs/heads/*:refs/remotes/origin/*`). So the tag doesn't get deleted locally.

This may actually be what you want since tags are "shared" references, but the same would happen with a regular remote branch being deleted that doesn't happen to match the built-in refspec.

**Comment by swisspol** [comment]
I fixed the first part i.e. the non-deterministicness in 37059623f1909549b01baa54e4247e823850445b

**Comment by carlosmn** [comment]
Are any of the issues you mentioned still in master?

**Comment by swisspol** [comment]
I can't say, a lot of the remote code has changed recently and I'm not familiar with the new one.

If this heuristic below is still in place, then the problem and the example case mentioned above are still valid:

> When you call git_remote_update_tips() after git_remote_upload(), the actual implementation of git_push_update_tips() uses the "intersection" of the passed-in refspecs for the push and the active refspecs when figuring out which tips to update.

**Comment by carlosmn** [comment]
The active refspecs are configured just before uploading, so this wouldn't be an issue. Re-using remotes like this only supported when people end up complaining, the code in the library always uses a remote for a particular purpose.
