### ISSUE TITLE
Support UNC Path on Windows

### ISSUE THREAD

**Issue by forcegroup** [libgit2/libgit2#2958]
code file: [win32/path_w32.h](https://github.com/libgit2/libgit2/blob/d8be5087771db34b191b13f22a2846888a477c36/src/win32/path_w32.h)
```C++
#define GIT_WIN_PATH_UTF16		MAX_PATH+6
```

We known,linux max path is usually 4096 ,Someone created project on the Linux , some file relative storage path of the root directory with more than 260. Another person on the Windows, clone this project, checkout the code maybe an error occurs?

when your add *\\\?\* to path ,This means that path is UNC Path。UNC Max Path is 32,767 characters.
Use Windows API ,Unicode Function almost support UNC Path

so I suggest define 
```C++
#define GIT_WIN_PATH_UTF16 4096+6 
```

Not to worry, OpenFileW WriteFileW DeleteFileW MoveFileW these functions support UNC paths

MSDN: [Naming Files, Paths, and Namespaces](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247.aspx)

Thanks

**Comment by ethomson** [comment]
We use the [Win32 file namespaces](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247%28v=vs.85%29.aspx) to avoid interpretation of the paths, not to enable support for paths > 260 characters.  (Note, these are not UNC paths, though they share the first two characters with typical UNC path format.)

That this is the common path format for long path support does not indicate that we should simply stop checking paths for their length and assume they will work.  Paths > 260 characters cause incompatibility with literally almost every other windows application and using them needs to be a well thought out decision with epic amounts of testing and thinking about the terrible trade offs involved and the horrible pain you are putting the user through.

We will support long paths on Windows, when `core.longpaths` is set.  But this needs to be a more appropriate and measured response than simply changing the size of a buffer and hoping for the best.

**Comment by ethomson** [comment]
Plan this in #3053

**Comment by forcegroup** [comment]
@ethomson  Very good ,Thanks.
