### ISSUE TITLE
Question: oid is sha1 of blob content?

### ISSUE THREAD

**Issue by JerryYangJin** [libgit2/libgit2#2976]
Hello, libgit2 team

I have a question regarding oid hash value, I posted a question on libgit2-backend, issue#8, but no answer, so I thought I might put it here. Please let me know if this is the wrong place to ask this.

I'm trying to use libgit2 and mysql as backend, I followed libgit2-backend project and managed to create blob to mysql table

This is the code to create a blob from buffer, it's a string.
```c
const char str[] = "Hello, World!";
git_blob_create_frombuffer(&oid, mysql_odb_backend->repo, str, strlen(str));
```
The blob successfully inserted to the odb table, the uncompress(data) is the string content

But I don't understand the oid column value, as according to git concept, it's sha1 value of the data content, please correct me if I'm wrong.

So I did a validation

```sql
select  lower(hex(oid)),
		type, 
		size, 
        convert(uncompress(data),char(100)),
        sha1(uncompress(data))
from git2_odb
```
result:

| lower(hex(oid)) | type | size | convert(uncompress(data),char(100)) | sha1(uncompress(data)) |
| ------------------- | ------ | ---- | ------------------------------------------------ | ------------------------------- |
| b45ef6fec89518d314f546fd6c3025367b721684 | 3 | 13 | Hello, World! | 0a0a9f2a6772942557ab5355d76af442f8f65e01 |

I found that the hex oid value is not the same as sha1 data, is this correct? or I'm doing it in the wrong way?

Thank you!

Best Regards,
Jerry

**Comment by vmg** [comment]
Hi Jerry! The OID is the SHA1 of **a header** plus the content of the blob, where the header is the type of the object (in this case `blob`), plus its size in bytes plus a NULL byte. That's why hashing `Hello, World!` is not working. You'd need to hash `blob 13\00Hello, World!` :)

You can read up more details about it on the Git Book: http://git-scm.com/book/no-nb/v1/Git-Internals-Git-Objects#Object-Storage

Cheers!

**Comment by JerryYangJin** [comment]
Thanks a lot, vmg!
Now I'm able to reconcile the oid and sha1(data)
