### ISSUE TITLE
Memory leak with `note_get_default_ref`

### ISSUE THREAD

**Issue by alexcrichton** [libgit2/libgit2#2980]
Since #2771 it looks like the `note_get_default_ref` function changed to returning a `strdup`'d string which needs to be deallocated, but I'm not sure that all callers have been updated. From an API perspective, I've noticed these leaks:

* `git_note_default_ref`'s documentation doesn't indicate the return pointer needs to be freed, and I think that it should now take a `git_buf` as well?
* `git_note_iterator_new` eventually calls `note_get_default_ref` if its `notes_ref` argument is `NULL`, leaking the memory allocated there. This also affects `git_note_{create,read}` I believe.

**Comment by carlosmn** [comment]
See #2947

**Comment by alexcrichton** [comment]
Oh oops, sorry for the noise! Thanks though!
