### ISSUE TITLE
Cross-building libgit2 on Linux for Windows fails

### ISSUE THREAD

**Issue by claudiuolteanu** [libgit2/libgit2#2984]
Hi there,

When I try to build I receive the following error:
```
[ 24%] Building C object CMakeFiles/libgit2_clar.dir/tests/checkout/icase.c.obj
/usr/bin/x86_64-w64-mingw32-gcc  -DCLAR_FIXTURE_PATH=\"/home/claudiu/Documents/windows/libgit2/tests/resources/\" -DCLAR_RESOURCES=\"\" -DCLAR_TMPDIR=\"libgit2_tests\" -DGIT_ARCH_64 -DGIT_SSH -DGIT_THREADS -DNO_GZIP -DNO_VIZ -DSTDC -DWIN32 -D_FILE_OFFSET_BITS=64 -D_WIN32_WINNT=0x0501 -D__USE_MINGW_ANSI_STDIO=1 -D_GNU_SOURCE -Wall -Wextra -O2 -g -pipe -Wall -fexceptions --param=ssp-buffer-size=4 -mms-bitfields  -Wno-missing-field-initializers -Wstrict-aliasing=2 -Wstrict-prototypes -Wdeclaration-after-statement -Wno-unused-function -O2 -g -DNDEBUG @CMakeFiles/libgit2_clar.dir/includes_C.rsp   -o CMakeFiles/libgit2_clar.dir/tests/checkout/icase.c.obj   -c /home/claudiu/Documents/windows/libgit2/tests/checkout/icase.c
/home/claudiu/Documents/windows/libgit2/tests/checkout/icase.c:7:22: fatal error: Windows.h: No such file or directory
 # include <Windows.h>
```
If I remove the include directive, it works. Do you have any idea what could be the problem? I know that it is just a test but is it safe to remove the include directive?

Here are some details about the environment:
```
livgit2 latest commit: d675982a15388d8c413acda139b4662062cf3286 
Platform: OpenSuse-13.2-KDE-x86_64
mingw64-make version: GNU Make 4.0
mingw64-cmake version: cmake version 3.0.2
```

The steps I followed are:
```
mkdir build
cd build/
mingw64-cmake ..
mingw64-make
```

**Comment by adrienthebo** [comment]
My guess would be that you either don't have the mingw headers installed, or they're not in your header search path. The [mingw header package](http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_13.2/noarch/mingw32-headers-3.1.99-5.3.noarch.rpm) has a copy of `windows.h` at `/usr/x86_64-w64-mingw32/sys-root/mingw/include/windows.h`; if that file is present on your system then make sure that path is on the search path for gcc.

**Comment by adrienthebo** [comment]
In addition it looks like the include directive is looking for `Windows.h` with an upper case `W` while the mingw provided header has a lower case `w`, that discrepancy could cause gcc to treat the files differently. Since Windows has a case insensitive filesystem (mostly) it might be necessary to change the include to `# include <windows.h>` for cross compiling compatibility. Windows isn't my forte though, so take this comment with a grain of salt.

**Comment by claudiuolteanu** [comment]
Yes, that was the problem. If I replace ```# include <Windows.h>``` with ```# include <window.h>``` it works.

Thanks for your help!

**Comment by ethomson** [comment]
I'm surprised that our mingw cross-compilation doesn't fail for the same reason.  Maybe our mingw package lays down a symlink somewhere.  This is what I would have expected, as MSDN suggests `#include <Windows.h>` (note the capital `W`).

However, I'd be more inclined to be pragmatic here than to match MSDN's prescription at the expense of actually working.

@claudiuolteanu Would you please send a pull request?

Thanks!

**Comment by claudiuolteanu** [comment]
@ethomson I just sent one.

Regards,
Claudiu

**Comment by tkelman** [comment]
I've had to make exactly this same change in other projects, +1 for #2985

**Comment by clns** [comment]
I'm trying to compile libgit2 for Windows as well, in a linux container. Could you post the commands you used to get it working? I have a standard ubuntu 14.04 container. Thanks.

**Comment by tkelman** [comment]
Try something like ```cmake .. -DCMAKE_C_COMPILER=x86_64-w64-mingw32-gcc -DCMAKE_SYSTEM_NAME=Windows -DCMAKE_RC_COMPILER=`which x86_64-w64-mingw32-windres` -DDLLTOOL=`which x86_64-w64-mingw32-dlltool` -DCMAKE_FIND_ROOT_PATH=/usr/x86_64-w64-mingw32 -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY```

**Comment by clns** [comment]
Thanks, it helped but I'm getting `x86_64-w64-mingw32-gcc: error: unrecognized command line option '-rdynamic'`. The error log is:

```
Determining if the C compiler works failed with the following output:
Change Dir: /go/src/github.com/libgit2/git2go/vendor/libgit2/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTryCompileExec1067044372/fast"
/usr/bin/make -f CMakeFiles/cmTryCompileExec1067044372.dir/build.make CMakeFiles/cmTryCompileExec1067044372.dir/build
make[1]: Entering directory '/go/src/github.com/libgit2/git2go/vendor/libgit2/build/CMakeFiles/CMakeTmp'
/usr/bin/cmake -E cmake_progress_report /go/src/github.com/libgit2/git2go/vendor/libgit2/build/CMakeFiles/CMakeTmp/CMakeFiles 1
Building C object CMakeFiles/cmTryCompileExec1067044372.dir/testCCompiler.c.o
/usr/bin/x86_64-w64-mingw32-gcc    -o CMakeFiles/cmTryCompileExec1067044372.dir/testCCompiler.c.o   -c /go/src/github.com/libgit2/git2go/vendor/libgit2/build/CMakeFiles/CMakeTmp/testCCompiler.c
Linking C executable cmTryCompileExec1067044372
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTryCompileExec1067044372.dir/link.txt --verbose=1
/usr/bin/x86_64-w64-mingw32-gcc       CMakeFiles/cmTryCompileExec1067044372.dir/testCCompiler.c.o  -o cmTryCompileExec1067044372 -rdynamic
x86_64-w64-mingw32-gcc: error: unrecognized command line option '-rdynamic'
CMakeFiles/cmTryCompileExec1067044372.dir/build.make:88: recipe for target 'cmTryCompileExec1067044372' failed
make[1]: Leaving directory '/go/src/github.com/libgit2/git2go/vendor/libgit2/build/CMakeFiles/CMakeTmp'
make[1]: *** [cmTryCompileExec1067044372] Error 1
Makefile:118: recipe for target 'cmTryCompileExec1067044372/fast' failed
make: *** [cmTryCompileExec1067044372/fast] Error 2
```

**Comment by tkelman** [comment]
What version of cmake? Try also adding `-DWIN32=ON -DMINGW=ON -DUSE_SSH=OFF` ?

**Comment by clns** [comment]
Same error with those flags added. `cmake version 3.0.2`.

**Comment by tkelman** [comment]
You could try dropping `-DCMAKE_RC_COMPILER`. I had hit some cmake bugs on 2.8.12.2 when that wasn't provided as an absolute path (some of which gave that same error), but some of the bugs may have been when cross-building from Cygwin to MinGW-w64. I have an Ubuntu 14.04 system where the above set of flags is working.

**Comment by clns** [comment]
I managed to make it work with the following:

`cmake -DBUILD_SHARED_LIBS=OFF -DBUILD_CLAR=OFF -DTHREADSAFE=ON -DCMAKE_SYSTEM_NAME=Windows -DCMAKE_C_COMPILER=x86_64-w64-mingw32-gcc -DCMAKE_RC_COMPILER="$(which x86_64-w64-mingw32-windres)" -DDLLTOOL="$(which x86_64-w64-mingw32-dlltool)" -DCMAKE_FIND_ROOT_PATH=/usr/x86_64-w64-mingw32 -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY -DCMAKE_INSTALL_PREFIX=../install-win .. && \`

Thanks for your help.
