### ISSUE TITLE
git_futils_mkdir_ext Non-Atomic Stat-Then-Mkdir Should Tolerate EEXIST

### ISSUE THREAD

**Issue by simonsj** [libgit2/libgit2#2987]
In function `git_futils_mkdir_ext` there is [this](https://github.com/libgit2/libgit2/blob/437ba9ad651a395b8b3105f5a2d2848194166c06/src/fileops.c#L420-L427) non-atomic stat-then-mkdir sequence:

```c
    if (p_lstat(make_path.ptr, &st) < 0) {
        opts->perfdata.mkdir_calls++;

        if (errno != ENOENT || p_mkdir(make_path.ptr, mode) < 0) {
            giterr_set(GITERR_OS, "Failed to make directory '%s'", make_path.ptr);
            error = GIT_EEXISTS;
            goto done;
        }
```

The sequence is a race whereby two processes may proceed past the stat and both try to mkdir: one will fail with errno `EEXIST`.

Filing this issue to propose that `EEXIST` be tolerated by the `p_mkdir` call above such that libgit2 does not consider the request for directory creation to have actually failed.

**Comment by ethomson** [comment]
Fixed in #3000
