### ISSUE TITLE
Deal with the file with colon in its filename on Windows

### ISSUE THREAD

**Issue by YueLinHo** [libgit2/libgit2#2994]
I got a testing repository from a Linux user.
(https://github.com/t-pascal/tortoisegit-colons)
There is one file with colon in its filename in that repository.
Since such a file is not allowed on Windows, checkout that file is impossible after clone that repository.
Assume the Windows users never touch that file, but the Linux user needs to keep that file in repository.
Is it possible to use something "assume-unchanged" or "skip work tree" on that file on Windows?

Thank you. ^_^

**Comment by carlosmn** [comment]
Are you asking about libgit2 specifically or about how to deal with this in git? It's possible that a sparse checkout will help you, but unless your question relates directly to issues you are seeing calling libgit2, you would get a much better answer by asking in general Git support forums, see http://git-scm.com/community

**Comment by saper** [comment]
See http://latkin.org/blog/2016/07/20/git-for-windows-accidentally-creates-ntfs-alternate-data-streams/ for a longer explanation what happens.
