### ISSUE TITLE
ERROR:could not determine kind of name for C.GIT_CHECKOUT_SAFE_CREATE

### ISSUE THREAD

**Issue by b35li** [libgit2/libgit2#2998]
I have clone both libgit2 and git2go on master, and install libgit2 firstly, and then try to go install the git2go, however, error shows up.
<code>
$ go install
github.com/libgit2/git2go
could not determine kind of name for C.GIT_CHECKOUT_SAFE_CREATE
</code>

I saw some changes form changelog, someone remove this constant, could you tell me what version I should use for libgit2 and git2go?

**Comment by carlosmn** [comment]
This is not a libgit2 issue. The git2go README mentions the support, whether you want to [use a libgit2 release](https://github.com/libgit2/git2go#stable-version) or stay on the [bleeding edge](https://github.com/libgit2/git2go#from-next)
