### ISSUE TITLE
libgit2 do merge but not update the working tree

### ISSUE THREAD

**Issue by fenh365** [libgit2/libgit2#3013]
using libgit2,I do the fetch from remote and merge to local directory.but after I do the merge.I can find the file was changed but the working tree not changed.

**Comment by ethomson** [comment]
We try to use issues and pull requests for bugs and bugfixes, respectively.  If you have questions about using the library, we recommend that you ask on [StackOverflow](stackoverflow.com).  Please post some code that can recreate your problem and / or questions.

**Comment by fenh365** [comment]
ok! thanks
