### ISSUE TITLE
git_describe_options.show_commit_oid_as_fallback not working properly

### ISSUE THREAD

**Issue by trilader** [libgit2/libgit2#3014]
When trying to use show_commit_oid_as_fallback (either in my own code or via the describe example using the --always option) it falis with 
```
Failed to describe rev 'HEAD' [-1] - Cannot describe - No reference found, cannot describe anything.
```
 this is what I did to reproduce this:
```
trilader@BETABOX /f
$ mkdir foo

trilader@BETABOX /f
$ cd foo

trilader@BETABOX /f/foo
$ git init
Initialized empty Git repository in f:/foo/.git/

trilader@BETABOX /f/foo (master)
$ touch testfile

trilader@BETABOX /f/foo (master)
$ git add testfile

trilader@BETABOX /f/foo (master)
$ git commit -m"Testing"
[master (root-commit) 0f52fac] Testing
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 testfile

trilader@BETABOX /f/foo (master)
$ git describe --always
0f52fac

trilader@BETABOX /f/foo (master)
$ /f/libgit2-master/build/examples/describe.exe --always
Failed to describe rev 'HEAD' [-1] - Cannot describe - No reference found, cannot describe anything.
```

Note the output from git describe --always.
I expected something similliar from the describe example . This only fails when there are no tags. If I use the --all option it works. As far as I know the --always option should still work, even if there are no tags present in the repository. In fact normal git works just fine with that option.
```
trilader@BETABOX /f/foo (master)
$ git describe --tags --always --long
0f52fac
```

I am working with the master branch with revision 5dcd2d6628dcebbb69860ccdd9b7e2ef9851a546

**Comment by carlosmn** [comment]
Fixed by #3033
