### ISSUE TITLE
Unexpected HTTP status code: 401

### ISSUE THREAD

**Issue by b35li** [libgit2/libgit2#3021]
Hi 
I ran into an error which shows as following:
```
Starting....
panic: Unexpected HTTP status code: 401

goroutine 1 [running]:
main.clone()
	/var/www/dev/test/gitcli.go:33 +0x14f
main.main()
	/var/www/dev/test/gitcli.go:78 +0xdf

goroutine 17 [syscall, locked to thread
```

Does anybody know how I fix the problem? Thanks very much, it blocks me two days.
here is snippet of code: 
```
  3 import (
  4     "fmt"
  5 
  6     "gopkg.in/libgit2/git2go.v22"
  7 )
  8 
  9 func credentialsCallback(url string, username string, allowedTypes git.CredType) (git.ErrorCode, *git.Cred) {
 10     // Tried my OS X username, Github username and 'git' here
 11     // I also tried git.NewCredSshKeyFromAgent below
 12     ret, cred := git.NewCredSshKey("git", "~/.ssh/id_rsa.pub", "~/.ssh/id_rsa", "")
 13     fmt.Println(cred.Type())
 14     return git.ErrorCode(ret), &cred
 15 }
 16 
 17 // Made this one just return 0 during troubleshooting...
 18 func certificateCheckCallback(cert *git.Certificate, valid bool, hostname string) git.ErrorCode {
 19     return 0
 20 }
 21 
 23 func clone() {
 24     cb := &git.RemoteCallbacks{
 25         CredentialsCallback: credentialsCallback,
 26         CertificateCheckCallback: certificateCheckCallback,
 27     }
 28     co := &git.CloneOptions{
 29         RemoteCallbacks: cb,
 30     }
 31     repo, err := git.Clone("http://{username}@{internalproject}", "proj", co)
 32     if err != nil {
 33         panic(err)
 34     }
 35     fmt.Println(repo.Config())
 36 }


```

**Comment by ethomson** [comment]
Hi @b35li - sorry to see that you're having troubles.

First, I would recommend posting this on the git2go project.  It's possible that this is a libgit2 issue, but it's also possible that this is a git2go issue, and I'm not familiar enough with that project to know so it might take someone there to unravel this to the level that we can help.

(You might want to read their README, also:  we prefer opening issues like this on stackoverflow and reserve issues for known bugs.  It's possible they do, too.)

However I would suggest that the problem likely lies with trying to use an ssh key to authenticate to an HTTP endpoint.  I think you probably want to use SSH keys over SSH and basic auth over HTTP.

Good luck, and we'll circle back here if this does turn out to be a problem in libgit2; until then I'm going to close this in favor of a git2go issue.  Thanks!

**Comment by b35li** [comment]
@ethomson I will do that. thanks for your quick reply.
