### ISSUE TITLE
error "The global/xdg file 'config' doesn't exist" on Windows

### ISSUE THREAD

**Issue by capr** [libgit2/libgit2#3025]
Hi, 

I get this error "The global/xdg file 'config' doesn't exist: The system cannot find the path specified" when trying to open _any_ repository on Windows (return value -1, e.klass = 2).

Any idea what's wrong here?

---------
I built libgit2 without iconv and without ssh with mingw-w64 gcc 4.9.2 like this:

<pre>
gcc -c -O2 -DGIT_ARCH_64 -DWINVER=0x501 src/win32/*.c \
	src/*.c -Isrc -Iinclude \
	src/xdiff/*.c -Isrc/xdiff \
	src/hash/hash_generic.c -Isrc/hash \
	src/transports/*.c -Isrc/transports \
	deps/regex/regex.c -Ideps/regex \
	deps/http-parser/http_parser.c -Ideps/http-parser \
	-I../zlib
gcc *.o -shared -o ../../bin/mingw64/git2.dll -L../../bin/mingw64 -lz -s -static-libgcc -lws2_32
</pre>

(assuming zlib headers are at ../ and binary at ../../bin/mingw64)

PS: even if the above is not the cmake way to build, the result is a binary that works on OSX and Linux, both 32bit and 64bit (if you don't count ssh and unicode paths).

**Comment by ethomson** [comment]
No, I don't think that it will.  You're not setting any of the preprocessor definitions (like `GIT_WIN32`) that are pretty likely to be important to getting a working library.

If you use cmake to build a mingw64 target and build that, do you have the same error?

**Comment by arrbee** [comment]
I know this was a bug in an old version of libgit2. Do you know what version of the sources you're using?

**Comment by capr** [comment]
>
> No, I don't think that it will. You're not setting any of the preprocessor
> definitions (like GIT_WIN32) that are pretty likely to be important to
> getting a working library.
>
>
Hi, and thanks fore responding.

Mingw-w64 sets _WIN32 automatically, and then libgit2/common.h defines
GIT_WIN32 based on that, so I think that's covered. Are there other things
that I have to set for mingw?

I compiled again with -D__USE_MINGW_ANSI_STDIO=1 -D_FILE_OFFSET_BITS=64
-DGIT_WIN32 -DWIN32  -D_WIN32_WINNT=0x0501 (i.e. all ADD_DEFINITIONS()
entries in CMakeLists.txt for mingw) and I get the same error.

> If you use cmake to build a mingw64 target and build that, do you have
the same error?

> Will try that next, I just didn't want to have to bring in iconv and
openssl. Can I build libgit2 without dependencies with mingw-w64? I don't
need transports except filesystem.

Thanks.

**Comment by capr** [comment]
@arrbee  0.22.2 release - should I try with master?

**Comment by ethomson** [comment]
If you use master you will not need OpenSSL for mingw.  (You do not need iconv, except on Mac OS.)

Sorry, I know cmake is a pain, but it's easier to narrow down this issue with a known-good quantity.  Unless you happen to know you have an odd roaming profile or a strange `%LOCALAPPDATA%` or your `%HOME%` is missing or something along those lines then I would want to rule this out first.  (Our install base on Windows is very large and I haven't seen this issue in releases >= 0.22 or master.)

**Comment by capr** [comment]
>
> If you use master you will not need OpenSSL for mingw. (You do not need
> iconv, except on Mac OS.)
>

Ok, I'll try that.


> Sorry, I know cmake is a pain, but it's easier to narrow down this issue
> with a known-good quantity.
>

Ok, I'll try it with cmake/master, see how it turns out.


> Unless you happen to know you have an odd roaming profile or a strange
> %LOCALAPPDATA% or your %HOME% is missing or something along those lines
> then I would want to rule this out first. (Our install base on Windows is
> very large and I haven't seen this issue in releases >= 0.22 or master.)
>

Actually, %HOME% is missing on stock WinXP32, WinXP64 and Win7 and
%LOCALAPPDATA% is only set on Win7.

Well, obviously I'm doing something wrong if no one else is complaining
about it... will poke around some more then.

One last question if you please -- what is xcb config? Should libgit2 even
look for it on Windows, or is the fact that is looking for it in the first
place an indication that something is wrong with my build?

**Comment by carlosmn** [comment]
@capr have you had a chance to try a build with CMake on a recent build?

**Comment by capr** [comment]
No, I gave up. I tried cmake -G "MinGW Makefiles". First it said it did not want me to have sh.exe in  PATH, I changed that, then it wanted me to install Python. I was like "are you kidding me". Went to the install instructions again, it says "You need to run the CMake commands from the Visual Studio command prompt, not the regular or Windows SDK one." Ok, so MinGW is not even supported, and I do not have a Visual Studio command prompt, only a WinSDK prompt in my Start menu. That's where I gave up. I have bunch of C files and two perfectly usable C compilers and I can't build this.

**Comment by ethomson** [comment]
We do, in fact, support mingw.

If the Python requirement is onerous for you, then you can build without our unit test framework by passing `-DBUILD_CLAR=OFF`.

But given that you're running into a problem with the library that nobody else has seen, I think that the unit tests would be very helpful, so I would encourage you to build them.

**Comment by capr** [comment]
Thanks. That switch allowed cmake to give me a binary. But the binary looks for swprintf_s in msvcrt.dll which is not available in WinXP. Is WinXP64 a suported OS?  If I get a new crt, how do I tell cmake to link against it? (I would prefer to link swprintf_s statically so that I don't have to drag the entire crt around).

**Comment by carlosmn** [comment]
We dropped support for Windows XP a couple of releases ago, around the time Microsoft dropped the extra-extra-extended support cycle for it.

**Comment by carlosmn** [comment]
I'm going to close this as there hasn't been any progress. If you do find out more, feel free to reopen. Do also take note that this particular error message is often left over during the opening of a repository, and if no error has happened or a function failed to set the message, you might be getting an old message.
