### ISSUE TITLE
Rev walk much slower than git.git

### ISSUE THREAD

**Issue by joshaber** [libgit2/libgit2#3034]
Using the following bastardized version of the `rev-list` example:

```c
static int push_range(git_repository *repo, git_revwalk *walk, const char *range, int hide);

int main(int argc, const char * argv[]) {
	git_repository *repo;
	git_revwalk *walk;
	git_oid oid;
	char buf[GIT_OID_HEXSZ+1];

	git_libgit2_init();

	const char *pathToLinux = "/Users/joshaber/Desktop/linux";
	git_repository_open_ext(&repo, pathToLinux, 0, NULL);
	git_revwalk_new(&walk, repo);
	push_range(repo, walk, "master..origin/master", 0);

	while (!git_revwalk_next(&oid, walk)) {
		git_oid_fmt(buf, &oid);
		buf[GIT_OID_HEXSZ] = '\0';
		printf("%s\n", buf);
	}

	git_libgit2_shutdown();
	return 0;
}

static int push_commit(git_revwalk *walk, const git_oid *oid, int hide)
{
	if (hide)
		return git_revwalk_hide(walk, oid);
	else
		return git_revwalk_push(walk, oid);
}

static int push_range(git_repository *repo, git_revwalk *walk, const char *range, int hide)
{
	git_revspec revspec;
	int error = 0;

	if ((error = git_revparse(&revspec, repo, range)))
		return error;

	if (revspec.flags & GIT_REVPARSE_MERGE_BASE) {
		/* TODO: support "<commit>...<commit>" */
		return GIT_EINVALIDSPEC;
	}

	if ((error = push_commit(walk, git_object_id(revspec.from), !hide)))
		goto out;

	error = push_commit(walk, git_object_id(revspec.to), hide);

	out:
	git_object_free(revspec.from);
	git_object_free(revspec.to);
	return error;
}
```

1. `git clone https://github.com/torvalds/linux linux`
2. `cd linux`
3. `git reset --hard HEAD^` so that `origin/master` has a commit unique to it.
4. 
```
$ time git rev-list master..origin/master
f22e6e847115abc3a0e2ad7bb18d243d42275af1

real	0m0.070s
user	0m0.003s
sys	0m0.067s
```
5.
```
$ time my-libgit2-test
f22e6e847115abc3a0e2ad7bb18d243d42275af1

real	0m5.610s
user	0m4.782s
sys	0m0.788s
```

The libgit2 version is almost two orders of magnitude slower.

**Comment by joshaber** [comment]
Oh so another interesting data point. If I then do:

```
git reset --hard origin/master
```

in `linux`, the libgit2 test spits out a lot of SHAs, where git.git rightly outputs no SHAs.

**Comment by carlosmn** [comment]
The last bit is a bug I thought I had fixed, but apparently we don't even have a test for it. It happens because you first hide a commit and then push it. If it were the other way around (first push then hide) it should give you the correct answer of no commits.

**Comment by carlosmn** [comment]
I can't reproduce the slowness. @joshaber are you using an oldish libgit2 version? We used to have to walk down the whole repo in order to hide stuff, but we changed it a while ago. I've put this code into a test in clar on master and it returns in 11ms, just slightly slower than git's 8ms.

**Comment by joshaber** [comment]
Oh so this gets even _more_ mysterious! I just pulled `linux` and now it doesn't reproduce. But I can still reproduce it if I get the repo back to where it was yesterday:

1. `cd linux`
2. `echo f22e6e847115abc3a0e2ad7bb18d243d42275af1 > .git/refs/remotes/origin/master`
3. `git reset --hard origin/master^`

And then run `my-libgit2-test` again.

(This is using libgit@47f37400253210f483d84fb9c2ecf44fb5986849, which is just a few days old.)

**Comment by joshaber** [comment]
If it's helpful at all, here's the output from the top two callstacks in Instruments:

```
Running Time	Self (ms)		Symbol Name
1557.0ms   28.9%	1557.0	 	 packfile_unpack_compressed
1557.0ms   28.9%	0.0	 	  git_packfile_unpack
1557.0ms   28.9%	0.0	 	   pack_backend__read_internal
1557.0ms   28.9%	0.0	 	    pack_backend__read
1557.0ms   28.9%	0.0	 	     git_odb_read
1557.0ms   28.9%	0.0	 	      git_commit_list_parse
1557.0ms   28.9%	0.0	 	       mark_uninteresting
1557.0ms   28.9%	0.0	 	        process_commit
1557.0ms   28.9%	0.0	 	         prepare_walk
1557.0ms   28.9%	0.0	 	          git_revwalk_next
1557.0ms   28.9%	0.0	 	           main
532.0ms    9.8%	532.0	 	 git_path_exists
532.0ms    9.8%	0.0	 	  locate_object
532.0ms    9.8%	0.0	 	   loose_backend__read
532.0ms    9.8%	0.0	 	    git_odb_read
532.0ms    9.8%	0.0	 	     git_commit_list_parse
532.0ms    9.8%	0.0	 	      mark_uninteresting
532.0ms    9.8%	0.0	 	       process_commit
532.0ms    9.8%	0.0	 	        prepare_walk
532.0ms    9.8%	0.0	 	         git_revwalk_next
532.0ms    9.8%	0.0	 	          main
```

**Comment by carlosmn** [comment]
Huh, that's odd. I can repro on master with those commits too. The difference between these commits is the simplest you could have. There is certainly something quite odd happening here.

**Comment by carlosmn** [comment]
It looks like a bad interaction from hiding the initial commit's parent. We're failing to account for the fact that we immediately run out of interesting commits and spend the whole time marking the whole history as uninteresting.

I've opened PR #3042 which fixes this. We don't have perf tests for this so I'm not sure we have a good way to avoid this kind of thing creeping up again.

**Comment by joshaber** [comment]
:metal: Thanks so much for digging into it!

**Comment by joshaber** [comment]
:boom:

**Comment by eaigner** [comment]
I'm kind of running into the same performance numbers now. It seems the revwalk time depends on the repo size somehow. When I open a repo with a few thousand commits, it's fine. When I open a huge repo like `tensorflow` with 63k commits, the revwalk time seems to go up exponentially, even though I only ever list the first 100 commits.

**Comment by neithernut** [comment]
This is and probably will always be true if the revwalk is configured to sort commits by time. I assume it is in your case?

**Comment by eaigner** [comment]
I assumed that was the problem, but it also happens with no or topo order.
