### ISSUE TITLE
Attaching extra information to error messages

### ISSUE THREAD

**Issue by carlosmn** [libgit2/libgit2#3036]
Our error reporting mechanism is currently fairly simplistic. We return an error code and store an error message and a class. It is sometimes advantageous to add more detailed information about the error which some consumers can make use of. An example would be the HTTP status which the server returned instead of making the caller code parse it out of the error string. One way to do this would be to add a pointer in the struct we return from `giterr_last()` to read this information and provide a function like

``` C
int giterr_attach(git_error_info *info);
```

by which the caller (in libgit2 or external) can attach extra information to the current/last error message. Alternatively,

``` C
int giterr_set_extra(int error_class git_error_info *info, const char *fmt, ...);
```

to do both at the same would should also work. A `giterr_clear()` would also free this structure. The structure itself would be something like

``` C
typedef struct {
    git_error_info_t type;
    char *custom_type;
    void free(git_error_info *);
} git_error_info;
```

which you can subclass in the usual C way. The string is there in case a custom backend wants to provide more detailed information; it can set type to a value such as `GIT_ERROR_INFO_CUSTOM` and it can provide a string to identify which type of custom error it has stored.

There's at least one place where we want to duplicate or store the error state locally to re-set it again (in clone, so the clean up doesn't mess with the clone error) so we need to make sure we don't double-free it, so we'd either want to refcount it or have it provide a `dup` field as well.

/cc @jamill

**Comment by ethomson** [comment]
This is rather old and we didn't pursue it.  Closing this.
