### ISSUE TITLE
git_remote_rename may duplicate remote

### ISSUE THREAD

**Issue by rcorre** [libgit2/libgit2#3043]
In certain cases, `git_remote_rename` will add a new remote but fail to remove the old one.
Here is one such case:

1. Clone a repo
2. Remove remote origin
3. Add remote origin
4. fetch, set master to track origin/master again

After 1-4, you end up with a config containing:

```
[remote "origin"]
[branch "master"]
    remote = origin
    merge = refs/heads/master
[remote "origin"]
    url = https://github.com/libgit2/TestGitRepository
    fetch = +refs/heads/*:refs/remotes/origin/*
```

Now rename origin to origin2.

You now have two remotes: origin and origin2.

I have a failing test case here: https://github.com/rcorre/libgit2/commit/49c39e2ceb51928e73c6bba55fb3f64aebe6a928

There is some general weirdness I've noticed with libgit2 editing config files (e.g. leftover empty sections) that may be related.

I'd like to get more involved with libgit2 and I'm investigating a fix now, but figured I should report the bug in the meanwhile.

**Comment by carlosmn** [comment]
Leftover config headers just happen to stay there. This is what git does as well, as removing them while keeping the rest of the semantics gets odd.

Is there an error when renaming? What does the configuration look like when it's done?

**Comment by rcorre** [comment]
At least in the case of remotes, core git removes the header when you remove a remote.
Rename returns success, and the config looks like:
```
[remote "origin"]
[branch "master"]
    remote = origin
    merge = refs/heads/master
[remote "origin"]
    url = https://github.com/libgit2/TestGitRepository
    fetch = +refs/heads/*:refs/remotes/origin/*
[remote "origin2"]
    url = https://github.com/libgit2/TestGitRepository
    fetch = +refs/heads/*:refs/remotes/origin/*
```

**Comment by carlosmn** [comment]
git happens to remove the header, but that's an implementation detail.

**Comment by rcorre** [comment]
To be clear - when I said rename returns success, I mean the return code indicates success, not that the rename was actually successful.
It creates the new remote (origin2) but fails to remove the entry for origin, so you end up with two remotes.

There are two issues here:
1. remote removal leaves an empty header (maybe not _wrong_, but messy)
2. remote rename is confused by an empty header (wrong)

I'm focusing on 2 right now, but it would be nice if 1 didn't happen either.

**Comment by jamill** [comment]
> It creates the new remote (origin2) but fails to remove the entry for origin, so you end up with two remotes.

It also look like several things point to origin (for instance, the remote for the master branch and the fetchspec for the origin2 remote)

**Comment by rcorre** [comment]
> It also look like several things point to origin (for instance, the remote for the master branch and the fetchspec for the origin2 remote)

Sorry, that was a typo on my part. The master branch is correctly updated to point at origin2.

While renaming, it creates "remote.origin2.fetch" and then tries to remove "remote.origin.fetch".
This removal should happen with the call:
`config_write(backend, "remote.origin.fetch", NULL, NULL)`
which is intended to wipe out the remote.origin.fetch entry.
It fails [here](https://github.com/libgit2/libgit2/blob/master/src/config_file.c#L1457).
`section_matches` is false, as it is currently reading [branch "master"]
`last_section_matched` is true, because we just read [remote "origin"] (the empty header).
This means that instead of consuming the line and continuing, we fall through and stop looking for the actual "origin" entry.

**Comment by carlosmn** [comment]
From your analysis, it looks like we can boil down the bug to trying to delete an entry, given a file

```
[remote "origin"]
[branch "something"]
[remote "origin"]
    url = "foo"
```

and then add a test which opens that and does `cl_git_pass(git_config_delete_entry(cfg, "remote.origin.url")`.

**Comment by rcorre** [comment]
Put in a PR with the failing unittest.
I had to add an entry under the [branch] header to get it to fail.

**Comment by rcorre** [comment]
I have something that makes all the tests pass: https://github.com/rcorre/libgit2/commit/6af9f6f4b46595bc093bc30ef586314652061209

I don't think its the right answer, as I basically obliterated something that was labeled 'sanity check', which is probably not a good sign. With my fix, `git_submodule_save` would trip the sanity check by calling `config_write` with a null value and a key that didn't exist (it is trying to write a NULL `submodule->branch`).

However, maybe it will shed some light on the issue. Basically, the current behavior of `config_write` assumes that, if it matches a section but finds no matching entry, then it is done.
If multiple sections headers are to be supported, `config_write` _has_ to read every section until it finds the target or EOF.
