### ISSUE TITLE
Updating references should use rename instead of truncate and write

### ISSUE THREAD

**Issue by jezell** [libgit2/libgit2#3045]
We see issues occasionally with libgit2 where references get truncated but never updated during a commit create. Taking a look at the source code, it looks like libgit2 introduces this possibility be the way it writes buffers:

https://github.com/libgit2/libgit2/blob/8311db0cf8ae15b46edd14358a8238862e0bac4d/src/fileops.c#L222

First, it truncates the file, then it writes to the file, then it closes the file. If there is any kind of error, machine reboots, process crashes etc. while the operation is in progress then you are left with a corrupted repo. Compare this to the standard git source, where it writes things like references to temporary files and then use a rename operation to swap, which gives an atomic operation instead of a sequence of operations that can result in corruption:

https://github.com/git/git/blob/1e6f5b22ad318446500fbd3b94b733eddd5b6414/lockfile.c#L290

Maybe libgit2 should do something similar to avoid these types of potential corruptions?

**Comment by carlosmn** [comment]
We do use the same technique that git does of locking the file by writing to the ".lock" file and then performing an atomic rename. Our version of `lockfile.c` is called `filebuf.c` and if you look at the references backend, you'll see that's what we use there. We don't use fileops in order to handle ref updates.

**Comment by jezell** [comment]
You're right. I was looking at reflog append operations, but it is locking as you say when it updates the ref. Thanks for pointing in the right direction. Will keep digging to see if I can find out what is causing references to be truncated occasionally.
