### ISSUE TITLE
Only GPL v2?

### ISSUE THREAD

**Issue by burdges** [libgit2/libgit2#3046]
Just noticed the license is GPL v2 only.  If I [understand correctly](https://www.gnu.org/licenses/quick-guide-gplv3.html), one cannot distribute binaries that link `libgit2` with Apache, XFree86, etc. licensed software. 

RMS made a case that [libraries should use GPL rather than LGPL](https://www.gnu.org/philosophy/why-not-lgpl.html) when a "library provides a significant unique capability".  I suppose `libgit2` could easily fit that description, but maybe not in everyone's minds since `git` is such a fixture now. 

A switch to LGPL v3 might maximize usability of the library, while maintaining the "community building" benefits of GPL over permissive licenses.  I presume the "or later" clause can again be dropped from the LGPL since the FSF explicitly designed in that feature. 

In practice, I'd wager this is all a moot point since the linking restriction only impacts the program linking to `libgit2`, not other the libraries the program uses that're licensed under Apache, XFree86, etc.

**Comment by arrbee** [comment]
`libgit2` is under the [GPL v2 with Linking Exception license](https://en.wikipedia.org/wiki/GPL_linking_exception), a la the GCC runtime. This allows the linking of `libgit2` into applications which are not themselves GPL, but requires you to donate back any changes you make to libgit2. It has worked pretty well so far IMO.

Is there a specific case where we have not "maximized usability" of the library that you feel is missing?

**Comment by burdges** [comment]
Oops, I'm not seeing the forest of the trees!  lol
