### ISSUE TITLE
Revisit the use of readdir_r()

### ISSUE THREAD

**Issue by carlosmn** [libgit2/libgit2#3057]
The `readdir_r()` interface is rather terrible, as it makes you assume what the output size is going to be. It is supposed to be the reentrant/threadsafe version of `readdir()` but within our threading model it is unlikely that we need it. The buffer returned by `readdir()` is shared only within the same directory stream, which is not something we share across threads.  The operations we expose keep their directory streams to themselves, and as we only support using an object from a single thread at a time, there is no race within a single directory stream for the "basic" `readdir()` to cause us issues.

AFAICT the Win32 equivalent for this behaves roughly the same, so we should be able to get rid of all our uses of `readdir_r()` which would make us a lot safer against oddly-sized entries.

**Comment by carlosmn** [comment]
Turns out there was only the one place, and #3220 takes care of it.

**Comment by ethomson** [comment]
Yep!  It had also been in `path_dirload_with_stat` which we got rid of in #3087!
