### ISSUE TITLE
git_diff_delta->nfiles is 2 for GIT_DELTA_UNMODIFIED instead of 1

### ISSUE THREAD

**Issue by swisspol** [libgit2/libgit2#3061]
This is what I found from experimenting and perusing the code:
```
nfiles = 1
  GIT_DELTA_DELETED
  GIT_DELTA_ADDED
  GIT_DELTA_IGNORED
  GIT_DELTA_UNTRACKED
  GIT_DELTA_UNREADABLE
  
nfiles = 2
  GIT_DELTA_UNMODIFIED
  GIT_DELTA_MODIFIED
  GIT_DELTA_RENAMED
  GIT_DELTA_COPIED
  GIT_DELTA_TYPECHANGE
```
Everything makes sense considering the definition of `nfiles` except for the `GIT_DELTA_UNMODIFIED` case: it should really be 1.

**Comment by swisspol** [comment]
Note that the fix is not trivial (that's why I don't have a patch for it yet) as `git_diff_delta`s can start with different states and then end up as `GIT_DELTA_UNMODIFIED` following concatenating added/deleted or realizing that a file that was potentially modified was not.

**Comment by ethomson** [comment]
I don't agree, I think that this is by-design and I think that this is exactly what I would expect.  You *do* have two files - an *old* side and a *new* side.  That they're the same doesn't meant that you're missing one.

The other cases where `nfiles = 1` really only have *one file*.  The other side was non existent to begin with, or deleted after the fact.

Please reopen if I'm very much missing the point here.
