### ISSUE TITLE
libgit2 tries to remove out-of-tree symlinks

### ISSUE THREAD

**Issue by WrinklyNinja** [libgit2/libgit2#3068]
loot/loot#417 details an issue filed by one of my users, who had replaced their AppData folder with a junction link to another location. My program clones a repository to a subfolder within AppData, and they were finding that libgit2 was returning the following error when it tried to do so.

> `Error: -4; Failed to remove symlink 'C:/Users/UsrName/AppData': Access is denied.`

Adding the `GIT_CHECKOUT_DONT_REMOVE_EXISTING` checkout strategy flag to the clone options structure (I was already using `GIT_CHECKOUT_FORCE`) prevented the error from occurring. 

However, my understanding is that libgit2 should be trying to remove files/symlinks *within* the target directory, not removing symlinks at all points in the path to that directory, so this looks like a bug.

**Comment by ethomson** [comment]
Git does not follow symbolic links in the working tree when writing.  If there is a symbolic link, it will remove it during checkout (if instructed to remove files).

Do you not observe that Git itself behaves similarly?

**Comment by WrinklyNinja** [comment]
I haven't tried: that's very counter-intuitive behaviour if so.

My understanding as a Git user is that its working tree has its root at the root of the local repository (because Git never refers to files outside that), and so all local operations are performed within that folder (besides the initial creation of the folder, of course). I've never encountered any behaviour before that would suggest otherwise, so when I run `git checkout -f` (or the equivalent with libgit2), I don't expect it to try removing files outside the repository folder.

Now, my assumptions seem to be flawed, but I think they're reasonable. The current behaviour allows damage to be unwittingly caused to the filesystem (in this case permissions stopped that happening, but that's not a given), so I think that the current behaviour should be changed, or at least the documentation updated to make the scope of possible changes very obvious.

**Comment by ethomson** [comment]
I think I misread your initial report.  Indeed, if your repository is beneath a symbolic link, then we should cope with this without too much difficulty.

I'll take a look.

**Comment by idealist1508** [comment]
Any progress on that?
