### ISSUE TITLE
Does `st_dev` matter for Windows?

### ISSUE THREAD

**Issue by ethomson** [libgit2/libgit2#3069]
Presently in `p_lstat` we assign `st_dev` to `_getdrive()` which is almost certainly incorrect.  We _probably_ want to actually use the device that the repository is on.  Realistically we probably only care about compatibility with Git for Windows (in the index) however we should make sure that this is not otherwise used.

Note that a simple drive letter translation to a device number may not be adequate since:

1. What do we do for UNC paths?
2. What do we do if you mount a volume inside a different drive letter?
3. Does any of this actually matter?

**Comment by whoisj** [comment]
Per this [MSDN article](https://msdn.microsoft.com/en-us/library/14h5k7ff.aspx), and I quote "`st_dev`, and `st_rdev` fields in the `_stat` structure are meaningless."

**Comment by ethomson** [comment]
Correct me if I'm wrong, but we don't call the Windows POSIXy `stat`.  We call `GetFileAttributesExW` and populate a `struct stat` with our own information.

**Comment by whoisj** [comment]
As best I can tell, that is correct. I'm not finding which use of the filed outside of link creation, which isn't allowed on Windows anyways.

**Comment by carlosmn** [comment]
This information isn't crucial on posix systems either. It's one of those fields we can use to figure out if a file has changed but it shouldn't hurt too much if we zero it out.

**Comment by carlosmn** [comment]
As an extra data point, using `st_dev` is a compile-time option in git, which is turned off by itself due to its instability across network filesystems, so it looks like we can simply not look at it and be perfectly fine.

**Comment by carlosmn** [comment]
So I think what we should do is write 0 there always and never use it for comparison. Most git builds won't do it either.
