### ISSUE TITLE
Submodule reload does not notice an externally removed branch setting

### ISSUE THREAD

**Issue by carlosmn** [libgit2/libgit2#3077]
When you call `git_submodule_reload()`, it will go through the settings which are set. This however does not notice if the branch setting was removed by an external process. The current test for `_save()` and `_reload()` hides this fact by re-using the same object, which already has the branch unset when it reloads.

I came across this while trying to remove `git_submodule_save()` in the same way I've been removing `git_remote_save()` which hightlighted this bug, though I suspect there may be more hiding.

I would also like to remove `git_submodule_reload()` in favour of simply calling `git_submodule_lookup()` in order to remove this kind of accidental sharing; unless someone has some use-case which cannot work.

// @jamill

**Comment by jamill** [comment]
seems reasonable to me, thanks for the heads up.

**Comment by carlosmn** [comment]
This should be handled by #3097

**Comment by carlosmn** [comment]
Solved by not doing any reloading in the new submodules code.
