### ISSUE TITLE
Got some warnings when building with gcc 4.8

### ISSUE THREAD

**Issue by tfarina** [libgit2/libgit2#3078]
../tests/rebase/merge.c:514:14: warning: unused parameter 'path' [-Wunused-parameter]
  const char *path,
              ^
../tests/rebase/merge.c:515:9: warning: unused parameter 'completed_steps' [-Wunused-parameter]
  size_t completed_steps,
         ^
../tests/rebase/merge.c:516:9: warning: unused parameter 'total_steps' [-Wunused-parameter]
  size_t total_steps,
         ^

**Comment by ethomson** [comment]
That seems correct; is this something that you would be able to fix with a pull request? Thanks!

**Comment by tfarina** [comment]
No, sorry. I usually don't send pull requests. I leave that to maintainers.
