### ISSUE TITLE
Android build should depend on -DANDROID instead of -DANDROID=1

### ISSUE THREAD

**Issue by yongthecoder** [libgit2/libgit2#3080]
It seems that most projects depend on -DANDROID instead of -DANDROID=1 for their android builds.

android.toolchain.cmake defines ANDROID in this way:
remove_definitions( -DANDROID )
add_definitions( -DANDROID )

Should libgit2 also depend on -DANDROID instead of -DANDROID=1?

**Comment by ethomson** [comment]
Sorry, can you enlighten me?  I don't immediately see where it is that we're checking for an `ANDROID == 1`?

**Comment by yongthecoder** [comment]
@ethomson In README.md: Add `-DCMAKE_TOOLCHAIN_FILE={pathToToolchainFile} -DANDROID=1` to cmake command

In CMakeLists.txt:

# Include POSIX regex when it is required
IF(WIN32 OR AMIGA OR ANDROID OR CMAKE_SYSTEM_NAME MATCHES "(Solaris|SunOS)")
	INCLUDE_DIRECTORIES(deps/regex)
	SET(SRC_REGEX deps/regex/regex.c)
ENDIF()

**Comment by ethomson** [comment]
The CMake `ADD_DEFINITIONS` and `REMOVE_DEFINITIONS` concern themselves with compiler flags.  So `ADD_DEFINITIONS(-DANDROID)` would specify that the resultant Makefiles should add a `-DANDROID` compiler flag.

Our README is about specifying to CMake itself that you want to perform an Android build.  Since we use a CMake option for it, you can also build with `-DANDROID=ON`...  or any valid CMake syntax.  There is not much option for libgit2 to influence CMake's command-line parsing behavior.

**Comment by yongthecoder** [comment]
Thanks for the explanation. I got it now. It is possible for libgit2's CMakeLists.txt to detect the compiler flag and know it is targeted to Android, but that may not be a good idea. I'll close the issue. Sorry for the buzz.

**Comment by yongthecoder** [comment]
My co-worker's further investigation found that android.toolchain.cmake does set( ANDROID True ). But sometimes it doesn't work because libgit2's cmake sets ANDROID as a cached option which default value is off. The fix should be set( ANDROID CACHE True ) in android.toolchain.cmake.

**Comment by ethomson** [comment]
We do not have an `android.toochain.cmake` in our build tree.  Can you clarify what you mean?

**Comment by yongthecoder** [comment]
A cmake script developed by OpenCV android project. 
 
https://code.google.com/p/android-cmake/
https://code.google.com/p/android-cmake/source/browse/toolchain/android.toolchain.cmake

I know it is nothing about libgit2. It is just that "set( ANDROID True )" didn't always work with libgit2. Adding "CACHE" can solve that. We first didn't notice this and got crash in regfree() because deps/regex was compiled.

Again, nothing wrong with libgit2.

**Comment by ethomson** [comment]
I see.  I'm afraid that I'm not very familiar with building for an android environment, so please let me know if there's anything we can do to help you out here!

**Comment by yongthecoder** [comment]
Thank you so much. Actually Android does have regex API. But that causes crashes in config.c. If I always check multivar_iter.have_regex and set&check all_iter.has_regex before calls to regfree()/regexec(), it works. I'll create another issue and post a patch
