### ISSUE TITLE
Android build crashes in regfree() when using system's regex API

### ISSUE THREAD

**Issue by yongthecoder** [libgit2/libgit2#3082]
Currently the Android build uses deps/regex. That works. However Android does have the POSIX regular expression API. The real problem is libgit2 crashes in git_remote_create() when using Android's regex functions. The root reason is multivar_iter_free() calls regfree() even when have_regex=0.

My proposed solution is
1) always check "multivar_iter.have_regex" before calling regfree() or regexec()
2) set and use all_iter.has_regex
3) rename has_regex to have_regex or rename have_regex to has_regex, to make the naming consistent.
4) modify the cmake file so ANDROID doesn't need deps/regex.

**Comment by yongthecoder** [comment]
Maybe this is also the reason why Solaris/Sun OS also needs deps/regex

**Comment by yongthecoder** [comment]
I cannot find an Android 2.2 (froyo) device or emulator. But I think the original problem (https://groups.google.com/forum/#!topic/android-ndk/BepvBlDw4_w) is a packaging bug in Android NDK 4, and now people are using Android NDK 10 (which can still be used to develop froyo native libraries). The libc.so in Android NDK 10 for Android 2.2 (froyo) does contain the regex functions. (Froyo's Android API level is 8). This means the native library should be able to use these functions on Android 2.2 devices. Removing deps/regex from Android build can only break those projects that still use Android NDK 4. Should we worry about that?

android-ndk-r10c/platforms/android-8/arch-arm/usr/lib$ arm-linux-androideabi-objdump -t libc.so | grep reg
00008044 g     F .text	00000014 __atexit_register_cleanup
0000b230 g     F .text	00000014 regcomp
0000b244 g     F .text	00000014 regerror
0000b258 g     F .text	00000014 regexec
0000b26c g     F .text	00000014 regfree
0000b6b8 g     F .text	00000014 setregid

**Comment by yongthecoder** [comment]
Of course the crash should be fixed first

**Comment by carlosmn** [comment]
Fixed via #3086
