### ISSUE TITLE
git_fetch__download_pack() unused function?

### ISSUE THREAD

**Issue by tfarina** [libgit2/libgit2#3093]
https://github.com/libgit2/libgit2/blob/master/src/fetch.h#L16

$ g grep git_fetch__download_pack
src/fetch.h:int git_fetch__download_pack(

Bye,

**Comment by meestaplu** [comment]
This function was originally added in commit 2c982daa2eec64b80c7940bfe1142295bd72edd8 on October 5, 2011.  The implementation was removed in commit 41fb1ca0ec51ad1d2a14b911aab3215e42965d1b on October 29, 2012, but the function declaration remains.  It is safe to remove the declaration at this point.
