### ISSUE TITLE
Unsupported index version for git index v4

### ISSUE THREAD

**Issue by smathieu** [libgit2/libgit2#3107]
Our distribution of git is configured to use the version 4 of the index file. As far as I understand it, that was done because it's much faster than the previous version. It seems like libgit2 does not currently support it. Reading the index causes the following error:

    Could not get the index! [-1] - Invalid data in index - incorrect header version

Any known workaround or idea on how to fix it?

**Comment by carlosmn** [comment]
Using index v4 can be faster in some situations where there is a significant amount of data to be written, though most non-huge projects shouldn't see too much of a difference.

As this is not activated by default and not too many people use v4, it's not a priority for us to implement support for this. The only workaround here would be to ask git to write out a v2 index and use that version.

**Comment by smathieu** [comment]
If we send a PR implementing support for it, would you be interested in merging it or do you not want to add support for it?

**Comment by carlosmn** [comment]
We'd like to have the extension, if you can write it, we'll take a loot at the PR.

**Comment by linquize** [comment]
ping!

**Comment by ethomson** [comment]
This is now being tracked in #3789
