### ISSUE TITLE
dst_refname not set in push_negotiation callback when deleting refs on remote

### ISSUE THREAD

**Issue by swisspol** [libgit2/libgit2#3126]
If I do a push to delete a remote branch by passing a refspec like `:refs/heads/master`, the `push_negotiation` callback gets called with a single `git_push_update` like this:
```
(lldb) p *update
(git_push_update) $1 = {
  src_refname = 0x000060800000a470 ""
  dst_refname = 0x000060800000a480 ""
  src = (id = "")
  dst = (id = "\xb31kz\xa7\x97T\xb2{r\x983\x1a/n\x86NE\x932")
}
```
`src` is a zero OID and `src_refname` is empty which is expected, but `dst_refname` is not set to `refs/heads/master`.

Seems like a bug, and in any case, having this ref name would be required to comply with the description of the `pre-push` hook (from http://git-scm.com/docs/githooks):

> If the foreign ref does not yet exist the <remote SHA-1> will be 40 0. If a ref is to be deleted, the <local ref> will be supplied as (delete) and the <local SHA-1> will be 40 0.

This implies that `<remote ref>` can never be an empty string.

**Comment by carlosmn** [comment]
>src is a zero OID [...] which is expected,

This is the opposite of what should be expected. `src` is the current ID, which is not zero, `dst` should be zero which is what we want the ref to point to.
