### ISSUE TITLE
Invoke `on_update_tips` for opportunistic updates

### ISSUE THREAD

**Issue by nulltoken** [libgit2/libgit2#3134]
- Given I Init a new repository
- And I create a remote named `testRemote` pointing to  `https://github.com/libgit2/TestGitRepository`
- When I git_remote_fetch() using `refs/heads/first-merge:refs/remotes/testRemote/master` as a refspec
- Then `on_update_tips` should be called for `refs/remotes/testRemote/master` and `refs/remotes/testRemote/first-merge`

This currently doesn't pass. `on_update_tips` callback doesn't get invoked for `refs/remotes/testRemote/first-merge`

**Comment by carlosmn** [comment]
#3127 now has a fix for this.
