### ISSUE TITLE
Release v0.23 and v0.22.3

### ISSUE THREAD

**Issue by carlosmn** [libgit2/libgit2#3135]
It's about time we release the next libgit2, and the last maintenance release of the current one. I would like the submodule changes to make it in as that's one the last pieces of API which I know we would have to change before long-term support.

This release should be one of the last before we agree on long-term support for the existing API and release 1.0.

### For v0.23

- [x] See what PRs we want to merge
- [x] Check to see if there's anything missing in CHANGELOG
- [x] Choose a codename "Entschuldigung"
- [x] Bump the SOVERSION
- [x] Bump the version string and defines
- [x] Update the 101 examples
- [x] Check for leaks
- [x] Create the maint branch

### For v0.22.3 :heavy_check_mark: 

- [x] See which fixes are worth backporting from master
- [x] Bump the version string and defines

**Comment by b35li** [comment]
When the release will be made?

**Comment by carlosmn** [comment]
Soon, hopefully. I plan to make the maintenance release today. v0.23 still needs some work.

**Comment by carlosmn** [comment]
libgit2 v0.22.3 is out now, to be followed hopefully this week by the first rc for v0.23.

**Comment by carlosmn** [comment]
The examples have a PR to update them, libgit2/libgit2.github.com#54
