### ISSUE TITLE
git2.dll is missing from your computer

### ISSUE THREAD

**Issue by AJSclyn** [libgit2/libgit2#3141]
I'm unsure where to post my question, but I am having trouble installing libgit2 into my project.  Whenever I try to run my program, this is the error I get:
![image](https://cloud.githubusercontent.com/assets/10897508/7727783/247bd030-fed9-11e4-8211-7417caa8a8bf.png)

I'm using Visual Studio Express 2012, and I followed the instructions in the link below starting from "Notes for Visual Studio" to "Linking and Usage":
https://libgit2.github.com/docs/guides/build-and-link/

I'm receiving 10 warnings after building with CMake

![image](https://cloud.githubusercontent.com/assets/10897508/7727921/00abce02-feda-11e4-90b0-d802b28ceb9f.png)

**Comment by carlosmn** [comment]
Did you build it statically or dynamically? If dynamically, did you put git2.dll where the Windows loader would expect it? This is typically on the same directory as your program or library.

**Comment by AJSclyn** [comment]
Yes I was able to figure that out.  Now I was wondering if you had any
experience building libssh2 with libgit2?  I have libgit2 built, but I need
to build libssh2 now.  It doesn't have a CMakeList.txt file so I'm unsure
how to build it.

Thanks in advance,

On Thu, May 21, 2015 at 8:17 AM, Carlos Martín Nieto <
notifications@github.com> wrote:

> Did you build it statically or dynamically? If dynamically, did you put
> git2.dll where the Windows loader would expect it? This is typically on the
> same directory as your program or library.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/libgit2/libgit2/issues/3141#issuecomment-104253007>.
>



-- 
AJ Saclayan

**Comment by carlosmn** [comment]
I've never built it on Windows. Released versions of libgit2 have an option to embed libssh2 into our build system, but that has been removed in master.

libssh2 is a completely different project from libgit2. We have nothing to do with their build system. If you're having issues, the libssh2 project itself would be the place go to seek help.

As you mention the original issue is solved, I'm closing the issue.
