### ISSUE TITLE
Make git_remote_ls automatically attempt to connect if the remote isn't already connected

### ISSUE THREAD

**Issue by nulltoken** [libgit2/libgit2#3156]
...And as such behave like **[git_remote_upload()](https://github.com/libgit2/libgit2/blob/master/src/remote.c#L2339-L2341)**

**Comment by carlosmn** [comment]
`git_remote_ls()` is an accessor, not action. It has nothing in common with `git_remote_upload()`.

**Comment by nulltoken** [comment]
An accessor? It doesn't look return a private member of the type. It performs a call over the transport (usually a network based one), interprets the result and perform some transformation. Looks rather like an action to me.

Or did I misunderstand you?

**Comment by carlosmn** [comment]
All `git_remote_ls()` does is call its equivalent in the loaded transport, which is the one which actually owns the transport. What the transport then does is extract a `git_vector` into the array and size components. There is no transformation made, just a function call and assigning a couple of pointers.
