### ISSUE TITLE
Feature: multiple worktrees

### ISSUE THREAD

**Issue by max630** [libgit2/libgit2#3159]
There is a new feature in git master: https://github.com/git/git/commit/68a2e6a2c8 , as far as I understand to be released eventually. It allows to create linked worktrees, or checkouts, which have another HEAD, index and working tree but reuse objects, references and other things in repository. They have different format and would not be read by older software.

It would be nice if the libgit supports the linked checkouts, at least reading them (aka COMMON_DIR support).

**Comment by carlosmn** [comment]
Eventually we should support it, but until it reaches widespread use, it's going to have to have a low priority.

**Comment by carlosmn** [comment]
There now has been a release of git with support for multiple worktrees, but this is still not officially supported. The release notes carefully elided how to use this, and there are still patches in-flight which attempt to make different bits of git aware of per-worktree information.

We'll have to wait for that to settle before trying to implement it.

**Comment by balaclark** [comment]
Any update on support for this? This is breaking several clients including gitup http://forums.gitup.co/t/git-worktree-support/353

**Comment by carlosmn** [comment]
There's a PR, but it's going to take some time until we can review it (as it means multiple people learning the inner workings). That feature isn't even stable in git itself, so implementing it right now means we'll still be broken for an arbitrary number of situations and versions.

**Comment by D-Giantis** [comment]
I tried to migrate from bazaar to git a while ago, and failed, because I could not set up worktrees with tortoisesvn, and they said it was because libgit2 wasn't ready to handle worktrees.

I wonder if you know if there is any path for migrating from bazaar to git, in the case that your clients are accustomed to being able to have multiple branches opened simultaneously (which is what worktrees in git address, and what bazaar provides natively)?

**Comment by dakotahawkins** [comment]
Worktrees seem very stable in Git, they're basically the only way I can work now.

**Comment by lexx9999** [comment]
In my work we have on a huge git repository (.git folder is about 2.5 GB), and it would be really helpful if TortoiseGit would support worktrees and support in libgit would allow them to start supporting it.

**Comment by Phoenix-** [comment]
Year and a half has passed - still no news?

**Comment by pks-t** [comment]
I will soon-ish come back to this, rebase and implement the missing bit. Probably around mid-October.

**Comment by ikashkuta** [comment]
Today is almost November, do you need any help with this? I use Gitup as main commit tool and it depends on this feature.

**Comment by pks-t** [comment]
Yeah, I know. That's the thing with plans, they never work out the way one wishes :/
Anyway, I only started rebasing the branch a few minutes ago and will at least have it updated then. The most important thing missing is support for configs and code reviews. If you want to work on this, I'd be grateful to have some kind of code review on my PR after I've rebased.

**Comment by sebres** [comment]
Just to link the PR #3436 (I suspect it would be solution for this "issue")

**Comment by kamalmarhubi** [comment]
Does #3436 being merged mean this issue is closed?

**Comment by ethomson** [comment]
Yes, thanks @kamalmarhubi 😄
