### ISSUE TITLE
libgit2 fails to parse commit with dual author field from FreeSWITCH repo

### ISSUE THREAD

**Issue by swisspol** [libgit2/libgit2#3182]
```
git clone https://freeswitch.org/stash/scm/fs/freeswitch.git
```

Then open the repo with libgit2 and attempt to load the commit `487128950df6ee433c131b5feaafe81ee86629f4`. It will fail with the error "Failed to parse signature - expected prefix doesn't match actual".

If we look at the commit object with `git cat-file commit 487128950df6ee433c131b5feaafe81ee86629f4` we get:

    tree 070633dfc3ea352dfb1094822f477111e519a9ca
    parent cde20f6fe68523d9416d2fed72435a8ba880a269
    author Travis Cross <tc@traviscross.com> 1395382322 +0000
    author Anthony Minessale <anthm@freeswitch.org> 1394747953 +0500
    committer Travis Cross <tc@traviscross.com> 1395665690 +0000
    
    Use the system version of APR / APR-util if possible
    
    Autodetect whether the system libapr / libaprutil has our
    necessary modifications and use it if it does.

As you can see, there are 2 author fields and 1 committer field instead of 1 author and 1 committer. Looks like libgit2 fails on parsing the commit because of this (after `author` it expects `committer` but finds instead another `author`).

**Comment by swisspol** [comment]
There's another commit with the same issue: `8574988c3a378b4d5861ecaeb0e958657635703b`.

**Comment by peff** [comment]
Yeah, I've seen these same commits before (long ago somebody wrote a blog post saying "here's a clever idea for paired programming!" without actually checking what git thinks of it). For the record, these commits are bogus, and `git fsck` will complain (and sites like GitHub will block them from being pushed). But git tries hard to be lenient in commands like `git log` and show what it can without dying.

So I think there is room for improvement in libgit2 by also parsing more leniently.

**Comment by swisspol** [comment]
Indeed
```sh
$ git fsck
Checking object directories: 100% (256/256), done.
error in commit 487128950df6ee433c131b5feaafe81ee86629f4: invalid format - expected 'committer' line
error in commit 8574988c3a378b4d5861ecaeb0e958657635703b: invalid format - expected 'committer' line
Checking objects: 100% (261388/261388), done.
```

**Comment by linquize** [comment]
does libgit2 has API to prepare a commit object with multiple author fields?

**Comment by carlosmn** [comment]
@linquize commits have a single author, even if we're lenient with parsing, we won't create this kind of invalid commit.
