### ISSUE TITLE
Missing documentation for git_treebuilder_create

### ISSUE THREAD

**Issue by ltworf** [libgit2/libgit2#3186]
The function ```git_treebuilder_create(git_treebuilder **builder_p, const git_tree *source)``` has been removed from the last release.

Besides from noting that the function is not available in the ```HEAD``` version, the documentation gives no information on how to replace it.

**Comment by carlosmn** [comment]
See the changelog which is where these changes are documented.

**Comment by ltworf** [comment]
Perhaps mention in the documentation to check the changelog or link it directly to the relevant part would be beneficial.

Thanks!
