### ISSUE TITLE
API: git_reference__alloc_symbolic issue on Mac OS X

### ISSUE THREAD

**Issue by JerryYangJin** [libgit2/libgit2#3190]
Hello, I'm trying to build git mysql backend using libgit2, I've test odb&refdb functions on windows, it's working fine. But when I test on Mac OS X 10.10, I found issue in api: git_reference__alloc_symbolic

environment:

* Mac OS X 10.10 64-bit
* Xcode 6.1
* libgit2 v0.22.2

my refdb_lookup code:

```c
                // fetch ref from mysql by ref_name
		if (type == GIT_REF_OID){
			git_oid_fromstr(&target, target_buf);
			*out = git_reference__alloc(ref_name, &target, NULL);
		}
		else if (type == GIT_REF_SYMBOLIC) {
                        // code goes here for this scenario
                        // ref_name = 'HEAD'
                        // target_buf = 'refs/heads/master'
			*out = git_reference__alloc_symbolic(ref_name, target_buf);
                        // the returned ref->db is null
		}
		else {
			giterr_set_str(GITERR_REFERENCE, "unknown ref type returned");
			error = GIT_ERROR;
		}
```

refdb.c - git_refdb_lookup function

```c
int git_refdb_lookup(git_reference **out, git_refdb *db, const char *ref_name)
{
	git_reference *ref;
	int error;

	assert(db && db->backend && out && ref_name);

	error = db->backend->lookup(&ref, db->backend, ref_name);
	if (error < 0)
		return error;

	GIT_REFCOUNT_INC(db);
	ref->db = db; // error here: Thread 1: EXC_BAD_ACCESS(code=1, address=0x170b4d0)
        // ref->db is null here

	*out = ref;
	return 0;
}
```

snapshot:

![screen shot 2015-06-08 at 10 14 14 pm](https://cloud.githubusercontent.com/assets/2571533/8036648/c7e604b4-0e2b-11e5-82b4-7433918fba83.png)

It looks like API git_reference__alloc_symbolic return a ref with NULL db member, please correct me if I'm wrong. This part works fine on windows 7 32-bit.

Please advise, thanks!

**Comment by ethomson** [comment]
> It looks like API git_reference__alloc_symbolic return a ref with NULL db member

That's correct, it does return a `ref` with no `db` member,  This is also true of `git_reference__alloc`.  This is by design, it's set later (in fact, where you're crashing.)

The problem here isn't that `ref->db` is `NULL`, the problem is that it can't write to `ref`.  Is that memory address what `git_reference__alloc_symbolic` really returned?

Have you stepped through our sample mysql backend implementation to see how yours differs?

**Comment by JerryYangJin** [comment]
@ethomson , thanks for the reply. Yes, the memory was returned from `git_reference__alloc_symbolic` , I debugged into (refs.c) git_reference__alloc_symbolic -> (refs.c) alloc_ref -> (util.h) git__calloc -> calloc

I checked mysql backend smaple, it only has odb backend, the refdb backend logic was taken the one for [redis backend](https://github.com/libgit2/libgit2-backends/blob/master/redis/hiredis.c#L250), only the data fetch part is different

**Comment by JerryYangJin** [comment]
i'm closing this ticket, it's not libgit2 issue, the problem is in my code

i ignored warning 'implicit declaration of function is invalid in c99', after adding '#include <git2/sys/refs.h>'  for api: 'git_reference__alloc_symbolic', the returned memory address is different and error is gone
