### ISSUE TITLE
libgit2 considers a remote valid even if URL is undefined

### ISSUE THREAD

**Issue by swisspol** [libgit2/libgit2#3196]
libgit2 consider this a valid remote:
```
[remote "origin"]
	fetch = +refs/heads/*:refs/remotes/origin/*
	url = 
```
However it does not consider this valid:
```
[remote "origin"]
	fetch = +refs/heads/*:refs/remotes/origin/*
```
Although Git CLT does.

This is because the regex used in `git_remote_list()` doesn't check for empty strings and `git_remote_lookup()` doesn't either.

Note that `git_remote_create()` also allows creating a remote with an empty string URL.

I don't know what's the right behavior here but just wanted to check with libgit2 maintainers that things indeed work as they are supposed to.

**Comment by swisspol** [comment]
One more thing: when URL is an empty string in the config, `git_remote_url()` returns NULL, not "".

**Comment by carlosmn** [comment]
We make no assertions about the validity of a remote, simply about whether there's something we can do with it. The difference in listing which remotes exist is a side-effect of how each implementation tries to gather this information. git's callback mechanism is completely context-unaware and will create a remote entry for any configuration, while libgit2 seeks out specific configuration variables.

**Comment by swisspol** [comment]
Sounds good, thanks.
