### ISSUE TITLE
Secure Transport path is not tested on OS X

### ISSUE THREAD

**Issue by swisspol** [libgit2/libgit2#3206]
Running all unit tests, it appears that the callbacks set by `SSLSetIOFuncs()` are never called.

**Comment by swisspol** [comment]
This was observed while working on #3195.

**Comment by carlosmn** [comment]
This is simply not true. SecureTransport is the only way the code in master has of talking TLS on OS X. If you don't see them called, you're not running the network tets.

**Comment by swisspol** [comment]
I'm running the clar tests from Xcode using the Xcode project generated with CMake. I pass no arguments and it's running a ton of tests.

Am I supposed to pass an explicit argument to enable network tests?

**Comment by swisspol** [comment]
I just ran again the tests on `master` and the Xcode console says:
> Loaded 291 suites: 
> Started

I have a breakpoint on `git_stransport_stream_new()` and it's never called.

**Comment by carlosmn** [comment]
`-ionline` or `-sonline` will activate the tests which talk to the network.

**Comment by swisspol** [comment]
It works now. Is there any other series of tests that is not enabled by default?

**Comment by carlosmn** [comment]
The expensive tests are disabled, as well as those which require special setup, like the pushing tests, or those which use a huge amount of disk space or try to write outside of the temp dirs. `ctest` should be running the network-facing tests, though.

https://github.com/libgit2/libgit2/blob/master/CMakeLists.txt#L537
