### ISSUE TITLE
libgit2 stash apply doesn't behave like core git

### ISSUE THREAD

**Issue by swisspol** [libgit2/libgit2#3230]
*From the discussion in #3018:*

## Case 1

Start with this state:
```sh
On branch master
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	new file:   bar.txt
	modified:   hello_world.txt

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   foo.txt

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	test.txt
```

Then do `git stash -u` and verify that `git status` shows no pending changes afterwards.

Using `git stash apply` results in this state:
```
On branch master
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	new file:   bar.txt

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   foo.txt
	modified:   hello_world.txt

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	test.txt
```

However using libgit2's `git_stash_apply()` results in this different state (which wasn't the case in my original implementation):
```
On branch master
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   foo.txt
	modified:   hello_world.txt

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	bar.txt
	test.txt
```

Notice that `bar.txt` wasn't restored in the index.

## ~~Case 2~~ (Actually works correctly!)

Start with this state:
```
On branch master
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	new file:   bar.txt
	modified:   hello_world.txt

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   foo.txt

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	test.txt
```

Then do git `stash -u` and verify that `git status` shows no pending changes afterwards.

Using `git stash apply --index` results in this state:
```
On branch master
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	new file:   bar.txt
	modified:   hello_world.txt

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   foo.txt

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	test.txt
```

However using libgit2's `git_stash_apply()` with the `GIT_STASH_APPLY_REINSTATE_INDEX` flag results in this different state (which wasn't the case in my original implementation):
```
On branch master
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   foo.txt
	modified:   hello_world.txt

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	bar.txt
	test.txt
```

Notice how the index wasn't restored at all.

**Comment by swisspol** [comment]
@ethomson Seems like this one is for you, sorry :wink: The instructions above should really make it easy to repro the issues hopefully.

Note that right now in my fork of libgit2 that is used in http://gitup.co, I have to revert to my original implementation of stash apply which doesn't have these issues. This is impractical and bound to break at some point.

**Comment by ethomson** [comment]
Are you ever writing the index?  If not, this is the behavior that I would expect.

**Comment by swisspol** [comment]
No, I wasn't writing the index and indeed I realized that your updated version of `git_stash_apply()` wasn't calling `git_index_write()` anymore. Why this decision BTW?

In any case, writing the index doesn't help, these 2 cases are still failing.

**Comment by ethomson** [comment]
> In any case, writing the index doesn't help, these 2 cases are still failing.

We have unit tests for these exact scenarios, don't we?  Why do they pass but your manual test fails?

**Comment by swisspol** [comment]
Actually libgit2 doesn't have test cases for these exact scenarios. I just finished writing some. It looks like case 1 is confirmed to fail and not match Git CLT, but case 2 is actually passing, so that one may be an issue at my level...

https://gist.github.com/swisspol/ebd25ab62da1aecd6f84

Hopefully you can take it from here considering you now have a libgit2 test case that fails :)

I'll let you integrate these tests considering that because of #3237 they can't simply be added to `apply.c`.

**Comment by swisspol** [comment]
So what's the reasoning behind not writing the index at the end of `git_stash_apply()`?

**Comment by ethomson** [comment]
> So what's the reasoning behind not writing the index at the end of git_stash_apply()?

Seems like it was probably an oversight.  Literally *one person* uses this functionality, so this is sort of like coding into a gaping blackhole of useful feedback.

**Comment by swisspol** [comment]
I sent a PR for the index not being written to disk: #3239.

**Comment by swisspol** [comment]
After more testing I can confirm that case #2 is not an issue, it was some sort of race condition due to a change in behavior regarding how your revised implementation does the checkout vs my original one did.

So the good news is that I'm aware of only 1 bug where libgit2 behavior doesn't match Core Git:
https://gist.github.com/swisspol/ebd25ab62da1aecd6f84

Let me know if you need help with anything.

**Comment by carlosmn** [comment]
PR merged.
