### ISSUE TITLE
Diff generation fails if xfuncname contains a PCRE regex

### ISSUE THREAD

**Issue by kballard** [libgit2/libgit2#3235]
When using libgit2 to generate a diff for a file, if the file has a custom diff attribute that defines an `xfuncname` regex, and the regex contains a pattern that's not compatible with vanilla core Git but instead relies on compiling git with PCRE, libgit2 completely fails to generate any diff whatsoever and instead yields an error message. In my case, I had a pattern `<!--(.*?)-->` and libgit2 failed with the error message "repetition-operator operand invalid".

This is particularly troublesome because this regex is just to define a custom hunk header. If the regex is invalid, libgit2 should still be able to generate a diff, just without the desired hunk header. And in fact, if the application using libgit2 doesn't even use hunk headers (such as [GitUp](http://gitup.co)), it still hits this issue.

**Reproduction:**

`~/.config/git/attributes` with

```
*.storyboard diff=storyboard
```

`~/.gitconfig` with

```
[diff "storyboard"]
    xfuncname = <!--(.*?)-->
```

This works fine in git compiled with PCRE, but when using an app that uses libgit2 (such as the aforementioned [GitUp](http://gitup.co)), asking it to generate a diff for a commit that modifies a `.storyboard` file fails with "repetition-operator operand invalid".

**Comment by kballard** [comment]
Incidentally, the source of `diff_driver_add_patterns()`, there's a [nice little comment](https://github.com/libgit2/libgit2/blob/c7f94123569e8fe00ffb3a35e6a12b6ebe9320ec/src/diff_driver.c#L120):

```c
			/* if regex fails to compile, warn? fail? */
```

It currently chooses to fail, which causes `diff_driver_xfuncname()` to return an error, which causes `git_diff_driver_load()` to return an error, which means the entire diff driver is torpedo'd by the inability to compile the regex for the entirely optional hunk header.

**Comment by carlosmn** [comment]
This seems specific to the OS X implementation. The pattern does not show an error on GNU regex.
