### ISSUE TITLE
git_stash_apply() doesn't handle untracked files correctly

### ISSUE THREAD

**Issue by swisspol** [libgit2/libgit2#3237]
I stumbled upon what looks like a bug when writing test cases for #3230 - add this to `apply.c`:
```c
void test_stash_apply__bug(void)
{
	git_oid oid;

	cl_git_mkfile("stash/untracked", "untracked\n");
	cl_git_pass(git_stash_save(&oid, repo, signature, NULL, GIT_STASH_INCLUDE_UNTRACKED));
	assert_status(repo, "untracked", GIT_ENOTFOUND);

	cl_git_pass(git_stash_apply(repo, 1, NULL));
	assert_status(repo, "untracked", GIT_STATUS_WT_NEW);
}
```
This simple test fails with this error:
```
  1) Failure:
stash::apply::bug [/Users/pol/Magnificent/libgit2-fork/tests/stash/stash_helpers.c:49]
  Function call failed: (git_status_file(&status, repo, path))
  error -3 - Attempt to get status of nonexistent file 'untracked'
```

Doing the stash apply with Git CLT works fine:
```sh
$ git stash apply
Already up-to-date!
On branch master
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	untracked

nothing added to commit but untracked files present (use "git add" to track)
```

The problem seems to be related to the fact the stash is #1 and not #0 (the test setup already creates a stash #0): if you drop the stash #0 so that the test creates a stash #0 instead of #1, then it passes.

**Comment by swisspol** [comment]
@ethomson Thoughts?

**Comment by swisspol** [comment]
FWIW my original `git_stash_apply()` implementation also has this bug: the same test fails.

**Comment by ethomson** [comment]
But `1` is not the newest stash.  From the man page:

> stash@{0} is the most recently created stash, stash@{1} is the one before it

So your test is actually unstashing the version that was laid down in the initializer.  Added a test to ensure this behavior is correct in #3260 - please reopen this if I'm misunderstood the problem.

**Comment by swisspol** [comment]
You're right, what was I thinking! I hate git stash...

**Comment by ethomson** [comment]
You and me both!
