### ISSUE TITLE
Run Clang static analyzer on libgit2

### ISSUE THREAD

**Issue by swisspol** [libgit2/libgit2#3252]
Using the static analyzer of Xcode 6.1 on libgit2, it reports 226 issues with maybe half or so in libgit2 itself vs the clar tests.

Examples:
* `git_proto_stream_free()` crashes if passed NULL which can happen from `_git_receivepack_ls()` on error (line 268)
* A number of "memory used after it is freed" reports in `submodule.c` e.g. `submodule_load_from_config()` calling `git_submodule_parse_ignore()` passing `sm` which has been freed before if `replaced` was true

The vast majority of these reports are in parts of the code base I'm not familiar with, so I wouldn't be able to say if they are false positive or what is the appropriate fix. That said, it shouldn't take more than an hour for @carlosmn or @ethomson to scan through them and figure out if there are some big issues in there :wink: 

PS: I don't think it's possible to export the report in a way that is actually usable, so one would need to run do it in Xcode directly.

**Comment by whoisj** [comment]
I'm surprised Coverity isn't reporting these issues, our is it?

**Comment by ytrezq** [comment]
@whoisj : Does Coverity support reporting uncapped data that is allocated into memory from compression ?

**Comment by whoisj** [comment]
@ytrezq honestly, I am not sure.

I'm also not sure how to find out... :disappointed:

**Comment by carlosmn** [comment]
It might, it might not, but if you want to know about Coverity features, their support site would be a much better place to ask.

As to the original question, that function now accepts `NULL` and the submodule code has been rewritten, and the whole reason the re-use could happen has been eliminated.

Static analyzers throw a lot of noise, so running the analyzer by itself doesn't bring us much; what we'd need is for someone to run it and wade through the false-positives so we can actually know what the actual issues are.
