### ISSUE TITLE
`git_submodule_reload_all` exists in the header but isn't defined

### ISSUE THREAD

**Issue by joshaber** [libgit2/libgit2#3282]
See https://github.com/libgit2/libgit2/blob/aa92c318a235cc6a5230682b9c071eb35f9c5f4c/include/git2/submodule.h#L595

I imagine it's supposed to be :skull:

**Comment by carlosmn** [comment]
Thanks, I removed it from the header and added this to the list of removed APIs in the release notes.

**Comment by joshaber** [comment]
:boom:
