### ISSUE TITLE
git_submodule_reload gets confused by submodules with the same path

### ISSUE THREAD

**Issue by joshaber** [libgit2/libgit2#3284]
This is a recent regression.

I'm working on updating objective-git to the latest SHA. We have some submodule tests that use the following `.gitmodules`:

```
[submodule "Test_App"]
        path = Test_App
        url = ../Test_App
[submodule "Test_App2"]
        path = Test_App2
        url = ../Test_App
[submodule "Archimedes"]
        path = Archimedes
        url = https://github.com/github/Archimedes
```

If we use `git_submodule_lookup` to look up `Test_App`, and then call `git_submodule_name`, we get `Test_App2`.

The PR with the failing test: https://github.com/libgit2/objective-git/pull/472

**Comment by carlosmn** [comment]
As it turns out it wasn't due to the same path but one submodule's name being the prefix of the other. There's a PR for this now. Regex is :(

**Comment by joshaber** [comment]
>Regex is :(

It really really is :sob: Thanks for looking into this!
