### ISSUE TITLE
Submodule whose name doesn't match its path is enumerated over twice

### ISSUE THREAD

**Issue by joshaber** [libgit2/libgit2#3293]
This is a recent regression, similar to #3284.

Given a repository with a `.gitmodules` like:

```
[submodule "TestApp"]
	path = Test_App
	url = ../Test_App
```

`git_submodule_foreach` will yield the submodule twice, once named `TestApp` and once named `Test_App`.

Looking quickly it seems like it's getting one name from the index and the other from the `.gitmodules` while not realizing it's the same submodule.

**Comment by carlosmn** [comment]
What's the status of this repository (`git status` and/or `git submodule status`). I've modified `submodule::lookup::foreach` to set up such a submodule, but I can't repro this with

```diff
diff --git a/tests/submodule/lookup.c b/tests/submodule/lookup.c
index 4d40e22..c378d9b 100644
--- a/tests/submodule/lookup.c
+++ b/tests/submodule/lookup.c
@@ -103,10 +103,24 @@ static int sm_lookup_cb(git_submodule *sm, const char *name, void *payload)
 
 void test_submodule_lookup__foreach(void)
 {
+       git_config *cfg;
        sm_lookup_data data;
+
        memset(&data, 0, sizeof(data));
        cl_git_pass(git_submodule_foreach(g_repo, sm_lookup_cb, &data));
        cl_assert_equal_i(8, data.count);
+
+       memset(&data, 0, sizeof(data));
+
+       /* Change the path for a submodule so it doesn't match the name */
+       cl_git_pass(git_config_open_ondisk(&cfg, "submod2/.gitmodules"));
+
+       cl_git_pass(p_rename("submod2/sm_unchanged", "submod2/sm_alternate_path"));
+       cl_git_pass(git_config_set_string(cfg, "submodule.sm_unchanged.path", "sm_alternate_path"));
+       git_config_free(cfg);
+
+       cl_git_pass(git_submodule_foreach(g_repo, sm_lookup_cb, &data));
+       cl_assert_equal_i(8, data.count);
 }
 
 void test_submodule_lookup__lookup_even_with_unborn_head(void)
```

**Comment by joshaber** [comment]
I've opened https://github.com/libgit2/objective-git/pull/480 which demonstrates the failure. https://github.com/libgit2/objective-git/commit/5d00c7d650ed2a44817ab99f4e1f9ecc73cf3fa3 is the important commit there.

**Comment by carlosmn** [comment]
I've managed to reproduce. I had completely missed that in the `.gitmodules` contents you write out you're changing `[submodule "Test_App"]` to `[submodule "TestApp"]`.

We do try to de-duplicate the submodules, but we do so by name, which means that we don't considier this case for deduplication. But it turns out that deduplication isn't enough, we need to merge the submodule information we have.
