### ISSUE TITLE
Can't create repository (webhotel/user rights)

### ISSUE THREAD

**Issue by larshg** [libgit2/libgit2#3308]
Hi

I once had the problem that I couldn't create repositories using Bonobo gitserver, thats using libgit2sharp wrapper for libgit2. The old issue is #2486, which was solved by @arrbee and included in libgit2sharp version 0.19

After updating to the newest libgit2sharp I'm met with similar error "Failed to make directory 'd:/web': Cannot create a file when that file already exists." - which is the root dir on Uneuro's webservers which my user don't have any rights to do anything with.

As I can track down it has something with the changes between [these two](https://github.com/libgit2/libgit2/compare/hf/libgit2sharp_020_patch...bindings/libgit2sharp/020_2).

with the changes to method ```git_futils_mkdir```.

I know its some old changes, but since you made the changes @ethomson - maybe you can figure out what changes is required to make it work again?

It also seems that a unittest for this was created [here](https://github.com/libgit2/libgit2/blob/bindings/libgit2sharp/020_2/tests/core/mkdir.c#L190-L218)

But maybe this error isn't catched here? since the error message is not the same, I might be on the wrong track?

Method calls:

Bonobo gitserver:
LibGit2Sharp.Repository.Init(path, true);

Libgit2sharp:
Proxy.git_repository_init_ext(null, path, isBare)
NativeMethods.git_repository_init_ext(out repo, gitdirPath, opts);

If any more info is need please say so.

**Comment by carlosmn** [comment]
The latest version of libgit2sharp is not 0.19, it is 0.21. Please make sure you've updated to at least that version, as the bug might be fixed in the libgit2sharp releases.

**Comment by larshg** [comment]
Yes, I know @carlosmn. As I write, after updating to the newest (ie. 0.21) I'm met with a similar error as in the original issue.

So 0.21 is not working, if the user creating the repository doesn't have access rights to the root directory, as the whole path is again traversed and parent errors are not ignored anylonger, as far as I understand.

But thanks for looking at the issue!

**Comment by nulltoken** [comment]
@larshg Any chance you could give it a try with the latest LibGit2Sharp pre-release NuGet package. It's pretty up-to-date with the latest libgit2 version.

**Comment by larshg** [comment]
@nulltoken yes, sure. I'll report back asap.

**Comment by larshg** [comment]
@nulltoken I tried using 0.22.0-pre20150716071016 which uses  native binary version 1.0.72, but I still get an error :(

**Comment by nulltoken** [comment]
@larshg Thanks for your feedback!

**Comment by carlosmn** [comment]
Fixed via #3432
