### ISSUE TITLE
Current libgit2 broken on Windows below Windows 7

### ISSUE THREAD

**Issue by csware** [libgit2/libgit2#3316]
For some operations (such as `git_status_list_new`, `git_branch_iterator_new` and `git_reference_iterator_new`) libgit2 fails with "Could not open directory 'C:/DOKUME~1/ADMINI~1/LOKALE~1/Temp/tgiBDD.tmp/.git//refs/': Invalid parameter.".

I bisected this issue and identified 1920ee4ef6096f888a9bb19bc329424d2c7ee656 as the (first) faulty commit.

The reason is that `FindExInfoBasic` is used as a parameter for `FindFirstFileEx` in https://github.com/libgit2/libgit2/commit/1920ee4ef6096f888a9bb19bc329424d2c7ee656#diff-62346907d7d63ea4758ea34b0614ffa6R351, however,  `FindExInfoBasic` is [not supported on Windows older than 7](https://msdn.microsoft.com/en-us/library/windows/desktop/aa364415%28v=vs.85%29.aspx).

**Comment by csware** [comment]
In the HEAD version of libgit2 the `FindFirstFileEx`call was moved to https://github.com/libgit2/libgit2/blob/master/src/path.c#L1125

**Comment by carlosmn** [comment]
There is no "or below". We don't support anything older than Vista.

/cc @whoisj who knows about the filesystem stuff.

**Comment by csware** [comment]
I did some further testing: The comment on https://github.com/libgit2/libgit2/blob/master/src/path.c#L1088 doesn't seem to be correct.

**Comment by whoisj** [comment]
@csware @carlosmn I'm investigating. My initial findings with a Windows Vista VM is that everything 
"just works" but there's a rather large permutation of possibilities when system settings, file system settings, etc are taken into account.

@csware can you provide additional information about the system(s) you're seeing the issue on? Version of Windows, 32 or 64 bit, SSD or spindle disk, any optional settings. etc.

Thanks

**Comment by csware** [comment]
Windows Vista 32 bit, in VMware

**Comment by ethomson** [comment]
@csware If you *don't* pass `FIND_FIRST_EX_LARGE_FETCH ` (eg, make it `0`) do your tests succeed?

**Comment by csware** [comment]
@ethomson Yes. (also have to pass FINDEX_..._Standard)

**Comment by ethomson** [comment]
Right on, thanks for verifying.  We can do a [quick version check](https://github.com/libgit2/libgit2/blob/master/src/win32/version.h#L12) to figure out what constants to pass.

**Comment by whoisj** [comment]
Yes, thanks.

**Comment by ethomson** [comment]
Closed via #3317
