### ISSUE TITLE
git_diff_find_similar not working as expected

### ISSUE THREAD

**Issue by nhjk** [libgit2/libgit2#3319]
I'm trying to replicate the git command git diff --shortstat -M <commit> <commit> (specifically the -M command for rename detection). Here's an example of the expected output with the golang/go repository: 
`git diff --shortstat -M 32082501859c5c3c61913df5791cafbbb45c2519 2bd616b1a7d2544e05d55141b6575f17a9b17263`
result: 
2208 files changed, 402 insertions(+), 854 deletions(-)

However when I use git_diff_find_similar with the GIT_DIFF_FIND_RENAMES flag set in git_diff_find_options the result is 4010 files changed 443557 insertions 444009 deletions.

libgit2 version: 0.22.3
git: same output with 1.9 and 2.3

**Comment by Therzok** [comment]
Yeah, the rename detection in Git is probably doing only exact-rename matches.

Can you try with `GIT_DIFF_FIND_EXACT_MATCH_ONLY`?

**Comment by Therzok** [comment]
I wanted to edit my previous comment, but accidentally pressed delete. Disregard it, I was wrong.

**Comment by nhjk** [comment]
For anyone wondering, with GIT_DIFF_FIND_EXACT_MATCH_ONLY "4136 files changed, 477995 insertions(+), 478447 deletions(-)."

**Comment by nhjk** [comment]
Unfortunately I can't code in C, but here's the code in both python and go that produce the exact same output if you want to replicate it (just git clone https://github.com/golang/go first).
python: https://gist.github.com/nhjk/7b3c0e4845c3fe2bdc35
go: https://gist.github.com/nhjk/5dcec7a93748bb27f61f

**Comment by ethomson** [comment]
I suspect this is caused by running over your [`rename_limit`](https://github.com/libgit2/libgit2/blob/master/include/git2/diff.h#L680).  Do the python or git bindings let you tune this?  I think if you put it up into a bignum (at least for testing) that you will get the results you expect.

There's two possibilities here:

1. Our `rename_limit` is wildly low compared to git.git's (I don't see the default with a quick glance), or
2. `rename_limit` doesn't apply to exact rename detection.

I can dig in a little bit more tomorrow.

**Comment by nhjk** [comment]
Thanks! Changing the rename_limit worked, maybe the default should be higher? According to [the diff doc page](https://git-scm.com/docs/git-diff) -l is not set and has no limit by default.

**Comment by ethomson** [comment]
git can do that without a limit because if it runs out of memory, it will simply crash and that's the end of that.  If libgit2 runs out of memory, we could take the long-running process that's hosting us down.  So having no limit by default is probably not appropriate for us.

**Comment by nhjk** [comment]
Makes sense, thanks again.
