### ISSUE TITLE
Win32 junctions expected behaviour?

### ISSUE THREAD

**Issue by Fallso** [libgit2/libgit2#3321]
Hi

I can see that support for junctions on Windows was added on #1680 but I'm not sure if what I'm seeing is expected behaviour or not.

I had a directory in my repo with a couple of files in, let's call this "dir_a". I've now subsequently moved "dir_a" outside the working directory, but I still want to track changes to it, so I made a junction in the original location and called this junction "dir_a" too. 

Now at this stage I would expect everything to remain the same and libgit2 to treat it as a normal path, but when I do a diff I get a "GIT_DELTA_UNTRACKED" status for the "dir_a" junction (it seems to think it's a file) and "GIT_DELTA_DELETED" statuses for the contents of the "dir_a" directory.

I suppose my question is is the above behaviour expected and intentional? If so, why? If not, I'll try and fix it!

**Comment by carlosmn** [comment]
That does seem like roughly the way it should work. Leaving aside the bit about moving files away from the dir which Git tracks and yet expecting Git to track them, a junction works much like a symlink, and this is how Git treats them: as a symlink, pointing to somewhere. If the target is also inside the workdir, then the files will be tracked. If the target it outside of the workdir, Git won't track them, as they're not inside its area of responsibility.

**Comment by Fallso** [comment]
Indeed you are correct, I've just tested this with native git and it appears deleted in there too. That's that then! Thanks for your quick response. I'll close this off now...
