### ISSUE TITLE
what reason is  "git_remote_fetch" return -1?

### ISSUE THREAD

**Issue by xiangism** [libgit2/libgit2#3340]
I called git_clone success, and clone my app in LiteMath fold. But when I call git_remote_fetch, it return -1. In the "errors.h", I found GIT_ERROR=-1, and the describe is "Generic error", so I losted.

This is my code. After called git_remote_fetch, r3's value is -1.
```
void TestFetch()
{
    git_repository *repo = NULL;

    git_libgit2_init();
    git_repository_open(&repo, "LiteMath/.git");

    {
        git_remote *remote = NULL;
        const git_transfer_progress *stats;
        struct dl_data data;
        git_fetch_options fetch_opts = GIT_FETCH_OPTIONS_INIT;
        const char *name = "origin";

        int r1 = git_remote_lookup(&remote, repo, name);
        int r2 = git_remote_create_anonymous(&remote, repo, name);


        fetch_opts.callbacks.update_tips = &update_cb;
        fetch_opts.callbacks.sideband_progress = &progress_cb;
        fetch_opts.callbacks.transfer_progress = transfer_progress_cb;
        fetch_opts.callbacks.credentials = cred_acquire_cb;

        int r3 = git_remote_fetch(remote, NULL, &fetch_opts, "fetch");
        stats = git_remote_stats(remote);
    }

    git_repository_free(repo);
    git_libgit2_shutdown();
}
```

**Comment by ethomson** [comment]
You can use `geterr_last` to query for a descriptive error message.  What is that message?

**Comment by xiangism** [comment]
@ethomson  yeah, I use geterr_last(), and find the error message is  "Unsupported URL protocol"

**Comment by ethomson** [comment]
What is the URL that you are trying to clone?

**Comment by xiangism** [comment]
It is my private git application in git.oschina.net.  https://git.oschina.net/xiangism/LiteMath.git

**Comment by carlosmn** [comment]
```C
        int r1 = git_remote_lookup(&remote, repo, name);
        int r2 = git_remote_create_anonymous(&remote, repo, name);
```

It is very unclear what you are trying to do here, as you're overwriting one remote with a completely different one. But regardless, an anoymous remote *does not* have a name, what you are doing there is passing "origin" as a URL.

**Comment by xiangism** [comment]
@carlosmn I want fetch the master in the remote git server. I get the "origin" from the code--
```
git_strarray remotes = {0};
        git_remote_list(&remotes, repo);
        for (int i = 0; i < (int) remotes.count; i++) {
            const char *name = remotes.strings[i];
        }
```
Just now, I delete git_remote_create_anonymous(), and the prgraom run successed. I have solved the problem.
Thanks~~

**Comment by ethomson** [comment]
Thanks for the update!
