### ISSUE TITLE
fetchbuf variable in create_internal() unused?

### ISSUE THREAD

**Issue by tfarina** [libgit2/libgit2#3346]
In create_internal() we have this:

git_buf canonical_url = GIT_BUF_INIT, fetchbuf = GIT_BUF_INIT;

....

git_buf_free(&fetchbuf);

**Comment by carlosmn** [comment]
It's quite possible that it became unnecessary but the initialisation suppresses the compiler warning. If you'd like to send a PR to remove it, we'll take a look at it.

**Comment by tfarina** [comment]
If it is OK, I will try to prepare a PR in the weekend.

**Comment by tfarina** [comment]
Sorry for the delay. I will try to get to this today.

**Comment by tfarina** [comment]
Just rebased.

Fixed by 22261344de18b3cc60ee6937468d66a6a6a28875.

Closing this.
