### ISSUE TITLE
How sould I call ```git_remote_push```

### ISSUE THREAD

**Issue by xiangism** [libgit2/libgit2#3347]
I have called ```git_index_add_all()```and ```git_commit_create()``` success, but I losted lots of time when I'm using ```git_remote_push```.

This is my code, I have followed your example  which in ```libgit2/tests/network/remote/push.c/test_network_remote_push__delete_notification() ``` to arieve.

```
    char *name = "origin";
    char *name2 = "refs/head/master";

    const git_strarray refs = {&name2, 1};
    git_reference *ref;

    if ((err = git_remote_lookup(&remote, repo, name)) != GIT_OK)
        goto out;

    git_reference_lookup(&ref, repo, "refs/heads/master");

    git_push_update expected;
    expected.src_refname = "";
    expected.dst_refname = "refs/heads/master";
    memset(&expected.dst, 0, sizeof(git_oid));
    git_oid_cpy(&expected.src, git_reference_target(ref));

	opts.callbacks.push_update_reference = push_update_reference_callback;
    opts.callbacks.payload = &expected;
	opts.callbacks.credentials = cred_acquire_cb;

	if ((err = git_remote_push(remote, &refs, &opts)))
		goto out;

out:
    const git_error *e = giterr_last();
```
But it have error message ```src refspec 'refs/head/master' does not match any existing object```.
I've tried a lot of other value of ```name2```.
How should I set the value of ```name```, and how should I call the ```git_remote_push```?
Thanks~~

**Comment by ethomson** [comment]
Did you mean `refs/heads/master` (`heads` with an `s`, not `head`)?

**Comment by xiangism** [comment]
@ethomson  Oh, I was so careless~~~~~

**Comment by ethomson** [comment]
No problem!

**Comment by xiangism** [comment]
Thanks~~
