### ISSUE TITLE
Duplicate base names kills build on older versions of Visual Studio

### ISSUE THREAD

**Issue by johnhaley81** [libgit2/libgit2#3356]
So Visual Studio 2008 and before will ignore the base-names of files. We've seen this before in https://github.com/libgit2/libgit2/issues/330. This is something you guys might not really want to worry about since it is an older version of VS but it does however break toolchains like GYP.

The files in question are:

- https://github.com/libgit2/libgit2/blob/master/src/buffer.c
- https://github.com/libgit2/libgit2/blob/master/src/win32/buffer.c

**Comment by ethomson** [comment]
Yes, this needs to be fixed.  Can you send a PR?

**Comment by johnhaley81** [comment]
:+1: 

I was fixing this on `maint/v0.23`. Do you want it on master?

**Comment by ethomson** [comment]
You're awesome.  Both would be amazing.  :sparkles:

**Comment by johnhaley81** [comment]
Cool! You'll have them later today. :D

**Comment by johnhaley81** [comment]
Thanks @ethomson!
