### ISSUE TITLE
How to get full binary from binary delta data

### ISSUE THREAD

**Issue by jessevdk** [libgit2/libgit2#3369]
I'm looking into implementing some image diff visualization using libgit2 for gitg. I think I understand the binary interface for diff's in libgit2, but I'm left wondering how I can reconstruct the full binary data in the case of `GIT_DIFF_BINARY_DELTA`. I suppose that in any case I would first need to inflate the data, and then apply the delta between `a` and `b`? How is the binary delta encoded?

Is it actually easier/recommended to just get the data from the blobs, instead of looking at the binary delta?

**Comment by carlosmn** [comment]
The binary patch format is for transferring diff data over plaintext. If, as the description suggests, you're using libgit2 to generate that patch, you already have both full versions. Going through the diff is doing a lot of extra work you'd be undoing.

Whatever image diff visualisation you're using presumably wants both full versions, so load both of the blobs and give them to your diff tool.
