### ISSUE TITLE
SSLv23_method() has been deprecated.

### ISSUE THREAD

**Issue by tfarina** [libgit2/libgit2#3374]
According to https://www.openssl.org/docs/ssl/TLSv1_server_method.html, this function is deprecated.

Maybe something to consider and update to TLS_Method() method in future.

**Comment by carlosmn** [comment]
Eventually we'd want to switch away, but we still want to work with older OpenSSL versions. That same doc still mentions it as the recommended one for larger compatibility.

**Comment by ethomson** [comment]
I'm afraid that we do indeed need to support this until such time as we want to stop supporting older OpenSSL versions.  (Which is, I pray, _very soon_.)

But until that time, we need to keep this as-is.  Thanks for reporting this!  Hopefully we'll change our requirements soon.
