### ISSUE TITLE
git_config_open_ondisk returns success for non-existant config file

### ISSUE THREAD

**Issue by ashishtyagi109** [libgit2/libgit2#3380]
If I provide a path to a non-existant config file to git_config_open_ondisk it still returns 0 (success).
According to the documentation - "@return 0 on success, GIT_ENOTFOUND when the file doesn't exist or an error code" it  should be returning GIT_ENOTFOUND.

**Comment by carlosmn** [comment]
The docs are wrong (our of date presumably). It is supposed to return success, as this is how you create a new config file.

**Comment by carlosmn** [comment]
Fixed in master.
