### ISSUE TITLE
Use typedef git_error_code instead of int for return methods?

### ISSUE THREAD

**Issue by xoofx** [libgit2/libgit2#3385]
Hi there!
This is just a suggestion/question.

Woud it be possible that all methods returning an error use a typed version like `typedef int git_error_code;`  instead of a plain int?

I don't know enough about all the API, but maybe even an global enum would be possible?

This would be more practical for many purposes:
- documentation
- automatic interop for language directly from sourcecode: generating a wrapper of libgit2 could be done more automatically by detecting methods returning an error and add proper error handling.

Do you think this is something that would cause trouble with the current API? (Apart from updating the code?)

**Comment by carlosmn** [comment]
We do have an enum with the error codes, [git_error_code](https://libgit2.github.com/libgit2/#v0.23.0/type/git_error_code) and you can see what each number means; but making the functions return that would give us much.

Automatic wrappers can only be generated in any meaningful way if the wrapper knows about the object model and conventions of a codebase, and while that's doable with gobject, we have our own way of doing things, with object lifetimes which cannot be specified in C types.

Some functions also cannot make use of this return code. Some functions return a boolean also need to specify an error happening, so we use the `int` return for true, false or error, which doesn't fit in an enum. Others return a count or an error code, which would also not fit in such an enum.

**Comment by xoofx** [comment]
I see...
Forget the enum, I understand that it would be difficult to merge them... but what about `typedef int git_return_code` when we know that there is potentially an error in it? (so that everything < 0 is an error, but whatever positive value is up to the semantic provided by the method ). For all return value that don't hold any errors (like `git_commit_parentcount` I guess?), we could leave them as-is.
What do you think?

**Comment by carlosmn** [comment]
libgit2 is mostly based around I/O, so everything but basic acessor functions can result in all sorts of odd errors, and those accessors already don't have `int` as a return code, as we use `size_t` for offsets.

I would be surprised if we have anything but a handful of functions which want to return an `int` but can't return an error, so we'd just be swapping one type for a much more verbose one which means the same.
