### ISSUE TITLE
assert() fails in submodule_load_from_config() after renaming submodule

### ISSUE THREAD

**Issue by swisspol** [libgit2/libgit2#3391]
I found another different bug with submodules having their names different than their paths while writing some unit tests for #3390 (cf #3367 and #3370):
```
	if (data->have_sm) {
		sm = data->sm;
	} else {
		khiter_t pos;
		git_strmap *map = data->map;
		pos = git_strmap_lookup_index(map, path ? path : name.ptr);
		if (git_strmap_valid_index(map, pos)) {
			sm = git_strmap_value_at(map, pos);
		} else {
			if ((error = submodule_alloc(&sm, data->repo, name.ptr)) < 0)
				goto done;

			git_strmap_insert(map, sm->name, sm, error);
			assert(error != 0);  <------------ FAIL
			if (error < 0)
				goto done;
			error = 0;
		}
	}
```

The part of the unit test that triggers the `assert()` is currently ifdef'ed out:
https://github.com/git-up/GitUp/blob/master/GitUpKit/Core/GCSubmodule-Tests.m#L352

It should be easy to rewrite an equivalent unit test in libgit2.

**Comment by carlosmn** [comment]
That code seems to be trying to list the submodules, but it doesn't say what the situation is. That assert should only be triggered if we try to insert the same submodule name twice, so something odd is happening there.

What is the situation with the submodules? What do you mean by "renaming the submodule"? Did you move the directory of its worktree somewhere else? Did you change it in the `.gitmodules` file? In both?

**Comment by swisspol** [comment]
What the test is doing is simply:
1. Add a submodule
2. (test listing submodules)
3. Commit
4. (test listing submodules)
5. Rename (i.e. move) submodule (done by calling the Git tool as `git mv foo bar`)
6. (test listing submodules) <- ASSERT!

**Comment by carlosmn** [comment]
The `git mv` should have only moved the submodule path on the worktree and on `.gitmodules`, for which we should have a test. If you can't get a unit test for libgit2, could you share the repository in a state which would make it crash with the new code?

**Comment by swisspol** [comment]
Do you have a Mac with Xcode? If so I can provide very easy instructions to reproduce.

**Comment by joshaber** [comment]
This looks the same as / related to #3414.

**Comment by carlosmn** [comment]
I have a mac, but I don't see that trying to walk me though a codebase, programming language and tooling with which I'm unfamiliar would be easier overall than providing a reproduction stituation in the form of a sample repository which is failing.

**Comment by swisspol** [comment]
This is the easiest way to reproduce IMO (and the codebase and language are irrelevant since the bug is in libgit2) - it takes less than a minute:
1. `git clone --recursive https://github.com/git-up/GitUp.git`
2. Open `GitUpKit/GitUpKit.xcodeproj`
3. Select "GitUpKit (OSX)" as the active scheme
![image](https://cloud.githubusercontent.com/assets/627915/9794666/462a82fa-57a1-11e5-81f7-908ae4e687e6.png)
4. Open `GitUpKit/Core/GCSubmodule-Tests.m` and scroll down to the test `-testRenameSubmodule`
5. Change `#if 0` to `#if 1`
6. Click the run button next to the test
![image](https://cloud.githubusercontent.com/assets/627915/9794713/8afe9c0e-57a1-11e5-8b3f-11fb545c989b.png)

And BOOM!

![image](https://cloud.githubusercontent.com/assets/627915/9794726/a1c63104-57a1-11e5-944e-56db71d1d3b3.png)

Because GitUpKit embeds the libgit2 source, that's the easiest way to repro and debug.

**Comment by swisspol** [comment]
If you want to build a test case, simply:
1. Start with an empty repo
2. Add a submodule and commit
3. Rename the submodule using `git mv`
4. Attempt to list the submodules 

GitHub issues doesn't let me attach files so I can't give you a repo in that state but here's the output:
```
$ cat .gitmodules 
[submodule "test-repo-base"]
	path = base
	url = https://github.com/git-up/test-repo-base.git

$ cat .git/config 
[core]
	bare = false
	filemode = true
	ignorecase = true
	precomposeunicode = true
	logallrefupdates = true
[core]
	repositoryformatversion = 0
[submodule "test-repo-base"]
	url = https://github.com/git-up/test-repo-base.git

$ git status
On branch master
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	modified:   .gitmodules
	renamed:    test-repo-base -> base
```

**Comment by ethomson** [comment]
I want to thank you for raising these issues, but I do want to comment on one point:

> Because GitUpKit embeds the libgit2 source, that's the easiest way to repro and debug.

It's really not.  Not all of us have Macs and not all of us would want to run another program just to debug a problem with libgit2.  As you point out, *the bug is in libgit2*, but the codebase *is* relevant.

We can't rely on third-party software that's built on top of libgit2 - for example, GitUp or Visual Studio - acting as our unit tests.  libgit2 needs to have high-quality unit tests to ensure correctness and avoid regression.

We *must* have a unit test for this issue *in libgit2*, regardless of any unit tests that you might have in GitUp.  The more you're able to help us out here, the better it is for everybody and the faster these bugs can get fixed.

**Comment by swisspol** [comment]
I think you're reading too much into this: I don't understand where you get this idea that I'm suggesting libgit2 should not have unit tests or something...

Just think of it as a piece of code that uses libgit2 that triggers the assert. You certainly don't need to run any app at all. Run the test in Xcode and it asserts. I wouldn't have offer this approach if it had required running the app. It's a special case here and IMO the easiest way to repro and debug *this specific issue*. The other related submodule issues don't even have repro cases IIRC.

If you can't or don't want to do this, I provided conceptual steps to repro above (twice actually). Surely you or @carlosmn can write a test in no time.

Yes, it should in an ideal world be provided as a unit test in libgit2, and as you know, I have written some in the past. But guess what, there's no documentation to write libgit2 unit tests, how to use fixtures, how to correctly implement different types of tests, etc... making it a total pain to write anything more than a trivial test. And maybe you can't emulate `git mv` on submodules using libgit2 anyway, so then what's the right way to implement the test, etc.... And for all I know the test will have to be rewritten anyway, so it would be a waste of time.

So I help as much as I can, and sometimes I even write the fix & unit test myself and submit a PR. In some other cases, like here, I hit diminishing returns earlier, especially since I've already spent quite some time tracking down these submodule issues through multiple layers, and coming up with reproducible cases.

**Comment by carlosmn** [comment]
I have written a test (currently the tip of #3070) reproducing the steps yo mention, but it does not crash.

**Comment by swisspol** [comment]
Does the test result in a repo with the `.gitmodules`, `.git/config` and status being the same as what I copy-pasted above?

**Comment by carlosmn** [comment]
It replicates the steps. As the test relies on the assets which we have in libgit2, the names are different, and there are extra changes in the worktree, but it replicates the rename of the directory, the gitmodules entry and the updated index.

**Comment by swisspol** [comment]
If you have a suggestion where I can host a simple ZIP file, I can provide a sample repo that shows the issue for me.

**Comment by carlosmn** [comment]
Does this happen with the current master version? The code at the top was the old code, which suggests this wasn't testing with the branch which was fixing the fragility of this area.

As for sharing the file, if you don't want to use whatever online drive you have from a Google or Apple or whatever account, Git repositories store files, so you can put your zip in a repo and put it up on GitHub or wherever.

**Comment by swisspol** [comment]
The reason I don't like Dropbox and Google Drive and whatnot for such cases is that I need to remember to keep the file around so it remains accessible. Anyway, I forgot I had Cloud App which is perfect for this: http://cl.ly/0v2u2T0h3c03.

**Comment by swisspol** [comment]
Great news! I just tried again to re-enable that test case, and it's fixed now - must have been from one of the very latest commits.
