### ISSUE TITLE
I can't access GitHub repositories using SSH

### ISSUE THREAD

**Issue by Wicker25** [libgit2/libgit2#3392]
Hello to everyone ;)

I'm trying to access a remote repository in Github using SSH but I'm getting a fatal error "username does not match previous request". It seems to depend on username "git" specified in the repository URL.

What am I doing wrong? Can I force the user in the SSH authentication?

The following is the code that I'm using:

```C
#include <git2.h>
#include <iostream>

int cred_acquire_cb(git_cred **out,
					const char *url,
					const char *username_from_url,
					unsigned int allowed_types,
					void *payload) {

	int error = git_cred_ssh_key_from_agent(out, "<username>");

	if (error < 0) {

		const git_error *e = giterr_last();
		printf("Error %d/%d: %s\n", error, e->klass, e->message);
		exit(error);
	}

	return error;
}

int main() {

	git_libgit2_init();

	const char *url  = "git@github.com:<username>/<repository>.git";
	const char *path = "./path/to/sources/";

	git_repository *repo = NULL;

	git_clone_options clone_opts = GIT_CLONE_OPTIONS_INIT;
	clone_opts.fetch_opts.callbacks.credentials = cred_acquire_cb;

	int error = git_clone(&repo, url, path, &clone_opts);

	if (error < 0) {

		const git_error *e = giterr_last();
		printf("Error %d/%d: %s\n", error, e->klass, e->message);
		exit(error);
	}

	git_libgit2_shutdown();

	return 0;
}
```
I'm using the libgit2 v0.23.0.

Regards,
Giacomo

**Comment by carlosmn** [comment]
The username to use to connect to GitHub is indeed `git`, as specified by every ssh URL they show on the site. Any other username won't work.

If a username is provided in the URL, that's what libgit2 will use when connecting to the ssh server, and that's what it will pass to the callback function. Though AFAICT it's technically allowed by the RFC, ssh servers don't like it when you swap out the username in the middle of authenticating, so we disallow that. Which means that if the credentials callback receives a username when trying to connect over ssh, that's what it must use to authenticate.

**Comment by Wicker25** [comment]
Ok. Now I understand the error message. Thanks for the clarification, @carlosmn .

Regards,
Giacomo
