### ISSUE TITLE
GitHub push report not parsed correctly by libgit2

### ISSUE THREAD

**Issue by swisspol** [libgit2/libgit2#3404]
I'm calling `git_remote_upload()` passing 2 refspecs to push to a private GitHub repo over SSH:
- `refs/heads/master:refs/heads/master`
- `refs/heads/test:refs/heads/test`

Based on the lines passed to `add_push_report_sideband_pkt()`, the push report contains:
```
"000eunpack ok\n"
""
"0019ok refs/heads/master\n"
""
"001fng refs/heads/test\n failed\n"
""
"0000"
""
```

Then `update_refs_from_report()` fails as it can't find the push report entry that matches the `refs/heads/test` push spec. That's because `push_spec->refspec.dst` is `refs/heads/test` while `push_status->ref` is `refs/heads/test\n` (notice the extra newline).

*Note that I have no idea why the push is failing on the GitHub server - I was tracing things down trying to debug what is happening when I stumbled over this other issue.*

**Comment by swisspol** [comment]
I should also provide this extra info just in case this matters:
- The local repo is bare
- The push is a no-op since both refs are already in sync between the local repo and the GitHub server
- If I push each separately i.e. one at a time using `git_remote_upload()`, then the GitHub server accepts them without failing

**Comment by swisspol** [comment]
According to the spec at https://github.com/git/git/blob/master/Documentation/technical/pack-protocol.txt, it may be that the GitHub server is not returning a valid push report: the line is expected to be `ng [refname] [error]` not `ng [refname]\n [error]`.

**Comment by carlosmn** [comment]
The length of the frame is correct, so we should be reading the whole thing; but yes, the spec does say there must be a SP. Likely git itself doesn't enforce this, which is unfortunately often more important than the spec.

**Comment by swisspol** [comment]
I wrote a reproducible case at https://github.com/git-up/github-bug - see README for details. I already invited @carlosmn and @ethomson as collaborators to https://github.com/git-up/test-dual-roots.

**Comment by carlosmn** [comment]
/cc @peff who knows about the git part of this

Would you consider this a bug on git/GitHub's side that it creates an ref update report with LF just after the refname instead of LF as it usually would?

**Comment by vmg** [comment]
Hi! I've already double checked with @peff that we're doing the right thing in libgti2. This looks like a regression on our Git proxy -- we're working on a fix. I think this issue would be safe to close.

**Comment by swisspol** [comment]
Great, thanks!

@vmg Do you have any input on what triggers this in the first place (see #3405)?

**Comment by peff** [comment]
Yeah, :+1:. This is a GitHub bug.
