### ISSUE TITLE
Build in IDE without CMake

### ISSUE THREAD

**Issue by mtangoo** [libgit2/libgit2#3407]
I want to be able to include necessary file and build the library using my IDE (CodeLite). I trid to Generate CodeLite Makefiles with CMake but they still depend on it. Is it possible to Build them without CMake?

If Yes, any pointer?

**Comment by ethomson** [comment]
I'm not immediately familiar with CodeLite, but this is the general approach that cmake takes when generating any build scripts:  this allow cmake to be able to *regenerate* the build scripts if something changes.  (Eg, CodeLite will invoke cmake to update itself.)

I don't think that cmake should be overly burdensome, and we would recommend simply using it.  However I do see the value in being able to generate something that *doesn't* require it for various reasons.  Unfortunately, though, we're not cmake experts so I would suggest that you [ask the cmake folks themselves](http://kitware.com/).

**Comment by mtangoo** [comment]
Thank you for a reply and gentle advice. Basically  what am asking is not how to make a CodeLite project. I already know that. I just want to know which files to include in the IDE so that it builds them and (if any) Preprocessor(s) is needed to Build the library.

**Comment by mtangoo** [comment]
I ended running Up CMake via Prebuild Command. But I will appreciate if any will comment with answer to OP
