### ISSUE TITLE
git_repository_init_ext with GIT_REPOSITORY_INIT_EXTERNAL_TEMPLATE does not work if path contains .git

### ISSUE THREAD

**Issue by csware** [libgit2/libgit2#3459]
Set

    [init]
        templatedir = C:/Users/something/.git_template

in `.gitconfig` and call `git_repository_init_ext` with `GIT_REPOSITORY_INIT_EXTERNAL_TEMPLATE` set and notice that no template is applied (fails here: https://github.com/libgit2/libgit2/blob/master/src/fileops.c#L903).

Using `git init` works as expected.

Cross-ref: https://tortoisegit.org/issue/2602

/CC @ethomson

**Comment by ethomson** [comment]
Fixed via #3565
