### ISSUE TITLE
git__malloc is undefined in mac osx

### ISSUE THREAD

**Issue by implausible** [libgit2/libgit2#3460]
in src/xdiff/xdiff.h libgit2 includes "util.h", but should actually include ../util.h. This causes git__malloc to not be defined and crashes in mac osx and linux during merges.

**Comment by ethomson** [comment]
That would cause a compilation error.

Can you actually paste some error that you're seeing?

**Comment by ethomson** [comment]
Just an update.  This looks like it's something in your custom build process, and nodegit is not using CMake, is that correct?

If so, can you provide a pull request that works for your build process, and for ours?

**Comment by ethomson** [comment]
Fixed by #3481
