### ISSUE TITLE
[Q] How to build a pure local version(without the libssl dependency)?

### ISSUE THREAD

**Issue by pandada8** [libgit2/libgit2#3464]
Currently I am using git2go with latest libgit2 for _local_ git operation, and I want to create a staticly linked version for distribution.
So is there any method I can remove the dependency and drop the network libs? Or is there any better way to handle it?
the cmake provide the options to drop libssh and libcurl, and i already remove them

**Comment by carlosmn** [comment]
libgit2 builds as a typical C library, which expects to work in the environment in which it was built. There is currently no option to disable linking against OpenSSL on non-Windows, non-OSX if the headers are available.

**Comment by tkelman** [comment]
maybe https://cmake.org/cmake/help/v3.0/variable/CMAKE_DISABLE_FIND_PACKAGE_PackageName.html ?

**Comment by ethomson** [comment]
We've refactored our cmake options heavily since this was opened; this is now obsolete.
