### ISSUE TITLE
Test "config::read::iterator_invalid_glob" fails with musl

### ISSUE THREAD

**Issue by asandroq** [libgit2/libgit2#3469]
I have built `libgit2` using [musl](http://www.musl-libc.org/) as my C library. When running the included tests, one of them fails:

```
  1) Failure:
config::read::iterator_invalid_glob [/home/vagrant/libs/libgit2-0.23.2/tests/config/read.c:405]
  Expected function call to fail: git_config_iterator_glob_new(&iter, cfg, "*")
```

Machine:
```
vagrant@vagrant:~/libs/libgit2-build$ uname -a
Linux vagrant 3.16.0-23-generic #31-Ubuntu SMP Tue Oct 21 17:56:17 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
vagrant@vagrant:~/libs/libgit2-build$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.10
DISTRIB_CODENAME=utopic
DISTRIB_DESCRIPTION="Ubuntu 14.10"
```

**Comment by carlosmn** [comment]
We're passing the value down to `regcomp(3)` so it's musl who's returning something unexpected. It looks like it might not be taking `REG_EXTENDED`.

**Comment by carlosmn** [comment]
One way to work around this would be to ask CMake to compile in the GNU regex implementation, like we do for Windows. It might get interesting since musl would also be exposing those functions.

**Comment by carlosmn** [comment]
You can add a rule to include GNU regex like we do on Windows if you want to use musl, but that feels like it's precisely what you don't want to do.

Closing as it's a bug in musl.
