### ISSUE TITLE
libgit2 fails to compile using musl as C library

### ISSUE THREAD

**Issue by asandroq** [libgit2/libgit2#3470]
`libgit2` fails to build with [musl](http://www.musl-libc.org/) because it does not test properly for the presence of `qsort_r` and instead relies on some preprocessor symbols to verify its availability.

**Comment by ethomson** [comment]
Are you looking at master, or are you looking at a released version?  We just changed this (in master) explicitly for alternate C libraries.  We now have CMake look for the symbol itself.

**Comment by asandroq** [comment]
I am using a released version. Sorry for the noise.

**Comment by ethomson** [comment]
Not at all - we should apologize for the bug.  :)  I think that this means that we should backport this to the next maintenance release.
