### ISSUE TITLE
SSH transport never disconnects from server

### ISSUE THREAD

**Issue by asandroq** [libgit2/libgit2#3473]
A call to `libssh2_session_disconnect` is missing from `ssh_stream_free` in the SSH transport. Without this call, the SSH client never logs out from the server. SSH servers like the one embedded in Gerrit are very strict about the number of simultaneously open connections.

**Comment by carlosmn** [comment]
We shouldn't *need* a close when freeing memory, but it'd be useful as a last resort. We should be fixing the places where we don't close the stream, however.

**Comment by asandroq** [comment]
The documentation of `libssh2` and my own experience with Gerrit's embedded SSH server say you need to disconnect before freeing the memory.

**Comment by carlosmn** [comment]
We do need to disconnect before freeing memory, but there's no overwhelming reason why we should free libgit2 structures just after disconnecting.
