### ISSUE TITLE
EXC_BAD_ACCESS in attr_cache_upsert compare-and-swap when iterating file status

### ISSUE THREAD

**Issue by logancollins** [libgit2/libgit2#3504]
In the current commit on master, I'm seeing a bad memory access when using git_status_file. The crash is in git__compare_and_swap, called by attr_cache_upsert. I'm not at all familiar with how git's attr caching works, so with some limited investigation I'm not sure offhand what's wrong (whether on my end, or the library's).

The bad pointer appears to be entry->file or one of its members, as the compare-and-swap is attempting to set one of the "entry->file" members. I'm attaching screenshots of the stacktrace, the section of code in attrcache.c, and the debugger output of the potentially relevant variables.

If you're not able to reproduce this (I can reproduce 100%), I can try to provide more debugging info. I am experiencing this on iOS 9, arm64, compiled with Clang.

![screen shot 2015-11-09 at 9 01 30 am](https://cloud.githubusercontent.com/assets/714246/11040420/018ce486-86c1-11e5-81d5-0c8c507ee6be.png)
![screen shot 2015-11-09 at 9 02 13 am](https://cloud.githubusercontent.com/assets/714246/11040422/05157ca8-86c1-11e5-83ce-e78b1d48a354.png)
![screen shot 2015-11-09 at 9 03 00 am](https://cloud.githubusercontent.com/assets/714246/11040425/079befc0-86c1-11e5-892e-2497c641388f.png)

**Comment by carlosmn** [comment]
Does this happen against all repos or a specific one? Can you reproduce on a "desktop" arch? Did you call `git_libgit2_init()` at the start of your program?

**Comment by logancollins** [comment]
I am calling `git_libgit2_init()`. I just tried reproducing this on OS X, but it's working fine. It doesn't seem to be repository specific, as I can reproduce it with two repos, one that has working directory changes, and one that's a clean working directory.

Offhand, the first major difference I can think for iOS and OS X is that iOS has a case-sensitive filesystem? Would that impact this at all?

In the meantime, I'm going to experiment a bit more with both OSs and see if I can trace to a common difference.

**Comment by logancollins** [comment]
The previous commit I was using before hitting this issue was `d0976a373e48b7ba3d919432b99e64de1812208f`, so I'm guessing some change in the interim 225 commits (!) is the source. I can also bisect back and see if I can trace it to a specific point.

**Comment by carlosmn** [comment]
Case sensitivity shouldn't be affecting this at all, I'd be more inclined to believe something about arm64 is special which we're not taking into account since it doesn't seem to happen on x86_64 (or it could just be a coincidence, but the arch looks rather guilty in this case).

If you could bisect it, that'd be awesome. I don't think any of the core team have an arm64 laying around. Luckily bisection is logarithmic, so it should only take about eight steps to find the culprit (if I remember my algorithms class correctly).

We did recently make some changes to the pool allocator, which the attributes code uses. So 232a7e32 would be a good place to start at. If that fails and efc659b07 works, then that's the bad change. Otherwise go with the bisection.

**Comment by logancollins** [comment]
Sure enough, that hit perfectly. The issue presents in 232a7e3, but not in efc659b.

**Comment by carlosmn** [comment]
Alright then, paging Dr @vmg it looks like you left a scalpel in your patient.

**Comment by logancollins** [comment]
I just successfully reproduced this also on arm7f, which is a 32-bit arch, so possibly more than just arm64 (potentially all the Apple/iOS/arm archs).

**Comment by jacquesg** [comment]
Pretty sure this is the culprit. I remember having to "force" alignment here to keep sparc happy.

https://github.com/libgit2/libgit2/commit/1e5e02b4f47779fe3733b1a6ab24a6ca13099ec3#diff-98cab5dfb1c0a306bc64d75f9d8736c9L11

**Comment by logancollins** [comment]
Reverting that line to re-insert the alignment doesn't seem to fix it for me.

**Comment by vmg** [comment]
:boom: UNALIGNED ACCESS IN A R M :boom:

...Sorry for the trouble. I see what's the issue now, I'll open a PR tomorrow.

**Comment by logancollins** [comment]
No worries! Thanks for jumping on this so quickly, guys.

**Comment by Jccp1983** [comment]
> In the current commit on master, I'm seeing a bad memory access when using git_status_file. The crash is in git__compare_and_swap, called by attr_cache_upsert. I'm not at all familiar with how git's attr caching works, so with some limited investigation I'm not sure offhand what's wrong (whether on my end, or the library's).
> 
> The bad pointer appears to be entry->file or one of its members, as the compare-and-swap is attempting to set one of the "entry->file" members. I'm attaching screenshots of the stacktrace, the section of code in attrcache.c, and the debugger output of the potentially relevant variables.
> 
> If you're not able to reproduce this (I can reproduce 100%), I can try to provide more debugging info. I am experiencing this on iOS 9, arm64, compiled with Clang.
> 
> ![screen shot 2015-11-09 at 9 01 30 am](https://cloud.githubusercontent.com/assets/714246/11040420/018ce486-86c1-11e5-81d5-0c8c507ee6be.png)
> ![screen shot 2015-11-09 at 9 02 13 am](https://cloud.githubusercontent.com/assets/714246/11040422/05157ca8-86c1-11e5-83ce-e78b1d48a354.png)
> ![screen shot 2015-11-09 at 9 03 00 am](https://cloud.githubusercontent.com/assets/714246/11040425/079befc0-86c1-11e5-892e-2497c641388f.png)

**Comment by fahadfa** [comment]
https://http://hr.al-jazeerapaints.com/Menaitech2/application/hrms/mename/ESS/system_info/reports.php
<body>

**Comment by Churru14** [comment]
::selection {
  background: aquamarine;
  color: black;
}

.custom-text-selection::selection {
  background: deeppink;
  color: white;
}
