### ISSUE TITLE
Why would it take nearly 10 seconds just to query one file's last commit log?

### ISSUE THREAD

**Issue by begeekmyfriend** [libgit2/libgit2#3507]
I have written [a test sample](https://github.com/begeekmyfriend/libgit2-log-sucks) to show how it is slow querying some repositories commit logs using the APIs  of libgit2. The source is mostly deprived from your `example/log.c` and I have simplified it to make it clearer.

The testing repository is just `Git` which, as we all know, possesses rapid log command to query commit logs. Since libgit2 was deprived from it, I thought there would not be big difference in speed. However, I was wrong when I tried some repositories and found the difference might be over 100 times.

Let us see what is going on. `git/COPYING` is an ordinary file in Git repository itself. It was last committed on 2010 and 5 years since then. I was curious about how fast that I could get its last commit log and then I used `git log` command and it immediately gave me the answer:

```shell
$ cd /tmp
$ git clone git@github.com:git/git.git
$ cd git
$ git log -1 COPYING
commit 703601d6780c32d33dadf19b2b367f2f79e1e34c
Author: Junio C Hamano <gitster@pobox.com>
Date:   Fri Jan 15 21:38:34 2010 -0800

    Update COPYING with GPLv2 with new FSF address
    
    The mailing address of FSF changed quite a while ago.  Also the expansion
    of the acronym LGPL (which we don't use) is "Lesser GPL" not "Library GPL"
    these days in recent copies of GPLv2.  Update the copy we have with a
    fresh download of <http://www.gnu.org/licenses/gpl-2.0.txt>.
    
    This incidentally removes form-feeds in the text we retained for all these
    years.
    
    Signed-off-by: Junio C Hamano <gitster@pobox.com>
```

Good! However when I was working on some secondary development of libgit2, things went weird. At first I thought my program was hanged up, but the commit log showed up several seconds later! In fact, **10 SECONDS ELAPSED** on my machine. WTF!

I checked the docs and your example code to ensure I did not f*ck up with your APIs. I was confused. So I checked Git source code to find out what methods it used to walk revisions and filter the right commit. I even spent time debugging. Finally I found that line: https://github.com/git/git/blob/master/revision.c#L2989.

See? It used `commit->object.flags` to decide whether the commit is changed and will be shown or ignored later. It judged the flag containing `TREESAME` or not which is defined as a macro. So there must be some **tree diff** between the commit and its parents.

In fact your `example/log.c` does the same thing. It uses `git_diff_tree_to_tree` to judge whether the commit matches its parents or not. Now here is the problem! You did it right and why it is so slow?

I am not able to figure out what on earth the implementation of **tree diff** is in libgit2. It may well be inefficient that even an O(N) algorithm cannot be 10-second long for thousands of commit logs history.

I will keep my testing [repo](https://github.com/begeekmyfriend/libgit2-log-sucks) until you fix it some day.

**Comment by carlosmn** [comment]
What version of libgit2 were you using? Have you compared it with master? A lot of improvements were recently merged into master which make both log and diff with path limiting quicker. Did you profile to see where the slowdown was coming from?

Do note that swearing and fowl language isn't going to motivate anybody into looking at an issue. I'm sorry if you've found an issue in libgit2 which frustrated your efforts, but that's no way to let the authors of software, which is provided to you for free, know about a possible issue in the code.

**Comment by begeekmyfriend** [comment]
I have pulled the latest version and tested on master branch, and it still all the same. Moreover, I used `perf` to show you the profiling.

That is the `libgit2` profile report: https://github.com/begeekmyfriend/libgit2-log-sucks/blob/master/libgit2-log-profile.txt

For more detail: https://github.com/begeekmyfriend/libgit2-log-sucks/blob/master/libgit2-log-profile-detail.txt

And that is the `git-log` one: https://github.com/begeekmyfriend/libgit2-log-sucks/blob/master/git-log-profile.txt

The result is interesting. The majority percentage in `git-log` is just directives in `zlib` while it is only about 3% in `libgit2`. And I told you `libgit2` takes more over 100 times than `git-log` with the same log command.

What does it mean? That says `libgit2` does enormous **UNNECESSARY** directives to parse commits, trees, strings or something else. The primary `log filename` command should have been so simple that it almost would not take redundant directives. And you work it around with a huge mess! I seriously doubt that is a **DESIGN MISTAKE**.

Now the main process of log command might be the same:

- Start with a HEAD revision.
- Get the commits due to date sorting.
- Fetch the tree structure of each commit and its parent(s).
- Diff the trees.
- Show the commit.

The problem is why `git-log` does not do so many "parsing" jobs? Unfortunately I am not quite clear about that either. I have to guess `git-log` uses simple `object.flags`(as I told you) to mark each object's revision state. And the enumeration is defined in [git/revision.h](https://github.com/git/git/blob/master/revision.h).

```c
#define SEEN		(1u<<0)
#define UNINTERESTING   (1u<<1)
#define TREESAME	(1u<<2)
#define SHOWN		(1u<<3)
#define TMP_MARK	(1u<<4) /* for isolated cases; clean after use */
#define BOUNDARY	(1u<<5)
#define CHILD_SHOWN	(1u<<6)
#define ADDED		(1u<<7)	/* Parents already parsed and added? */
#define SYMMETRIC_LEFT	(1u<<8)
#define PATCHSAME	(1u<<9)
#define BOTTOM		(1u<<10)
```

The `TREESAME` enumerates the **tree diff** state in Git. So just check the `commit->object.flags` when traversing and querying the commit revision and the answer would be clear. That is simple.

I debugged with `git-log` but I am not quite sure I get it. Neither do I figure out how `libgit2` work around with it. The code seems more complicated for me. The profiling shows there are so many "parsing" jobs during the log command and I guess that should do something with your design.

**Comment by ethomson** [comment]
We have not implemented `git log` functionality.  This is a dup of #3041
