### ISSUE TITLE
git rev-list --cherry-pick equivalent in libgit?

### ISSUE THREAD

**Issue by stanluk** [libgit2/libgit2#3510]
Is there any way to reproduce output similar using libgit2 to:

git rev-list --cherry-pick A...B

Some options I can already preproduce:
--no-merges - just check number of commit parent != 1
-- reverse
-- topo-order

What about --cherry-pick?

**Comment by carlosmn** [comment]
There is currently no way to produce that output. This would likely come as part of the `git_log` functionality as described in #3041 but AFAIK nobody is working on this.

**Comment by carlosmn** [comment]
That issue now has that as one of the features we'd want to support via a log mechanism.
