### ISSUE TITLE
Sorting trees vs trusting the input

### ISSUE THREAD

**Issue by carlosmn** [libgit2/libgit2#3536]
When we parse a tree, we go a sorting round at the end to make sure the entries are in the right position for searching through them. But the tree format already forces the entries to be sorted, so this operation should always be a no-op. The cases where it's not, we might want to consider that part of the error path which shouldn't cost cycles to properly-formed trees with successful lookups.

`perf` indicates that we spend 13% of the runtime comparing strings, which all come from the sorting. `git_vector_sort()` tales up 24% cumulative time.

```diff
diff --git a/src/tree.c b/src/tree.c
index 2de8e72..6b3a37e 100644
--- a/src/tree.c
+++ b/src/tree.c
@@ -476,7 +476,7 @@ int git_tree__parse(void *_tree, git_odb_object *odb_obj)
                buffer += GIT_OID_RAWSZ;
        }
 
-       git_vector_sort(&tree->entries);
+       /* git_vector_sort(&tree->entries); */
 
        return 0;
 }
```

This patch takes us from 3.8s to 2.8s in my benchmark loading ~41k commits and top-level trees in the git repository and moves the most expensive part back to parsing the mode (but this is in Debug mode, Release should inline it making it a lot cheaper to call). Including diffing each commit against its first parent, this patch takes us from 8.5s to 6.4s.

AFAICT git itself doesn't try to make sure this is sorted, so maybe we can say we don't want to bother with it at all either. We will however still perform a sort when someone first tries to do a path-based lookup, so this affects primarily uses which go by the index (which is why diff gets a speedup).  This opens up (extremely rare) the possibility that two iterations over a tree might not give the same result, if there's been a path lookup (as we could have resorted). We could also just tell the vector that it's sorted and just say that broken trees are broken and you can't make heads or tails of it.

/cc @vmg @peff who'd likely have opinions on this.

**Comment by peff** [comment]
> AFAICT git itself doesn't try to make sure this is sorted, so maybe we can say we don't want to bother with it at all either. 

Correct. If you feed bad data, you will get buggy results. Git considers this OK, as long as the result is well behaved (e.g., I think we had a case where duplicate pack entries would cause us to infinite loop, which is A Bad thing).

Which isn't to say being careful is _wrong_, but if it is making a big performance difference, I think it's OK to assume correctness.

If somebody really wants carefulness, I think the right solution is something like noticing the broken objects during fsck and using `git-replace` or similar to provide sane contents.

**Comment by vmg** [comment]
I'm perfectly fine with removing the extra sorting step after parsing. If Git doesn't have it, we don't need to.

**Comment by ethomson** [comment]
Yep, I also agree.

> Including diffing each commit against its first parent, this patch takes us from 8.5s to 6.4s.

Out of curiosity, where are we vs Git itself with this change?

**Comment by carlosmn** [comment]
It's hard to compare 1-to-1 since git does a few things differently. First it doesn't allocate full entries but points to inside the buffer for both the filename and id (I've a branch which does this; the difference is measurable but not huge now that we pool the allocations anyway), and it parses entries lazily so it makes a difference whether you're looking up the first entries or the last ones.

But `git log --oneline -- README" takes about 0.3s on my laptop (asking for `zlib.c` takes 0.5s as it's at the end of the tree, making it parse more things). This isn't just because our code is slow (though including this change I think I've slashed something like 40% of parse time with low-hanging fruit in a few PRs) but also because git has a lot more information about what it wants to do and re-uses stuff internally which we don't (currently?) enable with libgit2. We'll likely want/need to use a `git_log` object to enable some of these optimisations (for completeness, in Release mode we go from 4.1s to 3.6s for the diff-every-parent benchmark).

What we're doing with my benchmark code looks a lot more like `git rev-list master | xargs -L 1 -J % git diff --name-only %` but that takes absolute ages with git (I killed it after two and half minutes) since it needs to start up the tool over and over again and it can't cache objects between calls, so that comparison isn't really fair either. Going the load-a-ton-of-trees route has the same issue, as `git ls-tree` also needs to do formatting.

So, where are we? If you want to interact with the repository in a way that it would take a lot of different git commands, we kick its arse. If you want to do a top-10 command for which git can know to skip work or modify data internally, then it kicks our arse. So not much has changed, but we're a lot faster than a month ago :)

**Comment by peff** [comment]
> `git rev-list master | xargs -L 1 -J % git diff --name-only %`

Yeah, that's crazy because of the process startup cost. You'd do it more like:

```
git rev-list master | git diff-tree --stdin --name-only README
```

That takes about 600ms on git.git on my machine. But the "internal" way of:

```
git log README
```

takes only 180ms. And the interesting thing here is why. Pipe overhead is part of it, but the main thing is that log is using the path limiter for both the diff output _and_ for history simplification. We're skipping whole chunks of history where the merge shows the side branch didn't touch `README`.

I don't know exactly what benchmarks you've done for libgit2, but make sure you are pruning history as you traverse if you want to compare apples to apples.

**Comment by carlosmn** [comment]
The benchmark I'm running is pretty directly your `rev-list` command in libgit2 form. It takes about 850ms on my machine. So if we take those numbers, we are about four times as slow (once we take out the needless sorting).

Log simplification is something that this future `git_log` object would do internally. A revwalk only does the plain rev-list walk down the history. So we do end up comparing every single commit to its parent.

**Comment by carlosmn** [comment]
Thanks everyone for their comments. With the PR to remove the extra sorting removed, most of the obvious fixes have been merged and we have tree parsing which is almost twice as fast.
