### ISSUE TITLE
The pool allocator should support being deactivated for debug

### ISSUE THREAD

**Issue by carlosmn** [libgit2/libgit2#3543]
The pool allocator is great for performance when we have a bunch of small allocations. But since we're allocating much more than we want to use at a time, it doesn't let `valgrind` or similar tools see what we're actually doing.

We should have a compile-time option to disable allocating the pool and passing each request to `git__malloc()` so don't work around the tools that are trying to tell us about bad memory accesses.

Instead of pooling allocations, we'd have to keep track of the allocations so we can free them in `git_pool_clear()` so we don't end up leaking everything.

**Comment by rossdylan** [comment]
I've started working on this and I had a question about coding conventions.  For debug code like this is it preferred to use ifdef's to enable/disable it, if not what is the preferred method?

**Comment by ethomson** [comment]
Fixed via #3577
