### ISSUE TITLE
Push walks through all commits

### ISSUE THREAD

**Issue by broudy3** [libgit2/libgit2#3545]
I did a simple test: pulled repository, made new commit and pushed it back and it seems that the push function is walking through all commits (reads them from disk), even the one remote repository already has. I debugged the problem a little bit, the code is not easy to understand without comments, but I think that the problem is in function mark_uninteresting (file revwalk.c). It seems that this function is called for commit the remote repository already has and it reads all previous commits and marks them as uninteresting.

**Comment by ethomson** [comment]
I believe this is a dup of #3364
