### ISSUE TITLE
winhttp Multiple Definition Errors under MinGW

### ISSUE THREAD

**Issue by deathssoul** [libgit2/libgit2#3570]
Using a freshly cloned copy of libgit2 and the 0.23.4 tag, I get the following error when I try to compile a static executable using a static build of libgit2 and a static build of wxWidgets 3.0.2:
```
/home/User/Code/boss/lib/libgit2.a(winhttp.c.obj):winhttp.c:(.rdata+0x810): multiple definition of `IID_IInternetSecurityManager'
/usr/x86_64-w64-mingw32/sys-root/mingw/lib/../lib/libuuid.a(lib64_libuuid_a-dxva-uuid.o):(.rdata$IID_IInternetSecurityManager[IID_IInternetSecurityManager]+0x0): first defined here
/home/User/Code/boss/lib/libgit2.a(winhttp.c.obj):winhttp.c:(.rdata+0x820): multiple definition of `CLSID_InternetSecurityManager'
/usr/x86_64-w64-mingw32/sys-root/mingw/lib/../lib/libuuid.a(lib64_libuuid_a-uuid.o):(.rdata$CLSID_InternetSecurityManager[CLSID_InternetSecurityManager]+0x0): first defined here
collect2: error: ld returned 1 exit status
CMakeFiles/boss_gui.dir/build.make:640: recipe for target 'boss_gui.exe' failed
make[2]: *** [boss_gui.exe] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/boss_gui.dir/all' failed
make[1]: *** [CMakeFiles/boss_gui.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```
Changing 
```c++
const CLSID CLSID_InternetSecurityManager = { 0x7B8A2D94, 0x0AC9, 0x11D1,
	{ 0x89, 0x6C, 0x00, 0xC0, 0x4F, 0xB6, 0xBF, 0xC4 } };
```
to
```c++
static const CLSID CLSID_InternetSecurityManager = { 0x7B8A2D94, 0x0AC9, 0x11D1,
	{ 0x89, 0x6C, 0x00, 0xC0, 0x4F, 0xB6, 0xBF, 0xC4 } };
```
brought up this error:
```
/home/User/Code/libgit2/src/transports/winhttp.c:55:20: error: static declaration of 'CLSID_InternetSecurityManager' follows non-static declaration
 static const CLSID CLSID_InternetSecurityManager = { 0x7B8A2D94, 0x0AC9, 0x11D1
                    ^
In file included from /home/User/Code/libgit2/deps/winhttp/urlmon.h:43:0,
                 from /usr/x86_64-w64-mingw32/sys-root/mingw/include/objbase.h:163,
                 from /usr/x86_64-w64-mingw32/sys-root/mingw/include/ole2.h:17,
                 from /usr/x86_64-w64-mingw32/sys-root/mingw/include/wtypes.h:12,
                 from /usr/x86_64-w64-mingw32/sys-root/mingw/include/winscard.h:10,
                 from /usr/x86_64-w64-mingw32/sys-root/mingw/include/windows.h:97,
                 from /usr/x86_64-w64-mingw32/sys-root/mingw/include/winsock2.h:23,
                 from /home/User/Code/libgit2/src/common.h:39,
                 from /home/User/Code/libgit2/src/buffer.h:10,
                 from /home/User/Code/libgit2/src/transports/winhttp.c:12:
/usr/x86_64-w64-mingw32/sys-root/mingw/include/urlmon.h:7348:20: note: previous declaration of 'CLSID_InternetSecurityManager' was here
 EXTERN_C const IID CLSID_InternetSecurityManager;
                    ^
/home/User/Code/libgit2/src/transports/winhttp.c: In function 'certificate_check':
/home/User/Code/libgit2/src/transports/winhttp.c:234:2: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
  error = t->owner->certificate_check_cb((git_cert *) &cert, valid, t->connectio
  ^
/home/User/Code/libgit2/src/transports/winhttp.c: In function 'write_chunk':
/home/User/Code/libgit2/src/transports/winhttp.c:493:23: warning: format '%X' expects argument of type 'unsigned int', but argument 3 has type 'size_t {aka long long unsigned int}' [-Wformat=]
  git_buf_printf(&buf, "%X\r\n", len);
                       ^
CMakeFiles/git2.dir/build.make:2968: recipe for target 'CMakeFiles/git2.dir/src/transports/winhttp.c.obj' failed
make[2]: *** [CMakeFiles/git2.dir/src/transports/winhttp.c.obj] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/git2.dir/all' failed
make[1]: *** [CMakeFiles/git2.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

The codebase I'm working on doesn't actually use those symbols and only occurs with wxWidgets in the mix, without the GUI it works fine.

**Comment by carlosmn** [comment]
It's not quite clear where the issue comes from, but define this ourselves and make it public, which is something we should definitely stop doing.

That alone *should* be enough if we do need to define it ourselves. But it looks like `urlmon.h` defines it, so why do we also have it? Why don't we fail to link if we're not supposed to?

It looks like libuuid might be trying to helpfully provide these ids and wxWidgets is bringing it in; so maybe the urlmon library doesn't actually bring it in? Is it then possible to support having libuuid and not? Should we just rename our variable to something else?

**Comment by deathssoul** [comment]
Is there any more information I can provide that could help?

**Comment by carlosmn** [comment]
These aren't questions specific to libgit2, so I guess if you know/find out how other programs deal with this, that would be helpful. Maybe we're running into issues because we expect to be running outside of MinGW so when we're inside, things don't go all that well.

**Comment by deathssoul** [comment]
I don't know how other programs handle it, no. I have, however, narrowed it down to wxWidgets specifically. The non-GUI executable also links in libuuid and doesn't have this issue so it sounds like it's something in wxWidgets that's causing this.

I think I should probably ask them if they have any insight.

**Comment by deathssoul** [comment]
The wxWidgets guys said something about libgit possibly needing a different libuuid than what comes with MinGW, does that mean anything?

**Comment by ethomson** [comment]
So I believe that the problem here is that we are building a struct for `CLSID_InternetSecurityManager` - which is provided on Win32 but not on MinGW.  And - of course - libuuid is doing the same thing.  And we both can't provide that symbol.

Making it `static` would be a reasonable solution, except that it's declared as `extern` in a public header file.

Instead, just name-mangle it on MinGW so that we build our own symbol that won't collide with another symbol in another package (hopefully!)

**Comment by deathssoul** [comment]
That fixes the build issue, thanks!
