### ISSUE TITLE
`git_submodule_foreach` includes submodules that `git submodule status` doesn't

### ISSUE THREAD

**Issue by joshaber** [libgit2/libgit2#3580]
On 0.23.4.

As an example, and rather self-referentially, https://github.com/nodegit/nodegit/ has libgit2 in its [`.gitmodules`](https://github.com/nodegit/nodegit/blob/ab27f659c973eb688d86dd99796aacfc3ea3c7c1/.gitmodules) but it's not *actually* a submodule. It seems to have been committed to the nodegit repository itself.

If we call `git_submodule_foreach` in nodegit, it reports `vendor/libgit2`, but `git submodule status` doesn't. And not too surprisingly, most submodule functions don't work on it.

It seems like libgit2 needs to do some sanity check on submodules instead of reporting everything in `.gitmodules`.

**Comment by carlosmn** [comment]
Have you checked the flags for the submodule? We report all the entries in `.gitmodules` as those are the configured ones, but you ask for where we detected them with [`git_submodule_location()`](https://libgit2.github.com/libgit2/#HEAD/group/submodule/git_submodule_location) so you can see if it's just in `.gitmodules` and not show it, or see that we did find it in `HEAD`, in the worktree...

**Comment by joshaber** [comment]
Ah that's interesting. Very good point. In that case I think this is reasonable behavior :+1:
