### ISSUE TITLE
Plans on 0.24.0 release?

### ISSUE THREAD

**Issue by johnhaley81** [libgit2/libgit2#3587]
Hi guys,

Just a friendly ping to see what your plans are for releasing what's currently in `HEAD`. Last release was back in November which was a bugfix bump to 0.23.4 and I haven't seen any news of what's up next.

Thanks!

**Comment by carlosmn** [comment]
The 0.24 release will be done soon. It would have usually been released towards the end of December, but this year the core team was busy/on vacation around this time.

**Comment by johnhaley81** [comment]
I figured as much. Thank you guys for your excellent work again! Much <3
