### ISSUE TITLE
Taking care of API/ABI backward compatibility

### ISSUE THREAD

**Issue by aponomarenko** [libgit2/libgit2#3591]
Hello,

Please continue taking care of API/ABI backward compatibility. It's very important for Linux maintainers.

I've recently developed a tool to help maintaining API/ABI changes in C libraries and just run it against the libgit2 today. And I'd like to share resulting compatibility report with you: http://abi-laboratory.pro/tracker/timeline/libgit2/

The report may be useful for Linux maintainers, so I decided to share results in the public issue tracker of the library in order to leave some instructions for those who would be interested in this topic.

Tools used:

https://github.com/lvc/abi-tracker
https://github.com/lvc/abi-compliance-checker
https://github.com/lvc/abi-dumper

Thank you.

**Comment by ethomson** [comment]
Thanks for this information.  At present, we have not yet reached 1.0 and thus we do not yet provide any API or ABI compatibility.  Once we have reached 1.0 we will commit to compatibility and this will become useful.  In the meantime, though, I'm going to close this issue as we have other issues tracking the road to 1.0.

Thanks again.
