### ISSUE TITLE
Checkout conflict when a submodule has changed

### ISSUE THREAD

**Issue by srajko** [libgit2/libgit2#3608]
When doing a safe checkout with libgit2 (for example via `git_checkout_tree`), I am getting a conflict error if a submodule is modified (if it's checked out to a different commit than the parent repo specifies).  The checkout works fine in the CLI.

The modification is first detected here - https://github.com/libgit2/libgit2/blob/maint/v0.23/src/checkout.c#L190

Then it's turned into a an action here -
https://github.com/libgit2/libgit2/blob/maint/v0.23/src/checkout.c#L468-L469
(as part of https://github.com/libgit2/libgit2/blob/maint/v0.23/src/checkout.c#L667 and https://github.com/libgit2/libgit2/blob/maint/v0.23/src/checkout.c#L1281-L1282)

The conflict is then turned into an error here -
https://github.com/libgit2/libgit2/blob/maint/v0.23/src/checkout.c#L1306-L1315

Is there a way around this problem? Or, if this is a bug, could you suggest what the fix should be?  It seems like conflicts on submodules should be ignored in this case, if we're not updating submodules as part of the checkout.

**Comment by ethomson** [comment]
I haven't been able to put a lot of cycles towards thinking about #3583 - but the few minutes that I have thought about it, it seems reasonable.  (I worry a bit about edge cases.)

Does #3583 solve this problem?

**Comment by srajko** [comment]
Good call - yep, that does solve it.  I'll comment there in a bit.

**Comment by ethomson** [comment]
Fixed via #3583
