### ISSUE TITLE
Cannot distinguish positive and negative UTC (+0000 / -0000) offset in signatures

### ISSUE THREAD

**Issue by olasd** [libgit2/libgit2#3620]
Git considers "-0000" a valid offset for signature lines. It can be found in the wild in some repositories.

Unfortunately, libgit2 supports such offsets, but coerces them silently to "0", which is ambiguous with "+0000". This prevents libgit2 from being able to round-trip all objects and computing their original hash.

If fixing that issue is desirable, I might be able to submit a pull-request. Let me know what you think.

Cheers,
Nicolas

**Comment by ethomson** [comment]
Ugh.  It's disappointing that any git client produced a timezone offset of `-0000`, which is clearly just ridiculous.

Out of curiosity, is this a theoretical concern or are you really trying to literally round-trip the data?  I fear that there are other limitations that would stymie a person trying to do this - for instance, `-0000` seems roughly equally as legitimate as if the timezone offset had been `foobar`.  So I wonder if simply understanding `-0000` is good enough for you, or if you want some more raw access to the data that was in a commit instead.

**Comment by linquize** [comment]
Might "adding a sign byte in the struct" help?

**Comment by olasd** [comment]
* Edward Thomson <notifications@github.com> [2016-02-18 12:47:45 -0800]:

> Ugh.  It's disappointing that any git client produced a timezone offset of `-0000`, which is clearly just ridiculous.
> 

Yes, definitely.

> Out of curiosity, is this a theoretical concern or are you really trying to
> literally round-trip the data?  I fear that there are other limitations that
> would stymie a person trying to do this - for instance, `-0000` seems roughly
> equally as legitimate as if the timezone offset had been `foobar`.  So I
> wonder if simply understanding `-0000` is good enough for you, or if you want
> some more raw access to the data that was in a commit instead.

This isn't a theoretical concern: I'm working on a project where we have made a
generic "revision" model out of the fields that are present in a "git commit"
object. For efficiency in imports (and, down the line, exports as well), we
use the way git calculates its object identifiers as our "intrinsic revision
identifier".

We therefore need to be able to "extract" enough metadata from commits to be
able to recompute the checksum of the object. Currently, the data libgit2
exposes is not sufficient (well, we can access the full commit object, but
that's not very appealing).

While I agree with your concern about genericity, in the wild, -0000 is the
only surprising value that we have found for a timezone (on a dataset of a bit
more than 300 million unique git commits). The raw header access lets us handle
the gpgsig and mergetags headers that aren't really exposed by libgit2.

As for implementation, I believe that a 'negative utc' boolean in the signature
structure would be enough (that's what dulwich does, for instance).

**Comment by hkleynhans** [comment]
Possible patch: https://github.com/libgit2/libgit2/pull/4408

**Comment by pks-t** [comment]
I've just merged #4408. Please verify this fixes your problems and close the issue if so.

**Comment by olasd** [comment]
I'm afraid we've stopped using pygit2/libgit2 (in favor of dulwich) for that project so I can't validate that #4408 fixes the issue concretely. By the description and the content of the patch the approach looks like it would, so I guess you should feel free to close this.

Thanks for libgit2!
