### ISSUE TITLE
Crashes when concurrently fetching in two different repositories

### ISSUE THREAD

**Issue by srajko** [libgit2/libgit2#3624]
We have an example using NodeGit in which a fetch is performed on two separate repos at the same time (https://github.com/nodegit/nodegit/issues/907), and it crashes.  We have an experimental thread safety system that can prevent overlapping calls to libgit2 per repository (so libgit2 calls working on the same repository are not allowed to overlap, libgit2 calls working on different repositories are allowed to overlap in different threads), but in this case our thread safety system doesn't help.  Modifying it to completely prevent overlapping calls to libgit2 does help though.

Is there any part of a fetch that uses shared objects, even for separate remotes and separate repositories?  We have seen similar crashes on different systems, and they seemed to implicate transactions, transports, and credentials.

From https://github.com/libgit2/libgit2/blob/master/THREADING.md I see that the crypto library could be at fault as well.  For https://github.com/nodegit/nodegit/issues/907, I was reproducing it with openssl.  I did try calling `git_openssl_set_locking`, but it did not make a difference in this case.

**Comment by carlosmn** [comment]
If you use OpenSSL (which you would if you use a released version of libssh2) you need to set up *its* thread safety. There's nothing libgit2 can do for you there.

**Comment by carlosmn** [comment]
Note that `git_openssl_set_locking()` won't do anything for you on OS X because libgit2 isn't linking against OpenSSL, so it's a no-op.

**Comment by ethomson** [comment]
Interesting.  There are very few pieces of state that are shared between repository instances; though indeed there are some that you might be running into.

Just to clarify one point:  you're fetching to two different on-disk repositories (eg `/foo/bar` and `/baz/quz`)?  Not two different repository instances of the same on-disk repository?

Do you have minidumps or core dumps that you can share?

**Comment by srajko** [comment]
@ethomson Correct, it is two different on-disk repositories, each with a remote pointing to a distinct github repository.  We do have some crash logs, I will paste them below.

@carlosmn Thanks for the pointers - we looked further into OpenSSL and libssh2 thread safety and found some things that we could be doing better (we are now setting up the OpenSSL locking callbacks manually, and calling `libssh2_init` ourselves - we found that if you don't init it explicitly, it will auto-init when needed, but the auto-init is not thread safe).  This much seemed to address the crash reported in nodegit/nodegit#907. I will do a PR on the documentation with some additional references we found helpful.

We are going to test GitKraken with the added OpenSSL / libssh2 thread safety and see if it helps resolve the intermittent crashes we've been seeing there.  Here are some crash logs we've seen in the past:

```
00007FFF51405E72 (ntdll): (filename not available): RtlRestoreContext
00007FFF51404693 (ntdll): (filename not available): RtlRaiseException
00007FFF51442D0A (ntdll): (filename not available): KiUserExceptionDispatcher
0000000700000003 ((module-name not available)): (filename not available): (function-name not available)
00007FFF1546A7D1 (nodegit): (filename not available): git_transport_init
00007FFF1546AD26 (nodegit): (filename not available): git_transport_init
00007FFF154A4228 (nodegit): (filename not available): git_transaction_free
00007FFF1544CFB4 (nodegit): (filename not available): git_remote_connect
00007FFF1544D947 (nodegit): (filename not available): git_remote_fetch
```

```
PID 31094 received SIGSEGV for address: 0x0
0   segfault-handler.node               0x000000010ada1e9e _ZL16segfault_handleriP9__siginfoPv + 286
1   libsystem_platform.dylib            0x00007fff8d4a7eaa _sigtramp + 26
2   ???                                 0x00007fbe062eeb10 0x0 + 140454124251920
3   nodegit.node                        0x000000010ba27c33 git_smart__close + 126
4   nodegit.node                        0x000000010ba27ca9 git_smart__free + 15
5   nodegit.node                        0x000000010ba07b74 git_remote_connect + 282
6   nodegit.node                        0x000000010ba08290 git_remote_fetch + 120
```

**Comment by srajko** [comment]
I submitted a PR for docs additions that helped us resolve nodegit/nodegit#907.

The two separate stack traces I provided below turned out to be our problem in NodeGit - we fumbled the creds passing from one thread to another in a way that would make it fail intermittently.

**Comment by ethomson** [comment]
@srajko Thanks for the documentation PR.  Are your issues resolved?  Can we close this issue?

**Comment by srajko** [comment]
Yep, resolved and closeable - thanks for the help!
