### ISSUE TITLE
libgit2 fails to properly unstage file.

### ISSUE THREAD

**Issue by bokic** [libgit2/libgit2#3632]
Let say you have some file that is already in git repo, and you modify that file, and stage it, then, if you want to unstage it with libgit2 it will leave that file in staged and deleted state.

The issue can be reproduced with both `git_index_remove_bypath()` and `git_reset_default()` function calls.

Tested on libgit2 that is shipped with Ubuntu 15.10, and with libgit2 latest master on Windows.

Or, maybe I'm doing something wrong.

I'm attaching linux project that shows the issue.

[libgit2_unstage.tar.gz](https://github.com/libgit2/libgit2/files/143439/libgit2_unstage.tar.gz)

**Comment by ethomson** [comment]
The act of "unstaging" is to update the repository's index to match the `HEAD` tree.  So you don't want to *remove* anything from the index, you want to *add* an index entry that matches `HEAD`.

That means that you'll need to reset *to something*.  You should lookup the HEAD commit and reset to that.

For example:

    git_reference *head;
    git_object *head_commit;

    git_repository_head(&head, repo));
    git_reference_peel(&head_commit, head, GIT_OBJ_COMMIT);
    git_reset_default(repo, head_commit, &paths);

**Comment by ethomson** [comment]
I'm going to close this issue - we try to keep issues reserved for bug reports and outstanding work to do.  We try to use [StackOverflow](http://stackoverflow.com/questions/tagged/libgit2) for assistance.  Thanks!

**Comment by bokic** [comment]
Thanks, and sorry for the noise, I will use StackOverflow in future.

**Comment by ethomson** [comment]
No problem at all!  :smile:
