### ISSUE TITLE
We should refresh objects when they're referenced

### ISSUE THREAD

**Issue by carlosmn** [libgit2/libgit2#3650]
git refreshes the mtime of objects (or the pack) when we add a reference to them, to help prune avoid race conditions with older objects which are de- and then re-referenced.

**Comment by carlosmn** [comment]
Quoting @mhagger from another issue:

---

When is a new reference made to an object?

 - When another new object is created that refers to it (e.g., when a newly-created tree refers to an existing blob).
 - When a reference (or, theoretically, a reflog entry) is updated to point directly at the object. Refreshing is needed in this case to cover the race that could otherwise occur if git prune reads the references before the new reference exists, and therefore thinks that the object is unreachable.

It is only necessary to refresh the timestamp on the object that is directly referred-to, not those of its ancestors.

**Comment by ethomson** [comment]
Fixed with #3861
