### ISSUE TITLE
Failed to finish ZLib inflation. Stream aborted prematurely

### ISSUE THREAD

**Issue by matthias-k** [libgit2/libgit2#3657]
Hi,

I use libgit2 via pygit2 to store large amounts of data in git (here, large means lots of small files, especially lots of files in one directory. Not lots of data per file). In the last weeks from time to time when doing larger git operations (creating up to 100 blobs and updating multiple tree objects with 50k entries) I experience errors like

``` python
    sub_tree = repo[tree[sub_directory].id]
  File "/home/matthias/.virtualenvs/Baton/local/lib/python2.7/site-packages/pygit2/repository.py", line 97, in __getitem__
    value = self.git_object_lookup_prefix(key)
_pygit2.GitError: e4272bad38fcaef362226308afbb08e1232f4dab: Failed to finish ZLib inflation. Stream aborted prematurely
```

These errors are completely unreproducible. When I execute the same code again, the error won't occur again. However, sometimes the repository is left with corrupt objects.

I am sorry that I cannot be more specific. If you have some advice about how to get better data on the bug, I will be happy to help.

Best,
  Matthias

**Comment by carlosmn** [comment]
This error would generally indicate that the source of the data has been corrupted. This is a lookup, so a failure here won't generate corrupt object. If you're seeing corrupt objects, check what's creating them.

**Comment by ethomson** [comment]
@matthias-k  Are you still seeing this?  Can you provide reproduction steps?

**Comment by carlosmn** [comment]
Closing due to missing repro and lack of response.
