### ISSUE TITLE
repo::init::extended_1 fails when /tmp mode is 7777

### ISSUE THREAD

**Issue by orivej** [libgit2/libgit2#3665]
`./libgit2_clar -srepo::init::extended_1` (from master) fails on Linux with message
```
  1) Failure:
repo::init::extended_1 [../tests/repo/init.c:370]
  Expression is not true: (02000 & st.st_mode) == 02000
```
when `/tmp` mode is 7777.

To reproduce, run the test under non-root user after `chmod 7777 /tmp`.

When a non-root attempts to set SETGID on a directory under such a /tmp, it looses its SETGID bit:
```
mkdir /tmp/x
stat /tmp/x # reports mode 2755
chmod 2755 /tmp/x
stat /tmp/x # reports mode 0755
```

**Comment by orivej** [comment]
There is the same error in `checkout::index::options_dir_modes`:
```
  1) Failure:
checkout::index::options_dir_modes [../tests/checkout/index.c:297]
  st.st_mode != (GIT_FILEMODE_TREE | 0701) & ~um
  0042701 != 0040701
```

**Comment by carlosmn** [comment]
The test suite is trying to determine that we set the bits correctly for a shared repository, which includes setting the group bits. If the filesystem is stopping us from doing that, then we cannot determine that the code has behaved correctly. The only option for the test suite when it sees this is fail the test.

I don't see how we can support running the tests on such a setup. The filesystem is changing the conditions such that we cannot check that the code is performing correctly. You'd have to run the tests against a different base directory if you want your `/tmp` to have that mode.

**Comment by orivej** [comment]
If I change the code that set the bits for a shared repository to test beforehand if they are already set (and skip chmod if they are), and if that fixes tests, could that be accepted?

**Comment by carlosmn** [comment]
That would lead to incorrect behaviour. If the caller is asking for the group bits to be set, they want the permissions set up in precisely that form so their multi-user git operations work.
