### ISSUE TITLE
Support topological sort by time

### ISSUE THREAD

**Issue by orivej** [libgit2/libgit2#3666]
Currently libgit2 does not support topological sort by time (the resulting order is not chronological). To confirm this, add
```
cl_git_pass(test_walk(_walk, &id, GIT_SORT_TIME | GIT_SORT_TOPOLOGICAL, commit_sorting_time, 1));
```
to `test_revwalk_basic__sorting_modes` in `tests/revwalk/basic.c`. Besides, libgit2 does not document that it does not support this mode, which is particularly surprising (when a user expects it) since it is the default for `git rev-list --date-order`.

**Comment by carlosmn** [comment]
That error would fail because you're asking it to compare topo + time against pure time-sorting, which is not the same. We do support combining topological and time sorting, like `--date-order` does. For some repositories this might not match git completely because there are multiple correct orders which satisfity the topo + time sorting.

**Comment by ethomson** [comment]
As @carlosmn mentioned, we do support topo + time sorting.  And indeed, that change you made to the test is now something that I would expect to fail:  you're now comparing the expected time-sorted output to topo and time sorted.

I'm going to close this issue.  Please reopen it, though, if we've misunderstood the problem that you're reporting.  Thanks!

**Comment by orivej** [comment]
Sorry, I missed the discussion. No, libgit2 does not correctly support topological sorting by time (the equivalent of `--date-order`).

> That error would fail because you're asking it to compare topo + time against pure time-sorting, which is not the same.

In general yes, but in this test time sorted commits happen to also be topologically sorted, so the proposed test should pass, because every unique chronological ordering that does not violate topological constraints is _the_ topological chronological ordering.

> For some repositories this might not match git completely because there are multiple correct orders which satisfity the topo + time sorting.

When all commits have different times, the ordering is unique.

>  Please reopen it, though, if we've misunderstood the problem that you're reporting.

I believe GitHub does not allow me to reopen the issue.
