### ISSUE TITLE
Support .gitattributes for bare repositories

### ISSUE THREAD

**Issue by matto1990** [libgit2/libgit2#3676]
I have been looking into why Gitlab (which uses Rugged, which wraps libgit2) does not respect marking files as binary in the diffs on merge requests.

After tracing it down to libgit2 it seems that the library does correctly support marking files as binary through `.gitattributes`, however, Stan Hu from Gitlab found that it does not support it for bare repositories.

You can read more about my research here: https://gitlab.com/gitlab-org/gitlab-ce/issues/2315#note_4045477

I'm new to all these projects codebases, so I'm unsure how big a task it would be to support this behaviour. Could you provide any guidance on where to start looking or any other hints?

**Comment by stanhu** [comment]
Thanks for raising this issue, @matto1990. It looks like if you copy `.giattributes` into the bare repo as `info/attributes` then things behave as they should. There was a post years ago about adding `.gitattributes` support for bare repositories in git:

http://git.661346.n2.nabble.com/RFC-gitattributes-on-a-bare-repo-td666815.html

**Comment by ethomson** [comment]
> it seems that the library does correctly support marking files as binary through .gitattributes

I disagree; we correctly *ignore* `.gitattributes` in a bare repository.  This is the behavior of git.git.

Let's take a simple example, and add a `.gitattributes` to a repository.

```
zoidberg:Temp/testrepo% git diff HEAD~1..HEAD
diff --git a/foo.txt b/foo.txt
index 8c2d357..f82d87d 100644
--- a/foo.txt
+++ b/foo.txt
@@ -1,4 +1,4 @@
-foo
+foo!
 foo
 foo
 bar
zoidberg:Temp/testrepo% echo '*.txt binary' > .gitattributes
zoidberg:Temp/testrepo% git diff HEAD~1..HEAD               
diff --git a/foo.txt b/foo.txt
index 8c2d357..f82d87d 100644
Binary files a/foo.txt and b/foo.txt differ
```

That all seems correct.  Now if we check it in:

```
zoidberg:Temp/testrepo% git add .gitattributes
zoidberg:Temp/testrepo% git commit -maddgitattributes
[master 8653486] addgitattributes
 1 file changed, 1 insertion(+)
 create mode 100644 .gitattributes
```

And clone the repository to a bare one:

```
zoidberg:Temp% git clone --bare testrepo bare-test.git
Cloning into bare repository 'bare-test.git'...
done.
zoidberg:~/Temp% cd bare-test.git 
zoidberg:Temp/bare-test.git% git diff HEAD~1..HEAD
diff --git a/foo.txt b/foo.txt
index 8c2d357..f82d87d 100644
--- a/foo.txt
+++ b/foo.txt
@@ -1,4 +1,4 @@
-foo
+foo!
 foo
 foo
 bar
```

What *I* would like to see is that this is added to git itself, so that the semantics are well agreed upon by everybody.  Blazing new trails here in libgit2 is always an interop and compatibility nightmare.

**Comment by stanhu** [comment]
> What I would like to see is that this is added to git itself, so that the semantics are well agreed upon by everybody. Blazing new trails here in libgit2 is always an interop and compatibility nightmare.

I agree. Consistent behavior is a good thing.

**Comment by matto1990** [comment]
Thanks for the replies. I agree that matching behaviour between git and libgit2. I'll look into the possibility of changing the functionality of git before coming back here for the matching change.

As I said, I have little experience with these codebases, so if you have some ideas for where to look to implement this it would be greatly appreciated.

**Comment by ethomson** [comment]
I'm closing this as there's no action for us to take in the libgit2 project at the moment.  If this is something that is done in git core, then we should reopen this.  Thanks!

**Comment by Jamedjo** [comment]
@ethomson This is possible when using `GIT_INDEX_FILE=` from a bare repo:

E.g. Using values set in the nested `.gitattributes` file in https://gitlab.com/jamedjo/engine/blob/master/subdir/.gitattributes:

```shell
engine.git|master» GIT_INDEX_FILE=tmp-index git read-tree --reset -i master
engine.git|master» GIT_INDEX_FILE=tmp-index git check-attr --cached --all subdir/pointer.sub
subdir/pointer.sub: diff: lfs
subdir/pointer.sub: merge: lfs
subdir/pointer.sub: text: unset
subdir/pointer.sub: filter: lfs
```

Does allowing use of a specified index sound viable for libgit2?

**Comment by ethomson** [comment]
@jamedjo You can set a `git_index` on a `git_repository` in the same manner.  Does this not produce behavior similar to Git?
