### ISSUE TITLE
broken docs

### ISSUE THREAD

**Issue by nickdesaulniers** [libgit2/libgit2#3678]
The documentation for `git_commit_create` seems broken

https://libgit2.github.com/libgit2/#HEAD/group/commit/git_commit_create

**Comment by carlosmn** [comment]
I've been digging through the stack to see why we're not parsing this and clang, which we use for parsing parsing the comment, seems to consider any function with a `size_t` not to have a comment, so our documentation generation ignores it.

**Comment by carlosmn** [comment]
Fixed via #3716 together with an updated docurium.
