### ISSUE TITLE
Why I got "packfile trailer mismatch" when I call git_remote_fetch

### ISSUE THREAD

**Issue by vcforge** [libgit2/libgit2#3692]
The trace log is(call by **git_remote_fetch**):

> remote: Counting objects: 3, done.
> remote: Compressing objects:  50% (1/2)   Compressing objects: 100% (2/2)   Compressing objects: 100% (2/2), done.
> remote: Total 3 (delta 0), reused 3 (delta 0), pack-reused 0

And the **git** command's log have:

> Unpacking objects: 100%(3/3), done.

**Comment by ethomson** [comment]
That means that you've downloaded a corrupt pack file.  The packfile trailer includes a hash of the contents that preceded it.

Does this happen with every repository that you try to fetch from, or just a particular repository?

**Comment by vcforge** [comment]
If it is the repository‘s problem, there are two confusing place:

First, I can delete the local directory and use **git_clone** to clone the whole repository, and it works well.
Second, I can fetch it by msysgit. The trace log of **git_remote_fetch** is:

> remote: Counting objects: 3, done.
> remote: Compressing objects: 50% (1/2) Compressing objects: 100% (2/2) Compressing objects: 100% (2/2), done.
> remote: Total 3 (delta 0), reused 3 (delta 0), pack-reused 0

And the msysgit's log is:

> remote: Counting objects: 3, done.
> remote: Compressing objects: 50% (1/2) Compressing objects: 100% (2/2) Compressing objects: 100% (2/2), done.
> remote: Total 3 (delta 0), reused 3 (delta 0), pack-reused 0
> Unpacking objects: 100%(3/3), done.

**Comment by vcforge** [comment]
The code is(Windows, repository is on GitHub):
```
	const git_error * pError;
	int iRetVal;
	git_repository* pRepository;
	progress_data pd = {{0}};
	git_remote* pRemote = NULL;

	iRetVal = git_repository_open(&pRepository, "C:\\testrepo");

	iRetVal = git_remote_load(&pRemote, pRepository, "origin");

	git_remote_callbacks remote_callbacks = GIT_REMOTE_CALLBACKS_INIT;

	remote_callbacks.update_tips = update_cb;
	remote_callbacks.progress = progress_cb;
	remote_callbacks.credentials = cred_acquire_cb;
	remote_callbacks.payload = &pd;
	iRetVal = git_remote_set_callbacks(pRemote, &remote_callbacks);
	iRetVal = git_remote_fetch(pRemote);
	pError = giterr_last();          // Here, I got "packfile trailer mismatch"

	git_remote_disconnect(pRemote);
	git_remote_free(pRemote);

```

**Comment by carlosmn** [comment]
Are you saying that through `git_clone` it doesn't fail but it does so reproducibly via `git_remote_fetch`? Have you tried with a recent version of libgit2 (the usage of `git_remote_load()` indicates an old version)? Are you checking for `iRetVal` to indicate an error? Otherwise it could just be left-over from something else.

**Comment by ethomson** [comment]
@vcforge Are you still seeing this or have you resolved this issue?

**Comment by carlosmn** [comment]
Closing due to lack of response.
