### ISSUE TITLE
testsuite failures without openssl on v0.24.0

### ISSUE THREAD

**Issue by andhe** [libgit2/libgit2#3731]
Hello!

While trying to update libgit2 in Debian I stumbled upon testsuite failures which only happens when building with openssl disabled (which is how it's been done in Debian to allow GPLv2 projects to use libgit2 without running into OpenSSL licensing issues).

The first problem is reproducible on git master and  fixed in #3730 

I run into two additional problems after that which I have no idea how they're openssl related:

  1) Failure:
repo::iterator::unreadable_dir [/build/libgit2-0.24.0/tests/repo/iterator.c:1037]
  Expected function call to fail: git_iterator_advance(&e, i)

  2) Failure:
status::worktree::unreadable [/build/libgit2-0.24.0/tests/status/worktree.c:1028]
  0 != counts.wrong_status_flags_count
  0 != 1

I can't reproduce these when building git master, but it seems there's been quite some refactoring of the iterators etc going on. Are the above known (fixed) issues? Is there an easy fix I can use with v0.24.0 ? Will a new release come soon?

**Comment by ethomson** [comment]
@andhe I can't reproduce those in v0.24.0.  I also can't imagine that they're openssl related - and while there has been iterator refactoring going on, that has happened post-v0.24.0.

I'm not very familiar with the debian packaging build environment, but these tests do things on the filesystem that may not be easily reproducible within a sandboxed environment.  For example, are you running the test suite as root?

When you're building & testing master, are you doing it from within the packaging build environment or in a normal setup?  Can you test v0.24.0 and see if those tests pass when run in a normal build setup?

**Comment by andhe** [comment]
@ethomson thanks for those hints. It seems the failure only happens while running under "fakeroot". Will investigate further.

**Comment by andhe** [comment]
I've worked around this with a hack that disables fakeroot while running the testsuite in the package building for now. I can confirm the above mentioned commit also fixes the issue when running under fakeroot. Please feel free to close this issue. Thanks for planning v0.24.1!

**Comment by ethomson** [comment]
@andhe We just shipped https://github.com/libgit2/libgit2/releases/tag/v0.24.1 for ya - hope this helps.  Thanks for maintaining the Debian package!  :)
