### ISSUE TITLE
[GSoC] Where to start from ?

### ISSUE THREAD

**Issue by saurabhsuniljain** [libgit2/libgit2#3732]
I have applied for GSoC 16, under libgit2 for the project "Port packfile creation optimisations to libgit2",
I am currently reading this :
[pack-objects.c](https://github.com/libgit2/libgit2/blob/77394a27af283b366fa8bb444d29670131bfa104/src/pack-objects.c)
I would like to know how to start for this project and what perquisites I should complete. 
Also are there any other things I should take care of like installing some libraries etc.
@carlosmn @ethomson @tiennou

**Comment by ethomson** [comment]
GSOC has not been finalized.  If you are accepted, you will be contacted at that time.

Also, there's no need to open duplicate issues here.  GSOC should be handled through the GSOC website, not through the libgit2 issue tracker.  Thanks!
