### ISSUE TITLE
ABI stability

### ISSUE THREAD

**Issue by chergert** [libgit2/libgit2#3743]
Do the libgit2 authors have any sort of contract on ABI stability? The continual breaking of ABI in virtually every minor *and* micro release is making it very hard to rely on this software in Linux distributions. This is made more difficult by most Linux distributions having policy disallowing embedding of libraries in applications (due to the added overhead of tracking down security patches).

Please, I implore you, to stop doing things like 6669e3e83900f76721603ed8a7ad9f7435042674 in micro releases which has broken libgit2-glib (and consumers of it such as `GNOME Builder` yet again causing flag days for distributions and developers).

**Comment by ethomson** [comment]
Hi!  Thanks for reaching out, and we're sorry that you've been inconvenienced.

However, I'm a bit confused about your complaint:  although we do break API and ABI compatibility between minor releases (until we reach 1.0) we don't break compatibility in patch-level releases.

I'm looking at the recently released (v0.24.1)[https://github.com/libgit2/libgit2/releases/tag/v0.24.1] and I don't see that I accidentally backported anything that broke compatibility.

To use your specific commit as an example:  6669e3e is not in _any_ released version of libgit2 yet, it would first land in 0.25.

Can you clarify for me:  are you the maintainer of the libgit2 or the libgit2-glib packages, or are you the maintainer or developer of an application that uses libgit2?  Are you using libgit2 directly, or are you using libgit2-glib?

Thanks again.

**Comment by chergert** [comment]
I'm the author of GNOME Builder, which uses libgit2-glib to integrate with our GTK/GObject/Keyring/etc stack. While I don't use Ubuntu, I'm getting complaints from Ubuntu users (presumably running the to be released next week) which has a version tagged as 0.24.1 missing the function removed.

**Comment by chergert** [comment]
I should note, that I have just seen this, and so I haven't dove in deep to track everything down, but I am regularly going through the ABI breakage dance. Does libgit2 use anything like libtool to enforce soname and binary interface versioning or parallel install-ability when ABI does break?

**Comment by carlosmn** [comment]
We do change the SOVERSION for each release, so you so `libgit2.so.24` will not have `_fromchunks()` removed. If the Ubuntu package doesn't have it, they've packaged the wrong thing. You can then have multiple `libgit2.so.X` alongside. E.g. Debian sid has v23 and v24 to install depending on what you were built against.

The one exception to that would be if you install `master` into your system, which you should not be doing.

**Comment by ethomson** [comment]
I'm very sorry to hear that.  We're very careful to keep our SONAMEs in line with our ABI, and we do not break ABI on point releases.  When we do break API and ABI compatibility, we're careful to increment our SONAME.

I'm looking at Ubuntu xenial's [libgit2 package](http://packages.ubuntu.com/xenial/libgit2-dev) which does have a libgit2 0.24.1 package.  But from what I'm looking at, its source _does not_ have 6669e3e.  `git_blob_create_fromchunks` is still a function...

I'm not very familiar with libgit2-glib.  But it looks like they _do not_ have an 0.24.1 package in any Ubuntu yet, only 0.24.0.  And their 0.24.0 _also_ has not removed `git_blob_create_fromchunks`.

**Comment by chergert** [comment]
I'll try to get some more information from the person reporting issues to me. Either way, these types of things would be nice if they were deprecated for a release or two and/or implemented on top of the new API.

**Comment by ethomson** [comment]
> I'll try to get some more information from the person reporting issues to me.

Yes, please.  It seems like it's time to bring in some of the projects in the middle between libgit2 and GNOME Builder.

**Comment by inizan-yannick** [comment]
hi all.
after investigation, there is a libgit2 in /usr/local.
sorry for the inconvenience

**Comment by chergert** [comment]
Thanks @ethomson and @carlosmn for your time!

**Comment by ethomson** [comment]
Thanks for the update @inizan-yannick .

Thanks @chergert for reaching out.  We don't often talk to people using libgit2 directly.  (Many people end up using libgit2 through one of the language bindings like LibGit2Sharp, Rugged, etc.)  We've been pretty vicious about API changes as a result (and let the bindings do the soft, friendly deprecation).  So we appreciate your feedback and will keep that in mind.
