### ISSUE TITLE
Better support for detecting libssh2 

### ISSUE THREAD

**Issue by mtangoo** [libgit2/libgit2#3744]
This might apply for those who love to use OpenSSL on Windows, but I will leave that for later discussion. As Introduction is about a month now I have been fighting with libgit2 on how to link libssh2 so that I have support for SSH. Today I finally solved it and wanted to present what I did and if it can be integrated to libgit2 cmake system.

I found a cmake module [here](https://github.com/datastax/cpp-driver/blob/master/cmake/modules/FindLIBSSH2.cmake)(Thanks to the author). After droping it into libgit2 cmake modules folder and added `SET(LIBSSH2_ROOT  "MY_PATH_TO_SSH_FOLDER")` and changed CMakeList.txt

```
IF (USE_SSH)
	PKG_CHECK_MODULES(LIBSSH2 libssh2)
ENDIF()
```

to

```
IF (USE_SSH)
	FIND_PACKAGE(LIBSSH)
ENDIF()
```
I had SSH2 Support. I wanted to know if the solution is acceptable to libgit2 standard and if I should make a PR to this.

TIA

**Comment by carlosmn** [comment]
On unix, we would much rather depend on `pkg-config` which is the standard way to figure out where libraries are located. This way it's the library authors themselves who say how to link to things.

On Windows this is a different story and AFAIK there is no good way to dealing with this. I suppose we could see about taking in that CMake module for Windows, but it seems to only search for the static library, which is a limitation which I'm not sure we want to have for our build.

**Comment by mtangoo** [comment]
I would like to know what is missing in that file so that I will fix it as I get time and eventually do PR.
As of Linux, I think the best way is to check if `LIBSSH2_ROOT` is set then use it to search the library and if not (the default) search using `package-config`

**Comment by ethomson** [comment]
I think that dynamically loading is the best way to solve this problem; closing in favor of that.

**Comment by mtangoo** [comment]
Can you explain what you mean? Afaik the issue is detection of libssh2 during compile time not runtime

**Comment by carlosmn** [comment]
Detecting at compile-time is one issue, but it's not the big issue. In order for libgit2 to be able to use libssh2 effectively on Windows, it has to be loaded at run-time when the user puts the dll next to us. Anything else makes the distribution of libgit2 for Windows a nightmare.

**Comment by mtangoo** [comment]
You're both right but the ticket was about detecting libssh2 on compile time.
