### ISSUE TITLE
`git_odb_read` is giving error with off-by-1 sha string

### ISSUE THREAD

**Issue by johnhaley81** [libgit2/libgit2#3753]
I'm getting an off-by-1 error [here](https://github.com/libgit2/libgit2/blob/master/src/odb.c#L998). Making a `git_graph_descendant_of` that I'm expecting to error gives me the correct error but the sha has the last char removed.

![image](https://cloud.githubusercontent.com/assets/867780/14802869/43d43854-0b09-11e6-8641-efbbc84c95b5.png)

Not really game breaking, but I thought I should at least log it.

**Comment by carlosmn** [comment]
Fixed via #3818
