### ISSUE TITLE
Is it possible to clone only the last commit in the branch

### ISSUE THREAD

**Issue by RudolfVonKrugstein** [libgit2/libgit2#3768]
Using the gut cli i would do this:

```
git clone --head=1 ...
```

This way I only get the latest commit, not the full history.

Is this also possible with libgit2?

**Comment by AraHaan** [comment]
or just download the whole branch and make a new repo like download it as a zip.

**Comment by carlosmn** [comment]
libgit2 does not support shallow clones or repositories. Neither does it support asking a remote for a tarball/zipfile. Many providers don't support that either, even if they provide alternative means to download a snapshot.

If what you want is a single state of the database (as suggested by the other issue), Git won't help, as it's not designed to do anything like that. S3 or a similar service sounds much more like what you want.

**Comment by ethomson** [comment]
We have other issues tracking the feature work involved in shallow cloning, I'm closing this to avoid duplication.  Thanks for the question.
