### ISSUE TITLE
returning GIT_PASSTHROUGH in git_remote_callbacks::certificate_check should behave as if callback wasn't set

### ISSUE THREAD

**Issue by MrHacky** [libgit2/libgit2#3771]
Currently GIT_PASSTHROUGH is treated as an error and the connection is aborted.
If git_remote_callbacks::certificate_check isn't set the connection succeeds, so returning GIT_PASSTHROUGH should do the same.

**Comment by carlosmn** [comment]
Indeed it should, as mentioned in #3440. Closing this as a duplicate.
