### ISSUE TITLE
Port packfile creation optimisations to libgit2

### ISSUE THREAD

**Issue by saurabhsuniljain** [libgit2/libgit2#3772]
I applied for GSoC 16 under this project [[Port packfile creation optimisations to libgit2](http://git.github.io/SoC-2016-Ideas/)] but couldn't make it through, but now I would like to contribute this project on myself. I had my exams going on till May 02 and returned to home yesterday from college. Now I will free for almost 2 months to work. I almost completed my Mini Project, . 
I would like to know what's the current status of this project. Who are currently working on it ? What's the priority for this project ? If work has been already started on this, where I can find all the discussions ? I tried to search through mailing list but found it difficult to understand. Is there any other way, to go through all the dicussions ?

**Comment by ethomson** [comment]
Hello, thanks for reaching out:

1. Nobody is working on this project.
2. This is low priority.  We would like to have it, but nobody is yet working on it.
3. No work has been started.  There have been no discussions.
4. We don't use a mailing list, we only use git issues.  I don't know offhand where discussions on the git project itself are (if there are any).

The canonical source would be the git source itself - its packbuilder would have the information you're looking for.

I'm going to close this issue - we like to reserve issues for bugs that need attention - for communication with and amongst the project itself, we would use one of the mechanisms outlined in [the README](https://github.com/libgit2/libgit2/blob/master/README.md).

Thanks!
