### ISSUE TITLE
Version number not updated in v0.24.1

### ISSUE THREAD

**Issue by jeffstyr** [libgit2/libgit2#3776]
In the v0.24.1 release, the version number in include/git2/version.h wasn't incremented (it still says 0.24.0); see [`LIBGIT2_VERSION`](https://github.com/libgit2/libgit2/blob/v0.24.1/include/git2/version.h#L10) and [`LIBGIT2_VER_REVISION `](https://github.com/libgit2/libgit2/blob/v0.24.1/include/git2/version.h#L13)

**Comment by ethomson** [comment]
Thanks - unfortunately now that 0.24.1 has been cut, there's no going back.  We'll be sure to correct this in 0.24.2 and / or 0.25.  Apologies!
