### ISSUE TITLE
API docs for type render badly

### ISSUE THREAD

**Issue by vergenzt** [libgit2/libgit2#3779]
At https://libgit2.github.com/libgit2/#HEAD/type/git_odb_backend:

![image](https://cloud.githubusercontent.com/assets/1725615/15161672/f4a492d6-16b3-11e6-83e2-b30f150649cf.png)

The names of the fields all end up in the same column as the table of contents on the right. :( It stays there even when resizing.

**Comment by ethomson** [comment]
This looks fixed to me
