### ISSUE TITLE
git_graph_descendant_of: Please document that a commit is not a descendant of itself

### ISSUE THREAD

**Issue by joshtriplett** [libgit2/libgit2#3780]
Please consider adding a note to the documentation of `git_graph_descendant_of`, stating that a commit is not considered to be a descendant of itself.

**Comment by roysc** [comment]
This behavior is not consistent with `git merge-base --is-ancestor` - is that intentional? It's worth considering whether this should be changed to match git.

**Comment by pks-t** [comment]
I'm closing this issue as documentation has been added via #4362. For now, I'll treat the behaviour as intentional, until somebody has some good arguments that it is not, and in that case that person should open a new issue :) Thanks for the report!
