### ISSUE TITLE
Please support using notes via a commit rather than a ref

### ISSUE THREAD

**Issue by joshtriplett** [libgit2/libgit2#3782]
The various functions that support git notes, such as `git_note_iterator_new`, `git_note_read`, `git_note_create`, and `git_note_remove` all take a `notes_ref` as a string (defaulting to `refs/notes/commits`).  Please consider adding support to use a commit instead of a ref; the functions to read notes would just need the commit, and the functions to write notes would take a notes commit and return a new notes commit.  This would allow storing the notes commit(s) in another way, rather than as a reference.

The existing functions that use a notes ref would then become simple wrappers around the lower-level API.

**Comment by richardipsum** [comment]
@joshtriplett I'd like to help with this if possible. But I don't see how the `notes_ref' parameter can be avoided in the low level calls that would take a commit instead of a notes_ref, if the higher level functions that take a `notes_ref' are to keep their existing functionality. So long as you provide the means to put notes somewhere other than `refs/notes/commits' you will need the `notes_ref' parameter.

**Comment by joshtriplett** [comment]
@richardipsum The functions that read notes would take a commit instead of a notes_ref string, and the existing functions would read the ref, turn it into a commit, and pass that.  The functions that write notes would take a parent commit and return a new commit, and the existing functions would (with appropriate locking) read the ref, turn it into a commit, pass that, get back a commit, and write that to the ref.

**Comment by richardipsum** [comment]
@joshtriplett Right I see, so literally just swapping the `const char *notes_ref` for `git_commit *notes_commit`? Okay I'll give this a try.

**Comment by joshtriplett** [comment]
@richardipsum That and a `git_commit **` out parameter for calls that write notes to provide the new commit they create.

**Comment by richardipsum** [comment]
Ack :smile_cat:

**Comment by richardipsum** [comment]
Hi! Sorry it's taken me so long to get this done. Pull request #4159 implements this feature request and is ready for review. :)

**Comment by richardipsum** [comment]
@carlosmn Hi, do you have any thoughts on my attempt at implementing this feature request?

**Comment by richardipsum** [comment]
@ethomson I implemented the solution to this issue 3 months ago and I've had no feedback at all, it seems as if there's no real desire for this functionality, can I suggest then that we close both the PR and this issue?

**Comment by joshtriplett** [comment]
@richardipsum I'm still really interested in this, and I'm sorry to see that you haven't gotten much response.

**Comment by richardipsum** [comment]
@pks-t You seem pretty active here can you help solve this issue? I opened the PR for it ages ago

**Comment by ethomson** [comment]
Fixed via #4159
