### ISSUE TITLE
Cannot resolve https addresses (Ubuntu 16.04)

### ISSUE THREAD

**Issue by anselg** [libgit2/libgit2#3786]
When I try to clone from https addresses, libgit2 fails. The message I get when I print out the git_error struct is: 
```
12: Failed to resolve address for https: Name or service not known
```

I'm getting this error when I use the system libgit2 package (Ubuntu 16.04) and when I build libgit2 from source (HEAD of master). I saw https://github.com/libgit2/pygit2/issues/573 and make sure I had libssl-dev installed.

It seems that the library isn't building with openssl properly. When I print out the GIT_FEATURE_THREADS information, I'm only getting the THREADS and SSH features. What's confusing is that when I look through the cmake output, it shows that it found libssl. 
```
-- The C compiler identification is GNU 5.3.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Performing Test HAVE_STRUCT_STAT_ST_MTIM
-- Performing Test HAVE_STRUCT_STAT_ST_MTIM - Success
-- Performing Test HAVE_STRUCT_STAT_ST_MTIMESPEC
-- Performing Test HAVE_STRUCT_STAT_ST_MTIMESPEC - Failed
-- Performing Test HAVE_STRUCT_STAT_MTIME_NSEC
-- Performing Test HAVE_STRUCT_STAT_MTIME_NSEC - Failed
-- Performing Test HAVE_STRUCT_STAT_NSEC
-- Performing Test HAVE_STRUCT_STAT_NSEC - Success
-- Checking for module 'libcurl'
--   Found libcurl, version 7.47.0
-- Found OpenSSL: /usr/lib/i386-linux-gnu/libssl.so;/usr/lib/i386-linux-gnu/libcrypto.so (found version "1.0.2g") 
-- Found HTTP_Parser: /usr/include  
-- Found ZLIB: /usr/lib/i386-linux-gnu/libz.so (found version "1.2.8") 
-- Checking for module 'libssh2'
--   Found libssh2, version 1.5.0
-- Looking for libssh2_userauth_publickey_frommemory in ssh2
-- Looking for libssh2_userauth_publickey_frommemory in ssh2 - not found
-- Performing Test IS_FVISIBILITY=HIDDEN_SUPPORTED
-- Performing Test IS_FVISIBILITY=HIDDEN_SUPPORTED - Success
-- Performing Test IS_WDOCUMENTATION_SUPPORTED
-- Performing Test IS_WDOCUMENTATION_SUPPORTED - Failed
-- Performing Test IS_WNO-MISSING-FIELD-INITIALIZERS_SUPPORTED
-- Performing Test IS_WNO-MISSING-FIELD-INITIALIZERS_SUPPORTED - Success
-- Performing Test IS_WSTRICT-ALIASING=2_SUPPORTED
-- Performing Test IS_WSTRICT-ALIASING=2_SUPPORTED - Success
-- Performing Test IS_WSTRICT-PROTOTYPES_SUPPORTED
-- Performing Test IS_WSTRICT-PROTOTYPES_SUPPORTED - Success
-- Performing Test IS_WDECLARATION-AFTER-STATEMENT_SUPPORTED
-- Performing Test IS_WDECLARATION-AFTER-STATEMENT_SUPPORTED - Success
-- Performing Test IS_WNO-UNUSED-CONST-VARIABLE_SUPPORTED
-- Performing Test IS_WNO-UNUSED-CONST-VARIABLE_SUPPORTED - Failed
-- Performing Test IS_WNO-UNUSED-FUNCTION_SUPPORTED
-- Performing Test IS_WNO-UNUSED-FUNCTION_SUPPORTED - Success
-- Looking for futimens
-- Looking for futimens - found
-- Looking for qsort_r
-- Looking for qsort_r - found
-- Looking for qsort_s
-- Looking for qsort_s - not found
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Looking for clock_gettime in rt
-- Looking for clock_gettime in rt - found
-- Found PythonInterp: /usr/bin/python (found version "2.7.11") 
-- Configuring done
-- Generating done
```

I don't really know what's happening at this point. 

For reference, this is the code I was running: 
```
#include <git2.h>
#include <stdio.h>

static int do_clone(const char *url, const char *path)
{
   git_repository *repo = NULL;
   int ret = git_clone(&repo, url, path, NULL);
   git_repository_free(repo);

   const git_error *e = giterr_last();
   printf("Error %d/%d: %s\n", ret, e->klass, e->message);

   return ret;
}

void print_features(void) {
   int features = git_libgit2_features();
   printf("Features: %d\n", features);
   if (features & (1<<0)) printf("\tGIT_FEATURE_THREADS\n");
   if (features & (1<<1)) printf("\tGIT_FEATURE_HTTPS\n");
   if (features & (1<<2)) printf("\tGIT_FEATURE_SSH\n");
   if (features & (1<<3)) printf("\tGIT_FEATURE_NSEC\n");
   return;
}

int main(int argc, char **argv)
{
   git_libgit2_init();
   const char *url, *path;

   if (argc < 3) {
      printf("USAGE: clone <url> <path>\n");
      return -1;
   }

   print_features();

   url = argv[1];
   path = argv[2];
   return do_clone(url, path);
}
```

Thanks.

**Comment by ethomson** [comment]
This error is that you're failing DNS, it doesn't appear to have anything to do with SSL.  The error message is very suspicious, it makes it appear that you're trying to resolve a hostname of `https`.

What is the URL that you're actually invoking your program with?

**Comment by anselg** [comment]
The url I've been trying is https://github.com/rtxi/plugin-template. I also get the same result with other urls, such as https://github.com/libgit2/libgit2. 

I get the same error message whether I provide a valid https url or complete gibberish. For example, both https://github.com/rtxi/plugin-template and https://woeirsidjalkfowt.owieruowier produce: 
```
12: Failed to resolve address for https: Name or service not known
```

When I change a valid https url to http (i.e. http://github.com/rtxi/plugin-template), I get: 
```
16: there is no TLS stream available
```

When I change gibberish https to http (http://woeirsidjalkfowt.owieruowier/), I get:
```
12: curl error: Could not resolve host: woeirsidjalkfowt.owieruowier
```

**Comment by ethomson** [comment]
Hmm.  Thanks for the report.  It looks like you're using the libcurl transport...

Does this work if you set up your build environment with `cmake -DCURL=OFF`?

**Comment by anselg** [comment]
Same story. The error message is `Failed to resolve address for https: Name or service not known`, and only `GIT_FEATURE_THREADS` and `GIT_FEATURE_SSH` are enabled. 

Relevant section of cmake output (libcurl is disabled):
```
-- Performing Test HAVE_STRUCT_STAT_NSEC - Success
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.0.2g") 
-- Found HTTP_Parser: /usr/include  
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8") 
-- Checking for module 'libssh2'
--   Found libssh2, version 1.5.0
-- Looking for libssh2_userauth_publickey_frommemory in ssh2
-- Looking for libssh2_userauth_publickey_frommemory in ssh2 - not found
-- Performing Test IS_FVISIBILITY=HIDDEN_SUPPORTED
```

**Comment by carlosmn** [comment]
The libgit2 library your program is using is not being linked to any TLS implementation, so it does not know what the `https` schema means. If the build system does show it detects OpenSSL then the most likely explanation is that you're not loading the new libgit2 you're building. Check with `ldd` what your program is going to load, or with `strace` to see how it's probing for the shared library.

**Comment by ethomson** [comment]
Please also remember that cmake caches these sorts of things, so if you simply ran `cmake` and then subsequently run `cmake -DCURL=OFF`, it will have effect.  Be sure to remove your build directory and run `cmake -DCURL=OFF` in a fresh one for it to have an effect.

**Comment by anselg** [comment]
My bad. I forgot to clear out the build directory before recompiling. After reinstalling, `GIT_FEATURE_HTTPS` is enabled and libgit2 successfully clones from https urls. I'm now running into another issue where the program I pasted in my first post segfaults when it executes `do_clone`. (The url I'm using is https://github.com/rtxi/plugin-template.) 

I ran a recursive diff against a copy of the repository cloned via libgit2's `do_clone` (test/) and another cloned via a command line `git clone` (plugin-template/) and [uploaded it here](https://github.com/libgit2/libgit2/files/265973/diff.txt). 

I also made an `strace` log. From the end of the strace log, I noticed that it runs into an `ENOENT (No such file or directory)` error when processing .git/index. The .git/index binary showed up in the diff, but I don't know if that's interesting or to be expected. Here's a snippet from the very end of the `strace` output: 

```
lstat("/home/canary", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
lstat("/home/canary/test", {st_mode=S_IFDIR|0775, st_size=4096, ...}) = 0
lstat("/home/canary/test/plugin-template.png", {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
write(4, "\211PNG\r\n\32\n\0\0\0\rIHDR\0\0\0014\0\0\1\v\10\2\0\0\0\330\317\355"..., 12628) = 12628
close(4)                                = 0
stat("/home/canary/test/plugin-template.png", {st_mode=S_IFREG|0644, st_size=12628, ...}) = 0
lstat("/home/canary/test/.git/index", 0x7ffff69f05e0) = -1 ENOENT (No such file or directory)
stat("/home/canary/test/.git/index", 0x7ffff69f05e0) = -1 ENOENT (No such file or directory)
access("/home/canary/test/.git/index.lock", F_OK) = -1 ENOENT (No such file or directory)
open("/home/canary/test/.git/index.lock", O_WRONLY|O_CREAT|O_EXCL|O_TRUNC|O_CLOEXEC, 0666) = 4
write(4, "DIRC\0\0\0\2\0\0\0\tW9\240\2\35\366g\256W9\240\2\35\366g\256\0\0\0\0"..., 732) = 732
write(4, "\370\t>~o\330\207&\353\367,\330\326\206\353f.\332l\272", 20) = 20
close(4)                                = 0
link("/home/canary/test/.git/index.lock", "/home/canary/test/.git/index") = 0
unlink("/home/canary/test/.git/index.lock") = 0
stat("/home/canary/test/.git/index", {st_mode=S_IFREG|0664, st_size=752, ...}) = 0
munmap(0x7f52451ac000, 104119)          = 0
close(3)                                = 0
munmap(0x7f52451e3000, 5748)            = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0} ---
+++ killed by SIGSEGV (core dumped) +++
Segmentation fault (core dumped)

```

The full log doesn't seem that interesting, but I'll [upload it just in case](https://github.com/libgit2/libgit2/files/265982/strace.txt)

**Comment by anselg** [comment]
Ignore that last post. The reason I was getting that segfault was that I was doing operations on a `git_error` struct when there wasn't an error. 

`git_clone()` works when I build with the -DCURL=OFF flag set. Thanks.

**Comment by mafrosis** [comment]
Hello folks, I know this is closed, but I just had the same problem with the ubuntu 16.04 package. I see the solution above was compiling oneself, but that seems overkill for this feature? Any ideas why this might occur with the ubuntu package, or where this should be reported?

**Comment by carlosmn** [comment]
@mafrosis if your packager did not build libgit2 with TLS support, you should complain to them. There is nothing we can do from here.
