### ISSUE TITLE
Please make git__date_rfc2822_fmt public

### ISSUE THREAD

**Issue by joshtriplett** [libgit2/libgit2#3787]
`git__date_rfc2822_fmt` includes the `__` that denotes an internal-use function.  Considering the widespread use of rfc2822 dates in Git, please consider exposing this function as `git_date_rfc2822_fmt`.

**Comment by carlosmn** [comment]
For the same reason as in #1708 this should remain internal. There is nothing Git-specific about this date format that means a Git library is the place where your program should be taking it from. Your programming language has ways of formatting dates which are meant to be used in general. If we happen to have a function that does this formatting internally, that's basically an accident.
