### ISSUE TITLE
git_diff_stats_to_buf should not show "0 insertions" or "0 deletions"

### ISSUE THREAD

**Issue by joshtriplett** [libgit2/libgit2#3788]
`git diff --stat` (or `git diff --shortstat`) simplifies the diffstat by not showing "0 insertions" or "0 deletions".  For instance, for a patch adding a line to a file, git shows:

```
 a | 1 +
 b | 1 +
 c | 1 +
 3 files changed, 3 insertions(+)
```

For the same patch, libgit2's `git_diff_stats_to_buf` shows:

```
 a | 1 +
 b | 1 +
 c | 1 +
 3 files changed, 3 insertions(+), 0 deletions(-)
```

Please consider adding the same simplification to `git_diff_stats_to_buf`.

**Comment by carlosmn** [comment]
Fixed via #3809
