### ISSUE TITLE
openssl_stream.c:285:2: warning: dereferencing type-punned pointer will break strict-aliasing rules

### ISSUE THREAD

**Issue by jonasstein** [libgit2/libgit2#3800]
The QA script of gentoo linux detected the following severe warning in the source:

```
 * QA Notice: Package triggers severe warnings which indicate that it
 *            may exhibit random runtime failures.
 * /var/tmp/portage/dev-libs/libgit2-0.22.3/work/libgit2-0.22.3/src/openssl_stream.c:285:2: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]

```

**Comment by ethomson** [comment]
Thanks for reporting this - we've fixed this quite a while ago (0.22.3 is a year old), so I'm closing this.

Is this the current version that gentoo is shipping?  If so, I would strongly encourage you to update (if you are the maintainer for this package) or encourage them to update (otherwise).
