### ISSUE TITLE
clarification on license

### ISSUE THREAD

**Issue by fommil** [libgit2/libgit2#3807]
the license has a linking exception to GPLv2 https://github.com/libgit2/libgit2/blob/master/COPYING but I'm not sure how you're allowed to legally do that without the permission of all git contributors. Did you get permission, or has a single copyright owner (such as Linus, but I'm not sure if he has ever asked for a copyright assignment) given permission?

**Comment by vmg** [comment]
We have explicit permission for all the relevant pieces of code. See https://github.com/libgit2/libgit2/blob/master/git.git-authors. Thank you!

**Comment by fommil** [comment]
@vmg thanks for clarifying. However I'm not sure that's enough. If any of your contributors view the git sources while writing their code, it means their contributions are subject to the GPLv2, not the GPLv2 with classpath exception. Are you sure that everything is a clean room implementation?

**Comment by vmg** [comment]
Yes, we're sure libgit2's licensing holds to scrutiny. This is a library used in commercial products by very large corporations with very large legal teams full of specialists on IP and software licenses. The code has been combed back and forth many times.

Please feel free to hire a legal team and do your own IP review, however. An extra set of eyes never hurt. :)

**Comment by fommil** [comment]
@vmg having worked in large corporations, I remain sceptical as to what "combing" actually means, but it is certainly reassuring to know that the matter has been taken seriously. Most likely social pressure is enough to force all git contributors into agreeing, since you've managed to obtain permission from some of the top commiters.
