### ISSUE TITLE
Difference between `git checkout --force HEAD` and `git_checkout_head()` with force

### ISSUE THREAD

**Issue by clns** [libgit2/libgit2#3811]
It seems that `git checkout --force HEAD` and `git_checkout_head()` (with force) behave differently in some cases. `git_checkout_head()` appears to do nothing.

To illustrate this I created a repo that can be cloned and tested - [clns/libgit2-checkout-head](https://github.com/clns/libgit2-checkout-head). All the details are included there. The repo actually uses [git2go](https://github.com/libgit2/git2go) instead of [libgit2](https://github.com/libgit2/libgit2), for convenience.

I think this is related to #2864. It happens when the HEAD is updated before the checkout, and in that issue it is explained why it happens. However `git checkout --force HEAD` behaves differently (it does modify the worktree even if the HEAD was updated prior), and my understanding is that the too should work the same.

**Comment by ethomson** [comment]
Thanks for the bug report and the very detailed reproduction steps.  This is exceptionally helpful.

Note that this is definitely _not_ related to #2864.  As noted, #2864 is a _documentation issue_.  (You can change your example to a tree checkout to illustrate the problem.)

You assessed the problem correctly in your StackOverflow answer - if there is no index at the beginning of the checkout operation _and_ there is nothing to do (ie the workdir matches the checkout target), we do not accurately update the contents of the index.

I'll take a look - thanks again for the bug report.
