### ISSUE TITLE
git_status_list_new stopped creating status

### ISSUE THREAD

**Issue by smallB007** [libgit2/libgit2#3819]
Hi guys, sorry if that's not the correct place for asking this question, but I'm literally desparate. I had my program working perfectly using git_status_list_new, that is the status object was properly initialized and I could do further processing of it.
Yesterday I've run my program and from nowhere, suddenly git_status_list_new cannot initialize status object, that is, status object is nullptr. I didn't touch the code. Don't know what have happened. I wonder if anyone of you happen to come across similar situation?
Any help really appreciated.
Thank you.

**Comment by ethomson** [comment]
What's the return code from `git_status_list_new`?  Does it return an error, or okay?  What error does the library set when this happens?

**Comment by smallB007** [comment]
Hi, thank you for your reply. The return code I'm getting is -1; As for what error the library sets I'm not sure but I'm more than happy to follow your instructions if you'd be so kind and give them to me as to how to check that error value.
Once again, thank you and looking forward to hear from you.

**Comment by ethomson** [comment]
`-1` indicates that an error occurred.  Call [`giterr_last()` to get the last error object](https://libgit2.github.com/libgit2/#HEAD/group/giterr/giterr_last).  For example:

    git_error *err = giterr_last();
    printf("Error: %s\n", err->message);

**Comment by smallB007** [comment]
Hi,
Yes, I am aware of that ;)
When I've followed with debugger I've found out that function pack_backend__read returns -3;
I can of course provide the repo if that would help in any way.
And thanks for the giterr_last(). Will use it and write the result.

**Comment by smallB007** [comment]
Ok, so I've got the message and it says:
"The references cannot be peeled - Cannot retrieve reference target"

**Comment by ethomson** [comment]
Sounds like your `HEAD` is pointing to a nonexistent branch.  Does `git status` on the command line work here?

**Comment by smallB007** [comment]
Hi, sorry for the delay.
Yes I can confirm that git status works as intended.

**Comment by ethomson** [comment]
Glad to hear that it's working now!

**Comment by ethomson** [comment]
I reopened this per your request.  Can you provide additional details?  What reference is dangling?  What is it pointing to?  What type of reference is it?

**Comment by smallB007** [comment]
Hi, of course I can provide any details you wish me to provide. I think that perhaps the best reference would be if I can send you that repo (really small and useless, I use it only for testing purposes) and you can try and execute status from your library and see what is happening. What do you think about it?

**Comment by ethomson** [comment]
Sure.  If you link to a zipped up repo, or attach it or what not, I can take a look at it when I have the time.

**Comment by smallB007** [comment]
Hi, thanks for your good will, here is the link:

https://www.mediafire.com/?hp38tas54u3089s

Best regards

**Comment by savalaraymond** [comment]
Yes i can defenatly help 333#22 Enter prise Rp ca

**Comment by ethomson** [comment]
This looks to be obsolete - I apologize for the delay, but I can confirm that `git_status_list_new` works in your repository.
