### ISSUE TITLE
Dual License with ASL 2.0

### ISSUE THREAD

**Issue by sirinath** [libgit2/libgit2#3829]
Is there a possibility to dual license with ASL 2.0 for the main project and binding projects which use GPL? Alternatively license under BSD or MIT?

**Comment by ethomson** [comment]
This would require every contributor to agree to relicense, including the contributors to the Git project itself who have generously allowed us to relicense their GPLed code under our license.  Some of these authors have expressed an unwillingness to use a non-free license.

Remember that we are _not_ licensed under the GPL but a variant that allows a linking exception.  You can use libgit2 in your application (link it) without requiring any particular license in your application.  Only if you modify libgit2 do you need to redistribute the modifications to libgit2 itself.

Binding projects of course are free to choose whatever license they wish.
