### ISSUE TITLE
Expected date for next release?

### ISSUE THREAD

**Issue by wflyer** [libgit2/libgit2#3844]
Hi,

In current release, v0.24.1, sometimes result of `diff` between commits is incorrect.

I discussed this issue with @ethomson at OSCON, and found that the issue is resolved in current master branch of libgit2. However, I can't use master branch build of libgit2 since client library that I use (`pygit2`) only supports released version and not works with the master branch due to API changes.

So, can you say any expected date or plan for next release? (if it looks too late to wait, then I should consider implement `diff` logic in client side)

**Comment by ethomson** [comment]
Sorry about the delay - we're managing this in #3863 which should be landing soon.  Thanks!
