### ISSUE TITLE
Git file commits

### ISSUE THREAD

**Issue by Odraio** [libgit2/libgit2#3848]
Hello all,

I would like to retrieve all log commit messages of a specific file (based on the name of the file). Is it also possible to retrieve the content of a file of a specific commit (based on the SHA)?

Could you point me in the right direction and/ or provide a code snippet?

Thank you in advance!

**Comment by joshtriplett** [comment]
You might find [this example of the blame API](https://libgit2.github.com/libgit2/ex/HEAD/blame.html) useful, to track down changes to a specific file, potentially even across copies or moves.

If, outside the context of the blame API, you want to get at a file within a specific commit: get the commit object, get the tree within that commit, use [`git_tree_entry_bypath`](https://libgit2.github.com/libgit2/#HEAD/group/tree/git_tree_entry_bypath) to get the entry for that path.  Make sure it has the right type, get it as a blob object, and then get the contents of that blob object.

**Comment by Odraio** [comment]
I probably put my question in the wrong topic. Is the Blame API also available in the C# version of libgit2 (libgit2sharp)?

**Comment by shiftkey** [comment]
@Odraio please open an issue against https://github.com/libgit2/libgit2sharp to discuss it further
