### ISSUE TITLE
Weird ~/.gitconfig causes errors when removing a remote

### ISSUE THREAD

**Issue by novalis** [libgit2/libgit2#3856]
Somehow I ended up with the following in my ~/.gitconfig:
[branch "master"]
    remote = origin
    merge = master
    rebase = true

I assume something went crazy while I was running git tests some time, and that I never noticed until now.

This is not a good configuration, but it shouldn't cause problems.  But it does. Specifically, if you have this in your config, and you perform the following set of actions:

create a remote
fetch from that remote
create a branch off of the remote master branch called "master"
delete the branch
delete the remote

The remote delete fails with the message "Could not find key 'branch.master.rebase' to delete". This is because it's iterating over the config entries (including the ones in the global config) and believes that there is a master branch which must therefore have these config keys.

IMO, failing to delete branch.master.rebase (or branch.master.merge) shouldn't be an error.

This is kind of stupid, sorry.

**Comment by linquize** [comment]
Do you use libgit2 to write config file directly? Or via a git client that uses libgit2?

**Comment by novalis** [comment]
No, I'm not blaming libgit2 for writing the bad config.  I have been a git developer, and while hacking on git, I probably screwed something up at some point that caused that to get added.  I've definitely seen some weird shit.

What I'm complaining about is that libgit2 cannot handle the weird config.

**Comment by carlosmn** [comment]
Fixed via #3862
