### ISSUE TITLE
diff flags don't appear to do anything for Index.diff_to_tree

### ISSUE THREAD

**Issue by dlenski** [libgit2/libgit2#3859]
I'm using `pygit2.__version__=='0.24.1'`, and I've found that the `GIT_DIFF_*` constants don't appear to have _any_ effect at all on `index.diff_to_tree`.

Am I missing something here? Is this a bug?

For example, here's a snippet that shows identical diffs with and without the `GIT_DIFF_REVERSE` flag:

```python
import pygit2
from time import time

repo = pygit2.init_repository('/tmp/%d.git'%time(), bare=True)

blob = repo.create_blob('blah blah blah\nx y z\n')
repo.index.add( pygit2.IndexEntry('foo.txt', blob, pygit2.GIT_FILEMODE_BLOB) )
ic = repo.create_commit('refs/heads/master', repo.default_signature, repo.default_signature, 'initial commit', repo.index.write_tree(), [])

blob2 = repo.create_blob('blah blah blah\nx y z\na b c')
repo.index.clear()
repo.index.add( pygit2.IndexEntry('foo.txt', blob2, pygit2.GIT_FILEMODE_BLOB) )

diff = repo.index.diff_to_tree( repo[ic].tree )
print("Forward diff")
print(diff.patch)

diffr = repo.index.diff_to_tree( repo[ic].tree, flags=pygit2.GIT_DIFF_REVERSE)
print("Reverse diff")
print(diff.patch)
```

**Comment by ethomson** [comment]
I think that the best thing to do would be to open an issue in https://github.com/libgit2/pygit2.  `diff_to_tree` appears to simply call `git_diff_tree_to_tree` which does honor diff flags, so it seems like something might be getting munged in the binding.

**Comment by dlenski** [comment]
Ah, thanks! Will do!
