### ISSUE TITLE
confusing naming of two separate sets of enum constants

### ISSUE THREAD

**Issue by dlenski** [libgit2/libgit2#3860]
I've been trying to use pygit2 to generate a diff between a tree and the index, and was trying to figure out how to get output similar to what I would get from `git diff --cached -M HEAD`.

I was mystified to find that whenever I used `flags=GIT_DIFF_FIND_RENAMES`, I would get the diff output in the reverse direction, as if I had used `flags=GIT_DIFF_REVERSE`.

After a lot of confusion, I discovered the problem. `GIT_DIFF_REVERSE` and `GIT_DIFF_FIND_RENAMES` have the **same value** (`==1`)!

The `libgit2/diff.h` source code sheds some light on why:
- The `GIT_DIFF_*` flags actually belong to two _entirely separate_ `enum` types: [git_diff_option_t](https://github.com/libgit2/libgit2/blob/HEAD/include/git2/diff.h#L72-L209) and [git_diff_find_t](https://github.com/libgit2/libgit2/blob/HEAD/include/git2/diff.h#L583-L652).
- The naming differences between these are exceeding subtle: it's not at all apparent from the pygit2 documentation that a `GIT_DIFF_FIND` flag cannot be used where a `GIT_DIFF_[anything-else]` flag _can_ be used.

It seems to me that the `GIT_DIFF_[anything-except-find]` constants should be named `GIT_DIFF_OPTION_*`, so that they could be referred to with an unambiguous prefix that doesn't also include the `GIT_DIFF_FIND_*` constants.

**Comment by dlenski** [comment]
I'm still not 100% certain whether this is best described as an issue with pygit2 lumping all the `enum` constants into the same namespace, or with libgit2's naming of those constants.

I lean towards the latter as the underlying cause, hence posting this as a libgit2 issue, rather than a pygit2 issue.

**Comment by carlosmn** [comment]
We have two distinct types for these variables. It would be better if we could be sure that the compiler would yell at you if you tried to use the wrong one, but we do have them prefixed appropriately. diff is a rather complex operation, so it has a lot of options, and the `GIT_DIFF` has to be there for both a the prefix. It's unfortunate that the `GIT_DIFF_FIND` prefix can be seen as part of the options, but we do tell you exactly which flags you can pass in for each function.
