### ISSUE TITLE
Failure to connect to SSH agent should not be fatal

### ISSUE THREAD

**Issue by Keno** [libgit2/libgit2#3866]
This issue is somewhat connected to #3761, but not entirely.
When the callback requests ssh agent usage, that connection can fail for a
variety of reasons (SSH_AUTH_SOCKET not defined, no permissions to the socket, weird ssh-agent, etc.). Currently, all of these are fatal and terminate the authentication process.
Instead, it would be great if the authentication callback could be called again, to provide
an alternative method of authentication (e.g. prompting the user for privkey/password).
I hacked around this locally, by just causing EAUTH to be returned when `libssh2_agent_connect`
fails. This works fine, but I'm not sure it's the best general solution, since some people may be
interested in why the SSH agent connection failed.

**Comment by tkelman** [comment]
bump, any comments from maintainers?

**Comment by mkitti** [comment]
Almost five years later and Julia is still having to apply this patch out-of-tree

**Comment by extrawurst** [comment]
> Almost five years later and Julia is still having to apply this patch out-of-tree

what patch? I don't even see a PR?

**Comment by mkitti** [comment]
It is more of a workaround than a fix:
https://github.com/JuliaLang/julia/pull/17459#issuecomment-312042758

@Keno 's workaround patch is here:
https://github.com/JuliaPackaging/Yggdrasil/blob/master/L/LibGit2/bundled/patches/libgit2-agent-nonfatal.patch
