### ISSUE TITLE
git_remote_fetch() with refspec "<branch>:" fails, Git does not

### ISSUE THREAD

**Issue by psprint** [libgit2/libgit2#3873]
Luckily, refspec "&lt;branch&gt;" does what "&lt;branch&gt;:" should, so there is a workaround, and ability to utilize FETCH_HEAD's non-durability properties, e.g. to just peek at a repo given via URL, doing git log ..FETCH_HEAD, without incorporating anything durable from the URL.

What I observe is:

Progress:  0
Progress:  0.25
Progress:  nan
Progress:  nan
Progress:  1

(the nans are not a problem). After that git_remote_fetch() returns GIT_ERROR (1), and diff -r after-fetch.git no-fetch.git shows: 

Binary files after-fetch.git/.git/index and no-fetch.git/.git/index differ
Only in after-fetch.git/.git/objects/pack: pack-49c8a6117d6a4fbb155e27cd458bf6941f195cef.idx
Only in after-fetch.git/.git/objects/pack: pack-49c8a6117d6a4fbb155e27cd458bf6941f195cef.pack

Wonder what was changed in index and how to obtain fully clean state?

**Comment by carlosmn** [comment]
I don't know what's changed in your index, but it has nothing to do with fetching. You can use tools like `git ls-files -s` to see what the contents are. The index contains some extra information which can change depending on the exact steps you've taken, so a difference is not surprising.

Similarly with the packfiles, their names depend on their exact content, so having different ones in different repositories is perfectly normal.

I don't know what you mean by "fully clean state". That's only a thing that Git defines as it relates to the worktree, but that again is unrelated to performing network operations.

**Comment by carlosmn** [comment]
The colon w/o rhs fetching issue was fixed via #3882
