### ISSUE TITLE
Poor FETCH_HEAD api

### ISSUE THREAD

**Issue by psprint** [libgit2/libgit2#3878]
There is a function to create annotated commit from FETCH_HEAD entry:

```c
int git_annotated_commit_from_fetchhead(
        git_annotated_commit **out,
        git_repository *repo,
        const char *branch_name,
        const char *remote_url,
        const git_oid *id);
```

In my opinion, to make it 100% useful, it should need just `branch_name`. It also requires `remote_url`. That is hardly acceptable but still is – when calling git_remote_fetch() one has the URL or symbolic name, would somewhat be able to do the job of establishing the URL – that's acceptable. But the function needs not only that, it also needs OID! What things does the function discover, actually? It wants everything in input.

One other way of doing FETCH_HEAD job is `git_repository_fetchhead_foreach()`. However, it doesn't return branch via the callback:

```c
typedef int (*git_repository_fetchhead_foreach_cb)(const char *ref_name,
        const char *remote_url,
        const git_oid *oid,
        unsigned int is_merge,
        void *payload);
```

Now just look at this. If one will make fetch with two refspecs, he will have two the same remote_urls in FETCH_HEAD. How can one discover which URL is for which branch? The only way is to do `git_remote_ls()` and establish OIDs that each of the branches uses at tip. This way it will be possible to differentiate between branches in the `*fetchhead_foreach_cb` call back. Again, one is forced to do the job manually and doubt if he actually gains anything from using the API. The API again wants everything in input – this time it wants prepared data for the callback. Also, the remote_ls way introduces race conditions.

**Comment by ethomson** [comment]
If you want to improve this then open a pull request.

**Comment by ethomson** [comment]
But to answer your question:

> But the function needs not only that, it also needs OID! What things does the function discover, actually? It wants everything in input.

Putting your incredulity aside for a moment, _yes_ it does want everything in input.  That's because it _doesn't_ discover anything at all.  An annotated commit doesn't do discovery, it's a bag of properties that merge and the merge-like functions use.

If you want an API that looks in `FETCH_HEAD` for you then you're welcome to propose one.  Otherwise, you'll need to iterate over the `FETCH_HEAD` contents until you find the one you want and feed it to the annotated commit creation functions.

As to your follow up question about multiple remotes in a `FETCH_HEAD`, I don't understand it.  The first output to the callback is the branch name.  There's no need to call `git_remote_ls`, that would be quite unnecessary.  All the information you need is in the `FETCH_HEAD` file already.

**Comment by psprint** [comment]
Well so it's agreed that no discovery is done. One could call normal annotated commit creation function (git_annotated_commit_lookup? example use: https://github.com/fritzing/fritzing-app/blob/master/src/version/partschecker.cpp#L576) and perform a merge this way.

The first argument of `*fetchhead_*_cb` was a blind spot for me as it didn't contain "branch" in its name and there is no doc in headers for it. If `const char *ref_name` returns a branch name, then indeed everything is OK and the callback is a useful way of FETCH_HEAD analysis.

**Comment by ethomson** [comment]
> Well so it's agreed that no discovery is done. One could call normal annotated commit creation function (git_annotated_commit_lookup? example use: https://github.com/fritzing/fritzing-app/blob/master/src/version/partschecker.cpp#L576) and perform a merge this way.

Indeed you could do this, but the point of the annotated commits is to provide information about the context around the commit - ie, why you're looking it up.

Using an annotated commit from `FETCH_HEAD`, with all the metadata around remote URL and branch information, will allow the merge functions to produce richer context.  For example, when you use the `FETCH_HEAD` to create an annotated commit, you will get a commit message like:

    Merge branch 'branch_name' of http://remote.url/repo.git

Whereas if you use a reference to create an annotated commit, you will get a commit message like:

    Merge branch 'branch_name'

And if you use a commit, then you will get:

    Merge commit '16f825815cfd20a07a75c71554e82d8eede0b061'

So although you will get a merge in each case, it's the messages around the merge that will be improved by the additional context.

**Comment by psprint** [comment]
I just tested that `*fetchhead_foreach*` doesn't return 'not-for-merge' branches. This is a show stopper. Git is confusing in this, libgit2 followed the confusion: doing `git fetch` downloads all objects, wants to merge only currently checked out branch. However, user might checkout other branch after fetch, and then want to merge it. How to do it if `*fetchhead_foreach*` doesn't return 'not-for-merge' branches? Also, why do a "foreach" function while it will be called only once.
