### ISSUE TITLE
Naming a repository

### ISSUE THREAD

**Issue by smallB007** [libgit2/libgit2#3906]
Guys, 
Sorry if that's a silly question, but during creation of repository with 'git_repository_init' I don't see a way to give a name to it. Is there something you don't support in your library and I simply have to implement myself, or am I missing something?
B.T.W:
I'm writing a c++ wrapper for your library in order to help me write an application in MFC (yes MFC ;). My application will have similiar functionality to SourceTree.
Thank you.

**Comment by ethomson** [comment]
Repositories don't have names!  :D  At least not innately - this is not a concept that git is familiar with.

Many visual tools use the name of the working directory, or the name of the folder for bare repositories (sans trailing `.git`).

Eg, `/home/ethomson/foo` might be called `foo`.  `/home/ethomson/bar.git` might be called `bar`.

This is not something that libgit2 provides - even though (by default) we read a repo off disk, we provide several layers of abstraction and a user could create a repository that is backed not by a filesystem but by a database.  So I'm afraid you'll have to derive this from the repo's on-disk path yourself.

**Comment by smallB007** [comment]
Thanks, just wanted to make sure that I'm not implementing functionality that already exists.
Thank you.
Best regards
