### ISSUE TITLE
git_repository_set_head() doesn't include tag name in reflog – `git status` shows OID

### ISSUE THREAD

**Issue by psprint** [libgit2/libgit2#3909]
When doing `git checkout <tag>` git lefts a trace in reflog that allows to interpret detached HEAD state as a tag checkout. The message looks like:

```
ec5bd6c HEAD@{0}: checkout: moving from master to testtag
```

I process the reflog too, and show user that he is detached at tag, not at commit. Message that libgit2 produces is:

```
ec5bd6c HEAD@{0}: checkout: moving from master to ec5bd6cce67ff7d961286cb8a55145072c9bccbc
```

The line of code responsible: https://github.com/libgit2/libgit2/blob/c60210d36780a39db669e52d6d592d339c6a2ed3/src/repository.c#L2290 – it doesn't treat tag specially.

**Comment by carlosmn** [comment]
It's not writing anything special into the reflog. It looks like it or you should be calling `git_repository_set_head_detached_from_annotated()` if you want to do what git does when given a tag.

**Comment by psprint** [comment]
IMO this shouldn't be closed. I wasn't fully clear, however @carlosmn rather got at least spark of the picture. The point is, `git_repository_set_head` will set meaningful log message for branch – there is the `log_message` prepared for `git_reference_symbolic_create`. However, it will not do it for tag – the `log_message` variable is not used. This is an omission and fixing it is rather easy.

**Comment by ethomson** [comment]
Hmm...  I suppose that's reasonable, but I agree with @carlosmn that you probably want `git_repository_set_head_detached_from_annotated` to truly capture the range of values that `git checkout` on the command line can take.

For example, you can `git checkout tagname^{commit}` and git will dutifully write `tagname^{commit}` as the target in the reflog.  `git_repository_set_head` can't capture that.
