### ISSUE TITLE
libgit2_clar test fails on FreeBSD

### ISSUE THREAD

**Issue by asomers** [libgit2/libgit2#3911]
Using a freshly cloned libgit2 repo at rev c60210d36780a39db669e52d6d592d339c6a2ed3 on FreeBSD 11.0-BETA1 amd64, the libgit2_clar test fails.

Test project /usr/home/somers/src/libgit2/build
    Start 1: libgit2_clar
1/4 Test #1: libgit2_clar .............................***Failed  649.44 sec
    Start 2: libgit2_clar-cred_callback
2/4 Test #2: libgit2_clar-cred_callback ...............   Passed    0.02 sec
    Start 3: libgit2_clar-proxy_credentials_in_url
3/4 Test #3: libgit2_clar-proxy_credentials_in_url ....   Passed    0.02 sec
    Start 4: libgit2_clar-proxy_credentials_request
4/4 Test #4: libgit2_clar-proxy_credentials_request ...   Passed    0.02 sec

75% tests passed, 1 tests failed out of 4

Total Test time (real) = 649.61 sec

The following tests FAILED:
	  1 - libgit2_clar (Failed)
Errors while running CTest

**Comment by ethomson** [comment]
Thanks for reporting this.  I'm not sure which test is failing, can you run `libgit2_clar` directly?  It should provide some more output about what is failing and why.

Thanks!

**Comment by asomers** [comment]
> ./libgit2_clar 
Loaded 323 suites: 
Started
.........................................................................................................................................................................SSSSSSSSSSSSS....................................................................................................F....................................................................................................................................................................................................................................S..S.SS.S.........................................................................................S.................................................................................................................................................................................................S....................................S................SSSSS...S......................................................................................................................................................................S........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................S..............................................................................................................................................................................................................................................................................................................................................S................................................................................................................................................................................................................................................................................................................................................SSSSSS..................

  1) Failure:
checkout::typechange::checkout_with_conflicts [/usr/home/somers/src/libgit2/tests/checkout/typechange.c:285]
  cts.conflicts != g_typechange_expected_conflicts[i]
  4 != 3

**Comment by asomers** [comment]
I've dug into the problem a little further.  AFAICT, the test_checkout_typechange__checkout_with_conflicts test creates a small git repo and checks out each revision, one at a time, intentionally creating conflicts by modifying files in the workspace.  The test failure happens when i=2.  In the temporary directory, a "git status" will show

> $ git status
> HEAD detached at 9bdb75b
> Changes not staged for commit:
>   (use "git add/rm <file>..." to update what will be committed)
>   (use "git checkout -- <file>..." to discard changes in working directory)
>   (commit or discard the untracked or modified content in submodules)
> 
> 	modified:   b
> 	deleted:    c
> 	deleted:    d
> 	modified:   e (untracked content)
> 
> Untracked files:
>   (use "git add <file>..." to include in what will be committed)
> 
> 	a/blocker
> 	untracked
> 
> no changes added to commit (use "git add" and/or "git commit -a")

That output is the same on FreeBSD as on Linux.  The problem is with "d".  FreeBSD detects that file as a conflict, but Linux does not.  It looks like "d" was a text file in the previous revision, then the test deleted it and replaced it with an empty directory, the new git revision deletes it and replaces it with an empty file.

I don't know why this shows up as a conflict on FreeBSD but not Linux, and I don't know anything about git's internals, so I'm not sure how far I can follow this.  But I can perform any experiments you need if they'll help debug the problem.
