### ISSUE TITLE
git_commit_dup doesn't exist

### ISSUE THREAD

**Issue by smallB007** [libgit2/libgit2#3913]
Hi guys, 
During the process of wrapping your library in C++ I found out that git_commit_dup doesn't exist. Trivally of course to implement by myself, but as it is listed in your docs I was wondering that I'm 'missing' something? (pun intended) ;)
Thank you.

**Comment by carlosmn** [comment]
It does exist, it was introduced by f0224772 (2016-02-17; git_object_dup: introduce typesafe versions) aka v0.24.0-112-gf022477. It does not exist in any release.

**Comment by smallB007** [comment]
Hi, thank you for your answer. So basically doesn't exist in release version, right? If so, are there any plans to implement it in next release?
Thanks

**Comment by carlosmn** [comment]
It's _already_ implemented. The next release will have what we have in the dev version. But you don't need it, we've had `git_object_dup()` in the releases for years.

**Comment by smallB007** [comment]
Hi thank you for your answer, It is gettin' bit confusing. The bit from your first post, there are two sentences which somewhat contradict each other:
1) It does exist, it was introduced by.....
2) It does not exist in any release.
From your last post 'I think' I can gather that:
a) I can use git_object_dup() instead of git_commit_dup
b) git_commit_dup is implemented but it is only in dev version, not in the latest release
Am I correct in those two  (a and b) points?
Thank you and sorry for seemingly asking third time the same question ;)

**Comment by ethomson** [comment]
Hi @smallB007 - that's exactly right.  It does exist in the current `HEAD` version, but it is not in the latest release.  It will definitely be in the next major release.

In the meantime, you can use:

    git_commit *orig;
    git_commit *dup;
    git_object_dup((git_object **)&dup, (git_object *)orig);

Sorry for the inconvenience, but we'll have that for you in the next version.  😀

**Comment by smallB007** [comment]
Hi @ethomson - Thank you very much for your prompt reply.
That's really good news. For number of reason, one of them being that I didn't loose my mind and can actually understand short, couple of sentences answer ;)
As for more serious part, I've just began the work on wrapping your great/fantastic library in C++, so I'm in no way in a hurry to have every bit of implementation ready 'now'. Another thing is that I do understand the fact that being simply a maintainer of a wrapper of somebody's else's library it will be actually me who will have to adjust to actual state of affairs and I will have to react to changes in your library, not the other way around ;)
Thank you once again for reply and help. Really appreciate it.
Best regards
