### ISSUE TITLE
diff fails on empty directory

### ISSUE THREAD

**Issue by mrh1997** [libgit2/libgit2#3933]
When a tree object contains a subtree that is empty, libgit2-diff does not work any more correctly.
In the example gist at https://gist.github.com/mrh1997/a7f23599231fef236ec85bf48868165d an erornous repo is created (with a single commit with one file ('datafile') and an empty directory ('EmptyDir')).
when diffing this file with git you git 'datafile', when doing the diff with pygit2/libgit2 you get nothing
=> It should show an error OR run the same behaviour that git...

Addmittedly this is a non-usual use-case as empty trees should not be created,
libgit2 provides the tools to do so and you get no feedback if your software uses these tools in an invalid manner (and creates empty dirs).

In my case I needed two days to track down the problem due to the missing error code....

**Comment by mad8vad** [comment]
I got same issue. If I have modified file abc.txt then diff show it
If I create empty directory abd/ diff doesn't show abc.txt
If set diff options to show untracked then abc.txt present

**Comment by pks-t** [comment]
> I got same issue. If I have modified file abc.txt then diff show it
> If I create empty directory abd/ diff doesn't show abc.txt
> If set diff options to show untracked then abc.txt present

This doesn't sound like the same issue as reported here, but please feel free to create a new ticket with a minimal reproducer that shows your error.

I've tried reproducing the reported error in #5374, but failed to do so. I'd thus say the original reported issue has been fixed and will close this issue as soon as #5374 is merged. If I made any mistake in converting your test case to libgit2's API, please let me know and I'll reopen the issue.
