### ISSUE TITLE
Apply git show <commit> on a commit without a parent

### ISSUE THREAD

**Issue by Inesteem** [libgit2/libgit2#3942]
I implemented the example code for git show from your website:
  https://libgit2.github.com/docs/guides/101-samples/
It works fine for almost all commits, but not for init ones without a parent, since it needs the parent commit object, which does not exist.
Is there any work around for this problem? Git itself works on this issue.

**Comment by carlosmn** [comment]
I don't know what problem you mean. You only need the parent commit if there is a parent. If there isn't you would not try to show any parents. That's why `git_commit_parentcount()` is there: so you can figure out how many parents there are.

**Comment by vivaladav** [comment]
I believe @Inesteem refers to the code in the "[Commit to Its Parent](https://libgit2.github.com/docs/guides/101-samples/#diff_commit_to_its_parent)" example in the case when you are dealing with the first commit of a repository which doesn't have a parent.

In that case you need to skip the call to _git_commit_tree_ (as that will trigger an assert) and pass NULL/nullptr to _git_diff_tree_to_tree_.

I would also like to point out how the code in that example is wrong as I reported in this [pull request](https://github.com/libgit2/libgit2.github.com/pull/69).

**Comment by vivaladav** [comment]
On a related note, wouldn't it be better to handle more gently the case when the _commit_ parameter of _git_commit_tree_ is null, maybe setting _tree_out_ to null?

**Comment by ethomson** [comment]
I think the improved docs will help clarify this issue.
