### ISSUE TITLE
Building with VS2008 on Win32

### ISSUE THREAD

**Issue by shadowwalkersb** [libgit2/libgit2#3943]
I am trying to add a build recipe for libgit2 to [conda-forge](https://conda-forge.github.io/), PR (https://github.com/conda-forge/staged-recipes/pull/1658). One of Win32 builds fails [here](https://ci.appveyor.com/project/conda-forge/staged-recipes/build/1.0.7430/job/bh09rjb4r3mjktx3#L394) 

> 1>c:\miniconda\conda-bld\work\libgit2-0.24.1\src\win32/win32-compat.h(10) : fatal error C1083: Cannot open include file: 'stdint.h': No such file or directory

This is the full [output](https://ci.appveyor.com/project/conda-forge/staged-recipes/build/1.0.7430). Any ideas how to solve this?

**Comment by whavinga** [comment]
Most likely see http://stackoverflow.com/questions/126279/c99-stdint-h-header-and-ms-visual-studio

**Comment by shadowwalkersb** [comment]
That helped. Thanks!
