### ISSUE TITLE
Is git-clean supported

### ISSUE THREAD

**Issue by CodeCyclone** [libgit2/libgit2#3952]
I don't see any examples for git-clean nor any API references I could invoke to act like git-clean. I see some things for cleanup but those look unrelated to git-clean.

I want to be able to do something like git clean -fdx on a repo through libgit2, is this possible with current builds? If not is it something planned or is a technical hurdle in the way? I noticed VSTS is calling git.exe directly for this scenario which prompted me to look.

**Comment by carlosmn** [comment]
`git-clean` is a porcelain (user-facing) command and it falls outside of the main scope of this project. You can implement your own `git-clean` for your own system by running a status and deleting whichever files you think shouldn't be there.

**Comment by CodeCyclone** [comment]
Thanks @carlosmn, that makes perfect sense. Closing the issue.
