### ISSUE TITLE
git_blob_lookup performs decompression of blob data

### ISSUE THREAD

**Issue by btaudul** [libgit2/libgit2#3961]
I need to inspect all blobs during a revwalk. I'm only interested in blobs of a certain size. To do that I call git_blob_lookup( git_tree_entry ), then check size using git_blob_rawsize() and if it matches, I retrieve the decompressed blob data using git_blob_rawcontent().

My expectation would be that git_blob_lookup() is very fast, filling just the bare requirements of the blob structure. Contents should be decompressed on first call to git_blob_rawcontent() (and cached for further calls to that function). Unfortunately, decompression is performed in the git_blob_lookup() call, resulting in needless processing of multiple large blobs, which makes the feature I'm writing on too slow to be of any use.

**Comment by carlosmn** [comment]
All of the lookup functions load and, if appropriate, parse the data. If you want to read the metadata for an object, you can use [`git_odb_read_header()`](https://libgit2.github.com/libgit2/#HEAD/group/odb/git_odb_read_header) which on current versions of the library will only decompress enough to get at the size and type.

**Comment by ethomson** [comment]
Since this is by-design, I'm closing this issue.  We like to keep issues for bug and feature requests.  We like to use [StackOverflow](http://stackoverflow.com/questions/tagged/libgit2) for questions about the API since it's a great platform for searching and documentation.

Thanks!  ❤️
