### ISSUE TITLE
push does not report an error if the remote denies the commits

### ISSUE THREAD

**Issue by mrh1997** [libgit2/libgit2#3963]
When pushing commits to a remote via ```git_remote_push()``` no error code is returned if the remote denies the commits i.e. due to hooks.

For example when running the following python script against a protected branch in gitlab (this is done via hooks) ```git_remote_push()``` (called by repo.push()) will return 0:

```python
import pygit2
class CredentialCallback(pygit2.RemoteCallbacks):
    def credentials(self, url, username_from_url, allowed_types):
        return pygit2.UserPass('username', 'password')
repo = pygit2.Repository('/local-repo')
remote = repo.remotes['origin']
remote.push(['refs/heads/master'], callbacks=CredentialCallback())   # here an exception should be thrown, but this does not happen
```

**Comment by cbargren** [comment]
This appears to be the case for protected branches on GitHub as well.

**Comment by carlosmn** [comment]
The acceptance or rejection is reported via the `push_update_reference` callback. It is not an error for the remote to reject a reference, not just because the semantics of that would become too complex to handle any return value properly.

**Comment by mrh1997** [comment]
Thanks for this info.

Although it is obviously a failure from my side I am pretty sure that many other users of libgit2 will run into the same problem.

At least for pygit2 I will provide a pullrequest which contains a small note in the push command.
