### ISSUE TITLE
error in API documentation for git_patch_num_lines_in_hunk

### ISSUE THREAD

**Issue by vivaladav** [libgit2/libgit2#3965]
Current documentation for _git_patch_num_lines_in_hunk_ says the return value is:

"Number of lines in hunk or **-1 if invalid hunk index**"

but the function returns _GIT_ENOTFOUND_ on error which is -3.

**Comment by ethomson** [comment]
Oops!  Great find; would you like to submit a pull request to fix that?

**Comment by vivaladav** [comment]
Sure, no problem. I'll do it after dinner.

**Comment by carlosmn** [comment]
Fixed via #3966
