### ISSUE TITLE
Assertion failure grabbing status list for repo as cloned by Travis CI

### ISSUE THREAD

**Issue by vermiculus** [libgit2/libgit2#3968]
See [this line of the build log](https://travis-ci.org/ksjogo/emacs-libgit2/builds/168327092#L1150) for all of the information I have.

The assertion being thrown is in [`repository.c:git_repository_is_bare`](https://github.com/libgit2/libgit2/blob/67dd314086fd743f2fc5032e9c7ff901cb5e8bab/src/repository.c#L2064). From what I can tell, [these tests](https://github.com/ksjogo/emacs-libgit2/blob/e28d8010aca828c0b2017a1e7541dad801f507c7/test/branch-test.el) are responsible – ultimately calling [this line](https://github.com/ksjogo/emacs-libgit2/blob/e28d8010aca828c0b2017a1e7541dad801f507c7/libgit2-core.c#L136) that appears in the stack trace on Travis. Here is that function (which is largely lifted from [the docs](https://libgit2.github.com/docs/guides/101-samples/#status_iterating_manual)):

```c
static emacs_value Flibgit2_status (emacs_env *env, ptrdiff_t nargs, emacs_value args[], void *data)
{
    /* args[0] := directory path for repository */
    ptrdiff_t directory_size = 1000;
    char directory[directory_size];
    env->copy_string_contents(env, args[0], directory, &directory_size);
/***   `directory' now contains the value of the first argument to libgit2-core-status */
/***    e.g., (libgit2-core-status "Teapot") => directory="Teapot" */

    git_repository *repo = NULL;
    git_repository_open_ext(&repo, directory, 0, NULL);
    git_status_options opts = GIT_STATUS_OPTIONS_INIT;
    git_status_list *statuses = NULL;
    int error = git_status_list_new(&statuses, repo, &opts);
/***    crashes here, I think */

    size_t count = git_status_list_entrycount(statuses);
    if (count == 0) return NULL;

    emacs_value *status_values = malloc(sizeof(emacs_value) * count);
    emacs_value internal_status_values[3];
    for (size_t status_i = 0; status_i < count; ++status_i) {
        const git_status_entry *entry = git_status_byindex(statuses, status_i);
        status_values[status_i] = Fgit_status_entry(env, git_status_byindex(statuses, status_i));
    }
    git_status_list_free(statuses);

    emacs_value Fvector = env->intern(env, "vector");
    emacs_value ret = env->funcall(env, Fvector, count, status_values);
    free(status_values);
    return ret;
}
```

**Comment by ethomson** [comment]
We `assert` on programmatic error.  In this case, we are asserting that a repository is not bare when you call status.

_Is_ your repository non-bare?

**Comment by vermiculus** [comment]
My repository is indeed non-bare, but that's not what we're asserting. We're asserting that `repo`, the function's argument, is not `NULL`.
