### ISSUE TITLE
Installation not working on Arch Linux

### ISSUE THREAD

**Issue by rahulraghu94** [libgit2/libgit2#3971]
I pulled this repository and did the following:
 `$ mkdir build && cd build`
`$ cmake ..`
`$ cmake --build .`

I then tried to compile the `init.c` by doing `$ make init` example program in the examples directory and it compiles just fine.

But when i run it with `./init` it gives me the following error:
`./init: error while loading shared libraries: libgit2.so.24: cannot open shared object file: No such file or directory`

**Comment by carlosmn** [comment]
That series of commands does not install libgit2. Unless you ask it to, it won't put it anywhere that your system would expect to search for dynamic libraries.

You need to run` cmke --build . --target install` or `make install` for it to be put into the prefix. You may then need to run `sudo ldconfig` for the linker to pick up the change.

**Comment by rahulraghu94** [comment]
You guys should update your README to include this!

**Comment by ethomson** [comment]
@rahulraghu94 I think that generally speaking, providing instructions for how to install shared libraries into your system is probably outside the scope of the instructions that any particular library should provide.  But if you have specific ideas for how to communicate this better (links to READMEs, etc) then please submit a pull request to our documentation.

Thanks!

**Comment by rahulraghu94** [comment]
You're probably right. Perhaps more research from my side.

Anyway, I followed with a `make install` followed by `sudo ldconfig` and I'm still facing the same issue.

**Comment by carlosmn** [comment]
The README _does_ say this, the installation steps are just below the build steps.

Are you testing the example binaries still? Check (e.g. with `ldd`) that they're not looking for it in the wrong place. Those work well with the shared library being built at the root, rather than try to use a system-installed library, since this is the code for the library itself.
