### ISSUE TITLE
git_patch_from_buffers takes one buffer as void and the other as char

### ISSUE THREAD

**Issue by joshtriplett** [libgit2/libgit2#3986]
The function `git_patch_from_buffers` takes the first buffer as a `void *` and the second buffer as a `char *`.  It should take both buffers as `void *`.  (Likewise, `git_patch_from_blob_and_buffer` should take the buffer as a `void *`.)

**Comment by ethomson** [comment]
Generally we don't use `void *` for arrays of bytes.  Shouldn't both be `char *`?

**Comment by joshtriplett** [comment]
If it's genuinely a "byte", rather than a "character", shouldn't it be uint8_t or unsigned char?

But in any case, yes, I mostly wanted to request consistency.

**Comment by ethomson** [comment]
You right, thanks @joshtriplett for the report.
