### ISSUE TITLE
Test failure of 'checkout::typechange.F' when building on btrfs

### ISSUE THREAD

**Issue by lfam** [libgit2/libgit2#3991]
Hi,

I'm working on distro packaging for GNU Guix.

I am seeing the same test failure as in https://github.com/libgit2/libgit2/issues/3911 for both 0.24.2 and 0.24.3 when building on the btrfs filesystem with Linux 4.8.6. It works fine on ext4. The test suite output is reproduced below:

```
Loaded 308 suites: 
Started

attr::file....
attr::flags...
attr::ignore............
attr::lookup.....
attr::repo..........
blame::buffer......
blame::getters..
blame::harder....
blame::simple..S......
buf::basic...
buf::oom..
buf::splice.........
checkout::binaryunicode..
checkout::conflict.................
checkout::crlf..............
checkout::head..
checkout::icaseSSSSSSSSSSSSS
checkout::index.............................
checkout::nasty..............................
checkout::tree.........................................
checkout::typechange.F

  1) Failure:
checkout::typechange::checkout_with_conflicts [/tmp/guix-build-libgit2-0.24.3.drv-0/libgit2-0.24.3/tests/checkout/typechange.c:285]
  cts.conflicts != g_typechange_expected_conflicts[i]
  4 != 3
```

We build our packages in an isolated chroot with a minimal filesystem tree. Some more information about the build environment can be found in our manual [0]. Please let me know what other information I can provide.

[0]
https://www.gnu.org/software/guix/manual/html_node/Build-Environment-Setup.html

**Comment by pks-t** [comment]
The commit is not part of any release currently but only on the master branch, so it is probably the same issue as in #3911.

**Comment by carlosmn** [comment]
@lfam can you try with the RC? It should be fixed on the upcoming release.

**Comment by lfam** [comment]
The 0.25.0-rc1 tarball passes its test suite for me on btrfs. Thanks!
