### ISSUE TITLE
git_repository_discover() does not work for files

### ISSUE THREAD

**Issue by max630** [libgit2/libgit2#3994]
After merges d8243465be and ebeb56f0f5, `git_repository_discover()` fails when start_path points to a file in repository with message:

> The `.git` file at '/tmp/libgit2_tests_tgTHjU/discover__file_repo/subdir/file' is malformed

Documentation is not clear if passing file to the function expected or not, but apparently there is already software which uses it - for example, GitDiffMargin -, so it's sort of regression.

**Comment by pks-t** [comment]
This should be fixed by #3998 as soon as it is merged

**Comment by carlosmn** [comment]
Fixed via #3998
