### ISSUE TITLE
Inconsistencies in interface?

### ISSUE THREAD

**Issue by smallB007** [libgit2/libgit2#3997]
Guys, during the process of wrapping your library, I stumbled across the following functions:
```
int git_diff_get_perfdata(git_diff_perfdata *out, const git_diff *diff);
int git_diff_get_stats(git_diff_stats **out, git_diff *diff);
```
Is there any reason why the first one requires just a pointer to the result and the second one requires pointer to pointer to result?

Thank you

**Comment by ethomson** [comment]
Sometimes we require you to provide a data structure that we write into.  Sometimes we will allocate something opaque and return it to you.  These should be clearly documented but are certainly not meant to be consistent, they're meant to be intelligent applications.

For example:  in the former you provide a `git_diff_perfdata` that we write into.  Obviously we wouldn't want to `malloc` this and then require you to `free` it, when that struct is both small and reusable.  In particular, the cost of a `malloc` would skew the perf data that you're trying to measure.

**Comment by smallB007** [comment]
@ethomson Hi, thank you for your reply.
I'm sure you have your reasons for doing it the way you do it. As usual there are 77 and 1 ways of doing things. I personally wouldn't choose that design, but then again, this isn't my library.
Anyway, I was simply curious and now my curiosity is satisfied.
Thank  you for your help.

Best regards
