### ISSUE TITLE
git_commit_dup doesn't exist in 24.3

### ISSUE THREAD

**Issue by smallB007** [libgit2/libgit2#4005]
Hi guys,
In #3913 I was told that git_commit_dup is implemented and will be in next version (that was 24.1). Now I'm checking in 24.3 and I still cannot find it. What's the story ;)

Thank you

**Comment by carlosmn** [comment]
There is no new version yet. `git_commit_dup` is a new API so we cannot add it during the same cycle. v0.25.x will have it, once that's released.

**Comment by smallB007** [comment]
Thank you for your answer.
