### ISSUE TITLE
Segmentation fault in examples/general

### ISSUE THREAD

**Issue by dglsswnsn** [libgit2/libgit2#4046]
### Reproduction steps
I downloaded libgit2 v0.25.0 (Latest release) onto a virtual machine running Lubuntu 16.10.  After building the shared library (build/libgit2.so.0.25.0) using cmake, I invoked "make" in the examples/ directory.  All the executables built without errors or warnings, but when I invoked "general", it ended with a segmentation fault.

### Expected behavior
I expected "general" to run to completion and terminate normally.

### Actual behavior
Here are the last few messages that "general" writes to the terminal.

refs/tags/test [b25fa35b38051e4ae45d4222e795f9df2e43f1d1]
refs/tags/wrapped_tag [849a5e34a26815e821f865b8479f5815a47af0fe]
refs/heads/packed [41bc8c69075bbdb46c5c6f0566cc8cc5b46e8bd9]

*Config Listing*
Autocorrect: 32697
Segmentation fault (core dumped)
douglas@strangelove:~/libgit2-0.25.0/examples$ 

### Version of libgit2 (release number or SHA1)
v0.25.0

### Operating system(s) tested
Lubuntu 16.10

### Additional
Looking at the config_files() function in general.c, I guessed that the invocation of git_config_get_string() was causing the fault.  I found the following comment before this function's prototype in config.h.

 * This function can only be used on snapshot config objects.

so I guessed that the "cfg" parameter on this invocation was incorrect.  A little shopping around revealed the git_repository_config_snapshot() function, and the following snippet fixed the problem.

	git_config *snap_cfg;
	check_error(git_repository_config_snapshot(&snap_cfg, repo), "config snapshot");
	git_config_get_string(&email, snap_cfg, "user.email");

**Comment by ethomson** [comment]
Thanks for troubleshooting this!  It would be great if you would submit a pull request to fix it!  😀

**Comment by dglsswnsn** [comment]
Thanks for reading my issue!  Sure, I'll be glad to fix the problem and submit a pull request.  

I found a couple of other problems with the config_files() function.  I'll create another issue to document them.

**Comment by ethomson** [comment]
Fixed via #4052
