### ISSUE TITLE
examples/general config_files() needs to check return codes from git_config_get_ invocations

### ISSUE THREAD

**Issue by dglsswnsn** [libgit2/libgit2#4047]
### Reproduction steps
I do not have a help.autocorrect configuration parameter.  When I run examples/general multiple times, I see a different value displayed for Autocorrect each time, e.g.

*Config Listing*
Autocorrect: 32697

*Config Listing*
Autocorrect: 32720

### Expected behavior
If a configuration parameter is not set, I would expect config_files() to tell me that the parameter is missing or undefined.

### Actual behavior
The invocation of git_config_get_int32() is failing, but its return code isn't tested before its returned value is used.  Both this invocation and the following invocation of git_config_get_string() should test the return code for three conditions:
- 0 (success)
- GIT_ENOTFOUND (undefined configuration parameter)
- Other (failure)

### Version of libgit2 (release number or SHA1)
v0.25.0

### Operating system(s) tested
Lubuntu 16.10

### Additional
config_files() creates a new git_config object when it calls git_config_open_ondisk().  Before returning config_files() should free this object by calling git_config_free().  I believe that "as is" config_files() is leaking memory.  In this case that's immaterial, but as an example, it should be a good one and not leak memory.

**Comment by ethomson** [comment]
Closed via #4078
