### ISSUE TITLE
Incorrect documentation for git_oid_fromstrn

### ISSUE THREAD

**Issue by main--** [libgit2/libgit2#4058]
The docs say:

>If N is odd, N-1 characters will be parsed instead. The remaining space in the git_oid will be set to zero.

This is clearly undesirable behavior when working with prefixes and - more importantly - *wrong*. The function works just fine with odd character counts and parses the nibble.

**Comment by carlosmn** [comment]
Indeed, it looks like we fixed the behaviour at some point but never updated the documentation to reflect this.
