### ISSUE TITLE
git_filter_list_stream_data() crashes if stream fails to initialize

### ISSUE THREAD

**Issue by swisspol** [libgit2/libgit2#4063]
When `git_filter_list_stream_data()` calls `stream_list_init()` and it fails, `stream_start` will be set to `NULL`.

Before returning, `git_filter_list_stream_data()` always executes `close_error = stream_start->close(stream_start);` which will obviously crash if `stream_start` is `NULL`.

The fix is obvious but what it should be depends on what's the resolution for #4062, which is why I'm not providing a patch at this time.

PS: This was observed on 805b90aac4a0bc4a388a28f0086ba8a7cf7e62dc.

**Comment by ethomson** [comment]
fixed via #4196
