### ISSUE TITLE
git_filter is passed absolute path instead of relative path when smudging

### ISSUE THREAD

**Issue by swisspol** [libgit2/libgit2#4064]
### Reproduction steps
Implement a `git_filter` using the stream API `git_filter_stream_fn`.

### Expected behavior
When the `git_filter_stream_fn` is called, `git_filter_source_path(src)` always returns a relative path to the working directory of the repo when smudging or cleaning (which is how `%f` expands when Git executes a custom filter).

### Actual behavior
`git_filter_source_path(src)` returns an absolute path when `git_filter_source_mode(src)` is `GIT_FILTER_SMUDGE`.

### Version of libgit2 (release number or SHA1)
805b90aac4a0bc4a388a28f0086ba8a7cf7e62dc

### Operating system(s) tested
n/a

**Comment by swisspol** [comment]
The same problem happens when using the `git_filter` `apply` callback since it's just a wrapper of the `stream` callback.

**Comment by ethomson** [comment]
This is by-design and would be a breaking change.
