### ISSUE TITLE
git_submodule_foreach segfaults in a bare repo

### ISSUE THREAD

**Issue by novalis** [libgit2/libgit2#4068]
Test case
[submodule_foreach_bare.patch.txt](https://github.com/libgit2/libgit2/files/686364/submodule_foreach_bare.patch.txt)

You can see in the backtrace that, because the wd check here https://github.com/libgit2/libgit2/blob/89c332e41b12a72d89de40d63bc568c56a2c336a/src/submodule.c#L459 fails, mods is still NULL -- but submodules_from_index and submodules_from_head need it to be non-NULL.

We could just set it to an empty config in a bare repo, which would stop the crash, but it wouldn't actually enable data about those modules to be correctly loaded, since e.g. submodules_from_index seems to depend on the .gitmodules in the working directory (that is, it has no provision to load one from the ODB).

The root cause of this is that the submodule API has a few separate concepts mixed together.  Here's a classification:

Operations on in-memory object, or operations that only affect the submodule's dir in .git/modules:
git_submodule_free
git_submodule_owner
git_submodule_repo_init (when used correctly, that is, with use_gitlink=true)
git_submodule_set_fetch_recurse_submodules
git_submodule_set_ignore
git_submodule_set_update
git_submodule_update_init_options
git_submodule_url

git_submodule_branch
git_submodule_fetch_recurse_submodules
git_submodule_ignore
git_submodule_name
git_submodule_path
git_submodule_update_strategy

The second set of these depend on various configuration, some of which will come from the config and some of which originate from a .gitmodules file, probably the one in the wd -- I haven't looked carefully.

Operations that depend on or affect the working directory:
git_submodule_add_setup
git_submodule_init
git_submodule_open
git_submodule_sync
git_submodule_update
git_submodule_wd_id

Operations that depend on or affect the index:
git_submodule_add_finalize
git_submodule_index_id

Operations that depend on or affect the HEAD:
git_submodule_head_id

Operations that depend on or affect the wd and index:
git_submodule_add_to_index

Operations that depend on or affect the wd, index, and HEAD:
git_submodule_foreach
git_submodule_location
git_submodule_lookup
git_submodule_reload
git_submodule_status

Further, there is no way to access information about a submodule's state as-of a prior commit (at least that I can see in the git_submodule_xxx api).  

Perhaps the right way to handle submodules is to model submodules using a few kinds of object: 
- a "submodule configuration set", representing the contents of a .gitmodules file, possibly one in the index or in a commit, and optionally as modified by local config.
- a "submodule configuration", an entry in such a set for a single submodule.
- a "submodule repository", representing a repo in .gitmodules (or, I guess, in the working tree, for legacy repos).  It's just a normal git_repository, so not really a separate object type.  This repository's HEAD can be read to see if there are new commits in the repo (since HEAD or the index).  
- a "submodule status", for information about a working tree's checkout of a submodule: whether it is initialized, and if so, whether it has untracked content or modified files.  This would be a transient thing created on request.

Under this approach, git_submodule_foreach might need three versions: one for a tree, one for the index, and one for the working directory.   Or, perhaps, it would not exist at all, since as far as I can tell from a Google search, pretty much nobody actually uses it.  We do call the underlying, buggy, all_submodules function in #4016.  But under the above theory, #4016 would not need to exist; instead, users would simply manage submodule config sets (the cache) themselves.

**Comment by ethomson** [comment]
Thanks for opening this issue; I'll have to meditate upon this a little bit (which is painful, because submodules are always painful).  But let me challenge this quickly:

> Or, perhaps, it would not exist at all, since as far as I can tell from a Google search, pretty much nobody actually uses it.

I can confirm for you that `git_submodule_foreach` is used.  It's [provided by LibGit2Sharp](https://github.com/libgit2/libgit2sharp/blob/master/LibGit2Sharp/SubmoduleCollection.cs#L122), and is used by products that use it.

**Comment by Uncommon** [comment]
I use it in my project, through Objective-Git.

**Comment by novalis** [comment]
What do you use it for?

**Comment by Uncommon** [comment]
To get a list of the repository's submodules.

**Comment by novalis** [comment]
Oh, you're building a graphical git tool.  It looks to me like Xit doesn't refresh in the case where someone adds a submodule to the working directory or index.  (This is based on code inspection; I don't have a Mac to test on). I don't really know what users expect here, but do you think the ideas I sketched above would be right for your project?

**Comment by Uncommon** [comment]
Yeah, that sounds reasonable. (and yes, I haven't gotten around to auto-refreshing the submodule list yet..)

**Comment by ethomson** [comment]
I'm a bit confused about the way you've split up the functions.  (Those affecting the workdir, those affecting the index, those affecting index + wd, etc.)

Are you being thorough here, or are you anticipating a need to really know, or work on the index?

Putting `foreach` aside:  do you want such granularity on these functions to operate only on the (say) index?  My rather naive assumption would have been that we would have a set of submodule operations that work bare, and a set of submodule operations that do not (and read/write the index or the working directory or both).  Does that align with your thinking?

If yes, can we extend this such that there's a `foreach` that works barely, and a `foreach` that works nonbare?  (Ignoring for a moment whether this is one API, maybe that detects bareness and works bare, or two, a `foreach` and an explicit `foreach_bare`)...

**Comment by novalis** [comment]
Sorry, the initial division was a description of the current state of the submodule functions -- not a description of how things should be.

On reflection, I think the future version of git_submodule_foreach could take a "submodule configuration set".  That set could be loaded from the index, or HEAD, or an arbitrary revision, or the working tree.  Do we need something version which works on multiple sets and lets you diff them?  Maybe, but most of hte time, changes to submodules could be handled through the normal diff machinery.
