### ISSUE TITLE
failed to set proxy: the parameter is incorrect

### ISSUE THREAD

**Issue by emilg79** [libgit2/libgit2#4069]
### Reproduction steps
Install `Julia` (`0.5.0` and `0.6.0-dev.1852`) on computer behind corporate proxy; run `Pkg.init()` which ultimately calls the Julia functions `LibGit2.clone` and in particular

    ccall((:git_clone, :libgit2), Cint,
          (Ptr{Ptr{Void}}, Cstring, Cstring, Ref{CloneOptions}),
          repo_ptr_ptr, repo_url, repo_path, clone_opts_ref)

### Expected behavior
To succeed in cloning from `github`, https://github.com/JuliaLang/METADATA.jl

### Actual behavior
    ERROR: GitError(Code:ERROR, Class:OS, Failed to set proxy: The parameter is incorrect)

### Version of libgit2 (release number or SHA1)
`0.24.5`

### Operating system(s) tested
Windows

### Notes
Access through proxy is successful for many other applications, such as `conda` and `apm`. Configuring `ENV["http_proxy"]`, `ENV["https_proxy"]` makes no difference. I think the problem is with `LibGit2`, but if this is `Julia`-side, please let me know. I was unable to debug further. 

Could the error message be made more informative? "The parameter" is not clear which parameter it means/where it is being pulled from, and I didn't find it in the docs. "is incorrect" leaves me hanging, I don't know if it means it is inadmissible, not working, or what the current value it is using is.

**Comment by ethomson** [comment]
"The parameter is incorrect" is a message from the Windows HTTP stack.  What are you setting the proxy to?

You mention the environment variables, is that how you're setting the proxy?  Do you get the same error message if you _don't_ set those variables, or does it simply not work?

**Comment by emilg79** [comment]
Hi, thanks for looking at this! Is there any way to extract from `LibGit2` which parameter it passed on to the Windows HTTP stack for this? (If I am correctly understanding your point)

I'm setting the proxy to `http://user:passw@proxy:port`, with the password html-encoded. This works for me with other applications, but I actually haven't been able to do anything that gets a different but related failure from `LibGit2.clone` -- I get the same error whether I set the `ENV` proxy data or not.

**Comment by ethomson** [comment]
If you don't set it with the environment variable, then how are you setting it?  Is it in a global git config?  Is it set in the remote?  If you're not doing it yourself, or you don't know, then I think we should ask the Julia folks how this is getting set.

We should break the `http://user:pass@proxy:port` apart properly; I have tested proxies with authentication, using the WinHTTP stack, but I haven't done it recently.  It looks like we have unit tests for proxy authentication with callbacks, but I don't see one explicitly that takes a `http://user:pass@host` format.

The easiest way to look at this is to set a breakpoint [at the point we set the proxy to WinHTTP](https://github.com/libgit2/libgit2/blob/master/src/transports/winhttp.c#L443).  If this is not feasible then this is something that I can look into, but it's not something that I can do immediately.

**Comment by carlosmn** [comment]
For the current release, the normal test suite tests using authentication for every build. For Windows it's done via the `appveyor.yml` file but we did not have these tests until we had proxy settings overall, any support from WinHTTP was done by the transport itself and it doesn't look like it was tested.

**Comment by emilg79** [comment]
I've done two things trying to set it. Firstly, run `SET https_proxy=...` in `cmd` before executing Julia `Pkg.init()`. Secondly, setting the `ENV` variable directly in Julia. But I don't know if anything percolates through to the `LibGit2` settings. I don't know how to set breakpoints and look at that kind of thing.

I just saw @tkelman merge https://github.com/JuliaLang/julia/pull/19855, looks related but I can't tell if it has implications here

**Comment by tkelman** [comment]
That was just upgrading the version we build against by default. Some API's changed and added proxy options, but we don't do anything special about setting them or threading them through anywhere yet.

**Comment by dirkhh** [comment]
did this ever get resolved? I also have a user that runs into problems with a proxy that requires authentication and he, too, provides it as `http://user:pass@proxy.host:port` on Windows.
Is there a preferred way to do this (I see the mention of callbacks above)?

**Comment by robmaz** [comment]
Doesn't look like it. I have the same problem here with Julia 0.6.1 for MacOS (binary distribution). Is it in fact intended behavior that libgit2 does not work where command line git does, or does pkg.jl somehow filter out the http_proxy environment? It would be interesting to know if this is a libgit2 or a Julia problem.

**Comment by robmaz** [comment]
Except that I have an anonymous proxy, i.e., no login, so just http_proxy=http://proxy.host:port

**Comment by ethomson** [comment]
@robmaz As pointed out, every CI test run we've perform goes tests our proxy code.  I have no idea what Julia does with the environment.  Unless you can provide a repro case with libgit2, I would encourage you to open an issue with Julia, that way the team who can debug with us will be able to.  (At this point, it's not clear to me that they're even aware of this issue.)

**Comment by dirkhh** [comment]
@ethomson So my test case is NOT Julia, it's Subsurface (http://subsurface-divelog.org) and for us quite specifically http proxy with user and password, given in the form `http://user:pass@proxy.host:port` fails ONLY on Windows. This works on Linux and Mac. This is with libgit2 0.26 on all three platforms.

**Comment by ethomson** [comment]
Interesting, thanks @dirkhh, that's helpful data.  I've got a couple of other things that I'm neck-deep in, but I'll try to take a look at this soon.

**Comment by dirkhh** [comment]
two months later, just a quick "ping" to see if you had a chance to look at this, @ethomson 
(I hate to be a nag, but I know from personal experience how hard it is to stay on top of dozens of issues that people post)

**Comment by dirkhh** [comment]
three months later... any chance this will get looked at?

**Comment by ethomson** [comment]
(Putting aside for a moment the question of whether `AUTO` should be the default or not.)

**Comment by dirkhh** [comment]
Sweet. Let me add that and get it tested (this will take a few days as I need to get a build to the right person and he needs to be at work to test it).
I really appreciate that you looked into this and that you even took the time to look at our sources to identify what we were missing (I need to go back and read the docs to figure out why I missed that option...)
Thank you

**Comment by dirkhh** [comment]
(putting aside for a moment the question why this works fine on Linux without that option)

**Comment by ethomson** [comment]
Not at all; sorry it took me so long to get to it.  (I was hoping to test my suggested change but Ubuntu doesn’t have a recent enough version for one of your dependencies and I didn’t have time enough to resolve that.)

Possible that Linux and Windows have different defaults here, which is problematic, but would actually make me feel better because the `NONE` default feels wrong.  It’s also possible that we default to libcurl on Linux which will honor the env variable always.  I’ll have to dig deeper.

**Comment by dirkhh** [comment]
My guess is that it's libcurl on Linux which does the trick... because I remember adding this to our builds at some point - maybe before libgit2 even had native proxy support...

**Comment by iaavo** [comment]
I'm facing the same issue. In my case, the corporate proxy is set in the form `http://:@proxy.company.com:8080`. This works with git cli but fails in libgit2 with the error message `the parameter is incorrect`.

If I set `http.proxy=http://proxy.company.com:8080` (without the `:@` in the url) in the git config, its the other way around. git cli stops working and fails with `fatal: unable to access '<repositoryurl>': CONNECT tunnel failed, response 407` while libgit2 starts to work.

**Comment by ethomson** [comment]
Fixed!
