### ISSUE TITLE
Memory leaks in examples/general.c

### ISSUE THREAD

**Issue by dglsswnsn** [libgit2/libgit2#4070]
### Reproduction steps
I originally discovered these memory leaks by reading the code.  To confirm my suspicions I ran valgrind, which discovered a couple more.  I attach the valgrind output, which clearly shows the causes of the leaks.

[valgrind1.txt](https://github.com/libgit2/libgit2/files/687976/valgrind1.txt)

### Expected behavior
Memory leaks are bad, even in example programs (or maybe especially in example programs).  There should be no memory leaks in any of the example programs.

### Actual behavior
There are ten memory leaks in examples/general.  

### Version of libgit2 (release number or SHA1)
v0.25.0

### Operating system(s) tested
Lubuntu 16.10

### Additional Information
Valgrind also detected the use of an uninitialized variable ("j") in config_files().  I have submitted a Pull Request to fix this problem.

**Comment by pks-t** [comment]
Thanks for the report. I fully agree that our examples should actually show proper usage only, which also includes avoiding memory leaks. I started re-doing this whole example a few months ago, but have been quite busy due to day work so I wasn't able to finish it up just yet.

**Comment by dglsswnsn** [comment]
Hi Patrick,

Thanks for responding to this issue.  I was unaware that anyone was reworking the examples.  I think it's a worthwhile effort.  I won't open any more issues on the examples.

In addition to this issue (#4070) I have one other open issue (#4047) on examples/general.c, I proposed a fix for issue #4047 (pull request #4059), but both may be irrelevant in light of your effort.  Should I close issue #4047 and pull request #4059?

Doug

**Comment by carlosmn** [comment]
This example is precisely _not_ for showing how you manage resources when using a C library but to show how you'd call a few functions, without any of the boilerplate.

This was created before the actual examples with functionality that make up a command similar to git; and those certainly should have error handling. But this is not a file to have any of that. I have argued before for its removal, as it doesn't show anything cohesive and you should be able to get the same information from the other examples.

**Comment by pks-t** [comment]
It certainly is not about _showing_ resource management, yes. As I've seen this example it is about showing the usual way of working with libgit2 so that the user can get a feeling how libgit2 does work in general. And because of this I'd argue that memory management should be part of it, as well.

**Comment by ethomson** [comment]
I agree that this file is a bummer, but if it's going to exist then it should suck less.  Its removal seems like a somewhat orthogonal concern.
