### ISSUE TITLE
A few code sample pages are empty

### ISSUE THREAD

**Issue by rcjsuen** [libgit2/libgit2#4071]
All of the following pages below are empty.

https://libgit2.github.com/libgit2/ex/HEAD/add.html
https://libgit2.github.com/libgit2/ex/HEAD/common.html
https://libgit2.github.com/libgit2/ex/HEAD/for-each-ref.html
https://libgit2.github.com/libgit2/ex/HEAD/network/common.html
https://libgit2.github.com/libgit2/ex/HEAD/rev-list.html
https://libgit2.github.com/libgit2/ex/HEAD/showindex.html

**Comment by ethomson** [comment]
These URLs have changed (to libgit2.org) but we've updated our docs generation scripts. So I think that these all exist now.
