### ISSUE TITLE
Coverity failures

### ISSUE THREAD

**Issue by nkeck720** [libgit2/libgit2#4080]
I recently got an email in my inbox from Coverity about a scan failure in libgit2. I'm not sure when or why I got this email, but I thought I would pass the information along to the proper people.

> Please find the latest report on new defect(s) introduced to libgit2 found with Coverity Scan.
> 
> 1 new defect(s) introduced to libgit2 found with Coverity Scan.
> 
> 
> New defect(s) Reported-by: Coverity Scan
> Showing 1 of 1 defect(s)
> 
> 
> ** CID 1368414:  Resource leaks  (RESOURCE_LEAK)
> /home/travis/build/libgit2/libgit2/tests/merge/trees/commits.c: 147 in test_merge_trees_commits__fail_on_conflict()
> 
> 
> ________________________________________________________________________________________________________
> *** CID 1368414:  Resource leaks  (RESOURCE_LEAK)
> /home/travis/build/libgit2/libgit2/tests/merge/trees/commits.c: 147 in test_merge_trees_commits__fail_on_conflict()
> 141                     merge_trees_from_branches(&index, repo, "df_side1", "df_side2", &opts));
> 142
> 143             cl_git_fail_with(GIT_EMERGECONFLICT,
> 144                     merge_commits_from_branches(&index, repo, "master", "unrelated", &opts));
> 145             cl_git_fail_with(GIT_EMERGECONFLICT,
> 146                     merge_commits_from_branches(&index, repo, "master", "branch", &opts));
> >>>     CID 1368414:  Resource leaks  (RESOURCE_LEAK)
> >>>     Variable "index" going out of scope leaks the storage it points to.
> 
> 
> ________________________________________________________________________________________________________
> To view the defects in Coverity Scan visit, https://u2389337.ct.sendgrid.net/wf/click?upn=08onrYu34A-2BWcWUl-2F-2BfV0V05UPxvVjWch-2Bd2MGckcRYUHdlOrF8DtX6xit0A1FZ3zwmhgROxOd0tlTkVutaqMw-3D-3D_Er8Pc9jR3Cu5n-2B03Jp8PbJLd6jRBCd4-2F3DhU5jMyGzplRpoOr0Zb982dcybkh-2BduJqM48Z-2BHMiJfbVGMgaQwdu9cq0nn5s48DuEPZ7gHz81u-2BHLSl2fBP95lxX-2FZ1V-2BLeKK4v7q3mSEE1iK-2BWebrHPKngZtIBYzlyidrtCtxxhtG7jr5pGoBQx0lmethpgan9aFajOQC2WIlQUXa9jfNHVMjnksa6cJtJ0IjT1f-2FIp8-3D
>

**Comment by carlosmn** [comment]
A bunch of people get them because they signed up on the page, including the core team.
