### ISSUE TITLE
git_index_remove() produces unexpected results

### ISSUE THREAD

**Issue by JabberSnatch** [libgit2/libgit2#4083]
So I got this strange situation when resolving a conflict where a call to git_index_conflict_remove() will fail to remove all entries and change the given path value.
I can observe a similar behaviour when calling git_index_remove(index, path, 2), after the call, path will hold an invalid value.

Do you have any idea about what I might be doing wrong? Or is it some sort of know behaviour?

Here is a sample from my code.
remote_commit is the fetch_head of satellite.repo.

```c++
git_merge_commits(&merge_index, satellite.repo,
				  satellite_commit, remote_commit,
				  &merge_options);

if (git_index_has_conflicts(merge_index))
{
	git_index_conflict_iterator*	conflict_ite;
	git_index_conflict_iterator_new(&conflict_ite, merge_index);

        std::vector<git_index_entry> unconflicted_entries;

	const git_index_entry *ancestor, *ours, *theirs;
	while (git_index_conflict_next(&ancestor, &ours, &theirs, conflict_ite) != GIT_ITEROVER)
	{
		git_index_entry resolution = *ours;

		GIT_IDXENTRY_STAGE_SET(&resolution, GIT_INDEX_STAGE_NORMAL);
		
		if (!(resolution.flags & GIT_IDXENTRY_VALID))
			resolution.flags |= GIT_IDXENTRY_VALID;

		unconflicted_entries.push_back(resolution);
	}

	for (auto ite = unconflicted_entries.begin();
		 ite != unconflicted_entries.end(); ite++)
	{
		git_index_add(merge_index, &(*ite));

//NOTE: Using the following will set ite->path to an invalid value and leave one conflicted entry in the index.
		git_index_conflict_remove(merge_index, ite->path);

//NOTE: Using the following will fail on the third call, as the second sets ite->path to an invalid value. It does however succeed to remove the entry.
		git_index_remove(merge_index, ite->path, 1);
		git_index_remove(merge_index, ite->path, 2);
		git_index_remove(merge_index, ite->path, 3);
	}

//NOTE: using this instead of the two alternative above works fine, but it doesn't feel like the proper way to handle conflicts resolution.
	git_index_conflict_cleanup(merge_index);

	git_index_conflict_iterator_free(conflict_ite);

	git_oid merge_tree_id;
	git_tree* merge_tree;

	git_index_write_tree_to(&merge_tree_id, merge_index, satellite.repo);
	git_checkout_index(satellite.repo, merge_index, &checkout_options);
	git_tree_lookup(&merge_tree, satellite.repo, &merge_tree_id);

	git_signature* signature;
	git_signature_now(&signature, c_commit_author, c_commit_email);

	git_oid commit_id;
	const git_commit* parents[] = { satellite_commit, remote_commit };

	git_commit_create(&commit_id, satellite.repo, "HEAD",
						  signature, signature,
						  "UTF-8", "",
						  merge_tree, 2, parents));

	git_repository_state_cleanup(satellite.repo);
	satellite_push(satellite);
}

```

**Comment by ethomson** [comment]
Right, I would expect bad things to happen here.  You're changing the `git_index_entry`s data.  The caveats for index manipulation are:

> The entry is not modifiable and should not be freed.

Though this is not explicitly stated for `git_index_conflict_next` (which is an oversight that I will correct).

If you want to pass a `git_index_entry` to a function like `git_index_add`, please make sure that it's your own - `memcpy` the `git_index` data into something that you own, modify that, and then pass a pointer to `git_index_add`.

**Comment by JabberSnatch** [comment]
Do you mean that I should memcpy the `git_index_entry` instead of `git_index`?
I believe `git_index_entry resolution = *ours` actually does the copy. Could you show me a line where I change a `git_index_entry` data?

**Comment by ethomson** [comment]
Yes - sorry that I was unclear.  `memcpy` the data (the `git_index_entry`) _and the path_ that the `git_index_entry` points to.

> I believe git_index_entry resolution = *ours actually does the copy.

Huh.  C++.  Is it truly doing a deep copy?  What's it doing with `path`?  Is it still pointing at the same string that's owned by the index?  If so, that's going to disappear when you remove it.

It certainly looks like you're iterating and referencing data that's getting modified underneath you.

**Comment by JabberSnatch** [comment]
You're right, I completely forgot about this pointer!
