### ISSUE TITLE
Need a way to disable loose backend

### ISSUE THREAD

**Issue by ssinyagin** [libgit2/libgit2#4090]
In my project, the data is written into thousands of small blobs into a mempack, and then a packfile is created after a commit. Currently there's a quite significant amount of filesystem requests trying to find a file for each object, because libgit2 verifies that an object doesn't exist before creating. 

As I'm explicitly not using the loose backend, it will be great to be able to disable it completely, and save on filesystem requests.

**Comment by ethomson** [comment]
You have complete control over the object database and backends.

Create a new object database (with [`git_odb_new`](https://github.com/libgit2/libgit2/blob/master/include/git2/odb.h#L39)).  Create a new pack odb backend (with [`git_odb_backend_pack`](https://github.com/libgit2/libgit2/blob/master/include/git2/odb_backend.h#L34)) and add that backend to your new object database (with [`git_odb_add_backend`](https://github.com/libgit2/libgit2/blob/master/include/git2/odb.h#L498)).  Finally, set that object database on your repository (with [`git_repository_set_odb`](https://github.com/libgit2/libgit2/blob/master/include/git2/sys/repository.h#L93)).

**Comment by ssinyagin** [comment]
thanks
