### ISSUE TITLE
revwalk produces incorrect results with GIT_SORT_TIME

### ISSUE THREAD

**Issue by adamniedzielski** [libgit2/libgit2#4099]
I reported this issue in `rugged` repo - https://github.com/libgit2/rugged/issues/673. It includes an example in Ruby which may be helpful. I believe that this issue is caused by `libgit2` and that it is a regression.

### Reproduction steps

Given a repository:

```
* commit C (HEAD)
|
* commit B
|
* commit A
```

walk from A, hiding C, using `GIT_SORT_TIME` order. See #4100 for a failing test case.

### Expected behavior

0 commits returned

### Actual behavior

1 commit returned (commit A).

### Version of libgit2 (release number or SHA1)

dad3c319d76f58bc600b53650723d0d3cc9e6feb

### Operating system(s) tested

macOS 10.12.2

**Comment by adamniedzielski** [comment]
I submitted #4100 with a failing test case - it should make my scenario super clear.

I used my test case to go a small bisect and found our that the change of behavior was introduced by ea1ceb7f554da276ffb0fe18c6ca4a0233845d55 /cc @carlosmn 

It's worth noting that:
1. it returns 1 commit only when we call `git_revwalk_sorting(_walk, GIT_SORT_TIME)`
2. it returns 0 commits when we swap these two lines:

```
cl_git_pass(git_revwalk_push(_walk, &to_oid));
cl_git_pass(git_revwalk_hide(_walk, &from_oid));
```

**Comment by adamniedzielski** [comment]
In ea1ceb7 these two lines were removed:

```
if (list->item->uninteresting)
  continue;
```

I think that they are still necessary. If I apply the following patch:

```
diff --git a/src/revwalk.c b/src/revwalk.c
index 8c370bc..3094189 100644
--- a/src/revwalk.c
+++ b/src/revwalk.c
@@ -572,8 +572,11 @@ static int prepare_walk(git_revwalk *walk)
 
                walk->get_next = &revwalk_next_toposort;
        } else if (walk->sorting & GIT_SORT_TIME) {
-               for (list = commits; list && !error; list = list->next)
+               for (list = commits; list && !error; list = list->next) {
+                       if (list->item->uninteresting)
+                               continue;
                        error = walk->enqueue(walk, list->item);
+               }
 
                git_commit_list_free(&commits);
```

my test passes. However, I believe that this patch is not enough and `GIT_SORT_TOPOLOGICAL` part also requires this check.

**Comment by adamniedzielski** [comment]
I looked into the code again. The bug may come from the asymmetry between `revwalk_next_unsorted`, `revwalk_next_toposort` and `revwalk_next_timesort`.

The better solution that the one I posted above may be:

```
diff --git a/src/revwalk.c b/src/revwalk.c
index 8c370bc..0c5d4a1 100644
--- a/src/revwalk.c
+++ b/src/revwalk.c
@@ -233,9 +233,11 @@ static int revwalk_next_timesort(git_commit_list_node **object_out, git_revwalk
 {
        git_commit_list_node *next;
 
-       if ((next = git_pqueue_pop(&walk->iterator_time)) != NULL) {
-               *object_out = next;
-               return 0;
+       while ((next = git_pqueue_pop(&walk->iterator_time)) != NULL) {
+               if (!next->uninteresting) {
+                       *object_out = next;
+                       return 0;
+               }
        }
 
        giterr_clear();
```

**Comment by ethomson** [comment]
Thanks for reporting this.  @carlosmn do you have any insights here?

**Comment by carlosmn** [comment]
Yes, it looks like we might still get uninteresting commits in the queue for the time iterator, so we do need the `if` to skip them.
