### ISSUE TITLE
Stash save does not behave the same as command line

### ISSUE THREAD

**Issue by implausible** [libgit2/libgit2#4101]
### Reproduction steps
1. Create a stash using git_stash_save with default options.
2. use `git show stash@{0}` in command line
3. There are no diffs for the stash

### Expected behavior
The expected behavior is that the stashed diffs are visible in command line.

### Actual behavior
The diffs are not visible via command line.

### Version of libgit2 (release number or SHA1)
37dba1a739b5ee6c45dc9f3c0bd1f7f7a18f13f7
### Operating system(s) tested
Linux, Mac OSX

**Comment by mtangoo** [comment]
What do you mean by diff not visible?
Here is what I get:

```
~ git stash show stash@{0}
 Develop.php | 10 +++++++++-
 1 file changed, 9 insertions(+), 1 deletion(-)
```
