### ISSUE TITLE
Segmentation fault with revwalk and GIT_SORT_TOPOLOGICAL

### ISSUE THREAD

**Issue by adamniedzielski** [libgit2/libgit2#4102]
This was originally reported in `rugged` repo by @cfillion. See https://github.com/libgit2/rugged/issues/663.

### Reproduction steps

1. Set sorting to `GIT_SORT_TOPOLOGICAL`
2. Push SHA
3. Hide SHA
4. Start walking

See PR with a failing test case - https://github.com/libgit2/libgit2/pull/4103

### Actual behavior

Segmentation fault.

### Version of libgit2 (release number or SHA1)

dad3c319d76f58bc600b53650723d0d3cc9e6feb

### Operating system(s) tested

macOS 10.12.2

**Comment by vmg** [comment]
Fixed in https://github.com/libgit2/libgit2/issues/4105. Your failing test has also been merged as part of that PR. Thanks for reporting! :)
