### ISSUE TITLE
Cloning a repo on Windows breaks symlinks

### ISSUE THREAD

**Issue by bquistorff** [libgit2/libgit2#4107]
I can't clone faithfully repos with symlinks on Windows. I have been able to do this using Git for Windows ([info](https://github.com/git-for-windows/git/wiki/Symbolic-Links)) when in Administrator mode and setting `core.symlinks=true`.

### Reproduction steps
I am using `libgit2` through R with the `git2r` package.
Start R in administrator mode
```
> git2r::config()
programdata:
        color.branch=auto
        color.diff=auto
        color.interactive=true
        color.status=auto
        core.autocrlf=true
        core.fscache=true
        core.symlinks=true
        diff.astextplain.textconv=astextplain
        help.format=html
        http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
        rebase.autosquash=true
global:
        core.symlinks=true
        filter.lfs.clean=git-lfs clean -- %f
        filter.lfs.process=git-lfs filter-process
        filter.lfs.required=true
        filter.lfs.smudge=git-lfs smudge -- %f
> git2r::clone("git://github.com/imbs-hl/ranger.git", "C:/Users/USER/Documents/GitHub/ranger2", progress = FALSE)
Local:    master C:/Users/USER/Documents/GitHub/ranger2/
Remote:   master @ origin (git://github.com/imbs-hl/ranger.git)
Head:     [47eb75a] 2017-01-20: Merge pull request #157 from imbs-hl/fix_extratrees
```

### Expected behavior
Expect many symlink files in `ranger-r-package/ranger/src` folder.

### Actual behavior
Many text files in `ranger-r-package/ranger/src` folder where file contents are the original symlink target paths.

### Version of libgit2 (release number or SHA1)
git2r version 0.18.0.9000 (latest release) which say that it has libgit2 commit 6b0510e from 20 December 2016

### Operating system(s) tested
Windows 10 Enterprise

**Comment by ethomson** [comment]
I truly dislike the `core.symlinks` option, but I suppose it's something that we should indeed support.  (To be honest, though, this isn't really on my radar at the moment.)

**Comment by csware** [comment]
I just want to add that symlinks on Windows require administrative privileges.

**Comment by jabbera** [comment]
@csware  the admin requirement is no longer needed for windows 10 creators.

**Comment by cyberbit** [comment]
@jabbera But only if the user has Developer Mode enabled.

**Comment by rogersachan** [comment]
Shouldn't the latest Git for Windows on Windows 10 April Update fix this?

**Comment by ethomson** [comment]
Support was added in #4713
