### ISSUE TITLE
Can't open repository that is created via "git wortree add"

### ISSUE THREAD

**Issue by shibukawa** [libgit2/libgit2#4116]
You are opening a _bug report_ against the libgit2 project.  If you have a
question about an API or usage, please ask on StackOverflow:
http://stackoverflow.com/questions/tagged/libgit2.  Please fill out the
reproduction steps (below) and delete this introductory paragraph.  Thanks!

### Reproduction steps

Open repository via ```git_repository_open()```

### Expected behavior

Works as same as regular git repository or submodule repository.

### Actual behavior

It returns error message ```"Could not find repository from 'path'"```

Worktree folders have .git regular file like submodule. It contains path to root folder under ```.git/worktrees```. But folder structure under ```.git/worktrees``` and ```.git/modules``` are completely different. Worktree doesn't have ```objects``` folder and ```refs``` folder. It contains five files:

* HEAD
* ORIG_HEAD
* commondir
* gitdir
* index

It has a link to the original repository in ```commondir``` file. But the following code assumes this folder is an invalid one, worktree folder is not available via libgit2.

https://github.com/libgit2/libgit2/blob/master/src/repository.c#L160-L174

### Version of libgit2 (release number or SHA1)

0.22 (for libqgit2), but the latest one has a same logic.

### Operating system(s) tested

macOS

**Comment by ethomson** [comment]
Worktree support is coming soon in #3436

**Comment by pks-t** [comment]
Working tree support is not yet ready currently. A pull request is currently in progress and will probably be merged for the next release (see #3436).

**Comment by pks-t** [comment]
Damn, 7 seconds too slow :P

**Comment by ethomson** [comment]
We've merged working tree support!  🎉
