### ISSUE TITLE
On OSX git_diff_print() fails on *.php files if LANG environment variable is set.

### ISSUE THREAD

**Issue by dmitrybezer** [libgit2/libgit2#4128]
### Reproduction steps
1) Have a git_diff object that includes some files with *.php extension.
2) Make sure LANG env var is set to "en_US.UTF-8" for example. 
3) Use git_diff_print() to print the diff

### Expected behavior
No errors

### Actual behavior
An error with message "illegal byte sequence" and klass 8 is returned.

### Version of libgit2 (release number or SHA1)
0.24.6

### Operating system(s) tested
OSX 10.12.2

I've investigated this a bit and found that when LANG variable is set, it sets the locale for libc and makes regcomp() call in git_diff_driver_builtin() to fail to compile the regular expression from builtin_defs (userdiff.h), specifically the "|[^[:space:]]|[\xc0-\xff][\x80-\xbf]+" part of it. 
Here is the source code for regcomp() from the Apple libc:
https://opensource.apple.com/source/Libc/Libc-1158.30.7/regex/TRE/lib/regcomp.c.auto.html
There is "if (TRE_MB_CUR_MAX_L(loc) == 1)" condition in tre_regncomp_l () that checks max size of a character in the current locale.  That is where it fails if the current locale has chars wider than 8bits.

**Comment by ethomson** [comment]
I think that this is resolved now that we ship our own regex code
