### ISSUE TITLE
libgit2 refuses to compile on an old OS (SLES9)

### ISSUE THREAD

**Issue by ifmalcuaz** [libgit2/libgit2#4132]
I am required to work with a very old OS as part of a spacecraft control system, SLES9 (released 10+ years ago). There were several warnings when the project was being built with CMake, and then when I tried to compile a simple program I am getting compilation errors related to the build warnings.

### Version of libgit2 (release number or SHA1)
libgit2 v0.25.1 (latest)

### Operating system(s) tested
SLES9. My CMake version: 2.8.12.2. 

### Reproduction steps
On a build directory as per installation instructions:
```
cmake .. -DBUILD_CLAR=OFF -DCMAKE_INSTALL_PREFIX=/install/prefix # Very old python version is incompatible with Clar
cmake --build . --target install
```

Then make a simple hello world .cpp program which includes libgit2 like so: `#include <git2.h>`. Now try to compile:

`g++ -Wall -I/install/prefix/include -L/install/prefix/lib -lgit2 hello_world.cpp -o hello_world`

### Expected behavior

The project compiles successfully.

### Actual behavior

The build was successful but it outputted several warnings in a loop:

```
/lhome1/libgit2-0.25.1/src/thread-utils.h: In function `git_atomic_inc':
/lhome1/libgit2-0.25.1/src/thread-utils.h:65: warning: implicit declaration of function `__sync_add_and_fetch'
/lhome1/libgit2-0.25.1/src/thread-utils.h: In function `git_atomic_dec':
/lhome1/libgit2-0.25.1/src/thread-utils.h:87: warning: implicit declaration of function `__sync_sub_and_fetch'
/lhome1/libgit2-0.25.1/src/thread-utils.h: In function `git___compare_and_swap':
/lhome1/libgit2-0.25.1/src/thread-utils.h:100: warning: implicit declaration of function `__sync_val_compare_and_swap'
/lhome1/libgit2-0.25.1/src/thread-utils.h:100: warning: assignment makes pointer from integer without a cast
/lhome1/libgit2-0.25.1/src/thread-utils.h: In function `git___swap':
/lhome1/libgit2-0.25.1/src/thread-utils.h:113: warning: return makes pointer from integer without a cast
[ 98%] Building C object CMakeFiles/git2.dir/src/unix/map.c.o
In file included from /lhome1/libgit2-0.25.1/src/common.h:77,
                 from /lhome1/libgit2-0.25.1/src/map.h:10,
                 from /lhome1/libgit2-0.25.1/src/unix/map.c:11:
/lhome1/libgit2-0.25.1/src/thread-utils.h: In function `git_atomic_set':
/lhome1/libgit2-0.25.1/src/thread-utils.h:54: warning: implicit declaration of function `__sync_lock_test_and_set' 
```
It also warns that 'libcurl' was not found (not available with SLES9) and that the bundled 'HTTP_Parser' will be used as the built-in HTTP_Parser is too old.

The compilation outputs the following error messages:

```
ito alcuaz@de-lin19:/lhome1/test$ g++ -Wall -I/install/prefix/include -L/install/prefix/lib -lgit2 test.C -o test
/install/prefix/lib/libgit2.so: undefined reference to `__sync_lock_test_and_set'
/install/prefix/lib/libgit2.so: undefined reference to `__sync_val_compare_and_swap'
/install/prefix/lib/libgit2.so: undefined reference to `__sync_synchronize'
/install/prefix/lib/libgit2.so: undefined reference to `__sync_sub_and_fetch'
/install/prefix/lib/libgit2.so: undefined reference to `__sync_add_and_fetch'
collect2: ld returned 1 exit status
```

The above functions in `thread-utils.h` seem to be implicitly declared and is undefined when compiled. Any help would be greatly appreciated.

**Comment by mplough** [comment]
Phew, an OS that's three years out of long-term support -- sounds "fun"!

What's the output of `gcc --version` for you, and which processor are you targeting?  The functions are [atomic builtins](https://gcc.gnu.org/onlinedocs/gcc-4.4.5/gcc/Atomic-Builtins.html) in gcc.  I'd assume you're on gcc 3.3.x based on the SLES9 release date.  Unfortunately, the atomic builtins used in `thread-utils.h` were added in gcc 4.1.

Easiest thing to do (if your project can live with it) may be to disable threading by turning `THREADSAFE` off in your cmake settings.

**Comment by ifmalcuaz** [comment]
That was indeed the problem, the output of `gcc --version` is `3.3.3` hence the undefined references. If I build with `-DTHREADSAFE=OFF` the warnings disappear. Will try to get by without it, thanks very much for your help!

**Comment by ethomson** [comment]
Thanks @ifmalcuaz for the report and @mplough for the details.

@ifmalcuaz - I'm introducing #4135 to improve the error message here.
