### ISSUE TITLE
git_remote_fetch problem : "there is no TLS stream available"

### ISSUE THREAD

**Issue by jablkojem** [libgit2/libgit2#4147]
git_remote_fetch returns error with message : "there is no TLS stream available"

if(error = git_remote_fetch(remote, NULL,NULL,"fetch")!=0) {
            const git_error *lastError = giterr_last();
            cerr << "problem with fetch, error message : '" << lastError->message <<"'"<< endl;
        }

I am trying to fetch from my remote repository (https://bitbucket.org/.....)
Some ideas how to fix that?

**Comment by Spotlight0xff** [comment]
Hi!

As per this [line](https://github.com/libgit2/libgit2/blob/8051b47f5bb25a2a80e19ff711cb67dd5421d6c9/src/tls_stream.c#L38), it seems like there is no TLS library linked.
Which version of libgit2 did you use? A prepackaged one, or did you compile it yourself?
You might also want to check if the dependency is met (e.g. using `ldd` on the library).

There was an resolved issue [here](https://github.com/libgit2/libgit2/issues/3786).

**Comment by jablkojem** [comment]
Hi,
I was working in Clion and when I downloaded some things in cygwin, this
problem got lost.
Thank you for your time.
Yours sincerely,
Martin Maják

2017-03-15 15:35 GMT+01:00 Spotlight0xff <notifications@github.com>:
