### ISSUE TITLE
Unable to detect changes during pre-commit hook with direct commit

### ISSUE THREAD

**Issue by LinuxBozo** [libgit2/libgit2#4152]
### Reproduction steps
* Compile the `status` and `diff` applications provided with libgit2/examples
* create a `pre-commit` hook that looks like:
```bash
#!/usr/bin/env bash
PATH=$PATH:/usr/local/bin:/usr/local/sbin
set -x
git status
/path/to/libgit2/examples/status
git diff --cached --name-only HEAD^{tree}
/path/to/libgit2/examples/diff --cached --name-only HEAD^{tree}
```
### Expected behavior

If you make a change to any file, and stage that file before commit, you get the following:
```sh
$ git add README.md
$ git commit
+ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	modified:   README.md

+ /Users/linuxbozo/bin/status
# On branch master
# Changes to be committed:
#   (use "git reset HEAD <file>..." to unstage)
#
#	modified:   README.md
#
+ git diff --cached --name-only 'HEAD^{tree}'
README.md
+ /Users/linuxbozo/bin/diff --cached --name-only 'HEAD^{tree}'
README.md
```
By staging the file, both git and libgit2 examples find the changed README.md file when doing both a diff to the index, and checking staged with status. I would expect to see this same behavior when doing a direct commit of the file without explicitly staging first.

### Actual behavior

When doing a direct commit, without staging, git itself behaves properly, showing the change to the README.md in both status and diff, libgit2 however does not.

```
$ git commit README.md
+ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	modified:   README.md

+ /Users/linuxbozo/bin/status
# On branch master
# Changes not staged for commit:
#   (use "git add <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working directory)
#
#	modified:   README.md
#
no changes added to commit (use "git add" and/or "git commit -a")
+ git diff --cached --name-only 'HEAD^{tree}'
README.md
+ /Users/linuxbozo/bin/diff --cached --name-only 'HEAD^{tree}'
```

### Version of libgit2 (release number or SHA1)
libgit2-0.25.1

### Operating system(s) tested
* OSX 10.12 Sierra

**Comment by ethomson** [comment]
This looks to me like it's a problem in the example, but not actually a problem in libgit2 itself...  Does that match what you're seeing?

I'll try to take a look soon-ish, but I would strongly recommend against you using the examples in production.  They're code samples and haven't received the level of scrutiny that the rest of the library has.

**Comment by LinuxBozo** [comment]
@ethomson  Ok, lets use the docs then. I would expect this to work as documented: https://libgit2.github.com/docs/guides/101-samples/#diff_head_to_index, or even https://libgit2.github.com/docs/guides/101-samples/#status_iterating_manual and yet, they do not when placed in this same scenario of `pre-commit` hook without explicit staging.

Unless you are saying that the docs can't be trusted either? If not, what's the point of having them?

Btw, I originally discovered this using [git2go](https://github.com/libgit2/git2go) in a project that explicitly is run during `pre-commit`, trying both a diff of head to index, and using status list implementations, and found the same behavior in both. If I stage explicitly first, everything is as expected. If I commit without explicitly staging, git itself gets it correct, libgit2/git2go does not.

**Comment by ethomson** [comment]
> Unless you are saying that the docs can't be trusted either? If not, what's the point of having them?

No, I did not say that.

If you're not actually staging files, and you're not putting them in the index, then diffing the head to the index wouldn't produce any results.

You need to replicate the behavior of git during the pre-commit hook.  It does some magic to use a different index.

I imagine it sets `GIT_INDEX_FILE` to accomplish this.  You would either need to explicitly honor that variable and open the temporary index it sets aside or open the repository with `	GIT_REPOSITORY_OPEN_FROM_ENV`.

**Comment by LinuxBozo** [comment]
@ethomson And there's my disconnect. git2go doesn't currently support `GIT_REPOSITORY_OPEN_FROM_ENV` and after tracing through that code, and even updating both C examples for `status` and `diff`, using that flag during repository open enables the behavior I would expect. I wrongly assumed that this would be the default way to open a repository.

Thanks for the pointer, and since this behaves as designed, closing.

**Comment by ethomson** [comment]
> I wrongly assumed that this would be the default way to open a repository.

It's not, mostly for backcompat, since it's rather new functionality.  It's a good question about what the Right Default is for a library.  It's not very discoverable, and if you were using a CLI-type of feature, or something that integrates with git itself, then it's very useful.

The examples should almost certainly use it as their default.  But that doesn't really solve your problem; it would be nice if git2go would support this also.

**Comment by LinuxBozo** [comment]
@ethomson Ahead of you on git2go: https://github.com/libgit2/git2go/pull/366

**Comment by ethomson** [comment]
😀
