### ISSUE TITLE
git_remote_delete fails with "Cannot delete multivar with a single delete"

### ISSUE THREAD

**Issue by jminor** [libgit2/libgit2#4155]
### Reproduction steps

Create a remote with multiple fetch or push specs like this:
git_remote_create(&remote, repo, name, url)
git_remote_add_push(repo, name, spec1)
git_remote_add_fetch(repo, name, spec2)

Now try to delete the remote with:
git_remote_delete(repo, name)

### Expected behavior

The remote should be deleted without error.

### Actual behavior

The call to git_remote_delete fails with return code -1
and the error message "Cannot delete multivar with a single delete"

### Version of libgit2 (release number or SHA1)

0.24.0

### Operating system(s) tested

iOS

**Comment by jminor** [comment]
Also, and this is likely related, I seem to end up with multiple entries for the one (and only) remote that I have added to my repo.

Here is what my .git/config file looks like after trying to delete and add the same remote multiple times:
```
[remote "backup"]
	url = ssh://redacted@redacted/path/repo.git
	fetch = +refs/heads/*:refs/remotes/backup/*
	push = +refs/heads/master
[remote "backup"]
[remote "backup"]
[remote "backup"]
	fetch = refs/heads/master
```

**Comment by ethomson** [comment]
Are you really using 0.24.0, or was that a typo?  I ask because that's quite old (over a year) and this sounds a bit like a bug that we've fixed previously.  Can you try with the most recent release?

**Comment by jminor** [comment]
I'm using the latest release of ObjectiveGit, which uses 0.24.0 of libgit2. https://github.com/libgit2/objective-git/releases
I'll try updating to a more recent version to see if that has the same issue. Thanks for pointing that out, I didn't realize that it was out of date.
