### ISSUE TITLE
git_config_set_string fails for symlink for config file on Windows

### ISSUE THREAD

**Issue by csware** [libgit2/libgit2#4168]
### Reproduction steps

Create a symlink on `%HOME%\.gitconfig` (e.g., using `mklink .gitconfig d:\.gitconfig`).

Try to alter a config value using `git_config_set_string`

### Expected behavior

The config file is updated.

### Actual behavior

`git_config_set_string` fails with: `failed to create locked file 'C:/Users/user/.gitconfigd:/.gitconfig.lock': Die Syntax für den Dateinamen, Verzeichnisnamen oder die Datenträgerbezeichnung ist falsch.`

### Version of libgit2 (release number or SHA1)

7143145f2fcb0f7476f333f9df990b8a06cd52c0

### Operating system(s) tested

Win7

**Comment by csware** [comment]
The error occurrs here: https://github.com/libgit2/libgit2/blob/7143145f2fcb0f7476f333f9df990b8a06cd52c0/src/filebuf.c#L247.

**Comment by pks-t** [comment]
This should be fixed by #4169.

**Comment by csware** [comment]
Yes, the issue is solved now.
