### ISSUE TITLE
git_clone error message Assertion failed: git_atomic_get(&git__n_inits) > 0

### ISSUE THREAD

**Issue by jablkojem** [libgit2/libgit2#4185]
When I tried to do git_clone(), this error message occured

Assertion failed: git_atomic_get(&git__n_inits) > 0, file C:\data\Install\Git\libgit2-0.25.1\src\global.c ,line 199

My program is interrupted by Visual Studio ( R6010 - abort() has been called )
There is my code : 

git_repository *cloned_repo = NULL;
	cout << all_urls.at(num).c_str() << " -> " << clone_to.at(num).c_str() << endl;
	int error = git_clone(&cloned_repo, all_urls.at(num).c_str(), clone_to.at(num).c_str(), &clone_opts);
	if (error != 0) {
		const git_error *err = giterr_last();
		cerr << "error in clone num " << num << " -> message :" << err->message << endl;
	}
	else cout << endl << "Clone " << num << " succesful" << "(from url : " << all_urls.at(num) << "    " << "to path : " << clone_to.at(num) << ")" << endl;
	git_repository_free(cloned_repo);

I have properly set clone_opts (credentials), so I really do not know where is the problem. 
Thanks

**Comment by pks-t** [comment]
You have probably not called the function `git_libgit2_init();`. Before you start using the library, you have to call it so that libgit2 can initialize some internal datastructures. On shutdown you should also call `git_libgit2_shutdown();`.

**Comment by jablkojem** [comment]
I called that in some methods before so I thought I don't have to call this function also in these method, but you are right,that was the problem. 
Thanks
