### ISSUE TITLE
git_merge needs to reload the index

### ISSUE THREAD

**Issue by Uncommon** [libgit2/libgit2#4203]
### Reproduction steps
* Do something that makes libgit2 load the index
* Do something to the index from the command line (like commit) so that the index & worktree are clean
* Call `git_merge()`

### Expected behavior
Merge proceeds, recognizing the clean state

### Actual behavior
Using a stale index, git_merge aborts with `GIT_ECONFLICT`

### Workaround
Manually refreshing the index produces the expected behavior.

### Version of libgit2 (release number or SHA1)
0.25.1

### Operating system(s) tested
macOS 10.12.3

**Comment by ethomson** [comment]
Yep, just like checkout reloads the index, so too should merge, when checking for conflicts.  Thanks for reporting this.
