### ISSUE TITLE
We should get rid of CURL and use our onw HTTP CONNECT proxy implementation

### ISSUE THREAD

**Issue by carlosmn** [libgit2/libgit2#4207]
The only use of libcurl that we have is for it to connect to proxies via the `CONNECT` method, which then simply proxies our data stream unaltered to the final location.

It however adds complexity in the build process and a dependency we're barely using. It introduces a different way of talking to remote machines and its own way of representing X.509 certificates which mean we can't convert them into native objects in higher-level languages.

Since we need to have our own HTTP stack anyway, it sounds like a worthwhile trade-off to implement our own `CONNECT` client so we don't depend on curl being available both on the build and target machines.

**Comment by mtangoo** [comment]
I agree. It took me days only to compile curl with libgit2. Today I don't even remember how I did it.  Curl is great but its just a nightmare to compile with libgit2 esp for app that should work in all major platforms

**Comment by ethomson** [comment]
Fixed via #4870

**Comment by mtangoo** [comment]
@ethomson does it mean libgit2 is no longer depending on libcurl?

**Comment by ethomson** [comment]
@mtangoo Yes.

**Comment by mtangoo** [comment]
That's great! One more dependency off..!
Next is OpenSSL (just kidding)
