### ISSUE TITLE
Unused sys/remote.h

### ISSUE THREAD

**Issue by alehed** [libgit2/libgit2#4208]
Is there any reason the file sys/remote.h exists?

Looking at the file the following puzzles me:
* It is not included anywhere
* It defines `INCLUDE_sys_git_transport_h` instead of `INCLUDE_sys_git_remote_h`
* the `#ifndef` is not terminated by a `#endif`

I'm building libgit2 as a module and with the newest Xcode this causes a build failure.

**Comment by pks-t** [comment]
Looks like the file's been added accidentally in 60d717c6f, at least nothing warrants the file being there. @carlosmn?

**Comment by carlosmn** [comment]
I probably created it while trying to expose some internals and never noticed the addition. It can indeed go away.
