### ISSUE TITLE
does git_stash_save() exists? Or how to perform "git stash" in libgit2

### ISSUE THREAD

**Issue by jablkojem** [libgit2/libgit2#4213]
Is there some function like git_stash_save() in libgit2? Or how can I perform "git stash" in libgit2 ? 
I searched in libgit2 API but all I found was functions to pop or drop stashes from stash list, but how do I fill that list?

https://libgit2.github.com/libgit2/#HEAD/group/stash

**Comment by rcjsuen** [comment]
@jablkojem There is a [`git_stash_save(*)`](https://github.com/libgit2/libgit2/blob/master/include/git2/stash.h#L49-L71) function but it doesn't seem to be included in the documentation.

**Comment by mtangoo** [comment]
Thanks @rcjsuen  for pointing that. It saved me good amount of pain. @carlosmn @ethomson  et al, is there any reason this function is not even mentioned in docs?

**Comment by ethomson** [comment]
That's an oversight, @mtangoo.  We would welcome a pull request to correct that.

**Comment by mtangoo** [comment]
ok thanks. I will try to find time and correct that. Any guidelines for adding things to docs?

**Comment by ethomson** [comment]
No idea why the docs generator isn't adding this.  🤷‍♂️

**Comment by tiennou** [comment]
I'm actually working on it 😉. We're missing some includes, which seems to confuse ffi/clang into thinking the comment is *not there*.
