### ISSUE TITLE
libgit2 0.25.1 doesn't build with libressl

### ISSUE THREAD

**Issue by Keruspe** [libgit2/libgit2#4220]
Latest release doesn't build with libressl.
The issue is fixed in git (since december ?) in #4043 but the fix doesn't appear to be in the release from january.
5 months have passed since the fix, could we get a 0.25.2 compatible with libressl?

**Comment by ethomson** [comment]
I think it's about time for an 0.26.

**Comment by ethomson** [comment]
Opened an issue to coordinate a new release - #4227 - closing this one.  Thanks!
