### ISSUE TITLE
GIT_STATUS_OPT_RENAMES_FROM_REWRITES always enabled

### ISSUE THREAD

**Issue by powerman** [libgit2/libgit2#4222]
### Reproduction steps

https://github.com/libgit2/git2go/issues/380 (but I suppose this isn't git2go issue, so report it here too).

### Expected behavior

When GIT_STATUS_OPT_RENAMES_FROM_REWRITES is not enabled slightly modified file shouldn't be detected as renamed.

### Actual behavior

No matter is GIT_STATUS_OPT_RENAMES_FROM_REWRITES enabled or not slightly modified file is detected as renamed.

### Version of libgit2 (release number or SHA1)

df4dfaa (week ago)

### Operating system(s) tested

Linux amd64.

**Comment by ethomson** [comment]
A slightly modified file falls under the category of _general_ rename detection.  If you don't want that, you need to turn off rename detection entirely.

Renames from rewrites turns on similarity detection for _all_ files, such that if some file is completely rewritten then it becomes eligible for rename detection.


If you delete some file `a.txt` and create a file `b.txt` with identical content, that's _exact_ rename detection.

If you delete some file `a.txt` and create a file `b.txt` with similar content, say changing just one line out of 1,000, that's _inexact_ rename detection.

If you delete some file `a.txt` and create a file `b.txt` with identical content...  and then you _recreate_ a new `a.txt` that is completely different, that's a situation that is eligible _renames from rewrites_.  When this is enabled then you'll see a rename from `a.txt` to `b.txt` and a new file `a.txt`.

It doesn't look like you're recreating `a.txt` in your example, and you're not seeing the new `a.txt` in status.  This is just normal rename detection in action.

**Comment by powerman** [comment]
Hm. Maybe I get it wrong, but it sounds like _inexact_ rename detection is always enabled and there is no flag to disable it. And at a glance this feature means modified file content should be read and compared to all existing files (or just deleted ones), which is much more work than single `lstat` call.

If this is the case then issue can be closed, as there is no issue… except libgit2 being surprisingly slow comparing to `git status` command (about 2 times slowed when core.untrackedCache is disabled and about 4.5 times slower when it's enabled on large repo like [gentoo](https://github.com/gentoo/gentoo) - but that's different issue anyway).

**Comment by ethomson** [comment]
> Maybe I get it wrong, but it sounds like inexact rename detection is always enabled and there is no flag to disable it.

No, but that's true of `git-status` as well, as far as I can recall.  This is a reasonable request, though.

> If this is the case then issue can be closed, as there is no issue… except libgit2 being surprisingly slow comparing to git status command (about 2 times slower when core.untrackedCache is disabled and about 4.5 times slower when it's enabled on large repo like gentoo - but that's different issue anyway).

Well, we don't support `core.untrackedCache`, which probably accounts for a lot of that speed difference when you enable it.  But I'd be interested in understanding why it's 2x slower without that turned on.

**Comment by powerman** [comment]
> But I'd be interested in understanding why it's 2x slower without that turned on.

I can show the code in Go and required commands to setup environment and benchmark times which demonstrate 2x slowdown, but that's all I can do. Of course, there is a chance slowdown happens because of Go libgit2 wrapper, but to find this out someone should rewrite my Go code in C. If this sounds reasonable for you - I'll open another issue here with all details.

**Comment by ethomson** [comment]
> Of course, there is a chance slowdown happens because of Go libgit2 wrapper...

Not impossible, but it seems unlikely.

> If this sounds reasonable for you - I'll open another issue here with all details.

Sure, I'd be happy to take a look.  Thanks!
