### ISSUE TITLE
One-sided revision ranges not supported

### ISSUE THREAD

**Issue by wabain** [libgit2/libgit2#4223]
Command-line git supports leaving one side of a revision range blank, like `origin/master...`. When unspecified, the revision defaults to HEAD. Currently, libgit2 doesn't support these revision formats.

### Reproduction steps

Run `examples/rev-parse` with one-sided revision ranges.

### Expected behavior

The same as command-line git:

```
$ git rev-parse ..HEAD~1
d476d024d0415a566b858daec7faa961587bae14
^f9d3b0d05f19a59e3327deabc2edc93e507c6aa3

$ git rev-parse HEAD~1..
f9d3b0d05f19a59e3327deabc2edc93e507c6aa3
^d476d024d0415a566b858daec7faa961587bae14
```

### Actual behavior

```
$ examples/rev-parse ..HEAD~1
Could not parse '..HEAD~1' [-12] - failed to parse revision specifier - Invalid pattern ''

$ examples/rev-parse HEAD~1..
Could not parse 'HEAD~1..' [-12] - failed to parse revision specifier - Invalid pattern ''
```

### Version of libgit2 (release number or SHA1)
v0.16.0-8230-g89141d9

### Operating system(s) tested
MacOS 10.12.4

**Comment by ethomson** [comment]
This seems like a reasonable request; I'm adding the up-for-grabs tag.
