### ISSUE TITLE
Error reading index v4

### ISSUE THREAD

**Issue by jdavid** [libgit2/libgit2#4234]
### Reproduction steps

Create an index v4 with Git:

    $ git --version
    git version 2.12.2
    $ git init /tmp/test-v4
    $ cd /tmp/test-v4/
    $ git update-index --index-version=4
    $ touch file.txt
    $ git add file.txt 
    $ git commit -m "first commit"

Try to open the index with libgit2:

    #include <git2.h>
    #include <stdio.h>

    int main()
    {
      git_repository *repo;
      git_index *index;
      int err;

      err = git_repository_open(&repo, "/tmp/test-v4");
      if (err < 0) {
        printf("Error opening repo\n");
        return 1;
      }

      err = git_repository_index(&index, repo);
      if (err < 0) {
        printf("%s\n", giterr_last()->message);
        return 1;
      }

      return 0;
    }

### Expected behavior

Run without error.

### Actual behavior

Error reading the index file:

    $ ./a.out
    Invalid data in index - extension is truncated

### Version of libgit2 (release number or SHA1)

0.25.1

### Operating system(s) tested

Linux (Gentoo)

**Comment by pks-t** [comment]
Thanks for the reproduction instructions, it's easily reproducible like this. Seems like we're reading compressed index path names in a wrong way, which causes this error. I'm investigating.

**Comment by jdavid** [comment]
@pks-t it works now, thanks!

**Comment by ethomson** [comment]
Fixed via #4236 - thanks @jdavid for reporting this and @pks-t for the fix!
