### ISSUE TITLE
Incorrect detection of modified/renamed files (simillarity)

### ISSUE THREAD

**Issue by FabriceSalvaire** [libgit2/libgit2#4237]
I found an incorrect detection of modified/renamed files using pygit2/libgit2 0.25.1 on a particular commit where git status (v2.9.3) reports the correct answer.

I used https://github.com/FabriceSalvaire/CodeReview as pygit2/libgit2 frontend.

### Reproduction steps
On this commit https://github.com/bleausard/meije-tk/commit/2e19032bd15cc7ae05e2e118681b42495c2acdaf

### Expected behavior

* new file: src/bleaudb/bleau_database.h
* deleted:  src/bleaudb/bleaudb_json_loader.h
* renamed:  unit-tests/bleaudb/test_bleau_database.cpp -> unit-tests/bleaudb/test_bleau_schema.cpp

### Actual behavior

Incorrect relation:
* renamed: src/bleaudb/bleaudb_json_loader.h -> src/bleaudb/bleau_database.h 55%

Renaming is not detected:
* modified: unit-tests/bleaudb/test_bleau_database.cpp
* new file: unit-tests/bleaudb/test_bleau_schema.cpp

### Version of libgit2 (release number or SHA1)
libgit2/pygit2 0.25.1

### Operating system(s) tested
Linux Fedora 25

**Comment by ethomson** [comment]
Renaming is a heuristic.  We use a similar algorithm to git, but it is not identical.  At the 55% similarity range, this is exceptionally unreliable, you're very close to the cutoff.  This is why the default is to not treat anything less than 60% similar as a rename.

**Comment by FabriceSalvaire** [comment]
I am more confused by this case:

renamed:    unit-tests/bleaudb/test_bleaudb.cpp -> unit-tests/bleaudb/test_bleau_database.cpp
renamed:    unit-tests/bleaudb/test_bleau_database.cpp -> unit-tests/bleaudb/test_bleau_schema.cpp

where test_bleau_database.cpp is considered as modified.

**Comment by ethomson** [comment]
That's "rewrite breaking".  If a file is completely rewritten (very dissimilar to the prior version), it becomes eligible for being used in rename detection.  It's to detect the case where you switch the contents of two files `A` and `B`

**Comment by FabriceSalvaire** [comment]
Just to precise my previous comment, these two **true** renamed and modified files was found by git status. 

I looked the diff for these two files to see how far they are. And it look like git status was very clever to find the right answer since there are modifications and a file name exchange. Maybe by chance ?

Can you confirm they don't implemented clever distance algorithm ?

**Comment by ethomson** [comment]
I'm not entirely sure what you're asking...  what is a "__true__" renamed file?

They definitely implement a clever distance algorithm.  Every add / delete pair in your commit is examined, and the similarity between each add is compared to the similarity between each delete.  The _most similar_ add/delete pair is converted to a "rename" if it's above a threshold (by default 60% similar).  Is that what you mean by clever?

**Comment by FabriceSalvaire** [comment]
I mean git status found the right answer for:

- renamed: unit-tests/bleaudb/test_bleaudb.cpp -> unit-tests/bleaudb/test_bleau_database.cpp
- renamed: unit-tests/bleaudb/test_bleau_database.cpp -> unit-tests/bleaudb/test_bleau_schema.cpp

Thus this answer is not by chance, but due to a different algorithm which found the right answer in this particular case.

I feel we should check the impact of a renaming before to commit. It is probably impossible to design the perfect algorithm.

Can we expect a convergence between the development of git and libgit in the future  ?

**Comment by ethomson** [comment]
What do you mean the "right answer"?  You mean that git happened to decide with its heuristic that the rename was actual the mechanism that you performed?

Are you using the same settings between git and libgit2?

> Can we expect a convergence between the development of git and libgit in the future ?

There's a lot of convergence in general.  More convergence in rename detection?  Unlikely - they're exceptionally similar already and, again, this is very questionable to begin with.  It's very much a guess.

**Comment by FabriceSalvaire** [comment]
> Are you using the same settings between git and libgit2?

I have to check (what is doing pygit2).

I agree this is a difficult topic. I remember bzr was in fact a pain.

I hesitate on theses strategies:
* don't commit change that mess git diff
* handle the mess in the code review tool (store manually what happened ?)

**Comment by ethomson** [comment]
I don't know what you mean by not committing...

Git does _not_ store rename information in commits.  It stores a complete snapshot of history.

Git clients will rederive rename information at the moment that you run `git diff` to compare two commits.

This means that if you don't like the output you can tweak the parameters.
