### ISSUE TITLE
setting credentials just for the first time 

### ISSUE THREAD

**Issue by jablkojem** [libgit2/libgit2#4245]
So I use some libgit2 functions to connect to the remote and perform git push. I want to push to private repository, so I have to set credentials. 

But for example, when I work with private repositories via git commands and I want to connect for the first time to this repository, I enter credentials...but after that, if I want to push for the second, third time or so, I don't have to write that credentials again, also when I restart computer. It seems to me that there is some place where "known repositories" are stored with their credentials. 

And my question is, is there a way how to do that with libgit2? I mean, is there a way how to push to "known" private remote repositories without setting credentials? "Known" means repositories which I already worked with so I have already set credentials.

 I want to work with many different repositories, each of these repositories have their own credentials so I don't want to set credentials manually everytime I push.

When I perform push without setting credentials(push to "known" repo), this error message is displayed

Request failed with status code: 401

So is there a way, how not to set credentials every time I push?

**Comment by pks-t** [comment]
Upstream git implements so-called credential helpers. They come in various forms, e.g. the `git-credential-store` helper writes credentials to disk in plain text, the `git-credential-cache` persists it in memory until the computer restarts. See gitcredentials(7) for more information. There is also interaction with the `ssh-agent`, which persists decrypted SSH keys in memory. This is only used for SSH-key based authentication.

libgit2 itself currently does not implement caching of credentials by itself, as this is somewhat out of scope of libgit2 itself. How credentials are to be stored should be handled by the application calling into libgit2, instead. That said, one thing I _could_ imagine is us talking to the git credential daemons ourselves. But currently, this is not implemented.
