### ISSUE TITLE
Cannot remove local branch with remote tracking branch if config is included

### ISSUE THREAD

**Issue by csware** [libgit2/libgit2#4247]
### Reproduction steps

1. Set an included config file, e.g. using `git config --local include.path ../something` (a valid config file named something must exist parallel to the .git dir)
2. Create a local branch with a remote tracked branch, e.g. using `git branch --track master2 remotes/origin/master`
3. Delete the local branch using libgit2 with `git_branch_delete` after looking it up using `git_reference_lookup`.

### Expected behavior

The branch is removed, the config file is adjusted and no error.

### Actual behavior

libgit2 fails with: `could not find key 'branch.master2.merge' to delete`

### Version of libgit2 (release number or SHA1)

87f5fbabdcd2318e136a142b9fcddf5614348546

### Operating system(s) tested

Win7 x64

Crossref: https://gitlab.com/tortoisegit/tortoisegit/issues/2976

**Comment by pks-t** [comment]
Thanks for the awesome reproduction steps, I can reproduce the error like this. It is indeed related to the include, erasing it allows me to delete the branch again. I'll take a look at the code.

**Comment by csware** [comment]
Fixed.
