### ISSUE TITLE
creating remote repository via libgit2

### ISSUE THREAD

**Issue by jablkojem** [libgit2/libgit2#4248]
I want to create remote repository on [www.bitbucket.org](url) via libgit2 in c++. If remote repository is already created, adding remote is easy :

`string url = "https://user@bitbucket.org/user/project.git";`
`git_remote_create(&remote, repo, "origin", url.c_str());`

But the problem is if this url doesn't exist, I mean that I don't have "project.git" in my remote repo, 
Is there a way how to create that project.git in my remote repo via libgit2?

I read this (the second issue), 
[ https://github.com/libgit2/libgit2sharp/issues/1162 ](url)
but is it still true? It's almost 2 years, so some changes could be made.

**Comment by ethomson** [comment]
No, this is not something that libgit2 is capable of doing.  BitBucket should provide you some API that is capable of talking to their servers.  This is not something that is part of the Git protocol, so it's not something that we support.
