### ISSUE TITLE
Support `git patch-id` to compare the changes in different diffs

### ISSUE THREAD

**Issue by not-an-aardvark** [libgit2/libgit2#4270]
(Context: I asked about whether this feature exists in the libgit2 slack channel, and @ethomson mentioned I should create an issue for it here.)

I'm looking for a way to compare two diffs to see if they modify precisely the same lines. When using git from the command line I would do this with `git patch-id`, but I don't think there is a way to determine something like a `patch-id` with libgit2.

---

Example of a scenario where `git patch-id` is useful on the command line:

1. Start from `master` with an existing file called `foo.txt`.
1. Create a branch `branchA` from master and make a commit `aaaaaaa` that modifies `foo.txt`.
1. Create a branch `branchB` from master and make a commit `bbbbbbb` that modifies a different part of `foo.txt`.
1. Cherry-pick commit `aaaaaaa` onto `branchB`.

`git diff branchB^ branchB` and `git diff master branchA` print out the "same" diff (they make the same changes to the same lines), but the textual output of the commands is different, because the diff output includes the line `index something..somethingElse` at the top. (I'm not sure exactly what this line means, but I think it's related to the state of the file at the base of the diff.)

To accurately compare the two, you can pipe both diff outputs to `git patch-id` before comparing them, i.e. compare `git diff branchB^ branchB | git patch-id` and `git diff master branchA | git patch-id`. `git patch-id` effectively hashes only the changed lines in a diff, and strips out the other metadata, so it allows diffs to be compared based on whether they make the same changes to the same lines.

**Comment by ethomson** [comment]
Seems like a reasonable feature, thanks for opening an issue.  I won't have time to get to this immediately, so I'm going to add the up for grabs tag in case somebody wants inspiration for a place to contribute before I'm able to get to this.

**Comment by not-an-aardvark** [comment]
By the way, I wanted to mention that I found a different solution to the problem I was trying to solve, so I no longer need this feature. Of course, I don't mind if you implement it anyway for the benefit of other users, but feel free to close this issue if it's not something that you think would be generally useful.

**Comment by pks-t** [comment]
This is already implemented (but not merged yet) by #4272, so I'll keep the issue open until it is merged.

**Comment by pks-t** [comment]
Implemented and merged via a94a54021c118df5d0cf526c0ace4bd96a442f39
