### ISSUE TITLE
Building on system without mmap seems to be broken

### ISSUE THREAD

**Issue by ids1024** [libgit2/libgit2#4281]
Since https://github.com/libgit2/libgit2/commit/f7310540ae888454f9ab69200cfcd8df07faf957, `p_mmap()` is used to write, but the fallback implementation for systems without mmap doesn't support this, and returns the error `trying to map shared-writeable`.

**Comment by ethomson** [comment]
We now run nightlies with mmap-disabled builds. I think that we've fixed this issue.
