### ISSUE TITLE
How do I force push?

### ISSUE THREAD

**Issue by logicminds** [libgit2/libgit2#4286]
How do I force push a branch?  I thought there was a undocumented way based on a specific symbol prepended in the ref but I don't remember where I saw that?  `+refs/heads/branch1123`

**Comment by linquize** [comment]
```
char *spec_push[] = { "+refs/heads/branch1123:refs/heads/branch1123" };
git_strarray specs = { spec_push, 1 };
git_remote_push(remote, &specs, NULL);
```

**Comment by rustyx** [comment]
Is that documented somewhere? Also, how to do a `force-with-lease`?

**Comment by tiennou** [comment]
@rustyx We normally prefer API-usage questions be posted to [StackOverflow](https://stackoverflow.com/questions/tagged/libgit2), but your question is not completely related to `libgit2` itself, so here's an attempt at an helpful answer :

AFAIK the '+' means `force` in [Refspeak](https://git-scm.com/book/it/v2/Git-Internals-The-Refspec), so IMHO that qualifies as documented, as part of `git`'s refspec syntax 😉. I do realize it's quite possible we never explicitly state that anywhere in our documentation though…

`force-with-lease` might be doable by handling the "lease checks" yourself, as part of the [negotiation](https://github.com/libgit2/libgit2/blob/HEAD/include/git2/remote.h#L461) callback (or maybe [update_refs](https://github.com/libgit2/libgit2/blob/HEAD/include/git2/remote.h#L475), but that might be too late), by comparing the pushed branch's "current OID", current remote "local OID", and the current remote "remote OID" (what the server is reporting), and complaining if "local OID" and "remote OID" are not the same. AFAIU it doesn't seem to depend on protocol-level changes, so what we provide might be sufficient, and if you're willing to implement this as part of libgit2 itself, that would be ❤️.
