### ISSUE TITLE
One cause of "The reference 'refs/heads/master' cannot be peeled - Cannot retrieve reference target"

### ISSUE THREAD

**Issue by dirk-de-bugger** [libgit2/libgit2#4293]
_I played with libgit2 and came around this error and debugged it a bit. In the end cmake found an ancient zlib header and lib burried in %PATH%._

_Here is a record of my findings in hope it may help._

**ERROR**:

Call to git_status_list_new() fails.

Message from git_reference_peel(): "the reference 'refs/heads/master' cannot be peeled - Cannot retrieve reference target"

**ISSUE**:

Primary error message **overwritten**:
Message from inflate_disk_obj(): "failed to inflate disk object"

**CAUSED BY**:

start_inflate(): inflateInit() returns 661 (?), inflate() then -6 (Z_VERSION_ERROR)

**CAUSED BY**:

cmake ..
-- Found ZLIB: C:/gnuwin32/lib/zlib.lib (found version "1.2.3")

**QUICK FIX**:

Disable package searching in CMakeLists.txt:

`#FIND_PACKAGE(ZLIB)`
`#IF (ZLIB_FOUND)`
`#    INCLUDE_DIRECTORIES(${ZLIB_INCLUDE_DIRS})`
`#    LINK_LIBRARIES(${ZLIB_LIBRARIES})`
`#    IF(APPLE OR CMAKE_SYSTEM_NAME MATCHES "FreeBSD")`
`#        LIST(APPEND LIBGIT2_PC_LIBS "-lz")`
`#    ELSE()`
`#        SET(LIBGIT2_PC_REQUIRES "${LIBGIT2_PC_REQUIRES} zlib")`
`#    ENDIF()`
`#ELSE()`
`    MESSAGE(STATUS "zlib was not found; using bundled 3rd-party sources." )`
`    INCLUDE_DIRECTORIES(deps/zlib)`
`    ADD_DEFINITIONS(-DNO_VIZ -DSTDC -DNO_GZIP)`
`    FILE(GLOB SRC_ZLIB deps/zlib/*.c deps/zlib/*.h)`
`#ENDIF()`

**SUGGESTED FIX**:

Add cmake option to disable package searching.

**Comment by ethomson** [comment]
Hmm, interesting.  Is it common that on Cygwin one might have defective libraries installed?  Should we just always use our own zlib on Cygwin?

**Comment by ethomson** [comment]
(I ask because I feel like figuring out the problem was the hardest part here?)

**Comment by pks-t** [comment]
I don't think it makes sense to always use our own libraries here, as in the common case you'd like to use the Cygwin provided one. What might have helped here is #4290 or a variation thereof, e.g. displaying information on which dependencies are being used.

**Comment by dirk-de-bugger** [comment]
Note: [GnuWin32](http://gnuwin32.sourceforge.net/) is not a Cygwin installation but a (rather old) collection of Linux tools compiled for Windows.

Whatever the outcome of this is, I hope there will be a official possibility to choose the deps packages in favor of the things floating around my machine. Just an improved info on the dependencies doesn't help much in my case.

Thanks for considering this.

**Comment by pks-t** [comment]
Didn't note this was GnuWin32 instead of Cygwin, thanks for clarifying. And yes, I do agree we should provide the ability to force usage of bundled dependencies instead of system-provided ones. I'll tackle this issue after #4282 is merged.

**Comment by hkleynhans** [comment]
Patch that adds cmake option to select bundled version of zlib: https://github.com/libgit2/libgit2/pull/4403

**Comment by pks-t** [comment]
I'll close the issue for now. Thanks to #4403 we now provide the ability to select the bundled version of zlib, which allows the user to at least fix the issue. Feel free to comment if you feel like your issue is not addressed after all.
