### ISSUE TITLE
Another .gitignore issue versus standard Git

### ISSUE THREAD

**Issue by segevfiner** [libgit2/libgit2#4295]
> https://github.com/libgit2/libgit2/issues/3224#issuecomment-313621374
> 
> @segevfiner I guess your issue is different, as it is caused by issues with case-insensitivity. It would be very nice if you could create a new issue describing the problem.

cc @pks-t 

CPython's has in it's .gitignore the following:
```
# Two-trick pony for OSX and other case insensitive file systems:
# Ignore ./python binary on Unix but still look into ./Python/ directory.
/python
!/Python/
```

The Python directory is not ignored by Git but is ignored by libgit2 (Found this due to Atom).

### Reproduction steps
1. Clone https://github.com/python/cpython
2. `git check-ignore -v Python` &ndash; The file isn't ignored
3. Using Pygit2:
```python
>>> import pygit2
>>> a = pygit2.Repository('.')
>>> a.path_is_ignored('Python')
True
```

### Expected behavior
The Python directory should not be ignored like in standard Git.

### Actual behavior
The Python directory is ignored by libgit2.

### Version of libgit2 (release number or SHA1)
`pygit2.LIBGIT2_VERSION` &ndash; v0.26.0
Atom git-utils v5.0.0 uses libgit2 v0.24.3

### Operating system(s) tested
Windows 10.0.15063 x64

**Comment by pks-t** [comment]
Thanks for creating a new issue for this! I've implemented a fix in #4296
