### ISSUE TITLE
How to use utf8 file names with libgit2

### ISSUE THREAD

**Issue by rgutherz** [libgit2/libgit2#4300]
How can I use libgit2 with utf8 file names with c/c++?
It seems that all API are char* and not wchar_t *
I'm on Windows machine and can't figure it out
Is is possible?

**Comment by rgutherz** [comment]
For example hot to use git_index_add_bypath with wchar_t* file names

**Comment by ethomson** [comment]
The various components of a Git repository store strings as sequences of bytes.  These are typically UTF8 (either by formality or by convention).  libgit2 therefore simply takes a sequence of bytes (a `char *` as you point out).

On Windows, it is expected that you pass paths as UTF8; Git for Windows will covert all paths from UCS2 to UTF8.  Users of libgit2 should do the same.  We do not have any API that takes UTF16 (or similar 16 bit Unicode encodings) or other wide encodings.

If you have a `wchar` array containing Unicode or another wide charset then you will need to convert using something like https://msdn.microsoft.com/en-us/library/dd374130(VS.85).aspx

**Comment by rgutherz** [comment]
Thanks a lot!
works great!

**Comment by ethomson** [comment]
Great! 😀
