### ISSUE TITLE
libgit2 doesn't handle .gitignore/exclude patterns with trailing white space

### ISSUE THREAD

**Issue by segevfiner** [libgit2/libgit2#4309]
libgit2 doesn't handle patterns with trailing white space the same as standard git. No one is likely to create such patterns on purpose. The only reason I encountered this is that Windows, being Windows, surprisingly treats a trailing white space between the '>' and the echo command as significant and writes that to the file.

### Reproduction steps
1. Execute (For Windows):
    ```cmd
    git init test-repo && cd test-repo
    echo. > test.txt && echo. > test2.txt
    echo test.txt > .gitignore
    echo test2.txt >> .git\info\exclude
    ```
    Or (For Linux, untested):
    ```sh
    git init test-repo && cd test-repo
    touch test.txt test2.txt
    echo "test.txt " > .gitignore
    echo "test2.txt " >> .git/info/exclude
    ```
2. `git status` or `git check-ignore` &ndash; "test.txt" and "test2.txt" are ignored.
3. Execute with pygit2:
    ```py
    >>> from pygit2 import Repository
    >>> a=Repository('.')
    >>> a.path_is_ignored('test.txt')
    False
    >>> a.path_is_ignored('test2.txt')
    False
    ```

### Expected behavior
The files are ignored by libgit2/pygit2 the same as in Git.

### Actual behavior
They are not ignored.

### Version of libgit2 (release number or SHA1)
0.26.0 (From pygit2 0.26.0)

### Version of git
2.13.2.windows.1

### Operating system(s) tested
Windows 10.0.15063 x64

### See Also
> * Trailing spaces are ignored unless they are quoted with backslash ("\\").
>
> &ndash; https://git-scm.com/docs/gitignore

https://github.com/atom/atom/issues/14706

cc @pks-t

**Comment by pks-t** [comment]
By now I really hate ignore rules. It's unbelievable how hard it is to get them completly right and the same as in upstream git :slightly_smiling_face: 

Anyway, thanks for the report. I'll take a look at this issue (hopefully) soon.

**Comment by gaborbernat** [comment]
solved by https://github.com/libgit2/libgit2/commit/5cb6a2c946a071d43be3cdabf2f6d4417a4be694

**Comment by pks-t** [comment]
Thanks a lot for digging up!
