### ISSUE TITLE
A static build does not include the http parser symbols

### ISSUE THREAD

**Issue by carlosmn** [libgit2/libgit2#4336]
### Reproduction steps

`cmake . -DUSE_EXT_HTTP_PARSER=OFF -DBUILD_SHARED_LIBS=OFF`

### Expected behavior

`libgit2.a` should have the http-parser symbols. This does happen with the dynamic build

```
% nm libgit2.so | grep http_parser
00000000000e86bb t http_parser_execute
00000000000eb956 t http_parser_init
00000000000ebe5b t http_parser_parse_url
00000000000ec09f t http_parser_pause
```

### Actual behavior

The symbols are undefined.

```
% nm libgit2.a | grep http_parser 
                 U http_parser_parse_url
                 U http_parser_execute
                 U http_parser_init
```

### Version of libgit2 (release number or SHA1)

Current master aka 3c21645360

### Operating system(s) tested

Ubuntu Trusty (in Travis, where I discovered this) and Debian Sid.

**Comment by carlosmn** [comment]
I've been trying to get CMake to include it, but the only way I found it would actually work is by going back to giving it the http-parser sources to build as part of the library.

```diff
diff --git a/src/CMakeLists.txt b/src/CMakeLists.txt
index 3392a4218..8a8542cfd 100644
--- a/src/CMakeLists.txt
+++ b/src/CMakeLists.txt
@@ -194,7 +194,7 @@ ELSE()
        MESSAGE(STATUS "http-parser version 2 was not found or disabled; using bundled 3rd-party sources.")
        ADD_SUBDIRECTORY("${CMAKE_SOURCE_DIR}/deps/http-parser" "${CMAKE_BINARY_DIR}/deps/http-parser")
        LIST(APPEND LIBGIT2_INCLUDES "${CMAKE_SOURCE_DIR}/deps/http-parser")
-       LIST(APPEND LIBGIT2_LIBS http-parser)
+       FILE(GLOB SRC_HTTP "${CMAKE_SOURCE_DIR}/deps/http-parser/*.[ch]")
 ENDIF()
 
 # Optional external dependency: zlib
@@ -355,7 +355,7 @@ SET(LIBGIT2_LIBDIRS ${LIBGIT2_LIBDIRS} PARENT_SCOPE)
 
 # Compile and link libgit2
 LINK_DIRECTORIES(${LIBGIT2_LIBDIRS})
-ADD_LIBRARY(git2 ${WIN_RC} ${GIT2INTERNAL_OBJECTS})
+ADD_LIBRARY(git2 ${WIN_RC} ${GIT2INTERNAL_OBJECTS} ${SRC_HTTP})
 TARGET_LINK_LIBRARIES(git2 ${LIBGIT2_LIBS})
 
 SET_TARGET_PROPERTIES(git2 PROPERTIES LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR})
```

**Comment by pks-t** [comment]
Yeah, this really sucks. I thought `TARGET_LINK_LIBRARIES` would automatically merge static archives together, but as we can see here this is not the case. Which is quite unfortunate. There are multiple solutions here where I'm not particularly happy with any of these.

The first one is yours, which we'd have to repeat for the regex and zlib dependencies as well. I'm not much of a fan of this, build instructions for dependencies should be self-contained if possible.

The second possibility is to use object libraries. Two problems: first, object libraries are only available for CMake v2.8.8 and greater. Last time I looked there were some conservative distributions which didn't have that. Second, handling of these is a bit awkward as we'd have to distinguish between system libraries and object libraries, as they are not added to `TARGET_LINK_LIBRARIES` but to `ADD_LIBRARY` as source files.

The third one is to have us create a custom target to merge static libraries. This isn't that hard to do, but obviously requires more platform-specific code here.

As said, I think all solutions suck in one way or another. So any hints would be most welcome.

**Comment by tiennou** [comment]
Looking through StackOverflow, maybe [this](https://stackoverflow.com/questions/28080641/how-to-make-static-imported-library-dependent-on-another-static-imported-library) can be helpful ?

- [IMPORTED_LINK_INTERFACE_LIBRARIES](https://cmake.org/cmake/help/v3.0/prop_tgt/IMPORTED_LINK_INTERFACE_LIBRARIES.html)
- [INTERFACE_LINK_LIBRARIES](https://cmake.org/cmake/help/v3.3/prop_tgt/INTERFACE_LINK_LIBRARIES.html)

**Comment by pks-t** [comment]
Unfortunately I don't think so. These functions seem to me like adding dependencies which are handled outside of CMake, which is not really what we want. First, our bundled deps are not outside of CMake but are built by ourselves. And second, this only adds a dependency without actually linking in the imported library.

**Comment by lunij** [comment]
Tried @carlosmn approach using `USE_EXT_HTTP_PARSER:BOOL=OFF` but it didn't work for me. Symbols remain undefined:
```bash
% nm libgit2.a | grep http_parser 
                 U http_parser_parse_url
                 U http_parser_execute
                 U http_parser_init
```
The interesting thing about this, on my Mac with **macOS Sierra** and **CMake 3.9.2** I get the following with `USE_EXT_HTTP_PARSER:BOOL=ON`:
```bash
% nm libgit2.a | grep http_parser
                 U _http_parser_parse_url
                 U _http_parser_execute
                 U _http_parser_init
libgit2.a(http_parser.c.o):
0000000000000000 T _http_parser_execute
0000000000004be0 T _http_parser_init
0000000000004d70 T _http_parser_parse_url
00000000000052f0 T _http_parser_pause
```
Only on my Mac with **macOS High Sierra** and **CMake 3.9.20170917-g214d0** it does not work.

**Comment by pks-t** [comment]
Could you please test whether #4339 fixes your issue? It's not yet been merged, but it did fix the issue for me.
