### ISSUE TITLE
Winhttp how to support proxy service by C, I don't known how to parameter input？

### ISSUE THREAD

**Issue by fuhao92** [libgit2/libgit2#4337]
You are opening a _bug report_ against the libgit2 project.  If you have a
question about an API or usage, please ask on StackOverflow:
http://stackoverflow.com/questions/tagged/libgit2.  Please fill out the
reproduction steps (below) and delete this introductory paragraph.  Thanks!

**Comment by fuhao92** [comment]
I only known comply proxy service by :error = git_remote_connect(remote, GIT_DIRECTION_FETCH, &callbacks, NULL, NULL); but, the fourth parameter is a Structure, so, I don't to comply it !

**Comment by ethomson** [comment]
Hi!  This looks more like a question of how to use the API than a bug report.  We would prefer you to ask this on StackOverflow:  http://stackoverflow.com/questions/tagged/libgit2

It's much easier to get help there, and the questions will persist and help everybody who uses libgit2 in the future, as opposed to a GitHub issue, which will get closed.  We'll try to help you out if you ask it over there.  Thanks!
