### ISSUE TITLE
Switching from libssh2 to libssh.

### ISSUE THREAD

**Issue by mothacehe** [libgit2/libgit2#4338]
libssh2 does not provide the ability to parse ssh configuration files. As this is a really important feature when dealing with ssh connections, would it be an option to switch to libssh ?

libssh allows configuration file parsing and seem to have a more complete API.

**Comment by ethomson** [comment]
I've used libssh in the past and been reasonably pleased with it.  I think that adding a libssh backend would be useful.

We'd welcome a pull request, but this is not something that I have on my radar.  Is this something that you would like to contribute?

**Comment by mothacehe** [comment]
Sure, I'll start working on a libssh transport, and propose a pull request if everything goes fine !

**Comment by carlosmn** [comment]
One thing libssh does not do is work with Windows' cryptography. You need to build openssl or libgcrypt on there, which reduces its usefulness as something to be shipped in a library that aims for for its code to work cross-platform.

I would recommend implementing the transport on its own, at least at first. There is nothing special about the transports in this code base, and it'll likely be less of a hassle if you don't have to get libgit2's build system to search for two kinds of ssh libraries.

**Comment by mothacehe** [comment]
@carlosmn, what do you mean by "implement the transport on it's own" ? I have a nearly functional transport/ssh-libssh.c based on libssh who shares 90% of it's code with the existing ssh.c based on libssh2.

Shall I let both ssh transports co-exist and add a compile-time option to select one of them ? Or maybe a run-time option ?

An other option would be to select the libssh2 based transport on windows, the libssh based transport on linux and to  factorize the code between those two transports in a ssh_common.c ?

**Comment by jacquesg** [comment]
I would like to see this as a compile-time option. In many cases people are quite happy with using libssh2 and as such switching to libssh is not needed or even undesired especially when dealing with cross-platform systems: If you have to use libssh2 on Windows for example, it makes sense to also use libssh2 on Linux.

**Comment by ethomson** [comment]
> Shall I let both ssh transports co-exist and add a compile-time option to select one of them ?

_Removing_ libssh2 and replacing it with libssh support is probably not something that we want to do.

> Or maybe a run-time option ?

Having to compile against both is almost certainly not something that anybody wants to do.

If we're going to support libssh, then doing so at compile time seems like the only reasonable choice.

**Comment by carlosmn** [comment]
>what do you mean by "implement the transport on it's own" ? 

I mean that there's nothing special about the network transports that exist in this repository. If you want to use a different one, you can have one aded at run-time with no difference to how libgit2 handles it.

**Comment by DemiMarie** [comment]
Libssh2 doesn’t support elliptic curve host keys.

**Comment by ethomson** [comment]
We haven’t seen much progress here after 12 months; closing this.

**Comment by ehmry** [comment]
I have a patch to replace libssh2 at 40cbc7be6535b3127feb89938e460882ec1be7ca. Libgit2 is actually transitively linked to libssh thru libCURL as it is now.

I have no reason to continue working on this issue because libgit2 is full of `mmap` performance hacks are not portable to my platform.

**Comment by cryptomilk** [comment]
In contrary to libssh2, libssh implements:

* State of the art crypto
* Kerberos support (GSSAPI auth)
* Parses openssh config files
* etc.

**Comment by ethomson** [comment]
> In contrary to libssh2, libssh implements:
> ...

I would be happy to see libgit2 support libssh, however this is not a priority for me.  Pull requests would be very welcome.

**Comment by eaigner** [comment]
I'm currently running into this problem. Creating a custom transport for that seems a bit excessive.
Since I found no option to just modify the URL on-the-fly, this would probably mean I have to duplicate the entire transport impl, because static methods like `git_smart__connect` are not accessible from the outside.

Isn't there a quicker method to emulate this?

I'm currently looking up the SSH hosts myself and tried to create an anonymous remote on the fly with the resolved URL. Unfortunately fetching and pushing to that anonymous remote won't update the correspoding named remote.

**Comment by eaigner** [comment]
Probably better to synthesize config records using `url.*.insteadOf`, since it seems libgit2 does respect this setting.

**Comment by bergkvist** [comment]
I use ProxyCommand in my `.ssh/config` for accessing private repos behind bastion servers. And assuming libssh supports using this config file, including ProxyCommand, I would also love to see the switch happen

**Comment by ethomson** [comment]
We have the ability to call out to the `ssh` command-line now. You can set `USE_SSH=exec` as a cmake option. I expect that this will be useful for many people, and I'd love feedback on whether this resolves some peoples problems or not.

That said, I'd still be happy to consider an option to use libssh. libssh2 is a disappointment. But it's not something that I want to invest time into.
