### ISSUE TITLE
proxy service set failed , return request failed！

### ISSUE THREAD

**Issue by fuhao92** [libgit2/libgit2#4340]
You are opening a _bug report_ against the libgit2 project.  If you have a
question about an API or usage, please ask on StackOverflow:
http://stackoverflow.com/questions/tagged/libgit2.  Please fill out the
reproduction steps (below) and delete this introductory paragraph.  Thanks!

**Comment by fuhao92** [comment]
then I use tortoisegit set proxy , then, I can see the file , .gitconfig save the proxy url and clone data succed, But, libgit2 still return failed, If libgit2 can read the .gitconfig, I think remote connect should succed, how can I do it? thinks for help me !

**Comment by appeonwavish** [comment]
int _tmain(int argc, _TCHAR* argv[])  //_TCHAR  char
{
  git_libgit2_init();
  git_clone_options clone_opts = GIT_CLONE_OPTIONS_INIT;
  clone_opts.fetch_opts.proxy_opts.type = GIT_PROXY_SPECIFIED;
	
  clone_opts.fetch_opts.proxy_opts.url = "http://192.0.0.8:88";
	
  clone_opts.fetch_opts.callbacks.certificate_check = succeed_certificate_check;
	
  clone_opts.fetch_opts.callbacks.credentials = proxy_creds;
	
  clone_opts.fetch_opts.callbacks.payload = &pd;
  int error = git_clone(&cloned_repo, "https://github.com/appeonwavish/tttt", path, &clone_opts);
  return 0; 
}
**This is my test dome to clone data, and set proxy service according to examples! But, it's failded! Can't the cause,help for gods!**

**Comment by fuhao92** [comment]
I according to libgit2/test/online/clone.c , can solve the problem,you can test !
