### ISSUE TITLE
I would like to upload data to the server by git_remote_push (),than, it can create a new directory in the server to save my data.

### ISSUE THREAD

**Issue by fuhao92** [libgit2/libgit2#4341]
You are opening a _bug report_ against the libgit2 project.  If you have a
question about an API or usage, please ask on StackOverflow:
http://stackoverflow.com/questions/tagged/libgit2.  Please fill out the
reproduction steps (below) and delete this introductory paragraph.  Thanks!

**Comment by ethomson** [comment]
I'm afraid that I'm not sure entirely what you're asking, but as the template and this issue suggest, we reserve issues for _bug reports_.  I suggest you open a question on [StackOverflow](https://stackoverflow.com/questions/tagged/libgit2) where we can help you out.  Thanks!
