### ISSUE TITLE
parallel fetches on mac return SecureTransport error

### ISSUE THREAD

**Issue by ankurmittal** [libgit2/libgit2#4350]
You are opening a _bug report_ against the libgit2 project.  If you have a
question about an API or usage, please ask on StackOverflow:
http://stackoverflow.com/questions/tagged/libgit2.  Please fill out the
reproduction steps (below) and delete this introductory paragraph.  Thanks!

### Reproduction steps
Run multiple fetches in parallel. I am hitting this error with more than 10 parallel fetches and it is consistent on 25 parallel fetches. It doesn't happen on 2-3 parallel fetches.

### Expected behavior
Should not throw error
### Actual behavior
Throwing error
 SecureTransport error: connection closed via error
or 
unexpected return value from ssl handshake -9806

### Version of libgit2 (release number or SHA1)
libgit2-v0.26.0, git2go-v26

### Operating system(s) tested
Mac

Additional info
We made a slight change on how gitgo it is compiled for our system but I don't think that should cause this error. Please see https://fuchsia.googlesource.com/third_party/git2go/+/4085ea05708d56909c787d12b1157754d33cd0ea%5E%21/#F1 for the change

**Comment by pks-t** [comment]
Are you running these concurrent fetches against a single repository? If so, then I'm afraid this is officially not supported by us. The [THREADING.md](https://github.com/libgit2/libgit2/blob/master/THREADING.md) has more details on this, but this here is the excerpt that applies to your case:

> Use an object from a single thread at a time. Most data structures do not guard against concurrent access themselves. This is because they are rarely used in isolation and it makes more sense to synchronize access via a larger lock or similar

**Comment by ankurmittal** [comment]
no they are all separate repositories so a separate object for each just in parallel.

The code:
fetch function: https://fuchsia.googlesource.com/jiri/+/acbc22129f5df0c4cb3881651bb4f7f74e29f531/project/project.go#1330

function to fetch in parallel: https://fuchsia.googlesource.com/jiri/+/acbc22129f5df0c4cb3881651bb4f7f74e29f531/project/project.go#1958

git2go wrapper: https://fuchsia.googlesource.com/jiri/+/acbc22129f5df0c4cb3881651bb4f7f74e29f531/git/git.go#94

**Comment by ethomson** [comment]
🤷‍♂  I've not seen additional reports of this.  I'm going to close it on the assumption that it's been resolved.
