### ISSUE TITLE
fetch on arm64 returns user cancelled certificate check

### ISSUE THREAD

**Issue by ankurmittal** [libgit2/libgit2#4351]
### Reproduction steps
simple fetch on arm64 machine should replicate this issue. git fetch doesn't return this error.

### Expected behavior
No error

### Actual behavior
Getting "user cancelled certificate check"

### Version of libgit2 (release number or SHA1)
v0.26.0
### Operating system(s) tested
ubuntu

**Comment by ankurmittal** [comment]
I am also using git2go v26

**Comment by ethomson** [comment]
How did you build libgit2?  What ssl libraries did you compile against?  What compiler options?  Or are you using the version in ubuntu?  Does this work on other platforms?

**Comment by ankurmittal** [comment]
We are using boringssl and we debugged a little and boringssl is searching for /etc/ssl/cert.perm which it cannot find. Not sure if it is boringssl or libgit2. It does work fine on ubuntu x_86_64 and no such error on darwin

This is how we build it
https://fuchsia.googlesource.com/jiri/+/master/scripts/build.sh

**Comment by ethomson** [comment]
Sounds to me like it can't find the system certs, and so it is prompting you whether or not to accept an untrusted certificate.  If you install the system certs correctly so that your server has a trust chain, does this succeed?  If you set up a certificate handler and accept the cert does this succeed?

**Comment by ankurmittal** [comment]
If I setup a certificate handler and accept the cert it does work. but i am not sure why git will not report that certificate is untrusted and libgit2 will

**Comment by ethomson** [comment]
Is Git also linked to boringssl?  What cert stores is it looking for (and finding)?  Have you strace'd it?

**Comment by ankurmittal** [comment]
no i don't git git uses boringssl thats why this might not be boringssl bug unless libgit has a function to validate certificates. strace doesn't give any actionable output, i will try to debug boringssl when i get time

**Comment by mankash** [comment]
@ankurmittal - Has there been any progress in your debug. I'm interested in building libgit2 with boringssl, given it's status as the library of choice on Android. 

As a side-note, /etc/ssl cannot be read for certificate validation  from apps on Android, unless they use the system crypto/transport. If you've statically linked your app against an ssl library, and if your target is Fuchsia, are you likely hitting the same issue? 

Also, libgit2 does allow you to ignore certificate validation error via a custom callback:

```C
git_remote_callbacks callbacks = {0};
...
...
callbacks.certificate_check = mycertificate_check;
...

```


In your mycertificate_check function, you can choose to ignore the certificate validation failure, and proceed with the network operation. That'll at least rule out other issues, if any.

**Comment by ankurmittal** [comment]
> @ankurmittal - Has there been any progress in your debug. I'm interested in building libgit2 with boringssl, given it's status as the library of choice on Android.

No i reverted back to old version. I am using commit 25a4b97b1bd0b5316deb77866756a3db772e08a2
> 
> As a side-note, /etc/ssl cannot be read for certificate validation from apps on Android, unless they use the system crypto/transport. If you've statically linked your app against an ssl library, and if your target is Fuchsia, are you likely hitting the same issue?

We do not build jiri for fuchsia yet, so don't know
> 
> Also, libgit2 does allow you to ignore certificate validation error via a custom callback:
> 
> git_remote_callbacks callbacks = {0};
> ...
> ...
> callbacks.certificate_check = mycertificate_check;
> ...
> In your mycertificate_check function, you can choose to ignore the certificate validation failure, and proceed with the network operation. That'll at least rule out other issues, if any.

we would be soon switching to go-git so don't want to spend time on this

**Comment by ethomson** [comment]
Not sure where to go with this; without more details, I'm closing this.  Please open a new issue if you have issues with boringssl.
