### ISSUE TITLE
Config iterators do not retain order

### ISSUE THREAD

**Issue by omus** [libgit2/libgit2#4361]
The `git_config_iterator` does not seem to maintain the ordering of the configuration files. Given the following configuration file:

```
[credential]
    helper = !echo first
[credential "https://mygithost"]
    helper = ""
[credential]
    helper = !echo second
```
Iterating through this configuration with `git_config_iterator_new` produces results which are out of order. Note that the [ordering here does matter](https://git-scm.com/docs/gitcredentials#gitcredentials-helper).

LibGit2 version v0.26.0 (15e119375018fba121cf58e02a9f17fe22df0df8)

**Comment by pks-t** [comment]
Thanks for the bug report. I've found the same issue just recently as part of another PR, and I hope to get around to this issue soon-ish. This bug is really unfortunate and completely breaks config iterators in certain scenarios.

**Comment by carlosmn** [comment]
Are you referring to the order of the `credential.helper` multivar, or the ordering between `credential.helper` and `credential.https://mygithost.helper`? The former is the one that's talked about by the credentials-helper documentation.

What is the effect that you expect from the configuration file you presented?  Based on my reading of the documentation, a tool which wishes to use a credential  helper for `mygithost` would first check the specific helper for the URL. It gets unset because it's an empty string, so it would fall back to looking through the `credential.helper` multivar, and it would first find `!echo first` and then `!echo second`.

The ordering of the multivar is defined by the config spec, and we do retain it. The ordering between different variables isn't really defined, though it makes sense that they'd go out in the same order as they went in.

**Comment by omus** [comment]
Based upon interactions with the git command line it appears that the helpers are read in the order they are in the configuration file applying URL specific helpers and general helpers as they are read. 

For example given the following in the `~/.gitconfig`:
```
[credential]
	helper = store --file ~/.git-demo1
[credential "https://mygithost"]
	helper = ""
[credential]
	helper = store --file ~/.git-demo2
```

```bash
$ git credential approve  # Writes to both .git-demo1 and .git-demo2
protocol=https
host=github.com
username=git
password=pass

$ cat ~/.git-demo1
https://git:pass@github.com

$ cat ~/.git-demo2
https://git:pass@github.com

$ git credential approve  # Writes to only .git-demo2
protocol=https
host=mygithost
username=foo
password=bar

$ cat ~/.git-demo1
https://git:pass@github.com

$ cat ~/.git-demo2
https://foo:bar@mygithost
https://git:pass@github.com
```

**Comment by carlosmn** [comment]
You do have to go through them in the order they different values for a particular key are defined. That's what I said. But you don't a generic iterator over the config, you want to look up the multivar you're interested in and go through the values in there, which retain order as demanded by the configuration format.

**Comment by omus** [comment]
I'm unclear on what your suggesting with using a multivar. Re-using the [example from above](https://github.com/libgit2/libgit2/issues/4361#issuecomment-340768057) I'm currently using
```
git_config_iterator_glob_new(&iter, cfg, "credential.*\.helper")
```
which returns helpers out of order:
```
"credential.https://mygithost.helper" = ""
"credential.helper = "store --file ~/.git-demo1"
"credential.helper" = "store --file ~/.git-demo2"
```
I believe you're suggesting I use the multivar iterator which would look something like:
```
git_config_multivar_iterator_new(&iter, cfg, "credential.https://mygithost.helper", NULL)
...
git_config_multivar_iterator_new(&iter, cfg, "credential.helper", NULL)
```
Unfortunately this approach doesn't work as I wish to retain the relative ordering between `"credential.https://mygithost.helper"` and `"credential.helper"`.

Feel free to correct me if I misunderstood your suggestion.

**Comment by carlosmn** [comment]
Is this relative ordering of different keys something git does on purpose? The documentation doesn't suggest this is the case. It only speaks about the context-less `credential.helper` and it speaks of each with and without context as things that match differently.

A cursory look into git's `t/t0300-credentials.sh` doesn't seem to show how they expect these to interact.

**Comment by omus** [comment]
I believe the relative ordering of different keys is done on purpose but unfortunately it appears to be undocumented.

**Comment by omus** [comment]
Is there a specific reason LibGit2 does not iterate through the configuration in the order in which it was written?

**Comment by pks-t** [comment]
If you ask me, this is simply an implementation shortcoming. In my opinion, we should support iterating through keys in the order they were parsed from the file, but right now there's only a sinlge map which keeps track of all items. In addition to that map, we'd also require a linked list that retains order.

I've started tackling that issue, but the code reminded me quite fast that it's very hard to grasp. I'll revisit the issue as soon as #4310 is done and merged, as that splits up the config file and config parsing logic. As a result, it should get easier to fix the ordering issue.

**Comment by pks-t** [comment]
Finally kept my promise, #4525 improves the implementation

**Comment by carlosmn** [comment]
Is this issue fixed by #4525 then?

**Comment by pks-t** [comment]
It is, thanks! Closing the issue

**Comment by omus** [comment]
Looks like this is still an issue.

**Comment by ethomson** [comment]
@omus That's correct, it will be in the upcoming release.  I'd like to see this finalized this week or next.
