### ISSUE TITLE
Successful cloning a repo using libgit2 compiled to JavaScript with Emscripten

### ISSUE THREAD

**Issue by vadimkantorov** [libgit2/libgit2#4376]
@petersalomonsen accomplished the feat in this [issue](https://github.com/kripken/emscripten/issues/4902)

Very few edits to libgit2 were [required](https://github.com/libgit2/libgit2/compare/master...fintechneo:master):
1. chmod in `indexer.c`, `filebuf.c` to explicitly give write permissions on the default read-only Emscripten's file system
2. pwrite in `indexer.c` to explicitly give write permissions to a mmap which is also default read-only in Emscripten
3. disabling http parsing of the response in `transports/http.c`
4. disabling writing http headers in write_chunk in `transports/http.c`

Dropping this here in case anyone wants to prepare these for a proper feature at some point.

**Comment by petersalomonsen** [comment]
What would be required in order to merge the mentioned edits back to the upstream libgit2 repository?

**Comment by ethomson** [comment]
Speaking generally, I'm interested in having emscripten support.  I think that would be neat.

As is noted in https://github.com/kripken/emscripten/issues/4902, that needs to be cleaned up.  eg:

1. Don't change the cmake defaults.  Instead, in your build script, turn features on/off as you need them.  (eg, `cmake -DTHREADSAFE=OFF`).
2. Have you tried with the mmap emulation?  (eg, define `NO_MMAP`)
3. I also would like to see a custom transport that uses emscripten

**Comment by petersalomonsen** [comment]
Thanks for the pointers @ethomson 

Will have a look at it and see what I can do.

Regarding 3, I changed to registering a tls stream for emscripten like this:

`git_stream_register_tls(git_open_emscripten_stream);`

But you'd rather prefer a full transport? Currently the http transport is used and works fine - just had to disable some lines of code. E.g. the http parser is not needed with emscripten as we already have one in the browser. Maybe better to introduce a configuration switch to turn off the http parser?

**Comment by CMCDragonkai** [comment]
So the reason why there are those http issues is because the browser already performs some parsing?

What happens if the same emscripten compiled output is run inside node, does it has the same problems? I intend to run libgit2 via emscripten on node primarily.

**Comment by CMCDragonkai** [comment]
@ethomson The mmap emulation denies the use of `MAP_SHARED` (https://github.com/libgit2/libgit2/blob/28c89507d1b9e1013e690adc1ef16f30bd3fa4f5/src/posix.c#L245-L248) is there any part of libgit2 that relies on `MAP_SHARED`?

**Comment by petersalomonsen** [comment]
@CMCDragonkai Node also has a builtin http parser ( https://nodejs.org/api/http.html ) so you would also want to bypass the libgit2 http parser when running in Node. Would have to adjust to the Node http API, but the concept is more or less the same as in the browser.

**Comment by petersalomonsen** [comment]
1. Reverted CMAKE defaults and now using -DTHREADSAFE=OFF etc.
2. Tested using NO_MMAP, but results in:

`ERROR 2: trying to map shared-writeable:`

Also tried to merge in the latest from libgit2 upstream but for some reason I haven't figured out yet, zlib isn't build. Any idea?

@CMCDragonkai @ethomson @vadimkantorov

**Comment by CMCDragonkai** [comment]
I tried to figure out what would be the quickest way to create a soft-MMU for emscripten, and my experiments lead me to create https://github.com/MatrixAI/js-permaproxy It isn't impossible to replace/extend Emscripten's heap architecture with a soft-MMU  based on ES6 proxies on Uint8Arrays that would properly emulate `MAP_SHARED`, but proxies are not very performant, I think possibly 2 orders of magnitude slower on my Chrome browser. There's also the issue that Uint8Arrays are just views, while ArrayBuffer is the actual data, and there's no way to Proxy mutations to ArrayBuffer. I think instead one should build a single "VirtualMemory" construct based on DataView instead, and rework all of the typed array accesses to be based on a single DataView.

**Comment by petersalomonsen** [comment]
Did some adjustments and added a build option so that it shouldn't interfere with existing code/other target platforms. For now the NO_MMAP is not usable, so leaving my hack in there - but at least it's only active when using the emscripten build option.

Hope you can use this @ethomson , and let me know if further adjustments are required.

See pull request here:

https://github.com/libgit2/libgit2/pull/4400

**Comment by petersalomonsen** [comment]
Now using webassembly and webworkers. A simple video demo can be seen here: https://youtu.be/rcBluzpUWE4

Also started initial work on a simple file-explorer frontend: https://github.com/fintechneo/angular-git-filebrowser

(which is the same as shown in the video)

**Comment by vadimkantorov** [comment]
With a proxy to bypass CORS?

**Comment by petersalomonsen** [comment]
@vadimkantorov Yes there's a proxy in that file-explorer project, so you can test it directly from there.

**Comment by petersalomonsen** [comment]
Demo of creating files and folders and pushing to github: https://youtu.be/qnCucFguDwE

**Comment by sbeaupre** [comment]
@ethomson did you have time to evaluate the PR from @petersalomonsen above? I see that some CI checks have failed...

**Comment by petersalomonsen** [comment]
@CMCDragonkai I've added a http transport for nodejs now. Example of cloning a repo is here:

https://github.com/fintechneo/libgit2/blob/emscripten_nodejs_http_transport/emscripten_hacks/jstests/nodejsclone.js

The stream code is here:

https://github.com/fintechneo/libgit2/blob/emscripten_nodejs_http_transport/src/streams/emscripten_nodejs.c

I'm creating a child process for the http request with `spawnSync` to be able to make the request synchronously.

**Comment by petersalomonsen** [comment]
> @ethomson did you have time to evaluate the PR from @petersalomonsen above? I see that some CI checks have failed...

@sbeaupre The CI checks pass just fine now: https://github.com/libgit2/libgit2/pull/4400 ( has been working for a while now ).

**Comment by petersalomonsen** [comment]
Published some npm packages with webassembly binaries of libgit2 today:

https://www.npmjs.com/package/libgit2.js

Exposed functions are limited to what can be found here: https://github.com/fintechneo/libgit2/blob/master/emscripten_hacks/jslib.c

**Comment by cspotcode** [comment]
Can this be combined with nodegit?

Ideally I would like to use a node git library that does not have any native components, because this makes it more maintainable.  Right now the latest nodegit from npm doesn't build against node 12.  Plus, since it requires recompiling, it makes deployment a little trickier.  At work I'm trying to webpack tools into a single JS file with a shebang, paired with a statically linked node binary, but I can't do that when nodegit is in the mix.

Could nodegit use this precompiled WASM binary of libgit2 under the hood?

**Comment by petersalomonsen** [comment]
Not out of the box, you'd have to change the exposed API of the wasm library to match that of nodegit, or at least the functions your application is using.

That said, if you know a little C, should be easy to tweak the API exposed to JS in this file https://github.com/fintechneo/libgit2/blob/master/emscripten_hacks/jslib.c to match your application. See the methods marked with `EMSCRIPTEN_KEEPALIVE` which is the way you can expose C methods to JS.

**Comment by ethomson** [comment]
[wasm-git](https://github.com/petersalomonsen/wasm-git) is the answer.  Thanks, @petersalomonsen!
