### ISSUE TITLE
git_remote_push how to read git-credentials file? than, I how to read first time input username or password?

### ISSUE THREAD

**Issue by fuhao92** [libgit2/libgit2#4379]
You are opening a _bug report_ against the libgit2 project.  If you have a
question about an API or usage, please ask on StackOverflow:
http://stackoverflow.com/questions/tagged/libgit2.  Please fill out the
reproduction steps (below) and delete this introductory paragraph.  Thanks!

**Comment by ethomson** [comment]
Hi - as the template on our issue (that you've posted as the issue itself) suggests, we would encourage you to post a question on [StackOverflow](http://stackoverflow.com/questions/tagged/libgit2), tagged with the [libgit2 tag](http://stackoverflow.com/questions/tagged/libgit2).

Support on StackOverflow ensures that it's searchable by all users, and persists indefinitely.  We reserve the issue tracker for bug reports.  Thanks!
