### ISSUE TITLE
No longer possible to add libgit2 to another cmake project with add_subdirectory

### ISSUE THREAD

**Issue by hackhaslam** [libgit2/libgit2#4381]
Since #4282 (72f27cb68be553ba0c8bd99b3c83e49487d1c87d in particular) it's no longer possible to add libgit2 to another cmake project with add_subdirectory. The uses of `CMAKE_CURRENT_SOURCE_DIR` changed to `CMAKE_SOURCE_DIR` which only works if libgit2 is the root project. I'd suggest that cmake list files in subdirectories that need to refer to the root of the libgit2 source tree should use [libgit2_SOURCE_DIR](https://cmake.org/cmake/help/latest/variable/PROJECT-NAME_SOURCE_DIR.html) instead.

**Comment by pks-t** [comment]
Thanks for the bug report! I've simply assumed that `CMAKE_SOURCE_DIR` and `CMAKE_BINARY_DIR` would be project-relative, but I should've checked that assumption. I've created #4382 to fix that issue.

**Comment by ethomson** [comment]
Fixed via #4382

**Comment by hackhaslam** [comment]
Thanks! That works for me.
