### ISSUE TITLE
hi!  How can i get status information for the specified directory Similar functionality as "git status."

### ISSUE THREAD

**Issue by fuhao92** [libgit2/libgit2#4399]
You are opening a _bug report_ against the libgit2 project.  If you have a
question about an API or usage, please ask on StackOverflow:
http://stackoverflow.com/questions/tagged/libgit2.  Please fill out the
reproduction steps (below) and delete this introductory paragraph.  Thanks!

**Comment by ethomson** [comment]
Hi!  Thanks for the question, and sorry that you're having trouble using libgit2.

We use the issue tracker for issues (bugs and features) - we use [StackOverflow](http://stackoverflow.com/questions/tagged/libgit2) for questions and for help with the API.  That lets your questions get much more visibility, persist longer and be much more searchable.  It lets us help you better, and helps the people who have the same question after you.

So I'm going to close this, and I'd encourage you to ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/libgit2) (making sure to add the [libgit2](http://stackoverflow.com/questions/tagged/libgit2) tag!)
