### ISSUE TITLE
Improve build error reporting

### ISSUE THREAD

**Issue by ethomson** [libgit2/libgit2#4413]
We should fail the builds:

1. Whenever valgrind pops up warnings.  (There are known warning points - eg, the TLS libraries and our (intentional) large malloc test which we should not be executing, obviously.)
2. Whenever we have memory leaks on Windows.

This would keep us from having to go through and deal with these every `<n>` months, because that's terrible.

**Comment by tiennou** [comment]
Nowadays we have an Über-CI setup, working as intended 😉.
