### ISSUE TITLE
Trouble linking to manually compiled libssh2

### ISSUE THREAD

**Issue by theredcat** [libgit2/libgit2#4419]
Hi I'm currently writing a little script to build a software called Fritzing using sources for library when possible.

The problem is that I'm not able to use the version of libssh2 that I've compilled

### Reproduction steps
Clone https://github.com/theredcat/fritzing-build.git
Run build.sh

### Expected behavior
Cmake for libgit2 should detect libssh2

### Actual behavior
Cmake for libgit2 don't detect libssh2

### Version of libgit2 (release number or SHA1)
v0.23.4

### Operating system(s) tested
Debian Stretch

**Comment by ethomson** [comment]
Have you tried compiling with `--trace` or `--debug-output` to see perhaps where it's looking for your ssh libraries?

**Comment by theredcat** [comment]
Hello,

I've managed to solve my problem using a good old strace :)

The problem was the var PKG_CONFIG_PATH wasn't defined.
`PKG_CONFIG_PATH=$rootpath/libssh2/lib/pkgconfig cmake .. -DCMAKE_INSTALL_PREFIX=$rootpath/libgit2` solved my problem
