### ISSUE TITLE
git_diff_hunk documentation has one-off field descriptions

### ISSUE THREAD

**Issue by brandonio21** [libgit2/libgit2#4441]
The documentation for `git_diff_hunk` has descriptions that are for the wrong fields. (Documentation found https://libgit2.github.com/libgit2/#HEAD/type/git_diff_hunk)

# Actual:
```
int | old_start

int | old_lines: Starting line number in old_file

int | new_start: Number of lines in old_file

int | new_lines: Starting line number in new_file

size_t | header_len: Number of lines in new_file

char [128] | header: Number of bytes in header text
```

# Expected:
```
int | old_start: Starting line number in old_file

int | old_lines: Number of lines in old_file

int | new_start: Starting line number in new_file

int | new_lines: Number of lines in new_file

size_t | header_len: Number of bytes in header text

char [128] | header: Header text, NUL-byte terminated
```

**Comment by ethomson** [comment]
Thanks for reporting this.

**Comment by pks-t** [comment]
I don't really get why this is though. We do it exactly as stated in https://www.stack.nl/~dimitri/doxygen/manual/docblocks.html, so I guess this is some incombatibility in Docurium? @carlosmn

**Comment by ethomson** [comment]
This appears to have been fixed - perhaps a transient bug in docurium?

**Comment by brandonio21** [comment]
Huh. You're right. Well, I suppose I'll consider the issue closed!
