### ISSUE TITLE
SSH: Pass hostkey to certificate check callback

### ISSUE THREAD

**Issue by aw32** [libgit2/libgit2#4452]
Feature request:
There is the certificate check callback for remote connections.
For the SSH certificate check `git_cert_hostkey` can only contain the MD5 and/or SHA1 hash of the hostkey as passed from libssh2. Since MD5 and SHA1 are not considered trustable anymore, it would be nice to receive the actual hostkey as returned by libssh2.
Would you consider this reasonable enough to accept a pull request?

**Comment by ethomson** [comment]
I'm not very familiar with libssh2, but if it's still another format that libssh2 uses, then this seems reasonable.  @carlosmn?

**Comment by carlosmn** [comment]
We provide these checksums as it's what libssh2 lets us have. It looks like they also provide the raw hostkey, but we do not currently have a mechanism for providing multiple forms of certificate.

**Comment by carlosmn** [comment]
It looks like this was added in #5307 and #5704
