### ISSUE TITLE
Release v0.27.0 & v0.26.1

### ISSUE THREAD

**Issue by carlosmn** [libgit2/libgit2#4465]
We're at that time again where we want to make a new release.

For the v0.27 series, codenamed "Stadtrandsiedlung"

- [x] Bump the versions in the headers
- [x] Make a release candidate
- [x] Plug any final leaks
- [x] Fix any last-minute issues
- [x] Make sure CHANGELOG reflects everything worth discussing
- [x] Update the version in CHANGELOG and the header
- [x] Produce a release candidate
- [x] Tag
- [x] Create maint/v0.27
- [ ] Update any bindings the core team works with

For v0.26.1

- [x] Select the changes we want to backport
- [x] Update maint/v0.26
- [x] Tag

**Comment by ethomson** [comment]
If we wanted to be really process-focused, either @carlosmn or myself could document the release process, since we've done it before, and we could validate those steps by letting @pks-t make sure the steps are well documented by actually doing the release.

**Comment by carlosmn** [comment]
I thought you had actually created a PR with a doc to document the release, or at least provide the checklist (which I've always just copied from the previous release) but I couldn't find it. Am I thinking of something else similar?

I think it's a good idea to have @pks-t do the release following written-down instructions (if he's up for it).

**Comment by pks-t** [comment]
As that was my idea initially I'm all for that. The PR you have in mind was probably #4404, which is only an issue.

I also think @ethomson's idea regarding tagging bugfix pull requests for future releases is very nice. Like this, we wouldn't have to crawl through all merged PRs at once and identify worthy ones.

**Comment by pks-t** [comment]
I've tagged possible backports for v0.26.1 with the "backport" label. Please have a look if some backports are missing or if you think some of them are not suitable.

**Comment by carlosmn** [comment]
I don't think we can backport #4408 as it changes a public struct. Anything which embeds that struct it would have a different size in .1.

**Comment by ethomson** [comment]
I tagged three issues that I am interested in merging for 0.27:

* #4542 : Sanitize the hunk header to ensure it contains UTF-8 valid data
* #4557 : Unescape special characters in SSH repo paths (and/or #4563)
* #4560 : Regcomp with LC_COLLATE

I'm a little on the fence about #4560, though, to be honest.  I feel like a more comprehensive fix may be an improvement, but including _this_ fix in #4560 may stem the bleeding a bit.

**Comment by pks-t** [comment]
I'd say to not include #4560. Most Linux/Unix based platforms provide `regcomp_l`, which makes the problem actually go away. Platforms not using that are e.g. musl-based Linux systems, which are really rare, or Windows-based systems. And on Windows I'd doubt anybody touches the locales at all. So not worth it, I guess.

While #4542 is rather uncontroversial, I doubt that fix is that important at all. This is really a very infrequent edge case where the last character in a context line needs to be a multi-byte character which would need to be split in half by the maximum context line length. And even if we get that wrong, all that happens is us displaying a weird character as the last line of the context line. So I think this is not an important fix, either.

#4557 sounds like it should be included, though.

**Comment by ethomson** [comment]
Released!
