### ISSUE TITLE
Test failures

### ISSUE THREAD

**Issue by rankr** [libgit2/libgit2#4469]
### Reproduction steps
Run tests in bulid directory, with command "ctest -V"
### Expected behavior
no test fail
### Actual behavior
The following tests FAILED:
	  1 - libgit2_clar (Failed)
some details:
1:   2) Failure:
1: diff::binary::delta [/Users/file4/libgit2-0.26.0/tests/diff/binary.c:53]
1:   String mismatch: expected != actual.ptr
### Version of libgit2 (release number or SHA1)
libgit2-0.26.0
### Operating system(s) tested
macOS 10.13.2 (17C88)
###some more info:
cmake version 3.10.1

**Comment by rankr** [comment]
If I test on the master branch, there's only one failure on test 1 with message 
" 1) Failure:
1: status::renames::precomposed_unicode_rename [/Users/file4/libgit2/tests/status/renames.c:74]
1:   expected->status != actual->status
1:   0080 != 0200
"

**Comment by ethomson** [comment]
Hi @rankr.  We have test failures on APFS filesystems.  Thanks for the report, I'll take a look when I have a moment.

**Comment by pks-t** [comment]
I'm closing this for now. It should be fixed by #4490 -- in case it was not fixed by that PR, feel free to re-open

**Comment by rankr** [comment]
I run tests on version 0.26.3 but it still fails.
The first failure info:
1: merge::driverFFFFFFFFFFFFatal error: a cleanup method raised an exception.  1) Failure:
1: checkout::binaryunicode::noautocrlf [/Users/apple/Downloads/libgit2-0.26.3/tests/checkout/binaryunicode.c:32]
1:   Function call failed: (git_checkout_tree(g_repo, (git_object *)tree, &opts))
1:   error -13 - 1 conflict prevents checkout

**Comment by rankr** [comment]
@ethomson

**Comment by pks-t** [comment]
As the issue for the failure was a wrong test, we didn't backport the fix to v0.26.3. It will only be included in v0.27.0, which is going to be released soon.

**Comment by rankr** [comment]
thank you
