### ISSUE TITLE
Request: Please consider publishing to conan.io

### ISSUE THREAD

**Issue by Phrohdoh** [libgit2/libgit2#4473]
Hello, libgit2 team / community / maintainers!

_Note: I am not affiliated with conan.io or JFrog in any way._

I am not a C developer by any means (I'm quite positive I would lose all of my limbs in a matter of minutes with C) which goes to show that I am also quite clueless regarding dependency management but from what I understand C (and C++) mostly consist of copying headers and implementation files of dependencies in-tree.

Given the above it is quite difficult, in my limited experience, to stay up to date (or even track which version of a library you are using).

It is my belief that more projects and developers (myself included of course) could benefit from the work put into libgit2 if it were easier to depend on in a trackable way.

This is where my request for you all (and if you decide to and I can help please let me know how!) to consider publishing libgit2 releases to [conan.io](https://conan.io/index.html) which markets itself as "Conan, the C / C++ Package Manager for Developers."

[`conan`](http://docs.conan.io/en/latest/getting_started.html) use is driven by the [`conanfile.txt`](http://docs.conan.io/en/latest/reference/conanfile_txt.html) which allows downstream projects to declare dependencies which the conan tool will resolve and build as specified in the manifest.

If the overhead of management and setup of publishing to conan.io outweighs the benefits then please note so and close this.

Thank you for your time!

**Edit**: Corrected a link.

**Comment by ethomson** [comment]
Hi @phrohdoh - thanks for the suggestion, we'll take a look at [conan](http://conan.io/)!

**Comment by impsnldavid** [comment]
I've had a go at an initial conan package recipe. 

https://github.com/impsnldavid/conan-libgit2
https://bintray.com/impsnldavid/public-conan/libgit2%3Aimpsnldavid

Having problems with libssh on Windows, but builds without this seem OK. Would be grateful for testers on other OS's.

**Comment by memsharded** [comment]
There is also the original recipe from @p-brz: https://github.com/p-brz/libgit2-conan.git that was in the old conan.io server (now in read-only, to be deprecated conan-transit repository in bintray)
This recipe worked well prior to conan 1.0, but now might require updating it. 

The recipe from @impsnldavid looks very good, with little work it could be included in conan-center (though it first needs to have some of its dependencies that is still not in conan-center, but in the bincrafters repo, like libssh2)

**Comment by danimtb** [comment]
I have just opened a PR here https://github.com/impsnldavid/conan-libgit2/pull/1 to start moving this library to conan-center. Recipe looks quite good and with little work it would be ready!

@ethomson in case you want to add official support, please check @impsnldavid great work :)

**Comment by ovidiub13** [comment]
@danimtb @memsharded any progress on getting this in **conan-center** ?

**Comment by danimtb** [comment]
Seems there was no progress on this from any of the sides as no inclusion request for conan center was received 😞

**Comment by ovidiub13** [comment]
I think a recipe needs to be submitted to Conan for review, not the other way around.

Look: https://docs.conan.io/en/latest/uploading_packages/bintray/conan_center_guide.html#conan-center-flow

**Comment by Croydon** [comment]
@danimtb is part of the Conan team and can see if there are inclusion requests for specific packages, hence danimtb's comment 😄 

@impsnldavid doesn't seem to maintain the Conan recipe anymore, so someone else would not to step up

**Comment by ovidiub13** [comment]
I read `from` instead of `for` in his comment. Thank you for the wishlist issue.

**Comment by Croydon** [comment]
Thanks to @intelligide we have now a libgit2 recipe in the Conan Center Index 🎉 

https://github.com/conan-io/conan-center-index/pull/402

I guess this issue can be closed 😄

**Comment by ethomson** [comment]
Thanks @intelligide!
