### ISSUE TITLE
Recursive merge uses parents of virtual commits instead of virtual commit itself when finding merge base

### ISSUE THREAD

**Issue by tyrielv** [libgit2/libgit2#4479]
Recursive merge passes the parents of a virtual commit to git_merge_bases_many in place of the virtual commit. This produces a different result in some cases than git.exe.

### Reproduction steps
See attached repo [bases.zip](https://github.com/libgit2/libgit2/files/1640783/bases.zip)
Call git_merge_commits(), passing the commits for branchJ-1 and branchJ-2.

### Expected behavior
One conflict, in version.txt

### Actual behavior
Two conflicts, one in version.txt and one in targetfile.txt

### Version of libgit2 (release number or SHA1)
v0.26.0

### Operating system(s) tested
Windows 10

**Comment by tyrielv** [comment]
I have a proposed fix on my fork:
[https://github.com/libgit2/libgit2/pull/4487](https://github.com/libgit2/libgit2/pull/4487)

**Comment by ethomson** [comment]
Thanks for the great report and the fix.
