### ISSUE TITLE
After run setuid, Maybe cannot open $HOME/.gitconfig 

### ISSUE THREAD

**Issue by fcharlie** [libgit2/libgit2#4493]
After a base libgit2 program run setuid change user root to other user, The program maybe cannot open the global `.gitconfig` that matches its own permissions.

Because run `setuid`, not change `environ`.
 
https://github.com/libgit2/libgit2/blob/1560b5808e71af170d3a0c09f35cab7e973df5a5/src/sysdir.c#L42

See current user `HOME`, Please use:
```
getpwuid_r
```

**Comment by pks-t** [comment]
Thanks for your report! I've created a PR in #4499 to fix this issue.

**Comment by csware** [comment]
Should this issue be marked as fixed now?
