### ISSUE TITLE
docs: git_stash_save is not currently documented online

### ISSUE THREAD

**Issue by caesay** [libgit2/libgit2#4505]
The function `git_stash_save`

https://github.com/libgit2/libgit2/blob/2b8163b8b3861842ca09720ecb1b51c6dafc51b6/include/git2/stash.h#L66

Is not currently found in the online documentation [when searching for stash](https://libgit2.github.com/libgit2/#HEAD/search/stash) or when viewing the [stash function group](https://libgit2.github.com/libgit2/#HEAD/group/stash).

**Comment by rcjsuen** [comment]
Same as #4213.

**Comment by caesay** [comment]
Closing as duplicate of #4213
