### ISSUE TITLE
CRLF in repository and * text = auto results in incorrect modified state

### ISSUE THREAD

**Issue by tboby** [libgit2/libgit2#4526]
This seems to happen in repositories that have CRLF committed, once you turn `* text = auto` on.
This might be related to #3285 and #4098?

### Reproduction steps
1. Clone https://github.com/tboby/libgit2-crlf-repro
2. Perform the following actions in libgit (I'm using libgit2sharp, but I don't think that's related)
```
    var x = new Repository(@"D:\Git\libgit2-crlf-repro");
    LibGit2Sharp.Commands.Checkout(x, "origin/test");
    LibGit2Sharp.Commands.Checkout(x, "origin/master");
    LibGit2Sharp.Commands.Checkout(x, "origin/test");
    Console.WriteLine(x.RetrieveStatus().IsDirty);
    Console.WriteLine(x.RetrieveStatus().Modified.FirstOrDefault().State);
````
### Expected behavior
The status should be clean.

### Actual behavior
The status is dirty, with state "ModifiedInWorkdir".

The consequence of this is that libgit2 is unusable as many commands will abort when suddenly finding modified files. Merge, rebase, pull can all fail unexpectedly.

### Version of libgit2 (release number or SHA1)
Latest distributed with LibGit2Sharp, git2-15e1193.dll

### Operating system(s) tested
Windows 7 SP1, 64-bit

**Comment by csware** [comment]
Suppose this relates to issue #4098 and issue #2798

**Comment by L4ZZA** [comment]
This happens very frequently on GitKraken... Especially when switching between branches. 
Very disrupting.

**Comment by ethomson** [comment]
We've updated the CRLF handling, this should no longer be an issue (assuming that your `.gitattributes` settings match what you have checked in.  If not, please make sure that you have `git add --renormalize .`)
