### ISSUE TITLE
Configure WinHttp to use TLS 1.2 on windows 7

### ISSUE THREAD

**Issue by matklad** [libgit2/libgit2#4546]
Hi! `libgit2` uses `WinHttp` internally and on Windows 7, Windows Server 2018 and Windows Server 2012, the `WinHttp` API will **not** use TLS 1.2 by default. This recently became a problem, because GitHub disabled support for older TLS 1.0([announcement](https://github.com/blog/2507-weak-cryptographic-standards-removed)), which rendered Cargo unusable on Windows 7 ([upstream issue](https://github.com/rust-lang/cargo/issues/5066)).

To enable TLS 1.2 support on windows 7, I believe both of these two things should happen:

1) [This update](https://support.microsoft.com/en-us/help/3140245/update-to-enable-tls-1-1-and-tls-1-2-as-a-default-secure-protocols-in) must be installed. 
2) `WinHttp` API must be explicitly configured to allow TLS 1.2.

There are two ways to configure `WinHttp` to use TLS 1.2: a user may set a specific registry key (described at the end of [update description](https://support.microsoft.com/en-us/help/3140245/update-to-enable-tls-1-1-and-tls-1-2-as-a-default-secure-protocols-in)), or the application may set `WINHTTP_OPTION_SECURE_PROTOCOLS` option of `WinHttp` to `WINHTTP_FLAG_SECURE_PROTOCOL_TLS1_2`. The option flags are described [here](https://msdn.microsoft.com/en-us/library/windows/desktop/aa384066(v=vs.85).aspx).

So it seems to me if one adds 

```C
unsigned long protocols = 
	WINHTTP_FLAG_SECURE_PROTOCOL_ALL | 
	WINHTTP_FLAG_SECURE_PROTOCOL_TLS1_1 | 
	WINHTTP_FLAG_SECURE_PROTOCOL_TLS1_2;

// TLS1_1 and TLS1_2 might not be supported on old unpatched windows,
// so ignore error here
WinHttpSetOption(s->request,
	WINHTTP_OPTION_SECURE_PROTOCOLS,
	&protocols,
	sizeof(peerdist));
```

over [here](https://github.com/libgit2/libgit2/blob/408b16c1b06526f509fdb8997818d648d4d1ea1e/src/transports/winhttp.c#L496), than libgit2 would just work on windows 7, without the need to tweak the register. 

I am not sure if it is a good idea to make this change though, because sticking to OS defaults seems like a more reasonable option, in the ideal world :)

**Comment by ethomson** [comment]
Yes, I think that your suggestion would enable TLS 1.2.

> sticking to OS defaults seems like a more reasonable option, in the ideal world :)

Yeah.  I think that libgit2 shouldn't be in the business of forcing configurations over the operating system...  However, we probably want to enable application developers who are using libgit2 to enforce stricter TLS standards themselves.  So if cargo (or whomever) wants to enable TLS 1.2 in the cipher list, they can.

One possibility is that application developers can swap out the transport layer for full control, but that seems quite onerous here.

Let me give this a bit more thought about how the other SSL backends should play nicely with a setting like this.

**Comment by Diggsey** [comment]
> Yeah. I think that libgit2 shouldn't be in the business of forcing configurations over the operating system... 

Almost certainly the only reason that `WINHTTP_FLAG_SECURE_PROTOCOL_ALL` does not already include TLS 1.1 and 1.2 is for backwards compatibility, and best practice on windows *is* for newer features to be opted-in by new applications so that legacy applications are not affected.

Given that the rust ecosystem has its own mechanism for maintaining backwards compatibility while introducing breaking changes (semver and the cargo lock-file), I *would* expect libraries to explicitly opt in to newer supported features as they become available.

**Comment by ethomson** [comment]
> and best practice on windows is for newer features to be opted-in by new applications so that legacy applications are not affected.

I agree, that's why libgit2 will enable your new application to do that.

**Comment by plainionist** [comment]
any thoughts on timeline for fixing the issue?

**Comment by ethomson** [comment]
@matklad I think that your analysis is not quite correct.  If you install the easy fix update, that will set the necessary registry keys so that there are _no_ changes needed to applications.  If you install that update, there are no code changes necessary at all, TLS 1.2 will simply work.

Based on my testing, you can point your users at that fix immediately, and it should enable connections to GitHub.

The code changes you've suggested do not appear to have any affect.  If the easy fix has been applied, TLS 1.2 works independent of your proposed change.  If the easy fix has not been applied, TLS 1.2 does not work independent of your proposed change.

Is that not what you're seeing?

**Comment by ethomson** [comment]
@plainionist When we have a solution to the problem.  Do you have input on that?

**Comment by ethomson** [comment]
@matklad It appears that the request handle is not the correct place to set that option, it needs to be set [on the session handle](https://msdn.microsoft.com/en-us/library/windows/desktop/aa384066(v=vs.85).aspx).  So, when that is performed, then there is no need for a registry update or the installation of that easy fix that you reference.  There are several other issues here, but that's a good start.

**Comment by matklad** [comment]
> If you install the easy fix update, that will set the necessary registry keys so that there are no changes needed to applications.

@ethomson This is no the whole truth, I think. My understanding is that that are two parts to this update:

1) The "windows update", which is installed automatically via the usual update delivery mechanisms (so users quite probably have it installed). This update makes it possible to enable support for TLS 1.2, but, crucially, it does not actually *enables* it. 

2) The "easy fix", which is a separate executable which actually turns the switch on for TLS 1.2. This "easy fix" is not an update itself, so the use must **manually** download and launch it (and they need to have admin rights to do so)

Quoting the docs, 

>Note The hotfix installer doesn't add the DefaultSecureProtocols value. The administrator must manually add the entry after determining the override protocols. Or, you can install the "Easy fix" to add the entry automatically.


So, the problem indeed can be fixed without touching the code, but it requires manual intervention from the admin (to either set the registry key, or to run the easy fix). 

Modifying libgit should allow to solve the problem without intervention from the admins, provided that the system has the recent updates. I am not sure if this is worth the hassle... The benefits are saving some people admin work, and improved security in cases where currently libgit uses TLS 1.0, but 1.2 is available. 


And yeah, regardless of the fix in libgit itself, the end applications ideally should special case this error and point the user to this update anyway, because no changes to libgit can help if the system is not up-to-date.

**Comment by ethomson** [comment]
@matklad Yes, I agree.  Users need:

1. The necessary windows update to enable TLS 1.2.  This is hopefully done automatically via Windows Update, and it's a hard requirement that we can't do anything about.

and:

2. Either the easy fix update _or_ a code change to winhttp/schannel usage.

I think I misunderstood your initial message and inferred and AND when you were implying an OR.  In any case, I think that we're on the same page.

**Comment by matklad** [comment]
@ethomson great!

I think I don't have any more valuable input: I have little experience with windows APIs, so I can't decide if we actually *need* the fix, and, as you've noticed, I actually don't know which code exactly should be use to configure WinHttp :-)

**Comment by ethomson** [comment]
@matklad Thanks for your help; I appreciate you opening this issue and the research that you did.

**Comment by ethomson** [comment]
See #4550 - I did, in fact, decide to enable TLS 1.2 by default.  There's really no API that makes much sense to enable TLS 1.2 in the absence of it being a default in the operating system.

There are a couple of ways that we could communicate that we want to enable TLS 1.2, even though the OS doesn't.  We could make callers enable it as the minimum version...  but that's not _really_ what people want -- this would break support for servers that support TLS 1.0/1.1 but not yet 1.2.

Or we could make callers specify TLS 1.2 as the _maximum_ version, and implicitly enable TLS 1.2 on Windows 7.  But we should instead let callers future-proof their use of us.  When TLS 1.3 is available, we should move into that (when possible), and not require users to recompile their apps ...

Anyway.  I think that we should pick up the responsibility of enabling TLS 1.2 on Windows 7.

**Comment by matklad** [comment]
Closed by https://github.com/libgit2/libgit2/pull/4550 I guess!

We've actually build Cargo with new libgit2, and it indeed works as expected on an unpatched windows 7 virtual box! :tada:

**Comment by matklad** [comment]
Oh, one, hopefully last, question, @ethomson !

You have written on the PR that

>Windows 7 has support for TLS 1.2 out of the box, without needing service packs or any software updates. This is not terribly obvious, since there's a KB discussing TLS 1.2 support - that KB is actually for the registry key support for enabling TLS 1.2 as a default protocol. Even without that update, applications can opt-in to TLS 1.2 support with this patch.

Am I correct that this basically means that applications **do not** need to give special warnings for the missing updates, if they use modern libgit2?

That is, my comment

>And yeah, regardless of the fix in libgit itself, the end applications ideally should special case this error and point the user to this update anyway, because no changes to libgit can help if the system is not up-to-date.

is, in fact, **wrong**?

**Comment by ethomson** [comment]
> Am I correct that this basically means that applications do not need to give special warnings for the missing updates, if they use modern libgit2?

Yes, I _think_ so.  This blog post suggests that TLS 1.2 support does exist in Vista and better:  https://blogs.msdn.microsoft.com/kaushal/2011/10/02/support-for-ssltls-protocols-on-windows/

My testing suggests that Vista doesn't support it out of the box, it requires patches.  But Windows 7 does support TLS 1.2 out of the box, no updates are required.  So the protocol is there, and programs can use it if they explicitly opt-in to it (like this patch does).

TLS 1.2 isn't actually turned on by default until Windows 8.1, unless you install that update and set the registry key.  Once that registry key is set, then any HTTPS connection, even those without explicit opt-in can take advantage of it.

Since libgit2 was not changing the defaults from the operating system, the only way to support TLS 1.2 on Windows 7 was with the update+registry key change.  Now that we override the defaults, we should support TLS 1.2 on Windows 7 without requiring any user intervention.  (And even Vista with patches.)

**Comment by ethomson** [comment]
I validated this by taking the libgit2 test harness on a completely standard out-of-the-box Windows 7 environment with no patches or updates, and it is able to talk to github.com.  But I think that you should double-check me, I've stared at many VMs with many different setups over the last week, so I may have missed something.  😀

**Comment by EaswarAiyer** [comment]
TLS 1.2 is not available for windows server 2008 non r2 machines. How does libgit handle the same?

**Comment by linquize** [comment]
https://blogs.msdn.microsoft.com/kaushal/2011/10/02/support-for-ssltls-protocols-on-windows/
windows server 2008 has TLS 1.2, but need to explicitly enabled

**Comment by EaswarAiyer** [comment]
https://community.qualys.com/thread/17465-tls-12-for-2008-non-r2
Patching was done and the said gpo changes were also done, it works through IE, but winhttp api doesn't seem to work

**Comment by EaswarAiyer** [comment]
> https://blogs.msdn.microsoft.com/kaushal/2011/10/02/support-for-ssltls-protocols-on-windows/
> windows server 2008 has TLS 1.2, but need to install a patch and explicitly enable

https://community.qualys.com/thread/17465-tls-12-for-2008-non-r2
Patching was done and the said gpo changes were also done, it works through IE, but winhttp api doesn't seem to work
