### ISSUE TITLE
Mailmap support

### ISSUE THREAD

**Issue by emilio** [libgit2/libgit2#4565]
Would contributions adding some sort of mailmap-querying API be welcome?

If so, how should that API look like?

Thanks!

---

### Reproduction steps

Try to use libgit2 on a repo with mailmap enabled.

### Expected behavior

There's some sort of API to do a mailmap lookup.

### Actual behavior

There's no such API (I don't see a single reference to `mailmap` on the source either, modulo the mailmap in this repo itself).

### Version of libgit2 (release number or SHA1)

2d2a602

### Operating system(s) tested

N / A

**Comment by carlosmn** [comment]
Mailmap support would be nice to have.

Its application in git itself is rather patchy IIRC so this shouldn't be forced onto the consumers but allow to be enabled/disabled and have a way to look up the mapping manually.
