### ISSUE TITLE
Need to report security issue but security@libgit2.com DOES NOT WORK !

### ISSUE THREAD

**Issue by Bozzzo** [libgit2/libgit2#4569]
### Reproduction steps
email to: security@libgit2.com
### Expected behavior
mail properly transmitted 
### Actual behavior

mail not delivered and return with:
     <security@libgit2.com>: host mx.libgit2.com[66.96.163.166] said: 550
     bosauthsmtp07: Host 82.216.111.42: No unauthenticated relaying permitted
 or similar...
(second line host name and IP varying)

### Version of libgit2 (release number or SHA1)
N.A.
### Operating system(s) tested
N.A

Please have your mail routing fixed so that I can report security issue !

**Comment by Bozzzo** [comment]
I just retried mail and did not receive failure notification from mail delivery system yet...
So I assume this is fixed.

I also forwarded to security@libgit2.org just to make sure...

Yet in both cases I asked for "delivery receipt" and "read receipt"... but received neither so far...

But then may be this is not a supported feature of destination mail server. ;^)

**Comment by ethomson** [comment]
Thanks.  I had set up security@libgit2.org, but we had documented security@libgit2.com.  My mistake.

We now accept mail at both .com and .org.  Sorry for the inconvenience, and thanks for reporting it.
