### ISSUE TITLE
Unable to push, pull, clone, etc... from Git repo through Visual Studio.

### ISSUE THREAD

**Issue by JThomas28** [libgit2/libgit2#4579]
You are opening a _bug report_ against the libgit2 project.  If you have a
question about an API or usage, please ask on StackOverflow:
http://stackoverflow.com/questions/tagged/libgit2.  Please fill out the
reproduction steps (below) and delete this introductory paragraph.  Thanks!

### Reproduction steps
Create new project in VS2013
Add to git and do initial commit

When trying to publish(push), I paste the link in to the github/bitbucket repo and get the following error:
"An error occurred. Detailed message: An error was raised by libgit2. Category=Net (Error).  An error occurred while sending the request"

I have tried reentering my credentials into credential manager, tried multiple repos (bitbucket and github), turned http.sslverify to false, all with no success. Don't know what to try next.

### Expected behavior
Push/clone to be successful

Git command line works fine, as well as tortoise Git, so I know it's not a Git problem. Also, Visual Studio 2017 works through IDE, but my research has shown me VS2017 does NOT use libgit2, which is another reason to think this is a libgit2 bug

### Actual behavior
Fails every time

### Version of libgit2 (release number or SHA1)
unsure. Is libgit2 not automatically installed in VS2013?

### Operating system(s) tested
Windows7

**Comment by ethomson** [comment]
Hi!  I’m sorry that you’re having trouble but there’s little that the libgit2 project can do for you here.  Even if there is a bug in libgit2, there’s little that could be done by you to resolve this.

You could open a support ticket with Microsoft, but I’m reasonably sure that they will indicate to you that you’re hitting an issue with TLS support on Windows 7.

Please check out some of the Microsoft resources like https://developercommunity.visualstudio.com/content/problem/201457/unable-to-connect-to-github-due-to-tls-12-only-cha.html and other similar resources.  (StackOverflow may also be able to help.)

**Comment by ethomson** [comment]
Did this fix your issue, @JThomas28?

**Comment by JThomas28** [comment]
I've opened a case with Microsoft on this issue. I am looking into TLS like you suggested. Thanks!
