### ISSUE TITLE
Don't add trailing slash when reporting repository path or workdir

### ISSUE THREAD

**Issue by mojavelinux** [libgit2/libgit2#4583]
### Reproduction steps

Invoke the [git_repository_path](https://libgit2.github.com/libgit2/#HEAD/group/repository/git_repository_path) or [git_repository_workdir](https://libgit2.github.com/libgit2/#HEAD/group/repository/git_repository_workdir). Observe that the directory path contains a trailing slash.

### Expected vs Actual behavior

It's unconventional to add a trailing slash to the directory name returned by these methods. It also differs from the values reported by the native git client.

Case in point.

Native git:

```
$ git rev-parse --absolute-git-dir
/home/user/projects/libgit2/.git
```

libgit2

```
git_repository_path(repo)
//=> /home/user/projects/libgit2/.git/
```

Native git:

```
$ git worktree list
# /home/user/projects/libgit2    937e7e2 [master]
```

libgit2

```
git_repository_workdir(repo)
//=> /home/user/projects/libgit2/
```

I believe these values should either match the native git client or this difference should be highlighted in the documentation.

### Version of libgit2 (release number or SHA1)

via nodegit 0.21.1 (libgit2 v0.26.0 according to the nodegit README at the time of that release)

### Operating system(s) tested

Linux, Windows, macOS

**Comment by ethomson** [comment]
Thanks for the report.  I don't remember the historical rationale here, but a behavioral change feels breaking and rather unnecessary.  But I agree that we should document this difference better.

**Comment by mojavelinux** [comment]
You don't think it's breaking that libgit2 returns a different result than the native git client? I've also never seen any library add a trailing slash to a directory name before. And the fact that there's no knowledge as to why it is the way it is tells me it needs to be reconsidered. To me, it's breaking not to fix it.

**Comment by ethomson** [comment]
I said that I didn't remember it off the top of my head, I didn't say that there wasn't any.

**Comment by cjhoward92** [comment]
I attempted to add docs for differences from the native client in [#4583](https://github.com/libgit2/libgit2/pull/4605)

**Comment by ethomson** [comment]
Thanks, @cjhoward92 for spinning up the documentation changes.  Closing this as a result.
