### ISSUE TITLE
When visiting https://libgit2.org/ I get a certificate warning before being redirected

### ISSUE THREAD

**Issue by cjhoward92** [libgit2/libgit2#4600]
I clicked on https://libgit2.org/ that can be found on the main GitHub repo home page, and before it redirects to https://libgit2.github.com/ I get a certificate warning in Chrome. Not sure what's up, but I have to manually allow my browser to proceed. Figured I would let everyone know.

**Comment by carlosmn** [comment]
What's up is that the site is not set up with HTTPS so the host is presenting its generic certificate.

Now that GitHub Pages supports certificates for custom domains we should be able to use that to host the redirect.

**Comment by ethomson** [comment]
I've moved us over to GitHub Pages with a custom domain.
