### ISSUE TITLE
git_revwalk_hide assertion failure during fetch

### ISSUE THREAD

**Issue by RazerM** [libgit2/libgit2#4612]
### Version of libgit2 (release number or SHA1)
0.27.0

I was debugging libgit2/pygit2/issues/787 where fetch was failing.

I found a bug in foreach_reference_cb, this is the backtrace:

```
#1  0x00007ffff2f885f5 in foreach_reference_cb (reference=0x105cc40, payload=0xfdf1d0) at .../libgit2/libgit2-0.27.0/src/transports/local.c:514
#2  0x00007ffff2f5419e in git_reference_foreach (repo=0xf85ae0, callback=0x7ffff2f885c8 <foreach_reference_cb>, payload=0xfdf1d0)
    at .../libgit2/libgit2-0.27.0/src/refs.c:746
#3  0x00007ffff2f88814 in local_download_pack (transport=0xffc520, repo=0xf85ae0, stats=0xfd25b0, progress_cb=0x7ffff7fe7fc0, progress_payload=0x7ffff0ad96d8)
    at .../libgit2/libgit2-0.27.0/src/transports/local.c:575
#4  0x00007ffff2effd9d in git_fetch_download_pack (remote=0xfd24e0, callbacks=0xfd12f8) at .../libgit2/libgit2-0.27.0/src/fetch.c:148
#5  0x00007ffff2f5885c in git_remote_download (remote=0xfd24e0, refspecs=0x0, opts=0xfd12f0) at .../libgit2/libgit2-0.27.0/src/remote.c:932
#6  0x00007ffff2f589d2 in git_remote_fetch (remote=0xfd24e0, refspecs=0x0, opts=0xfd12f0, reflog_message=0x0)
```

`foreach_reference_cb` passes `git_reference_target(reference)`
https://github.com/libgit2/libgit2/blob/d9007dc8520942763a21e4058dfa8f159f3e3c56/src/transports/local.c#L510-L514

to `git_revwalk_hide`

https://github.com/libgit2/libgit2/blob/d9007dc8520942763a21e4058dfa8f159f3e3c56/src/revwalk.c#L103-L107

but `git_reference_target` can return `NULL`. so `assert(walk && oid)` will fail.

https://github.com/libgit2/libgit2/blob/d9007dc8520942763a21e4058dfa8f159f3e3c56/src/refs.c#L372-L380

In my case, `type = GIT_REF_SYMBOLIC`, and `symbolic = "refs/remotes/origin/master"`

**Comment by pks-t** [comment]
Thanks for the report. I could reproduce the error and have provided a fix in #4613. Please verify it solves your issue

**Comment by RazerM** [comment]
It fixes the issue, thanks!

**Comment by pks-t** [comment]
Thanks for confirming!
