### ISSUE TITLE
How to implement "git pull","git clean -f","git checkout ." ?

### ISSUE THREAD

**Issue by ZhangXiaoxu** [libgit2/libgit2#4621]
How to implement "git pull","git clean -f","git checkout ." ?
How to checkout a remote branch?

**Comment by ethomson** [comment]
Hi!  Thanks for the question(s).

We use this issue tracker for issues (bugs and features) - we use [StackOverflow](http://stackoverflow.com/questions/tagged/libgit2) for questions and for help with the API.  That lets your questions get much more visibility, persist longer and be much more searchable.  It lets us help you better, and helps the people who have the same question after you.

So I'm going to close this, and I'd encourage you to ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/libgit2) (making sure to add the [libgit2](http://stackoverflow.com/questions/tagged/libgit2) tag!)
