### ISSUE TITLE
.gitignore single wildcard negation rule negates subdirs too

### ISSUE THREAD

**Issue by hackhaslam** [libgit2/libgit2#4623]
With a .gitignore file like this:

```
*.test
!dir/*
```

and repository layout like this:

```
dir
  a.test
  subdir
    b.test
```

libgit2 correctly negates the ignore of dir/a.test, but also incorrectly negates the ignore of dir/subdir/b.test. The is in contrast to core git where only dir/a.test is negated and dir/subdir/b.test stays ignored. In core git the negation pattern has to be:

```
!dir/**
```

to negate entries in subdirs.

**Comment by pks-t** [comment]
Thanks for your report. Please check if #4670 fixes your issue.

**Comment by hackhaslam** [comment]
@pks-t That fixes it for me. Thanks for working on this!

**Comment by ethomson** [comment]
Thanks for the report @hackhaslam !
