### ISSUE TITLE
libgit2 status fails to ignore untracked file

### ISSUE THREAD

**Issue by rgburke** [libgit2/libgit2#4624]
Given the following directory structure where `bk.d` and `foto` are directories and `file1` and `file2` are files:
```
bk.d
├── file2
└── foto
    └── file1
```
The `.gitignore` file in this repository contains the following entries:
```
bk.d/*
!bk.d/*/
```

The output of `git status` is:
```
richard@DevNew:~/code/goworkspace/src/github.com/rgburke/grv$ git status
On branch master
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean
```
However the file `bk.d/file2` is returned with status `GIT_STATUS_WT_NEW` by libgit2. Therefore `git status` ignores the file `bk.d/file2` but libgit2 doesn't.

Tested with version v0.27.0

**Comment by pks-t** [comment]
Thanks for your report. Please check if #4670 fixes your issue.

**Comment by rgburke** [comment]
@pks-t Yes, this fixes the issue. Thanks!

**Comment by pks-t** [comment]
Thanks for checking and your report. Closing this via #4670
