### ISSUE TITLE
git_worktree_lookup fails with "out of memory" on a bare repository

### ISSUE THREAD

**Issue by mjnz** [libgit2/libgit2#4625]
### Reproduction steps
1. Open bare repository that has at least one work tree added to it.  git_repository_open(repo, "repo.git")
2. Get the working tree names (which works fine). git_worktree_list(items, repo)
3. Try to get a git_worktree structure (which fails). git_worktree_lookup(wt, repo, items.strings[0])

### Expected behavior
Should succeed (return 0) and allocate git_worktree structure

### Actual behavior
Fails (return -1), giterr_last returns "Out of memory"

### Version of libgit2 (release number or SHA1)
0.26.3

### Operating system(s) tested
Windows

### Analysis
Based on what I can figure it looks like the problem is because a bare repository returns NULL for git_repository_workdir and that causes the error inside open_worktree_dir

#### git_worktree_lookup
https://github.com/libgit2/libgit2/blob/b55bb43d0a733e6100d4eb52719b619281550a00/src/worktree.c#L177
The above call will result in the second parameter (parent) been passed in as NULL

#### open_worktree_dir
https://github.com/libgit2/libgit2/blob/b55bb43d0a733e6100d4eb52719b619281550a00/src/worktree.c#L143

git__strdup will return NULL (because input parameter parent is NULL) which causes it to error out

**Comment by tiennou** [comment]
This has been fixed by #4630. Thanks for the report @mjnz, this was helpful in pinpointing it!
