### ISSUE TITLE
git_push APIs missing

### ISSUE THREAD

**Issue by slarew** [libgit2/libgit2#4648]
### Reproduction steps

Implement a custom transport with only the public library headers.

1. Call `git_transport_register` with a custom callback that fills in a `git_transport` struct.
2. Try to implement the `push` function for the `git_transport` from step 1.

### Expected behavior

Public APIs exist for using the `git_push` context object.

### Actual behavior

No public APIs exist to use the `git_push`.  Thus, it appears one can't implement a custom transport with only the public interfaces.

### Version of libgit2 (release number or SHA1)

v0.27.0 and master (f9cf9a04)

### Operating system(s) tested

N/A

**Comment by ethomson** [comment]
I don't understand yet...  We have configured a custom transport, created a remote from it, then created a `git_push` from that remote.

Can you show me some pseudo-cde that explains what you expect to work, and outlines the API that's missing for you?

**Comment by slarew** [comment]
```c
#include <git2.h>

git_transport t;
t.push = my_transport_push;

int my_transport_push(git_transport *transport, git_push * push, const git_remote_callbacks *callbacks)
{
// Step 1: Write/stream packfile for this push.

// Oh, there are no public APIs to get the git_packbuilder from push?
// git_push is an opaque type with no public APIs. No way to get the packbuilder :(
abort();

// Step 2: set "unpack_ok" for this push (in git_push struct).


// Step 3: insert push_status structs in the git_push.
}
```

**Comment by slarew** [comment]
Assuming I am not missing something for how to implement a custom transport.push function, I mocked up this untested API to be able to use git_push.

```c
/**
 * Returns the packbuilder for the push.
 *
 * The push's updates are inserted into the packbuilder before the push transport function is called.
 *
 * @param push The push object.
 *
 * @return Packbuilder for the push.
 */
GIT_EXTERN(git_packbuilder*_Nonnull) git_push_packbuilder(
        git_push *_Nonnull push);

/**
 * Report the success or failure of unpacking at the remote.
 *
 * For remotes that unpack a received packfile, the success or failure of the unpack should be reported.  If the remote doesn't process or unpack the packfile, then report a successful unpack when the remote has received the packfile.
 *
 * @param push The push object.
 * @param ok 1 if the remote successfully unpacked the packfile else 0 on failure.
 */
GIT_EXTERN(void) git_push_report_unpack_ok(git_push *_Nonnull push, int ok);

/**
 * Get the reference updates for this push.
 *
 * The returned list is owned by this push object and is constant and valid for the duration of the call to the push transport function.
 *
 * @param updates_out List of git_push_update.
 * @param len_out Filled with length of updates list.
 * @param push The push object.
 */
GIT_EXTERN(void) git_push_updates(
        git_push_update const *_Nonnull *_Nullable *_Nonnull updates_out,
        size_t *_Nonnull len_out,
        git_push *_Nonnull push);

/**
 * Insert a reference in the push status list.
 *
 * The reference is a destination reference as given by git_push_updates.  If the reference on the remote was updated successfully, do not supply a message. Otherwise, message must describe the reason the remote failed to update the reference.
 *
 * @param ref Name of reference on remote.
 * @param message NULL if reference was successfully updated. Otherwise, description of the failure in updating the reference.
 */
GIT_EXTERN(int) git_push_insert_status(git_push *_Nonnull push, char const *_Nonnull ref, char const *_Nullable message);
```

**Comment by carlosmn** [comment]
It looks like you're after something rather different from a transport. You should not have to care about the packbuilder or any details about the Git Smart Protocol.

What are you trying to build? Why do you think you want to create your own transport with intimate knowledge of its caller?

**Comment by slarew** [comment]
The remote I want to support does not natively speak the Git Smart Protocol.  Nor does it reside in the local file system.  Thus, I believe neither `git_transport_smart`+`git/http/ssh_subtransport_definition` nor `git_transport_local` will work for me.

Alternatives:
1. I could add support for the Git Smart Protocol and implement a custom subtransport to talk with the remote.
2. Create a temporary local repository with *custom* ODB and refs backends and then use built-in `git_transport_local` to talk to the temp local repo.
3. Implement a new remote protocol.

Option 1 is not appealing since I would need to implement the server side of the smart protocol.  This would be in addition to another private protocol translation already occurring.  The custom subtransport would not be git, ssh, http, or file and would instead be an custom local IPC.

Option 2 is possible since I could natively speak to my remote to provide the custom backends for a temp local repository.  However, the local (i.e., `file://`) transport seems to assume the backends are locally available when in reality the backends would be serviced over a remote network connection.  I suspect this would be rather slow.

Option 3 tackles the problem head on, I believe. Since my remote does not speak the smart protocol, it makes sense to implement a custom remote protocol.  As far as I can tell, the way to implement a custom protocol is to create a custom `git_transport`.  However, it seems that the public APIs do not exist to implement the `push` method of a `git_transport`.

Maybe my analysis of these options is wrong? Maybe I missed an alternative? Thanks for your help.

**Comment by ethomson** [comment]
I'm closing this issue, it's been open quite a while without further followup.

This isn't something that I would intend to provide.  My brief analysis is that either:

1. "push" is not the right thing to use here: one is only _pushing_ if you're actually using the protocol as it's defined.  We don't open up the push mechanism because if you're not speaking the smart transport then you're doing something else to get your objects from one place to another, perhaps...

2. You want to use a custom object database that knows how to speak to your remote.  Although this isn't what I would call a "push", I don't have details enough to know what exactly your desired configuration looks like.  So I mention this option for completeness.  But finally,

3. There's an opportunity to provide some abstraction that can help you achieve your goals, but I don't know what it is.  I think that you'd need to provide a PR that refactors this into something pluggable like what you want.

In any case, I think the next step would be an RFC in the form of a pull request, and that there's not a lot that can be done by us on this issue.
