### ISSUE TITLE
Cloning fails with error: invalid Content-Type: text/plain; charset=UTF-8;

### ISSUE THREAD

**Issue by jhaye** [libgit2/libgit2#4652]
Please note: This issue was encountered with git2-rs which utilises this library. Unfortunately I lack the knowledge about implementation details, so please excuse the brevity of this report.

Tracking issue for git2-rs: https://github.com/alexcrichton/git2-rs/issues/314

### Reproduction steps
Try cloning https://git.matrix.org/git/olm/ with libgit2. (Works with git via CLI)

### Expected behavior
Cloning finishes successfully.

### Actual behavior
Libgit2 finishes with the following error code: `invalid Content-Type invalid Content-Type: text/plain; charset=UTF-8; class=Net (12)`

### Version of libgit2 (release number or SHA1)
`c9d59c6140fc365eb7ab950fb1a33187a949d403`

### Operating system(s) tested
Debian Buster

**Comment by ethomson** [comment]
It looks like git.matrix.org uses "[dumb HTTP](https://git-scm.com/book/en/v2/Git-Internals-Transfer-Protocols)".  As that page notes:

> The dumb protocol is fairly rarely used these days... It’s generally advised to use the smart protocol, which we describe a bit further on.

Indeed, the dumb protocol was the original HTTP protocol for git.  The smart HTTP protocol was introduced nearly a decade ago, and is superior in every way.  Most hosting providers have either [disabled it](https://blog.github.com/2011-03-09-git-dumb-http-transport-to-be-turned-off-in-90-days/) or simply [never supported it at all](https://visualstudio.com/team-services/).

Git protocol v2 is coming, and a much more interesting thing for us to start supporting than this.  Unless you want to contribute dumb HTTP support, I find it unlikely that we will pursue supporting this.

I would encourage your hosting provider to enable smart HTTP.

**Comment by jhaye** [comment]
Thank you for such a comprehensive response.
This is an issue that I fear I won't have time to directly help this project implement.
I'll be reaching out to the Matrix folks about the used HTTP protocol and if that fails, I'll probably just mirror the project on a different service.

Thank you for your work!

**Comment by ethomson** [comment]
Understandable.  Sorry that this didn’t work out for you.  It looks like matrix uses dumb http so that they can use a CDN for the objects.  I’d be happy to chat with them about other ways they may be able to reduce their bandwidth utilization while using modern git protocols.
