### ISSUE TITLE
Rename git_push_transfer_progress to git_push_transfer_progress_cb

### ISSUE THREAD

**Issue by rcjsuen** [libgit2/libgit2#4654]
Since `git_push_transfer_progress` is a callback, could it be renamed to `git_push_transfer_progress_cb` instead? NodeGit's code generator currently does not flag it as a callback because of this (see nodegit/nodegit#1500) The other members in the `git_remote_callbacks` struct follow the same convention like `git_cred_acquire_cb`, `git_transfer_progress_cb`, `git_push_update_reference_cb`, and so on.

But I guess this ship has long sailed already?

### Version of libgit2 (release number or SHA1)
Valid in `HEAD` https://github.com/libgit2/libgit2/blob/f9cf9a04ba61cba7b1112764dd25c0e4638bed75/include/git2/remote.h#L460-L466

https://github.com/libgit2/libgit2/blob/f9cf9a04ba61cba7b1112764dd25c0e4638bed75/include/git2/remote.h#L350-L355

**Comment by pks-t** [comment]
Yeah, this is misnamed. But due to API stability, we unfortunately cannot fix it anymore :/ Thanks for your report, but I'm afraid we have no way to fix this anymore. Sorry!

**Comment by Uncommon** [comment]
Perhaps there could be an additional typedef so that both names are available?

**Comment by rcjsuen** [comment]
Given #4997, would it be possible to add another typedef per @Uncommon's suggestion?

**Comment by pks-t** [comment]
Given our new deprecation strategy I'm definitely not opposed to this
