### ISSUE TITLE
Warning: enum out of range

### ISSUE THREAD

**Issue by jeroen** [libgit2/libgit2#4657]
I am getting the following warning when compiling my bindings against libgit2 0.27.0 with `-pedantic`:

```
./libgit2-0.27.0/include/git2/diff.h:214:30: warning: ISO C restricts enumerator values to range of 'int' [-Wpedantic]
```

Unfortunately my repository maintainers insist that the code can be compiled without any `-pedantic` warnings. Here is the offending line:

https://github.com/libgit2/libgit2/blob/d11c4a1a464f10c69d5cc58824e980ea5045d439/include/git2/diff.h#L210-L215

**Comment by pks-t** [comment]
Thanks for the report. This indeed sucks, as we _do_ break ISO C90 here, but at the same time we cannot really change the interface due to API stability as it was released as part of v0.27. I'm rather clueless how to fix this right now :/ @carlosmn, any ideas?

**Comment by jeroen** [comment]
I think your only option is to remove this value from the enum if you want to be C99...

**Comment by ethomson** [comment]
As a short-term solution, we can simply move `GIT_DIFF_INDENT_HEURISTIC` to one of the unused bits in the middle of `git_diff_option_t`.

Obviously we need a long-term solution since we're about out of bits here, anyway.

**Comment by pks-t** [comment]
That would work, I guess. A user of libgit2 might have compiled
against an old version with the previous enum value, though, and
not recompile his application. In that case, he'd use an invalid
value. But as we're bumping soversions for each release anyway, I
guess that is not a problem?

**Comment by ethomson** [comment]
> But as we're bumping soversions for each release anyway, I guess that is not a problem?

Yes, that's my thinking.  We haven't made an effort on ABI compatibility (which is why we're generous about bumping the soversion).  This keeps API compatibility, at least.

**Comment by jeroen** [comment]
Awesome. Are there any plans to tag a release soon? This was blocking me from a release.

**Comment by pks-t** [comment]
I'm afraid not, sorry. We have just released v0.27.2 this Sunday,
so we do not want to burden users with another release in quick
succession.

**Comment by jeroen** [comment]
That's unfortunate. I may just cherry pick the patch then.

**Comment by carlosmn** [comment]
@jeroen note that this is changing a public enum so that change is incompatible with the released library with SONAME 27 and putting such a library into the system is going to break users of the library.
