### ISSUE TITLE
git_clone(github.com) return "unknown certificate check failure" on Vista

### ISSUE THREAD

**Issue by AndrJ** [libgit2/libgit2#4663]
libgit2 v0.27.1
Windows Vista SP2 x86 (latest Windows Update + KB4019276 + EnableIE9TLS1.2 registry patch Applied)

git_clone(... https://github.com/libgit2/libgit2 ...)
API Return:-17
giterr_last() Return: unknown certificate check failure

#https://github.com/libgit2/libgit2/commit/5ecb62206a9cdb6cb2105f5ef6cfcd3b9f5bab3a
How can I enable TLS 1.2 in Vista?
Append:
I can browse https://github.com/libgit2/libgit2 from Vista IE9

**Comment by ethomson** [comment]
We should now enforce TLS 1.2 as long as the appropriate libraries are installed.
