### ISSUE TITLE
git_repository_path is incorrect for worktree from bare repo

### ISSUE THREAD

**Issue by GeorgeLyon** [libgit2/libgit2#4684]
### Reproduction steps

I reproduced this using Rust's `cargo` tool. If you try to run `cargo build` inside of a worktree of a bare git repo, the command fails because git_repository_path returns null.

1. Clone any Rust project with `git clone --bare`
2. In the bare repo, use `git worktree add` to create a worktree
3. try `cargo build` in the newly created worktree 
4. `cargo build` fails because git_repository_path returns NULL

### Expected behavior

git_repository_path should return the path of the worktree.

### Actual behavior

git_repository_path returns NULL

**Comment by ethomson** [comment]
Have you opened an issue with cargo about this issue?

**Comment by GeorgeLyon** [comment]
I have not yet, because it seems that this is specific to libgit2 (and when it is fixed, cargo should work correctly)

**Comment by ethomson** [comment]
It’s not.  Please report it to them so that they can make their tool worktree aware.  Thanks!

**Comment by ethomson** [comment]
Thanks @tiennou for chasing this down.  I was obviously wrong and this is indeed our bug.  Oops!  Thanks for reporting it @GeorgeLyon!

**Comment by tiennou** [comment]
Sorry, misunderstanding. I investigated this in #4686, and I'm [confident](https://github.com/libgit2/libgit2/pull/4686/commits/853657f9f675c0d29aa4752e06f4118fb1566635) this is fixed on our side, so I suspect cargo hasn't updated to 0.27 (which IIRC has #4630, which fixes the underlying issue).

@GeorgeLyon You might want to file an issue with the cargo developers so they can investigate their code, just to make sure they're aware of the issue and can respond accordingly.

**Comment by pks-t** [comment]
Yeah, the test explicitly calls `git_repository_path` on that worktree. Closing this issue again as it should be fixed. @GeorgeLyon, in case I'm wrong, please feel free to reopen.

**Comment by pks-t** [comment]
Sigh. I reviewed @tiennou's PR already and thus thought it was merged already, that's why I already closed this issue. Anyway, as we're already tracking the issue in there I'll just keep this issue closed for now.
