### ISSUE TITLE
Fix link in repository description

### ISSUE THREAD

**Issue by simon0191** [libgit2/libgit2#4690]
Bug:
In the repository description there's a link pointing to https://libgit2.org/ which has an invalid SSL certificate.

Solution:
Replace that link with https://libgit2.github.com/

**Comment by ethomson** [comment]
Thanks for reporting this; now that [GitHub Pages supports HTTPS on custom domains](https://blog.github.com/2018-05-01-github-pages-custom-domains-https/), I've updated our configuration.  [https://libgit2.org/](https://libgit2.org/) should work for you once the DNS updates propagate.
