### ISSUE TITLE
Misleading `git_tree_walk` errors

### ISSUE THREAD

**Issue by omus** [libgit2/libgit2#4693]
When using `git_tree_walk` with a callback which stops the walk it can appear that a previously generated libgit2 error was created in the callback. To reproduce:

1. Use `giterr_set_str` to create an error which does not use the callback error class. This emulates an error created earlier. 
2. Execute [`git_tree_walk`](https://libgit2.org/#HEAD/group/tree/git_tree_walk) where the provided callback stops the walk (returns a negative value)
3. The error returned will be the error set in step 1 and not from [`giterr_set_after_callback_function`](
https://github.com/libgit2/libgit2/blob/26f5d36d2f14dc1d711ed0a2c844ef4d7887a9b3/src/common.h#L115-L133)

**Comment by ethomson** [comment]
Hi @omus, thanks for reporting this.  This feels very much like a usage error to me: are you following the discussion in #4703?

**Comment by omus** [comment]
Hi @ethomson. I'll post a reply in #4703

**Comment by ethomson** [comment]
Closed via #4703.  Thanks @omus for reporting it!
