### ISSUE TITLE
oss-fuzz integration for libgit2

### ISSUE THREAD

**Issue by nelhage** [libgit2/libgit2#4697]
I've been working on fuzzing libgit2, and would like to submit an integration to Google's [oss-fuzz](https://github.com/google/oss-fuzz). Would there be interest in this from the project maintainers?

I've already found a number of issues, with more to come:
 
- https://github.com/libgit2/libgit2/pull/4694 
- https://github.com/libgit2/libgit2/pull/4695 
- https://github.com/libgit2/libgit2/pull/4696

If submitted and accepted, Google would continually fuzz libgit2 using libfuzzer, and report issues to the libgit2 maintainers. You can read more about the process [in oss-fuzz's docs](https://github.com/google/oss-fuzz#process-overview)

If there's interest on your part, I'll submit an integration to oss-fuzz for review over there. Is there a mailing list address I should attach to the submission that will receive crash reports from the fuzzer?

**Comment by pks-t** [comment]
Yeah, we're definitely interested in having support for oss-fuzz. Especially testing the remote protocol would be rad. There was already some work in #4433, but we didn't yet have time to properly review and merge it. I'd be interested on your current approach, so please feel free to create another pull request as soon as you feel like your integration is ready.

**Comment by nelhage** [comment]
You can take a look at my work-in-progress here: https://github.com/nelhage/oss-fuzz/tree/libgit2
The main fuzzer I've been using is https://github.com/nelhage/oss-fuzz/blob/libgit2/projects/libgit2/fuzz_download_refs.cc which fuzzes the network protocol. It currently relies on a git repository in a tempdir on disk, which I'm not thrilled about; Do you happen to know if there's an in-memory backend anywhere I could borrow? It looks like one could be stitched together from custom refdb, odb, and config backends, but I didn't see prior art at a glance.

**Comment by tiennou** [comment]
As far as I know, we're now fuzzing the network and odb layers, so I'm tempted to close this. Your call, @pks-t @nelhage.

**Comment by pks-t** [comment]
On Tue, Jan 29, 2019 at 01:45:03PM -0800, Etienne Samson wrote:
> As far as I know, we're now fuzzing the network and odb layers, so I'm tempted to close this. Your call, @pks-t @nelhage.

We've also got a config fuzzer :)

We certainly can close this. Thanks again for all the work that
has beed done here!
