### ISSUE TITLE
add.c -v/-n option does not work

### ISSUE THREAD

**Issue by mgood7123** [libgit2/libgit2#4706]
You are opening a _bug report_ against the libgit2 project: we use
GitHub Issues for tracking bug reports and feature requests.  If you
have a question about an API or usage, please ask on StackOverflow:
http://stackoverflow.com/questions/tagged/libgit2.  If you want to
have high-level discussions about the libgit2 project itself, visit
https://github.com/libgit2/discussions.

Otherwise, to report a bug, please fill out the reproduction steps
(below) and delete these introductory paragraphs.  Thanks!

### Reproduction steps
compile init.c and add.c,
init  . ; add -v add.c
### Expected behavior
add 'add.c'
### Actual behavior
callback isnt called
### Version of libgit2 (release number or SHA1)
0.26.0 , 0.27.0
### Operating system(s) tested
iOS Mobile C App , debian

**Comment by pks-t** [comment]
This issue is kind of sparse with the details. I assume that by "init.c" and "add.c" you actually refer to our examples. At least that is the only thing that should print out "add 'file'" in our code base. Compiling our examples and testing it produces the correct results for me, though. Did you try that with the latest master?

Please also note that our examples are really just that: examples. They really shouldn't be used for any real-world usage, but should just demonstrate how to use our API to implement certain features.

**Comment by mgood7123** [comment]
curl https://paste.pound-python.org/raw/YwSQJTxiQBHHEwkUWbZ7/ -o lib
git.c ; gcc libgit.c -std=gnu99 -lgit2 -o libgit && ./libgit

Merged init.c and add.c examples into a single compilable file

'''
cabox@box-codeanywhere:~/workspace$ curl https://paste.pound-python.org/raw/YwSQJTxiQBHHEwkUWbZ7/ -o lib
git.c ; gcc libgit.c -std=gnu99 -lgit2 -o libgit && ./libgit                                            
  % Total    % Received % Xferd  Average Speed  Time    Time    Time  Current                        
                                Dload  Upload  Total  Spent    Left  Speed                          
100 22910  100 22910    0    0  197k      0 --:--:-- --:--:-- --:--:--  196k                          
libgit.c:33:9: warning: #pragma once in main file [enabled by default]                                  
#pragma once                                                                                          
        ^                                                                                              
libgit.c: In function 'git_libgit_version_2_api_create_initial_commit':                                
libgit.c:455:3: warning: too many arguments for format [-Wformat-extra-args]                            
  giterror("Could not open repository index", NULL);                                                  
  ^                                                                                                    
libgit.c:468:3: warning: too many arguments for format [-Wformat-extra-args]                            
  giterror("Unable to write initial tree from index", NULL);                                          
  ^                                                                                                    
libgit.c:476:3: warning: too many arguments for format [-Wformat-extra-args]                            
  giterror("Could not look up initial tree", NULL);                                                    
  ^                                                                                                    
libgit.c:492:3: warning: too many arguments for format [-Wformat-extra-args]                            
  giterror("Could not create the initial commit", NULL);                                              
  ^                                                                                                    
libgit.c: In function 'Xmalloc':                                                                        
libgit.c:795:9: warning: format '%d' expects argument of type 'int', but argument 3 has type 'size_t' [-
Wformat=]                                                                                              
        fprintf(stderr, nomem, sz);                                                                    
        ^                                                                                              
libgit.c: In function 'Xrealloc':                                                                      
libgit.c:806:9: warning: format '%d' expects argument of type 'int', but argument 3 has type 'size_t' [-
Wformat=]                                                                                              
        fprintf(stderr, nomem, sz);                                                                    
        ^                                                                                              
testing                                                                                                
argc = 2                                                                                                
argv[0] = init                                                                                          
argv[1] = test                                                                                          
Initialized empty Git repository in /home/cabox/workspace/test/                                        
argc = 3                                                                                                
argv[0] = add                                                                                          
argv[1] = -v                                                                                            
argv[2] = ./test                                                                                        
testing done                                                                                           
'''

**Comment by mgood7123** [comment]
Also it appears that when looking at the source code it git_index_add_all calls index_apply_to_wd_diff however i cannot find the source code for that function

**Comment by mgood7123** [comment]
ok

**Comment by mgood7123** [comment]
But still, the callback should be getting called right?

**Comment by pks-t** [comment]
Yes, if used correctly the callback should get called. And in fact it is being called, as you can see in our "examples/add.c" program, where the callback in being executed sa expected. So I guess it most likely is an issue in your code.

I'm closing this issue for now -- like @ethomson said, Stackoverflow is the better avenue to get support. In case you have a small reproducer which shows that we _are_ indeed to blame, please feel free to reopen this issue.

**Comment by mgood7123** [comment]
Is there a way to actually verify the callback is being called

**Comment by pks-t** [comment]
Sure. You can either use a debugger and set a breakpoint in your callback function or simply use printf-style debugging.
