### ISSUE TITLE
Stashing specific files

### ISSUE THREAD

**Issue by Uncommon** [libgit2/libgit2#4725]
I have sometimes wished for the ability to stash specific files, and I just had a user request for this as well.

There is the `GIT_STASH_KEEP_INDEX` option, which is one way to achieve this. Even better, though, would be the ability to pass either a list of files or a file filter function. I think the latter might be better since it's more powerful.

I'd probably be able to tackle this myself, so any feedback on appropriate API design and such would be great.

**Comment by tiennou** [comment]
If I were to add something like that, I'd do something like this :

```c
typedef struct git_stash_save_opts {
   int version;
   const git_signature *stasher; /*< can be null, default to repo's signature */
   const char *msg; /*< can be null */
   int flags;
   git_strarray pathspec;
}

/*  standard libgit2 option boilerplate */

GIT_EXTERN(int) git_stash_save_with_opts(git_oid *out, git_repository *repo, const git_stash_save_opts *opts);
```

Note that, from a cursory glance, diff seems to be the underlying mechanism used for choosing what to stash, and it seems to handle [pathspecs](https://github.com/libgit2/libgit2/blob/master/include/git2/diff.h#L415). Though there's a bunch of callback just below, I don't know if they permit that kind of filtering, ie. they seem to be "FYI" callbacks, so maybe you'll need to do pathspecs anyways…

A possible alternative might be to allow stashing indexes directly (if that makes sense ?). That would make users go though the index API (which already handles files however you want), and be somewhat more "generic" (ie. that might enable bare-repo stashing 😉). That's from the top of my head, though, so it might not be viable…

**Comment by extrawurst** [comment]
This would be super useful! @tiennou / @Uncommon are you still planning to do this?

**Comment by Uncommon** [comment]
I'm still interested in having this at some point, although I have no timeline for it.

**Comment by extrawurst** [comment]
ideally we can just create a stash from a bunch of patches, to allow stashing the whole index, a whole file, paths or whatever combination.

**Comment by JWess** [comment]
GitKraken is built on libgit2, and it has a [partial stash feature request](https://feedback.gitkraken.com/suggestions/194826/support-partial-stash) with 223 upvotes that is being blocked. As a GitKraken user, I would LOVE to see this resolved.

**Comment by PibePlayer** [comment]
I really need this for my workflow. Please, someone :)
