### ISSUE TITLE
libgit2 0.27.0 tests segfaults on armhf, mips64el and ppc64el architectures

### ISSUE THREAD

**Issue by pravi** [libgit2/libgit2#4737]
More details here https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=904004

Full build logs

https://buildd.debian.org/status/fetch.php?pkg=libgit2&arch=mips64el&ver=0.27.0+dfsg.1-0.8&stamp=1531913949&raw=0

https://buildd.debian.org/status/fetch.php?pkg=libgit2&arch=ppc64el&ver=0.27.0+dfsg.1-0.8&stamp=1531912011&raw=0

0.27.3 also fails with the below error on mips64el.

33% tests passed, 2 tests failed out of 3

Total Test time (real) = 359.07 sec

The following tests FAILED:
          2 - libgit2_clar-proxy_credentials (SEGFAULT)
          3 - libgit2_clar-ssh (SEGFAULT)
Errors while running CTest
make: *** [Makefile:98: test] Error 8

### Version of libgit2 (release number or SHA1)

0.27.0, 0.27.3

### Operating system(s) tested

debian unstable with gcc 8.1.0-12 (it also failed with gcc 7 earlier)

**Comment by pravi** [comment]
https://salsa.debian.org/debian/libgit2/blob/master/debian/rules has the cmake options. We use mbedTLS with backported patch from master.

**Comment by ethomson** [comment]
Neither I - nor as best as I know - any other developer has any of these uncommon architectures.  More information would be helpful.

**Comment by pravi** [comment]
@ethomson you can get a free ppc64el VM from http://openpower.ic.unicamp.br/minicloud/ I will also try to see if I can get a stacktrace via gdb.

**Comment by pravi** [comment]
Hmm weird https://buildd.debian.org/status/package.php?p=libgit2 from this page click on 'Build attempted' link under status column.

**Comment by infinity0** [comment]
The segfault actually happens on all architectures and is trivially reproducible on x86-64, see #4753. This issue can be closed.

**Comment by ethomson** [comment]
Fixed via #4754
