### ISSUE TITLE
regexec symbol conflict with oniguruma

### ISSUE THREAD

**Issue by kornelski** [libgit2/libgit2#4738]
### Reproduction steps

1. Link libgit2 and oniguruma together in one project
2. Use any libgit2 function that calls `git_config_next`, which calls `all_iter_glob_next` and `regexec`

### Expected behavior

The library should co-exist with other libraries

### Actual behavior

It crashes if the linker decides to use `regexec` from oniguruma rather than from libgit2's internal regex dependency.

```
regexec + 256 (regposix.c:203) // note regposix.c is oniguruma's.
all_iter_glob_next + 85 (config.c:426) // this was meant to call regexec.c
git_config_next + 45 (config.c:1081)
apply_insteadof + 411 (remote.c:2506)
create_internal + 407 (remote.c:216)
git_remote_create_with_fetchspec + 129 (remote.c:321)
git_remote_create + 171 (remote.c:304)
default_remote_create + 49 (clone.c:248)
create_and_configure_origin + 324 (clone.c:280)
git_clone + 532 (clone.c:424)
git2::build::RepoBuilder::clone::h38f379ee2822ae4f + 960 (build.rs:231)
```

### Version of libgit2 (release number or SHA1)

771dfd1dd1c27a4693dfdfea521c07e72f456b29

### Operating system(s) tested

macOS 10.14

See also https://github.com/alexcrichton/git2-rs/issues/232

**Comment by pks-t** [comment]
Thanks for your report! Unfortunately, I don't think there's anything we can do here. In case where POSIX-specified symbols part of libc get replaced by third-party symbols which aren't compatible we cannot guarantee anything at all. As soon as we'd start working around such issues, we'd be opening a can of worms: what if anybody provides an `open` symbol, overwriting the standard one, or really any symbol which conflicts with POSIX/libc owned ones?

That being said, I'd think that you should be able to fix your issue by changing the order of libraries passed to the linker. A library requiring a certain symbol always should come to the left of the one providing that symbol. So in case where libgit2 is listed previous to onigu, it might try to use its symbols. But swapping those two libraries might already help you, if I'm not mistaken.
