### ISSUE TITLE
Out of memory error on AIX

### ISSUE THREAD

**Issue by hkrummeck** [libgit2/libgit2#4748]
### Reproduction steps
Call *git_status_list_new()* with flag *GIT_STATUS_OPT_RENAMES_HEAD_TO_INDEX*
on a clean repository.

### Expected behavior
Returns the status of the repository.

### Actual behavior
Out of memory error occurs.

**Reason** 
With above option the function *git_diff_find_similar()* is called. 
If *diff->deltas.length* is 0 the memory allocation *git__calloc(0)* raises the error
because *calloc(0)* returns a NULL pointer on the specified system.

### Version of libgit2 (release number or SHA1)
0.27.3, 0.26.3

### Operating system(s) tested
AIX 7.1
gcc 8.1 64 bit

**Comment by pks-t** [comment]
Thanks for your report! Could you please verify whether #4761 fixes your problem?

**Comment by hkrummeck** [comment]
Yes, this fixes the problem.
