### ISSUE TITLE
how can I install libgit2 v0.27.4 using apt-get command?

### ISSUE THREAD

**Issue by flauberjp** [libgit2/libgit2#4793]
I can't find a .deb package for libgit2 version v0.27.4, it isn't generated by here?
My suggestion is that every version should produce one.

**Comment by tiennou** [comment]
We don't package libgit2 directly, so you should look at the list at [debian.org](https://packages.debian.org/search?searchon=sourcenames&keywords=libgit2). It looks like there's a backport of 0.27.4 to Debian stretch which you might be able to use.

**Comment by pks-t** [comment]
Yup, @tiennou is right. Distros are responsible for providing packages, we unfortunately cannot really help you with this issue. Closing

**Comment by flauberjp** [comment]
I was analysing https://packages.debian.org/sid/libgit2-27, there you have a URL we could use with apt-get like http://debian.mirror.ac.za/debian/pool/main/libg/libgit2/libgit2-27_0.27.4+dfsg.1-0.1_amd64.deb
Thanks @tiennou, and @pks-t !
