### ISSUE TITLE
git_tag_delete doesn't behaves like git tag -d

### ISSUE THREAD

**Issue by Orace** [libgit2/libgit2#4806]
### Reproduction steps

call git_tag_delete on a tag that is not packed and is alone in its folder like .git/refs/tags/Test/Tag1

### Expected behavior

the tag is deleted 
the empty folder is deleted

### Actual behavior

the tag is deleted 
the folder is kept empty

### Remarks

git tag -d Test/Tag1 will delete the tag and the folder

### Version of libgit2 (release number or SHA1)

c1ef58ac0540d9b6b65066415da6c588d54c6881

### Operating system(s) tested

Windows 7

**Comment by csware** [comment]
This issue is fixed by PR#4833.
