### ISSUE TITLE
libgit2 doesn't show all changed binary files compared to git for repository

### ISSUE THREAD

**Issue by terhechte** [libgit2/libgit2#4820]
### Reproduction steps

Tricky. It is happening on a private repository. I've tried it on a couple of test repositories where it doesn't happen. I can't share the private repo.

### Expected behavior

The repository has a couple of binary files (snapshot images) and some of those have been modified. I'd like to get a diff of the `HEAD` and the workdir. I'm using `git_diff_tree_to_workdir` for this. The code I'm using is in Rust. I can try developing a similar example in C, but I wanted to create this issue before doing so in order to see if maybe I'm doing something wrong:

``` rs
extern crate git2;

use git2::{Repository};

fn main() {
    let repository = Repository::open("/tmp/repository").unwrap();
    // for the sake of this example, we just want to compare to HEAD
    let head = repository.find_reference("HEAD").unwrap();
    let commit = head.peel_to_commit().unwrap();
    let tree = commit.tree().unwrap();
    let diff = repository.diff_tree_to_workdir_with_index(Some(&tree), None).unwrap();
    // iterate over all the changes in the diff
    diff.foreach(&mut |_, _| {
        // this will be called for each delta. returning means continue iterating
        true
    } , Some(&mut |a, _| {
        // this will be called only for the binary deltas, which is what we're interested in
        if let Some(path) = a.new_file().path() {
            println!("file: {:?}", &path);
        }
        true
    }), None, None).unwrap();
}
```

It should show all the modified files that `git` also shows:

```
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   README.md
        modified:   examples/image1.png
        deleted:    examples/image2.png
        modified:   examples/image3.png
        modified:   examples/image4.png
        modified:   examples/image5.png
        modified:   examples/image6.png
        modified:   examples/image7.png
```

### Actual behavior

The tool (from the Rust code above) only shows two files.
```
    Finished dev [unoptimized + debuginfo] target(s) in 0.06s
     Running `target/debug/gitdiff`
file: "examples/image1.png"
file: "examples/image2.png"
```

The weirdest thing is that when I restore the one deleted file, it will not display any changes.

Instead of comparing to the head tree, I also tried comparing to the tip of the current branch:
``` rs
let commit = repository.find_branch("name-of-branch", BranchType::Local).unwrap().into_reference().peel_to_commit().unwrap();
```
with the same result.

So, somehow, on our repository here, the `git` commandline tool returns the proper information on `git diff` or `git status` while `git_diff_tree_to_workdir` does not. Am I using the `git_diff_tree_to_workdir` wrong, or could it be that our repo is corrupt? (But then, why does the `git` ommandline tool work properly?)

I've also checked SourceTree, and they also display the correct files. 

### Version of libgit2 (release number or SHA1)
771dfd1dd1c27a4693dfdfea521c07e72f456b29

### Operating system(s) tested
macOS 10.13.6

**Comment by terhechte** [comment]
I just tried with the `examples/diff.c` tool, and it has the same issue, it only lists two changed files, and ignores the others.

**Comment by ethomson** [comment]
Odd.  Any chance that these files are not changing in size?

**Comment by ethomson** [comment]
Hmm.  I think it’s going to be very hard to debug this without being able to have a repository that reproduces this.

Could you see if an anonymous export of the repository reproduces this?  See the notes on “Anonymizing”, here:  https://git-scm.com/docs/git-fast-export

**Comment by terhechte** [comment]
It might habe been an issue with our repository (which doesn't really explain why porcelain showed it just fine though), because I pulled in master (with the changes still in the workdir) the bug was gone.
