### ISSUE TITLE
follow_and_lstat_link does not correctly follow symbolic links for UNC shares

### ISSUE THREAD

**Issue by GabeDeBacker** [libgit2/libgit2#4821]
### Reproduction steps
This was discovered using LibGit2Sharp, but the issue is actually in the native binaries.

Easiest way to set up is through the command prompt.
Copy the %userprofile%\.gitconfig to a UNC share (i.e. \\server\share\myGitConfig\.gitconfig)
Delete the %userprofile%\.gitconfig
mklink %USERPROFILE%\.gitconfig \\server\share\myGitConfig\.gitconfig

Executing the following code from LibGit2Sharp:
                var repo = new Repository(repoRoot);

                var matchesRequiredConfig= repo.Config.Any((config) =>
                {
                });

### Expected behavior
No exception.

### Actual behavior
Exception thrown: 'LibGit2Sharp.NotFoundException' in LibGit2Sharp.dll
could not find 'C:/Users/gabrield/.gitconfig' to stat: The system cannot find the path specified.

### Version of libgit2 (release number or SHA1)
v0.16.0-8972-g6311e886d

### Operating system(s) tested
x64 Windows 

### Additional information
After debugging the issue quite a bit, the issue stems from this stack:

size_t git_win32__canonicalize_path(wchar_t *str, size_t len) -> libgit2.git\src\win32\w32_util.c
static int getfinalpath_w(git_win32_path dest, const wchar_t *path) -> libgit2.git\src\win32\posix_w32.c
static int follow_and_lstat_link(git_win32_path path, struct stat* buf) -> libgit2.git\src\win32\posix_w32.c
int p_stat(const char* path, struct stat* buf) -> libgit2.git\src\win32\posix_w32.c

getfinalpath_w correctly gets the UNC path to the server (using the example above, it results in:
"\\?\UNC\server\share\myGitConfig\.gitconfig"

Then it calls win32__canonicalize_path, which results in stripping the "\\\\?\\UNC\\" from the path, resulting in "server\\share\\myGitConfig\\.gitconfig"

follow_and_lstat_link then calls GetFileAttributesExW with an invalid path of "server\share\myGitConfig\.gitconfig" which should be "\\\\server\share\myGitConfig\.gitconfig"

**Comment by GabeDeBacker** [comment]
Wanted to clarify, the bat to GetFileAttributesExW should be "\\server\share\myGitConfig.gitconfig".

**Comment by anon99** [comment]
I use Windows git with a windows share, containing git worktrees.
Inside the .gitconfig is a Linux path containing /home/username/ etc ending in .git/worktrees/repo-name.

This seems to upset git claiming a workree is not a repo. [Non worktrees appear to work fine, its this .gitconfig containing a linux (not windows) path that seems to be the offender.

Does (or might) this fix address this issue?. From a quick skim the fix appeared to address git on windows using windows path semantics. Is git on windows with worktrees (on linux) supported by libgit2 ? and if not are there any plans in that direction?.

Or does .gitconfig support having both windows and linux paths?,

**Comment by anon99** [comment]
Created issue #4861 hope thats enough detail.
