### ISSUE TITLE
feature request git_worktree_add commitish reference

### ISSUE THREAD

**Issue by Richard-Mathie** [libgit2/libgit2#4823]
From libgit2/pygit2#814 `git_worktree_add` only has arguments of name and path so it is currently not possible to create a work tree on a specific reference (existing branches, tags ect) and it just creates a new branch name.
using pygit2 bindings
```
repo.listall_branches()
>>  ['master',
     'develop']

worktree_dir = tempfile.mkdtemp()
os.rmdir(worktree_dir)
worktree = repo.add_worktree('develop', worktree_dir)
>>  Traceback (most recent call last):

      File "<ipython-input-134-cb34d9dc7f6a>", line 4, in <module>
        worktree = repo.add_worktree('develop', worktree_dir)

    ValueError: failed to write reference 'refs/heads/develop': a reference with that name already exists.
```
expected behaviour would be to create a worktree off the existing branch `develop` in the new `worktree_dir`

in plain git i can do this
```
$ cd repo
$ git branch 
      develop
    * master
$ git worktree add ../versions/develop develop
Preparing ../versions/bare/develop (identifier develop)
    HEAD is now at 4532215 first commit
$ git worktree list
    /..../repo              [master]
    /..../../versions/develop  4532215 [develop]
```

from @jdavid
> We just wrap `git_worktree_add`, so this looks more like a feature request first for libgit2, as it lacks the commit-ish optional parameter in git worktree add, see https://libgit2.org/libgit2/#HEAD/group/worktree/git_worktree_add . Maybe open an issue in libgit2?

Proposal would be to create the worktree off the existing name if it is committish (branch, tag, commit) and exists else create the branch as it currently behaves.

**Comment by tiennou** [comment]
This looks to be already available (unless I'm misunderstanding) through the `opts` argument of `git_worktree_add`, which has a `reference` [parameter](https://github.com/libgit2/libgit2/blob/HEAD/include/git2/worktree.h#L88). It seems this struct displeased docurium so its documentation doesn't show up…

**Comment by tiennou** [comment]
Closing because this seems to be supported, and the documentation is showing up correctly.
An additional caveat would be that #4630 might be causing your segfault.
