### ISSUE TITLE
Why is 0.26.7 marked as the latest release?

### ISSUE THREAD

**Issue by tpimh** [libgit2/libgit2#4855]
On this page https://github.com/libgit2/libgit2/releases the release 0.26.7 is marked as the latest release, but I think this is not correct, because 0.27.5 should be the latest release.

**Comment by ethomson** [comment]
It's chronological - we released 0.27.5 and 0.26.7 as security releases at (roughly) the same time.  0.26.7 apparently got tagged last, so, yes 0.26.7 is the _latest_ release.  This is not something that we can change, it's a designation that GitHub assigns.
