### ISSUE TITLE
Tests are failing on 32bit platforms

### ISSUE THREAD

**Issue by ignatenkobrain** [libgit2/libgit2#4868]
### Reproduction steps

Build and run tests on 32bit.

### Expected behavior

Tests pass.

### Actual behavior

```
  1) Failure:
buf::oom::grow [../tests/buf/oom.c:39]
  Expression is not true: git_buf_grow(&buf, 0x0fffffff) == -1
```

### Version of libgit2 (release number or SHA1)

0.27.7

### Operating system(s) tested

Fedora Rawhide.

**Comment by ethomson** [comment]
This was fixed in #4854.  Previously, we were trying to guess a magic number per-platform to pass to `*alloc` that would fail but not crash or cause errors in various static code analysis tools.  This was, obviously, crazy and brittle as you've noticed.

If the ppc64le failures aren't in this test, more details would be helpful.  Please open a new issue if you don't mind.  Thanks!

**Comment by ignatenkobrain** [comment]
@ethomson could you release new version of 0.26.x and 0.27.x with those fixes, please? Would save me (and not only) some time when updating in distributions.

**Comment by ethomson** [comment]
No, unfortunately these rely on the new pluggable allocation functionality, which is not something that we'd be able to backport.

As a stopgap measure, we could remove the tests from the next point releases.

**Comment by ignatenkobrain** [comment]
Or you could backport
https://github.com/libgit2/libgit2/commit/415a8ae9c9b6ac18f0524b6af8e58408b426457d,
that would be enough I guess.

**Comment by awilfox** [comment]
Just hit this packaging 0.27.7 for Adélie on all 32-bit architectures (ppc32, armv7, i586).  Backporting 415a8ae involved changing a single context line (from _dispose back to _free).

If anyone else is running in to this, you can use [the backport patch we made](https://code.foxkit.us/adelie/packages/blob/0f54263183261c3d26e59fa25de6f39517fb0231/user/libgit2/test-32bit.patch).
