### ISSUE TITLE
Support for SSH ProxyCommand

### ISSUE THREAD

**Issue by logancollins** [libgit2/libgit2#4872]
The built-in SSH transport currently only supports socket connections directly to a remote host. I'm attempting to write support for Krypton (https://krypt.co) to work with libgit2, but the lack of ProxyCommand (which Krypton uses to perform its operations), means this is a bit of a non-starter unless:

1. I write my own custom transport, reimplementing all features of it on top of libssh2 again
2. The built-in transport is amended to support delegating to the host app for ProxyCommand-like behaviors

I'd prefer not to do the former, as that means not using the already great built-in SSH transport. With that in mind, here are some thoughts for how hooks to support ProxyCommand could be implemented in the library.

From my (limited) knowledge, OpenSSH-style ProxyCommand works, on Unix at least, by starting a subprocess by shell command (either via fork-exec or another method), setting up a socket between the host and subprocess via stdio, and passing all traffic into and out of that subprocess's socket as if it were the remote socket created for normal SSH operations. Krypton also works this way, using its `krssh` executable, which is a wrapper around `ssh`.

This is obviously all very specific to Posix, and implemented differently on Windows, and not supported at all on iOS due to the lack of multiprocess support. Also, most of ProxyCommand's details are stored in a user's SSH config file, and as such, it's unlikely that the `libgit2` library wants to handle anything that specific: SSH config files, exec'ing processes, etc.

With that in mind, the SSH transport currently creates its socket using `git_socket_stream_new`, passing it the expected host and port. A very simple option is to create a callback that asks the host application to create the socket for `libgit2` before this, taking the host and port as arguments, and returning the file descriptor to be used by the libssh2 implementation. This would allow the host app to perform the actual socket creation, or pass through to fall back on the default behavior. The library would not need to handle ProxyCommand-related cross-platform issues. Since the socket is just a file descriptor either way, libssh2 likely doesn't care?

This does, however, introduce a remote callback that is very specific to the SSH transport. I've been thinking about better ways to abstract this operation out (similar to how credential callbacks work, as those have SSH-specific functionality), but have not come up with anything concrete, as this is a very specific case related mostly to just SSH over the other transport types.

I'd love to hear the project contributors' thoughts on how best something like this should be implemented. I'm happy to work on it, but definitely wanted to propose everything and get some feedback before I got started making API-related changes to a fork of the project.

Thanks!

### Version of libgit2 (release number or SHA1)

Currently I am at tag 0.27.0.

### Operating system(s) tested

macOS 10.14

**Comment by pks-t** [comment]
The underlying issue is that libssh2 itself doesn't care about ~/.ssh/config. It has been a source of complaint for many users who were bitten by this, and I myself find it unfortunate, too. But we certainly do not want to implement support for parsing the SSH configuration ourselves, and I think implementing just a subset of it that is not even applied via ~/.ssh/config is not really worth it.

One solution would be to implement another transport based on libssh that can be chosen instead of the libssh2-based transport at build-time. As far as I know, libssh supports a subset of valid options of the SSH configuration file, including ProxyCommand, so your use case would certainly be supported. But compared to only writing special code for handling ProxyCommand, you get a whole bunch of things for free by using libssh instead, most importantly the aspect that it "just works" for users who already have their ~/.ssh/config set up.

I've never worked with libssh, but I can't imagine it being too hard to implement this new transport when one has the existing SSH transport as a reference already. But please take this statement with a grain of salt.

**Comment by logancollins** [comment]
Thanks for the thoughts! I agree, it's definitely not something the library should be concerned with in parsing ~/.ssh/config.

We are very heavily on libssh2 as well, so it makes sense to continue doing so with libgit2. We use libssh2 in two other major places unrelated to Git, and we're already parsing the configs in a central place, so it likely makes more sense for us just to be able to configure the libgit2 SSH transport with specific options.

With that in mind, I've forked the library and made some API additions that adds additional callback capability when creating an SSH transport, specifically to allow the application to specify a custom socket to operate on (instead of the default INET socket, so ProxyCommand can work), and also to allow a callback for setting options on the `LIBSSH2_SESSION *` object, as we need the ability to set specific cipher, key-exchange, and MAC settings parsed out of the user's config.

I'm planning on filing a pull request soon; Your response is driving me to do it sooner! So, look forward to that, I guess, and I'm welcoming of feedback on it as to whether my changes are even sane.

**Comment by axkibe** [comment]
Do I understand it correctly, that this feature like this would also create the ability to keep ssh connections alive to a particular host?

Right now it seems libgit2 will reopen a ssh connection with a specific host for every fetch/push. While with canonical git/ssh one can setup "ControlMasters" in ~/.ssh/config. 

I wouldn't mind managing the connection in the host app. (I think everyone agrees parsing ~/.ssh/config is a non goal) But I don't see a possibility to so manually in the host app as the situation is, right?

**Comment by bergkvist** [comment]
Is it possible to have libgit2 use OpenSSH instead of libssh2?

**Comment by ethomson** [comment]
> Is it possible to have libgit2 use OpenSSH instead of libssh/libssh2?

Actually, I've been working on this. See https://github.com/libgit2/libgit2/tree/ethomson/openssh

**Comment by ethomson** [comment]
@bergkvist see #6617 - this is really aimed at interactive usage in a command-line application. I'd be curious how (or if) it works for you?

**Comment by ethomson** [comment]
Closing this — OpenSSH support has landed and is optional

**Comment by logancollins** [comment]
This issue was originally about adding appropriate hookes in libgit2 for using ProxyCommand with libssh2 (something I wrote and am still maintaining on our fork of libgit2). Does this support add the appropriate hooks to make this possible when the client is using libssh2 and not OpenSSH?

**Comment by WWWwgc** [comment]
@logancollins Hello, I'm currently working on Git support for the SSH protocol. We're using libssh2 as the backend, but it seems libssh2 doesn't support connecting to the repository using a proxy; it only succeeds when connecting without a proxy. My current idea is to simply establish a TCP connection and then return the socket to the libssh2 library for further SSH protocol processing. However, I haven't found any functions that can pass the socket to the libssh2 backend. Could you provide some assistance? Thank you very much.
