### ISSUE TITLE
cmake error on Ubuntu 12.04.5 LTS

### ISSUE THREAD

**Issue by zjuchujinjin** [libgit2/libgit2#4876]
You are opening a _bug report_ against the libgit2 project: we use
GitHub Issues for tracking bug reports and feature requests.  If you
have a question about an API or usage, please ask on StackOverflow:
http://stackoverflow.com/questions/tagged/libgit2.  If you want to
have high-level discussions about the libgit2 project itself, visit
https://github.com/libgit2/discussions.

Otherwise, to report a bug, please fill out the reproduction steps
(below) and delete these introductory paragraphs.  Thanks!

### Reproduction steps
- download the code
- git checkout v0.27.5
- cd libgit2
- mkdir build && cd build
- cmake ..

### Actual behavior
-- The C compiler identification is GNU
CMake Error: Could not find cmake module file: /home/git/libgit2/build/CMakeFiles/2.8.12.2/CMakeCCompiler.cmake
-- Check for working C compiler: /usr/bin/gcc

### Version of libgit2 (release number or SHA1)
v0.27.5

### Operating system(s) tested
Distributor ID: Ubuntu
Description:    Ubuntu 12.04.5 LTS
Release:        12.04

**Comment by pks-t** [comment]
I really ain't got any clue why this should fail with this particular error message. Could you please post the output of cmake with the "--trace" flag? So:

```
cd libgit2
rm -r build && mkdir build
cd build
cmake --trace ..
```

**Comment by ethomson** [comment]
Going to go ahead and close this - we'll reopen if you provide additional details.
