### ISSUE TITLE
revwalk hide callback not changeable?

### ISSUE THREAD

**Issue by TheBB** [libgit2/libgit2#4887]
The documentation for *git_revwalk_new* says

> This revision walker uses a custom memory pool and an internal commit cache, so it is relatively expensive to allocate.
> 
> For maximum performance, this revision walker should be reused for different walks.

This is facilitated by *git_revwalk_reset* which removes all state on the revwalk object *except* (it seems) the hide callback function. This would be fine if I could just unset the callback myself, but *git_revwalk_add_hide_cb* errors out if a callback is already set, even if all I'm trying to do is to set it to `NULL`.

So it seems in the current state that the revwalk object can be reused but only if you want to use the same callback function. This seems a little restrictive, and I don't see any reason why we can't change the callback, either in *git_revwalk_add_hide_cb* or *git_revwalk_reset*, or both.

I'd be happy to submit a fix so long as someone indicates which solution is preferable.

**Comment by ethomson** [comment]
> This is facilitated by git_revwalk_reset which removes all state on the revwalk object except (it seems) the hide callback function.

This _feels_ right to me, without having thought about it in depth.  When I think about resetting this, it simply starts over at the beginning, it doesn't remove the configuration.

> This would be fine if I could just unset the callback myself, but git_revwalk_add_hide_cb errors out if a callback is already set, even if all I'm trying to do is to set it to NULL.

Indeed, this is regrettable.  I think that it's absolutely reasonable to be able to clear a `hide_cb` that you've already set.

> I'd be happy to submit a fix so long as someone indicates which solution is preferable.

Awesome!  🎉
