### ISSUE TITLE
Clone fails with core.logAllRefUpdates=always

### ISSUE THREAD

**Issue by bk2204** [libgit2/libgit2#4889]
### Reproduction steps

1. `git config --global core.logAllRefUpdates always`
1. Attempt to clone a repository using libgit2 or a language wrapper
1. Receive an error: "failed to parse 'always' as a boolean value"

### Expected behavior

The git configuration is honored and the clone happens successfully.

### Actual behavior

An error occurs.  The clone fails.

### Version of libgit2 (release number or SHA1)

git2go v27 (libgit2 838a2f2918b6d9fad8768d2498575ff5d75c35f0)

I've confirmed that this should be broken in master as well, as on master the option is read as a boolean value, and "always" is not a boolean value.

### Operating system(s) tested

macOS

**Comment by ethomson** [comment]
Thanks for reporting this, and thanks @tiennou for the quick fix!

**Comment by bk2204** [comment]
That's great!  Thanks so much for this.

**Comment by tiennou** [comment]
This is now fixed, though I can't say if it made it in a release. Thanks for the report @bk2204 !

**Comment by pks-t** [comment]
Not yet, it is only going to be part of the soon-to-be-released v0.28.0
