### ISSUE TITLE
Mismatch between documentation and STATIC_CRT default in CMakeLists.txt

### ISSUE THREAD

**Issue by xleclercq** [libgit2/libgit2#4893]
On this page: https://libgit2.org/docs/guides/build-and-link/ it says:
"STATIC_CRT | (MSVC Only) By default, libgit2 will link to a DLL version of the C runtime."
This seems to be incorrect as in the CMakeLists.txt it says:
"OPTION(STATIC_CRT		"Link the static CRT libraries"		 		 ON)"

**Comment by xleclercq** [comment]
The THREADSAFE option also seems to be ON by default while the documentation says the default is off.

**Comment by ethomson** [comment]
Thanks for noticing, this document is indeed out of date.

**Comment by ethomson** [comment]
Fixed via https://github.com/libgit2/libgit2.github.com/pull/89
