### ISSUE TITLE
Diff errors out failing to find the config if HOME=/dev/null

### ISSUE THREAD

**Issue by carlosmn** [libgit2/libgit2#4897]
### Reproduction steps

1. Set `HOME=/dev/null`
1. Try to open the global configuration (or have `git_diff_tree_to_tree` do it as part of operation

### Expected behavior

Ignore being unable to find the global configuration

### Actual behavior

It returns an error. The stack trace I have is in ruby because we're hipsters but it boils down to calling diff in libgit2 (slightly redacted). This seems to be restricted to when `HOME` is a directory. Setting it to nonexitent paths does work.

```
[...]: failed to stat '/dev/null/.gitconfig'
[...]/gems/rugged-0.27.0.22.g238bca5/lib/rugged/tree.rb:149:in `diff_tree_to_tree'
[...]/gems/rugged-0.27.0.22.g238bca5/lib/rugged/tree.rb:149:in `diff'
[...]/gems/github-linguist-7.1.2/lib/linguist/repository.rb:139:in `compute_stats'
```

### Version of libgit2 (release number or SHA1)

v0.27.5

### Operating system(s) tested

Debian

**Comment by pks-t** [comment]
Huh, I can't reproduce this error. The following test case first sets HOME to /dev/null and then calls `git_diff_tree_to_tree`, but it passes just fine on my system:

```
diff --git a/tests/diff/tree.c b/tests/diff/tree.c
index e4b2a8bbe..c16c2ddf8 100644
--- a/tests/diff/tree.c
+++ b/tests/diff/tree.c
@@ -372,6 +372,18 @@ void test_diff_tree__symlink_blob_mode_changed_to_regular_file(void)
 	cl_assert_equal_i(0, expect.file_status[GIT_DELTA_TYPECHANGE]);
 }
 
+void test_diff_tree__symlink_blob_mode_changed_to_regular_file_home_dev_null(void)
+{
+	cl_git_pass(cl_setenv("HOME", "/dev/null"));
+	process_tree_to_tree_diffing("7fccd7", "806999");
+
+	cl_assert_equal_i(3, expect.files);
+	cl_assert_equal_i(2, expect.file_status[GIT_DELTA_DELETED]);
+	cl_assert_equal_i(0, expect.file_status[GIT_DELTA_MODIFIED]);
+	cl_assert_equal_i(1, expect.file_status[GIT_DELTA_ADDED]);
+	cl_assert_equal_i(0, expect.file_status[GIT_DELTA_TYPECHANGE]);
+}
+
 void test_diff_tree__symlink_blob_mode_changed_to_regular_file_as_typechange(void)
 {
 	/*
```

**Comment by pks-t** [comment]
I can reproduce with our diff example. There's probably some caching of paths going on

**Comment by kbrock** [comment]
I think this error is due to not having privilege to read the directory vs the directory not existing
