### ISSUE TITLE
Add Common Lisp to list of languages with libgit2 bindings

### ISSUE THREAD

**Issue by pfdietz** [libgit2/libgit2#4907]
There are Common Lisp bindings for libgit2, in the cl-git project, which you may want to add to your list of languages with libgit2 bindings:

https://github.com/russell/cl-git

This project with dependencies is available in the standard Quicklisp distribution:

https://www.quicklisp.org/beta/

**Comment by ethomson** [comment]
It looks like cl-git hasn't been updated in quite some time.  Is there a fork of that project that's been updated or another set of common lisp bindings?

**Comment by pfdietz** [comment]
You're right.  This would have to be brought up to date with current libgit2 before it should be added to the list.

**Comment by ethomson** [comment]
Please do open a new issue (or better yet - a pull request) if you've picked up cl-git and started moving it forward again.  🙇
