### ISSUE TITLE
document regarding git_time_t should be clear about its unit

### ISSUE THREAD

**Issue by shi-yan** [libgit2/libgit2#4908]
### Reproduction steps

This is a documentation bug. Wherever the type git_time_t is mentioned in the document or in the example, there is no mentioning of its unit. 

Is this the milliseconds since the Epoch or the seconds since the Epoch?

https://github.com/libgit2/libgit2/commit/b5c00c6d41ff4eb809f7deda38fe61ccaacb7cbf

https://libgit2.org/libgit2/#HEAD/group/signature/git_signature_new

Similarly in examples, large, incomprehensible integers are used for git_time_t, hard to understand what they mean.

https://libgit2.org/libgit2/ex/HEAD/general.html#git_signature_new-80

  git_signature_new(&author,
      "Scott Chacon", "schacon@gmail.com", 123456789, 60);
  git_signature_new(&committer,
      "Scott A Chacon", "scott@github.com", 987654321, 90);

### Expected behavior

The document should be clear about the type's meaning. the current description "time when the action happened" isn't a very useful guide on using this api.

### Version of libgit2 (release number or SHA1)
b5c00c6d41ff4eb809f7deda38fe61ccaacb7cbf
### Operating system(s) tested
n/a

**Comment by ethomson** [comment]
Thanks!

**Comment by shipof123** [comment]
It is in seconds, I believe, as evidenced by  [(this)](https://github.com/libgit2/libgit2/blob/e6cdd17c846648aa8e1e025fa1988475886a551e/src/date.c) at line 51
