### ISSUE TITLE
git_annotated_commit_from_ref() fails if passed in reference is a tag

### ISSUE THREAD

**Issue by milke** [libgit2/libgit2#4909]
I don't know if this is on purpose, but if a (non-lightweight) tag is passed as a reference to git_annotated_commit_from_ref(), it fails. That's because target oid of resolved reference passed to annotated_commit_init_from_id() belongs to the tag, not to a commit. For this to work, the (non-lightweight) tag has to be peeled to a commit, and then pass that commit's oid to annotated_commit_init_from_id().

### Operating system(s) tested: macOS 10.14.2

**Comment by carlosmn** [comment]
This is definitely not on purpose, as the point of annotated commits is to pass in whatever other forms of getting to it there are.
