### ISSUE TITLE
Static Compiling with c-ares

### ISSUE THREAD

**Issue by dgoo2308** [libgit2/libgit2#4912]
With the removal of curl for opening connections, how can we compile a static package that does not rely on a shared c lib for getadressinfo? (dlopen)

Is there support for compiling with e..g. [c-ares](https://github.com/c-ares/c-ares.git)?

My Application runs in a container with unknown,missing or different versions of glibc, which makes it vital that libgit2 can be fully static compiled without dlopen.

For this I have curl compiled static with c-ares with libgit2 v0.26.

**Comment by ethomson** [comment]
I'd be happy to take a PR to support alternate resolution libraries. This hasn't had any activity in a while, so I'm closing; happy to review a PR, though.
