### ISSUE TITLE
Expected date for next release?

### ISSUE THREAD

**Issue by stanhu** [libgit2/libgit2#4923]
@ethomson Thanks for your work in this project! I was wondering when we might be able to expect a new release. I was hoping to ship changes that haven't been part of a new release yet:

* https://github.com/libgit2/libgit2/pull/4542
* https://github.com/libgit2/rugged/pull/774

**Comment by ethomson** [comment]
v0.28.0 is released.  Thanks for your patience!

**Comment by stanhu** [comment]
Thanks! Will Rugged see a release soon?
