### ISSUE TITLE
git_branch_lookup should accept GIT_BRANCH_ALL

### ISSUE THREAD

**Issue by eaigner** [libgit2/libgit2#4938]
Unfortunately `git_branch_lookup` does not support `GIT_BRANCH_ALL` as branch type. It seems that there should be no reason for this, since it just restricts the input options for the branch type and basically makes it a programming error if `GIT_BRANCH_ALL` is supplied.

Wouldn't it be more useful and less error prone to support `GIT_BRANCH_ALL` and just try to look up local branches first and if nothing is found, search for a remote branch?

**Comment by ethomson** [comment]
🤷‍♂️  I don't see any reason why not.

**Comment by ethomson** [comment]
Fixed via #5000
