### ISSUE TITLE
git_odb_foreach continues looping after callback returns > 0

### ISSUE THREAD

**Issue by zlikavac32** [libgit2/libgit2#4946]
Hi, 

in [include/git2/odb.h:246](https://github.com/libgit2/libgit2/blob/22d2062d954dcb88fa3dc65281d3f3d88ae87d68/include/git2/odb.h#L246) it states `Return a non-zero value from the callback to stop looping.`

Implementation in [odb.c:1263](https://github.com/libgit2/libgit2/blob/22d2062d954dcb88fa3dc65281d3f3d88ae87d68/src/odb.c#L1263) considers only values less than 0 as a condition to finish looping.

So I'm not sure whether this is a bug or not. It's true that public API allows any non zero value, but perhaps implementation makes more sense.

### Reproduction steps

Depends. If this is considered a bug, than any `return > 0` from callback.

### Expected behavior

Depends. If this is considered a bug, then looping should exit for `return > 0`.

### Actual behavior

When callback returns value greater than 0, looping still continues.

### Version of libgit2 (release number or SHA1)

Current `master` (- `22d2062d954dcb88fa3dc65281d3f3d88ae87d68`) and from when, don't know :).

### Operating system(s) tested

Arch, but it doesn't matter.

Thank you for this cool library.

**Comment by ethomson** [comment]
Thanks for reporting this - indeed we should be propagating positive return codes from the callback.
