### ISSUE TITLE
1.0 planning / next few releases

### ISSUE THREAD

**Issue by ethomson** [libgit2/libgit2#4960]
Hey, it's just shy of _five years ago_ when we did our [first planning for 1.0](https://github.com/libgit2/libgit2/issues/2136).  😆😢😭

But seriously, here's my thinking for a 1.0 schedule:  let's be quality-focused over the next month or so.  I'm not _opposed_ to merging feature work, but I want to prioritize bug fixing and API stability.

* **0.28**:  January 2019  
Our next release.  We've done some (responsible!) refactoring of some public API for consistency.  But we're not quite done yet, and it's been _forever_ since we've had a release.  So I want to push out any further refactorings into the (yes) next release.  I want to button up the last few changes that need to land in _this_ release and get 0.28 out the door.  Many consumers are asking for a proper stable release and we're already behind.

* **0.99**:  Late February/Early March 2019
I'd like 0.99 to be a real prerelease of 1.0.  I'd like to see us finalize any (still responsible) refactoring of the public API.  I want to see us warning free on _all platforms_ not just the Unix platforms.  Fundamentally, I want this to really be a staging of the actual release, and we really expect this to be the *last* changes before 1.0.  We should expect the public APIs to be frozen, and only take minor bugfixes for 1.0.  I would expect that we'd branch off master for a freeze so that we can pick up post-1.0 development.  🤞 

* **1.0**: Late March 2019
Ideally contains no changes from 0.99 except to bump the version number and SONAME.  🎉

(I'm not strictly opposed to sneaking an 0.29 in here if we feel we need it but I want to focus on stablility, and get us to 1.0 reasonably quickly but responsibly.  I would rather iterate on an 0.99 and release an 0.99.1, 0.99.2 if that's actually necessary.  This is a subtle difference, I concede, but I think there's a psychological difference.)

Here's some things that I would like to see resolved and shipped in 0.99:

- [x] `git_off_t` is...  surprising.  Why is it signed?  Why is it named after an "offset" when it's a size?  Maybe these are fine, but they're not obvious, so let's reconsider it and fix it or document why it is the way it is.
- [x] What is going on with `include/git2/inttypes.h`?  We're publishing an inline `imaxdiv` function.  😢 
- [x] Remove `git_time_monotonic` from the public API.  It was added sort of hackily so that rugged could get some high-resolution timing for benchmarking.  But:  a) this is really outside the scope of libgit2, b) rugged ended up not using it anyway, and c) google suggests that absolutely _nobody_ is using it.  It's gross, remove it.
- [x] Windows amd64 (MSVC) has a bunch of warnings.  (Several of them are related to `git_off_t`, amusingly.)  Fix them all, then enable the MSVC equivalent of `-Werror`.
- [x] Get some resolution on #4935.  If we're going to use PCRE then we need to do that well before a 1.0.
- [x] Example improvements in #4956

**Comment by tiennou** [comment]
Should we do something about the bunch of PRs we talked about in the "Release" discussion thread as well ? How about having an "api-stability"/"1.0", just to keep track of PRs/issues ?

**Comment by pks-t** [comment]
What's the benefit of having v0.99 instead of simply saying v1.0-rc1?

And please, let's not say "Maybe do a v0.29 release". The next version is absolutely going to be v1.0. We already said "Maybe do a v0.28 release instead of v1.0", and here we are again saying the same.

With regards to your checkboxes: they all look perfectly reasonable to me and worthwhile to be fixed.

**Comment by pks-t** [comment]
By the way, one more thing. We should use the upcoming pre-v1.0-no-features period to tackle one of our most important topics: SHA256. If we don't get this going now, then we'll face severe problems as soon as git.git is ready to use SHA256. Because even if the implementation will be easier for us, we'll have quite a lot of pain points that will require a lot of mind numbing fixes. Especially when it comes to our tests.

**Comment by ethomson** [comment]
> By the way, one more thing. We should use the upcoming pre-v1.0-no-features period to tackle one of our most important topics: SHA256. If we don't get this going now, then we'll face severe problems as soon as git.git is ready to use SHA256. Because even if the implementation will be easier for us, we'll have quite a lot of pain points that will require a lot of mind numbing fixes. Especially when it comes to our tests.

Tell me more about this?  What do you see needing to change in the public API here to support sha256?

**Comment by ethomson** [comment]
> What's the benefit of having v0.99 instead of simply saying v1.0-rc1?

I posit that people are more likely to install a “real release” than a “release candidate”.  We didn’t see people installing the 0.28.0 release candidate, for instance.  But we got several reports that our very compatible deprecation attempts weren’t very compatible as soon as 0.28 was really released.

**Comment by pks-t** [comment]
On Fri, Feb 15, 2019 at 01:45:29PM +0000, Edward Thomson wrote:
> > By the way, one more thing. We should use the upcoming
> > pre-v1.0-no-features period to tackle one of our most
> > important topics: SHA256. If we don't get this going now,
> > then we'll face severe problems as soon as git.git is ready
> > to use SHA256. Because even if the implementation will be
> > easier for us, we'll have quite a lot of pain points that
> > will require a lot of mind numbing fixes. Especially when it
> > comes to our tests.
> 
> Tell me more about this?  What do you see needing to change in
> the public API here to support sha256?

I don't suspect any changes are required. We should be able to
deduce which hash to use from a given repo in most cases. And as
we do not expose the hashing functions we're fine to change them.

I'm only worried about us starting work on it much too late. I
don't want to live in a world where libgit2 starts to become
unusable because users start to migrate to SHA256. So I think
that we should try to use the pre-1.0-calm to refactor our
hashing internals here.

**Comment by pks-t** [comment]
On Fri, Feb 15, 2019 at 07:25:00AM -0800, Edward Thomson wrote:
> > What's the benefit of having v0.99 instead of simply saying v1.0-rc1?
> 
> I posit that people are more likely to install a “real release”
> than a “release candidate”.  We didn’t see people installing
> the 0.28.0 release candidate, for instance.  But we got several
> reports that our very compatible deprecation attempts weren’t
> very compatible as soon as 0.28 was really released.

True, I very much agree.

**Comment by ethomson** [comment]
By the way, I have a name in mind for our 1.0 release.  "Luftschloss (air castle)".  The fluent German speakers can correct me, but my understanding is:

> This refers to an impossible or unrealistic dream -- like building a castle in the air -- and is used to describe that which, sadly, just cannot be achieved.

This seems appropriate for something that we sat down in a meeting room to plan ... 5 years ago?

**Comment by pks-t** [comment]
On Sat, Feb 01, 2020 at 02:48:37AM -0800, Edward Thomson wrote:
> By the way, I have a name in mind for our 1.0 release.  "Luftschloss
> (air castle)".  The fluent German speakers can correct me, but my
> understanding is:
> 
> > This refers to an impossible or unrealistic dream -- like building a
> > castle in the air -- and is used to describe that which, sadly, just
> > cannot be achieved.

Sounds about right.

> This seems appropriate for something that we sat down in a meeting
> room to plan ... 5 years ago?

Definitely. Seems like a good fit to me ;)

**Comment by cuviper** [comment]
Would it be possible to abstract the ssh backend before 1.0, so libssh2 isn't baked into libgit2's API? AFAICS the only exposure is in the callbacks in `include/git2/credential.h`. Even if libssh support isn't done in time for 1.0, perhaps the API can at least be _ready_ for alternates.
(issue #5225, WIP pull request #5253)

**Comment by ethomson** [comment]
libssh support won't be done in time for 1.0.  There is no more time.  😀   1.0 is _done_.

v0.99 is the pre-release for v1.0.  We would have called it v1.0rc, except that our experience is that calling things "release candidates" doesn't give them good visibility.  Calling it v0.99 instead was a forcing function.

But that's ok!  There's no rush.  We need to find a way to cram libssh support into the library in a way that doesn't break backward compatibility.  That's not tied to v1.0, that's something that we started guaranteeing after v0.28.

Maybe that's new structures and new functions with compatibility wrappers.  There's some [prior art](https://github.com/libgit2/libgit2/blob/master/include/git2/deprecated.h) to look at.

**Comment by cuviper** [comment]
OK, thanks, good to know libssh won't be out of the question for the future.

**Comment by ethomson** [comment]
TODAY IS THE DAY.
