### ISSUE TITLE
git_worktree_add fails on master branch with already checked out

### ISSUE THREAD

**Issue by mjnz** [libgit2/libgit2#4977]
Other branches work all OK just seems to be the master that fails.  Note that the repo is bare just in case that has any effect.
 
### Reproduction steps
```
git clone --bare url
```
```
    git_reference_lookup(ref, Handle, 'refs/heads/master')
    git_worktree_add_init_options(@opts, GIT_WORKTREE_ADD_OPTIONS_VERSION);
    opts.ref := ref;
    r := git_worktree_add(wt, Handle, 'worktreename', '/some/path', @opts)
```
### Expected behavior
r = 0 (Success)

### Actual behavior
r = -4 (Fail)
Error message = "reference is already checked out"

### Version of libgit2 (release number or SHA1)
0.28

### Operating system(s) tested
Windows

### Additional Information
After the failure partial work tree structure is left behind which maybe should have been cleaned up or maybe the validity checks should happen before any structure gets created - which may or may not be possible.  

Anyway if I clear out the invalid worktree structure that was left behind and run
```
git worktree add --checkout /some/path master
```
it works just fine so we know that the master was not checked out anywhere else

**Comment by ethomson** [comment]
Thanks for reporting this @mjnz, and thanks for the fix @pks-t.
