### ISSUE TITLE
visibility of deprecated functions like giterr_last is hidden

### ISSUE THREAD

**Issue by bearsh** [libgit2/libgit2#4978]
### Reproduction steps
build libgit2

### Expected behavior
deprecated functions like `giterr_last` are visible and end up in the library, linking against them should just work

### Actual behavior
symbol is hidden in object file and doesn't end up in library
```bash
$ less build/src/CMakeFiles/git2internal.dir/errors.c.o | grep giterr_last
    37: 00000000000004c0     5 FUNC    GLOBAL HIDDEN     1 giterr_last
$ less /var/tmp/portage/dev-libs/libgit2-0.28.0/image/usr/lib64/libgit2.so.0.28.0 | grep giterr_last # no output
```
if I remove `-fvisibility=hidden` symbol is visible and ends up in library after linking

### Version of libgit2 (release number or SHA1)
0.28.0

### Operating system(s) tested
Gentoo Linux

**Comment by bearsh** [comment]
following patch seems to _fix_ the problem as it marks also the deprecated functions visible:
```diff
--- a/src/errors.c
+++ b/src/errors.c
@@ -11,6 +11,9 @@
 #include "posix.h"
 #include "buffer.h"
 
+#undef GIT_DEPRECATE_HARD
+#include "git2/deprecated.h"
+
 /********************************************
  * New error handling
  ********************************************/
```

**Comment by ethomson** [comment]
Hrmf.  I think that this is happening because we defined `GIT_DEPRECATE_HARD` in `CMakeLists.txt`, which means that the library ended up getting created without actually setting `__attribute__((visibility("default")))` on the deprecated functions.

That was an unintended consequence indeed.

**Comment by ethomson** [comment]
Thanks for the helpful report; I opened #4979 to fix this up.

**Comment by ethomson** [comment]
I did a decent amount of testing here, but would you mind sanity checking #4979 to make sure that this is fixed in your environment?  I want to cut an 0.28.1 quickly to resolve this but I want to make sure that I _actually_ resolve it.  😀

**Comment by bearsh** [comment]
Thanks for the fast response.
I checked #4979 and it works for me...

**Comment by ethomson** [comment]
Thanks for reporting this, [v0.28.1](https://github.com/libgit2/libgit2/releases/tag/v0.28.1) should resolve this.
