### ISSUE TITLE
git_apply corrupts file if no NL at EOF

### ISSUE THREAD

**Issue by eaigner** [libgit2/libgit2#4993]
### Reproduction steps

- Create a file `lipsum.txt` with the following contents (no NL at EOF!)

```
Lorem ipsum dolor sit amet, consectetur adipiscing elit.
Nam lacinia hendrerit nibh, at tempor erat cursus eu.
In eros2 urna, aliquet id sodales vel, rhoncus nec ipsum.
Praesent dapibus risus eu metus egestas vehicula.
Morbi in condimantum risus, auctor malesuada massa.
Sed auctor, tellus at finibus convallis, massa lectus iaculis urna, eget malesuada ligula nunc at lacus.
Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
Vivamus vitae tortor erat.
Duis vitae pharetra sapien.
Integer auctor lacus sapien, vel vehicula ex mollis eu.
Cras odio ligula, ultrices ac facilisis in, volutpat eget metus.
In sed tincidunt felis, ut fringilla nisl.
Ut suscipit quam in lacus posuere semper.
Ut luctus vitae mi non faucibus.
Integer sit amet tortor nec lectus dapibus interdum vitae et nibh.
Morbi eget urna id dolor gravida posuere sit amet non diam.
Suspendisse sit amet diam dui.
```

- Commit the file
- Apply the following patch (from buffer)

```
diff --git a/lipsum.txt b/lipsum.txt
index b071d73..b70d77a 100644
--- a/lipsum.txt
+++ b/lipsum.txt
@@ -1,6 +1,6 @@
 Lorem ipsum dolor sit amet, consectetur adipiscing elit.
 Nam lacinia hendrerit nibh, at tempor erat cursus eu.
+In eros urna, aliquet id sodales vel, rhoncus nec ipsum.
-In eros2 urna, aliquet id sodales vel, rhoncus nec ipsum.
 Praesent dapibus risus eu metus egestas vehicula.
 Morbi in condimantum risus, auctor malesuada massa.
 Sed auctor, tellus at finibus convallis, massa lectus iaculis urna, eget malesuada ligula nunc at lacus.
```
### Expected behavior

The patch applies cleanly

### Actual behavior

The patch applies, but produces garbage characters at the end of the resulting file `<0x00>somerandommenorycontents`

### Version of libgit2 (release number or SHA1)

`master@1a107fac0fc88a4d74b64ffc9ae2fd178ba631c0` `v0.28.0-rc1`

### Operating system(s) tested

macOS 10.14.3 (18D109)

**Comment by eaigner** [comment]
As soon as `lipsum.txt` has a NL at the end, this issue doesnt arise. I've also noticed all files in the apply tests have a `NL` at the end, so this is not covered by tests.

**Comment by eaigner** [comment]
I made a small C test. Here the patch won't apply at all (the `git` binary will)

```
#include <git2.h>
#include <string.h>
#include <assert.h>
#include <stdio.h>

#define DIFF_APPLY_ISSUE \
    "diff --git a/test/lipsum.txt b/test/lipsum.txt\n" \
    "index b071d73..b70d77a 100644\n" \
    "--- a/test/lipsum.txt\n" \
    "+++ b/test/lipsum.txt\n" \
    "@@ -1,6 +1,6 @@\n" \
    " Lorem ipsum dolor sit amet, consectetur adipiscing elit.\n" \
    " Nam lacinia hendrerit nibh, at tempor erat cursus eu.\n" \
    "+In eros urna, aliquet id sodales vel, rhoncus nec ipsum.\n" \
    "-In eros2 urna, aliquet id sodales vel, rhoncus nec ipsum.\n" \
    " Praesent dapibus risus eu metus egestas vehicula.\n" \
    " Morbi in condimantum risus, auctor malesuada massa.\n" \
    " Sed auctor, tellus at finibus convallis, massa lectus iaculis urna, eget malesuada ligula nunc at lacus.\n"

int main() {
    git_repository *repo = NULL;
    git_diff *diff = NULL;

    git_libgit2_init();

    git_repository_open(&repo, ".");

    assert(git_diff_from_buffer(&diff, DIFF_APPLY_ISSUE, strlen(DIFF_APPLY_ISSUE)) == 0);
    assert(git_apply(repo, diff, GIT_APPLY_LOCATION_WORKDIR, NULL) == 0);

    git_diff_free(diff);

    git_libgit2_shutdown();
    return 0;
}
```

**Comment by eaigner** [comment]
Seems to be the same kind of memory corruption I had with another bug here. I'll debug this once and for all now. Starting to feel kind of stupid for opening bugs that are probably to a wrongly converted cstring or something. Will reopen when I have definitive info that is also mirrored via a C example.

**Comment by pks-t** [comment]
> Starting to feel kind of stupid for opening bugs that are probably due to a wrongly converted cstring or something.

That probably has happened to all of us ;)

**Comment by eaigner** [comment]
Nope! I actually found a memory bug. Patch incoming.

**Comment by eaigner** [comment]
The only reason I find those is because I have turned on guard malloc in Xcode. I don't know what the corresponding flag would be in `gcc` or `clang` but it would probably be good to run the test suites with those flags enabled.

**Comment by neithernut** [comment]
The CI already runs some jobs with valgind.

**Comment by pks-t** [comment]
Which obviously doesn't seem to be sufficient. Could we maybe also enable guard malloc on macOS CI?

/cc @ethomson?

**Comment by neithernut** [comment]
I think valgrind would have reported this if one of the tests would have contained a blob which does not end with a newline. As @eaigner pointed out, none of the tests triggered this out-of-bounds read.

**Comment by pks-t** [comment]
Of course, you're right. Anyway, we now do have a test and a fix for this issue via #4996

**Comment by ethomson** [comment]
> Which obviously doesn't seem to be sufficient. Could we maybe also enable guard malloc on macOS CI?

@tiennou do you know how to do this?  Is this as simple as setting these variables before execution?  https://developer.apple.com/library/archive/documentation/Performance/Conceptual/ManagingMemory/Articles/MallocDebug.html

**Comment by tiennou** [comment]
MallocStackLogging (and friends) is what's used to get the nice stacktraces from `leaks`. What we're missing might be `MallocScribble` (though I think I enabled it because it makes double-frees more visible), `MallocPreScribble`, and `MallocGuardEdges`, but I'm not certain what combination of those Xcode calls Guard Malloc.

**Comment by eaigner** [comment]
It's a separate setting, not a combination of both

![screen shot 2019-02-21 at 12 04 37](https://user-images.githubusercontent.com/112197/53164620-e7352400-35d0-11e9-9ddd-7a7d0e979043.png)
