### ISSUE TITLE
Test Failed

### ISSUE THREAD

**Issue by yjqiu** [libgit2/libgit2#5002]
somehow my test was failed after building. I put the part of the failed test below. All other tests are passed.

3: Test command: /mnt/silencer2/home/serein/app/libgit2/build/libgit2_clar "-v" "-sonline"
3: Test timeout computed to be: 9.99988e+06
3: Loaded 367 suites:
3: Started (test status codes: OK='.' FAILURE='F' SKIPPED='S')
3:
3: online::badssl...S
3: online::cloneFFFFFFFFFSFFSFFS.SS.F..SSSF
3: online::fetch.FF.F.FFFFF
3: online::fetchhead......
3: online::pushSSSSSSSSSSSSSSSSSSSSS
3: online::remotes......
3:
3:   1) Failure:
3: online::clone::network_full [/mnt/silencer2/home/serein/app/libgit2/tests/online/clone.c:116]
3:   Function call failed: (git_clone(&g_repo, "http://github.com/libgit2/TestGitRepository", "./foo", &g_options))
3:   error -17 - user rejected certificate for github.com
3:
3:   2) Failure:
3: online::clone::network_bare [/mnt/silencer2/home/serein/app/libgit2/tests/online/clone.c:131]
3:   Function call failed: (git_clone(&g_repo, "http://github.com/libgit2/TestGitRepository", "./foo", &g_options))
3:   error -17 - user rejected certificate for github.com
3:
3:   3) Failure:
3: online::clone::empty_repository [/mnt/silencer2/home/serein/app/libgit2/tests/online/clone.c:142]
3:   Function call failed: (git_clone(&g_repo, "http://github.com/libgit2/TestEmptyRepository", "./foo", &g_options))
3:   error -17 - user rejected certificate for github.com
3:
3:   4) Failure:
3: online::clone::can_checkout_a_cloned_repo [/mnt/silencer2/home/serein/app/libgit2/tests/online/clone.c:182]
3:   Function call failed: (git_clone(&g_repo, "http://github.com/libgit2/TestGitRepository", "./foo", &g_options))
3:   error -17 - user rejected certificate for github.com
3:
3:   5) Failure:
3: online::clone::clone_mirror [/mnt/silencer2/home/serein/app/libgit2/tests/online/clone.c:226]
3:   Function call failed: (git_clone(&g_repo, "http://github.com/libgit2/TestGitRepository", "./foo.git", &opts))
3:   error -17 - the SSL certificate is invalid
3:
3:   6) Failure:
3: online::clone::custom_remote_callbacks [/mnt/silencer2/home/serein/app/libgit2/tests/online/clone.c:256]
3:   Function call failed: (git_clone(&g_repo, "http://github.com/libgit2/TestGitRepository", "./foo", &g_options))
3:   error -17 - user rejected certificate for github.com
3:
3:   7) Failure:
3: online::clone::custom_headers [/mnt/silencer2/home/serein/app/libgit2/tests/online/clone.c:284]
3:   Function call failed: (git_clone(&g_repo, "http://github.com/libgit2/TestGitRepository", "./foo", &g_options))
3:   error -17 - user rejected certificate for github.com
3:
3:   8) Failure:
3: online::clone::cred_callback_failure_return_code_is_tunnelled [/mnt/silencer2/home/serein/app/libgit2/tests/online/clone.c:309]
3:   Function call failed: (git_clone(&g_repo, _remote_url, "./foo", &g_options))
3:   error -17 (expected -172) - user rejected certificate for github.com
3:
3:   9) Failure:
3: online::clone::cred_callback_called_again_on_auth_failure [/mnt/silencer2/home/serein/app/libgit2/tests/online/clone.c:343]
3:   Function call failed: (git_clone(&g_repo, _remote_url, "./foo", &g_options))
3:   error -17 (expected -7) - user rejected certificate for github.com
3:
3:   10) Failure:
3: online::clone::bitbucket_style [/mnt/silencer2/home/serein/app/libgit2/tests/online/clone.c:398]
3:   Function call failed: (git_clone(&g_repo, "https://libgit3@bitbucket.org/libgit2/testgitrepository.git", "./foo", &g_options))
3:   error -17 - user rejected certificate for bitbucket.org
3:
3:   11) Failure:
3: online::clone::bitbucket_uses_creds_in_url [/mnt/silencer2/home/serein/app/libgit2/tests/online/clone.c:416]
3:   Function call failed: (git_clone(&g_repo, "https://libgit3:libgit3@bitbucket.org/libgit2/testgitrepository.git", "./foo", &g_options))
3:   error -17 - user rejected certificate for bitbucket.org
3:
3:   12) Failure:
3: online::clone::can_cancel [/mnt/silencer2/home/serein/app/libgit2/tests/online/clone.c:459]
3:   Function call failed: (4321)
3:   error 4321 (expected -17) - user rejected certificate for github.com
3:
3:   13) Failure:
3: online::clone::ssh_auth_methods [/mnt/silencer2/home/serein/app/libgit2/tests/online/clone.c:506]
3:   Function call failed: (git_clone(&g_repo, "ssh://github.com/libgit2/TestGitRepository", "./foo", &g_options))
3:   error -1 (expected -7) - failed to start SSH session: Unable to exchange encryption keys
3:
3:   14) Failure:
3: online::clone::certificate_invalid [/mnt/silencer2/home/serein/app/libgit2/tests/online/clone.c:710]
3:   Function call failed: (GIT_ECERTIFICATE)
3:   error -17 (expected -1) - failed to start SSH session: Unable to exchange encryption keys
3:
3:   15) Failure:
3: online::clone::proxy_auto_not_detected [/mnt/silencer2/home/serein/app/libgit2/tests/online/clone.c:848]
3:   Function call failed: (git_clone(&g_repo, "http://github.com/libgit2/TestGitRepository", "./foo", &g_options))
3:   error -17 - user rejected certificate for github.com
3:
3:   16) Failure:
3: online::fetch::default_http [/mnt/silencer2/home/serein/app/libgit2/tests/online/fetch.c:48]
3:   Function call failed: (git_remote_fetch(remote, ((void *)0), &options, ((void *)0)))
3:   error -17 - the SSL certificate is invalid
3:
3:   17) Failure:
3: online::fetch::default_https [/mnt/silencer2/home/serein/app/libgit2/tests/online/fetch.c:48]
3:   Function call failed: (git_remote_fetch(remote, ((void *)0), &options, ((void *)0)))
3:   error -17 - the SSL certificate is invalid
3:
3:   18) Failure:
3: online::fetch::no_tags_http [/mnt/silencer2/home/serein/app/libgit2/tests/online/fetch.c:48]
3:   Function call failed: (git_remote_fetch(remote, ((void *)0), &options, ((void *)0)))
3:   error -17 - the SSL certificate is invalid
3:
3:   19) Failure:
3: online::fetch::doesnt_retrieve_a_pack_when_the_repository_is_up_to_date [/mnt/silencer2/home/serein/app/libgit2/tests/online/fetch.c:114]
3:   Function call failed: (git_clone(&_repository, "https://github.com/libgit2/TestGitRepository.git", "./fetch/lg2", &opts))
3:   error -17 - the SSL certificate is invalid
3:
3:   20) Failure:
3: online::fetch::can_cancel [/mnt/silencer2/home/serein/app/libgit2/tests/online/fetch.c:158]
3:   Function call failed: (git_remote_connect(remote, GIT_DIRECTION_FETCH, ((void *)0), ((void *)0), ((void *)0)))
3:   error -17 - the SSL certificate is invalid
3:
3:   21) Failure:
3: online::fetch::ls_disconnected [/mnt/silencer2/home/serein/app/libgit2/tests/online/fetch.c:172]
3:   Function call failed: (git_remote_connect(remote, GIT_DIRECTION_FETCH, ((void *)0), ((void *)0), ((void *)0)))
3:   error -17 - the SSL certificate is invalid
3:
3:   22) Failure:
3: online::fetch::remote_symrefs [/mnt/silencer2/home/serein/app/libgit2/tests/online/fetch.c:190]
3:   Function call failed: (git_remote_connect(remote, GIT_DIRECTION_FETCH, ((void *)0), ((void *)0), ((void *)0)))
3:   error -17 - the SSL certificate is invalid
3:
3:   23) Failure:
3: online::fetch::twice [/mnt/silencer2/home/serein/app/libgit2/tests/online/fetch.c:205]
3:   Function call failed: (git_remote_fetch(remote, ((void *)0), ((void *)0), ((void *)0)))
3:   error -17 - the SSL certificate is invalid
3:
3/6 Test #3: online ...........................***Failed   17.47 sec

**Comment by pks-t** [comment]
Judging from the paths, you probably use a Unix-based system, right? Which HTTPS backend did you use to compile libgit2? I'm asking because this is most likely a configuration issue of your SSL library which does not have the root certificates available that are required to talk to GitHub.

**Comment by yjqiu** [comment]
Yes. It is a Linux Cent OS.

I agree with that but I am not familiar with HTTPS backend you mentioned. Can you advise on how to find the information? I can look it up and paste it here. Thanks!

**Comment by ethomson** [comment]
@yjqiu can you paste the output of your `cmake` configuration step?

**Comment by yjqiu** [comment]
-- Checking prototype qsort_r for HAVE_QSORT_R_BSD - False
-- Checking prototype qsort_r for HAVE_QSORT_R_GNU - True
-- Could NOT find HTTP_Parser (missing:  HTTP_PARSER_INCLUDE_DIR HTTP_PARSER_LIBRARY)
-- http-parser version 2 was not found or disabled; using bundled 3rd-party sources.
--   Resolved libraries: /usr/lib64/libssh2.so
-- Enabled features:
 * threadsafe , threadsafe support
 * HTTPS , using OpenSSL
 * SHA , using CollisionDetection
 * http-parser , http-parser support (bundled)
 * zlib , using system zlib
 * SSH , SSH transport support

-- Disabled features:
 * debugpool , debug pool allocator
 * tracing , tracing support
 * SPNEGO , SPNEGO authentication support
 * iconv , iconv encoding conversion support

-- Configuring done
-- Generating done
-- Build files have been written to: /mnt/silencer2/home/serein/app/libgit2/build

**Comment by pks-t** [comment]
Could you please post the output of `openssl s_client -showcerts -connect github.com:443 </dev/null`? I want to make sure that your openssl distribution is set up correctly and has the required root certificates to be able to verify GitHub's certificate.

**Comment by yjqiu** [comment]
I was able to install it using yum. Thanks anyway!

**Comment by pks-t** [comment]
On Mon, Mar 18, 2019 at 10:38:03AM -0700, Yunjiang Qiu wrote:
> I was able to install it using yum. Thanks anyway!

Fair enough. Could you please close this ticket in case you
consider it solved, then?
