### ISSUE TITLE
Potential loose/packed ref race when deleting packed refs

### ISSUE THREAD

**Issue by ethomson** [libgit2/libgit2#5003]
As @peff noted in #4981:

> `refdb_fs_backend__delete_tail` doesn't have this bug, but I think creates its own race. It deletes the loose ref first, before touching `packed-refs`. During the moment between those two steps, a reader would see the `packed-refs` value as the authoritative one, but it's garbage at that point (it was _some_ previous value that the ref had, but it could be very old, and possibly not even a reachable object). This was fixed in upstream Git by [git/git@dc39e09](https://github.com/git/git/commit/dc39e099422b1d44f6230f557f94f7945c7521a7).

**Comment by pks-t** [comment]
Both #4984 and #5106 have been merged, so the race shouldn't exist anymore. Closing.
