### ISSUE TITLE
Diff contains binary data

### ISSUE THREAD

**Issue by eaigner** [libgit2/libgit2#5009]
When I add the attached `bin1.dat` to the index, a diff is produced, despite the file being completely random 120 bytes from `/dev/urandom`.

I am not sure what the expected behavior is, since the official `git` binary also seems to produce a nonsensical diff with binary chars.

I think the reason is that the binary data starts with a `\r` (`0x0D`) char.

[bin1.dat.zip](https://github.com/libgit2/libgit2/files/2911777/bin1.dat.zip)

### Reproduction steps

- Create a new repository
- Add the `/dev/urandom` generated `bin1.dat` (attached) to the index
- Generate a new diff with `git_diff_tree_to_workdir_with_index`
- Iterate over it with `git_diff_foreach`

### Expected behavior

- The diff has no deltas, because it's binary

### Actual behavior

- The diff produces a hunk of binary text

### Version of libgit2 (release number or SHA1)

9eb098d8614bdd0365140f6614441465123ce903

### Operating system(s) tested

macOS 10.14.3 (18D109)

**Comment by ethomson** [comment]
> I am not sure what the expected behavior is, since the official `git` binary also seems to produce a nonsensical diff with binary chars.

I believe that git examines the contents to determines if its binary (by looking for a NUL).  Our aim is to match git's behavior, so we should do the same.

If we're not behaving the same way that git does, then that's definitely an issue.  But if we are the same and you believe that git is in error then I'd encourage you to start a thread on the mailing list.

**Comment by eaigner** [comment]
I was just asking because I saw in the test cases that libgit2 also tries to match gits "errors".

**Comment by eaigner** [comment]
Here is the git diff, just FYI

![screen shot 2019-02-27 at 19 58 59](https://user-images.githubusercontent.com/112197/53515572-9474d400-3aca-11e9-9f9f-964762691b91.png)

**Comment by ethomson** [comment]
Curious if git can apply that diff?  😀
