### ISSUE TITLE
Cannot build libgit2 as part of Monodevelop

### ISSUE THREAD

**Issue by monoluser** [libgit2/libgit2#5016]
Hi! I'm unable to build Monodevelop because the compilation of (builtin) libgit fails. Is it an OpenSSL version issue?

### Reproduction steps
Running `make `to build monodevelop.

### Expected behavior
Monodevelop being built successfully.

### Actual behavior
Monodevlop cannot be built because libgit2 fails.

### Version of libgit2 (release number or SHA1)
e8b8948f5a07cd813ccad7b97490b7f040d364c4

### Operating system(s) tested
Generic Linux.

### Output
https://github.com/mono/monodevelop/files/2952061/monodevelop.log

**Comment by ethomson** [comment]
Yes.  It looks like the version of libgit2 included with monodevelop is quite old.  I suspect that you cannot update their version on your own (without also changing the way monodevelop invokes libgit2).

**Comment by tiennou** [comment]
I'm suspecting the reverse, actually. You're building against `Found OpenSSL: /usr/local/lib/libcrypto.so (found version "1.1.1")`, and our current Linux builds use "1.0.1f". I suspect more structs have been made opaque in the latest version.

**Comment by ethomson** [comment]
Our CI builds use 1.0.1 (via Ubuntu 16.04), but we build fine on 1.1.0g (which is what Ubuntu 18.04 uses).  I don't have anything with 1.1.1 in front of me, but I'd be a little surprised if they broke something.  (Though only a little.)

On the other hand, monodevelop is using a [three-year old version of libgit2](https://github.com/libgit2/libgit2/commit/e8b8948f5a07cd813ccad7b97490b7f040d364c4) (via LibGit2Sharp).

**Comment by pks-t** [comment]
I remember that we had some fixes for OpenSSL v1.1 compatibility over the last two releases. So a three-year old version of libgit2 is definitely expected to fail when trying to compile against OpenSSL v1.1, especially so as that version was released only 2.5 years ago.

**Comment by ethomson** [comment]
Not sure how to proceed here; it's unfortunate that the included version is quite old, but that's beyond our ability to service, I'm afraid.
