### ISSUE TITLE
support merge analysis for bare repos

### ISSUE THREAD

**Issue by rcoup** [libgit2/libgit2#5017]
### Reproduction steps

Call `git_merge_analysis()` or `git_merge_analysis_for_ref()` on a bare repository.

### Expected behaviour

Since we can do `git_merge_trees()` and other things on bare repositories, makes sense analysis should work too since it's non-destructive. From Slack:

> @ethomson
> it doesn't seem like that's something that should need a workdir for.
> i suspect that some refactoring just ended up shuffling the not-bare check there.

### Actual behaviour

It errors with `cannot merge. This operation is not allowed against bare repositories`. The bare repository check appears in `merge_heads()`:

https://github.com/libgit2/libgit2/blob/2e0a304839764236654e73d38fa380b317a3fac1/src/merge.c#L3115-L3116

### Version of libgit2 (release number or SHA1)

0.28.1 @ 2e0a304839764236654e73d38fa380b317a3fac1

### Operating system(s) tested

OSX

**Comment by rcoup** [comment]
Looks like [`git_merge()` already has a not-bare-repo check](https://github.com/libgit2/libgit2/blob/2e0a304839764236654e73d38fa380b317a3fac1/src/merge.c#L3275), are there any other merging functions that actually need the guard, or could it simply be removed from `merge_heads()`?

**Comment by ethomson** [comment]
> Looks like git_merge() already has a not-bare-repo check, are there any other merging functions that actually need the guard, or could it simply be removed from merge_heads()?

Looking at the history, this came in with #2183, so I think it was an effort to make `git_merge_status` fail in bare repositories.

Now, this raises another question: why do we really need _that_ to be non-bare?  I don't think it does.  It's possible that at some point in time it read `MERGE_HEAD` or something but I think it's okay to remove the bare check altogether.

Would you be interested in opening a PR?

**Comment by ethomson** [comment]
Fixed via #5022 - thanks for the report and the PR!
