### ISSUE TITLE
git_diff_from_buffer crashes if filenames have spaces in header

### ISSUE THREAD

**Issue by eaigner** [libgit2/libgit2#5029]
Parsing a diff using `git_diff_from_buffer` that has filenames with spaces in its `diff --git` header crashes libgit

Example:

```
#define PATCH_ORIGINAL_NEW_FILE_WITH_SPACE \
	"diff --git a/sp ace.txt b/sp ace.txt\n" \
	"new file mode 100644\n" \
	"index 000000000..789819226\n" \
	"--- /dev/null\n" \
	"+++ b/sp ace.txt\n" \
	"@@ -0,0 +1 @@\n" \
	"+a\n"

void test_diff_parse__new_file_with_space(void)
{
	const char *content = PATCH_ORIGINAL_NEW_FILE_WITH_SPACE;
	git_diff *diff;

	cl_git_pass(git_diff_from_buffer(&diff, content, strlen(content)));
	git_diff_free(diff);
}
```

crashes in `check_prefix:888`.

This diff was generated by adding a new file named `sp ace.txt` and running `git --cached`.

### Version of libgit2 (release number or SHA1)
`master`

### Operating system(s) tested

macOS 10.14.3 (18D109)

**Comment by ethomson** [comment]
Fixed via #5035
