### ISSUE TITLE
GIT_CHECKOUT_FORCE/SAFE should not be mutually exclusive

### ISSUE THREAD

**Issue by eaigner** [libgit2/libgit2#5031]
`GIT_CHECKOUT_FORCE` documentation reads

    Allow all updates to force working directory to look like index

and `GIT_CHECKOUT_SAFE`

    Allow safe updates that cannot overwrite uncommitted data

To me that doesn't necessarily mean that they are mutually exclusive, but when I try to check out a tree using `git_checkout_tree` with both flags, `GIT_CHECKOUT_SAFE` seems to be completely ignored and all current changes are lost.

To me the meaning of `GIT_CHECKOUT_SAFE` + `GIT_CHECKOUT_FORCE` would be "force the working directory to look like the index and proceed only if we have no uncommitted data".

Maybe its just a docfix, I don't know what is actually expected to happen in this case.

### Expected behavior

The checkout is aborted with uncommitted changes

### Actual behavior

The checkout proceeds deleting all uncommitted changes

### Version of libgit2 (release number or SHA1)

`master`

### Operating system(s) tested

macOS 10.14.3 (18D109)

**Comment by ethomson** [comment]
They are definitely mutually exclusive and `GIT_CHECKOUT_FORCE` wins.  This is by-design, and if we keep that design, then we should update the documentation.

> To me the meaning of GIT_CHECKOUT_SAFE + GIT_CHECKOUT_FORCE would be "force the working directory to look like the index and proceed only if we have no uncommitted data".

Can you expand on that a bit?  How is this different than `GIT_CHECKOUT_SAFE` alone?  If there's no uncommitted data, then there's nothing to force, AFAIK.

**Comment by eaigner** [comment]
I need to do some more digging, because I currently have a case where `GIT_CHECKOUT_SAFE` checks out the tree, even though I have uncommitted changes (without discarding the index).

**Comment by ethomson** [comment]
> I need to do some more digging, because I currently have a case where GIT_CHECKOUT_SAFE checks out the tree, even though I have uncommitted changes (without discarding the changes).

This is true - and should be identical to the behavior of git.  By default (with git's checkout and ours) you can have any changes staged, unstaged or uncommitted as long as they don't conflict with the changes being checked out.  eg:

```
hypnotoad:Temp/TestRepos/021% git status
On branch master
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	modified:   baz.c

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   foo.c

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	untracked

hypnotoad:Temp/TestRepos/021% git checkout update_to_bar
M	baz.c
M	foo.c
Switched to branch 'update_to_bar'
hypnotoad:Temp/TestRepos/021% git status
On branch update_to_bar
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	modified:   baz.c

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   foo.c

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	untracked
```

**Comment by eaigner** [comment]
Ah, ok. Was getting confused by this, because my unit test did trigger a conflict and thus reported the error correctly and when I tried it in my app there was no error. Its about time I made a docfix PR so this stuff doesn't confuse me again every 5 minutes 😉
