### ISSUE TITLE
Cannot parse gitconfig file if it is a symlink

### ISSUE THREAD

**Issue by musm** [libgit2/libgit2#5033]
I'm having issues where  `git_repository_open` will fail if my  user `~/.gitconfig` file is symlinked. 
The error given is
`:Config, failed to parse config file: Invalid configuration key`

**Comment by ethomson** [comment]
What version of libgit2 is exhibiting this behavior?

**Comment by musm** [comment]
Version v0.27.7

**Comment by pks-t** [comment]
I'm unfortunately unable to reproduce your issue, neither on current master nor on v0.27.7. Please have a look whether the tests in #5034 match what you describe

**Comment by musm** [comment]
Thanks. Strange, this might then be a downstream issue with Julia. I thought it was an upstream issue since we just make  a ccall to the shared library function  `git_repository_open`.  I'll try to investigate.

**Comment by musm** [comment]
I should have noted that this occurred in a `Cygwin` environment.

**Comment by musm** [comment]
Indeed, I can confirm symlinks work fine with windows. Just not in a Cygwin environment.

**Comment by musm** [comment]
I'm closing this since I'm not reproducing the bug.  Yesterday, I kept hitting this bug, and today it works after cleaning my environment and building julia again 😕 . Heisenbug....    I'll let you know if I see this cropping up again.

**Comment by pks-t** [comment]
Sure, thanks for keeping us up to date!
