### ISSUE TITLE
index: file status shown as DELETED in libgit but not git

### ISSUE THREAD

**Issue by eaigner** [libgit2/libgit2#5041]
I currently have a (corrupt?) repo on my hands that has a file still in its index, but the file is missing on disk. I don't think its an issue per-se with `libgit`, but `git` seems to not display any status for that file. Here are the files how they appear in the index.

![Screen Shot 2019-04-05 at 12 50 39](https://user-images.githubusercontent.com/112197/55623452-56db2900-57a3-11e9-92a6-479525c79fc9.png)

The file was apparently renamed at some point and the `ß` was changed to `ss`.

The strange thing is, `git status` seems to ignore this, while `libgit` shows a`DELETED` status item for the file with the `ß`, which is actually correct.

**Comment by ethomson** [comment]
This is pretty surprising.  Do you still have this repository?  If so, can you share it?  I'd love to take a look.

**Comment by eaigner** [comment]
No, I can't share it unfortunately. Not my code and not allowed to share (proprietary).

**Comment by eaigner** [comment]
I dont know how a repo could reach this state. Maybe a commit where a rename was not detected and the add staged separately?

**Comment by tiennou** [comment]
Is that on macos/HFS+ ? Those extended Latin characters make me suspect an UTF-8 normalization issue, that you've added (say) a NFKD path to the index, which we didn't renormalize while git did (or the reverse, most likely) ?

**Comment by eaigner** [comment]
It was committed on macOS/APFS as far as I know.

**Comment by tiennou** [comment]
IIRC I've seen a patch cover planning to add iconv support to `git.git`, but I can remember neither the timeframe nor the details. Was the underlying filesystem upgraded from HFS+, and if so, was the offending file added prior to that ?

https://mjtsai.com/blog/2017/06/27/apfs-native-normalization/ seems to imply APFS is now normalization-preserving :suspect:.

**Comment by ethomson** [comment]
> Does git.git itself do some sort of unicode normalization?

Yes.  `core.precomposeunicode` should affect how file paths are added to the index, converting canonically decomposed paths to canonically composed.

But converting an ß to ss is surprising.  Is ss the canonical decomposition of ß?  I'd be very surprised if so.

> IIRC I've seen a patch cover planning to add iconv support to git.git, but I can remember neither the timeframe nor the details. Was the underlying filesystem upgraded from HFS+, and if so, was the offending file added prior to that ?

You might be thinking about the patches to do conversion of _contents_ of files.  (Because mutating line endings wasn't bad enough.)

**Comment by eaigner** [comment]
@tiennou The commit in question was fairly recent (few weeks ago) done on macOS 10.14.4 or 10.14.3 I believe (with APFS).

**Comment by eaigner** [comment]
I was able to reproduce a minimal example. Here is what I did

```
era$ mkdir test
era$ cd test
era$ git init
Initialized empty Git repository in /Users/era/Desktop/test/.git/
era$ echo "test" > ß.txt
era$ git add .
era$ git cm first
[master (root-commit) 3de426f] first
 1 file changed, 1 insertion(+)
 create mode 100644 "\303\237.txt"
era$ mv ß.txt ss.txt
era$ git add .
era$ git cm "second"
[master 4f05aaf] second
 1 file changed, 1 insertion(+)
 create mode 100644 ss.txt
era$ git st
On branch master
nothing to commit, working tree clean
```

`git cm` is just my alias for commit -m

[test.zip](https://github.com/libgit2/libgit2/files/3073253/test.zip)

**Comment by tiennou** [comment]
There's this [SO question](https://stackoverflow.com/questions/23808611/git-checkout-remove-file-with-special-characters), linked from the blogpost above, which talks about hiccups with git and APFS filenames.

> You might be thinking about the patches to do conversion of contents of files.

Dunno, I was running around in circles searching for diff header parsing patches, so I'm pretty sure it was about filenames, but again, this might have been from sometime ago.

Thanks for the reproducer @eaigner! I hadn't realized you were `status`-ing after the commit.
