### ISSUE TITLE
Parsing of refspec in remote fetch configuration different from git

### ISSUE THREAD

**Issue by tmat** [libgit2/libgit2#5058]
Based on an issue reported in https://github.com/dotnet/sourcelink/issues/256.

### Reproduction steps

Add a configuration entry like so:

```
[remote "origin"]
        url = https://github.com/somerepo.git
        fetch = +refs/heads/package-*:refs/remotes/origin/package-*
```

and read remotes information using libgit2 APIs.

The issue is that the fetch refspec does not end with `/*`. libgit2 is able to read the configuration if the refspec does end with `/*`.

```
fetch = +refs/heads/package/*:refs/remotes/origin/package/*
``` 

### Expected behavior

Succeeds.

### Actual behavior

```
'+refs/heads/package-*:refs/remotes/origin/package-*' is not a valid refspec.
```

### Version of libgit2 (release number or SHA1)

libgit2-a904fc6

### Operating system(s) tested

Windows.

**Comment by pks-t** [comment]
Thanks for your report! git.git has indeed changed restrictions on refspecs to allow your scenario in 2015. Please see #5060 for my proposed fix.
