### ISSUE TITLE
publish a libgit2.wasm

### ISSUE THREAD

**Issue by ctaggart** [libgit2/libgit2#5059]
Please publish a libgit2.wasm, ideally to https://wapm.io/ ([announcement](https://medium.com/wasmer/announcing-wapm-the-webassembly-package-manager-18d52fae0eea)). There are a ton of user cases this will enable. My use case it to [transpile it to a .NET assembly](https://github.com/libgit2/libgit2sharp/issues/1675) to avoid shipping 9+ different native dlls of libgit2 with [Source Link](https://github.com/dotnet/sourcelink) and [GitVersioning](https://github.com/AArnott/Nerdbank.GitVersioning).

My understanding is that libgit2 needs to be be compiled with clang-8 and wasi-sysroot. It sounds like openssl dependency could be an issue. Some people wouldn't want to ship that. For both of the projects I've listed, I only need access to the local git folder.

**Comment by petersalomonsen** [comment]
https://www.npmjs.com/package/libgit2.js

built from: https://github.com/libgit2/libgit2/pull/4400

demo video: https://www.youtube.com/watch?v=rcBluzpUWE4

**Comment by ethomson** [comment]
Closing this, as @petersalomonsen has taken over the emscripten/webassembly efforts as [wasm-git](https://github.com/petersalomonsen/wasm-git).
