### ISSUE TITLE
support in-memory ssh keys

### ISSUE THREAD

**Issue by ccutrer** [libgit2/libgit2#5067]
libssh2 has a function libssh2_userauth_publickey_frommemory that allows getting the private key from memory, instead of reading from a file. this is useful if my key is stored in some alternative data store (an encrypted vault my application can access). right now I have to work around it by writing the key to a temporary file :(

**Comment by tiennou** [comment]
I think it's supported via [git_cred_ssh_key_memory_new](https://libgit2.org/libgit2/#HEAD/group/cred/git_cred_ssh_key_memory_new), though I can guarantee you that the libssh2 backend used will influence support (OpenSSL has the most, but it's installation-dependent so YMMV).

**Comment by ccutrer** [comment]
oh perfect! I didn't see that. I guess I just needed to scroll down further.
