### ISSUE TITLE
.gitignore parsing: BOM not skipped

### ISSUE THREAD

**Issue by tmat** [libgit2/libgit2#5071]
### Reproduction steps

The parser does not skip byte-order-mark.

Consider `.gitignore` file with the following binary content:
```
EF BB BF 78 2E 74 78 74
```

That is, text `x.txt` is encoded in UTF8 with BOM.

### Expected behavior

`git_ignore_path_is_ignored("x.txt")` returns true.
Compare with output of `git check-ignore "x.txt"`.

### Actual behavior

`git_ignore_path_is_ignored("x.txt")` returns false. 

### Version of libgit2 (release number or SHA1)

a904fc6d12ffc20aa1a238a78000921494222e89

### Operating system(s) tested

Windows

**Comment by ethomson** [comment]
Interesting.  We updated config parsing to handle BOMs, while we're fixing this we should also make a pass over attribute files and any other config-like text file bits (submodule definitions?) and validate git's behavior vs ours.
