### ISSUE TITLE
cache: crash on evict

### ISSUE THREAD

**Issue by eaigner** [libgit2/libgit2#5081]
I have some sporadic crashes when using a `revwalk` object. Here is the log:

```
malloc: *** error for object ...: pointer being freed was not allocated

#6. Crashed: NSOperationQueue 0x60000039d3c0 (QOS: USER_INITIATED)
0  libsystem_kernel.dylib         0x7fff5d32a2c6 __pthread_kill + 10
1  libsystem_pthread.dylib        0x7fff5d3dfbf1 pthread_kill + 284
2  libsystem_c.dylib              0x7fff5d2946a6 abort + 127
3  libsystem_malloc.dylib         0x7fff5d3a2aef malloc_vreport + 545
4  libsystem_malloc.dylib         0x7fff5d3a28b0 malloc_report + 151
5  Git                            0x10cce7e0e git_odb_object__free + 30
6  Git                            0x10ccae68e git_commit_list_parse + 814
7  Git                            0x10cd1a614 add_parents_to_list + 100
8  Git                            0x10cd1a10d git_revwalk_next + 333
9  Git                            0x10cd2e6d4 git_smart__negotiate_fetch + 500
10 Git                            0x10ccc51b1 git_fetch_negotiate + 609
11 Git                            0x10cd0fb9a git_remote_download + 1194
12 Git                            0x10cd0fd1a git_remote_fetch + 202
13 Git                            0x10cb8bc4b globalinit_33_46240B7271BAB13E345CE2E50BE21379_func5 + 51947
14 Gitfox                         0x10c95bc53 AsyncOpFetch.execute(txn:) (AsyncOpFetch.swift:69)
```

Upon looking more closely at `git_commit_list_parse`, I think it could be that

    git_odb_object *obj;

is not properly set to `NULL` on initialization.

**Comment by eaigner** [comment]
Is it possible to let the build system fail on uninitialized vars?

**Comment by ethomson** [comment]
> Is it possible to let the build system fail on compile if there are uninitialized vars?

It is.  valgrind will catch those.

This and the other issue you just opened suggest some concurrency issues.  Tell me about how you manage libgit2 resources and threads?

**Comment by eaigner** [comment]
Well, the `revwalk` API says it is not threadsafe, unless executed on different threads. I basically have 2 queues for remote and local operations, each with their own thread that are set to serial execution.

**Comment by ethomson** [comment]
I'm surprised that revwalk makes that guarantee.  I think we should review that for accuracy.

Having said that, there's no revwalk in your stack trace.  `git_remote_fetch` should definitely not be invoked while anything else is working on a repository.

**Comment by eaigner** [comment]
There is: `0x10cd1a10d git_revwalk_next + 333`

**Comment by tiennou** [comment]
From `git_revwalk_new` (emphasis mine):
> This revision walker is not thread safe: it may only be used to walk a repository on a single thread; *however, it is possible to have several revision walkers in several different threads walking the same repository.*

Yeah, this is not quite correct, as many basic structures don't really handle concurrency (`git_pool` comes to mind, as well as the threaded-diff branch and its atomics helpers), or at least it should be tested by CI. If you want to do that, you might be safer handing an entire `git_repository` to each of your threads (as per THREADING.md).

**Comment by eaigner** [comment]
In any case, I really hope this guarantee is right. Lets imagine a GUI client, that has currently a potentially long running fetch in progress. Since the `revwalk` that fetch internally uses is not accessible, it would mean that the whole UI would have to wait for that single fetch to complete.

**Comment by eaigner** [comment]
@tiennou so basically, the safe way is to open another copy of the repo object for each asynchronous task?

**Comment by tiennou** [comment]
Yeah, or at least make sure that there's no way another thread accesses it while it's in progress (eg. the low-level [GitX wrapper responsible for enumerating](https://github.com/gitx/gitx/blob/master/Classes/git/PBGitRevList.m) sidesteps the issue by putting up a modal dialog so the main thread is busy).

In any case, AFAIK there's no such guarantee (even though it makes UI code harder). A possible way out might be to devise a parallel revwalk test case, run it under TSan/fuzzers for a few weeks, fixing issues until it stops complaining 😬.

Maybe we should start some kind of project-wide consolidation/discussion effort ? There are at least 3 different subsystem people have expressed interest in, namely #4205 (checkout), #5043 (diff), now this (revwalk).

**Comment by eaigner** [comment]
Well, I run 100 fetches in parallel just to test if it actually was a concurrency issue, and nothing crashed. Yet there is still a path in the code where `git_odb_object *obj` will not get initialized. I think this has nothing to do with concurrency but that `obj` isn't set properly to `NULL`.

**Comment by eaigner** [comment]
I also tried to perform the operation on a separate `git_repository` instance for that one operation, still crashes at the same point.

**Comment by eaigner** [comment]
I dug a little deeper, seems the underlying issue is cache related.

![Screen Shot 2019-05-23 at 18 21 54](https://user-images.githubusercontent.com/112197/58269388-bb6c3a80-7d87-11e9-98d2-7160dee59516.png)

I had the `GIT_OPT_SET_CACHE_MAX_SIZE` set to 25MB.
Leaving it on default (250MB) seems to alleviate the issue in some cases.

**Comment by eaigner** [comment]
I have found a way to reproduce the problem with an existing test case.
Test cases actually never exercise the lower part of `cache_evict_entries`,
they always return at the first `if` statement.

Ok, here is how you can reproduce this issue with `clar`.

- Turn on `guard malloc` if you can
- Set the cache size globally to 1MB `ssize_t git_cache__max_storage = (1 * 1024 * 1024);`
- Run the `test_blame_simple__trivial_libgit2` test case.

It will crash at the exact same point as above (`git_oidmap_delete`).

**Comment by pks-t** [comment]
On Fri, May 24, 2019 at 02:03:13AM -0700, Erik Aigner wrote:
> I have found a way to reproduce the problem with an existing test case.
> Test cases actually never exercise the lower part of `cache_evict_entries`,
> they always return at the first `if` statement.
> 
> Ok, here is how you can reproduce this issue with `clar`.
> 
> - Turn on `guard malloc` if you can
> - Set the cache size globally to 1MB `ssize_t git_cache__max_storage = (1 * 1024 * 1024);`
> - Run the `test_blame_simple__trivial_libgit2` test case.
> 
> It will crash at the exact same point as above (`git_oidmap_delete`).

I can reproduce on glibc based systems with this, thanks!

**Comment by pks-t** [comment]
I've found the issue, which was essentially a memory ready after free. Please see #5088 and check whether it fixes your segfault.

**Comment by eaigner** [comment]
Tried your branch with different cache sizes, seems to be fixed!

**Comment by pks-t** [comment]
Perfect, thanks for verifying!
