### ISSUE TITLE
Consecutive asterisks are not collapsed to regular asterisks when they can't be interpreted as directories

### ISSUE THREAD

**Issue by nathansobo** [libgit2/libgit2#5093]
In Atom, we're using libgit2 to determine whether files are ignored. We recently upgraded, and got a user complaint about a file that was previously shown as ignored being shown as not ignored even though Git continued to ignore it (https://github.com/atom/tree-view/issues/1317).

It turns out that the user was incorrectly using the `**` pattern in their file, with a `**.log` pattern to ignore all log files. They could have just used `*.log` instead, but apparently Git automatically collapses `**` to `*` in situations where `**` does not make sense.

In the documentation provided by `man gitignore`, the following is stated about double asterisks in gitignore patterns:

> Two consecutive asterisks (`**`) in patterns matched against full pathname may have special meaning:
>
> * A leading `**` followed by a slash means match in all directories. For example, `**/foo` matches file or directory `foo` anywhere, the same as pattern `foo`. `**/foo/bar` matches file or directory `bar` anywhere that is directly under directory `foo`.
> * A trailing `/**` matches everything inside. For example, `abc/**` matches all files inside directory `abc`, relative to the location of the .gitignore file, with infinite depth.
> * A slash followed by two consecutive asterisks then a slash matches zero or more directories. For example, `a/**/b` matches `a/b`, `a/x/b`, `a/x/y/b` and so on.
> * **Other consecutive asterisks are considered regular asterisks and will match according to the previous rules.**

Note the final bullet, which I have bolded.

I'm not sure how much we care about libgit2 matching the exact behavior of Git, and this admittedly a pretty strange edge case. We can tell the user to fix thier ignore file, but I thought it was worth reporting anyhow.

### Reproduction steps

This test can be added to `tests/attr/ignore.c`

```c
void test_attr_ignore__collapse_spurious_stars(void)
{
	cl_git_rewritefile(
		"attr/.gitignore",
		"**.log\n"
	);

	assert_is_ignored(true, "a.log");
	assert_is_ignored(true, "dir1/a.log");
}
```

### Expected behavior

The assertions should pass, indicating that `a.log` and `dir1/a.log` are ignored.

### Actual behavior

The assertions fail.

### Version of libgit2 (release number or SHA1)

ac070afecc33e9f263353455debd07876b0e91bf

### Operating system(s) tested

macOS 10.14.4 (18E226)

**Comment by pks-t** [comment]
Thanks for your detailed bug report! Our behaviour is indeed wrong and inconsistent with git.git. I'll investigate.

**Comment by pks-t** [comment]
Turns out git.git has removed all their fnmatch code in 70a8fc999d (stop using fnmatch (either native or compat), 2014-02-15) and replaced it with wildmatch. I've started porting over wildmatch into our codebase to start transitioning to it, too.

**Comment by ethomson** [comment]
Oy, we'll have to check the licensing on that one.  It looks like git took it from rsync (the last version of rsync that was GPLv2), but the origin of wildmatch was @richsalz's `wildmat.c`.

I haven't actually run down the actual original implementation of `wildmat.c` that is credited in the rsync code, from 1986.  Given the date, I assume it landed on a usenet newsgroup, so I may be able to track that down.  What I _am_ seeing some later versions and derivative works.  For example, a usage of [revision 1.3](https://github.com/jpmens/diablo/blob/master/lib/wildmat.c), which has this copyright and licensing information:

```
**    Copyright 1991 Rich Salz.
**    All rights reserved.
**    $Revision: 1.3 $
**
**    Redistribution and use in any form are permitted provided that the
**    following restrictions are are met:
**	1.  Source distributions must retain this entire copyright notice
**	    and comment.
**	2.  Binary distributions must include the acknowledgement ``This
**	    product includes software developed by Rich Salz'' in the
**	    documentation or other materials provided with the
**	    distribution.  This must not be represented as an endorsement
**	    or promotion without specific prior written permission.
**	3.  The origin of this software must not be misrepresented, either
**	    by explicit claim or by omission.  Credits must appear in the
**	    source and documentation.
**	4.  Altered versions must be plainly marked as such in the source
**	    and documentation and must not be misrepresented as being the
**	    original software.
**    THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR IMPLIED
**    WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF
**    MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
```

So the wildmatch code from Samba (and thus Git) is a derivative work _of this_.  I will do a bit more investigation before I :+1: pulling this in, but I wanted to at least get to this point to know whether I should tell you to 🛑 what you're doing with engineering work in case we wouldn't be able to include it for licensing reasons.

**Comment by pks-t** [comment]
@ethomson: meeh. I simply assumed it'd be fine to use in libgit2 because git actually used it under its own license terms. But I forgot that we actually have a linking exception, which'd need to be compatible, too. So I highly appreciate you doing that nasty legal work :)

I've already got a version of libgit2 that works with wildmatch, mostly, except for the nasty places where we use glibc-specific extensions like `FNM_LEADING_DIR`. I'll just continue with good faith and hope that we'll actually be able to use that code.

**Comment by richsalz** [comment]
I am the author.  At the time I wrote it the BSD license was the only open source license around. At this point, 28 years later, it should be in the public domain.  Feel free.  Email me rich.salz at gmail.com if you need a statement.

**Comment by ethomson** [comment]
Thanks @richsalz - both for your work and for taking a moment to drop by.  😀

**Comment by pks-t** [comment]
@richsalz: perfect, thanks a lot for dropping by any clarifying!

@nathansobo: could you please give #5110 a go and check whether it fixes the issue you're seeing?

**Comment by nathansobo** [comment]
Awesome! I can confirm this fixes the issue. I have https://github.com/atom/git-utils/pull/97 open on our Node add-on that points to @pks-t's fork with a passing unit test. I will probably wait for the #5110 to be merged to master before updating, however.

**Comment by pks-t** [comment]
Thanks a lot for checking!

**Comment by pks-t** [comment]
Fixed via #5110

**Comment by nathansobo** [comment]
@pks-t Now that the fix is merged to master, I'm inclined to merge https://github.com/atom/git-utils/pull/97, which updates the submodule of our Node add-on include it. Do you have any thoughts on the stability of code that's on libgit2 master but not yet published as an official release? Obviously anything can happen, but would you feel confident rolling it out to users?

**Comment by ethomson** [comment]
@nathansobo I think that it's of high quality - the largest refactoring would be in the networking code.  But looking at https://github.com/atom/git-utils, you're not using that.  So I think it's exceedingly stable, IMO.

**Comment by pks-t** [comment]
The second place that's enjoyed some major refactoring is the fnmatch/wildmatch conversion, which does also fix your problems. I wouldn't be too surprised if there would be some minor issues popping up, as it did touch quite a lot of different places.

Other than that, I'd agree with @ethomson. It's not like we do some magic stuff to get our tree in shape as soon as we're prepping for a release, instead we try to always keep master in a deployable state.

**Comment by nathansobo** [comment]
Awesome. Thanks to you both!

**Comment by richsalz** [comment]
In case anyone (else) cares, the public domain code is now posted at https://github.com/richsalz/wildmat

**Comment by ethomson** [comment]
@richsalz 🎉🎉🎉
