### ISSUE TITLE
test_online_clone__cred_callback_called_again_on_auth_failure fails with HTTP status code 404

### ISSUE THREAD

**Issue by dvzrv** [libgit2/libgit2#5096]
Hi! I'm currently trying to build `0.28.2` for packaging purposes on Arch Linux and I'm running into a failing online test.
AFAICS, the test function [test_online_clone__cred_callback_called_again_on_auth_failure](https://github.com/libgit2/libgit2/blob/master/tests/online/clone.c#L343) is failing on an unexpected 404 HTTP status code.

How can this be prevented? Generally it can potentially be desirable to not run online tests at all.

### Reproduction steps

```
  mkdir -p build
  cd build
  cmake -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_BUILD_TYPE=Release \
        -DTHREADSAFE=ON \
        ..
  make VERBOSE=1
  make test VERBOSE=1
```

### Expected behavior

All tests pass.

### Actual behavior

```
Running tests...
/usr/bin/ctest --force-new-ctest-process 
Test project /build/libgit2/src/libgit2-0.28.2/build
    Start 1: offline
1/6 Test #1: offline ..........................   Passed   22.64 sec
    Start 2: invasive
2/6 Test #2: invasive .........................   Passed    0.14 sec
    Start 3: online
3/6 Test #3: online ...........................***Failed   38.64 sec
    Start 4: gitdaemon
4/6 Test #4: gitdaemon ........................   Passed    0.34 sec
    Start 5: ssh
5/6 Test #5: ssh ..............................   Passed    0.34 sec
    Start 6: proxy
6/6 Test #6: proxy ............................   Passed    0.01 sec

83% tests passed, 1 tests failed out of 6

Total Test time (real) =  62.12 sec

The following tests FAILED:
          3 - online (Failed)
Errors while running CTest
```

Or more specifically: 
[LastTest.log](https://github.com/libgit2/libgit2/files/3262378/LastTest.log)

And in build context: 
[libgit2-0.28.2-build.log](https://github.com/libgit2/libgit2/files/3262436/libgit2-0.28.2-build.log)

### Version of libgit2 (release number or SHA1)

0.28.2

### Operating system(s) tested

Arch Linux

**Comment by ethomson** [comment]
This was due to a behavior change on GitHub.  You can cherry-pick https://github.com/libgit2/libgit2/pull/5094, disable the test, or ignore the output as you see fit.

> How can this be prevented? Generally it can potentially be desirable to not run online tests at all.

We're going to continue running our online tests in CI as there's no way to mock Git providers.  If you want to avoid the online tests, you can run `libgit2_clar -xonline`.

**Comment by ethomson** [comment]
Also, I noticed that you're running `make test`.  I think that you should be able to `make test offline` to skip the online tests, but I haven't tested this.

**Comment by pks-t** [comment]
Closing this issue as a fix is available by now. If you feel like your issue hasn't been properly addressed, please feel free to reopen this ticket.

**Comment by dvzrv** [comment]
Thanks for the quick reply and the link to the issue! Applying it as a patch indeed solved my problem with the failing test. Many thanks!
