### ISSUE TITLE
Handling of port component in URLs (with schema) differs from git

### ISSUE THREAD

**Issue by neithernut** [libgit2/libgit2#5100]
### Reproduction steps

build libgit2 with examples (`lg2`), then

    mkdir test
    cd test
    git init
    git remote add origin https://github.com:/libgit2/libgit2.git
    lg2 fetch origin

### Expected behavior

The repository is fetched 

### Actual behavior

    Bad news:
     malformed URL 'https://github.com:/libgit2/libgit2.git'

### Version of libgit2 (release number or SHA1)

e50d138e898dd034161663873f75716086266f86

### Operating system(s) tested

Gentoo linux

**Comment by neithernut** [comment]
In the above reproducer, fetching works if `git` is used instead of `lg2`. With `lg2`, URLs without ports (e.g. `https://github.com/libgit2/libgit2.git`) are fine, and so are schema-less URLs for ssh remotes (e.g. `git@github.com:libgit2/libgit2.git`).

----

For URLs with an (empty) port component, [http_parse_host](https://github.com/libgit2/libgit2/blob/e50d138e898dd034161663873f75716086266f86/deps/http-parser/http_parser.c#L1989) fails due to some [sanity check](https://github.com/libgit2/libgit2/blob/e50d138e898dd034161663873f75716086266f86/deps/http-parser/http_parser.c#L2046). _Maybe_ the issue can be solved by just removing the `s_http_host_port_start` case, but I didn't (yet) check whether this breaks anything else.

**Comment by ethomson** [comment]
That's horrible, but RFC 3986 says:

> URI producers and normalizers **should** omit the port component and its ":" delimiter if port is empty or if its value would be the same as that of the scheme's default.

(Emphasis mine.)  Which indicates that they **may** and therefore we **must** accept it.

Not that it matters anyway, we stay bug-for-bug compatible with git.  So yeah, we should certainly fix this.

Having said that, I've done a lot of refactoring of the networking code in #5052.  So I'd like to ensure that this still exists there (I'm sure that it does) and fix it there to avoid conflicts.

**Comment by ethomson** [comment]
The issue here, though, is that we use `http_parser_parse_url` to do our parsing for us.  The fix itself is simple, removing the error case when you're at the port start, at the end of parsing, 

```diff
diff --git a/deps/http-parser/http_parser.c b/deps/http-parser/http_parser.c
index 27bdd2081..cc53a5215 100644
--- a/deps/http-parser/http_parser.c
+++ b/deps/http-parser/http_parser.c
@@ -2047,7 +2047,6 @@ http_parse_host(const char * buf, struct http_parser_url *u, int found_at) {
     case s_http_host_start:
     case s_http_host_v6_start:
     case s_http_host_v6:
-    case s_http_host_port_start:
     case s_http_userinfo:
     case s_http_userinfo_start:
       return 1;
```

But since http-parser is a system dependency _or_ a bundled dependency, we can only fix this in our bundled version.  The problem here is that we have a few options:

1. Update our bundled dependency to fix this, but admit defeat against system dependency.  I hate being inconsistent between the two.
2. Always use our bundled http-parser.  We'll be consistent and compatible with git.
3. Do nothing and be consistent but incompatible with git.

I lean toward (2) and but I think that @pks-t will hate this idea.

**Comment by pks-t** [comment]
On Tue, Jun 11, 2019 at 01:52:50PM -0700, Edward Thomson wrote:
> But since http-parser is a system dependency _or_ a bundled dependency, we can only fix this in our bundled version.  The problem here is that we have a few options:
> 
> 1. Update our bundled dependency to fix this, but admit defeat against system dependency.  I hate being inconsistent between the two.
> 2. Always use our bundled http-parser.  We'll be consistent and compatible with git.
> 3. Do nothing and be consistent but incompatible with git.
> 
> I lean toward (2) and but I think that @pks-t will hate this idea.

4. Create a fix for our bundled http-parser and upstream it.

As that incurs additional overhead, I'd naturally do the
upstreaming part for you (but probably take over ownership of the
proposed patch to make this easier, if that's fine with you).

Meanwhile, we could do the following:

- Default to bundled http-parser iff it's version is smaller than
  the one with the required fix.

- Provide a new build option "-DUSE_HTTP_PARSER=(SYSTEM|BUNDLED)"
  to override behaviour. If you ask me, we should have that
  regardless.

**Comment by ethomson** [comment]
> 4. Create a fix for our bundled http-parser and upstream it.

Indeed, I was thinking more immediately about the problem, as it exists without the benefit of an http-parser that has this fix.  I'm okay with providing a bundled/system option for http-parser and defaulting to ours now.  When there exists an http-parser with this fix, we can add the version check in.  I'll update my PR to add the cmake option.

**Comment by pks-t** [comment]
> Indeed, I was thinking more immediately about the problem, as it exists without the benefit of an http-parser that has this fix. I'm okay with providing a bundled/system option for http-parser and defaulting to ours now. When there exists an http-parser with this fix, we can add the version check in. I'll update my PR to add the cmake option.

Fair enough. Do you want to handle upstreaming or shall I lift you of that burden?
