### ISSUE TITLE
libgit2.so: undefined reference to `__sync_val_compare_and_swap_4'

### ISSUE THREAD

**Issue by sam6666666** [libgit2/libgit2#5103]
target:
centos5.5 32bits

gcc -v
Using built-in specs.
Target: i386-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-libgcj-multifile --enable-languages=c,c++,objc,obj-c++,java,fortran,ada --enable-java-awt=gtk --disable-dssi --enable-plugin --with-java-home=/usr/lib/jvm/java-1.4.2-gcj-1.4.2.0/jre --with-cpu=generic --host=i386-redhat-linux
Thread model: posix
gcc version 4.1.2 20080704 (Red Hat 4.1.2-48)

I compiled libgit.so, on this platform to report errors when using this dynamic library.

/usr/local/libgit2/lib/libgit2.so: undefined reference to `__sync_val_compare_and_swap_4'
/usr/local/libgit2/lib/libgit2.so: undefined reference to `__sync_sub_and_fetch_4'
/usr/local/libgit2/lib/libgit2.so: undefined reference to `__sync_add_and_fetch_4'

I found through google that I couldnundefinedt solve this problem.
such as -lgcc_s...

**Comment by sam6666666** [comment]
emmm....

I solved this problem and needed to add parameters at compile time。
-m32 -march=i486

**Comment by ethomson** [comment]
I'm reopening this because if we're failing to get you building correctly using the standard steps, then we're wrong.

How did you set this up?  Just a standard `cmake` then `cmake --build` (or `make`)?

If so then our compare and swap macros for gcc need some tuning.

**Comment by tiennou** [comment]
Looks like a gcc/32-bit intrinsic selection issue (ie. not adding whatever `compiler-rt.dylib` is in gcc-land), or missing those flags in the pkg-config ?

**Comment by sam6666666** [comment]
This problem was encountered by me using libgit2 on a 32-bit system, which needs to add
-m32 -march=i486.
This does not need to be modified in libgit2 undefineds cmake.
 But I hope to have a note that using libgit2.so on 32-bit systems saves a lot of time.

**Comment by sam6666666** [comment]
I think the issue can be closed.
thanks。
