### ISSUE TITLE
Library claims to be C89-compliant, but is not

### ISSUE THREAD

**Issue by mehrdadn** [libgit2/libgit2#5120]
On this project's [website](https://libgit2.org/), it claims compliance with C89.  
However, [the library uses variadic macros](/libgit2/libgit2/blob/fef847ae57d74e93563bc04222d9da7007fffc4f/src/parse.h#L29) which are [not C89-compliant](https://en.wikipedia.org/wiki/Variadic_macro).  
Either the compliance claim or the variadic macros should be removed.

**Comment by pks-t** [comment]
Indeed, thanks for your report. This is being fixed by #5121

**Comment by mehrdadn** [comment]
Sure thing. Note that I believe there are other macros too; I only reported one of them.

**Comment by pks-t** [comment]
Converted the others, too. There's one more instance in "tests/clar.c", but that should better be fixed upstream in http://github.com/clar-test/clar

**Comment by mehrdadn** [comment]
Cool! Also, just realized one more thing... the library also uses `__restrict`/`__restrict__` and I'm not sure if that's a problem in this respect or not. On the one hand they're both compiler-specific; on the other hand it's not using the C99 `restrict`.

**Comment by ethomson** [comment]
Closing this — I think that the `__restrict__` is limited to MSVC, and makes sense in this regard.
