### ISSUE TITLE
git_diff_find_similar: resulting diff always only shows additions

### ISSUE THREAD

**Issue by eaigner** [libgit2/libgit2#5139]
I have a problem with calling `git_diff_find_similar` on an existing diff. Every time I try to resolve renames with it, the resulting diff doesn't show the actual changes, but all lines as ADDED.

I have tried tweaking different split params of `git_diff_find_options` but nothing seems to change the outcome.

I don't know what exactly I am missing, but I just can't get this to work.

1. Check in a file
2. Add one line at the end and rename the file
3. Run `git_diff_find_similar` with default options

Expected:

Renamed file in diff is shown with changes

Actual:

Renamed file in diff is shown with all lines as ADDED

**Comment by ethomson** [comment]
All lines or all deltas?  I'd expect that you see `GIT_DELTA_RENAMED` deltas.

However, if everything is `ADDED` then it sounds like you didn't have any rename candidates to begin with?

**Comment by ethomson** [comment]
(Can you show me some sample code?)

**Comment by eaigner** [comment]
Hold on, working on a sample. But the culprit is probably my own incompetence here ;)

**Comment by eaigner** [comment]
I found that

    #define GIT_DIFF_FIND_OPTIONS_INIT {GIT_DIFF_FIND_OPTIONS_VERSION}

is not actually initializing any defaults (except the version).
Is that wanted/expected?

**Comment by ethomson** [comment]
I'd have to give it some more thought, but I wouldn't think that you'd want to call `git_diff_find_similar` if you wanted to have a similarity metric of `0`...

**Comment by ethomson** [comment]
(But I also don't think that this explains why you're not seeing renames?)

**Comment by eaigner** [comment]
No it doesn't. Still scratching my head what's the problem in my specific case... I'll get back to you when I have distilled an example.

**Comment by eaigner** [comment]
Ha.... I had the `pathspec` constrained to a single file to view the diff for a status list entry. Obviously if that pathspec doesn't include the old file name, the diff doesn't display the actual modified lines but all  lines as ADDED. **facepalm**

**Comment by ethomson** [comment]
Yeah, that's what I would expect.  If you have a `NULL` pathspec (or one that includes delete/add pairs that can be coerced into a rename), is it working for you?

**Comment by eaigner** [comment]
I added the old and new filename of the corresponding status entry, and the diff now looks correct.

**Comment by eaigner** [comment]
Would it make sense to automatically force this behavior when searching for renames/copies? (automatically modifying the pathspec as necessary)

**Comment by ethomson** [comment]
> Would it make sense to automatically force this behavior when searching for renames/copies? (automatically modifying the pathspec as necessary)... probably not I guess.

I don't think so - I don't know how we could modify the pathspec.  It could be useful to limit the pathspec, and as long as you had some pairs of deletes and adds then they could make rename pairs.  So you wouldn't want to automatically include all files in the repo, I don't think,.

**Comment by ethomson** [comment]
But maybe I'm wrong - if you have suggestions for how to make this easier for end-users, I'm all ears.

**Comment by pks-t** [comment]
> Would it make sense to automatically force this behavior when searching for renames/copies? (automatically modifying the pathspec as necessary)... probably not I guess.

I don't think so, either. After all, git.git behaves the same, doesn't it? If you restrict paths in git-diff(1), then you'll also see either old or new file, only.
