### ISSUE TITLE
DllMain included in static library on Windows

### ISSUE THREAD

**Issue by kevinlul** [libgit2/libgit2#5154]
### Reproduction steps
Linking against both `libgit2` and `irrlicht` statically in a project. 

### Expected behavior
The project compiles and links successfully.

### Actual behavior
Linking fails with a duplicate definition of `DllMain`.

### Proposed fix
In https://github.com/libgit2/libgit2/blob/master/src/global.c, wrap `BOOL WINAPI DllMain` in a preprocessor flag checking if we are building as a static library. The same bug also exists in other libraries that compile this into their binaries even if not building a DLL.

### Version of libgit2 (release number or SHA1)
0.28.2

### Operating system(s) tested
Windows 10

**Comment by ethomson** [comment]
Hmm, interesting.  Indeed we should not be defining a `DllMain` unless we're actually building a dll.

However, we'll need to clean up our TLS data a bit differently: https://stackoverflow.com/a/3245082/729881

**Comment by thiloschulz** [comment]
Hi, I had the same error. If this still bothers you, see https://github.com/libgit2/libgit2/pull/5194. It requires the application writer to call git_libgit2_dllmain() from their own DllMain() though.

**Comment by kevinlul** [comment]
Since the issue only occurs when two libraries contain `DllMain` even when static linking, I resolved my specific issue by building `irrlicht` from source and patching it so that `DllMain` was not compiled when linking statically. A similar solution could be used here.

**Comment by thiloschulz** [comment]
If an application has a DllMain() that handles the thread destruction case then it is usually for a good reason. Having a static library does not make issues like thread local storage go away. So just #undeffing it may result in memory leaks and other bad behaviour.

**Comment by thiloschulz** [comment]
Hmmm.. continuing that thought: DllMain() is never called for an .EXE - so libgit2 will leak memory in either case if you link it statically into your problem.
This means the method from https://stackoverflow.com/a/3245082/729881 is the only way to do it properly in this case.

**Comment by thiloschulz** [comment]
As became evident from the discussion in https://github.com/libgit2/libgit2/issues/5207, the solution from https://stackoverflow.com/a/3245082/729881 is still not complete.

A thread may persist even if git_libgit2_shutdown() has called TlsFree() on the TLS slot. In this case, the "destructor thread" will call TlsGetValue() on a freed slot (memory leak), or even worse: on a slot  allocated for another purpose in the meantime and try to free that one (heap corruption).

So you would need to create an event source with CreateEvent and have the destructor thread WaitForMultipleObjects(). If the thread terminates, it will free the tls data. If git_libgit2_shutdown() calls SetEvent(), it will free the tls data.

**Comment by ethomson** [comment]
This should be fixed via #5314.
