### ISSUE TITLE
diff: git_diff_from_buffer fails to parse diff with comment lines

### ISSUE THREAD

**Issue by eaigner** [libgit2/libgit2#5157]
Consider this diff produced by `git` after adding a newline at the end

```
diff --git a/test/diff2.txt b/test/diff2.txt
index 212a1d6d8..b27c6ecb3 100644
--- a/test/diff2.txt
+++ b/test/diff2.txt
@@ -1,4 +1,4 @@
 This is just
 a text file to
 test git diff file
-changes
\ No newline at end of file
+changes
```

feeding this to `git_diff_from_buffer` will result in an error

     invalid patch hunk at line 10

Looking at `patch_parse.c:parse_hunk_body` it seems that comment lines like

    \ No newline at end of file

are completely ignored and the default error is thrown

**Comment by pks-t** [comment]
I think this is a duplicate of #5153, right? This was in fact the next thing I had on my todo list for today.

**Comment by eaigner** [comment]
Oh, didn't see that. Yes.

Probably also a good idea to test the reverse (remove newline).

**Comment by pks-t** [comment]
See #5159
