### ISSUE TITLE
status: git_status_list_new errors on does_negate_rule

### ISSUE THREAD

**Issue by eaigner** [libgit2/libgit2#5166]
Steps:

- clone `git@github.com:nodejs/node.git`
- run `lg2 status` in the repository

Expected:

- No error

Actual:

- libgit errors out with `Could not get status [-1] - error matching pattern`

`git status` works just fine.

Apparently `libgit2` is not comfortable with the `node`s repo `.gitignore` file.

The error stems from `ignore.c:does_negate_rule:145`

The offending rule seems to be `!**/node_modules/**`

**Comment by eaigner** [comment]
The offending rule seems to be `!**/node_modules/**`

**Comment by pks-t** [comment]
This is a result of our migration to the new wildmatch code of git.git. Honestly I've been sort of expecting this exact error. I'll create a PR to fix this

**Comment by pks-t** [comment]
Please have a look at #5173

**Comment by eaigner** [comment]
@pks-t will do ASAP.

**Comment by eaigner** [comment]
@pks-t i know its already merged, but I just verified it with the Node repo and it seems to be resolved 👍

**Comment by pks-t** [comment]
Perfect, thanks for verifying!
