### ISSUE TITLE
ssh: process exits when public key is malformed

### ISSUE THREAD

**Issue by eaigner** [libgit2/libgit2#5169]
When the public key is "malformed" or does not have a very specific format, `libgit` crashes with `SIGPIPE`

    Message from debugger: Terminated due to signal 13

To reproduce, just remove some base64 chars from the middle of a public key file.

**Comment by eaigner** [comment]
Maybe it should be masked on connect with `pthread_sigmask`

I used this as an intermediate solution for me:

    signal(SIGPIPE, SIG_IGN)
    git_libgit2_init()

**Comment by pks-t** [comment]
This is most likely a problem with libssh2, as for example noted in #5162, right? If so, I'd vote for closing this issue as we cannot really do anything about it until it's fixed upstream. Please let me know if you disagree, though.

**Comment by eaigner** [comment]
Well, maybe my issue title is a bit wrong. Actually a signal would not be an actual crash (although it results in the application quitting).

**Comment by tiennou** [comment]
I'm tempted to say that signals, thread masks and those kind of things are "up to the application's developer", because we (as libgit2) can't really set anything up without making assumptions, hence it's likely this is the "correct" fix. Maybe a point could be made that libssh2 should take care of that itself, but I don't think this is libgit2's responsibility (and it's also been a while since I've encountered SIGPIPE).

**Comment by eaigner** [comment]
The problem is, you can't really test for those things in a desktop app, because it doesn't generate a proper crash report. Not handling `SIGPIPE` makes only sense if libgit were only used as a command-line tool IMHO. As soon as you have a desktop app, this assumption no longer holds.

In my case I was oblivious that a problem even existed, because to the system it looks like "everything as expected, nothing to see here".

**Comment by jacquesg** [comment]
Changing signal dispositions should definitely not be done by a library.

Using ```MSG_NOSIGNAL``` or ```setsockopt(SO_SIGNOPIPE)``` (if available) by a library is recommended.

**Comment by eaigner** [comment]
I thought the consensus was that the client should handle this?

**Comment by tiennou** [comment]
Sorry, forgot to state The Obvious™ : either libssh2 does it for us, or we're not doing something correctly ourselves. I'm pretty sure I got a hit while grepping their source, and sadly left it at that. I'm still waiting for movement on my rewrite of libssh2's testsuite to land before looking at any more code from "them", and wanted to revisit @jacquesg recommendation. I'll assign to me 😉.
