### ISSUE TITLE
git_patch_parse: valid patch fails to parse

### ISSUE THREAD

**Issue by ddevault** [libgit2/libgit2#5177]
### Reproduction steps

1. [Obtain this patch](https://paste.sr.ht/~mkaito/36c7b292598b5a4df415020d01ca2670af639ab4)
2. Feed into git_patch_parse

### Expected behavior

Parses correctly

### Actual behavior

`invalid patch hunk at line 260`

### Version of libgit2 (release number or SHA1)

0.28.2

### Operating system(s) tested

Linux

**Comment by ethomson** [comment]
Dup of #5153
