### ISSUE TITLE
git_repository_init creates useless ".lnk" files

### ISSUE THREAD

**Issue by sxyzy1016** [libgit2/libgit2#5188]
### Reproduction steps
My code:
```
int main() {
    git_libgit2_init();
    const char* path = "rj45";
    git_repository* rep = nullptr;
    int error = git_repository_init(&rep, path, 0);
    if (error < 0) {
        const git_error *e = giterr_last();
        std::cout << "Error: " << error << " / " << e->klass << " : " << e->message << std::endl;
        goto SHUTDOWN;
    }
SHUTDOWN:
    git_repository_free(rep);
    git_libgit2_shutdown();
    return 0;
}
```

### Expected behavior
create a `.git` in `rj45`, make `rj45` a git repo

### Actual behavior
output of `dir /a rj45`:
```
2019/07/25  17:47    <DIR>          .
2019/07/25  17:47    <DIR>          ..
2019/07/25  17:46    <DIR>          .git
2019/07/25  17:47    <SYMLINKD>     _git2_a26532 [testing]
2019/07/25  17:46    <SYMLINKD>     _git2_a28884 [testing]
```
it creates some .lnk files pointing to a non-exist 'testing' directory

### Version of libgit2 (release number or SHA1)
0.28.2, mingw-w64 (msys2)

### Operating system(s) tested
Windows 10 10.0.18362.239

Any help?

**Comment by ethomson** [comment]
Should be fixed in master, via #5151.  It will be in the next release, but in the meantime, can you try a build out of master to confirm?

**Comment by sxyzy1016** [comment]
Thanks. `master` works fine!

**Comment by ethomson** [comment]
Woo, great.  😀
