### ISSUE TITLE
PCRE dependency information is not stored in libgit2.pc

### ISSUE THREAD

**Issue by carlosmn** [libgit2/libgit2#5203]
### Reproduction steps

Configure and compile libgit2 such that it decides to link dynamically against libpcre.

### Expected behavior

This fact should be stored in `libgit2.pc` in case we want to statically include the library.

### Actual behavior

It is not there

### Version of libgit2 (release number or SHA1)

Current master (08cfa43d0e1a9214) presumably since the PCRE functionality was introduced.

### Operating system(s) tested

Debian bullseye, Ubuntu Xenial.

**Comment by carlosmn** [comment]
More specifically, we have a line

    Requires.private: openssl zlib

which should add `libpcre` (or whatever `pkg-config` sees on other systems).

**Comment by AmarOk1412** [comment]
Still seems to get some problem when including libgit2 and need to add PCRE_LIBS to my cmake
