### ISSUE TITLE
Undefined reference to `git_error_last' using libgit2 version 0.28.3

### ISSUE THREAD

**Issue by jvelilla** [libgit2/libgit2#5215]
I'm creating an Eiffel binding to libgit2 and I've got some undefined references for functions defined in git2/errors.h on Linux (Ubuntu using version 0.28.3) works fine on Windows.

# Reproduction steps
Just compile a simple code that uses git_error_last, 
I got also the same undefined reference for others 
functions defined in: git2/errors.h

* git_error_clear
* git_error_set_oom
* git_error_last
* git_error_set_str

### Version of libgit2 
Version: 0.28.3

Builded with vckp package manager
./vcpkg install libgit2:x64-linux

Same issue if I build it using this [guideline](https://libgit2.org/docs/guides/build-and-link/)

### Operating system(s) tested
Ubuntu 19.04

**Comment by ethomson** [comment]
Curious.  What's the output of `ldd` on your built binary?

**Comment by jvelilla** [comment]
it seems the issue is with vcpkg tool,  I've recompiled the lib and works fine.

**Comment by ethomson** [comment]
Thanks for the information.  I'm afraid that I'm not familiar with vcpkg - I'm going to close this for now, but if you have any further details, please let us know.
