### ISSUE TITLE
Bad interaction with empty `http.proxy` in `.gitconfig` and `GIT_PROXY_AUTO`

### ISSUE THREAD

**Issue by fredrikekre** [libgit2/libgit2#5220]
There is some bad interaction with empty `http.proxy` in `.gitconfig` and `GIT_PROXY_AUTO`. I noticed this when we upgraded to libgit2 0.28 for Julia (https://github.com/JuliaLang/julia/issues/33111). For reasons I don't know I had an empty `http.proxy`  in `.gitconfig` and `libgit2` then fails to `clone`/`fetch`. I am guessing here, but maybe related to this changelog entry for `0.28.0`:

> HTTP proxy support is now builtin; libcurl is no longer used to support
> proxies and is removed as a dependency.

### Reproduction steps
`.gitconfig`:
```
$ cat .gitconfig
[http]
    proxy =
```
C-program:
```c
#include <stdio.h>
#include <dlfcn.h>
#include "include/git2.h"

// Compile:
//     gcc -o bug bug.c -ldl
// Run:
//     ./bug ./libgit2.so
int main(int argc, char *argv[]){
    if (argc != 2) {
        fprintf(stderr, "Wrong number of arguments\n");
        return 1;
    }

    void *handle;
    int (*git_libgit2_init)(void);
    int (*git_clone)(git_repository **out, const char *url, const char *local_path, const git_clone_options *options);
    git_error* (*git_error_last)(void);

    // dlopen and initialize libgit2
    handle = dlopen(argv[1], RTLD_LAZY);
    git_libgit2_init = dlsym(handle, "git_libgit2_init");
    git_libgit2_init();

    // git clone arguments
    git_repository *repo = NULL;
    const char *url = "https://github.com/octocat/Spoon-Knife.git";
    const char *path = "/tmp/Spoon-Knife";
    git_clone_options clone_opts = GIT_CLONE_OPTIONS_INIT;
    clone_opts.fetch_opts.proxy_opts.type = GIT_PROXY_AUTO; // <-- This is key

    // git clone
    git_clone = dlsym(handle, "git_clone");
    git_error_last = dlsym(handle, "git_error_last");
    int err = git_clone(&repo, url, path, &clone_opts);
    if (err != 0) {
        git_error* gerror = git_error_last();
        fprintf(stderr, "git clone failed. Message: %s, klass: %i, ret: %i\n", gerror->message, gerror->klass, err);
    }

    dlclose(handle);
    return err;
}

```
```
$ gcc -o bug bug.c -ldl

$ ./bug ./libgit2.so.0.28.3
git clone failed. Message: unrecognized URL prefix, klass: 12, ret: -1

$ ./bug ./libgit2.so.0.28.2
git clone failed. Message: unrecognized URL prefix, klass: 12, ret: -1

$ ./bug ./libgit2.so.0.28.1
git clone failed. Message: unrecognized URL prefix, klass: 12, ret: -1

$ ./bug ./libgit2.so.0.28.0
git clone failed. Message: unrecognized URL prefix, klass: 12, ret: -1

$ ./bug ./libgit2.so.0.27.9 # works
```

### Expected behavior

Presumably the empty entry should be ignored. This is what seems to happen in `libgit` `0.27.9`, and `git` does not complain either).

### Actual behavior
See above.

### Version of libgit2 (release number or SHA1)
Fails on `0.28.0`, `0.28.1`, `0.28.2`, `0.28.3` and `master` (5fc27aac6f47aaf06f454805f77c942c5a08393b). Works on `0.27.9`.

### Operating system(s) tested
Linux x86_64 (Ubuntu)

**Comment by ethomson** [comment]
Makes sense.  Thanks for the report.

**Comment by fredrikekre** [comment]
Can apparently also happen with an empty (but existing) environment variable: https://github.com/JuliaLang/julia/issues/33111#issuecomment-540539851

**Comment by StefanKarpinski** [comment]
Bump: this is still an ongoing problem for many Julia users who have proxies. So far this has been a problem for @omus, @kcajf, @tkluck, @wsshin, @antoine-levitt, @jdtuck, @jekriske-lilly, @gwatcha, @znmeb, @toktay, @jxy, @diabonas, @getzze, @tuhtah, @tastyminerals, @tbhaxor, @ghost, @hzhangxyz, @barche, @TLDay, @yalwan-iqvia, @CSchoel, @pmaldona, @samirop, @rideckard, @akabla, @casv2, @cycomanic, @tkf and @ShoofLLC at the very least. And those are only the people we know about. If the above listed could share reports here about their issues with using libgit2 (via Julia or otherwise) with git proxy settings.

**Comment by jdtuck** [comment]
For me the latest version I have no problems any more

**Comment by jdtuck** [comment]
As long as I make sure that the http and https proxy servers are correctly set. This can be done in the Julia REPL with the commands ENV[“HTTP_PROXY”] and ENV[“HTTPS_PROXY”].

**Comment by jekriske-lilly** [comment]
I still have an issue in 1.5.1 if there's no trailing forward slash in .gitconfig proxy entries (which shouldn't be necessary).

**Comment by jekriske-lilly** [comment]
I still have an issue in Julia 1.5.1 if there's no trailing slash in .gitconfig (which shouldn't be neccessary)

**Comment by barche** [comment]
I can confirm @jekriske-lilly 's observation, trailing slash was needed in .gitconfig.

**Comment by kcajf** [comment]
I still have this problem -  I have to add a trailing slash to my environment variables to work around it
