### ISSUE TITLE
Last part of stash message with a lot of \n passed to next read oid function.

### ISSUE THREAD

**Issue by lolgear** [libgit2/libgit2#5262]
### Reproduction steps
1. Create repository.
2. Add stashes with messages.
3. Add '\n' characters to stash messages.
4. Catch error "invalid characters in OID".

### Investigation
While you are reading message to 'first' occurrence of '\n', you will skip last part of message that can contain '\n'.
```
<valid_ref1> ... message
end_of_message
<valid_ref2>
```

or actual

```
76050078fc2923fdffb1b45e7231b4edfe4542b7 3cb51e2ace7b2aa4ebaa8985cf492117736b70f3 Author Name <author@email.opensource> 1566897223 +0300	On master: abc.
abc
3cb51e2ace7b2aa4ebaa8985cf492117736b70f3 e7454a3710b9ae4fbbdbe7fafa0699990355d88c Author Name <author@email.opensource> 1566897270 +0300	On master: abc
```

You will output "On master: abc." as a message. It is correct for sha-760.
But..
Last part of it (abc again, but with \n bracers around, \nabc\n) will exist and will be passed to next read oid function.

### Expected behavior
Skip last part of a message with a lot of '\n' and output only first part before first '\n'. (as `git stash list` do)

### Actual behavior
Do not skip last part of a message with a lot of '\n' and get invalid characters in oid error.

### Version of libgit2 (release number or SHA1)
Current master

### Operating system(s) tested
macOS 10.15

### Example
Example git repository in attachment.
[GitUpInvalidCharacters.zip](https://github.com/libgit2/libgit2/files/3716638/GitUpInvalidCharacters.zip)

**Comment by ethomson** [comment]
Fixed via #5275
