### ISSUE TITLE
libgit2's patch parser could ignore missing `index [:hexdigit:]+..[:hexdigit:]+ lines

### ISSUE THREAD

**Issue by durin42** [libgit2/libgit2#5267]
### Reproduction Steps

1. Generate a git-format diff with Mercurial, eg https://lists.sr.ht/~sircmpwn/sr.ht-dev/%3Caea421ff5fe46339493b.1570722314%40devahi%3E
2. Try to parse the diff with `git_patch_from_buffer()` or similar

### Expected Behavior
The patch parses fine.

### Actual Behavior
You get a parse error, of the form `invalid patch header at line NNN`.

### Investigation
I messed around with diff contents until I got past this particular parse error. If I add the line `index abcd..abcd` after the `diff --git ...` line and before the `--- a/...` line, the parse succeeds. That *appears* to be the only issue in patch-header parsing to allow hg-originated patches to parse just fine. I didn't get past that point in my investigation before other things required my attention, but I was convinced to at least file this bug.

### Version of libgit2
`ef5a3851f`

### Operating system(s) tested
Reproduces on both Linux and macOS

Example:
The patch at https://lists.sr.ht/~sircmpwn/sr.ht-dev/%3Caea421ff5fe46339493b.1570722314%40devahi%3E, or any output from `hg export --git SHA1` should get you started.

**Comment by pks-t** [comment]
Thanks a lot for your report!
