### ISSUE TITLE
add a simple example to show how to switch to an branch

### ISSUE THREAD

**Issue by Nelson-numerical-software** [libgit2/libgit2#5277]
git_clone seems to allow to clone directly on a branch.
But How to switch on branch after ?
stackoverflow does not have an working example.

Thanks to provide an simple example directly in your code
equivalent to:
git clone http:// ...
```
git branch -a
*  master
  remotes/origin/branch_dev
  remotes/origin/master
```
git checkout branch_dev

```
git branch -a
* branch_dev
  master
  remotes/origin/branch_dev
  remotes/origin/master
```

**Comment by pks-t** [comment]
Please have a look at our checkout example, which demonstrates show to switch between branches. One thing that it currently hasn't implemented is automatic creation of branches via git's guess heuristic (git switch --guess, git checkout --guess), but I've got that covered in #5283. Please let me know if this helps you.
