### ISSUE TITLE
git_worktree_validate return true if the worktree dir not exists.

### ISSUE THREAD

**Issue by Whirlwind** [libgit2/libgit2#5280]
I add a worktree to my repo. After remove the worktree path from my finder, the `git_worktree_validate` still return 0.

I check the code in the `worktree.c`:

https://github.com/libgit2/libgit2/blob/b246bed5ab83035d8aef95f1b7ff10dd746db7cb/src/worktree.c#L235-L262

It seems that it does not check the `worktree_path` exists. It check the `gitdir_path`、`commondir_path` and `parent_path`, but these paths are the origin git path, it exists.

**Comment by pks-t** [comment]
Indeed, we fail to check that, thanks for your report. It should probably be as simple as adding another check `if (!git_path_exists(wt->worktree_path))` and bailing out with an appropriate error message in that case. Would you like to create a pull request to fix this?

**Comment by rbmclean** [comment]
Mind if I try to tackle this and #5598 ? Seems like all that needs to be done is add in the check mentioned above and a test case demonstrating the flaw.

**Comment by ethomson** [comment]
That would be great @rbmclean !
