### ISSUE TITLE
config: crash when creating config snapshot

### ISSUE THREAD

**Issue by eaigner** [libgit2/libgit2#5281]
~~~
Hardware Model:      MacBookPro13,3
Code Type:       x86_64
Parent Process:  launchd [1]

Date/Time:       undefined
Launch Time:     undefined
OS Version:      Mac OS X 10.15.1 (19B77a)
Report Version:  104

Exception Type:  SIGSEGV
Exception Codes: SEGV_MAPERR at 0x4f2295f27810
Crashed Thread:  11

Thread 11 Crashed:
0   libsystem_platform.dylib             0x00007fff66136732 0x7fff66135000 + 5938
1   libsystem_c.dylib                    0x00007fff65fe6fdf 0x7fff65f90000 + 356319
2   Git                                  0x000000010e65b6ab stdalloc__strdup + 10
3   Git                                  0x000000010e6735fc git_config_entries_dup_entry + 91
4   Git                                  0x000000010e67387c git_config_entries_dup + 107
5   Git                                  0x000000010e674294 config_iterator_new + 51
6   Git                                  0x000000010e67682b config_readonly_open + 58
7   Git                                  0x000000010e67006f git_config_snapshot + 270
8   Git                                  0x000000010e6d6132 git_repository_config_snapshot + 33
9   Git                                  0x000000010e6d0824 git_remote_lookup + 259
10  Git                                  0x000000010e662a72 git_branch_upstream_name + 417
11  Git                                  0x000000010e662e26 git_branch_upstream + 85
~~~

**Comment by eaigner** [comment]
Nah, sorry. Not my machine :(

**Comment by pks-t** [comment]
Yeah, thought so. I'm currently investigating whether it's somehow possible to end up with a configuration entry without key, as that's my most likely lead right now.

**Comment by pks-t** [comment]
Do you by any chance have concurrence access to the repository/config from multiple threads at the same time or is there a single thread that performs all git-related functionality?

**Comment by pks-t** [comment]
Mh, okay. By now I assume that there might be a lifecycle issue somewhere due to improper use of refcounting of the config entries struct, mostly because I didn't find any way to allocate an entry config entry name at all.

**Comment by pks-t** [comment]
I think I've found a very likely candidate, as there is a rather severe race condition when creating iterators. When one thread e.g. refreshes config values while another one wants to create an iterator, then we might have free'd the config entries while duplicating them because we didn't properly increase the refcount. This bug would be very likely to show the exact same trace you've posted.

Please see #5282 for a fix.
