### ISSUE TITLE
HOME is not expanded in init.templatedir

### ISSUE THREAD

**Issue by BenWiederhake** [libgit2/libgit2#5290]
This is basically #2814 with shell variables.  My specific case isn't `templatedir = ~/gittemplate` but rather `templatedir = ${HOME}/Dropbox/org/dotfiles/git_templates`, and I expect this to happen for all variables.  The issue was not resolved by #2884.

### Reproduction steps

1. Have a `~/.gitconfig` with `templatedir = ${HOME}/my_git_templates`, where `${HOME}/my_git_templates` actually exists
1. Do `cargo new whatever`

(Sorry for the indirection, but I strongly believe that it actually is libgit2's issue, especially because #2814 is so similar regarding use case, primary cause, and fix.)

### Expected behavior

libgit2 can parse `~/.gitconfig` in the same way as the program git.  Specifically, it can substitute shell variables.

### Actual behavior

libgit2 can only understand `~`, and only for the current user, as is apparent from the code in [`git_config_parse_path`](https://github.com/libgit2/libgit2/blob/63307cbad7408b38693e73b74560a063da21f530/src/config.c#L1365).

### Version of libgit2 (release number or SHA1)

All?  Personally I'm using version [0.9.2](https://github.com/rust-lang/cargo/blob/23ef9a4ef/Cargo.toml#L34), but given that the code in libgit2 is still the same, I hope the version doesn't matter too much.

### Operating system(s) tested

Debian (but shouldn't matter)

**Comment by pks-t** [comment]
In fact this is not an issue, as we're strictly conforming to what upstream git does here. E.g.:

```$ strace -f -s1024 -e trace=file -e status=failed git -c 'init.templateDir=${HOME}/tmpl' init repo
access("/etc/gitconfig", R_OK)          = -1 ENOENT (No such file or directory)
access("/home/pks/.gitconfig", R_OK)    = -1 ENOENT (No such file or directory)
lstat("/tmp/repo/.git/commondir", 0x7fff40c49140) = -1 ENOENT (No such file or directory)
access("/etc/gitconfig", R_OK)          = -1 ENOENT (No such file or directory)
access("/home/pks/.gitconfig", R_OK)    = -1 ENOENT (No such file or directory)
mkdir("/tmp/repo/.git", 0777)           = -1 EEXIST (File exists)
lstat("/tmp/repo/.git/commondir", 0x7fff40c49150) = -1 ENOENT (No such file or directory)
open("${HOME}/tmpl/", O_RDONLY|O_CLOEXEC|O_DIRECTORY) = -1 ENOENT (No such file or directory)
warning: templates not found in ${HOME}/tmpl
access("/etc/gitconfig", R_OK)          = -1 ENOENT (No such file or directory)
access("/home/pks/.gitconfig", R_OK)    = -1 ENOENT (No such file or directory)
mkdir("/tmp/repo/.git/refs", 0777)      = -1 EEXIST (File exists)
lstat("/tmp/repo/.git/commondir", 0x7fff40c491c0) = -1 ENOENT (No such file or directory)
mkdir("/tmp/repo/.git/refs/heads", 0777) = -1 EEXIST (File exists)
mkdir("/tmp/repo/.git/refs/tags", 0777) = -1 EEXIST (File exists)
readlink("/tmp/repo/.git/config", 0x6434f4300a80, 32) = -1 EINVAL (Invalid argument)
readlink("/tmp/repo/.git/config", 0x6434f4300a40, 32) = -1 EINVAL (Invalid argument)
readlink("/tmp/repo/.git/config", 0x6434f4300a40, 32) = -1 EINVAL (Invalid argument)
mkdir("/tmp/repo/.git/objects", 0777)   = -1 EEXIST (File exists)
mkdir("/tmp/repo/.git/objects/pack", 0777) = -1 EEXIST (File exists)
mkdir("/tmp/repo/.git/objects/info", 0777) = -1 EEXIST (File exists)
Reinitialized existing Git repository in /tmp/repo/.git/
+++ exited with 0 +++
```

Note the line `open("${HOME}/tmpl/", O_RDONLY|O_CLOEXEC|O_DIRECTORY) = -1 ENOENT (No such file or directory)`. So git doesn't expand shell variables at all, and thus we won't do so either as we're trying to be as compatible as possible.

I'm thus closing this issue, but please feel free to correct me if you think I'm mistaken. We're definitely not opposed to adding this support, but upstreaming this in git.git needs to be first.

Anyway, thanks for raising this issue and sorry for taking so long to answer!

**Comment by BenWiederhake** [comment]
I don't know why git behaves differently when `init.templateDir` is set on the command-line versus set in the configfile, but apparently it does.  I've been using the configfile with `${HOME}` in it for a long time, and wouldn't have opened a bug if git didn't accept it.

Oh well, apparently `~/` works, so this is fine with me.

**Comment by ethomson** [comment]
Interesting!  @BenWiederhake could you provide the command that you're running and your literal `.gitconfig`?  I'd love to 👀 what's going on.

**Comment by BenWiederhake** [comment]
Oh boy.  Thanks for pointing me to `strace`, otherwise I wouldn't have noticed that this particular line of my `.gitconfig` got ingored.

Turns out, my `.bashrc` contains the line:
`export GIT_TEMPLATE_DIR=${HOME}/Dropbox/org/dotfiles/git_templates`
which of course gets executed by bash and therefore the variable gets resolved while bash starts.  Git then sees the environment variable, which apparently overrides both the command-line argument and `.gitconfig`.

If I comment that line out and start a new independent bash without that env var, it behaves as you describe it:
`openat(AT_FDCWD, "${HOME}/Dropbox/org/dotfiles/git_templates/", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = -1 ENOENT (Datei oder Verzeichnis nicht gefunden)`

So this is the story of how I got fooled for a very long time.

So @pks-t is correct: `git` does not show that behavior, and libgit2 shouldn't either.

**Comment by ethomson** [comment]
Aha!  Thanks for the additional investigation @BenWiederhake!

**Comment by pks-t** [comment]
On Fri, Dec 13, 2019 at 03:02:52PM -0800, Ben Wiederhake wrote:
> Oh boy.  Thanks for pointing me to `strace`, otherwise I
> wouldn't have noticed that this particular line of my
> `.gitconfig` got ingored.
> 
> Turns out, my `.bashrc` contains the line: `export
> GIT_TEMPLATE_DIR=${HOME}/Dropbox/org/dotfiles/git_templates`
> which of course gets executed by bash and therefore the
> variable gets resolved while bash starts.  Git then sees the
> environment variable, which apparently overrides both the
> command-line argument and `.gitconfig`.
> 
> If I comment that line out and start a new independent bash
> without that env var, it behaves as you describe it:
> `openat(AT_FDCWD,
> "${HOME}/Dropbox/org/dotfiles/git_templates/",
> O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = -1 ENOENT (Datei
> oder Verzeichnis nicht gefunden)`
> 
> So this is the story of how I got fooled for a very long time.
> 
> So @pks-t is correct: `git` does not show that behavior, and
> libgit2 shouldn't either.

Cool, thanks a lot for digging deeper!
