### ISSUE TITLE
Creating a snapshop of a snapshot caused null pointer dereference

### ISSUE THREAD

**Issue by csware** [libgit2/libgit2#5292]
### Reproduction steps

1. Create a config snapshot.
2. Create a snapshot of the snapshot (e.g., set a snapshot config using `git_repository_set_config` and then call `git_repository_set_head(repo, "refs/heads/other")` or `git_repository_hashfile`).

### Expected behavior

Creating a snapshot of a snapshot works.

Why is snapshotting a `config_mem` not possible? I though snapshotting can always be used to have an in memory read-only representation of any config which can be used everywhere (e.g., to avoid disk access).

### Actual behavior

Null-pointer dereference in `git_repository_config_snapshot`, because `snapshot` is not set for the snapshot backend.

### Version of libgit2 (release number or SHA1)

current master (tested on 257dd59d031f169a55afb55d0c34527fac71c11e)

**Comment by pks-t** [comment]
In #5293 you said it would partly fix the error reported here. So I wonder whether there is there a second part that needs fixing?

**Comment by csware** [comment]
`config_mem` cannot be snapshotted at all right now.

**Comment by pks-t** [comment]
See #5299

**Comment by ethomson** [comment]
Fixed via #5299
