### ISSUE TITLE
Git clone hangs forever

### ISSUE THREAD

**Issue by inech** [libgit2/libgit2#5294]
# Bug report
### Reproduction steps

1. Start **git_clone** of a repo (as an example you can use "https://github.com/aspnet/AspNetCore.git" but any other repo taking ~20 sec - 2 min to clone should be fine to reproduce this bug).
2. Wait for few seconds so the connection gets established.
3. Pull out an internet cable from the WiFI router (it assumes you're connected through WiFi without any VPNs, etc). The point here is to simulate **silent** connection drop so the server doesn't send "terminate" connection signal.
4. Wait for 5 minutes or more.
5. Put the internet cable back.

### Expected behavior
It should have timed out on step 4.

### Actual behavior
**git_clone** hangs **forever**.

### Version of libgit2 (release number or SHA1)
Commit: [572e4d8](https://github.com/libgit2/libgit2/tree/572e4d8)

### Operating system(s) tested
Microsoft Windows 10 Pro x64
Version: 10.0.18362 Build 18362

# Feature request
This bug is caused by #2502 PR which changes timeouts of [WinHttpRequest](https://docs.microsoft.com/en-us/windows/win32/winhttp/iwinhttprequest-settimeouts) to ResolveTimeout (Infinite), Connection (60 secs), SendTimeout (Infinite), ReceiveTimeout (Infinite).
This behavior caused for us a lot of trouble since we were syncing data from git to our internal database in the background process which just stuck in the loop so we were not getting important updates. Please, make it possible to specify timeouts or set some sensible defaults.

**Comment by inech** [comment]
I see it's related to #3334.

**Comment by thiloschulz** [comment]
Yes, user applications should be able to specify timeouts. But from my point of view the problem goes much deeper. I have opened https://github.com/libgit2/discussions/issues/14 for discussion.

**Comment by Blueve** [comment]
Vote for this topic.
We have a very big git repository which usually cost hours to clone and seems very easy to touch this bug. The hanging just without any exceptions and everything blocked.

A possible workaround is put the clone to a thread and monitor the progress, if the progress stuck more than a threshold, then kill the thread and do the clean up for the repo root dir.

**Comment by thiloschulz** [comment]
Killing the thread may work for you, but it is not a proper solution.
The thread may have allocated resources which would need to be freed somewhere after the syscall it's stuck in rerturns, and which you cannot get at from git_remote. Furthermore, you'll potentially leave git_remote in an inconsistent state.

**Comment by dcecile** [comment]
Maybe similar to @Blueve, I have a repo (not too big, 8.8 MB) that clones fine using `git clone`, but hangs often when trying to use pygit2 to clone.

Is there something that `git clone` is doing to avoid this issue? Retries or something?

**Comment by ethomson** [comment]
@dcecile to the best of my knowledge, no `git clone` is never doing retries.  It may be timing out though (per this issue) and so you would see git and libgit2 fail differently.  Is that possible?  If so, this issue would resolve your problem.  If not, opening a new issue may help.  (If you're not sure, then a new issue would be most beneficial.)  It would be useful to know how often libgit2 fails, how long the clone takes when it _does_ succeed, etc.  Do you know when in the clone process you're hanging?  Do you have status callbacks set up?  If not, setting them up would be helpful to get some more insight into what's happening.

**Comment by saurabh-deep** [comment]
This is causing issues for us also. When the connection drops in the middle of `git clone` it just hangs and you have to kill the process.

 Hey @ethomson! Are there any plans to look into this one?

**Comment by freemanjohn** [comment]
Gave up on pygit2 and just used GitPython with SSH authentication

**Comment by ethomson** [comment]
We added timeouts! Closing this as stale.
