### ISSUE TITLE
CI doesn't Coverity Scan anymore

### ISSUE THREAD

**Issue by tiennou** [libgit2/libgit2#5297]
It seems Coverity is stuck with a build from May. IIRC the last thing done before it went down at the beginning of the year is #4922, then it went down for a couple month, was reinstated into CI by #4962, but it somehow still shows as version `c9f116f` from May 13, 2019.

I've tried to understand a little what could be going wrong, as far as I know there's a green [Coverity pipeline](https://dev.azure.com/libgit2/libgit2/_build?definitionId=21), but I'm not sure how debuggable all this is (arguably since the Travis switch 🤣) . Should I be able to dockerize that pipeline locally and check what's going on ? Is there an helpful guide somewhere I missed 😉  ?

**Comment by pks-t** [comment]
This has been fixed meanwhile, so I'm closing this. Thanks for the report! :+1d
