### ISSUE TITLE
Support push options

### ISSUE THREAD

**Issue by sathieu** [libgit2/libgit2#5335]
Git supports push options since v2.10.

They can be set on CLI, (`-o`) or using the `push.pushOption` config.

Please add support for this in libgit2 and pygit2.

Refs:
- Git's client-side push options: https://github.com/git/git/commit/f6a4e61fbb647928d615a0befaec163a5d2bf4af
- Gitlab's server-side push options: https://docs.gitlab.com/ee/user/project/push_options.html#push-options

**Comment by pablonardone** [comment]
Was there any progress for this issue?
