### ISSUE TITLE
Writing pack into repository

### ISSUE THREAD

**Issue by stoically** [libgit2/libgit2#5349]
Thanks for the excellent work on libgit2!

I'm looking for a way to manually import packfiles that were [written](https://libgit2.org/libgit2/#HEAD/group/packbuilder/git_packbuilder_write) using the [packbuilder](https://libgit2.org/libgit2/#HEAD/group/packbuilder/git_packbuilder_new). It should just write them into an [opened repository](https://libgit2.org/libgit2/#HEAD/group/repository/git_repository_open), no custom odb backend or such. So basically what fetch is already doing, but manually.

There's [git_odb_write_pack](https://libgit2.org/libgit2/#HEAD/group/odb/git_odb_write_pack), but that seems to require to manually implement a writepack function, but I'm not sure how to do that and I think that the functionality is already in libgit2 somewhere?

I also saw https://github.com/libgit2/libgit2/issues/4494 and https://github.com/libgit2/libgit2/issues/3098 which seem to be related, but were asking for something different.

Any pointers would be appreciated and sorry if I missed something obvious!

**Comment by stoically** [comment]
Ok, I did miss something obvious - https://github.com/libgit2/libgit2/issues/3098#issuecomment-99127987 pretty much explains it, I just didn't realize. Sorry for the noise.

**Comment by stoically** [comment]
Just for reference,

<details>
<summary>here's how I ended up doing it (yes, I'm new to C)</summary>

```c
#include <stdio.h>
#include <git2.h>


main() {
    git_libgit2_init();

    git_repository *repo = NULL;
    git_repository_open(&repo, ".");

    git_odb *odb = NULL;
    git_repository_odb(&odb, repo);

    git_odb_writepack *writepack = NULL;

    void *progress_payload = NULL;
    git_transfer_progress_cb progress_cb;
    git_odb_write_pack(&writepack, odb, progress_cb, progress_payload);


    // https://stackoverflow.com/a/2029227
    char *source = NULL;
    size_t bufsize = -1;
    FILE *fp = fopen("file.pack", "r");
    if (fp != NULL) {
        /* Go to the end of the file. */
        if (fseek(fp, 0L, SEEK_END) == 0) {
            /* Get the size of the file. */
            bufsize = ftell(fp);
            if (bufsize == -1) { /* Error */ }

            /* Allocate our buffer to that size. */
            source = malloc(sizeof(char) * (bufsize + 1));

            /* Go back to the start of the file. */
            if (fseek(fp, 0L, SEEK_SET) != 0) { /* Error */ }

            /* Read the entire file into memory. */
            size_t newLen = fread(source, sizeof(char), bufsize, fp);
            if ( ferror( fp ) != 0 ) {
                fputs("Error reading file", stderr);
            } else {
                source[newLen++] = '\0'; /* Just to be safe. */
            }
        }
        fclose(fp);
    }

    git_transfer_progress *progress;
    writepack->append(writepack, source, bufsize, progress);
    writepack->commit(writepack, progress);

    return 0;
}
```
</details>

**Comment by pks-t** [comment]
Fair enough. If there's any way how we could improve documentation around this feature that would've helped you, please feel free to create a pull request to address that.

Anyway, thanks for posting your solution!
