### ISSUE TITLE
reject attempts to delete HEAD

### ISSUE THREAD

**Issue by josharian** [libgit2/libgit2#5357]
I just wrote some buggy code in which I accidentally deleted HEAD, rather than its symbolic target. However, HEAD is required to exist.

Given that deleting HEAD is not a legitimate git operation (it turns a git dir into a non-git dit), perhaps libgit2 could prevent this by returning an error when `git_reference_delete` is called on HEAD. I'm not sure what error code/class would be the right one, though.

Sound ok?

**Comment by ethomson** [comment]
Yeah, deleting HEAD is no good.  We should prevent this.  Here's what git says when you try to `symbolic-ref --delete HEAD`:

> deleting 'HEAD' is not allowed

I think the `GIT_ERROR_REFERENCE` is appropriate here.
