### ISSUE TITLE
Merge msg may contain password

### ISSUE THREAD

**Issue by mad8vad** [libgit2/libgit2#5370]
If clone repo by `https://login:password@bitbucket...` this url will be stored at .git/config
Then `merge_msg_write_remotes()` just print url to MERGE_MSG file

Git removes credentials from merge msg (as well as .git after repository name)

Need to do something like
`new_source = strdup(source);`
`strcpy(strstr(new_source, "https://") + 8, strstr(new_source, "@") + 1);`

**Comment by pks-t** [comment]
Thanks a lot for your report, this is definitely bad. I've just taken a look and didn't find a way to reproduce via just doing the equivalent of git-clone(1). Thing is as soon as there's a remote from which we're merging, the merge message will contain that remote's name and not its URL. So if you still managed to produce that error via git-clone(1), could you please provide some instructions?

That being said, I _was_ able to reproduce this via "git fetch https://foo:bar@example.com/repo". This will write FETCH_HEAD, which contains the URL and we didn't strip off the credentials causing it to potentially end up in MERGE_MSG. Upstream git always writes a sanitized URL to FETCH_HEAD, and I've fixed libgit2 in #5373.

So please let me know whether #5373 already fixes your problem or if you happened to find another way to abuse this.

**Comment by ethomson** [comment]
Thanks for the report @mad8vad - I merged @pks-t's change - please let us know if there are other ways to reproduce this.

**Comment by mad8vad** [comment]
It helped, thank you
