### ISSUE TITLE
use error code GIT_EAUTH for HTTP auth failures

### ISSUE THREAD

**Issue by josharian** [libgit2/libgit2#5389]
b9c5b15 is backwards incompatible. (Related: #5385.) Prior to that commit, HTTP auth failures had an error class of `GIT_ERROR_NET`. That commit changes them to `GIT_ERROR_HTTP`. I will adjust my code accordingly, but it should probably be called out in the release notes.

That said, it'd be nicer to have a more precise error code for auth failures. For lack of a good alternative, I currently check the error class and then do a string match for the word "authentication", because the error code is a generic `GIT_ERROR`. There is already an error code for authentication failures, `GIT_EAUTH`, but it appears that only the ssh network operations return it.

I'd like to suggest that HTTP use it too. Now is a particularly good time to switch, since people may have to update their error handling in light of b9c5b15 anyway.

cc @ethomson @pks-t

**Comment by pks-t** [comment]
> b9c5b15 is backwards incompatible. (Related: #5385.) Prior to that commit, HTTP auth failures had an error class of GIT_ERROR_NET. That commit changes them to GIT_ERROR_HTTP. I will adjust my code accordingly, but it should probably be called out in the release notes.

Well, that goes on my cap. Sheesh, there's a whole lot more to backwards compatibility than one thinks of at first. Maybe we should even revert the introduction of `GIT_ERROR_HTTP`, as silent breakage is the worst kind of breakage. @ethomson?

> That said, it'd be nicer to have a more precise error code for auth failures.

Totally agreed, if you ask me.

**Comment by josharian** [comment]
> Sheesh, there's a whole lot more to backwards compatibility than one thinks of at first.

Is there ever! :) I've a pretty active contributor to the Go compiler for a while. Go takes backwards compatibility extremely seriously, and yet folks who have been working on it for a decade are still surprised. Very recent example: https://github.com/golang/go/issues/28591#issuecomment-583093984.

Fortunately (or unfortunately?), I don't think libgit2 has quite the same level of commitment to backwards compatibility.

> more precise error code for auth failures

I'm happy to do the legwork on this, if the http code has stabilized enough that I won't just be in the way. Or unless @ethomson would prefer to do it.

**Comment by ethomson** [comment]
> I'm happy to do the legwork on this, if the http code has stabilized enough that I won't just be in the way. Or unless @ethomson would prefer to do it.

You would not be in the way - on the contrary, your contributions would be welcome!  😀
