### ISSUE TITLE
Compile fails on FreeBSD with ld: error: undefined symbol: htonll

### ISSUE THREAD

**Issue by mfechner** [libgit2/libgit2#5414]
I maintain the libgit2 package for FreeBSD.

### Reproduction steps
Try to compile the new version 0.99.0 on FreeBSD.

### Expected behavior
It should compile.

### Actual behavior
Get a linker error:
```
ld: error: undefined symbol: htonll
>>> referenced by ntlm.c
>>>               deps/ntlmclient/CMakeFiles/ntlmclient.dir/ntlm.c.o:(ntlm_client_response)

ld: error: undefined symbol: htonll
>>> referenced by ntlm.c
>>>               deps/ntlmclient/CMakeFiles/ntlmclient.dir/ntlm.c.o:(ntlm_client_response)

ld: error: undefined symbol: htonll
>>> referenced by ntlm.c
>>>               deps/ntlmclient/CMakeFiles/ntlmclient.dir/ntlm.c.o:(ntlm_client_response)
```

You can find the full build log here:
https://pkg.fechner.net/data/121amd64-gitlab/2020-02-20_22h51m26s/logs/errors/libgit2-0.99.0.log

### Version of libgit2 (release number or SHA1)
0.99.0

### Operating system(s) tested
FreeBSD

**Comment by hkrummeck** [comment]
The same happens on SunOS (5.10)

**Comment by pks-t** [comment]
Thanks for your bug report. Just for your interest: you can work around the issue by setting USE_NTLMCLIENT=OFF, but obviously this disables support for NTLM. Anyway, we should get this fixed.

Could you please check whether #5417 fixes the problem?

**Comment by mfechner** [comment]
> Could you please check whether #5417 fixes the problem?

thanks a lot, that fixes the problem for FreeBSD.

**Comment by pks-t** [comment]
Thanks a lot for confirming. Will wait for @hkrummeck's feedback before merging #5417.

**Comment by pks-t** [comment]
@ethomson: do you know if there is an easy way for us to get at least one of the BSDs into Azure so that we have testing for them? I'd be happy to set up required scripts when we've got a VM.

**Comment by hkrummeck** [comment]
Unfortunately this does not work for **SunOS 10**, there is no **htonll** defined.
It was apparently only introduced in Sunos 11.

At least on SPARC this should be a null operation:

```
#if defined(_BIG_ENDIAN) && !defined(ntohll)
#define ntohll(x)       (x)
#define htonll(x)       (x)
#endif
```

I found another issue in _../src/transports/auth_ntlm.c,_ **strndup** is not available in SunOS 10. I suppose this should be **git__strndup**?

With these 2 changes it can be compiled and linked.

**Comment by ethomson** [comment]
> Unfortunately this does not work for SunOS 10, there is no htonll defined.
> It was apparently first introduced in Sunos 11.

Thanks for the info.  We should be cognizant of little endian machines as well, as there was SunOS for x86 platforms.

> I found another issue in ../src/transports/auth_ntlm.c, strndup is not available in SunOS 10. I suppose this should be git__strndup?

Yes, thanks, it probably should.

**Comment by ethomson** [comment]
> @ethomson: do you know if there is an easy way for us to get at least one of the BSDs into Azure so that we have testing for them? I'd be happy to set up required scripts when we've got a VM.

I started working on this: https://github.com/ethomson/libgit2/commit/1fe3fa5e59818c851d50efc6563db5f8a5d7ae9b

Maintaining a FreeBSD machine is a bit of a pain, due to cost.  It gets disabled if I hit my preset spending limits in my cloud provider, which would cause the nightlies to fail.  But we can and should figure out a solution here.

**Comment by pks-t** [comment]
@hkrummeck: I've amended my PR to hopefully fix this with SunOS<=10

**Comment by pks-t** [comment]
I've also rolled in the strndup/strdup fixes. @ethomson, please let me know if I should move them into a separate PR. They seem to be trivial enough though to keep them here, though

**Comment by ethomson** [comment]
This LGTM

**Comment by hkrummeck** [comment]
Yes, thanks, this fix builds on SunOS 10.
