### ISSUE TITLE
Please link http-parser issues

### ISSUE THREAD

**Issue by mgorny** [libgit2/libgit2#5416]
`changelog.md` states that:

> This is due to a deficiency in http-parser that we have fixed in our implementation. The bundled library is now the default [...]

However, it doesn't really indicate what the claimed 'deficiency' is. My guess would be that the 'deficiency' is fixed by either of the following commits:

https://github.com/libgit2/libgit2/commit/1bbdec69bef50208f77f0c4cbac7c6b56c35973f#diff-2fa8bbf310441e8c75f4177e97e10e47
https://github.com/libgit2/libgit2/commit/b292c35fef2c0e509571a12f55a35e2ea30ef944#diff-2fa8bbf310441e8c75f4177e97e10e47

However, I wasn't able to find a matching issue report or pull request upstream. Could you please link them, so that we could track when we can switch back to non-bundled libraries?

**Comment by ethomson** [comment]
@mgorny https://github.com/nodejs/http-parser/pull/483

**Comment by pks-t** [comment]
Closing this issue -- please feel free to re-open in case you don't see your request as solved!
