### ISSUE TITLE
0.99.0: Performance regression in Mac OS clone

### ISSUE THREAD

**Issue by implausible** [libgit2/libgit2#5427]
# Reproduction steps
1. Be on Mac OS
2. Clone libgit2 from: https://github.com/implausible/libgit2/tree/repro/slow-clone-mac-os
3. Build libgit2
4. run the test suite `online::slow::clone`.

### Expected behavior
The test suite should finish in 10 seconds. Note, I've also added 
https://github.com/implausible/libgit2/tree/repro/fast-clone-mac-os which has the same test suite built before #5286 was merged. Running that on Mac OS, the suite finishes in <10s.

### Actual behavior
The test suite finishes in 2 to 3 minutes. This behavior is completely isolated to Mac OS.

### Version of libgit2 (release number or SHA1)
I've tracked the change to `4460bf40c9e935acb853b5d61279a50014ede0b3` or #5286. This is still slow in 0.99.0.

### Operating system(s) tested
Mac OS
Linux
Windows

**Comment by ethomson** [comment]
I cherry-picked that test onto `f9b41a6600f35f36ba5381f355355c303bd05df1` (before the HTTP refactoring)...

```
% time ./libgit2_clar -sonline::slow::clone
Loaded 386 suites:
Started (test status codes: OK='.' FAILURE='F' SKIPPED='S')
..

./libgit2_clar -sonline::slow::clone  2.34s user 0.53s system 2% cpu 2:10.33 total
```

When I cherry-pick that test onto `a48da8fab662aaa77340a3e969ac0deec9d51731` (the current master)...

```
% time ./libgit2_clar -sonline::slow::clone
Loaded 386 suites:
Started (test status codes: OK='.' FAILURE='F' SKIPPED='S')
..

./libgit2_clar -sonline::slow::clone  2.17s user 0.53s system 2% cpu 2:11.70 total
```

**Comment by ethomson** [comment]
It seemed a bit like the first test was slower (just watching it), so running only `online::slow::clone::can_clone_with_https` (commenting out the one that does it twice).

On `f9b41a6600f35f36ba5381f355355c303bd05df1 `:

```
% time ./libgit2_clar -sonline::slow::clone::can_clone_with_https
Loaded 386 suites:
Started (test status codes: OK='.' FAILURE='F' SKIPPED='S')
.

./libgit2_clar -sonline::slow::clone::can_clone_with_https  0.72s user 0.17s system 1% cpu 1:03.31 total
```

On `master`:

```
% time ./libgit2_clar -sonline::slow::clone::can_clone_with_https
Loaded 386 suites:
Started (test status codes: OK='.' FAILURE='F' SKIPPED='S')
.

./libgit2_clar -sonline::slow::clone::can_clone_with_https  0.77s user 0.15s system 1% cpu 1:02.57 total
```

**Comment by implausible** [comment]
I am on Mac OS 10.15.2 and can consistently reproduce this. I'll hook up a dummy repo with some github actions on it to demonstrate this, because I can reproduce this on github's servers as well.

**Comment by implausible** [comment]
So I've moved the `repro/slow-clone-mac-os` and `repro/fast-clone-mac-os` around so that they're based on the same points but have an intermediate master with this github actions file:
https://github.com/implausible/libgit2/blob/master/.github/workflows/demo.yml

Before the introduction to the new http client in libgit2 you can see the test stage finishes in 6 seconds:
https://github.com/implausible/libgit2/runs/473513487?check_suite_focus=true

After the change, the test suite finishes in 3m4s:
https://github.com/implausible/libgit2/runs/473519868?check_suite_focus=true

**Comment by implausible** [comment]
Just some notes, I've also given this a try with the new expect continue flag enabled and got the same results.

**Comment by ethomson** [comment]
I really don't understand what's going on here yet.  I checked out `repro/fast-clone-mac-os`, and it indeed ran quickly.  Then I checked out `repro/slow-clone-mac-os` and built it.  Here's what happens when I did...  the first run was quick, so I was like "what, which branch did I really check out?" and ...  sure enough, it was `repro/slow-clone-mac-os`.  So then I ran it again and it took a minute.

```
zoidberg:libgit2/libgit2/build% time ./libgit2_clar -sonline::slow::clone::can_clone_with_https_once
Loaded 386 suites:
Started (test status codes: OK='.' FAILURE='F' SKIPPED='S')
.

./libgit2_clar -sonline::slow::clone::can_clone_with_https_once  0.93s user 0.22s system 27% cpu 4.109 total
zoidberg:libgit2/libgit2/build% git branch
  0_99
  ethomson/credtype
  ethomson/gssapi
  ethomson/gssapi.bak
  ethomson/no_void
  master
  pks/valgrind-openssl
  repro/fast-clone-mac-os
* repro/slow-clone-mac-os
zoidberg:libgit2/libgit2/build% time ./libgit2_clar -sonline::slow::clone::can_clone_with_https_once
Loaded 386 suites:
Started (test status codes: OK='.' FAILURE='F' SKIPPED='S')
.

./libgit2_clar -sonline::slow::clone::can_clone_with_https_once  0.93s user 0.22s system 1% cpu 1:04.29 total
```

This is very puzzling.  Here's a few more runs...

```
zoidberg:libgit2/libgit2/build% time ./libgit2_clar -sonline::slow::clone::can_clone_with_https_once
Loaded 386 suites:
Started (test status codes: OK='.' FAILURE='F' SKIPPED='S')
.

./libgit2_clar -sonline::slow::clone::can_clone_with_https_once  0.90s user 0.22s system 32% cpu 3.507 total
zoidberg:libgit2/libgit2/build% time ./libgit2_clar -sonline::slow::clone::can_clone_with_https_once
Loaded 386 suites:
Started (test status codes: OK='.' FAILURE='F' SKIPPED='S')
.

./libgit2_clar -sonline::slow::clone::can_clone_with_https_once  0.90s user 0.23s system 23% cpu 4.849 total
zoidberg:libgit2/libgit2/build% time ./libgit2_clar -sonline::slow::clone::can_clone_with_https_once
Loaded 386 suites:
Started (test status codes: OK='.' FAILURE='F' SKIPPED='S')
.

./libgit2_clar -sonline::slow::clone::can_clone_with_https_once  0.91s user 0.22s system 22% cpu 4.963 total
zoidberg:libgit2/libgit2/build% time ./libgit2_clar -sonline::slow::clone::can_clone_with_https_once
Loaded 386 suites:
Started (test status codes: OK='.' FAILURE='F' SKIPPED='S')
.

./libgit2_clar -sonline::slow::clone::can_clone_with_https_once  0.86s user 0.20s system 1% cpu 1:03.70 total
```

So...  it either takes 4 seconds or a minute and 4 seconds.  Weird.

**Comment by ethomson** [comment]
Indeed, that one minute and 4 seconds is _important_.  It's hitting a 60 second timeout.

This is some weird (probably _wrong_ but that doesn't really matter for our purposes) behavior in SecureTransport.

See https://github.com/seanmonstar/reqwest/issues/26 for a similar complaint.

I'm pretty sure that simply changing the buffer size that we try to read to 16k (that's the size of a TLS packet) is a sufficient fix here but I need to understand better what rust actually did here to fix this.

**Comment by ethomson** [comment]
Also of interest is to answer _why did this start with the HTTP stack change_.  Some possible options:

1. We do keep-alive more than we used to.  The problem here is that we're doing an `SSLRead` of 8kb at the end of the returned packfile of a keep-alive session.  `SSLRead` is not returning data that it seems to have buffered until the connection is closed (because it was idle for 60 seconds).
2. We changed the buffer size that we use for reads - maybe it used to be 16 kb.

**Comment by ethomson** [comment]
The buffer was 64kb.  Changing to read an 8kb buffer in the old code repros for me.

**Comment by ethomson** [comment]
So here's [more information about this issue](https://github.com/seanmonstar/reqwest/issues/26#issuecomment-290205986):

> I believe I've found the issue. Searching the Apple's source code for `SSLRead` revealed that if called with data length longer than what was buffered internally in SslContext, it would copy from the buffer, and then perform a socket read. This is contrary to how typical IO objects work, such as TCP will first return the data in its buffer, and only subsequent calls will block on the socket.

[Looking in the `SSLRead` source shows this fun comment](https://gist.github.com/seanmonstar/c58fc023d60bc295230539f2f4c82a0c#file-ssltransport-cpp-L94-L98):

> what we really have to do is just return as soon as we read one record

This is why moving to a buffer larger than 16 kb (the maximum size of a TLS packet -- in other words, "one record" -- will fix this.
