### ISSUE TITLE
docs: git_repository_commondir docs are confusing

### ISSUE THREAD

**Issue by josharian** [libgit2/libgit2#5428]
https://libgit2.org/libgit2/#HEAD/group/repository/git_repository_commondir says:

> If the repository is bare is not a worktree, the git directory path is returned.

I don't know how to parse that. :) I'd fix it, but I'm not 100% sure what it would say. Happy to send a PR if someone can give me a hint about the behavior.

**Comment by pks-t** [comment]
On Thu, Feb 27, 2020 at 04:31:27PM -0800, Josh Bleecher Snyder wrote:
> https://libgit2.org/libgit2/#HEAD/group/repository/git_repository_commondir says:
> 
> > If the repository is bare is not a worktree, the git directory path is returned.
> 
> I don't know how to parse that. :) I'd fix it, but I'm not 100% sure
> what it would say. Happy to send a PR if someone can give me a hint
> about the behavior.

Neither do I. And to be honest, I always have to refresh my memory about
commondirs.

The common directory is the same as the gitdir for all repository types
except for worktrees, where gitdir and commondir are different. For such
a worktree, commondir is the parent repo's gitdir and gitdir is
"$parentrepo/.git/worktrees/$worktree/".

I'd say we should just replace the part you've quoted with the above or
something similar, which does help a lot more. Or at least I think so ;)
