### ISSUE TITLE
Segfault when calling git_blame_buffer

### ISSUE THREAD

**Issue by xldenis** [libgit2/libgit2#5443]
Hi! 

I managed to trigger a segfault when running git blame buffer. 

It seems like if a blame buffer is run on a file with a single hunk then the `line_cb` is called before the `hunk_cb` and tries to dereference a null `current_hunk` pointer. 

If I add more lines in a second commit then the problem goes away.

I can't follow the the actual process of blaming a buffer, I get lost with all the callbacks etc.. However, I made a minimal testcase that causes this segfault and added it to a fork of the repo.
 
### Reproduction steps

Using my branch at github.com/xldenis/libgit2

Build and then run the test:

 `cmake -sblame::buffer::segfault`

### Expected behavior

I expect it to return a blame result with two hunks

### Actual behavior

segfault :(

### Version of libgit2 (release number or SHA1)

cb17630b75dbdc502c21da8e73641fa932bc8c6b

### Operating system(s) tested

OS X

**Comment by pks-t** [comment]
Thanks a lot for your report! Could you please verify whether #5445 fixes your problem?

**Comment by xldenis** [comment]
I'll check it out right now.

**Comment by xldenis** [comment]
My test passes with your commit.
