### ISSUE TITLE
Ability to test long paths...

### ISSUE THREAD

**Issue by DynConcepts** [libgit2/libgit2#5446]
I have an immediate specific need for long path support on windows. Found

Support `core.longpaths` on Windows #5347

but it does not appear to have been merged yet.....

It there a build (even if unofficial) that I could use for test purposes???

**Comment by tapika** [comment]
Can be tested like this:

    using (var config = Configuration.BuildFrom(null))
    {
        var longpaths = config.GetValueOrDefault<bool>("core.longpaths", ConfigurationLevel.Global);

        // can use also "git config --system core.longpaths true", but requires elevation.
        if (!longpaths)
            longpaths = config.GetValueOrDefault<bool>("core.longpaths", ConfigurationLevel.System);

        _useCoreLongPaths = !longpaths;
    }


Also need to test that windows supports long paths:

    [SupportedOSPlatform("windows")]
    static bool Reconfigure()
    {
        using (RegistryKey key = Registry.LocalMachine.OpenSubKey(@"SYSTEM\CurrentControlSet\Control\FileSystem"))
        {
            object o = key.GetValue("LongPathsEnabled");
            if (!(o is int) || (int)o == 0)
            {
                Console.WriteLine("\n\nError: Please enable 'LongPathsEnabled' registry entry accoding to:\n" +
                    "https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry\n");
                return false;
            }
        }

        return true;
    }


    ...somewhere in Main...

    if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows) && !Reconfigure())
    {
        return -3;
    }

Maybe close this ticket ?

**Comment by ethomson** [comment]
👍 Indeed we support long paths on windows.
