### ISSUE TITLE
Attribute lookup fails when path contains invalid utf8

### ISSUE THREAD

**Issue by carlosmn** [libgit2/libgit2#5450]
### Reproduction steps

Call `Rugged::Repository#fetch_attributes` which boils down to `git_attr_get_many`, `git_attr_get`, or `git_attr_foreach`. If you pass a path like `"test/fixtures/ba\xEF\xBF\xBDr/file_\xC3\xA3.pl"` none of them are able to look up attributes for this path.

### Expected behavior

The lookup should return the set attributes

### Actual behavior

It does not

### Version of libgit2 (release number or SHA1)

v0.99.0 behaves this way, v0.28.4 does not. There are no changes in rugged between these versions so it looks like a regression in the library.

### Operating system(s) tested

Debian, and I assume @lildude is running this on macOS.

/cc github/linguist#4813

**Comment by lildude** [comment]
> @lildude is running this on macOS.

I am.

**Comment by carlosmn** [comment]
Bisecting tells me that 05f9986a3555e3c5768e949743ed6dcdbd88252c is the commit which broke this which is the commit that converted to wildmatch so that might be a fun one to untangle.

**Comment by carlosmn** [comment]
So... FWIW

```
% git check-attr -a test/fixtures/ba�r/file_ã.pl
% git check-attr -a test/fixtures/foo.rb
test/fixtures/foo.rb: linguist-vendored: false
```

it looks like git does not work here either, so I guess we are both using wildmatch the same way or wildmatch does not like this path which is really annoying as it breaks the Git promise of paths being sequences of bytes.

**Comment by carlosmn** [comment]
It turns out the above behaviour isn't about the weird path, but about it being in a subdirectory. The change to wildmatch means that we want two asterisks in order for the rules to apply recursively. If I change the rule to be

```
test/fixtures/** linguist-vendored=false
```

then I do see the expected output

```
% git check-attr -a test/fixtures/ba�r/file_ã.pl
"test/fixtures/ba\357\277\275r/file_\303\243.pl": linguist-vendored: false
```

**Comment by carlosmn** [comment]
Well it turns out it's not a bug just a change in behaviour.

**Comment by ethomson** [comment]
Sorry we broke y'all, but yeah, there was a behavioral change here to align with git's behavior.
