### ISSUE TITLE
git_diff_from_buffer fails to parse a patch when it involves a rename and file mode change

### ISSUE THREAD

**Issue by ollieatkinson** [libgit2/libgit2#5460]
### Reproduction steps

```diff
diff --git a/RENAMED.md b/README.md
old mode 100644
new mode 100755
similarity index 100%
rename from RENAMED.md
rename to README.md

```

using the above as input to `git_diff_from_buffer`, it fails with the message:

```
failed - invalid patch header at line 4
```

This seems to occur only when there is a rename and file mode change involved in the diff, since it operates fine if I do not have a rename involved.

---

I've attached a small reproduction of the behaviour. [reproduction.zip](https://github.com/libgit2/libgit2/files/4370818/reproduction.zip)

```bash
$ swift run
```

### Expected behaviour

diff is parsed without an error being omitted.

### Actual behaviour

```
failed - invalid patch header at line 4
```

### Version of libgit2 (release number or SHA1)

0.28.4

### Operating system(s) tested

macOS 10.15

**Comment by pks-t** [comment]
Thanks a lot for your bug report! I've verified that the patch you provide is what git.git would generate, so the report is definitely valid. I've fixed this bug in #5466.

**Comment by ollieatkinson** [comment]
Thanks for taking the time to fix this one @pks-t - if you're interested to how I found this... I did by auto-generating some test cases for a tool I am building:

```bash
#!/bin/bash

git -C repo fetch

branches=$(git -C repo branch --all --list --format='%(refname:short)' | grep origin | grep -v HEAD)

mkdir -p patch_files

for a in $branches; do
  for b in $branches; do
    if [ "$a" != "$b" ]; then
      git -C repo diff -M20 $a $b > patch_files/${a////_}_to_${b////_}.diff
    fi
  done
done
```

I have also found some issues with the `similarity index` being different, but I am still trying to understand the impacts of that.

**Comment by pks-t** [comment]
On Thu, Mar 26, 2020 at 07:32:46AM -0700, Oliver Atkinson wrote:
> Thanks for taking the time to fix this one @pks-t - if you're
> interested to how I found this... I did by auto-generating some test
> cases for a tool I am building:
> 
> ```bash
> #!/bin/bash
> 
> git -C repo fetch
> 
> branches=$(git -C repo branch --all --list --format='%(refname:short)' | grep origin | grep -v HEAD)
> 
> mkdir -p patch_files
> 
> for a in $branches; do
>   for b in $branches; do
>     if [ "$a" != "$b" ]; then
>       git -C repo diff -M20 $a $b > patch_files/${a////_}_to_${b////_}.diff
>     fi
>   done
> done
> ```
> 
> I have also found some issues with the `similarity index` being
> different, but I am still trying to understand the impacts of that.

That's great! I'm happy to fix whatever differences in diff parsing we
have compared to upstream git.git, so please feel free to raise issues
for whatever inconsistencies you find.

You could probably automate this even further by creating a libgit2
executable that gets a patch as stdin, parses it via libgit2's API,
print it to stdout the way libgit2 understood it and then do a diff of
git's and libgit2's patch. That should be quite easy to code up as we
can just reuse our patch infrastructure.
