### ISSUE TITLE
Does libgit2 support Kerberos for SSH?

### ISSUE THREAD

**Issue by Whirlwind** [libgit2/libgit2#5470]
My server support Kerberos/GSSAPI for SSH, but not for HTTPS.
I build the libgit2 with `-DUSE_GSSAPI=ON`, and the GSSAPI is work. But It seems that it do not support the GSSAPI for the SSH.
I found a MR for the HTTPS, but not for the SSH.

### Reproduction steps

use `git_remote_connect` to connect the ssh url which use `gssapi-with-mic` auth.

### Expected behavior

libgit2 could connect the SSH service with GSSAPI, using the `git_credential_default_new`.

### Actual behavior

Connect failed.

### Version of libgit2 (release number or SHA1)

0.99

### Operating system(s) tested

macOS 10.15.3

**Comment by ethomson** [comment]
Indeed, this would be a nice feature to have.  I'm not sure if libssh2 supports Kerberos.

**Comment by Whirlwind** [comment]
> Indeed, this would be a nice feature to have. I'm not sure if libssh2 supports Kerberos.

It seems that NO....

I am not sure.

**Comment by ethomson** [comment]
Closing this - this is up to libssh2 or OpenSSH (which we now support). If we need to do something (like a new credtype) to make something work then let’s open a new issue
