### ISSUE TITLE
checkout: investigate CHECKOUT_ACTION__DEFER_REMOVE

### ISSUE THREAD

**Issue by ethomson** [libgit2/libgit2#5486]
It looks like we can pull some dead code out of `checkout`.  Beginning in 7e5c8a5b41ca660def7de23fd32b942878a6ee24, we stopped doing anything in the "deferred removal" case.  In 5cf9875a4f6ee6fa26f5617aca8433dd49c72751, we `assert` if we ever enter that function.  Obviously the function can be removed.

I suspect that means that we should remove the entire notion of "deferred removal".  I don't remember offhand all the details, though, so I'm logging an issue here for me to investigate a bit further.

**Comment by pks-t** [comment]
Closing via 46637b5e24afc7a859caa0302bd23616053e40f4
