### ISSUE TITLE
git_reference_foreach does not honor per worktree refs

### ISSUE THREAD

**Issue by csware** [libgit2/libgit2#5492]
### Reproduction steps

1. Clone a repository and create a separate worktree for it (using `git worktree`).
2. Start bisect on the worktree
3. Retireve all refs for the worktree using `git_reference_foreach`

### Expected behavior

`git_reference_foreach` returns the `bisec/good` and `bisec/bad` refs.

### Actual behavior

`git_reference_foreach` does not return the `bisec/good` and `bisec/bad` refs.
Those refs are only returned in the main repo when bisecting is started there.

The refs `bisect/good` and `bisec/bad` are stored in `.git/worktree/NAME/refs/bisect/...`.

### Version of libgit2 (release number or SHA1)

918a7d19553a9a4181bf1561b8b828a5f82e60e0, still in 1.5.0

### Operating system(s) tested

Win10 1909, x64

**Comment by csware** [comment]
cf. https://github.com/gitster/git/blob/efe3874640e2e58209ddbb3b072f48f6b7094f34/refs.c#L721 and https://github.com/gitster/git/blob/efe3874640e2e58209ddbb3b072f48f6b7094f34/refs/files-backend.c#L218

**Comment by csware** [comment]
@pks-t @ethomson Could you please have a look at this?

**Comment by csware** [comment]
@pks-t @ethomson Any news on this?

**Comment by JohnAZoidberg** [comment]
Seems to continue being an issue: https://gitlab.com/tortoisegit/tortoisegit/-/issues/3897

**Comment by ethomson** [comment]
Fixed via #6387 - thanks again!
