### ISSUE TITLE
git_transport_certificate_check_cb not working as expected

### ISSUE THREAD

**Issue by HappyCerberus** [libgit2/libgit2#5496]
### Reproduction steps
```
fetch_opts.callbacks.certificate_check = libgit2_decide_on_failing_cert_check;

// ... snip ...

int libgit2_decide_on_failing_cert_check(git_cert*, int valid, const char*, void*) {
  if (!FLAGS_git_disable_cert_checks) {
    // Follow the validity of the certificate as normal.
    return valid;
  }
  // Always allow certificate.
  return 0;
}
```

### Expected behavior

If returning `valid`, no change to validity of certificates should be done. 

### Actual behavior

Invalid certificates are treated as valid no matter whether returning `valid` or 0.

### Version of libgit2 (release number or SHA1)

1.0.0

### Operating system(s) tested

Linux

**Comment by ethomson** [comment]
Per [the documentation](https://github.com/libgit2/libgit2/blob/aa4cd778b97d7271aa0ad12a4f9d492c443d5935/include/git2/sys/transport.h#L250-L253), you should return

> 0 for no error, `GIT_PASSTHROUGH` to indicate that there is no callback registered (or the callback refused to validate the certificate and callers should behave as if no callback was set), or < 0 for an error

If you want to explicitly reject a certificate, regardless of what the TLS system says about validity, you'll need to error out (returning `< 0` and ideally calling `git_error_set_str` before you do).

If you want to just defer to the TLS system's notion of validity, return `GIT_PASSTHROUGH`.

If you want to continue _always_, return 0.

Returns of `> 1` are not defined.

**Comment by HappyCerberus** [comment]
Ah OK. Could you update the documentation on `callbacks.certififcate_check` and `git_transport_certificate_check_cb`?

Because neither of those mention this and I don't see how I would manage to get to `git_transport_smart_certificate_check`.

**Comment by StefanKarpinski** [comment]
This is still incorrectly documented:

https://libgit2.org/libgit2/#HEAD/group/callback/git_transport_certificate_check_cb
