### ISSUE TITLE
Standalone Libgit2 build for distribution

### ISSUE THREAD

**Issue by twaritwaikar** [libgit2/libgit2#5499]
First of all thank you maintaining this awesome project. 

I am one of the maintainers at godotengine/godot-git-plugin. Our plugin uses Libgit2 to let the Godot engine editor do git operations from the editor. 

The common issues I used to get were issues with our static Libgit2 build not including libraries like Zlib, OpenSSL, Winhttp in it and instead it was depending on the user system to provide them. This has been hard to track sometimes due to varying system configurations amongst all the users.

As of now we have been able to correct most of these issues by including libraries in our static Libgit2 build on a case by case basis.

However I would like to know how can I build Libgit2 to be completely system dependencies independent. I see a lot of CMake options to turn off features/dependencies in the CMake recipe but going at it by guessing it probably not the best thing to do.

**Comment by scottfurry** [comment]
Judging by you mention of _Winhttp_, I'm going to take a wild stab in the dark and say you're on a Windows-based OS. I can't speak to win-systems explicitly but I can throw out a few ideas/suggestions.

Nice part about CMake (and something that isn't circulated very widely) is its ability to generate out-of-source builds. Telling CMake to put all generated build files into a folder __NOT__ in the source tree is ideal, IMO. Make a mistake? RM the build folder and start again. A hint about is given in [The Hitchhicker's Guide to the CMake](https://cgold.readthedocs.io/en/latest/index.html). The secret sauce is...
```
# assuming windows
DIR [path\to\sources]
cmake -H. -Bbuildfolder ...[other CMake flags here]...
make -C buildfolder
```
See the index of link above for '-H' and '-B' switches.

As for missing dependencies, the easiest management strategy I found was to consolidate all the libraries into a folder name without spaces(assuming a mingw type system). The path can be added to build flags for include folders ('-I') and library folders ('-L').

Once you got "something" working. Copy the build instructions to a 'spec' file you can call to re-generate the build. An example from my experiments (note - this is a bash script):
```
#!/bin/bash
PRJFLDR="libgit2-src"
HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
UPHOME=$(dirname "$HOME")
BLD_NAME="build"
BLD_FLDER="${UPHOME}/${PRJFLDR}/${BLD_NAME}"
CURRDT=$(date +%Y%m%d_%H%M)
LOGFILE="CPPCHK_${CURRDT}_BUILD.log"
echo "${HOME} ${UPHOME}"

if [[ -d "${BLD_FLDER}" ]]
then
    echo "Removing ${BLD_FLDER}"
    rm -fR "${BLD_FLDER}"
fi

cd "${UPHOME}/${PRJFLDR}"
cmake -H. -B"${BLD_NAME}" \
    -DCMAKE_C_STANDARD=11 \
    -DCMAKE_CXX_STANDARD=11 \
    -DCMAKE_BUILD_TYPE="Debug" \
    -DBUILD_EXAMPLES=ON >"${HOME}/${LOGFILE}" 2>&1

make -C"${BLD_NAME}" all >>"${HOME}/${LOGFILE}" 2>&1
```

Apologies if these instructions seem minor or inconsequential. I'm taking big guess about the build system you are using.

**Comment by ethomson** [comment]
This seems quite stale and I’m hoping that the suggestions helped. If not, let me know and we can dig in and improve the situation.
