### ISSUE TITLE
CMake Error "could not resolve ws2_32" MinGW build

### ISSUE THREAD

**Issue by A-Ovchinnikov-mx** [libgit2/libgit2#5502]
### Reproduction steps

Compile libgit2 with MinGW-w64 toolchain.

The toolchain+cmake are installed with `pacboy sync toolchain:x cmake:x`. Also the same behavior if I repeat the steps from PKGBUILD in MinGW-w64 repository: https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-libgit2/PKGBUILD

My MinGW installation is based on MSYS2 + Git for Windows SDK.

### Expected behavior

Configuring completes successfully.

### Actual behavior

CMake Error: could not resolve ws2_32:

```
MINGW64 /c/libgit_build
$ tar --exclude tests/resources/testrepo-worktree/link_to_new.txt -xzf libgit2-1.0.0.tar.gz

MINGW64 /c/libgit_build
$ cd libgit2-1.0.0/

MINGW64 /c/libgit_build/libgit2-1.0.0
$ mkdir build && cd build

MINGW64 /c/libgit_build/libgit2-1.0.0/build
$ cmake -G"MinGW Makefiles" ..
-- The C compiler identification is GNU 9.3.0
-- Check for working C compiler: C:/msys64/mingw64/bin/gcc.exe
-- Check for working C compiler: C:/msys64/mingw64/bin/gcc.exe - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found PkgConfig: C:/msys64/mingw64/bin/pkg-config.exe (found version "0.29.2")
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Performing Test HAVE_STRUCT_STAT_ST_MTIM
-- Performing Test HAVE_STRUCT_STAT_ST_MTIM - Failed
-- Performing Test HAVE_STRUCT_STAT_ST_MTIMESPEC
-- Performing Test HAVE_STRUCT_STAT_ST_MTIMESPEC - Failed
-- Performing Test HAVE_STRUCT_STAT_MTIME_NSEC
-- Performing Test HAVE_STRUCT_STAT_MTIME_NSEC - Failed
-- Performing Test IS_WALL_SUPPORTED
-- Performing Test IS_WALL_SUPPORTED - Success
-- Performing Test IS_WEXTRA_SUPPORTED
-- Performing Test IS_WEXTRA_SUPPORTED - Success
-- Performing Test IS_WDOCUMENTATION_SUPPORTED
-- Performing Test IS_WDOCUMENTATION_SUPPORTED - Failed
-- Performing Test IS_WNO_MISSING_FIELD_INITIALIZERS_SUPPORTED
-- Performing Test IS_WNO_MISSING_FIELD_INITIALIZERS_SUPPORTED - Success
-- Performing Test IS_WSTRICT_ALIASING_SUPPORTED
-- Performing Test IS_WSTRICT_ALIASING_SUPPORTED - Success
-- Performing Test IS_WSTRICT_PROTOTYPES_SUPPORTED
-- Performing Test IS_WSTRICT_PROTOTYPES_SUPPORTED - Success
-- Performing Test IS_WDECLARATION_AFTER_STATEMENT_SUPPORTED
-- Performing Test IS_WDECLARATION_AFTER_STATEMENT_SUPPORTED - Success
-- Performing Test IS_WSHIFT_COUNT_OVERFLOW_SUPPORTED
-- Performing Test IS_WSHIFT_COUNT_OVERFLOW_SUPPORTED - Success
-- Performing Test IS_WUNUSED_CONST_VARIABLE_SUPPORTED
-- Performing Test IS_WUNUSED_CONST_VARIABLE_SUPPORTED - Success
-- Performing Test IS_WUNUSED_FUNCTION_SUPPORTED
-- Performing Test IS_WUNUSED_FUNCTION_SUPPORTED - Success
-- Performing Test IS_WINT_CONVERSION_SUPPORTED
-- Performing Test IS_WINT_CONVERSION_SUPPORTED - Success
-- Performing Test IS_WNO_FORMAT_SUPPORTED
-- Performing Test IS_WNO_FORMAT_SUPPORTED - Success
-- Performing Test IS_WNO_FORMAT_SECURITY_SUPPORTED
-- Performing Test IS_WNO_FORMAT_SECURITY_SUPPORTED - Success
-- Looking for futimens
-- Looking for futimens - not found
-- Checking prototype qsort_r for HAVE_QSORT_R_BSD - False
-- Checking prototype qsort_r for HAVE_QSORT_R_GNU - False
-- Looking for qsort_s
-- Looking for qsort_s - found
-- Looking for clock_gettime in rt
-- Looking for clock_gettime in rt - not found
-- Found OpenSSL: C:/msys64/mingw64/lib/libcrypto.dll.a (found version "1.1.1g")
-- Could NOT find PCRE (missing: PCRE_LIBRARY PCRE_POSIX_LIBRARY PCRE_INCLUDE_DIR)
-- Looking for regcomp_l
-- Looking for regcomp_l - not found
-- Looking for dirent.h
-- Looking for dirent.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for inttypes.h
-- Looking for inttypes.h - found
-- Looking for sys/stat.h
-- Looking for sys/stat.h - found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Looking for windows.h
-- Looking for windows.h - found
-- Looking for bcopy
-- Looking for bcopy - not found
-- Looking for memmove
-- Looking for memmove - found
-- Looking for strerror
-- Looking for strerror - found
-- Looking for strtoll
-- Looking for strtoll - found
-- Looking for strtoq
-- Looking for strtoq - not found
-- Looking for _strtoi64
-- Looking for _strtoi64 - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of long long
-- Check size of long long - done
-- Check size of unsigned long long
-- Check size of unsigned long long - done
-- Performing Test IS_WNO_UNUSED_FUNCTION_SUPPORTED
-- Performing Test IS_WNO_UNUSED_FUNCTION_SUPPORTED - Success
-- Performing Test IS_WNO_IMPLICIT_FALLTHROUGH_SUPPORTED
-- Performing Test IS_WNO_IMPLICIT_FALLTHROUGH_SUPPORTED - Success
-- http-parser version 2 was not found or disabled; using bundled 3rd-party sources.
-- Performing Test IS_WIMPLICIT_FALLTHROUGH_1_SUPPORTED
-- Performing Test IS_WIMPLICIT_FALLTHROUGH_1_SUPPORTED - Success
-- Found ZLIB: C:/msys64/mingw64/lib/libz.dll.a (found version "1.2.11")
-- Checking for module 'libssh2'
--   Found libssh2, version 1.9.0
CMake Error at cmake/Modules/FindPkgLibraries.cmake:17 (MESSAGE):
  could not resolve ws2_32
Call Stack (most recent call first):
  src/CMakeLists.txt:204 (FIND_PKGLIBRARIES)


-- Configuring incomplete, errors occurred!
See also "C:/libgit_build/libgit2-1.0.0/build/CMakeFiles/CMakeOutput.log".
See also "C:/libgit_build/libgit2-1.0.0/build/CMakeFiles/CMakeError.log".

MINGW64 /c/libgit_build/libgit2-1.0.0/build
$ which cmake
/mingw64/bin/cmake

MINGW64 /c/libgit_build/libgit2-1.0.0/build
$ cmake --version
cmake version 3.17.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).

```

### Version of libgit2 (release number or SHA1)

v1.0

### Operating system(s) tested

Windows 10 x64 build 18363.720

### CMake log files

[CMakeError.log](https://github.com/libgit2/libgit2/files/4554574/CMakeError.log)
[CMakeOutput.log](https://github.com/libgit2/libgit2/files/4554575/CMakeOutput.log)

**Comment by A-Ovchinnikov-mx** [comment]
The toolchain+cmake are installed with `pacboy sync toolchain:x cmake:x`. Also the same behavior if I repeat the steps from PKGBUILD in MinGW-w64 repository: https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-libgit2/PKGBUILD

**Comment by ethomson** [comment]
I'm sorry to hear that.  We run CI with mingw-w64, version 8.1.0, for both both x86_64 and i686.  So more details about what's different about your environment would be helpful.

**Comment by A-Ovchinnikov-mx** [comment]
@ethomson Thanks for the response! Here's the output of `gcc -v` in my environment:

```
$ which gcc
/mingw64/bin/gcc

$ gcc -v
Using built-in specs.
COLLECT_GCC=C:\msys64\mingw64\bin\gcc.exe
COLLECT_LTO_WRAPPER=C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.3.0/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../gcc-9.3.0/configure --prefix=/mingw64 --with-local-prefix=/mingw64/local --build=x86_64-w64-mingw32 
--host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --with-native-system-header-dir=/mingw64/x86_64-w64-mingw32/include --libexecdir=/mingw64/lib --enable-bootstrap --with-arch=x86-64 --with-tune=generic --enable-languages=c,lto,c++,fortran,ada,objc,obj-c++ --enable-shared --enable-static --enable-libatomic --enable-threads=posix --enable-graphite --enable-fully-dynamic-string --enable-libstdcxx-filesystem-ts=yes --enable-libstdcxx-time=yes --disable-libstdcxx-pch --disable-libstdcxx-debug --disable-isl-version-check --enable-lto --enable-libgomp --disable-multilib --enable-checking=release 
--disable-rpath --disable-win32-registry --disable-nls --disable-werror --disable-symvers --enable-plugin --with-libiconv --with-system-zlib --with-gmp=/mingw64 --with-mpfr=/mingw64 --with-mpc=/mingw64 --with-isl=/mingw64 --with-pkgversion='Rev2, Built by MSYS2 project' --with-bugurl=https://sourceforge.net/projects/msys2 --with-gnu-as --with-gnu-ld
Thread model: posix
gcc version 9.3.0 (Rev2, Built by MSYS2 project)
```

Also, as mentioned, the installation is essentially MSYS2 (https://www.msys2.org/) + Git for Windows SDK as described here: https://github.com/git-for-windows/git/wiki/Install-inside-MSYS2-proper

The packages are updated regularly, so I have the last released versions at the moment.

Please let me know what else information about my environment would be helpful!

**Comment by PierreTechoueyres** [comment]
Today I was able to finish the compilation by editing the file /mingw64/lib/pkgconfig/libssh2.pc to suppress all references to -lw2_32

I know this is a really ugly dirty hack but at this time I haven't found any other way.

**Comment by guillep** [comment]
I'm having the same problem in here. Trying to build on windows in travis:

https://travis-ci.com/github/guillep/libgit_build/jobs/328901184

I've inspired myself a bit from the [configuration files for builds in azure](https://github.com/libgit2/libgit2/tree/master/azure-pipelines).

But the main difference is that the azure builds of libgit2 are not using SSH, so @ethomson maybe that's why they are all green? See for example in:

https://dev.azure.com/libgit2/libgit2/_build/results?buildId=3604&view=logs&j=0e75e4c9-c5ab-5c8b-aae3-1786af1ce3d7&t=81b3ffc1-c49f-592b-f29d-8099cc1f3a16&l=148

```
-- Disabled features:
 * debugpool, debug pool allocator
 * SSH, SSH transport support
```

I got the build working correctly without SSH, but as soon as I tried to add SSH I got bit :)
I'll try to get my hands on a windows machine to check it in detail...

**Comment by guillep** [comment]
> Today I was able to finish the compilation by editing the file /mingw64/lib/pkgconfig/libssh2.pc to suppress all references to -lw2_32

It seems libssh2 depends on this msys package: https://packages.msys2.org/package/msys2-w32api-runtime?repo=msys&variant=x86_64

Installing that package (`msys2-w32api-runtime`) from msys makes compilation pass. However, I don't want to depend on an msys package... I'll probably fallback to a visual studio compilation...

**Comment by A-Ovchinnikov-mx** [comment]
@guillep Thanks for pointing me in the right direction! 😄

I've checked the MinGW packages, and it appears that the package [mingw-w64-x86_64-crt-git](https://packages.msys2.org/package/mingw-w64-x86_64-crt-git) installs all the libraries into a specific directory within MSYS2 filesystem:

```
...
/mingw64/x86_64-w64-mingw32/lib/libws2_32.a
...
```

So simply adding the following parameter to CMake command line solves the problem:

`-DCMAKE_LIBRARY_PATH=/mingw64/x86_64-w64-mingw32/lib/`

Hope this helps! /cc @PierreTechoueyres 

P.S. @ethomson Maybe it's worth including in the build instructions? 🙂

**Comment by guillep** [comment]
Hi all,

I just tested the compiled dll I had in Windows, and I wanted to confirm that the `msys2-w32api-runtime` is just a library with stubs. So the DLL generated MinGW seems to have the correct dependencies and seems what I was looking for.

![image](https://user-images.githubusercontent.com/708322/81574189-ca3b6b00-93a5-11ea-9fd9-d0974f40c177.png)

I'll test it further and come back here to see if ssh support is actually working (I'm on my windows box now).

This would boil down to adding to the build instructions that libssh2 support in windows requires the installation of that package in a mingw/msys environment. Would a pull request adding that to the readme be acceptable? Or it should go in some kind of wiki? or... ?

**Comment by A-Ovchinnikov-mx** [comment]
@guillep I would say - since it is building for MinGW it would be better to use the correct libraries. CMake cannot find the libraries in `/mingw64/x86_64-w64-mingw32/lib/` directory, so it's pretty straightforward to point it to that folder. I would vote against referencing MSYS package just because it puts the libraries in `/usr/lib` which is in the lib search path.

**Comment by ethomson** [comment]
> This would boil down to adding to the build instructions that libssh2 support in windows requires the installation of that package in a mingw/msys environment. Would a pull request adding that to the readme be acceptable? Or it should go in some kind of wiki? or... ?

Improving the instructions for how to get this working with libssh2 in mingw would be welcome, indeed.  Thanks for chasing this!

**Comment by A-Ovchinnikov-mx** [comment]
Unfortunately it feels that my comments in this thread are largely ignored, but nonetheless I've opened a pull request which contains both proposals for solving the issue:

https://github.com/libgit2/libgit2/pull/5512

Please have a look when you have time. Thanks.

**Comment by guillep** [comment]
Hi @A-Ovchinnikov-mx, I'm not (and I plan not to be) an msys/mingw expert :)
In my travis setup I use MSYS, as it is the setup they propose (and document) and use MSYS to install mingw packages...

I'll check how the compilation goes with the solution you proposed too.

**Comment by A-Ovchinnikov-mx** [comment]
@guillep I'm not an expert either 😄 But from my understanding, MSYS2 is a derivative of Cygwin, which means that this is basically "Wine inside-out" - an emulation layer that translates Unix API calls into Windows API calls. Because of this, software built for MSYS usually depends on this emulation layer which is msys-2.0.dll library.

On the other hand, MinGW refers to "Minimalist GNU on Windows" and is basically a set of Unix-like tools to build native Windows software. So software built for MinGW is the native Windows software that doesn't depend on msys-2.0.dll or any other emulation layer.

The problem with mixing two worlds is - again, from my understanding - that you might end up referencing software that's built on top of this emulation layer from native Windows software. Yet again, I'm not an expert, but I guess this might lead to some spectacular ways to break things :) I'm not even sure the ABI is 100% compatible between MSYS and MinGW.
