### ISSUE TITLE
Custom filter is applied to all files on Windows when calling git_index_add_all

### ISSUE THREAD

**Issue by J0Nes90** [libgit2/libgit2#5504]
Hi,
I do have a custom filter that is called correctly on filtered files on macOS but gets wrongly called on all files on windows.

### Reproduction steps
Create a custom filter like so:
`_filter = (git_filter*) calloc(1, sizeof(git_filter));`
`_filter->version = GIT_FILTER_VERSION;`
`_filter->attributes = "filter=lfs";`
`_filter->shutdown = GitFilter::freeFilter;`
`_filter->apply = lfsFilterApply;`
`_filter->check = lfsFilterCheck;`

Register the filter:
`git_filter_register("lfs", _filter, GIT_FILTER_DRIVER_PRIORITY);`

Provide a .gitattributes that looks like this, for example:
`*.tif filter=lfs diff=lfs merge=lfs -text `

Add files to the index
`git_index_add_all`

Observe that `lfsFilterCheck` is called for all files with `NULL ` attr_values on Windows.

### Expected behavior
lfsFilterCheck is called with attr_values "lfs" for files filtered in .gitattributes on both windows and macOS

### Actual behavior
lfsFilterCheck is called correctly on macOS whereas attr_values is `NULL` on Windows, hence the filter gets applied to all files that were added by git_index_all

### Version of libgit2 (release number or SHA1)
bd6b1c4

### Operating system(s) tested
macOS 10.14.6
Windows 10

**Comment by J0Nes90** [comment]
I am very sorry, the issue is on my side overwriting memory. Closing the issue

**Comment by ethomson** [comment]
Thanks for the update @J0Nes90!
