### ISSUE TITLE
validating a branch name?

### ISSUE THREAD

**Issue by bradwood** [libgit2/libgit2#5506]
Hi,

I'm looking for the api equivalent of this cli call
```shell
git check-ref-format --branch <branch_name>
```
I'm aware that I can call `git_reference_is_valid_name()` but this excerpt from `git-check-ref-format(1)` concerns me with this approach:

> With the `--branch` option, the command takes a name and checks if it can be used as a valid branch name (e.g. when creating a new branch). But be cautious when using the previous checkout syntax that may refer to a detached HEAD state. The rule `git check-ref-format --branch $name` implements may be stricter than what `git check-ref-format refs/heads/$name` says (e.g. a dash may appear at the beginning of a ref component, but it is explicitly forbidden at the beginning of a branch name). 

I also found this post downstream on this topic. https://github.com/libgit2/libgit2sharp/issues/267

Any suggestions on this, or plans to implement something? I can knock together a regex if needed, but somehow it feels as this functionality should be in the ref or branch API.

**Comment by ethomson** [comment]
Interesting question.  I think that if branch naming validity is not decidable using `git_reference_is_valid_name` then we should offer `git_branch_is_valid_name` and `git_tag_is_valid_name` as well.

**Comment by bradwood** [comment]
It is definitely different. The libgit2 implementation seems to be the same as that in the cli, but sans the `--branch` switch.

So, a valid ref name to `git_reference_is_valid_name` would be something like `refs/heads/-badbranch` even though `-badbranch` is not a valid branch name.

Also, it requires at least one `/` which a branch name clearly doesn't.

**Comment by bradwood** [comment]
@ethomson - any movement on this one? Cheers

**Comment by ethomson** [comment]
Sorry @bradwood, I'm afraid not.  A pull request would definitely be welcome if this was something that you wanted to implement yourself.  🙂

**Comment by bradwood** [comment]
I would, but my c sucks! I'm actually waiting for the downstream rust
wrapper... I will work around it. Thanks.

**Comment by csware** [comment]
Here a link which additional checks TortoiseGit performs: https://github.com/TortoiseGit/TortoiseGit/blob/5170b17c9c12f0e956a1cf123a56ed11f7437312/src/Git/Git.cpp#L246

**Comment by ethomson** [comment]
We have these functions now! Thanks @csware
