### ISSUE TITLE
Flaky testcase checkout::index::can_disable_pathspec_match

### ISSUE THREAD

**Issue by pks-t** [libgit2/libgit2#5514]
Starting with #5378, the newly introduced testcase checkout::index::can_disable_pathspec_match is flaky on my machine:

```bash
 ~/Development/libgit2/build:master $ ./libgit2_clar -scheckout::index::can_disable_pathspec_match
Loaded 386 suites:
Started (test status codes: OK='.' FAILURE='F' SKIPPED='S')
.

 ~/Development/libgit2/build:master $ ./libgit2_clar -scheckout::index::can_disable_pathspec_match
Loaded 386 suites:
Started (test status codes: OK='.' FAILURE='F' SKIPPED='S')
F

  1) Failure:
checkout::index::can_disable_pathspec_match [../tests/checkout/index.c:146]
  testrepo/test10.txt
  file content mismatch at byte 0
```

Bisecting the flaky failure points to commit 24bd12c4f91f841b70bd65252aa25b221bf63eb5, which is rather boring as that commit simply introduced the test to our tree.

Ain't got the time to debug the cause right now, so I thought I'd create an issue for now to document it.

**Comment by ethomson** [comment]
Hmm, thanks for the heads up.  What platform is this that you're seeing the intermittent failures?

**Comment by pks-t** [comment]
I'm seeing this on Gentoo Linux with musl libc, amd64. Judging by your question you probably don't see it, right?

**Comment by pks-t** [comment]
Oh, I bet it's simply racy. We're re-writing the file from contents "original\n" to "modified\n", where both have the same amount of bytes. In case the mtime isn't changed either we'll regard the file as unmodified and thus not switch it back to "original". I'll check if that's the case -- if so, I'll create a pull request that uses differently-sized contents.
