### ISSUE TITLE
Multi-threading issues

### ISSUE THREAD

**Issue by HappyCerberus** [libgit2/libgit2#5520]
The way I understand the documentation is that as long as I never access a libgit2 object from multiple threads (or ensure proper locking when that happens), there should not be any multi-threading issues with libgit2. But I seem to be running into a lot of problems with the libgit2 global state.

### Reproduction steps

```
#include <ftw.h>
#include <memory.h>

#include <string>
#include <thread>
#include <vector>

#include "include/git2/clone.h"
#include "include/git2/errors.h"
#include "include/git2/global.h"
#include "include/git2/types.h"

class TempDir {
 public:
  TempDir();
  ~TempDir();
  std::string Path() { return path_; }

 private:
  std::string path_;
};

TempDir::TempDir() {
  char* name = strdup("/tmp/multithread_test_XXXXXX");
  if (mkdtemp(name) != nullptr) {
    path_ = std::string(name);
  }
  free(name);
}

namespace {
/* Call-back to the 'remove()' function called by nftw() */
static int remove_callback(
    const char* pathname,
    __attribute__((unused)) const struct stat* sbuf,
    __attribute__((unused)) int type,
    __attribute__((unused)) struct FTW* ftwb) {
  return remove(pathname);
}
}  // namespace

TempDir::~TempDir() {
  if (path_ == "") return;

  /* Delete the temporary directory */
  if (nftw(path_.c_str(), remove_callback, FOPEN_MAX, FTW_DEPTH | FTW_MOUNT | FTW_PHYS) == -1) {
    perror("tempdir: error: ");
  }
}

void encapsulated_clone() {
  TempDir dir;
  git_clone_options clone_options = GIT_CLONE_OPTIONS_INIT;
  git_repository* repo = nullptr;
  git_clone(&repo, "https://github.com/HappyCerberus/libgit2_problems", dir.Path().c_str(), &clone_options);
  git_repository_free(repo);
}

int main() {
  git_libgit2_init();
  std::vector<std::thread> threads;
  for (int i = 0; i < 20; i++) {
    threads.emplace_back(encapsulated_clone);
  }
  for (int i = 0; i < 20; i++) {
    threads[i].join();
  }
  git_libgit2_shutdown();
}
```

### Expected behavior

No multi-threading issues.

### Actual behavior

A lot of multi-threading issues reported by TSAN:
https://gist.github.com/0a2326ad478c75e666291f9d12141540

### Version of libgit2 (release number or SHA1)

1.0.0

### Operating system(s) tested

Ubuntu 19.10

**Comment by ethomson** [comment]
Can I ask a clarifying question?  Are you running into _problems_ or are you running into TSAN _complaints_?

A quick glance suggests that you're seeing statics in functions in a potential data race.  However, these are also variables that are initialized precisely once to a particular value.

Is there a race?  Sure.  Two threads could enter `git_pool__system_page_size` at the same time, get past the `if (!size)` test, and then both could calculate and then set `size`.

However, they'll both do it to the same value.  There's no variation here - it's not like `sizeof(void *)` can vary between calls.  So this is just a cached value that will always be the same in every thread.  The worst case scenario is that we do the calculation twice, which is a risk I'd take over putting a mutex around this calculation.  Even on a processor with aggressive caching of this value and not having it visible to other threads...  the worst we do is miss the cached value and recalculate the page size.

Anyway, that just serves as an explanation.  I think that TSAN is super useful.  And as a library, we shouldn't spam you with useless output (even if you assume that all that output is harmless, which I concede we shouldn't blindly assume).  Us being noisy in TSAN output harms you from using TSAN in your application.

So, thanks much for the report.  This is a super useful bug report and something that we should act on.  Is there an opportunity to provide a suppression file for things until we tackle this?

**Comment by HappyCerberus** [comment]
It's both running into problems and seeing noisy TSAN :-)

So, the tricky part is that we are currently having issues and I'm trying to narrow them down to the source. The noisy TSAN is not helping, and I wasn't sure whether this actually is a race or not.

Suppression file would be nice, but we use bazel, and I wasn't able to figure out how to integrate a suppression file into `.bazelrc`.

**Comment by vraychev** [comment]
This is a bug. According to this: https://preshing.com/20130618/atomic-vs-non-atomic-operations/, you cannot be sure that when comparing (!size) and reading size, the entire value would have been stored by the other thread.
