### ISSUE TITLE
Files renamed with changed case only are not detected in Windows

### ISSUE THREAD

**Issue by mvorisek** [libgit2/libgit2#5524]
In Windows paths are CI (case insensitive), but when these files are then synchronized to Unix/WSL, there are wrong thus this issue is quite critical.

Steps to reproduce:
- Windows OS
- create/checkout any repo
- change case in any filepath - ex. change `README.md` to `readme.md`
- commit these changes (and create another branch here)

now reset back to the previous commit and verify:
- ~~RENAME/RESET: file is not renamed back to `README.md`~~ (UPDATE: not related to git or GitKraken)
- DETECTION: no changes are detected (the file is named differently vs. the HEAD)

Both operations (~~RENAME/RESET and~~ DETECTION) must be CS.

This issue it critical as a lot of application relies on exact case.

**Comment by ethomson** [comment]
> RENAME/RESET: file is not renamed back to README.md

I'm surprised by this - we should be restoring the correct case of the target when checking out (and the `checkout::icase` tests should be validating this behavior.

Can you provide code and a repo that shows this deficiency?

> DETECTION: no changes are detected (the file is named differently vs. the HEAD)

This is by-design.  On a case-insensitive filesystem, git will - well - _ignore case_.  Given macOS with a tree that has a single file in `HEAD` named `README.md`:

```
% git ls-files --stage
100644 8178c76d627cade75005b40711b92f4177bc6cfc 0	README.md
```

If the file on-disk does not match the case in `HEAD`:

```
% ls
./		../		.git/		readme.md
```

Then git will ignore the difference:

```
% git status
On branch master
nothing to commit, working tree clean
```

This is what you want.  If you didn't have that, you'd constantly have the case flip-flopping due to editors that do things like move a file out of the way and recreate the file with the wrong case.

**Comment by mvorisek** [comment]
> 
> 
> > RENAME/RESET: file is not renamed back to README.md
> 
> I'm surprised by this - we should be restoring the correct case of the target when checking out (and the `checkout::icase` tests should be validating this behavior.
> 
> Can you provide code and a repo that shows this deficiency?
> 

This issue is presented in the latest GitKraken which uses this lib. So open GitKraken, repeat instructs from description and notice the file names (at least not directory names in the repo) are not reset properly.


> > DETECTION: no changes are detected (the file is named differently vs. the HEAD)
> 
> This is by-design. On a case-insensitive filesystem, git will - well - _ignore case_. Given macOS with a tree that has a single file in `HEAD` named `README.md`:
> 
> This is what you want. If you didn't have that, you'd constantly have the case flip-flopping due to editors that do things like move a file out of the way and recreate the file with the wrong case.

You meant by `git` design, is it defined somewhere? Which editor does "flip-flopping"? I do not know any...

**Comment by ethomson** [comment]
> So open GitKraken, repeat instructs from description and notice the file names (at least not directory names in the repo) are not reset properly.

/cc @implausible

**Comment by ethomson** [comment]
> This issue is presented in the latest GitKraken which uses this lib.

Then this bug report should be directed to GitKraken.  You're making assumptions that the bug actually exists in libgit2, which might be true.  Or it might not.  It could be in the node wrapper for libgit2.  Or it could be in their application code itself.  But without reproduction steps _in libgit2_, there's little that we can do to help troubleshoot.

I verified that libgit2's `git_reset` renames the case 

```c
git_reset(repo, (git_object *)prev, GIT_RESET_HARD, NULL);
```

Results in:

```
zoidberg:~/Temp/casechangingrename% ls -Flas
total 4
0 drwxr-xr-x    4 ethomson  staff   128 May 18 11:15 ./
0 drwxr-xr-x  214 ethomson  staff  6848 May 18 10:00 ../
0 drwxr-xr-x   13 ethomson  staff   416 May 18 11:15 .git/
4 -rw-r--r--    1 ethomson  staff    11 May 18 11:15 readme.md
zoidberg:~/Temp/casechangingrename% ../repro/repro
zoidberg:~/Temp/casechangingrename% ls -Flas
total 4
0 drwxr-xr-x    4 ethomson  staff   128 May 18 11:15 ./
0 drwxr-xr-x  214 ethomson  staff  6848 May 18 10:00 ../
0 drwxr-xr-x   13 ethomson  staff   416 May 18 11:15 .git/
4 -rw-r--r--    1 ethomson  staff    11 May 18 11:15 README.md
```

Please report this to your vendor so that we can work with somebody who can aide us in troubleshooting.

**Comment by mvorisek** [comment]
> Then this bug report should be directed to GitKraken.

@ethomson thanks for a quick reply, reported under #ASI280013 to GitKraken Pro support.

> > > DETECTION: no changes are detected (the file is named differently vs. the HEAD)
> > 
> > 
> > This is by-design. On a case-insensitive filesystem, git will - well - _ignore case_. Given macOS with a tree that has a single file in `HEAD` named `README.md`:
> > This is what you want. If you didn't have that, you'd constantly have the case flip-flopping due to editors that do things like move a file out of the way and recreate the file with the wrong case.
> 
> You meant by `git` design, is it defined somewhere? Which editor does "flip-flopping"? I do not know any...

@ethomson can you verify this too solely using this lib?

**Comment by ethomson** [comment]
> @ethomson thanks for a quick reply, reported under #ASI280013 to GitKraken Pro support.

Thanks!

> @ethomson can you verify this too solely using this lib?

Our tests should deal with this case pretty exhaustively, but I'll take a look tonight.

**Comment by implausible** [comment]
Investigated this on Windows using GitKraken. If a commit was made on a CS system where we change the name `README.md` to `readme.md`, and we reset HARD to the previous commit, the file is appropriately reverted back to `README.md` on Windows in GitKraken.

That said, if you do happen to rename `README.md` to `readme.md` on Windows, GitKraken, git core, and libgit2 will not be able to recognize or commit this change. Further, no reset I can perform in git core, GitKraken, or libgit2 (w/o checkout multithreading) will properly reset the file name back to the CS name.

Can you help me @mvorisek by providing detailed steps of the commit making process that you went through to commit a CS name change on Windows?

**Comment by mvorisek** [comment]
> Can you help me @mvorisek by providing detailed steps of the commit making process that you went through to commit a CS name change on Windows?

@implausible 
> You can verify this on: https://github.com/atk4/ui/tree/fix_misc_ns (ie. checkout fix_misc_ns and verify RESET between misc and Misc dir rename between commits 8f30a41/HEAD and 018ab7a)

please let me know if you was able to reproduce it

**Comment by mvorisek** [comment]
> > @ethomson can you verify this too solely using this lib?
> 
> Our tests should deal with this case pretty exhaustively, but I'll take a look tonight.

@ethomson RENAME does work, DETECTION is working as standard `git` on Windows does. Closing and no need to test this more...
