### ISSUE TITLE
mempack: Support packing with threads

### ISSUE THREAD

**Issue by joshtriplett** [libgit2/libgit2#5530]
mempack internally uses a packbuilder to write out a pack, but does not call `git_packbuilder_set_threads`. (By comparison, the local transport calls `git_packbuilder_set_threads` with `0` to enable automatic use of a thread per CPU.)

Please consider automatically using a thread per CPU with the mempack backend.

**Comment by ethomson** [comment]
mempack isn't _experimental_ per se, but it it's also not something that we really use in production.  It doesn't really get a lot of love - would you be willing to submit a PR?

**Comment by joshtriplett** [comment]
I'd be happy to submit a PR.

Also, if there's another way to create objects on disk directly as a packfile, without first making loose objects, I'd be happy to use that instead. (mempack isn't exactly what I'm looking for; ideally I'd like to stream a pack to disk and not require it to fit entirely in memory. I'm working with repositories where a single commit and all the objects it depends on may take up multiple gigabytes.)

**Comment by joshtriplett** [comment]
https://github.com/libgit2/libgit2/pull/5531 uses threads if available, without introducing configurability. Does this seem reasonable, rather than adding a new configuration mechanism?

**Comment by ethomson** [comment]
I think so.  @carlosmn remind me - are you using mempack anywhere?

**Comment by pks-t** [comment]
Closing as it's been implemented via #5531. Thanks for your work, @joshtriplett!
