### ISSUE TITLE
boolean config parsing fails with integers in some cases

### ISSUE THREAD

**Issue by ehuss** [libgit2/libgit2#5555]
In some situations, the config parsing code will fail on boolean values that use integers (0 or 1).

### Reproduction steps

Add to `.gitconfig`:

```
[core]
    logAllRefUpdates = 1
```

Then, perform some operation in a **bare** repo (such as adding a new commit). It will fail with `failed to map '1'`.

### Expected behavior

All boolean config values should support integers.

### Actual behavior

Some boolean config values fail to parse.

### Version of libgit2 (release number or SHA1)

86b85492b1bc8eeb9ff1af25b92877969f17833a

### Operating system(s) tested

macOS

### Notes

The issue is that some functions (like [`git_config_lookup_map_value`](https://github.com/libgit2/libgit2/blob/96a5f38f51bc53895000787542f92d0a3352c026/src/config.c#L1241)) call the low-level [`git__parse_bool`](https://github.com/libgit2/libgit2/blob/96a5f38f51bc53895000787542f92d0a3352c026/src/util.c#L633-L652) which does not support integers.  I think, instead, they should be using [`git_config_parse_bool`](https://github.com/libgit2/libgit2/blob/96a5f38f51bc53895000787542f92d0a3352c026/src/config.c#L1288-L1300) which handles integers.

**Comment by ethomson** [comment]
Fixed via #5626 - thanks @csware!

**Comment by githubnew-pro** [comment]
> در برخی شرایط ، کد تجزیه پیکربندی در مقادیر boolean که از اعداد صحیح (0 یا 1) استفاده می کنند ، خراب می شود.
> 
> ### مراحل تولید مثل
> افزودن به `.gitconfig`:
> 
> ```
> [core]
>     logAllRefUpdates = 1
> ```
> 
> سپس ، عملیاتی را در یک repo **خالی انجام دهید** (مانند افزودن تعهد جدید). با شکست خواهد خورد `failed to map '1'`.
> 
> ### رفتار مورد انتظار
> تمام مقادیر پیکربندی بولی باید از اعداد صحیح پشتیبانی کنند.
> 
> ### رفتار واقعی
> برخی از مقادیر پیکربندی بولی تجزیه نمی شوند.
> 
> ### نسخه libgit2 (شماره انتشار یا SHA1)
> [86b8549](https://github.com/libgit2/libgit2/commit/86b85492b1bc8eeb9ff1af25b92877969f17833a)
> 
> ### سیستم عامل (های) آزمایش شده
> macOS
> 
> ### Notes
> The issue is that some functions (like [`git_config_lookup_map_value`](https://github.com/libgit2/libgit2/blob/96a5f38f51bc53895000787542f92d0a3352c026/src/config.c#L1241)) call the low-level [`git__parse_bool`](https://github.com/libgit2/libgit2/blob/96a5f38f51bc53895000787542f92d0a3352c026/src/util.c#L633-L652) which does not support integers. I think, instead, they should be using [`git_config_parse_bool`](https://github.com/libgit2/libgit2/blob/96a5f38f51bc53895000787542f92d0a3352c026/src/config.c#L1288-L1300) which handles integers.

**Comment by githubnew-pro** [comment]
#5886 #5815
