### ISSUE TITLE
Unable to clone on AWS-EFS (NFS) failed to truncate pack file Permission denied

### ISSUE THREAD

**Issue by Georgegriff** [libgit2/libgit2#5556]
## System information
  - OS/version/architecture: Kubernetes (Docker image on ubi8-minimal as non-root user) writing to shared mount that is AWS-EFS (which i believe uses nfs)

![image](https://user-images.githubusercontent.com/9056958/84484514-c6e01b80-ac92-11ea-83cf-2dfc3c4a17e8.png)

May be related too: 

https://github.com/JuliaLang/Pkg.jl/issues/1247
https://github.com/libgit2/git2go/issues/194

We have confirmed outside of the library in restricted we can:
- Write to shared mount
- Read from shared mount
- Delete from shared mount

More detail:

```bash
[2020-06-12T10:04:44.858] [ERROR] remotes - Error testing remote connection [Error: failed to truncate pack file '/mnt/assets/git/tmp/41091e79-81df-48f2-a5a0-d6a901b1
2e82/objects/pack/pack_git2_wXV3By': Permission denied] {
  errno: -1,                                             
  errorFunction: 'Remote.fetch'
} 

```

```bash
bash-4.4$ ls -la /mnt/assets/git/tmp/5fc54c2b-b118-4e97-a062-300d946a43ce/
total 36
drwxr-sr-x. 6 1000680000 2002 6144 Jun 12 10:06 .
drwxr-sr-x. 3 1000680000 2002 6144 Jun 12 10:06 ..
-rw-r--r--. 1 1000680000 2002   23 Jun 12 10:06 HEAD
-rw-r--r--. 1 1000680000 2002  182 Jun 12 10:06 config
-rw-r--r--. 1 1000680000 2002   73 Jun 12 10:06 description
drwxr-sr-x. 2 1000680000 2002 6144 Jun 12 10:06 hooks
drwxr-sr-x. 2 1000680000 2002 6144 Jun 12 10:06 info
drwxr-sr-x. 4 1000680000 2002 6144 Jun 12 10:06 objects
drwxr-sr-x. 4 1000680000 2002 6144 Jun 12 10:06 refs
bash-4.4$ ls -la /mnt/assets/git/tmp/5fc54c2b-b118-4e97-a062-300d946a43ce/objects/
total 16
drwxr-sr-x. 4 1000680000 2002 6144 Jun 12 10:06 .
drwxr-sr-x. 6 1000680000 2002 6144 Jun 12 10:06 ..
drwxr-sr-x. 2 1000680000 2002 6144 Jun 12 10:06 info
drwxr-sr-x. 2 1000680000 2002 6144 Jun 12 10:06 pack
bash-4.4$ ls -la /mnt/assets/git/tmp/5fc54c2b-b118-4e97-a062-300d946a43ce/objects/pack/
total 224
drwxr-sr-x. 2 1000680000 2002   6144 Jun 12 10:06 .
drwxr-sr-x. 4 1000680000 2002   6144 Jun 12 10:06 ..
-r--r--r--. 1 1000680000 2002 219220 Jun 12 10:06 pack-0eea1f7c2b3bc716ed30f7e38044075e54010a41.idx
bash-4.4$
```

Notice that the last entry has an strange permission

```
-r--r--r--. 1 1000680000 2002 219220 Jun 12 10:06 pack-0eea1f7c2b3bc716ed30f7e38044075e54010a41.idx
```

**Comment by senadjukic** [comment]
Dear all, I am facing this issue too. In my case, I am mounting an EFS volume to a Docker container and using libgit2 v0.27. 

```
docker volume create --driver local --opt type=nfs --opt o=addr=<EFS_URL|IP>,rw,nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,local_lock=none --opt device=:/ efs

docker run -dit -v efs:<path inside container> -p 38080:38080 --name mycontainer <image name> 
```

I get the same error as described above:

`Return code from GIT is (2). failed to truncate pack file "/home/userid/test/.git/objects/pack/pack_git2_TVmllk': Permission denied`

Is there any chance to fix this issue in the short term? 
Do you have any ideas on a workaround?

If you need more information about the setup, just let me know.

Thanks in advance, 
Senad

**Comment by Georgegriff** [comment]
Unfortunately our work around. was to stop using libgit2 entirely and rolled with another solution :( was very painful.  Hopefully someone else will have some answers

**Comment by 0xdky** [comment]
The pack file appears to get created with 0444 mode by default: https://github.com/libgit2/libgit2/blob/master/src/pack.h#L23

How about building libgit2 with the following patch and try:

```
diff --git a/src/pack.h b/src/pack.h
index 17ae72228..03c011346 100644
--- a/src/pack.h
+++ b/src/pack.h
@@ -20,7 +20,7 @@
 #include "oidmap.h"
 #include "zstream.h"
 
-#define GIT_PACK_FILE_MODE 0444
+#define GIT_PACK_FILE_MODE 0644
 
 #define PACK_SIGNATURE 0x5041434b	/* "PACK" */
 #define PACK_VERSION 2
```

**Comment by cfanz** [comment]
Hi, all, I encountered this problem too when using CephFS as backend storage. But, finally, I found this can be solved by set fuse_default_permissions = true which means using fuse's permission check mechanism instead of CephFS. So I think this should be a problem of the filesystem, not libgit.
I abstract the problem as codes below, which can be tested whether the file system is OK for libgit. Complie the code by gcc and run it as a normal user without sudo:
```
#include <errno.h>
#include <string.h>
#include <stdio.h>
#include <unistd.h>
#include <sys/stat.h>
#include <fcntl.h>
int main() {
  int fd = -1;
  int ret = -1;
  char file[11] = "test_XXXXXX";
  fd = mkstemp(file);
  if (fd < 0) {
    printf("open err with: %d\n",fd);
    printf("%s\n", strerror(errno));
  }
  ret = fchmod(fd, 0444);
  if (ret != 0) {
    printf("chmod err with: %d\n",ret);
    printf("%s\n", strerror(errno));
  }
  ret = ftruncate(fd, 2);
  if (ret != 0) {
    printf("truncate err with: %d\n",ret);
  }
  printf("%s\n",strerror(errno));
  return 0;
}
```

**Comment by patrickdevivo** [comment]
I was encountering pretty much this same issue (https://github.com/libgit2/git2go/issues/194#issuecomment-865611331) and the patch @0xdky was able to resolve it (https://github.com/askgitdev/libgit2/commit/7f102fe38a425a28a7c96262a50d7b5fa60569d0)

**Comment by lhchavez** [comment]
_maybe_ we can try doing something along the lines of reimplementing a variant of [`mkstemp(3)`](https://man7.org/linux/man-pages/man3/mkostemp.3.html) that allows the [`open(2)`](https://man7.org/linux/man-pages/man2/open.2.html) call to receive the intended mode from the get-go. that way there is no `chmod`/`fchmod` call at all!

**Comment by lhchavez** [comment]
can someone with NFS give this patch a try?

```diff
diff --git a/src/futils.c b/src/futils.c
index a44820875..0b4817b3f 100644
--- a/src/futils.c
+++ b/src/futils.c
@@ -24,8 +24,11 @@ int git_futils_mkpath2file(const char *file_path, const mode_t mode)

 int git_futils_mktmp(git_buf *path_out, const char *filename, mode_t mode)
 {
-       int fd;
+       int fd, count;
+       char *template;
        mode_t mask;
+       uint64_t random;
+       const char *alphabet = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ01234567890_-";

        p_umask(mask = p_umask(0));

@@ -35,19 +38,35 @@ int git_futils_mktmp(git_buf *path_out, const char *filename, mode_t mode)
        if (git_buf_oom(path_out))
                return -1;

-       if ((fd = p_mkstemp(path_out->ptr)) < 0) {
-               git_error_set(GIT_ERROR_OS,
-                       "failed to create temporary file '%s'", path_out->ptr);
-               return -1;
-       }
+       // This avoids a call to `mkstemp(3)`, because that way there is no need to
+       // call `chmod(2)`, which causes issues under some platforms (e.g. with NFS).
+       template = path_out->ptr + strlen(path_out->ptr) - 6;
+       random = (uint64_t)(git__timer() * 1.0E9);
+       for (count = 0; count < TMP_MAX; count++) {
+               uint64_t template_value = random;
+               int i;

-       if (p_chmod(path_out->ptr, (mode & ~mask))) {
-               git_error_set(GIT_ERROR_OS,
-                       "failed to set permissions on file '%s'", path_out->ptr);
-               return -1;
+               // MMIX PRNG.
+               random = random * 0x5851F42D4C957F2Dull + 0x14057B7EF767814Full;
+
+               for (i = 0; i < 6; i++) {
+                       template[i] = alphabet[template_value & 0x3f];
+                       template_value >>= 6;
+               }
+
+               fd = p_open(path_out->ptr, O_RDWR | O_CREAT | O_EXCL, mode);
+               if (fd < 0) {
+                       if (errno == EEXIST)
+                               continue;
+                       break;
+               }
+
+               return fd;
        }

-       return fd;
+       git_error_set(GIT_ERROR_OS,
+               "failed to create temporary file '%s'", path_out->ptr);
+       return -1;
 }

 int git_futils_creat_withpath(const char *path, const mode_t dirmode, const mode_t mode)
```

**Comment by lhchavez** [comment]
@boretrk pointed out that this commit _might_ fix this issue: https://github.com/libgit2/libgit2/pull/6039

I successfully tried it locally with NFS 4.2, but can somebody with AWS-EFS / CephFS try this out just in case there's something slightly different in those implementations?

**Comment by patrickdevivo** [comment]
I've applied an earlier patch ([see here](https://github.com/askgitdev/libgit2/compare/main...packfile-perm-fix)), it's a bit stale from upstream now but appears to be working for my use on AWS EFS. It's in the backend for https://try.askgit.com/ where every query is executed in a Lambda with an EFS mount.

I can give the patch from @lhchavez a try and report back

**Comment by ethomson** [comment]
> It's in the backend for https://try.askgit.com/ where every query is executed in a Lambda with an EFS mount.

Whoa, this is neat.

> I can give the patch from @lhchavez a try and report back

It would be great to be sure that this works before we merge.  😁

**Comment by patrickdevivo** [comment]
Tried with the patch, but unfortunately am back to receiving the original error: 
![image](https://user-images.githubusercontent.com/57259/132584885-d245c5fe-ae2f-4d6b-b962-8c7545c0ff92.png)

😞

I will also double check on my side to ensure I'm applying the patch correctly

**Comment by lhchavez** [comment]
> Tried with the patch, but unfortunately am back to receiving the original error:
> ![image](https://user-images.githubusercontent.com/57259/132584885-d245c5fe-ae2f-4d6b-b962-8c7545c0ff92.png)
> 
> 
> 
> I will also double check on my side to ensure I'm applying the patch correctly

ah! the new patch is PR #6039.

**Comment by patrickdevivo** [comment]
> > Tried with the patch, but unfortunately am back to receiving the original error:
> > ![image](https://user-images.githubusercontent.com/57259/132584885-d245c5fe-ae2f-4d6b-b962-8c7545c0ff92.png)
> > I will also double check on my side to ensure I'm applying the patch correctly
> 
> ah! the new patch is PR #6039. It fixes something else and avoids calling `ftruncate` altogether out of sheer serendipity!

Ok! Let me give that a shot and report back, thanks!

**Comment by patrickdevivo** [comment]
> > > Tried with the patch, but unfortunately am back to receiving the original error:
> > > ![image](https://user-images.githubusercontent.com/57259/132584885-d245c5fe-ae2f-4d6b-b962-8c7545c0ff92.png)
> > > I will also double check on my side to ensure I'm applying the patch correctly
> > 
> > 
> > ah! the new patch is PR #6039. It fixes something else and avoids calling `ftruncate` altogether out of sheer serendipity!
> 
> Ok! Let me give that a shot and report back, thanks!

@lhchavez seems to be working! It at least clones successfully (and the queries I spot-checked seemed to be working without issue).

**Comment by lhchavez** [comment]
> > > > Tried with the patch, but unfortunately am back to receiving the original error:
> > > > ![image](https://user-images.githubusercontent.com/57259/132584885-d245c5fe-ae2f-4d6b-b962-8c7545c0ff92.png)
> > > > I will also double check on my side to ensure I'm applying the patch correctly
> > > 
> > > 
> > > ah! the new patch is PR #6039. It fixes something else and avoids calling `ftruncate` altogether out of sheer serendipity!
> > 
> > 
> > Ok! Let me give that a shot and report back, thanks!
> 
> @lhchavez seems to be working! It at least clones successfully (and the queries I spot-checked seemed to be working without issue).

thank you very much for checking! :D seems like the permanent fix will be here soon :tada:.
