### ISSUE TITLE
Unexpected behavior in httpclient.check_certificate

### ISSUE THREAD

**Issue by darlaam** [libgit2/libgit2#5558]
```
error = cert_cb(cert, is_valid, url->host, cert_cb_payload);

	if (error == GIT_PASSTHROUGH && !is_valid)
		return git_error_state_restore(&last_error);
	else if (error == GIT_PASSTHROUGH)
		error = 0;
	else if (error && !git_error_last())
		git_error_set(GIT_ERROR_HTTP,
		              "user rejected certificate for %s", url->host);
```
The error analysis conditions overrides the callback return. Even if the callback emits a GIT_PASSTHROUGH knowing that the certificate is not valid, the certificate will be rejected as invalid.

The condition should be something like : 
```
if (!error && !is_valid || error != GIT_PASSTHROUGH && git_error_last())
		return git_error_state_restore(&last_error);
	else if (error == GIT_PASSTHROUGH)
		error = 0;
	else if (error && !git_error_last())
		git_error_set(GIT_ERROR_HTTP,
		              "user rejected certificate for %s", url->host);

```

**Comment by ethomson** [comment]
> The error analysis conditions overrides the callback return. Even if the callback emits a GIT_PASSTHROUGH knowing that the certificate is not valid, the certificate will be rejected as invalid.

Maybe I'm not clear on what you're saying, but yes - if the callback emits a `GIT_PASSTHROUGH` and the certificate was not valid, then the certificate should be rejected.

`GIT_PASSTHROUGH` is a mechanism for callbacks to decide to do nothing at all.  It's as if they did not exist.  And if there is no callback configured and a certificate is invalid, then it will be treated as invalid.

If you want your certificate callback to accept an invalid certificate, then you need to do so explicitly.

**Comment by darlaam** [comment]
Ok seems I got in a muddle with the doc, and didn't clearly understood the role of GIT_PASSTHROUSH.
in transport.h :
```
 * @return the return value of the callback: 0 for no error, GIT_PASSTHROUGH
 *         to indicate that there is no callback registered (or the callback
 *         refused to validate the certificate and callers should behave as
 *         if no callback was set), or < 0 for an error
```
Sorry for the trouble....
