### ISSUE TITLE
Setting `HTTP_PROXY` env var in Ruby no longer picked up in 0.28+

### ISSUE THREAD

**Issue by Magisus** [libgit2/libgit2#5560]
In r10k, we rely on environment variables to configure proxies for rugged/libgit2 to use, like this https://github.com/puppetlabs/r10k/blob/master/lib/r10k/git.rb#L175-L194. When upgraded to 0.28+ (most recently I tried libgit2 0.28.5 and 1.0.1), rugged stopped respecting the proxy configuration. We noticed this in tests that configure a non-existent proxy and then expect an error. The tests stopped erroring and proceeded to talk to the final server and successfully complete the request, and therefore failed.

I'm curious if there's some issue with this usage that we need to adjust for to use the newer versions of libgit2, or if this is a bug.

### Reproduction steps
Configure a non-existent proxy for r10k, either via `HTTP_PROXY` env var or via the r10k config. Deploy an environment, and see the deploy succeed, even though hitting the non-existent proxy should fail.

### Expected behavior
The proxy as specified in environment variables should be respected.

### Actual behavior
The proxy configuration is ignored, and the actual destination URL is used instead.

### Version of libgit2 (release number or SHA1)
0.28.0, still present in 1.0.1

### Operating system(s) tested
RHEL 6, 7 and 8, Ubuntu 16.04 and 18.04, SLES 12,

**Comment by Magisus** [comment]
I can provide more detailed repro instructions if needed, but since setting up r10k is fairly complicated, I was sort of just hoping for confirmation on whether what we're trying to do with proxies -- based on the code linked above -- is expected to be supported or known to be bugged at the moment.

**Comment by ethomson** [comment]
I can’t speak to rugged, but it’s possible that you were using a version of libgit2 that used libcurl before, and _it_ honored that environment variable even if you didn’t ask libgit2 to.  We now never use libcurl, so you’ll need to make sure that you specify that you want us to look at the environment.

Eg:
`fetch_opts.proxy_opts.type = GIT_PROXY_AUTO;`

(How you do this in rugged I do not know.)

**Comment by Magisus** [comment]
That's helpful, I'll look into that!

**Comment by Magisus** [comment]
I think we might need https://github.com/libgit2/rugged/pull/808 or something similar for it to work with rugged. We could probably use that to translate a user's env vars into a direct value passed to to libgit instead, which is fine.

**Comment by ethomson** [comment]
Since the rugged change landed, I’m going to close this.
