### ISSUE TITLE
Incorrect Use of HTTP Upgrade Header

### ISSUE THREAD

**Issue by jriddell** [libgit2/libgit2#5573]
libgit incorrectly fails if the server it is talking to sends an HTTP upgrade header.

Code causing failure is here
https://github.com/libgit2/libgit2/blame/96a5f38f51bc53895000787542f92d0a3352c026/src/transports/httpclient.c#L1124

This is a misunderstanding of the upgrade header which is a suggestion to upgrade from http/1.1 to http/2 not a requirement.

RFC7230 section 6.7, an Upgrade header in a normal response merely informs the client that the server supports upgrading to other protocols, and the client can ask for such an upgrade in a later request. The server requiring an upgrade is via the 426 Upgrade Required response code, not the mere presence of the Upgrade response header.

**Comment by csware** [comment]
This issue can be closed.

**Comment by ethomson** [comment]
Thanks for the report @jriddell and for the fix @csware
