### ISSUE TITLE
Shared libgit2 linking fails with cached system-provided libraries on macOS 11.0

### ISSUE THREAD

**Issue by milke** [libgit2/libgit2#5575]
I don't know if this is strictly related to CMake itself or libgit2 CMake build, so I'll report it here for a start. Also, as I do most of my work in Xcode, I’m totally unexperienced with CMake, apart from creating and tweaking very simple scripts, so I may post some incorrect assumptions here.

As you may already know, macOS 11.0 Big Sur comes with cache of all system-provided libraries. Here is the related paragraph from [release notes](https://developer.apple.com/documentation/macos-release-notes/macos-big-sur-11-beta-release-notes):

> New in macOS Big Sur 11 beta, the system ships with a built-in dynamic linker cache of all system-provided libraries. As part of this change, copies of dynamic libraries are no longer present on the filesystem. Code that attempts to check for dynamic library presence by looking for a file at a path or enumerating a directory will fail. Instead, check for library presence by attempting to dlopen() the path, which will correctly check for the library in the cache.

So, the standard location `/usr/lib` contains only symlinks pointing to targets, which aren't actually present on the file system. This apparently affects building of shared libgit2 library using (building of static library works just fine). As I've said, I'm not experienced with CMake, but  I suspect that, once the required library is found in a form of symlink in `/usr/lib`, at certain moment scripts tend to check for a presence on the file system of an actual target of the symlink in the linking phase, and then it fails.

For example, one such cached system shared library is `libz.dylib` (symlink `/usr/lib/libz.dylib` pointing to `/usr/lib/libz.1.dylib`, but that target is not actually present on the filesystem) . The linking phase fails with error

`[100%] Built target ntlmclient`
`Scanning dependencies of target git2`
`make[2]: *** No rule to make target '/usr/lib/libz.dylib', needed by 'libgit2.1.0.1.dylib'.  Stop.`
`make[1]: *** [src/CMakeFiles/git2.dir/all] Error 2`
`make: *** [all] Error 2`

I compared both *CMakeError.log* and *CMakeOutput.log* files when building on both macOS 10.15 (Catalina) and macOS 11.0 (Big Sur) and, apart from differences in cryptic build target names and clang and OS versions, I haven't noticed any significant difference, apart from this one in *CMakeError.log*, present at the very beginning of a file on macOS 11.0, but not macOS 10.15:

`Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.`
`Compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc`
`Build flags:`
`Id flags:`
`The output was:`
`1`
`ld: library not found for -lSystem`
`clang: error: linker command failed with exit code 1 (use -v to see invocation)`

As I've said, I'm quite ignorant when it comes to CMake, but I'll definitely dig deeper into the issue. Anyway, I just wanted to let you know, perhaps you can guess immediately what the problem is. I have macOS 11.0 installed on ARM based ["Developer Transition Kit"](https://developer.apple.com/programs/universal), so if you need me to do any additional testing or anything else I can help with solving this issue, just let me know.

**Comment by milke** [comment]
Just a shot update… I built the shared library by modifying some CMake generated files between configuration (`cmake ..`) and build (`cmake --build .`) phases.

In file *BUILD_DIR/src/CMakeFiles/git2.dir/build.make* I deleted line:

` libgit2.1.0.1.dylib: /usr/lib/libz.dylib`

just before the command: `@$(CMAKE_COMMAND) -E cmake_echo_color … "Linking C shared library ../libgit2.dylib"`. Without this change, building fails with error:

`make[2]: *** No rule to make target '/usr/lib/libz.dylib', needed by 'libgit2.1.0.1.dylib'.  Stop.`

In a single line file *BUILD_DIR/src/CMakeFiles/git2.dir/link.txt* I modified the very end of the file, by removing reference to `/usr/lib/libz.dylib` from `-framework` section and adding `-lz` after `-liconv` in section `-L/usr/lib`. Without this change, building fails with error:

`[100%] Linking C shared library ../libgit2.dylib`
`clang: error: no such file or directory: '/usr/lib/libz.dylib'`

It seems that found zlib is treated as a macOS framework (a framework bundle in macOS terminology), instead of a regular dynamic library. It appears to work if the actual dynamic library file is present in the file system at claimed path, but with this new system with cached libraries (and framework, but not related to the problem here), it fails.

While investigating this, I've noticed that libssh2 (if found) is treated exactly the same way, whereas libiconv is treated as a regular dynamic library (`-liconv` flag). I wonder why is that? In my case building doesn't fail on libssh2, because I have it custom built in */usr/local/lib* and actually present on the filesystem.

I'm currently happy that I can build the shared library for macOS11/ARM, but I'll probably dedicate some time to try to make CMake generate different build files, treating both libz and libssh2 as regular dynamic libraries. But I'd be happy if you fix it in one of the future releases, you'd probably be able to do it much faster than I can.

**Comment by milke** [comment]
Okay, another short update (as I'm becoming more proficient in CMake 🙂)… It all boils down to package-specific information about found packages. For example, `FIND_PACKAGE(Iconv)` finds ICONV package with properties:

`ICONV_INCLUDE_DIR = '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk/usr/include'`
`ICONV_LIBRARIES = -L/usr/lib -liconv`

On the other hand `FIND_PACKAGE(ZLIB)` finds Zlib package, with the same include property, but completely different type of libraries property:

`ZLIB_INCLUDE_DIRS = '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk/usr/include'`
`ZLIB_LIBRARIES = /usr/lib/libz.dylib`

This value propagates during the build system creation and eventually causes the problem explained in the previous comment. Now, why two packages of exactly the same type (macOS dynamic library *.dylib*) are reported in a such different way is (still) outside of scope of my knowledge :-). But it definitely creates a problem. I guess this will be happening in a lot of projects with different libraries/packages.

For this particular case the solution is quite simple, just change the line 184 of file *src/CMakeLists.txt* from:

`LIST(APPEND LIBGIT2_LIBS ${ZLIB_LIBRARIES})`

to

`LIST(APPEND LIBGIT2_LIBS "-L/usr/lib -lz")`

but that covers only this particular case of system provided zlib, so I assume the problem needs some better general solution.

**Comment by ethomson** [comment]
That's curious.  I just installed Big Sur 11.0 Beta (20A4300b), Xcode 11.5 (11E608c) and cmake 3.18.0-rc4.  I used the usual steps that I use to build and test libgit2 without any problems:

```
mkdir build
cd build
cmake ..
cmake --build .
./libgit2_clar
```

I can confirm that the resulting test binary is linked against the system zlib, not our bundled version:

```
otool -L libgit2_clar
libgit2_clar:
...
        /usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
...
```

(If you're using a release and not a release _candidate_, I didn't intend to download an RC, I just clicked on the first download listed on cmake.org without having realized that it wasn't the latest release.)

**Comment by ethomson** [comment]
The other wrinkle here is that I'm doing this on x86_64, I don't have an ARM transition kit.

Amusingly, Xcode uses libgit2, so ...  somebody has made this work on ARM.  😁

**Comment by milke** [comment]
I'm on Xcode 12 Beta (and underlying tools), as that one is needed to produce binaries for ARM. But it doesn't seem to be the culprit. I was on CMake 3.17, as I was a bit reluctant to use still unofficial version. So I installed CMake 3.18.0-rc4 and tried it again, original libgit2 1.0.1 distribution files, without my custom modification mentioned above. And it worked! So, it definitely seems to be CMake issue and not even libgit2 build scripts.

I've noticed one crucial difference though; during build system creation, the line reporting zlib recognition with CMake 3.17 says:

`-- Found ZLIB: /usr/lib/libz.dylib (found version "1.2.11") `

With CMake 3.18 the same line says"

`-- Found ZLIB: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk/usr/lib/libz.tbd (found version "1.2.11")`

Just to be sure my system is not messed up, I revert back to CMake 3.17 and get the same zlib recognition (`/usr/lib/libz.dylib`) and the known error:

`make[2]: *** No rule to make target `/usr/lib/libz.dylib', needed by `libgit2.1.0.1.dylib'.  Stop.`
`make[1]: *** [src/CMakeFiles/git2.dir/all] Error 2`
`make: *** [all] Error 2`

It's isn't about libgit2 code at all, it's perfect and very portable (huge kudos and thanks to all of you). It's no wonder that Apple already made it work, as I suspect they don't use CMake to build it.

There are some other project exhibiting similar or same issues. For example, both libarchive and libssh2 come with scripts to build libraries with either automake of CMake. And while automake in both projects works fine on ARM/macOS 11/Xcode 12, CMake build fails for both projects with similar errors as those mentioned above.

Anyway, I'll close this, as it surely has nothing to do with libgit2, not even when it comes to build scripts.

**Comment by ethomson** [comment]
Interesting!  Thanks for the additional details.  I'll get Xcode 12 beta (and hopefully we'll get an ARM at work that I can try - I'm sure somebody has one, I just don't know who yet.  😁 )

Please let me know if there's problems on macOS ARM.  I hope that there aren't too many since we work on both macOS amd64 and iOS ARM.  But I'm sure there will be a few problems.
