### ISSUE TITLE
release fix for #5089 (checkout ignores untracked files in subpaths not matching the pathspec)

### ISSUE THREAD

**Issue by extrawurst** [libgit2/libgit2#5587]
see issue #5089
see commit: https://github.com/libgit2/libgit2/commit/d62e44cb8218840a0291fb5fbb7c5106e1e35a12

This was merged in may, but not released in June as of `1.0.1`.
A new point release would be cool anyways :)

**Comment by extrawurst** [comment]
@ethomson Is this going to land in 1.1?

**Comment by ethomson** [comment]
@extrawurst It will.  I added a mention in the changelog specifically.
