### ISSUE TITLE
Support ~/.ssh/id_rsa or ~/.ssh/config

### ISSUE THREAD

**Issue by tbenst** [libgit2/libgit2#5640]
Unless a user is running `ssh-agent`, libgit2 does not find ssh keys, when git does.

There are popular issues with both [Rust's Cargo](https://github.com/rust-lang/cargo/issues/2078), and [Julia's Pkg.jl](https://github.com/JuliaLang/Pkg.jl/issues/911#issuecomment-699243851).

Currently, Cargo solves this issue by [using system git as a replacement for libgit2](https://github.com/rust-lang/cargo/issues/2078#issuecomment-434388584). Julia 1.6 [may also support this](https://github.com/JuliaLang/Pkg.jl/issues/911#issuecomment-699215929).

This has been discussed before, in https://github.com/libgit2/libgit2/issues/4338.

It seems the simplest solution is to revert from libssh2 to libssh: https://github.com/libgit2/libgit2/pull/5253. This is made more urgent by RedHat's deprecation of libssh2 in favor of libssh: https://github.com/libgit2/libgit2/issues/5225. 

I wanted to bring it up again because this feature is critical enough that two of the higher-profile software that depends on `libgit2` have or are exploring alternatives due to this issue.

**Comment by ethomson** [comment]
If you're willing to open a PR with libssh support, of course, then I'd be perfectly happy to include it. Otherwise, I'd prefer to stop using libssh2 or libssh and just call ssh directly as in #5507.

**Comment by tbenst** [comment]
Thanks for the response! I'm not much of a C programmer but wanted to highlight the open PR for adding libssh as a backend: https://github.com/libgit2/libgit2/pull/5253

**Comment by extrawurst** [comment]
with #6133 being merged is this now shelling out to ssh? is this issue fixed by it?

**Comment by ethomson** [comment]
Closing since OpenSSH is now an option
