### ISSUE TITLE
Fix unbalanced custom allocator malloc/free in path.c

### ISSUE THREAD

**Issue by dan-tull** [libgit2/libgit2#5653]
The free here is of a pointer that was malloc'd with git__malloc:
https://github.com/libgit2/libgit2/blob/master/src/path.c#L2048

### Reproduction steps
(code inspection)

Use a custom allocator.
Exercise the git_path_validate_system_file_ownership codepath at the above line with a non-NULL info pointer.

### Expected behavior
All malloc/free are paired.

### Actual behavior
With a custom allocator, the free can result in a crash or other bad behavior (this will be easier to spot with instrumentation like Address Sanitizer).

### Version of libgit2 (release number or SHA1)
1.0.1

### Operating system(s) tested
macOS 10.15.4/Windows 10

Pull request coming shortly. The fix here is quite trivial.

**Comment by ethomson** [comment]
Subtle one!  Good eye, thanks.
