### ISSUE TITLE
Build error on mingw-w64

### ISSUE THREAD

**Issue by jeroen** [libgit2/libgit2#5662]
Trying to upgrade libgit2 from 1.0.0 to 1.1.0 on mingw-w64 (windows) fails with:

```
-- Checking for module 'libssh2'
--   Found libssh2, version 1.8.2
CMake Error at cmake/FindPkgLibraries.cmake:17 (MESSAGE):
  could not resolve crypt32
Call Stack (most recent call first):
  src/CMakeLists.txt:213 (FIND_PKGLIBRARIES)
-- Configuring incomplete, errors occurred!
```

It seems to trip on this output:

```
#  pkg-config --libs libssh2
-LC:/rtools40/mingw64/lib -lssh2 -lcrypt32 -lgdi32 -lws2_32
```

I think because `crypt32` is a windows system library.

Full log here: https://github.com/r-windows/rtools-packages/pull/159 . Has anything changed in the cmake files?

**Comment by jeroen** [comment]
This is due to a combination of mingw-w64 and static linking; it's probably easier to work around this on my end.

**Comment by ethomson** [comment]
Yoinks!  I'm happy to take a pull request if you have a solution here, but this is very, very far outside my wheelhouse.  😁
