### ISSUE TITLE
Multiple unchecked return values in libgit2

### ISSUE THREAD

**Issue by bmajik** [libgit2/libgit2#5665]
All,

We (at Microsoft) have a GitHub Application called "Monocle-AI" which uses some light AI to do C/C++ code analysis, looking for different types of defects.  We've run the tool against the libgit2 codebase and the tool has auto-generated some github issues and 2 PRs based on what it discovered.

Before having the tool create issues and PRs into the libgit2 repository, I wanted to get permission from the community before hand.

You can see the issues and PRs we identified here:
https://github.com/siva-msft/libgit2/issues
and 
https://github.com/siva-msft/libgit2/pulls

This tool is under active development here at Microsoft and one reason we are running it on different public github repos is to learn how to make it useful to developers.  We'd appreciate any thoughts you could share on how to improve this tool to make it more relevant and useful to you.  

### Reproduction steps
1) Check out commit hash 1e987525b3bd86fc29e7ff67d973861efd22faf7
2) install the Monocle-Ai GitHub application, or have a friend share its output with you :)

### Expected behavior
API calls that return a value have that return value checked in a consistent way across the codebase

### Actual behavior
Some API calls are called without having their return values checked.  Our AI tries to find places where return values are not checked, and where we think the API call is performing data initialization on otherwise uninitialized variables.  This is not a fool proof system, so we are auditing and training it.

In a couple of occurrences in the libgit2 codebase, we have manually audited the code, based on the findings of the AI, and it seems that some of the API calls it flagged _could_ follow code paths that return an error code before having successfully completed variable initialization.  Because the caller hasn't checked this, and doesn't validate that the variable was properly initialized, the caller could then misbehave by operating on data that is in fact random memory contents.

Even when manual code analysis suggests that variable initialization is guaranteed, or that a piece of code cannot fail, we will still flag missing return value checks.  Even if there doesn't appear to be a possibility of a runtime bug, developers often like to see when there are inconsistent contract assumption in the code; e.g. when the API says it returns success or failure, and when callers usually check for this, but a specific caller is not checking it.

When auto-logging issues, our AI finds other places in the codebase where the same API is called and where its return value is properly checked.  We include this information in the issue report as a reference to any developers who are reviewing the issues.

Finally, when it is possible to automatically generate a source code patch that fixes an issue, our system automatically generates those PRs for your inspection and approval.

### Version of libgit2 (release number or SHA1)
1e987525b3bd86fc29e7ff67d973861efd22faf7

### Operating system(s) tested
This issue comes from code analysis - no runtime testing done.

**Comment by ethomson** [comment]
I'd be happy to review these, but there are definitely a number of false positives that this will find.  For example, our `git_buf` API will preserve the failure.  This lets us:

```
git_buf_puts(&buf, "foo");
git_buf_puts(&buf "bar");

if (git_buf_oom(&buf)) {
    // fail
}
```

Which means that static code analysis will flag the `git_buf_puts` as ignoring the return value, but in fact, is a permitted use of our API.

Which is all to say - yes, I'm very interested in improved code analysis.  But I would caution you that we are unlikely to make much progress in reviewing any issue reports based on the large number of false positives.  Pull requests, on the other hand, would be much more appreciated.

**Comment by bmajik** [comment]
Thanks @ethomson !

Firstly, if I understand what you're saying correctly, git_buf_oom is a codebase-specific, or even scenario-specific error checking function that looks at the variable's state, instead looking at the return value.

We deal with scenarios like this for some "well known" error handling patterns, e.g. some types of HRESULT checks on Windows codebases.  If our system understood that git_buf_oom(&varname) represented a valid initialization check for &varname, I assume that would reduce the FP rate.  However, to make the system scale, I think we'd need someway for you to "teach" us that git_buf_oom was an initialization checking function for your codebase.  Supposing that mechanism existed and were reasonably painless, would you be interested?  What sort of interaction/user experience would appeal to you to help the system learn about this pattern in the libgit2 codebase?

Secondly, for the two PR's we created on the private fork, do you have any objection to those same PRs being made against the primary repo?

Thanks,
Matt

**Comment by ethomson** [comment]
> Supposing that mechanism existed and were reasonably painless, would you be interested? What sort of interaction/user experience would appeal to you to help the system learn about this pattern in the libgit2 codebase?

I think so, yes.  Some sort of decorator on the function, not on the callsites.  😁

**Comment by ethomson** [comment]
I didn’t expect that you’d unleash this app upon us.  Do you want feedback on these issues that it’s opened - beyond “hey why are you spamming my repo!?!” - or what’s the expectation you have here?

**Comment by bmajik** [comment]
Sorry that’s not what you were expecting.  We didn’t turn on the tool on a cadence or anything like that – this is a one-off occurrence.  I believe that most of these issues are ones that you would want to take a look at.  Our system doesn’t yet know how to handle the specific situation you mentioned of an API with multiple success checking semantics, but I don’t believe that pattern is the majority of these issues.  
 
If you’re willing to engage with these issues, what would be beneficial to us would be how you end up dealing with each issue.  E.g. if someone merges a PR that links one of these issues, we’ll infer that the issue was thought to be legitimate by you.  If that doesn’t happen, we’ll infer that you didn’t want this sort of issue after all.  If you close the issues without attaching any PRs that address them, a comment indicating why you didn’t choose to act on the issue [e.g. “false positive”, “doesn’t meet the bug bar”, “our API is supposed to work this way”] would be helpful to help us learn.

**Comment by ethomson** [comment]
> If you’re willing to engage with these issues, what would be beneficial to us would be how you end up dealing with each issue. E.g. if someone merges a PR that links one of these issues, we’ll infer that the issue was thought to be legitimate by you. If that doesn’t happen, we’ll infer that you didn’t want this sort of issue after all. If you close the issues without attaching any PRs that address them, a comment indicating why you didn’t choose to act on the issue [e.g. “false positive”, “doesn’t meet the bug bar”, “our API is supposed to work this way”] would be helpful to help us learn.

Makes sense.  👍
