### ISSUE TITLE
gcc: warning: unrecognized command line option '-Wno-documentation-deprecated-sync'

### ISSUE THREAD

**Issue by jeroen** [libgit2/libgit2#5666]
I'm compiling with gcc-8.3.0 and seeing a compiler warning:

```
C:/Users/jeroen/Desktop/rtools-packages/mingw-w64-libgit2/src/libgit2-1.1.0/src/win32/map.c: At top level:
cc1.exe: warning: unrecognized command line option '-Wno-documentation-deprecated-sync'
```

This is due to https://github.com/libgit2/libgit2/pull/5481 by @pks-t which now sets `disable_warnings(documentation-deprecated-sync)`  unconditionally in cmake, however this flag doesn't seem to exist in gcc?

Not super important, but I don't think this is intended?

**Comment by ethomson** [comment]
No, we shouldn't warn on this.  I thought `enable_warnings` / `disable_warnings` checked for the viability of the flag.  This is, indeed, annoying.

**Comment by ethomson** [comment]
`enable_warnings` should do an `add_c_flag_if_supported`; hopefully this is resolved.
