### ISSUE TITLE
Build error with git2/sys/transport.h

### ISSUE THREAD

**Issue by AmarOk1412** [libgit2/libgit2#5669]
### Reproduction steps

```cpp
#include <git2/sys/transport.h>
```

Build a program using git smart transport

### Expected behavior

This should build. Also lot of docs are missing for transport

### Actual behavior

Some errors with undefined structs like git_transport_message_cb are thrown (it builds with v0.28)
I need to include <git2/remote.h> in order to fix the build

### Version of libgit2 (release number or SHA1)
v1.1.0

### Operating system(s) tested
Fedora 32

**Comment by ethomson** [comment]
`git2/sys/transport.h` now includes `transport.h`
