### ISSUE TITLE
The same file appears as deleted and added in the same commit

### ISSUE THREAD

**Issue by suhaibmujahid** [libgit2/libgit2#5688]
### Reproduction steps
* Clone https://github.com/npm/npm
* Create a diff for the commit `c178365094bcb99250fd85c9fc1de541ccbf541a`

_or_

Browse the commit on Github: https://github.com/npm/npm/commit/c178365094bcb99250fd85c9fc1de541ccbf541a

### Expected behavior
The file `doc/search.md` should appear as a modified file. The expected behavior consistent with `git` CLI tool as is shown below:
```
git show --stat c178365094bcb99250fd85c9fc1de541ccbf541a
```
```
commit c178365094bcb99250fd85c9fc1de541ccbf541a
Author: Isaac Z. Schlueter <i@izs.me>
Date:   Mon Mar 21 13:54:13 2011 -0700

    Documentation for 1.0

 doc/adduser.md    |  22 ++--------
 doc/author.md     |   1 +
 doc/build.md      |  10 +----
 doc/cache.md      |  49 +++++++++++-----------
 doc/changelog.md  | 258 +++++++++++++----------------------------------------------------------------------------------------------------
 doc/completion.md |  25 +++++------
 doc/config.md     | 401 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++------------------------------------------------------------------------------
 doc/deprecate.md  |   9 ----
 doc/docs.md       |   4 +-
 doc/edit.md       |  18 ++------
 doc/faq.md        |  46 +++++++++------------
 doc/folders.md    | 184 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-----------------------
 doc/install.md    | 100 ++++++--------------------------------------
 doc/json.md       |   4 ++
 doc/link.md       |  37 ++++++++++-------
 doc/list.md       |  64 +++++++---------------------
 doc/npm.md        |   7 ++--
 doc/outdated.md   |  28 -------------
 doc/owner.md      |  32 --------------
 doc/prefix.md     |  10 +++++
 doc/prune.md      |  15 +++++++
 doc/publish.md    |  10 +----
 doc/rebuild.md    |   8 +---
 doc/registry.md   |  47 +--------------------
 doc/restart.md    |   2 +-
 doc/root.md       |  10 +++++
 doc/run-script.md |   4 +-
 doc/scripts.md    |  20 ---------
 doc/search.md     |  11 ++++-
 doc/start.md      |   4 +-
 doc/stop.md       |   4 +-
 doc/tag.md        |   9 ++--
 doc/test.md       |   5 ++-
 doc/uninstall.md  |  18 ++------
 doc/update.md     |  14 +------
 35 files changed, 573 insertions(+), 917 deletions(-)
```
### Actual behavior
`libgit2`, as well as Github (since it uses `libgit2`), shows that the same file got deleted and added in the same commit.

![image](https://user-images.githubusercontent.com/4151357/97616880-7b38cf00-19f3-11eb-97eb-d70f0c674302.png)

### Version of libgit2 (release number or SHA1)
`v1.1.0`

### Operating system(s) tested
Debian buster

**Comment by lhchavez** [comment]
FWIW `git diff` also reports the file being deleted and added in the same commit, since it was changed from being a symlink to a regular file:

```diff
npm$ git diff c178365094bcb99250fd85c9fc1de541ccbf541a^ c178365094bcb99250fd85c9fc1de541ccbf541a -- doc/search.md
diff --git a/doc/search.md b/doc/search.md
deleted file mode 120000
index eaad7ac..0000000
--- a/doc/search.md
+++ /dev/null
@@ -1 +0,0 @@
-list.md
\ No newline at end of file
diff --git a/doc/search.md b/doc/search.md
new file mode 100644
index 0000000..22cbeb6
--- /dev/null
+++ b/doc/search.md
@@ -0,0 +1,10 @@
+npm-ls(1) -- List installed packages
+======================================
+
+## SYNOPSIS
+
+    npm search [search terms ...]
+
+## DESCRIPTION
+
+Search the registry for packages matching the search terms.
```

**Comment by ethomson** [comment]
I don't know what "midfield" means precisely, but depending on your similarity options, a completely rewritten file will be split into an add and delete.  This is useful for tracking renames, especially cyclical ones, where you rename `a` to `b` and `b` to `a`.

This file looks to have been completely rewritten, so it's certainly reasonable that this would be the output here.  If you can reproduce with the same similarity matching settings between git and libgit2 then that would be helpful but at the moment I don't necessarily see that there's a problem.

**Comment by suhaibmujahid** [comment]
@lhchavez thank you for your reply. I have the same behavior you described when I run the following: 
```
git show c178365094bcb99250fd85c9fc1de541ccbf541a -- doc/search.md
```
```diff
commit c178365094bcb99250fd85c9fc1de541ccbf541a
Author: isaacs <i@izs.me>
Date:   Mon Mar 21 13:54:13 2011 -0700

    Documentation for 1.0

diff --git a/doc/search.md b/doc/search.md
deleted file mode 120000
index eaad7acae..000000000
--- a/doc/search.md
+++ /dev/null
@@ -1 +0,0 @@
-list.md
\ No newline at end of file
diff --git a/doc/search.md b/doc/search.md
new file mode 100644
index 000000000..22cbeb6a6
--- /dev/null
+++ b/doc/search.md
@@ -0,0 +1,10 @@
+npm-ls(1) -- List installed packages
+======================================
+
+## SYNOPSIS
+
+    npm search [search terms ...]
+
+## DESCRIPTION
+
+Search the registry for packages matching the search terms.
```
but it looks different with `--stat`:
```
git show --stat c178365094bcb99250fd85c9fc1de541ccbf541a -- doc/search.md
```
```
commit c178365094bcb99250fd85c9fc1de541ccbf541a
Author: isaacs <i@izs.me>
Date:   Mon Mar 21 13:54:13 2011 -0700

    Documentation for 1.0

 doc/search.md | 11 ++++++++++-
 1 file changed, 10 insertions(+), 1 deletion(-)
```

I'm not sure if this is intended behavior in the git tool. When you add the `--stat` option, you see the file as modified, but with the normal diff, you see it as deleted then added. This could be confusing, I think the naive exception is to see the file as modified and have it consistent.

Thank you for matching the behavior in your PR #5691.

**Comment by suhaibmujahid** [comment]
@ethomson thank you for your reply. 

> I don't know what "midfield" means precisely, but depending on your similarity options, a completely rewritten file will be split into an add and delete. This is useful for tracking renames, especially cyclical ones, where you rename `a` to `b` and `b` to `a`.

Sorry, I meant *modified* 😞 .

----

In this particular case, we do not have a rename. It is a complete written as you mentioned but without changing the path. I'm not sure if the similarity is involved in such cases.

For cyclical rename, I tried to replicate the case by doing a cyclical rename without changing the content. It appears as modified files, not a rename or added and deleted files (`git version 2.24.3`):
```
commit a51e1a4c12f17f6a27c9b154f6edfef4a2a97df0 (HEAD -> latest)
Author: Suhaib Mujahid <suhaibmujahid@gmail.com>
Date:   Sat Oct 31 15:15:05 2020 -0400

    Cyclical rename example

 .mailmap  | 91 +++++++++++++++++--------------------------------------------------------------------------
 README.md | 91 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-----------------
 2 files changed, 91 insertions(+), 91 deletions(-)
```

----

> This file looks to have been completely rewritten, so it's certainly reasonable that this would be the output here. If you can reproduce with the same similarity matching settings between git and libgit2 then that would be helpful but at the moment I don't necessarily see that there's a problem.

As @lhchavez mentioned, using the `diff` command, both git and libgit2 have the same behavior. However, when adding the `--stat` option or using `git_diff_get_stats()` the behavior between git and libgit2  differs and @lhchavez opened a PR (#5691) to solve that.

Still, I'm not sure if showing the same path as deleted then added in the same commit should be expected behavior.

**Comment by ethomson** [comment]
Hmm.  I guess my question is whether this is a _data_ problem or a _reporting_ problem of that data.  `git_diff` creates a diff object with data, and then `git_diff_get_stats` creates a report on top of that data.

It doesn't feel like `git_diff_get_stats` should - despite the name - guarantee to provide the same reporting as `git diff --stat` does based on arbitrary input data.  It feels to me like it should report that data, not modify it.

It feels like if one wanted to emulate `git diff --stat` that we should create a set of options to do that, if there aren't already, and we should document those options if there are.  And then `git_diff_get_stats` would emit the data unmodified.

But I could be wrong here.

**Comment by suhaibmujahid** [comment]
Thank you @ethomson, I appreciate your response. 

I agree with you that `git_diff_get_stats` should just report that data, not modify it. But also it will be confusing if the reporting does not match the git tool behavior. 

I feel like there is a buggy behavior in the git tool itself. Passing the `--stat` option should not change that date and also the `git diff` command itself should not have the same file path twice in the same diff result (e.g. as deleted and then added).

I can describe the situation as following:

|      Procedure    |            libgit2          |             git             |
| ----------------- | --------------------------- | --------------------------- |
| `git diff`        | shown as deleted then added | shown as deleted then added |
| `git diff --stat` | shown as deleted then added | shown as modified           |

To avoid unnecessary confusion, I think the output should be consistent across all shown cases in the table above. If we cannot change the behavior in the git tool itself, maybe it is good to adapt to its behavior.


I may miss understood something. Feel free to correct me.

**Comment by ethomson** [comment]
> But also it will be confusing if the reporting does not match the git tool behavior.

What I'm saying is that if you want to emulate `git diff --stat`, then you may need to pass some diff options to the `git_diff` function to make that happen before calling `git_diff_get_stats`.  libgit2's commands at this level are not 1:1 analog to git CLI commands.  If we had a `git_cmd_diff` (and I expect that we will) then it should have that 1:1 analog, but I don't think that there's necessarily an expectation that `git_diff` with the default options followed by `git_diff_get_stats` with the default options should _necessarily_ match the `git diff --stat` behavior.

**Comment by ethomson** [comment]
Closing as stale.
