### ISSUE TITLE
French characters in file name not handled correctly

### ISSUE THREAD

**Issue by anthony-7** [libgit2/libgit2#5693]
We have a French customer who has files with names that contain the "à" character. For example, DEPTAB.DCàDEMOLIB.file.yml.

The filename in the path that git_status_foreach_ext() sends to its callback function is incorrect. It's returning DEPTAB.DCÃ DEMOLIB.file.yml. ie. It's replaced the "à" (0xE0) with "Ã " (0xC3 0xA0).

### Version of libgit2
1.1.0

### Operating system(s) tested
Win 10

Built with Visual Studio 2019.

**Comment by ethomson** [comment]
Can you provide reproduction steps to produce this behavior?

**Comment by anthony-7** [comment]
I've just realised that 0xC3 0xA0 is the UTF-8 byte code for "à". Does libgit2 only return strings in UTF-8 or is there a way that I can build it or call it such that it returns ASCII or UTF-16 ?

**Comment by ethomson** [comment]
> I've just realised that 0xC3 0xA0 is the UTF-8 byte code for "à". Does libgit2 only return strings in UTF-8 or is there a way that I can build it or call it such that it returns ASCII or UTF-16 ?

No - git stores its files as UTF-8 and we don't have any functionality on top of that to give you file paths in a different format.  If you have UTF-16 data, you'll need to do a conversion step.
