### ISSUE TITLE
Concurrent clones from local bare repository

### ISSUE THREAD

**Issue by vchuravy** [libgit2/libgit2#5726]
### Reproduction steps

Our current workflow uses LibGit2 to:

1. Create a bare clone of the upstream repository
2. Concurrent workers use the bare clone to a local clone into their local working directory.

### Expected behavior
Each worker should obtain a clone

### Actual behavior

We seem to be running into a race condition on the `bare clone`. Looking at the log of the workers:

- Several workers error with: ` GitError(Code:ENOTFOUND, Class:OS, could not find '/depot/downloads/llvm-project.git/objects/pack/pack_git2_DvLgtp' to stat: No such file or directory)`
- Other workers error with: `GitError(Code:ENOTFOUND, Class:OS, could not find '/depot/downloads/llvm-project.git/objects/pack/pack_git2_iIidx.lock' to stat: No such file or directory)`

### Version of libgit2 (release number or SHA1)
v1.1.0

### Operating system(s) tested
Linux

**Comment by ethomson** [comment]
What's you've posted is obviously not C...  what is it?  Can you help me boil this down to a reproducible issue in libgit2 itself?

I don't mean to suggest that libgit2 isn't the problem - I'm sure it is - but I'd like to better understand what you're doing precisely.

**Comment by lhchavez** [comment]
just out of curiosity: is the bare clone being modified concurrently with the workers that are cloning that? I was not able to reproduce this behavior by just cloning a repository multiple times, i *had* to be actively modifying the source repository for me to hit the same issue. stack trace just for reference:

```
(gdb) where
#0  git_path_set_error (errno_value=<optimized out>, path=0x7fffec0081f0 "/tmp/libgit2_tests_lPtdXD/clone.02.git/.git/objects/pack/trash.lock", action=0x555555852896 "stat")
    at ../src/path.c:686
#1  0x00005555555de70c in _cp_r_callback (ref=0x7ffff6808780, from=0x7ffff6808760) at ../src/futils.c:984
#2  0x00005555556178a9 in git_path_direach (path=path@entry=0x7ffff6808760, flags=flags@entry=0, fn=fn@entry=0x5555555de690 <_cp_r_callback>, arg=arg@entry=0x7ffff6808780)
    at ../src/path.c:1166
#3  0x00005555555de8bb in _cp_r_callback (ref=0x7ffff6808780, from=0x7ffff6808760) at ../src/futils.c:1009
#4  0x00005555556178a9 in git_path_direach (path=path@entry=0x7ffff6808760, flags=flags@entry=0, fn=fn@entry=0x5555555de690 <_cp_r_callback>, arg=arg@entry=0x7ffff6808780)
    at ../src/path.c:1166
#5  0x00005555555de8bb in _cp_r_callback (ref=ref@entry=0x7ffff6808780, from=from@entry=0x7ffff6808760) at ../src/futils.c:1009
#6  0x00005555555deb4c in git_futils_cp_r (from=<optimized out>, to=0x7fffec0016b0 "/tmp/libgit2_tests_lPtdXD/clone.02.git/.git/objects/", flags=<optimized out>, 
    dirmode=dirmode@entry=511) at ../src/futils.c:1091
#7  0x00005555555be4ae in clone_local_into (link=<optimized out>, branch=0x0, co_opts=0x7ffff6808978, fetch_opts=0x7ffff6808a08, remote=0x7fffec0013c0, repo=0x7fffec004630)
    at ../src/buffer.h:140
#8  git__clone (out=out@entry=0x7ffff6809c78, url=<optimized out>, local_path=local_path@entry=0x7fffec000b60 "./clone.02.git", _options=_options@entry=0x7ffff6809ca0, 
    use_existing=use_existing@entry=0) at ../src/clone.c:490
#9  0x00005555555be8ec in git_clone (out=out@entry=0x7ffff6809c78, url=<optimized out>, local_path=local_path@entry=0x7fffec000b60 "./clone.02.git", 
    _options=_options@entry=0x7ffff6809ca0) at ../src/clone.c:525
```

is there a way to perform locking (like with a read-write mutex, or through the filesystem with the aid of [`flock(2)`](https://linux.die.net/man/2/flock)) while the source repository is being modified so that the workers know that they need to wait until the source repository has cleaned up all temporary files?

**Comment by vchuravy** [comment]
Turns out our code had a race-condition where multiple workers would trigger a fetch https://github.com/JuliaPackaging/BinaryBuilderBase.jl/pull/120
