### ISSUE TITLE
Static linking fails for external dependency 'http_parser'

### ISSUE THREAD

**Issue by wehrend** [libgit2/libgit2#5739]
Hello, I have a question I couldn't solve on my own.

For the maker software 'Fritzing' I need libgit2 v0.28.x
as external dependency as a static build

Also I've seen there is already an http_parser implementation 
in deps/ without any references to an external library.
So which one is the right one? Please clear up

### Reproduction steps

clone, build and install http_parser to /usr/local/lib 
clone libgit2, and checkout 
 git clone https://github.com/libgit2/libgit2.git
 git checkout tags/v0.28.5
 mkdir build
 cmake -DBUILD_SHARED_LIBS=OFF .. 
       ...
       -- Found HTTP_Parser: /usr/local/include
       ...
       (complete log see below)
 cmake .. && cmake --build .

 
 

### Expected behavior

nm should output address for functions involving http_parser

 nm --demangle libgit2.so | grep http_parser
    <address>    T http_parser_execute
    <address>    T http_parser_init
    <address>    T http_parser_parse_url

### Actual behavior

nm --demangle libgit2.so | grep http_parser
                 U http_parser_execute
                 U http_parser_init
                 U http_parser_parse_url

### Version of libgit2 (release number or SHA1)

v0.28.5 

### Operating system(s) tested

Debian Buster

Thanks, Sven Wehrend

Log:
-- The C compiler identification is GNU 8.3.0
        -- Check for working C compiler: /usr/bin/cc
        -- Check for working C compiler: /usr/bin/cc -- works
        -- Detecting C compiler ABI info
        -- Detecting C compiler ABI info - done
        -- Detecting C compile features
        -- Detecting C compile features - done
        -- Found PkgConfig: /usr/bin/pkg-config (found version "0.29") 
        -- Looking for pthread.h
        -- Looking for pthread.h - found
        -- Looking for pthread_create
        -- Looking for pthread_create - not found
        -- Looking for pthread_create in pthreads
        -- Looking for pthread_create in pthreads - not found
        -- Looking for pthread_create in pthread
        -- Looking for pthread_create in pthread - found
        -- Found Threads: TRUE  
        -- Performing Test HAVE_STRUCT_STAT_ST_MTIM
        -- Performing Test HAVE_STRUCT_STAT_ST_MTIM - Success
        -- Performing Test HAVE_STRUCT_STAT_ST_MTIMESPEC
        -- Performing Test HAVE_STRUCT_STAT_ST_MTIMESPEC - Failed
        -- Performing Test HAVE_STRUCT_STAT_MTIME_NSEC
        -- Performing Test HAVE_STRUCT_STAT_MTIME_NSEC - Failed
        -- Performing Test HAVE_STRUCT_STAT_NSEC
        -- Performing Test HAVE_STRUCT_STAT_NSEC - Success
        -- Performing Test IS_WALL_SUPPORTED
        -- Performing Test IS_WALL_SUPPORTED - Success
        -- Performing Test IS_WEXTRA_SUPPORTED
        -- Performing Test IS_WEXTRA_SUPPORTED - Success
        -- Performing Test IS_WDOCUMENTATION_SUPPORTED
        -- Performing Test IS_WDOCUMENTATION_SUPPORTED - Failed
        -- Performing Test IS_WNO_MISSING_FIELD_INITIALIZERS_SUPPORTED
        -- Performing Test IS_WNO_MISSING_FIELD_INITIALIZERS_SUPPORTED - Success
        -- Performing Test IS_WSTRICT_ALIASING_SUPPORTED
        -- Performing Test IS_WSTRICT_ALIASING_SUPPORTED - Success
        -- Performing Test IS_WSTRICT_PROTOTYPES_SUPPORTED
        -- Performing Test IS_WSTRICT_PROTOTYPES_SUPPORTED - Success
        -- Performing Test IS_WDECLARATION_AFTER_STATEMENT_SUPPORTED
        -- Performing Test IS_WDECLARATION_AFTER_STATEMENT_SUPPORTED - Success
        -- Performing Test IS_WSHIFT_COUNT_OVERFLOW_SUPPORTED
        -- Performing Test IS_WSHIFT_COUNT_OVERFLOW_SUPPORTED - Success
        -- Performing Test IS_WUNUSED_CONST_VARIABLE_SUPPORTED
        -- Performing Test IS_WUNUSED_CONST_VARIABLE_SUPPORTED - Success
        -- Performing Test IS_WUNUSED_FUNCTION_SUPPORTED
        -- Performing Test IS_WUNUSED_FUNCTION_SUPPORTED - Success
        -- Performing Test IS_WFORMAT_SUPPORTED
        -- Performing Test IS_WFORMAT_SUPPORTED - Success
        -- Performing Test IS_WFORMAT_SECURITY_SUPPORTED
        -- Performing Test IS_WFORMAT_SECURITY_SUPPORTED - Success
        -- Performing Test IS_WINT_CONVERSION_SUPPORTED
        -- Performing Test IS_WINT_CONVERSION_SUPPORTED - Success
        -- Performing Test IS_WNO_DOCUMENTATION_DEPRECATED_SYNC_SUPPORTED
        -- Performing Test IS_WNO_DOCUMENTATION_DEPRECATED_SYNC_SUPPORTED - Success
        -- Looking for regcomp_l
        -- Looking for regcomp_l - not found
        -- Looking for regcomp
        -- Looking for regcomp - found
        -- Looking for futimens
        -- Looking for futimens - found
        -- Checking prototype qsort_r for HAVE_QSORT_R_BSD - False
        -- Checking prototype qsort_r for HAVE_QSORT_R_GNU - True
        -- Looking for qsort_s
        -- Looking for qsort_s - not found
        -- Looking for clock_gettime in rt
        -- Looking for clock_gettime in rt - found
        -- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.1.1d")  
        -- Found mbedTLS:
        --   version 2.16.0
        --   TLS: /usr/lib/x86_64-linux-gnu/libmbedtls.so
        --   X509: /usr/lib/x86_64-linux-gnu/libmbedx509.so
        --   Crypto: /usr/lib/x86_64-linux-gnu/libmbedcrypto.so
        -- Found HTTP_Parser: /usr/local/include  
        -- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
        -- Checking for module 'libssh2'
        --   Found libssh2, version 1.8.0
        --   Resolved libraries: /usr/lib/x86_64-linux-gnu/libssh2.so
        -- Looking for libssh2_userauth_publickey_frommemory in /usr/lib/x86_64-linux-gnu/libssh2.so
        -- Looking for libssh2_userauth_publickey_frommemory in /usr/lib/x86_64-linux-gnu/libssh2.so - found
        -- Found PythonInterp: /usr/bin/python (found version "2.7.16") 
        -- Enabled features:
        * threadsafe, threadsafe support
        * HTTPS, using OpenSSL
        * SHA, using CollisionDetection
        * http-parser, http-parser support
        * zlib, using system zlib
        * SSH, SSH transport support

        -- Disabled features:
        * debugpool, debug pool allocator
        * tracing, tracing support
        * SPNEGO, SPNEGO authentication support
        * iconv, iconv encoding conversion support

        -- Configuring done
        -- Generating done
        -- Build files have been written to: /home/sven/development/fritzing/libgit2/build

**Comment by ethomson** [comment]
I'd use the included version if you need to link statically.

**Comment by wehrend** [comment]
I was able to work around it,by just linking Fritzing with the installed version of libgit2. 
I guessed that it needs an external dependency called libhttp_parser based on the dependencies listed by the debian package, 
but as I have seen the http_parser in deps doesn't need anything. And I had the same result without the external lib

**Comment by ethomson** [comment]
Thanks for the info!
