### ISSUE TITLE
Lack of documentation for "version" member of struct "git_blob_filter_options"

### ISSUE THREAD

**Issue by JoshuaS3** [libgit2/libgit2#5756]
### Expected behavior
Detailed usage documentation describing how to value this property when passing options to `git_blob_filter`.

### Actual behavior
No usage documentation at all.

### Version of libgit2 (release number or SHA1)
HEAD (fe41e5823986aff01054b7db4b869b2896ea4c30)

---

Definition:
https://github.com/libgit2/libgit2/blob/fe41e5823986aff01054b7db4b869b2896ea4c30/include/git2/blob.h#L119-L127

---

I have no idea what to put for `version` when passing options to `git_blob_filter`. As a result, I still use `git_blob_filtered_content` despite documentation saying it's deprecated.

**Comment by JoshuaS3** [comment]
It looks like `version` is supposed to be `GIT_BLOB_FILTER_OPTIONS_VERSION`.

`git_blob_filter`:
https://github.com/libgit2/libgit2/blob/fa618a595bff675fa1d001dc9d57f8fd6c1b052e/src/blob.c#L426-L427

`GIT_BLOB_FILTER_OPTIONS_VERSION`:
https://github.com/libgit2/libgit2/blob/fa618a595bff675fa1d001dc9d57f8fd6c1b052e/include/git2/blob.h#L129

`GIT_ERROR_CHECK_VERSION`:
https://github.com/libgit2/libgit2/blob/a5cb2cc9f547d9defaf51b2af25ba2fa9d9015a0/src/common.h#L116-L133

Based on this and other instances of structure versioning throughout libgit2 (and their documentations), this should be the documentation for `git_blob_filter_options.version`:
```
The struct version; pass `GIT_BLOB_FILTER_OPTIONS_VERSION`.
```

**Comment by JoshuaS3** [comment]
Opened a PR at #5759

**Comment by lhchavez** [comment]
yeah, ideally the `.version` fields in any `_options` struct should not be manually populated. instead there are two initialization patterns that are equivalent:

```c
git_foo_options my_options = GIT_FOO_OPTIONS_INIT;
// or
git_foo_options my_options;
git_foo_options_init(&my_options, GIT_FOO_OPTIONS_VERSION);
```

that way the struct has good defaults set.

but `git_blob_filter_options` lacks `git_blob_options_init()`!

**Comment by JoshuaS3** [comment]
Oh, wow. Now I see something like that for `git_clone_options`

https://github.com/libgit2/libgit2/blob/fe41e5823986aff01054b7db4b869b2896ea4c30/include/git2/clone.h#L96-L104

https://github.com/libgit2/libgit2/blob/fe41e5823986aff01054b7db4b869b2896ea4c30/include/git2/clone.h#L171-L183

It looks like this documentation is just completely missing from `git_blob_filter_options`.
