### ISSUE TITLE
.gitignore file contains "tags" which ignores some folders in the test directory

### ISSUE THREAD

**Issue by lrm29** [libgit2/libgit2#5779]
The "tags" pattern in the .gitignore file;

https://github.com/libgit2/libgit2/blob/487f2a8287c4d1d41d39e05ac53d0e50c679d7e9/.gitignore#L5

means that (for example), the contents of these directories would be ignored:

tests/resources/empty_bare.git/refs/tags
tests/resources/testrepo.git/refs/tags
tests/resources/push_src/.gitted/refs/tags
tests/resources/empty_standard_repo/.gitted/refs/tags
tests/resources/describe/.gitted/refs/tags
tests/resources/testrepo/.gitted/refs/tags

Could the pattern be updated to not ignore these folders? I'm not sure what the pattern was supposed to refer to.

**Comment by ethomson** [comment]
Yes, it should - this is to ignore [ctags files](https://en.wikipedia.org/wiki/Ctags).  It should only be meant to ignore the `tags` file in the root of the working directory.
