### ISSUE TITLE
SSL Routines: SSL shutdown: Shutdown while init

### ISSUE THREAD

**Issue by jaripog** [libgit2/libgit2#5782]
You are opening a _bug report_ against the libgit2 project: we use
GitHub Issues for tracking bug reports and feature requests.  If you
have a question about an API or usage, please ask on StackOverflow:
http://stackoverflow.com/questions/tagged/libgit2.  If you want to
have high-level discussions about the libgit2 project itself, visit
https://github.com/libgit2/discussions.

Otherwise, to report a bug, please fill out the reproduction steps
(below) and delete these introductory paragraphs.  Thanks!

### Reproduction steps
IDPprovider : Auth0,
Protocal: SAML 2.0,
while logging in intermittently we facing this error internal server error 500 in the apache level.

the debug log is below 
[Fri Jan 08 10:00:49.238914 2021] [ssl:info] [pid 4129:tid 140534936950528] [client 172.19.19.184:54012] AH01992: SSL library error 1 reading data
[Fri Jan 08 10:00:49.238937 2021] [ssl:info] [pid 4129:tid 140534936950528] SSL Library Error: error:140E0197:SSL routines:SSL_shutdown:shutdown while in init
[ 2021-01-08 10:00:49.2390 4129/7fd0d6fed700 apache2/Hooks.cpp:732 ]: Unexpected error in mod_passenger: An error occurred while receiving HTTP upload data: Internal error (specific information not available) (20014)
Backtrace:
     in 'boost::shared_ptr<Passenger::BufferedUpload> Hooks::receiveRequestBody(request_rec*)' (Hooks.cpp:1190)
     in 'int Hooks::handleRequest(request_rec*)' (Hooks.cpp:546)

### Expected behavior
SSL handshake should be successful

### Actual behavior
out of 10 login attemts 1 is failure login which SSL is causing this

### Operating system(s) tested
centos 7 ,
Ruby 2.7.1
Phusion passenger - 4.0.59
OpenSSL 1.0.2k-fips  26 Jan 2017

**Comment by ethomson** [comment]
Does this have anything to do with libgit2?

**Comment by jaripog** [comment]
Hi ethomson,

I really dont know, i was able to see the some changes made to openssl.c where out error_log was also pointing to the same file

https://github.com/libgit2/libgit2/pull/4875

Please guide.

**Comment by ethomson** [comment]
It looks like the problem is with OpenSSL or Apache.  We don't build OpenSSL, we use it just like you do.  I think that you need to open an issue with the Apache project, or with OpenSSL themselves.

**Comment by jaripog** [comment]
Thanks ethomson
