### ISSUE TITLE
git_repository_discover doesn't work inside subst-mounted drives

### ISSUE THREAD

**Issue by invrainbow** [libgit2/libgit2#5785]
I used `subst` on Windows to mount a folder to the w: drive:

```batch
subst w: c:\some\folder
```

This `c:\some\folder` is a git repo. Now if I call `git_repository_discover` on a folder inside, `w:\inner`

```c
git_buf root = {0};
git_repository_discover(&root, "w:\\inner", 0, NULL);
```

then it fails with

```
could not find repository from 'w:\inner'
```

But calling `git_repository_discover` with `c:\some\folder\inner` works.

**Comment by ethomson** [comment]
Out of curiosity, does setting `across_fs` to `1` change the behavior?
