### ISSUE TITLE
libgit2 not building correctly using latest cmake

### ISSUE THREAD

**Issue by Why-not-now** [libgit2/libgit2#5825]
### Reproduction steps
building using cmake 3.19.7
### Expected behavior
Expected to build
### Actual behavior
see picture
![image](https://user-images.githubusercontent.com/81090788/111907159-0d1ea280-8a8f-11eb-859e-65ac5c81201f.png)
### Version of libgit2 (release number or SHA1)
0.28.5
### Operating system(s) tested
Windows

**Comment by ethomson** [comment]
I just upgraded and it works fine for me.  Did this work previously with a different version of cmake and stopped working? Can you provide more information about your environment?  Does it work if you try to build without libssh2 support?
 
(Please paste text, don't attach screenshots.)

**Comment by Why-not-now** [comment]
I uninstalled perl strawberry and was able to got the output
>C:\fritzing\libgit2\build>cmake -DBUILD_SHARED_LIBS=OFF ..
>-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19042.
>
> CMake Deprecation Warning at CMakeLists.txt:15 (CMAKE_MINIMUM_REQUIRED):
>   Compatibility with CMake < 2.8.12 will be removed from a future version of
>   CMake.
> 
>   Update the VERSION argument <min> value or use a ...<max> suffix to tell
>   CMake that the project does not need compatibility with older versions.
> 
> 
> -- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
> -- Checking prototype qsort_r for HAVE_QSORT_R_BSD - False
> -- Checking prototype qsort_r for HAVE_QSORT_R_GNU - False
> -- Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY OPENSSL_INCLUDE_DIR)
> -- Could NOT find HTTP_Parser (missing: HTTP_PARSER_INCLUDE_DIR HTTP_PARSER_LIBRARY)
> -- http-parser version 2 was not found or disabled; using bundled 3rd-party sources.
> -- Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR)
> -- zlib was not found; using bundled 3rd-party sources.
> -- LIBSSH2 not found. Set CMAKE_PREFIX_PATH if it is installed outside of the default search path.
> -- Enabled features:
>  * threadsafe, threadsafe support
>  * HTTPS, using WinHTTP
>  * SHA, using CollisionDetection
>  * http-parser, http-parser support (bundled)
>  * zlib, using bundled zlib
> 
> -- Disabled features:
>  * debugpool, debug pool allocator
>  * tracing, tracing support
>  * SSH, SSH transport support
>  * SPNEGO, SPNEGO authentication support
>  * iconv, iconv encoding conversion support
> 
> -- Configuring done
> -- Generating done
> -- Build files have been written to: C:/fritzing/libgit2/build
> 

(btw, this is my 1st time building anything from scratch, so how do I fix/install SSL and libssh2?)

**Comment by ethomson** [comment]
The OpenSSL problem is not actually a _problem_.  You (probably) don't want to use OpenSSL on Windows - we'll use the Windows native TLS stack, which is (probably) what you want.  😁 

libssh2, on the other hand, is a little trickier.  I don't use it, personally, so I don't have any experience with making the build see it.  Is lack of SSH support a dealbreaker for you?  I ask because it may not be obvious that it, too, is an optional component.  libgit2 works fine without libssh2, except that you can't talk to remotes over SSH (only HTTPS).  For some people, obviously, that's a critical lack of functionality.  For some people, it's not noticeable.

**Comment by Why-not-now** [comment]
> git2.lib(path.obj) : error LNK2001: unresolved external symbol __imp_GetTokenInformation
> git2.lib(path.obj) : error LNK2001: unresolved external symbol __imp_OpenProcessToken
> git2.lib(path.obj) : error LNK2001: unresolved external symbol __imp_IsValidSid
> git2.lib(path.obj) : error LNK2001: unresolved external symbol __imp_IsWellKnownSid
> git2.lib(path.obj) : error LNK2001: unresolved external symbol __imp_GetNamedSecurityInfoW
> git2.lib(path.obj) : error LNK2001: unresolved external symbol __imp_EqualSid
> git2.lib(findfile.obj) : error LNK2001: unresolved external symbol __imp_RegQueryValueExW
> git2.lib(findfile.obj) : error LNK2001: unresolved external symbol __imp_RegOpenKeyExW
> git2.lib(findfile.obj) : error LNK2001: unresolved external symbol __imp_RegCloseKey
> git2.lib(winhttp.obj) : error LNK2001: unresolved external symbol __imp_WinHttpConnect
> git2.lib(winhttp.obj) : error LNK2001: unresolved external symbol __imp_WinHttpQueryOption
> git2.lib(winhttp.obj) : error LNK2001: unresolved external symbol __imp_WinHttpSetStatusCallback
> git2.lib(winhttp.obj) : error LNK2001: unresolved external symbol __imp_CoUninitialize
> git2.lib(winhttp.obj) : error LNK2001: unresolved external symbol __imp_WinHttpSetTimeouts
> git2.lib(winhttp.obj) : error LNK2001: unresolved external symbol __imp_CoCreateInstance
> git2.lib(winhttp.obj) : error LNK2001: unresolved external symbol __imp_CertFreeCertificateContext
> git2.lib(winhttp.obj) : error LNK2001: unresolved external symbol __imp_WinHttpSetCredentials
> git2.lib(winhttp.obj) : error LNK2001: unresolved external symbol __imp_WinHttpSendRequest
> git2.lib(winhttp.obj) : error LNK2001: unresolved external symbol __imp_WinHttpWriteData
> git2.lib(winhttp.obj) : error LNK2001: unresolved external symbol __imp_WinHttpQueryAuthSchemes
> git2.lib(winhttp.obj) : error LNK2001: unresolved external symbol __imp_WinHttpCloseHandle
> git2.lib(winhttp.obj) : error LNK2001: unresolved external symbol __imp_WinHttpSetOption
> git2.lib(winhttp.obj) : error LNK2001: unresolved external symbol __imp_WinHttpOpenRequest
> git2.lib(winhttp.obj) : error LNK2001: unresolved external symbol __imp_WinHttpReadData
> git2.lib(winhttp.obj) : error LNK2001: unresolved external symbol __imp_WinHttpQueryHeaders
> git2.lib(winhttp.obj) : error LNK2001: unresolved external symbol __imp_WinHttpAddRequestHeaders
> git2.lib(winhttp.obj) : error LNK2001: unresolved external symbol __imp_CoInitializeEx
> git2.lib(winhttp.obj) : error LNK2001: unresolved external symbol __imp_WinHttpOpen
> git2.lib(winhttp.obj) : error LNK2001: unresolved external symbol __imp_UuidCreate
> git2.lib(winhttp.obj) : error LNK2001: unresolved external symbol __imp_WinHttpReceiveResponse

These are the error I have when trying to build a program (fritzing) that uses libgit2

**Comment by ethomson** [comment]
I'm not very familiar with this, but you're running into problems in the linking phase of building your executable.  libgit2 uses system libraries like winhttp.  I think that you'll need to specify them in the linking phase.  See, for example https://stackoverflow.com/questions/22954119/linker-error-while-linking-some-windows-apis which is a similar problem.

**Comment by Why-not-now** [comment]
@ethomson, do you have a .dll file in your ~/libgit2/Build64/Release file?

**Comment by ethomson** [comment]
> @ethomson, do you have a .dll file in your ~/libgit2/Build64/Release file for 0.28.5?

I had a dll for 1.1.0.  I did not try this with 0.28.5 since that's over two years old and quite out of our support matrix.

Closing this, since based on another issue, it looks like you were able to get your build going.  LMK if not!
