### ISSUE TITLE
[Submodule] Missing retain function

### ISSUE THREAD

**Issue by lolgear** [libgit2/libgit2#5889]
I guess that I'm wrong and you could tell an API function for this, but...
If I would like to iterate over submodules and convert them to my objects, I need a retain function.

```c
int git_submodule_foreach(
	git_repository *repo,
	git_submodule_cb callback,
	void *payload) {/*...*/}
```

```c
void git_submodule_retain(git_submodule *sm)
{
	assert(sm);
	GIT_REFCOUNT_INC(sm);
}
```

### Reproduction steps

1. Iterate over submodules.
2. Callback will return an instance of submodule.
3. After iteration it will release instance of submodule.

### Expected behavior
Instance isn't freed. ( I have a function that retains this instance ).

### Actual behavior
Instance is freed.

### Version of libgit2 (release number or SHA1)
3532c5f49a7158096666764b099f872e779625c2

### Operating system(s) tested
macOS 11.3.1

**Comment by ethomson** [comment]
I can see the value here. To match with prior art, this function should be `git_submodule_dup`. (It would simply refcount and return itself behind the scenes, not actually make a copy.)

**Comment by lolgear** [comment]
@ethomson Could you check mentioned PR?
