### ISSUE TITLE
PCRE dependency not present in build

### ISSUE THREAD

**Issue by tslothorst** [libgit2/libgit2#5894]
I'm using libgit2 in a Visual Studio C++ project. When I build my project there are no problems, everything compiles and links just fine. However when I launch my executable I get an error stating pcre.dll is not found: 
![image](https://user-images.githubusercontent.com/56511738/118946677-ec6fad80-b956-11eb-8caf-c082f9cc2c61.png)

This .dll is indeed missing in the build output directory. The git2.dll is however present:
![image](https://user-images.githubusercontent.com/56511738/118946851-15903e00-b957-11eb-8951-5ae3903cbf25.png)

I've installed libgit2 through vcpkg and it and it's dependencies can be resolved by Visual Studio, however during the build process the pcre dependency is not taken into account. 

### Reproduction steps
Create Visual Studio C++ project and build a project using libgit as dependency.

### Expected behavior
git2.dll and the pcre.dll on which libgit is dependent should be included in the build of the project.

### Actual behavior
git2.dll is included, but pcre.dll is not. 

### Version of libgit2 (release number or SHA1)
v1.1.0.

### Operating system(s) tested
Windows 10 64-bit

**Comment by ethomson** [comment]
> git2.dll and the pcre.dll on which libgit is dependent should be included in the build of the project.

It shouldn't.  We don't built `pcre.dll`; you can either build and link against an existing pcre, in which case you supply the headers and the library yourself, *or* you can use the included pcre, in which case the functionality is built in to libgit2 and there's no separate pcre library produced.

It looks like you're building against an existing pcre but your executable can't find it.  Can you share your cmake options and the output?

**Comment by ethomson** [comment]
> I've installed libgit2 through vcpkg and it and it's dependencies can be resolved by Visual Studio, however during the build process the pcre dependency is not taken into account.

Sorry, I missed this part.  I don't know enough about how vcpkg works to understand how or why it should include pcre but we don't produce the vcpkg packages so this is unfortunately not something that we control ourselves.

**Comment by tslothorst** [comment]
Thank you for your quick reply.

I have in this project no need myself for `pcre.dll` to be present, my own code doesn't use anything from this library. 

I'm not using Cmake for this project, it's a Visual Studio solution `.sln`/'.vcxproj'. However I'd be happy to give it a try with Cmake. Could you provide me with the targets I need to put in `find_package()` and `target_link_libraries()` for libgit2? (If I add libgit2 it's not found).

This is the build output from Visual Studio:
```
'gitlab-release.exe' (Win32): Loaded 'C:\development\[redacted]\gitlab\gitlab-release\Debug\gitlab-release.exe'. Symbols loaded.
'gitlab-release.exe' (Win32): Loaded 'C:\Windows\SysWOW64\ntdll.dll'. 
'gitlab-release.exe' (Win32): Loaded 'C:\Windows\SysWOW64\kernel32.dll'. 
'gitlab-release.exe' (Win32): Loaded 'C:\Windows\SysWOW64\KernelBase.dll'. 
'gitlab-release.exe' (Win32): Loaded 'C:\development\[redacted]\gitlab\gitlab-release\Debug\curlpp.dll'. 
'gitlab-release.exe' (Win32): Loaded 'C:\development\[redacted]\gitlab\gitlab-release\Debug\git2.dll'. Symbols loaded.
'gitlab-release.exe' (Win32): Loaded 'C:\Windows\SysWOW64\ws2_32.dll'. 
'gitlab-release.exe' (Win32): Loaded 'C:\Windows\SysWOW64\rpcrt4.dll'. 
'gitlab-release.exe' (Win32): Loaded 'C:\Windows\SysWOW64\crypt32.dll'. 
'gitlab-release.exe' (Win32): Loaded 'C:\Windows\SysWOW64\ucrtbase.dll'. 
'gitlab-release.exe' (Win32): Loaded 'C:\Windows\SysWOW64\ole32.dll'. 
'gitlab-release.exe' (Win32): Loaded 'C:\Windows\SysWOW64\combase.dll'. 
'gitlab-release.exe' (Win32): Loaded 'C:\Windows\SysWOW64\gdi32.dll'. 
'gitlab-release.exe' (Win32): Loaded 'C:\Windows\SysWOW64\win32u.dll'. 
'gitlab-release.exe' (Win32): Loaded 'C:\Windows\SysWOW64\gdi32full.dll'. 
'gitlab-release.exe' (Win32): Loaded 'C:\Windows\SysWOW64\msvcp_win.dll'. 
'gitlab-release.exe' (Win32): Loaded 'C:\Windows\SysWOW64\user32.dll'. 
'gitlab-release.exe' (Win32): Loaded 'C:\Windows\SysWOW64\advapi32.dll'. 
'gitlab-release.exe' (Win32): Loaded 'C:\Windows\SysWOW64\msvcrt.dll'. 
'gitlab-release.exe' (Win32): Loaded 'C:\Windows\SysWOW64\sechost.dll'. 
'gitlab-release.exe' (Win32): Loaded 'C:\development\[redacted]\gitlab\gitlab-release\Debug\libcurl-d.dll'. 
'gitlab-release.exe' (Win32): Loaded 'C:\Windows\SysWOW64\Wldap32.dll'. 
'gitlab-release.exe' (Win32): Loaded 'C:\Windows\SysWOW64\msvcp140d.dll'. 
'gitlab-release.exe' (Win32): Loaded 'C:\Windows\SysWOW64\vcruntime140d.dll'. 
'gitlab-release.exe' (Win32): Loaded 'C:\Windows\SysWOW64\ucrtbased.dll'. 
'gitlab-release.exe' (Win32): Loaded 'C:\Windows\SysWOW64\winhttp.dll'. 
The thread 0x329c has exited with code 0 (0x0).
The thread 0x323c has exited with code 0 (0x0).
The program '[2528] gitlab-release.exe' has exited with code 0 (0x0).
```

Vcpkg pulls the latest stable libgit2 from this repo and builds it plus it sets up the include paths needed for working with the library.  PCRE is installed/included when I pulled libgit2 since it was listed as a dependency for, here is a screenshot listing installed packages:
![image](https://user-images.githubusercontent.com/56511738/118968338-154e6d80-b96c-11eb-8863-f154e5889bbf.png)
![image](https://user-images.githubusercontent.com/56511738/118968832-ae7d8400-b96c-11eb-8290-4915ea98dd2b.png)

**Comment by ethomson** [comment]
> I'm not using Cmake for this project, it's a Visual Studio solution .sln/'.vcxproj'. However I'd be happy to give it a try with Cmake. Could you provide me with the targets I need to put in find_package() and target_link_libraries() for libgit2? (If I add libgit2 it's not found).

Sorry, I originally thought that you were compiling libgit2 yourself and was asking for the cmake options you were using to build libgit2.  (I wasn't suggesting that you switch over to cmake for your project.)

I don't know enough about vcpkg to understand this, but it seems like there's definitely a problem here.  If you have the libgit2[pcre] feature, I would expect you to get pcre.dll in your output directory, since it's a dependency.  You're [not the only person with this problem](https://stackoverflow.com/questions/67487957/libgit2-dependency-pcre-not-present-in-build), it appears from googling.

I'll find a vcpkg expert who can help enlighten me on this or, in a very worst case scenario, try to learn enough about vcpkg to fix this control file myself.

**Comment by ethomson** [comment]
If you add a dependency on pcre as a workaround, does this work?

**Comment by tslothorst** [comment]
I've added pcre in my vcxproj settings as an additional dependency, however this does not cause pcre.dll to be created. Most likely because it's still deemed as not needed. I'm looking now into adding a bit of code that goes nowhere, but which uses something from `pcre.h` so the proper .dll will be generated when building the project.

**Comment by ethomson** [comment]
I hope that this has been resolved by vcpkg. I'm going to close this as it's quite stale, but please let me know if there's something that we can fix here. 🙏
