### ISSUE TITLE
Broken pipe error while pushing over HTTPS

### ISSUE THREAD

**Issue by pluehne** [libgit2/libgit2#5905]
When pushing to repositories using the HTTPS protocol, we sporadically observed an issue where `git_remote_push` fails with a `SIGPIPE`. When using the Rust wrapper `git2-rs`, the error message reads as follows:

>code: -1
>klass: 2
>message: libgit2 error (2): SSL error: syscall failure: Broken pipe

While debugging this issue, we noticed that it can be reliably reproduced when pushing the `master` branch of https://github.com/algolia/docsearch-configs to an empty repository over HTTPS.

We tried finding the root of the issue, but we were unable to understand what exactly is causing the broken pipe error so far. To us, it looks like a timeout occurs directly before or while sending data to an SSL socket such that the connection is terminated prematurely, resulting in an error the next time data is sent. The reason for that is unclear to us. We also saw that the push operation consistently fails trying to push a specific object (number 17, size: 116732 bytes).

It would be nice if someone more knowledgeable with the networking implementation could take a look :slightly_smiling_face:.

### Reproduction steps

Make sure that you have the updated `push` example with the changes from #5904 on your machine. (Our patch adds support for authentication to the `push` example, which is helpful for testing—most Git servers don’t provide unauthenticated write access after all. We considered this a simpler way to reproduce the issue than building and debugging a separate code example.)

1. Create a new repository you have write access to on a server such as GitHub.com.

2. Clone https://github.com/algolia/docsearch-configs.

   ```shell
   $ cd /tmp
   $ git clone https://github.com/algolia/docsearch-configs
   $ cd docsearch-config
   ```

3. Set the `origin` remote to the repository you created in step 1. Make sure to use an HTTPS URL.

   ```shell
   $ git remote set-url origin https://github.com/<account>/<repository>
   ```

4. Run the `push` example from your working copy of `libgit2`. This will push the previously obtained `master` branch to the `origin` remote, which was updated to point to the target repository in the previous step.

   ```shell
   $ cd <path to libgit2 build directory>
   $ ./examples/lg2 --git-dir /tmp/docsearch-config push
   ```

   Provide your credentials as needed. On GitHub.com, it is advisable to use a [personal access token](https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/creating-a-personal-access-token) for that purpose (`token` can be used as a user name in that case).

### Expected behavior

We would expect the push operation to succeed and the target repository to contain the `master` branch of https://github.com/algolia/docsearch-configs.

### Actual behavior

The process terminates abnormally with `SIGPIPE`. The target repository does not contain the `master` branch of https://github.com/algolia/docsearch-configs.

### Version of libgit2 (release number or SHA1)

Reproduced with

- the 1.1.0 release (7f4fa178629d559c037a1f72f79f79af9c1ef8ce)
- the tip of the `main` branch as of 2021-06-02 (868f4bcb4d3290f4b5320f030fccdf1e7fc8ac8a)

### Operating systems tested

- Arch Linux (latest)
- Ubuntu 20.04

### Related bug reports

- [An issue reported in the `simplegit` project](https://github.com/sba1/simplegit/issues/40), which is also using `libgit2`, could be identical to this one.

---

(CC: @mariusknaust)

**Comment by tiennou** [comment]
I gave a spin to that (macOS 10.15.7/`pr/5904`, with OpenSSL as the HTTPS backend), made myself a new PAT, enabled tracing at `GIT_TRACE_TRACE` level, ran the provided command, and got the described issue.

I'm attaching the log of my lldb session, and it seems to confirm that, by the time we start sending data, the server has already timed out on us (there's no "Received:" line after the initial negotiation).

[issue5905.txt](https://github.com/libgit2/libgit2/files/6591270/issue5905.txt)

**Comment by mariusknaust** [comment]
Unfortunately, we still see this error with some repositories. An example is https://chromium.googlesource.com/v8/v8 (this repository is quite large). In order for the `push` example to work, you must switch to the `master` branch at the end of the 2nd reproduction step (or modify the example to use `refs/heads/main` as a [refspec](https://github.com/libgit2/libgit2/blob/3847522e86e9c65be674f1372cefefdbfbe9ba2b/examples/push.c#L36)).
