### ISSUE TITLE
Implement API for partial file adding similar to "git add -p"

### ISSUE THREAD

**Issue by kaisellgren** [libgit2/libgit2#591]
An API that allows you to add parts of files into the index would be vastly helpful. The behavior would be similar to what you can achieve with ```git add -p```. I believe this API would allow you to define the line numbers ```from``` and ```to``` and it would add the lines between those two values to the index.

**Comment by carlosmn** [comment]
As it's been pointed out mulitple times, the `git add -p` interface is not something libgit2 can implement itself, and this is too broad an issue to get meaningful discussion. If there is introspection or other aspects with which libgit2 can help (patch application is already being worked on, which would be the first large step), those should be handled in individual issues.

**Comment by felixfbecker** [comment]
Is there an issue for "patch application"? Is that implemented already?

**Comment by ethomson** [comment]
@felixfbecker see https://github.com/libgit2/libgit2/pull/4705
