### ISSUE TITLE
[macOS] Security framework. SecureTransport header is deprecated. Project build failed.

### ISSUE THREAD

**Issue by lolgear** [libgit2/libgit2#5914]
I am very curious why current master doesn't build well on macOS 11.4.
I read logs carefully ( well, I read them ) and I noticed that it fails at `SelectHTTPSBackend.cmake`.
Interesting line is `Looking for SSLCreateContext`, because Security framework is considered old at this step.
`SSLCreateContext` is not found in latest `Security.framework`. ( somehow )

Let's look at this function at apple [documentation](https://developer.apple.com/documentation/security/1393063-sslcreatecontext).
This function is deprecated last year.

Also you may check whole header [SecureTransport.h](https://developer.apple.com/documentation/security/secure_transport) with this function.
It is also deprecated.
Apple suggests to use `Network` framework as replacement.

### Documentation
1. [SSLCreateContext](https://developer.apple.com/documentation/security/1393063-sslcreatecontext)
2. [SecureTransport.h](https://developer.apple.com/documentation/security/secure_transport)

### Reproduction steps
1. Build project via `cmake ..` or `cmake -G 'Xcode' ..`
2. Look at errors.

### Environment
libgit2 latest master ( 0d0150d8eb5fe5654af4172fe2f923f5d1317eb7 )
Xcode 12.5
macOS 11.4

### Notes

I assume that this functionality should be delivered via Network framework ( as Apple suggests ).

### Tests
All tests are passed. But environment is pretty old (macOS 10.15 and Xcode 12.4) and tricky, because you install both `libssh2` and `openssl@1.1`.

Could you add tests for latest environment ( macOS 11 and Xcode 12.5 )?
Also it would be nice if you add `-DUSE_SSH=OFF` flag to test everything with clean Xcode and clean macOS without homebrewing additional dependencies.

**Comment by carlosmn** [comment]
This sounds like it would be an additional TLS provider you can choose. Meanwhile finding out why it fails and defining whatever they provide to stop it from failing should be the first step.

**Comment by ethomson** [comment]
Without repro steps, I’m closing this. Please let me know if there’s a way to reproduce.
