### ISSUE TITLE
Update Contribution notes.

### ISSUE THREAD

**Issue by lolgear** [libgit2/libgit2#5927]
I'm very proud to be a part of this community (I wish I'm a part of this community), but I don't understand a PRs merging process.

Some of these PRs are 3 years old. ( Yes, they soon will go to kindergarten ).
However, it seems that they've never met a main branch.

Could anybody at this community write a note about "how to" make a correct PR which will be merged into a main branch?
I opened several PRs and asking for help.
I added required fixes and added tests.
I asked for re-review.

No attention from collaborators since last update.

I believe that PR process can be handled in another way. 
Maybe this project needs more people for review.
Maybe this project needs "collaborators" group that you can point to for review.

**Comment by ethomson** [comment]
> Maybe this project needs more people for review.

Yep, that would be great!  Projects often have many users, a few contributors and very few people who take the time to code review.  A project needs all of these types of collaborators, but the project velocity will, unfortunately, slow down a bit when the code reviewers get busy.  For my part, I've been needed at home with a new baby 👶 and moving the family to another country 🏠🚚🌎✈️.

I appreciate your patience, @lolgear, and we'll try to get your PR merged 🔜.  Thanks again for the contribution!

**Comment by ethomson** [comment]
This does seem like a bug - but an organizational one not a technical one. Maybe we should reopen a discussion item, as I’m not sure that there’s an obvious path forward to gain more contributors organically.
