### ISSUE TITLE
[Feature Request] support `--no-checkout` for `git_worktree_add` 

### ISSUE THREAD

**Issue by Whirlwind** [libgit2/libgit2#5949]
`git worktree add [Path] --no-checkout` will allow user skip checkout the files.

In the libgit2, it will force checkout the files, and there is not option to skip it.

I hope the `git_worktree_add_options` add the `checkout` option.

**Comment by ethomson** [comment]
This seems like a good idea.  Naively, I suspect that this is an easy fix, so I've added that label.  This seems like a good first issue for a [new contributor](https://up-for-grabs.net/#/filters?names=508)!

**Comment by Jagroop-Singh** [comment]
Hey there, I'll grab this one

**Comment by Whirlwind** [comment]
I try to add the feature for my project:
```
	if (wtopts.checkout == 1) {
		/* Checkout worktree's HEAD */
		git_checkout_options coopts = GIT_CHECKOUT_OPTIONS_INIT;
		coopts.checkout_strategy = GIT_CHECKOUT_FORCE;
		if ((err = git_checkout_head(wt, &coopts)) < 0)
			goto out;
	}
```
But, I found that everything is deleted in the stage, not the unstaged. I don't know how to keep them in the unstaged ( not in the index).

**Comment by alexandre1985** [comment]
how is the progress @Jagroop-Singh ?
I also want to grab a newbie coding issue....

**Comment by Jagroop-Singh** [comment]
@alexandre1985 You can go ahead, I've looked at the code of git/git and no dice on where the code is. I've tried recursive listing with cat, and grepped for the relevant keywords, and following the code has led me in circles.

**Comment by Jagroop-Singh** [comment]
I couldn't find where the logic for --no-checkout exists

**Comment by alexandre1985** [comment]
@Jagroop-Singh I am also stuck there.... 🤔

**Comment by ethomson** [comment]
Looking at this: https://github.com/libgit2/libgit2/blob/e65229ee972c113413eeca77853213352129bd47/src/worktree.c#L406

The way that I would approach this problem is to extend `git_worktree_add_options` to include `git_checkout_options`.

You can look at other functions (like merge) to see this.

**Comment by alexandre1985** [comment]
what is GIT_INIT_STRUCTURE_FROM_TEMPLATE() ?

**Comment by punkymaniac** [comment]
In short, This macro initialise a struct from it's template.

In fact, it simplies memory copy a struct initialiser (define under a `GIT_*_INIT` macro) given as  `TPL` parameter, to a newly created struct (parameter `PTR`) for the given struct type (parameter `TYPE`).
It also verify if the version of the given struct (parameter `VERSION`) is the same as the template (to ensure compatibility I guess).

**Comment by punkymaniac** [comment]
@alexandre1985 Do you still working on it ?

**Comment by alexandre1985** [comment]
A 8 de setembro de 2021 08:26:40 WEST, punkymaniac ***@***.***> escreveu:
***@***.*** Do you still working on it ?
>

I am not
---
Daniel Santos

**Comment by punkymaniac** [comment]
I think this issues could be close since the Pull Request #6062 was successfully merged in the main branch.

**Comment by alexandre1985** [comment]
You may close it

**Comment by ethomson** [comment]
Thanks everybody!
