### ISSUE TITLE
[Config] git_config_find_local is missing.

### ISSUE THREAD

**Issue by lolgear** [libgit2/libgit2#5960]
Function `git_config_find_local` is missing.
Is there any decisions why it is not presented in public API?

I can see private `repo_local_config`.

However, I can't find simple `git_config_find_local`.

```c
int gitup_config_find_local(git_repository *repo, git_buf *path)
{
	assert(repo);

	git_buf_sanitize(path);
	if (git_buf_joinpath(path, repo->gitdir, GIT_CONFIG_FILENAME_INREPO) < 0)
		return -1;

	if (!git_path_exists(path->ptr)) {
		git_error_set(GIT_ERROR_OS, "The config file '%s' doesn't exist", path->ptr);
		return GIT_ENOTFOUND;
	}

	return 0;
}
```

**Comment by ethomson** [comment]
The `git_config_find_` functions are concerned with finding a singular config for the system.  That is to say, `git_config`s don't have a repository.  `git_repository`s have a config.

I think that you're looking for `git_repository_item_path`

**Comment by lolgear** [comment]
Yes, I see.
I'm trying to revive old branch from another OpenSource client.
Issue can be closed.
Thanks!
