### ISSUE TITLE
mbedTLS: Certificate directory is not set correctly using GIT_OPT_SET_SSL_CERT_LOCATIONS

### ISSUE THREAD

**Issue by mikezackles** [libgit2/libgit2#6003]
### Reproduction steps
* Build libgit2 with the mbedTLS backend
* Call `git_libgit2_opts(GIT_OPT_SET_SSL_CERT_LOCATIONS, NULL, path_to_directory)`.

### Expected behavior
The mbedTLS backend should be instructed to load certificates in the requested directory.

### Actual behavior
`git_mbedtls__set_cert_location` is never called (See [here](https://github.com/libgit2/libgit2/blob/c8f4b5699ad0e7f57f0c0b82c1149efc0926e083/src/libgit2.c#L264-L267).)

### Workaround
Call `git_libgit2_opts(GIT_OPT_SET_SSL_CERT_LOCATIONS, "NOT_A_REAL_PATH", path_to_directory)`

### Version of libgit2 (release number or SHA1)
v1.1.1

### Operating system(s) tested
Android

Thanks!

**Comment by ethomson** [comment]
🤔 thanks for the report.  I don't use mbedtls - so a unit test would be exceedingly helpful.  (If you don't want to invest in learning our test framework, I understand.  But a minimal `main` that should succeed but fails would be amazing.)

**Comment by mikezackles** [comment]
Thanks for the prompt reply! I'll take a look at the test stuff. Just to clarify, as best I can tell the bug is just that the directory stuff isn't called unless the file stuff errors out:
```
if (file)
  error = ...
if (error && path) // <- Always fails if file is NULL
  // Code I want to run
```

**Comment by mikezackles** [comment]
On my system the following reproduces the bug with the main branch:
```
mkdir build && cd build
cmake -GNinja -DUSE_HTTPS=mbedTLS -DCERT_LOCATION="$(pwd)" .. # <- needs to be a directory that exists (but not the one that actually has the root CAs)
ninja
cat > main.c <<EOF
#include <git2.h>
#include <stdio.h>
int main(int, char **) {
  int res;
  git_libgit2_init();
  res = git_libgit2_opts(GIT_OPT_SET_SSL_CERT_LOCATIONS, NULL, "/etc/ssl/certs"); // Use appropriate path for your system
  if (res < 0) {
    fprintf(stderr, "Couldn't set cert path");
    return res;
  }
  git_repository *repo;
  res = git_clone(&repo, "https://github.com/libgit2/libgit2", "$(pwd)/libgit2_clone", NULL);
  if (res < 0) {
    git_error const *e = git_error_last();
    fprintf(stderr, "Expected failure: %s", e->message);
    return res;
  }
  git_libgit2_shutdown();
}
EOF
gcc -I../include -Wl,-rpath,. -lgit2 -o repro main.c
./repro
```
Note that the same test succeeds with the branch in my pull request.

I thought about an automated test, but it seems a bit tricky. Here are some approaches I thought of:

* Attempt to clone an online repository over https. Unfortunately the hardcoded CA root directory will make this succeed by default on most systems. But perhaps there is some well-known online repo that is not signed by a trusted CA that could be used for testing?
* Spin up a local https repo for testing using testing certificates. This seems like a good bit of work.
* Call `git_libgit2_opts` and then use mbedtls directly to validate testing certificates. Bypassing libgit2 doesn't feel like a great test
* Something custom in the CI workflows similar to the above script. Again, extra work, but maybe the best approach?

I think the intent of the original code may have been something like `if (error || path)` instead of the offending `if (error && path)` which would be an improvement if my pull request seems like too much.

Thanks, and sorry for all the extra noise over such a small bug. Looking forward to having fun with this lib.

**Comment by mikezackles** [comment]
> Certainly easier than keeping our legitimate certificate up to date.

lol

I misspoke: I think the intent was `if (!error && path)`. In any case, for what it's worth the motivation for the changes in the PR was that in the case that the user provides both a file and a path, both get picked up instead of just one. (But I'm not really sure why someone would want to do that.)
