### ISSUE TITLE
Add `v1.2.0` to Homebrew registry

### ISSUE THREAD

**Issue by patrickdevivo** [libgit2/libgit2#6042]
I apologize if this is not the best place to post this, please let me know if so! I would like to request an update to the [libgit2 Homebrew formula](https://formulae.brew.sh/formula/libgit2), as it currently lists `v1.1.1` as the latest stable release.

I'm happy to open a PR as well! Thanks so much

**Comment by ethomson** [comment]
Hi @patrickdevivo!  I'm afraid that none of the libgit2 core team is involved in Homebrew.  I would encourage you to open a PR against that formula!

**Comment by ethomson** [comment]
(Note that v1.3.0 is coming 🔜 - https://github.com/libgit2/libgit2/pull/6069)

**Comment by patrickdevivo** [comment]
Understood @ethomson and thanks for the heads up! `v1.2.0` appears to have been merged into Homebrew core: https://github.com/Homebrew/homebrew-core/pull/84518 as of now anyways. Will close this out 😃
