### ISSUE TITLE
enum out of range in libgit2 1.2.0

### ISSUE THREAD

**Issue by jeroen** [libgit2/libgit2#6057]
The R bindings require strict ISO C. Compiling the R bindings with `-pedantic` now gives:

```
libgit2-1.2.0/include/git2/diff.h:173:32: warning: ISO C restricts enumerator values to range of 'int' [-Wpedantic]
```

It seems like the bug https://github.com/libgit2/libgit2/issues/4657 has been re-introduced in https://github.com/libgit2/libgit2/pull/5853.

**Comment by ethomson** [comment]
😭  Thanks for letting us know.  We need to catch these in CI...  but `-pedantic` (at least on clang) is insane.  `-Wno-c99-extensions` helps, but if you had some guidance as to how you compile, that would be helpful.
