### ISSUE TITLE
`git_commit_summary` creates too long output for some commits

### ISSUE THREAD

**Issue by ArekPiekarz** [libgit2/libgit2#6065]
### Description
`git_commit_summary` produces too long paragraphs for some commits, like for this one in the Linux repository - https://github.com/torvalds/linux/commit/3218357c94af92478ef39163163a81e654385320. It creates 925 characters long text (almost the whole commit message) instead of 46 characters long (just the first line).

### Reproduction steps
Create a project with following files:

main.cpp:
```c++
#include "deps/libgit2/include/git2.h"
#include <iostream>

int main()
{
    git_libgit2_init();
    const std::string repoPath = "path_to_linux_repository";  // INSERT YOUR OWN

    git_repository* repo = nullptr;
    if (const auto status = git_repository_open(&repo, repoPath.c_str()); status != 0)
    {
        throw std::runtime_error("Failed to open repository at " + repoPath + ", status: " + std::to_string(status));
    }

    git_oid id{};
    if (const auto status = git_oid_fromstr(&id, "3218357c94af92478ef39163163a81e654385320"); status != 0)
    {
        throw std::runtime_error("Failed to create OID, status: " + std::to_string(status));
    }
    git_commit* commit = nullptr;
    if (const auto status = git_commit_lookup(&commit, repo, &id); status != 0)
    {
        throw std::runtime_error("Failed to lookup commit, status: " + std::to_string(status));
    }
    const std::string summary = git_commit_summary(commit);
    std::cout << "git_commit_summary returned (size: " + std::to_string(summary.size()) + "): " << summary << "\n";
    return 0;
}
```
CMakeLists.txt:
```cmake
project(libgit2-commit-summary-test)
cmake_minimum_required(VERSION 3.0)

add_subdirectory(deps/libgit2)
add_executable(${PROJECT_NAME} main.cpp)
target_link_libraries(${PROJECT_NAME} git2)
```
Also download libgit2 as the dependency:
```
mkdir deps && cd deps
git clone https://github.com/libgit2/libgit2.git
cd ..
```
Build and run the project:
```
mkdir build && cd build
cmake ..
cmake --build .
./libgit2-commit-summary-test
```

### Expected behavior
The summary should be: `[MIPS] More uaccess.h fixes with gcc >= 4.0.1.`

### Actual behavior
The summary is:
`[MIPS] More uaccess.h fixes with gcc >= 4.0.1. From Richard Sandiford <richard@codesourcery.com>: This patch caused a miscompilation of the restore_gp_regs() block in restore_sigcontext().  This was in a 32-bit kernel compiled with GCC CVS head. restore_gp_regs() copies 64-bit user fields into 32-bit variables, and in this combination, the new __get_user_asm_ll32() clobbers too many registers.  It says: /* * Get a long long 64 using 32 bit registers. */ {                                                                    \ __asm__ __volatile__(                                         \ "1:   lw      %1, (%3)                                \n"     \ "2:   lw      %D1, 4(%3)                              \n"     \ "     move    %0, $0                                  \n"     \ "3:   .section        .fixup,\"ax\"  \n"      \ "4:   li      %0, %4                                  \n"     \ "     move    %1, $0                                  \n"     \ "    move     %D1, $0                                 \n"     \ "     j       3b                                      \n"     \ "     .previous      \n"      \ "     .section        __ex_table,\"a\"                \n"     \ "     " __UA_ADDR "   1b, 4b                          \n"     \ "    " __UA_ADDR "    2b, 4b                          \n"     \ "     .previous                                       \n"     \ : "=r" (__gu_err), "=&r" (val)                                        \ : "0" (0), "r" (addr), "i" (-EFAULT));                                \ }`

### Version of libgit2 (release number or SHA1)
0a8728622ecf77ce4185139761b31f0c6f77f04e

### Operating system(s) tested
Manjaro

**Comment by ethomson** [comment]
Indeed.  The commit message in https://github.com/torvalds/linux/commit/3218357c94af92478ef39163163a81e654385320 is `message<nl><sp><sp><sp><sp><nl>...`  We should treat two newlines as a paragraph separator even when those two newlines have whitespace in between.

**Comment by PyllrNL** [comment]
The behaviour of the fix does change whether we want to reserve the whitespace characters before the first newline.
Should the first three whitespace characters be preserved in this message: `mesage<sp><sp><sp><nl><sp><sp><sp><nl>....` ?

**Comment by ArekPiekarz** [comment]
The documentation of `git_commit_summary` says:
> The returned message is the summary of the commit, comprising the first paragraph of the message with whitespace trimmed and squashed.

So I believe the whitespace at the end should be removed.

**Comment by PyllrNL** [comment]
Yeah sorry, I posted the question bu re-read the code itself and saw the the behaviour of squashing whitespace at the end was already implemented, so I removed my comment.
