### ISSUE TITLE
http-parser library is unmaintained

### ISSUE THREAD

**Issue by dschepler** [libgit2/libgit2#6074]
The GitHub page for the http-parser library indicates that it is now unmaintained, and suggests llhttp as a replacement to migrate to.  I don't know how much of an impact that would have on libgit2 moving forward; but I thought it might be a good idea for there to be an issue to mark the fact and any thoughts of libgit2 maintainers on implications.

**Comment by ethomson** [comment]
Hi @dschepler - there was some discussion of this over in https://github.com/libgit2/libgit2/discussions/5828.  I'm happy to move to llhttp, but we'd need to port that change in https://github.com/nodejs/http-parser/pull/483 over if it's not there.  This hasn't been a high priority for me, but I'd welcome a PR that moves us over to llhttp if it was something that you were interested in.

**Comment by sgallagher** [comment]
I'm not a subject matter expert for libgit2 OR llhttp, but I've got the beginnings of a patch for this in #6713 
I'd appreciate some help driving it to completion.

**Comment by glaubitz** [comment]
llhttp is part of NodeJS which means that any distribution that packages libgit2 and wants to use the system http parser will no longer be able to build libgit2 on platforms that don't have support for NodeJS.

I don't think this change was wise.

**Comment by glaubitz** [comment]
> llhttp is run by the Node.js project, but it has its own separate releases. Fedora for example ships it as an independent system library. It's not built as part of Node.

Is there a separate upstream repository that does not contain any Javascript code?
 
> Note also that http-parser was also run by the Node.js project and delivered as a separate release in the same way.

Yes, but it was a standalone C package without any additional JavaScript code.

Debian decided to make llhttp part of the [node-undici](https://tracker.debian.org/pkg/node-undici) package which in turn has a build dependency on NodeJS which is not available on all architectures.

So, Debian will have to split llhttp from the node-undici package, although it's unfortunate that upstream didn't split the C from the JavaScript code.

**Comment by ethomson** [comment]
> llhttp is part of NodeJS which means that any distribution that packages libgit2 and wants to use the system http parser will no longer be able to build libgit2 on platforms that don't have support for NodeJS.

I don't understand. Why can't those distributions that don't want to use llhttp just keep using the http-parser that they've been using?

**Comment by sgallagher** [comment]
@glaubitz Just so we're clear, libgit2 didn't *drop* support for http-parser, it just replaced the default with llhttp.

That said, it's a bad idea to keep using http-parser because it's unmaintained and likely has unpatched security vulnerabilities at this point.

**Comment by glaubitz** [comment]
> > llhttp is part of NodeJS which means that any distribution that packages libgit2 and wants to use the system http parser will no longer be able to build libgit2 on platforms that don't have support for NodeJS.
> 
> I don't understand. Why can't those distributions that don't want to use llhttp just keep using the http-parser that they've been using?

Well, Debian just switched back to http-parser because of that for the time being.

> @glaubitz Just so we're clear, libgit2 didn't _drop_ support for http-parser, it just replaced the default with llhttp.

OK.

> That said, it's a bad idea to keep using http-parser because it's unmaintained and likely has unpatched security vulnerabilities at this point.

I agree. But the current situation is still sub-optimal. Upstream should either unbundle llhttp from the Node stuff or libgit2 should use a different http parser library when it wants to stay as portable as it is.

**Comment by glaubitz** [comment]
> > Well, Debian just switched back to http-parser because of that for the time being.
> 
> Ubuntu Security allowed http-parser into the main package archive, but only as a dependency necessity. We strongly prefer llhttp: https://bugs.launchpad.net/ubuntu/+source/http-parser/+bug/1990655/comments/14
> 
> edit: requesting deprecation of http-parser in Ubuntu: https://bugs.launchpad.net/ubuntu/+source/libgit2/+bug/2080872

So, you think it's reasonable having to build `nodejs` which itself has a long list of build dependencies only to be able to build `node-undici` which then embeds `llhttp` which is used for `libgit2` which proclaims itself for being highly portable and lean?

What do you do if an architecture is not supported by NodeJS? Just not build `libgit2` on this architecture?

**Comment by eslerm** [comment]
I am saying it is unreasonable and dangerous to use unmaintained code.

What will happen when a `http-parser` vulnerability is discovered? Since the project is archived, [you cannot even file an issue](https://github.com/nodejs/http-parser/issues). `rustc` depends on `libgit2`..

**Comment by sgallagher** [comment]
> > > Well, Debian just switched back to http-parser because of that for the time being.
> > 
> > 
> > Ubuntu Security allowed http-parser into the main package archive, but only as a dependency necessity. We strongly prefer llhttp: https://bugs.launchpad.net/ubuntu/+source/http-parser/+bug/1990655/comments/14
> > edit: requesting deprecation of http-parser in Ubuntu: https://bugs.launchpad.net/ubuntu/+source/libgit2/+bug/2080872
> 
> So, you think it's reasonable having to build `nodejs` which itself has a long list of build dependencies only to be able to build `node-undici` which then embeds `llhttp` which is used for `libgit2` which proclaims itself for being highly portable and lean?
> 
> What do you do if an architecture is not supported by NodeJS? Just not build `libgit2` on this architecture?

You're doing a lot of arguing for someone who has apparently not actually looked at the implementation here...

When we landed this change, we did so by bringing the generated llhttp.h and llhttp.c content into libgit2: https://github.com/libgit2/libgit2/tree/main/deps/llhttp

Which means that you can ship libgit2 with llhttp support compiled only with GCC/clang and no Node.js dependency. You'd just be using a statically-linked, bundled copy.

If your concern is for distro-packaging, then it's quite easy; most distributions do have Node.js for all architectures they support, and if they don't... they can create an intermediate noarch package where they generate the llhttp.c and llhttp.h on one arch and then build them into the final library on another.

It's really not that complicated.

**Comment by glaubitz** [comment]
> I am saying it is unreasonable and dangerous to use unmaintained code.

Yes, and it's unreasonable to add unnecessary dependencies. It's like having to build Firefox to be able to build glibc.

Bootstrappability is not just something that is nice to have, it's fundamental for distributions.

> What will happen when a `http-parser` vulnerability is discovered? Since the project is archived, [you cannot even file an issue](https://github.com/nodejs/http-parser/issues). `rustc` depends on `libgit2`..

Yes, I know that `rustc` depends on `libgit2`. But thanks to this unclever move, `rustc` also now pointlessly depends on `nodejs`.

> You're doing a lot of arguing for someone who has apparently not actually looked at the implementation here...

I'm arguing from the perspective of a distribution maintainer. A perspective that some upstream projects unfortunately often ignore.

> When we landed this change, we did so by bringing the generated llhttp.h and llhttp.c content into libgit2: https://github.com/libgit2/libgit2/tree/main/deps/llhttp

Embedded code copies have been a no-go for a long time. You cannot be seriously arguing with security and then suggest to use embedded code copies.

See: https://wiki.debian.org/EmbeddedCopies and: https://fedoraproject.org/wiki/Bundled_Libraries

> If your concern is for distro-packaging, then it's quite easy; most distributions do have Node.js for all architectures they support, and if they don't... they can create an intermediate noarch package where they generate the llhttp.c and llhttp.h on one arch and then build them into the final library on another.

Or maybe upstream projects which praise their code to be "lean and mean" shouldn't introduce a pointless dependency on something as big as NodeJS.

> It's really not that complicated.

Well, obviously it is since Debian switched back to `httpparser`.

**Comment by sgallagher** [comment]
> Bootstrappability is not just something that is nice to have, it's fundamental for distributions.

Just so we're clear: my day-job is bootstrapping Red Hat Enterprise Linux releases. I fully understand what this entails.

> > What will happen when a `http-parser` vulnerability is discovered? Since the project is archived, [you cannot even file an issue](https://github.com/nodejs/http-parser/issues). `rustc` depends on `libgit2`..
> 
> Yes, I know that `rustc` depends on `libgit2`. But thanks to this unclever move, `rustc` also now pointlessly depends on `nodejs`.

Your definition of "pointless" would seem to disagree with most dictionaries. The libgit2 project needs a parser for HTTP. The available choices today are

1. http-parser: an abandoned, probably vulnerable C library that is such a mess of code that even the original authors refuse to work on it anymore.
2. llhttp: An actively maintained and meticulously reviewed llparse-based library that can be exported as C code and headers and built as a system library. Yes, to build it directly from TypeScript needs Node.js. If you have arches that can't support that, I recommended an approach in an earlier ticket.

> 
> > You're doing a lot of arguing for someone who has apparently not actually looked at the implementation here...
> 
> I'm arguing from the perspective of a distribution maintainer. A perspective that some upstream projects unfortunately often ignore.

And yet you are ignoring that I'm a distribution maintainer too.


> > When we landed this change, we did so by bringing the generated llhttp.h and llhttp.c content into libgit2: https://github.com/libgit2/libgit2/tree/main/deps/llhttp
> 
> Embedded code copies have been a no-go for a long time. You cannot be seriously arguing with security and then suggest to use embedded code copies.
> 
> See: https://wiki.debian.org/EmbeddedCopies and: https://fedoraproject.org/wiki/Bundled_Libraries

First off, that Fedora wiki page is YEARS out of date. The correct one is https://docs.fedoraproject.org/en-US/packaging-guidelines/#bundling

Modern Fedora is aware that bundling is sometimes unavoidable and provides mechanisms to at least record and monitor which packages are doing so. That said, we (Fedora) don't bundle llhttp. If you want to see how we are building it, they recipe is public: https://src.fedoraproject.org/rpms/llhttp/blob/rawhide/f/llhttp.spec

> > If your concern is for distro-packaging, then it's quite easy; most distributions do have Node.js for all architectures they support, and if they don't... they can create an intermediate noarch package where they generate the llhttp.c and llhttp.h on one arch and then build them into the final library on another.
> 
> Or maybe upstream projects which praise their code to be "lean and mean" shouldn't introduce a pointless dependency on something as big as NodeJS.

Again, you keep using the word "pointless" when you actually mean "mildly inconvenient for me".

> > It's really not that complicated.
> 
> Well, obviously it is since Debian switched back to `httpparser`.

Debian maintainers make their own decisions. And I'll point out that they did so as a temporary measure while they properly package llhttp (which is a completely reasonable thing to do).

**Comment by ethomson** [comment]
@glaubitz can you please describe the change that you would like to see in this project? Use small words so that I can understand and knock off the pointless bickering, please.

**Comment by glaubitz** [comment]
> > Bootstrappability is not just something that is nice to have, it's fundamental for distributions.
> 
> Just so we're clear: my day-job is bootstrapping Red Hat Enterprise Linux releases. I fully understand what this entails.

Then I'm even more surprised that you're refusing to understand what the problem is here. Or your definition of bootstrap is a different one than mine. Real bootstrapping starts completely from source and introducing build dependencies like these makes it incredibly more harder.

Moreover, if you are involved in this job, you'd share my point of view and not brush it off.

> > > What will happen when a `http-parser` vulnerability is discovered? Since the project is archived, [you cannot even file an issue](https://github.com/nodejs/http-parser/issues). `rustc` depends on `libgit2`..
> > 
> > 
> > Yes, I know that `rustc` depends on `libgit2`. But thanks to this unclever move, `rustc` also now pointlessly depends on `nodejs`.
> 
> Your definition of "pointless" would seem to disagree with most dictionaries. The libgit2 project needs a parser for HTTP. The available choices today are

You well aware know that this comment refers to NodeJS. It introduces a transitive build dependency which is actually not needed because someone at Node thought it would be a good idea to make a C library part of a Node package even though they're both unrelated.

Thus, you have to build NodeJS and then the Node package just to get the C library despite the fact that the C library is unrelated to the Node package.

>     1. http-parser: an abandoned, probably vulnerable C library that is such a mess of code that even the original authors refuse to work on it anymore.
> 
>     2. llhttp: An actively maintained and meticulously reviewed llparse-based library that can be exported as C code and headers and built as a system library. Yes, to build it directly from TypeScript needs Node.js. If you have arches that can't support that, I recommended an approach in an earlier ticket.

This is not the point of the discussion. You're arguing against a strawman here.

> > > You're doing a lot of arguing for someone who has apparently not actually looked at the implementation here...
> > 
> > 
> > I'm arguing from the perspective of a distribution maintainer. A perspective that some upstream projects unfortunately often ignore.
> 
> And yet you are ignoring that I'm a distribution maintainer too.

Yet, you don't understand that being able to bootstrap completely from source and being able to avoid pointless build dependencies is an important feature. You wouldn't accept a build dependency of glibc on Firefox either, yet you think that rustc transitively build-depending on NodeJS is a clever thing to do.

> > > When we landed this change, we did so by bringing the generated llhttp.h and llhttp.c content into libgit2: https://github.com/libgit2/libgit2/tree/main/deps/llhttp
> > 
> > 
> > Embedded code copies have been a no-go for a long time. You cannot be seriously arguing with security and then suggest to use embedded code copies.
> > See: https://wiki.debian.org/EmbeddedCopies and: https://fedoraproject.org/wiki/Bundled_Libraries
> 
> First off, that Fedora wiki page is YEARS out of date. The correct one is https://docs.fedoraproject.org/en-US/packaging-guidelines/#bundling
> 
> Modern Fedora is aware that bundling is sometimes unavoidable and provides mechanisms to at least record and monitor which packages are doing so. That said, we (Fedora) don't bundle llhttp. If you want to see how we are building it, they recipe is public: https://src.fedoraproject.org/rpms/llhttp/blob/rawhide/f/llhttp.spec
> 
> > > If your concern is for distro-packaging, then it's quite easy; most distributions do have Node.js for all architectures they support, and if they don't... they can create an intermediate noarch package where they generate the llhttp.c and llhttp.h on one arch and then build them into the final library on another.
> > 
> > 
> > Or maybe upstream projects which praise their code to be "lean and mean" shouldn't introduce a pointless dependency on something as big as NodeJS.
> 
> Again, you keep using the word "pointless" when you actually mean "mildly inconvenient for me".

You are intentionally misinterpret what I say. The term "pointless" refers to NodeJS which is a pointless build dependency in this case.

Should Firefox be a build dependency for glibc? Should the Linux kernel build depend on Libre Office? Would that be acceptable for you as distribution maintainer, because, hey, Firefox and LibreOffice are supported on the architectures you care about?

> > > It's really not that complicated.
> > 
> > 
> > Well, obviously it is since Debian switched back to `httpparser`.
> 
> Debian maintainers make their own decisions. And I'll point out that they did so as a temporary measure while they properly package llhttp (which is a completely reasonable thing to do).

The reasonable thing to do is for Node upstream to untie a C library from an unrelated Node package.

**Comment by glaubitz** [comment]
> @glaubitz can you please describe the change that you would like to see in this project? Or perhaps better the outcome that you want and why you can't get there after this change. Can you describe this simply for me, because this thread has become confusing and I'm having trouble teasing out what the problem is.

My first comment was to make you aware of the problem. Unfortunately, the first replies I got were in the form of "We don't care, please go away" or "Fedora and Ubuntu are much smarter, we don't have this problem, please go away" which is why I'm mildly annoyed by this discussion.

> Because _I_ think the problem is "I build libgit2, I have an existing package for http-parser, I want to use that and not use llhttp". And so I must not be understanding what you want.

No, the problem is that someone at Node thought it would be a good idea to mangle a portable C library into a Node package so that distributions that want to use the C library have to build NodeJS to be able to build the NodeJS package containing the C library. This introduces a new build pointless build dependency on NodeJS which is otherwise not required to build the C library.

The proper solution would be to convince the maintainer of the `llhttp` package to unbundle the C library from the Node package.

**Comment by ethomson** [comment]
We're talking past each other. You're talking about llhttp and bundling, which is not something in my control.

Can you describe the outcome that you want _from libgit2_? We made a change that should have zero impact upon you.

There's a very long and increasingly heated thread about this change, so please help me understand how I can help you.

**Comment by glaubitz** [comment]
As I said, NodeJS upstream needs to be convinced to unbundle `llhttp` from the Node stuff and I think this should have happened before switching `libgit2` over. But I'll file a bug report there.

**Comment by ethomson** [comment]
No, let's back up. Why does that need to happen? http-parser is unbundled. Why can't you use that?

**Comment by dschepler** [comment]
@glaubitz I'm not sure what more needs to be done to unbundle `llhttp`.  As far as I can tell, https://github.com/nodejs/llhttp is already self-contained and does not require nodejs to build.

**Comment by ethomson** [comment]
@dschepler please can we keep this issue focused on libgit2? Unbundling llhttp is far outside the scope of this project. This issue is convoluted enough already, I'd like to focus it.
