### ISSUE TITLE
`git_merge_file` return unexpected char on `result.ptr` with small input file content.

### ISSUE THREAD

**Issue by punkymaniac** [libgit2/libgit2#6085]
`git_merge_file` return unexpected random char on `result.ptr` with small file content.
When the input `theirs.ptr` is lower than 6 chars, some random character appear at the end on the result `ptr` content.

### Short investigation
The issue came from the internal function `xdl_merge`.
So here, the call to `xdl_malloc` return an memory block who is not set to zero.
This is not a big problem, but the new allocated memory could contains (each time for me) some random char.
So the buffer copied could not erase all of it and the returned `ptr` contain these unexpected char.
 
https://github.com/libgit2/libgit2/blob/b7bad55e4bb0a285b073ba5e02b01d3f522fc95d/src/xdiff/xmerge.c#L718-L742

### Impacted function
* git_merge_file
* git_merge_file_from_index

### Reproduction steps
Copy, compile and execute the following code:

```c
#include <unistd.h>
#include <stdio.h>
#include <git2.h>

int main(void)
{
    int libRet;
    git_repository *repo;

    git_libgit2_init();

    git_repository_init(&repo, "./test_repo", 0);

    git_merge_file_input ancestor = GIT_MERGE_FILE_INPUT_INIT,
                         ours = GIT_MERGE_FILE_INPUT_INIT,
                         theirs = GIT_MERGE_FILE_INPUT_INIT;
    git_merge_file_result result = {0};

    ancestor.ptr = "0 10";
    ancestor.size = strlen(ancestor.ptr);
    ancestor.path = "testfile.txt";
    ancestor.mode = 0100755;

    ours.ptr = "0 10";
    ours.size = strlen(ours.ptr);
    ours.path = "testfile.txt";
    ours.mode = 0100755;

    theirs.ptr = "0 Ten";
    theirs.size = strlen(theirs.ptr);
    theirs.path = "testfile.txt";
    theirs.mode = 0100755;

    libRet = git_merge_file(&result, &ancestor, &ours, &theirs, 0);

    printf("libRet: %d\n", libRet);
    printf("ptr: [%s]\n", result.ptr);
    printf("len: %ld\n", result.len);

    git_repository_free(repo);
    git_libgit2_shutdown();

    return (0);
}
```
### Expected behavior
Expected output
```
libRet: 0
ptr: [0 Ten]
len: 5
```
### Actual behavior
Actual output
```
libRet: 0
ptr: [0 TenV] # 'V' is for example it could be a random char
len: 5
```
### Version of libgit2 (release number or SHA1)
* v1.3.0 b7bad55e4bb0a285b073ba5e02b01d3f522fc95d

### Operating system(s) tested
* linux (debian 10.10)

**Comment by ethomson** [comment]
Do we guarantee that we NUL terminate `git_merge_file_result`?  I would have thought not.  This file could certainly be binary.  That's why we give you the length.

**Comment by ethomson** [comment]
In other words:

```c
    printf("libRet: %d\n", libRet);
    printf("ptr: [%.*s]\n", (int)result.len, result.ptr);
    printf("len: %ld\n", result.len);
```

should give you the expected behavior.

**Comment by punkymaniac** [comment]
Okay, so this is a normal behaviour.
Sorry about that.
