### ISSUE TITLE
Multiline config values not preserved

### ISSUE THREAD

**Issue by Uncommon** [libgit2/libgit2#6088]
When a multiline config value is written back out, only the first line is written, including the backslash.

Originally reported in Uncommon/Xit#461

### Reproduction steps

Parse a config file with this in it:
```
[alias]
    echo = !echo "this \
        is some text"
```
..and write it back out again.

### Expected behavior

The value should be written just as it was.

### Actual behavior

Only the first line of the value is written:
```
[alias]
    echo = !echo "this \
```

### Version of libgit2 (release number or SHA1)

1.3.0

### Operating system(s) tested

macOS 11.4

**Comment by ethomson** [comment]
Fixed via #6124
