### ISSUE TITLE
config parsing confused by continuations that start with quotes

### ISSUE THREAD

**Issue by ehuss** [libgit2/libgit2#6089]
### Reproduction steps

Create a `.gitconfig` with the following content and attempt to load it with libgit2:

```
[alias]
	myalias2 = cmd \
";;" \
";;" \
bar
```

Note that the indentation here is important, the quotes must start at the beginning of the line.

### Expected behavior

The value should parse to `cmd ;; ;; bar`

### Actual behavior

Fails with `invalid configuration key`

### Version of libgit2 (release number or SHA1)

1.3.0 (b7bad55e4bb0a285b073ba5e02b01d3f522fc95d)

### Operating system(s) tested

macOS

### Notes

I did some investigation and hit [this line](https://github.com/libgit2/libgit2/blob/b7bad55e4bb0a285b073ba5e02b01d3f522fc95d/src/config_parse.c#L39) in `strip_comments` which has a test `ptr > line` which prevents it from detecting quotes that start on the beginning of the line.  I think something like the following will fix it:

```diff
diff --git a/src/config_parse.c b/src/config_parse.c
index 9f95e67d7..2cd57908f 100644
--- a/src/config_parse.c
+++ b/src/config_parse.c
@@ -36,7 +36,7 @@ static int strip_comments(char *line, int in_quotes)
 	char *ptr;

 	for (ptr = line; *ptr; ++ptr) {
-		if (ptr[0] == '"' && ptr > line && ptr[-1] != '\\')
+		if (ptr[0] == '"' && ((ptr > line && ptr[-1] != '\\') || ptr == line))
 			quote_count++;

 		if ((ptr[0] == ';' || ptr[0] == '#') &&
```

**Comment by ethomson** [comment]
Fixed via #6124
