### ISSUE TITLE
pushInsteadOf is ignored without pushurl

### ISSUE THREAD

**Issue by mkhl** [libgit2/libgit2#6099]
### Reproduction steps
1. clone a repo via https, say `https://github.com/user/repo`
2. configure `pushInsteadOf`, say
    ```
    [url "git@github.com:user/"]
        pushInsteadOf = "https://github.com/user/"
    ```
3. using libgit2, lookup the remote using `git_remote_lookup`
4. check the push url using `git_remote_pushurl`
5. push using `git_remote_push`

### Expected behavior
* the pushurl is `git@github.com:user/repo`
* the push succeeds without additional credentials

### Actual behavior
* the pushurl is null
* the push requires credentials

### Version of libgit2 (release number or SHA1)
e61abdce434e17104b40c09b34094e2d571ba9e9
(used by git2-rs)

### Operating system(s) tested
Linux, Fedora 34

**Comment by ethomson** [comment]
Fixed by #6101
