### ISSUE TITLE
Missing read the port number from ssh url

### ISSUE THREAD

**Issue by brew0722** [libgit2/libgit2#6110]
You are opening a _bug report_ against the libgit2 project: we use
GitHub Issues for tracking bug reports and feature requests.  If you
have a question about an API or usage, please ask on StackOverflow:
http://stackoverflow.com/questions/tagged/libgit2.  If you want to
have high-level discussions about the libgit2 project itself, visit
https://github.com/libgit2/discussions.

Otherwise, to report a bug, please fill out the reproduction steps
(below) and delete these introductory paragraphs.  Thanks!

### Expected behavior
Expect `git_ssh_extract_url_parts` to parse up to port number.
should be able to connect to ssh not using the default port.

e.g) ssh://[user@]host.xz[:port]/path/to/repo.git/
https://git-scm.com/docs/git-clone#_git_urls

### Actual behavior
Not setting urldata.port in `git_ssh_extract_url_parts`.
It seems just parse a scp-like syntax case only.
https://github.com/libgit2/libgit2/blob/44ec8b5cdf960cfeb66284a3cd5bdd8c14aefedf/src/transports/ssh.c#L261

So, `_git_ssh_setup_conn` can only connect to port 22, which is the default.
https://github.com/libgit2/libgit2/blob/44ec8b5cdf960cfeb66284a3cd5bdd8c14aefedf/src/transports/ssh.c#L545

### Operating system(s) tested

- [ ]

**Comment by ethomson** [comment]
To clarify, you mention SSH URLs:

> e.g) ssh://[user@]host.xz[:port]/path/to/repo.git/

but we're actually talking about scp style paths with a port number, a la https://github.com/libgit2/libgit2/issues/6163, is that correct?  We should be able to parse an actual URL (and our CI runs ssh on a nonstandard port to verify this).

**Comment by ethomson** [comment]
Marking this a dup of #6163 which will be fixed 🔜
