### ISSUE TITLE
Respect textconv for binary diff

### ISSUE THREAD

**Issue by albfan** [libgit2/libgit2#6126]
### Reproduction steps

- Install xls2csv  (turn xls files into csv text files)
- Unzip attached example repo [libgit2-diff-attributes.zip](https://github.com/libgit2/libgit2/files/7616420/libgit2-diff-attributes.zip) which is configured to compare binary xls files as text (using xls2scv) and contains a xls file with a modification.
- 
```
$ unzip libgit2-diff-attributes.zip

$ cd libgit2-diff-attributes

$ cat .gitattributes 
*.xls diff=xls

$ git config --get diff.xls.textconv
xls2csv
```

With this config, git correctly compares xls changes as text:

```
$ git show
commit 223f9e306223dc93b47e4dbc5e03490f948b307c (HEAD -> master)

    change xls file

diff --git a/file.xls b/file.xls
index 546063f..00ad111 100644
--- a/file.xls
+++ b/file.xls
@@ -1,2 +1,2 @@
-"foo","bar"
+"baz","qux"
 ^L
\ No newline at end of file
```

I tried with the diff example provided and it compares as binary:

```
$ ~/projects/c/libgit2/build/examples/lg2 diff HEAD^
diff --git c/file.xls i/file.xls
index 546063f..00ad111 100644
Binary files c/file.xls and i/file.xls differ
```

### Expected behavior

Seing issues like https://github.com/libgit2/libgit2/issues/5655, looks like .gitattributes is honored for some config, but is not the case for diff in textconv

### Actual behavior

binary diffs are not compared as text if gitattributes textconv is setup. Is there any additional setup not included in diff example but supported by libgit2?

### Version of libgit2 (release number or SHA1)

Tested from master 358a60e1b46000ea99ef10b4dd709e92f75ff74b

### Operating system(s) tested

Linux

**Comment by ethomson** [comment]
libgit2 doesn't run external programs; you can imagine that this would be a significant attack vector for hosting platforms if we did.

If this is something that is safe for your application to do, then you'll need to handle `textconv` yourself.  I'd like to make this easier for consumers, so if there is an API that will help you then I'd be happy to give that some more thought.

**Comment by albfan** [comment]
Sure , just double checking before implementing on gitg.
libgit2 already have patch API to generate diff so all plumbing are there (attr, config, patch)
