### ISSUE TITLE
Turn "Conflicts:" hint into a comment

### ISSUE THREAD

**Issue by cjolowicz** [libgit2/libgit2#6131]
When a merge conflict occurs, libgit2 inserts a "Conflicts:" hint into `.git/MERGE_MSG`. Unlike git >= 2.3.0, this hint does not use comment markers. If the user does not edit the conflict block, it ends up in the commit message after conflict resolution.

Would you consider a PR changing the behavior to match that of git? These days, users don't expect to need to edit the conflict block in a merge message, for example when cherry-picking. So this seems to be a frequent oversight (definitely for myself 🙃 ).

Here's the relevant section of libgit2's source code:

https://github.com/libgit2/libgit2/blob/6fdb1b2f55da9593576b096ee2eecce61995fb51/src/merge.c#L3129-L3141

The current behavior of libgit2 also used to be the behavior of git before v2.3.0. It was changed in https://github.com/git/git/commit/261f315bebfa9af2d09f20211960100ff06f87cb, which cites the following reasons:

> Just like other hints such as "Changes to be committed" we show in the editor to remind the committer what paths were involved in the resulting commit to help improving their log message, this section is merely a reminder.
>
> Traditionally, it was not made into comments primarily because it has to be generated outside the wt-status infrastructure, and also because it was meant as a bit stronger reminder than the others (i.e. explaining how you resolved conflicts is much more important than mentioning what you did to every paths involved in the commit).
>
> But that still does not make this hint a part of the log message proper, and not showing it as a comment is inviting mistakes.
>
> Note that we still notice "Conflicts:" followed by list of indented pathnames as an old-style cruft and insert a new Signed-off-by: before it.  This is so that "commit --amend -s" adds the new S-o-b at the right place when used on an older commit.

### Reproduction steps

- TBD

### Expected behavior

- Use comment markers in the conflict block in `.git/MERGE_MSG`.

### Actual behavior

- The conflict block does not use comment markers.

### Version of libgit2 (release number or SHA1)

- 1.3.0

### Operating system(s) tested

- macOS

**Comment by ethomson** [comment]
Yes, we should fix this to match git's behavior.

**Comment by cjolowicz** [comment]
Thank you @ethomson !
