### ISSUE TITLE
crash on malformed includeif

### ISSUE THREAD

**Issue by ehuss** [libgit2/libgit2#6162]
### Reproduction steps
Include the following in a git config file (global or in `.git/config`):

```ini
[includeif]
    path = doesnotexist
```

And attempt to open a repository.

### Expected behavior
Returns an error that the config file is malformed (the `includeif` is missing the condition).

### Actual behavior
Segmentation fault (SIGSEGV) dereferencing a null pointer.

### Version of libgit2 (release number or SHA1)
50b4d53ef3897fd4066cd74734f4a6e141a64201

### Operating system(s) tested
Any

### Notes
The problem is this line:

https://github.com/libgit2/libgit2/blob/50b4d53ef3897fd4066cd74734f4a6e141a64201/src/config_file.c#L733-L734

There are two problems here. One is that the size calculation goes negative because the length of "includeIf..path" is longer than "includeif.path" (resulting in a size of 18446744073709551615 on 64-bit systems).  The second is that it doesn't check for a NULL return from strdup.

Ideally it should check for a missing condition and return an error.  It should also check for a NULL return.

**Comment by ethomson** [comment]
Yikes, thanks for the helpful analysis.  Fixed in #6165.
