### ISSUE TITLE
git_remote_callbacks: Using a repo URL formatted with square brackets results in malformed credentials

### ISSUE THREAD

**Issue by Cottser** [libgit2/libgit2#6163]
Hi there, I'm coming from https://github.com/extrawurst/gitui/issues/916 so please see there for some additional context. I can try to provide additional context/information as needed here but I hope this report is fairly clear.

### Reproduction steps

When using [git_remote_callbacks](https://libgit2.org/libgit2/#HEAD/type/git_remote_callbacks) with a repository URL formatted like `[git@github.com:22]:extrawurst/gitui.git`, the `credentials` field will return a malformed result.

### Expected behavior

`credentials` should be returning `git` in this case (stripping/removing the square brackets).

### Actual behavior

`credentials` field returns `[git`.

### Version of libgit2 (release number or SHA1)

Sorry, not sure.

### Operating system(s) tested

Linux (Ubuntu-like) and macOS.

**Comment by ethomson** [comment]
The syntax is entirely new to me.  Is it documented somewhere?

**Comment by Cottser** [comment]
Great question! I cannot find this syntax documented anywhere, https://git-scm.com/docs/git-fetch#URLS doesn't mention it at all.

I may have found the commit that added this syntax to GitLab, but it was originally intended to handle IPv6 addresses, not non-standard SSH ports. https://gitlab.com/gitlab-org/gitlab/-/commit/0ed4ae7295ef1cf5d3a63be64315738a19a178b1

I can't speak to why the GitLab instance I'm using is exhibiting this behaviour - it could very well be a misconfiguration based on my reading of the GitLab code. The repo URL works with git itself, but that may not be intentional.

**Comment by ethomson** [comment]
Yeah, I was quite wondering about how this interacts with IPv6 (which I think that we're deficient in parsing.)  scp requires square brackets for SSH addresses.  So I'm wondering if `[git@[::1]:2222]:extrawurst/gitui.git` is also legal.  Like many things, I suspect that this may be a time when we have to trial and error against git to figure it out.

**Comment by ethomson** [comment]
Amusingly, `[git@::1]:path` is legal, `[git@localhost:22]` is legal, but to the best of my knowledge there's no way to specify user, host _and_ port for an IPv6 address in git.

You would think that `[git@[::1]:22]:path` would be the way to disambiguate this, but that (amusingly) treats the username as `[git`, just like our parsing failures.  🙃

**Comment by Cottser** [comment]
Thank you! 🎉
