### ISSUE TITLE
multi-pack-index parsing performance problem

### ISSUE THREAD

**Issue by rcoup** [libgit2/libgit2#6166]
Reading anything from a larger multi-pack index files takes many seconds because libgit2 is spending its time verifying the index is valid.

cc @lhchavez 

### Reproduction steps

Assemble a GB-sized multi-pack-index

```
$ ls -lah objects/pack/
total 35G
drwxrwxr-x  5 rcoup staff  160 Dec 23 14:26 .
drwxrwxr-x 14 rcoup staff  448 Dec 23 13:40 ..
-rw-rw-r--  1 rcoup staff 3.5G Dec 23 13:34 multi-pack-index
-rw-rw-r--  1 rcoup staff 3.5G Dec 23 13:34 pack-956a7569baf4cc7ef8a89d986eb5e6bc43101910.idx
-rw-rw-r--  1 rcoup staff  28G Dec 23 13:35 pack-956a7569baf4cc7ef8a89d986eb5e6bc43101910.pack
```

Simple reproducer to look up an object in the pack file:

**`bug-slow-lookup-mvt.c`**
```c
#include <assert.h>
#include <stdio.h>

#include "git2.h"

int main(int argc, char *argv[]) {
  git_libgit2_init();

  git_repository *repo = NULL;

  assert(git_repository_open(&repo, argv[1]) == 0);

  git_object *obj;
  const git_oid *oid;

  git_reference *ref = NULL;
  assert(git_reference_lookup(&ref, repo, "HEAD") == 0);

  assert(git_reference_peel(&obj, ref, GIT_OBJECT_TREE) == 0);
  oid = git_object_id(obj);
  printf("%s\n", git_oid_tostr_s(oid));
}
```

```console
$ cc -g -o bug-slow-lookup-mvt bug-slow-lookup-mvt.c -Lbuild -Iinclude -lgit2 -Wl,-rpath,$(pwd)/build
$ time ./bug-slow-lookup-mvt /path/to/repo
ed3d59fccf5f5d40a52c12911f265b1835e801a1

real	0m49.401s
user	0m41.887s
sys	0m2.353s
```

### Expected behavior

The lookup is completed in a few milliseconds.

### Actual behavior

😴 

From profiling:
1. 99.9% of the time is parsing the multi-pack-index file
2. ~95% is [hashing the index data](https://github.com/libgit2/libgit2/blob/e2e3f3e4cde7871f86eabacc6a639439b70a8fc7/src/midx.c#L216) to generate the checksum signature. SHA1 CollisionDetect is slow, switching to CommonCrypto/OpenSSL is about 75% faster. Generic is 20% faster. Still slow.
3. The other ~4.5% is spent [checking the index is sorted monotonically](https://github.com/libgit2/libgit2/blob/e2e3f3e4cde7871f86eabacc6a639439b70a8fc7/src/midx.c#L129)

Commenting out the above two steps gets the same reproducer well under 100ms.

While it's probably possible to optimise (2) to be faster for large buffers, Git [doesn't perform either of those verification steps when loading a multi pack index](https://github.com/git/git/blob/master/midx.c#L84) — it is only part of `git multi-pack-index verify` / [`verify_midx_file()`](https://github.com/git/git/blob/master/midx.c#L1569).

I suggest libgit2 does the same — punting everything that isn't **required** for reading the index into a `git_midx_verify()` function, or activating it via a parameter to `git_midx_open()`/`git_midx_parse()`/etc.

### Version of libgit2 (release number or SHA1)

e2e3f3e4cde7871f86eabacc6a639439b70a8fc7 (main > 1.3.0)

### Operating system(s) tested

macOS 11.6.2 x86_64
Originally found on Linux

**Comment by ethomson** [comment]
Fixed in #6291 - thanks for the report!
