### ISSUE TITLE
libssh not found on head (but works with 1.3.0)

### ISSUE THREAD

**Issue by axkibe** [libgit2/libgit2#6170]
I cloned git head and tried to build it, out of some reason it just cannot find libssh2 (but libssh2-1-dev is installed). However it does work as expected out of the box when downloading libgit2-1.3.0.tar.gz so it must have been recently broken 

### Reproduction steps

mkdir build
cmake ..

### Expected behavior

cmake  find SSH, SSH transport support

### Actual behavior

-- Disabled features:
 ...
 * SSH, SSH transport support

### Version of libgit2 (release number or SHA1)

e2e3f3e4cde7871f86eabacc6a639439b70a8fc7

### Operating system(s) tested

debian bullseye

**Comment by axkibe** [comment]
Okay it's just disabled now (I guess there was some reason for that)
It was only confusing since it reports it as not found instead of disabled as per (default) choice.
PR to make this more intuitive.

**Comment by ethomson** [comment]
Thanks for the update - going to close this since you have a PR to improve the messaging.

**Comment by axkibe** [comment]
It ain't merged tough.
