### ISSUE TITLE
"invalid version 0 on git proxy options" when cloning repository

### ISSUE THREAD

**Issue by mseld2** [libgit2/libgit2#6172]
### Reproduction steps
1.  Set up `git_clone_options` not using a proxy, with or without authentication.
2.  Clone remote repository using `git_clone`

### Expected behavior
The repository is cloned without error.

### Actual behavior
The repository isn't cloned. An error is returned:
*  `giterr_last()->klass` = 3
*  `giterr_last()->message` = "invalid version 0 on git proxy options"

### Version of libgit2 (release number or SHA1)
v1.2.0 and v1.3.0

### Operating system(s) tested
Windows, Ubuntu, and Mac. 

#### CPU architecture
amd64
#### Compilers
GCC 11 (Ubuntu and Mac), clang 11 (Windows and Ubuntu), Visual Studio (Windows)

*  Initially, I used libgit2 v1.3.0 installed with Homebrew (`brew install libgit2`) on Mac, but the error occurred, so I built it myself.  
*  I never tried building it with (Apple) clang.

### Note
The error occurs starting with commit: 16a2e6676f531ae3948036b4d3af39e3a27fd0c8. I reverted part of that commit _remote: introduce git_remote_ready_cb_ (72df17c659619707e4e5f27b2a51db60848a1d04). The error no longer occurs in v1.20 or v.1.30. Everything else seems to be working fine (i.e., unit tests and integration tests pass).

![proxy_opts_version](https://user-images.githubusercontent.com/25728622/149303583-189d4357-f6b3-49f8-84b9-41fa89c2bb1a.png)

**Comment by ethomson** [comment]
> Set up git_clone_options not using a proxy, with or without authentication.

What does setting it up look like?  Are you using `GIT_CLONE_OPTIONS_INIT` or `git_clone_options_init()`?

Can you post a snippet of sample code that reproduces this?  It's very not obvious how https://github.com/libgit2/libgit2/commit/72df17c659619707e4e5f27b2a51db60848a1d04 would have affected this unless you're using some FFI where you need to redefine our memory layout (like PInvoke or rust's FFI) but it sounds like this isn't the case for you since you mentioned gcc and Visual Studio?  🤔

**Comment by mseld2** [comment]
I'm using `GIT_CLONE_OPTIONS_INIT`. I also tried with `git_clone_options_init()`. I tried explicitly initializing `git_proxy_options` with `GIT_PROXY_OPTIONS_INIT`, as well as `git_proxy_init_options()`. I did lots of experimenting in my code and libgit2.

I'm not very familiar with the codebase, but I read that commit carefully. It's very self-contained and there's no funny business going on. I'm sure how it would cause this type of problem.

I've attached the code that causes the issue. The code is cross-platform. I don't use any libraries like Qt or Boost. It's just normal C++ 17. I usually use clang, but thought maybe that was causing an issue, so I tried with GCC (on Ubuntu) and Visual Studio (on Windows). 

`writeError()` is just so the error prints. It's normally not there, but it doesn't make a difference whether or not it's there.

[git_repo_impl.zip](https://github.com/libgit2/libgit2/files/7863077/git_repo_impl.zip)

**Comment by mseld2** [comment]
For me, this issue is a deal-breaker because I cannot clone a repository at all. I would go to a previous version, but the new version provides support for additional SSH key types, which is important for my use case. I'm not sure if this is the proper thing to do, but...until the issue is **_resolved officially_**, a (rough) workaround for the handful of others that have encountered this issue is available here. **It's NOT official. It's not my fault if something goes wrong.**

*  v1.3.0 with modification: https://github.com/mseld2/libgit2/tree/v1.3.0_mod
*  v1.2.0 with modification: https://github.com/mseld2/libgit2/tree/v1.2.0_mod

**Comment by ethomson** [comment]
There's no funny business going on in https://github.com/libgit2/libgit2/commit/16a2e6676f531ae3948036b4d3af39e3a27fd0c8, but what it does do is add a pointer to `git_remote_callbacks`, which would increase the offset of your `git_proxy_options` by the size of a pointer.  Your debugger screenshot on the right shows everything lining up correctly with what you set (eg, `update_fetchhead` is `1`).  Your screenshot on the left shows everything misaligned.

Reverting that change and rebuilding libgit2 would make the options structs align again with what you're defining, but why are they misaligned in the first place?

Are you perhaps including a different `git2.h` (and friends) than the ones that are included with the libgit2 that you're linking against?

If not, can you show me a full memory dump of your options structure?

**Comment by ethomson** [comment]
Wait, it adds _two_ pointers.  🤔  I'm rather stumped.

I can't compile your file since I'm missing a bunch of extra funny business, but reproducing the initialization in a simple C program, I was _not_ able to reproduce this.  But I would worry that that's not particularly meaningful - if I could reproduce it like that, I would expect that our tests and example code would all be susceptible to this.

**Comment by mseld2** [comment]
Ugh. I don't know what to say. There's no _"I'm going to put my tail between my legs now and walk away slowly like this never happened"_ emoji. `git2.h` (and friends) weren't the ones included with v1.2.0 or v1.3.0. They were from v1.1.1. The shame.

I really, really appreciate the time you took to look into this. 

Again, thanks for the help.

**Comment by ethomson** [comment]
Oh thank goodness!  😅

I'm really happy to hear that.  I have done precisely the same thing when vendoring libgit2, and I was reminded of that while I was absentmindedly making a sandwich.  So I was very hopeful that it might be the same thing here.  Thanks for the update!

**Comment by vitalyster** [comment]
For people who came from search engines: I had the same issue but it happened in Mac sandboxed application, and error is gone when I allow "Outgoing connections (Client)" in app sandbox options.
