### ISSUE TITLE
Environment Variables for config paths are not considered

### ISSUE THREAD

**Issue by michha** [libgit2/libgit2#6182]
### Reproduction steps
- set `GIT_CONFIG_GLOBAL` to `C:\work\.gitconfig`

### Expected behavior
- git_config_find_global should respect the environment variables

### Operating system(s) tested
- Windows

### What else to say
- I use the [git-tfs](https://github.com/git-tfs/git-tfs/) tool that is using the [LibGit2Sharp](https://github.com/libgit2/libgit2sharp) Library, but I am confident, that the underlying problem is in this repo. Feel free to correct me 😄 
- https://git-scm.com/docs/git-config#_environment - Documentation about the environment variables
- Probably `GIT_CONFIG_GLOBAL` and `GIT_CONFIG_NOSYSTEM` should also be considered in future versions

**Comment by michha** [comment]
Any comment on this issue?

**Comment by ethomson** [comment]
It needs a motivated hacker to send a pull request. I'm happy to talk about the structure of the changes and the best path forward with someone who wants to tackle this. Do you want to work on this?

**Comment by clnoll** [comment]
Hi @ethomson, I've opened a [PR](https://github.com/libgit2/libgit2/pull/6399) that should fix this but would like feedback on the approach when you've got time.
