### ISSUE TITLE
Handle symlinks in .git directory

### ISSUE THREAD

**Issue by rrevans** [libgit2/libgit2#620]
libgit2 clobbers symlinks in the .git directory instead of updating the linked file.

This behavior is incompatible with tools like git's [contrib/workdir/git-new-workdir](https://github.com/gitster/git/blob/master/contrib/workdir/git-new-workdir).  This tool uses symlinks to create a new working directory for an existing git repository.  Most of the metadata files become symlinks to another .git directory (except HEAD).  This setup works with git but not libgit2 because git's file update implementation honors symbolic links.

git_filebuf_open should resolve symbolic links (including nested links) when opening files for writing.  See git's implementation in [lockfile.c](https://github.com/gitster/git/blob/master/lockfile.c#L80).

**Comment by carlosmn** [comment]
Fixed with #3413
