### ISSUE TITLE
odb writes can fail silently

### ISSUE THREAD

**Issue by dan-tull** [libgit2/libgit2#6201]
### Reproduction steps
Fault injection would be required to repro directly, this issue was noted by code inspection to diagnose a failure we saw in the field. We use a unified custom refs and odb backend (an append only file) and saw a situation where the most recent refs were missing some blobs and trees that had silently failed to be written. We believe an out of disk space condition may have been involved (which fits with the refs succeeding even after the blobs failed).

Code inspection: https://github.com/dan-tull/libgit2/blob/master/src/odb.c#L1322

> stream->write(stream, data, len);
> error = stream->finalize_write(stream, oid);

The call to write to the stream could return an error which will be silently ignored.

On a related note, the loose files backend also does not check error codes on these writes, either:
https://github.com/libgit2/libgit2/blob/main/src/odb_loose.c#L1090

We've since turned off the loose files store entirely, but I figured I'd mention it.

### Expected behavior
The error should be reported so that the whole operation fails cleanly and leaves the refs in a valid state.

### Actual behavior
The error Is eaten and the operation can appear to succeed when the blob was not properly persisted, potentially resulting in a repo that is referentially invalid (has refs that refer to trees/blobs that were not correctly written).

### Version of libgit2 (release number or SHA1)
Still present (by code inspection) in: https://github.com/libgit2/libgit2/commit/4efd6563cab0caeeeb442b688523a7683cc20174

### Operating system(s) tested
I believe the field issue was seen on Windows.

**Comment by ethomson** [comment]
Thanks @dan-tull - I agree that the error checking in `odb.c` is insufficient.  😢  I'll open a PR to repair that.

I took a quick pass through looking for other obvious places that we've missed and didn't see any, which only means that we have a bunch of less obvious places that do this.  😢 

The `odb_loose.c` issue with `git_filebuf` is a little trickier.  `git_filebuf` follows a pattern where if a write fails then it will [set an internal error flag](https://github.com/dan-tull/libgit2/blob/master/src/filebuf.c#L148), which subsequent write operations will [check](https://github.com/dan-tull/libgit2/blob/master/src/filebuf.c#L468), and the finalize / commit step will [turn into an error](https://github.com/dan-tull/libgit2/blob/master/src/filebuf.c#L423).

This is a pattern that is used elsewhere within libgit2 - `git_buf`s do this, for example.  But personally, I'm not a fan.  I prefer simpler functionality, meaning hopefully a reduced cognitive load for developers and reviewers.  But I don't want to do a big lift to change this today, I'd like to give some more thought to our error handling after v1.4.0, there are a number of things that I'd like to fix (including, now, this).

**Comment by dan-tull** [comment]
Thanks! Also, thanks for the helpful elaboration on the `odb_loose.c` case. I found a number of other calls to `git_filebuf_write` ignoring the return value and those now make more sense as well, which is reassuring.
