### ISSUE TITLE
The size of `git_status_options` has changed without a change in the structure's version number

### ISSUE THREAD

**Issue by apnadkarni** [libgit2/libgit2#6210]
### Reproduction steps
The commit https://github.com/libgit2/libgit2/commit/ef84889189c65b4e977ec199925b1b0ea44ed1cc adds the field `rename_threshold` to the structure `git_status_options`. Applications that bind at runtime to libgit2 may land up with corrupted memory because they allocate `sizeof(git_status_options)` but are using an older (still v1.3) header status.h that does not include this field in the structure. For example, a `git_status_options_init` call may write past the allocated memory.

### Expected behavior
The `GIT_STATUS_OPTIONS_VERSION` define should be bumped to 2 and libgit2 should verify the versions match and change behavior accordingly, returning an error if  necessary.
 
### Actual behavior

No version check is made and invalid (as in past structure end) memory accessed.

### Version of libgit2 (release number or SHA1)

Commit ef84889189c65b4e977ec199925b1b0ea44ed1cc

**Comment by ethomson** [comment]
> Thanks for the super-quick response. I understand but in this case the minor version has not changed in HEAD (still 1.3) so I presume that will change to 1.4 for the next release. (As long as all versions 1.3.x behave the same, I'm happy).

This is correct, we don't bump the version number until the last minute.  I want to ship v1.4.0 🔜.

> BTW, I'm writing language bindings, and having written them for several libraries, I have to say despite being a non-trivial library, libgit2 was surprisingly easy and quick to bind compared to most others. Kudos on a clean API design.

Thanks - I think that we started with a real "bindings first" mentality, which helps, but this is great to hear.  🎉

**Comment by apnadkarni** [comment]
Congratulations on releasing 1.4. While I understand changing version numbers right before shipping a new release, please consider the following change to versioning if at all possible:

- Bump the minor version right after release
- Bump it again just before release

This does mean official releases skip a minor version number but they are plentiful :-)

This request arises from my releasing my bindings specifically checking for v1.3.0 when loading libgit2,  and having a user immediately try them by compiling libgit2 from its repository and failing (for the reason mentioned in this original bug report.) Because the repo version was still 1.3.0, my runtime check passed. Resolving these kind of errors can be a time sink because the user insists he is using the supported version of libgit2.

In any case, this ticket can be closed irrespective of what you decide. I would close it myself but not sure what project policy is with respect to closing tickets by folks other than maintainers.

**Comment by ethomson** [comment]
I think that we can improve our versioning process.  I've never particularly loved it, but I've never been bothered enough to fix it.  😁 

I opened #6220.  Instead of burning an intermediate minor number, I'd like to add prerelease information.  Nightlies are "alpha", we may (or may not) ship "beta" or "rc1", "rc2", etc releases.  When we do a final release, we remove the prerelease designator.  Let me know if this doesn't work for you!
