### ISSUE TITLE
1.4.x releases have the wrong VERSION

### ISSUE THREAD

**Issue by mgorny** [libgit2/libgit2#6236]
### Reproduction steps

https://github.com/libgit2/libgit2/blob/v1.4.2/CMakeLists.txt#L6

### Expected behavior

```
project(libgit2 VERSION "1.4.2" LANGUAGES C)
```

### Actual behavior

```
project(libgit2 VERSION "1.4.0" LANGUAGES C)
```

### Version of libgit2 (release number or SHA1)

1.4.1, 1.4.2

### Operating system(s) tested

n/a

**Comment by ethomson** [comment]
Thanks for the heads-up. This is fixed in the forthcoming [v1.4.3](https://github.com/libgit2/libgit2/pull/6270).
