### ISSUE TITLE
Does not support iOS , there is no header file sys/random.h 

### ISSUE THREAD

**Issue by Lojii** [libgit2/libgit2#6280]

**Comment by i-tengfei** [comment]
same issue
```
fatal error: 'sys/random.h' file not found
```

**Comment by i-tengfei** [comment]
After modifying CMAKE_ARGS, it can be built normally.
```
GIT_RAND_GETENTROPY=0
BUILD_TESTS=OFF
```

**Comment by ethomson** [comment]
That shouldn't be necessary. We need to fix this.

**Comment by ethomson** [comment]
Fixed in main. Apologies for breaking you!

**Comment by leleliu008** [comment]
this has been fixed? 

I'm facing this problem too.

```
/opt/ppkg/installing/libgit2/src/src/util/rand.c:14:11: fatal error: 'sys/random.h' file not found
# include <sys/random.h>
          ^~~~~~~~~~~~~~
```

https://www.gnu.org/software/gnulib/manual/html_node/sys_002frandom_002eh.html

It seems that `sys/random.h` is missing on many platforms.

**Comment by ethomson** [comment]
> this has been fixed?

What's the version that you're trying to build (whether a release or a git hash)?

**Comment by leleliu008** [comment]
I tried `github-main` and v1.5.0, both have this problem. my host is openbsd

**Comment by ethomson** [comment]
Ah, this change - https://github.com/libgit2/libgit2/commit/9bc82c8f884eda41fdb68f4862a83ee03ebcc8d2 - simply detected whether `getentropy` existed, but did not consider _where_ it was defined.

**Comment by leleliu008** [comment]
Yes, that works on GNU/Linux only.
