### ISSUE TITLE
Implement capability for tag signing

### ISSUE THREAD

**Issue by kuwv** [libgit2/libgit2#6293]
*Overview*
Currently, libgit2 provides commit signing with GPG but does not provide tag signing. The ability to sign tags with libgit2 is important because it is difficult to apply security practices without automation.

Please implement this so that I may extend pygit2 also.

Thank you

*References*
https://github.com/libgit2/libgit2/pull/3673
https://libgit2.org/libgit2/#HEAD/group/commit/git_commit_create_buffer
https://libgit2.org/libgit2/#HEAD/group/commit/git_commit_create_with_signature
https://github.com/libgit2/pygit2/pull/1142

**Comment by kuwv** [comment]
@carlosmn I saw the work you did for commit signing. Would you be interested in doing this or maybe outline some of the work?

**Comment by L11R** [comment]
@kuwv afaik you can sign tags already with libgit2 according to this: https://www.nodegit.org/api/tag/#createWithSignature

Example of usage:
https://github.com/nodegit/nodegit/blob/a25279f97ca9913f205cdb2335bc3ce918d9305b/test/tests/tag.js#L321

**Comment by kuwv** [comment]
@L11R 

I think you might be right. Wondering why I couldn't find many references to it though:

```
static void action_create_tag(tag_state *state)
{
  git_repository *repo = state->repo;
  struct tag_options *opts = state->opts;
  git_signature *tagger;
  git_oid oid;
  git_object *target;

  check(!opts->tag_name, "Name required");
  check(!opts->message, "Message required");

  if (!opts->target) opts->target = "HEAD";

  check_lg2([git_revparse_single](https://libgit2.org/libgit2/#HEAD/group/revparse/git_revparse_single)(&target, repo, opts->target),
      "Unable to resolve spec", opts->target);

  check_lg2([git_signature_default](https://libgit2.org/libgit2/#HEAD/group/signature/git_signature_default)(&tagger, repo),
      "Unable to create signature", NULL);

  check_lg2([git_tag_create](https://libgit2.org/libgit2/#HEAD/group/tag/git_tag_create)(&oid, repo, opts->tag_name,
        target, tagger, opts->message, opts->force), "Unable to create tag", NULL);

  [git_object_free](https://libgit2.org/libgit2/#HEAD/group/object/git_object_free)(target);
  [git_signature_free](https://libgit2.org/libgit2/#HEAD/group/signature/git_signature_free)(tagger);
}
```

**Comment by L11R** [comment]
@kuwv it definitely works, I implemented it for Go, works flawlessly: https://github.com/libgit2/git2go/pull/926

**Comment by kuwv** [comment]
@L11R That's great. Those are two references I can use to implement what I was planning. Thank you very much!

**Comment by albfan** [comment]
I just implement signing comits on gitg. Looking for same on tags:

Looks weird there's not public api to create tag buffer so we need to poorly reimplement it, like:

https://github.com/libgit2/git2go/pull/926/files#diff-d789b1adb70876292f4e6e6b8a2cc6a4b6731375f81a717587e97fa9301f1c26R106

I think is just expose `write_tag_annotation` https://github.com/libgit2/libgit2/blob/main/src/libgit2/tag.c#L213

If it is possible expose a `git_tag_create_buffer`

**Comment by L11R** [comment]
@albfan yep, it would be prefered, but my knowledge of C is pretty bad :\
