### ISSUE TITLE
clone fails with GIT_ECERTIFICATE

### ISSUE THREAD

**Issue by ChristianBirzer** [libgit2/libgit2#6312]
Hi,

I'm trying to integrate libgit2 into darktable (raw photo editing software) to install and update extension scripts from github repos (currently git executable is needed). I'm on Win10 with MinGW2 msys64 environment. Even with a minimal test application, when I git_clone() my repo, I get a result code of -17 (should be GIT_ECERTIFICATE).
git.exe does not have any problems cloning this repo.

libgit is version 1.4.3. 
libssh2 is 1.10.0

There are similar issue(s) but they state that they use an outdated version of libssh2 which seems not to be the case here.

### Reproduction steps
my minimal test program:

```
#include <stdio.h>
#include <sys/stat.h>
#include <git2.h>

void main() {
  git_repository *repo = NULL;
  int major, minor, rev;
  struct stat st = { 0 };  
  const char *cp_path = "C:/TempGit";
  
  if( stat( cp_path, &st ) == -1 ) {
    mkdir( cp_path );
  }  
  
  git_libgit2_init();
  git_libgit2_version( &major, &minor, &rev );
  printf( "version: %d.%d.%d\n", major, minor, rev );
  int error = git_clone( &repo, "https://github.com/ChristianBirzer/darktable_extra_scripts", cp_path, NULL );
  printf(" git clone: result = %d\n", error );  
  git_libgit2_shutdown();
}
```

### Expected behavior
clone of repo is written to c:\TempGit

### Actual behavior
output of error -17 and nothing is cloned.

### Version of libgit2 (release number or SHA1)
1.4.3 as installed with mingw Msys 64

### Operating system(s) tested
Win 10

**Comment by ethomson** [comment]
Sorry for the delay - were you able to make any progress here? I'm surprised to see this failing on an `https` URL.

I would expect that there's a problem with the underlying certificates that msys is using. Does this work if you compile with MSVC (and using the standard Windows crypto systems)?

**Comment by ChristianBirzer** [comment]
Thanks for your reply. 
I did not really find a solution. More a workaround. I installed the certificate_check callback in the clone_opts.fetch_opts and let it always return 0. I think that's not the best way to check certificates 🙄 but at least the clone now works fine without any error.

I currently do not have a MSVC dev environment available so I cannot check this.

**Comment by ethomson** [comment]
> I currently do not have a MSVC dev environment available so I cannot check this.

Would it help you if we started offering prebuilt binaries for Windows?  🤔

**Comment by ChristianBirzer** [comment]
> Would it help you if we started offering prebuilt binaries for Windows? 🤔

I'm not sure. I don't think so. My goal is to integrate libgit into darktable. The windows build environment for darktable is msys2 based. Therefore libgit is already used as prebuilt binary that's distributed with msys2. 
If I'd get an other prebuilt binary (e.g. newer release etc.) then the difficulty would be to integrate it in the darktable build (extra step to download, install, etc.). I'm not sure if/how this could be handled without making the darktable build more difficult.

Are there any possibilities to get more information about the error? Some enhanced logging, tracing etc. to get a more detailed insight of what's going wrong here...

**Comment by ethomson** [comment]
Hey @ChristianBirzer - just wanted to check in and see if you were able to resolve this? I missed your question about debugging - I realize it's been a while but do you still need assistance?

**Comment by ChristianBirzer** [comment]
Thank you for asking. To be honest, I have lost sight of the topic somewhat. I haven't had time to do anything for darktable lately, so I haven't been able to do any more testing here. The last state was that I could disable certificate checking completely, which would allow the repo to be cloned. 
Since I won't be working on the issue much in the near future either, it's ok with me if the issue is closed.
