### ISSUE TITLE
branch: git_branch_create allows creation of branches with invalid names

### ISSUE THREAD

**Issue by lrm29** [libgit2/libgit2#6328]
### Reproduction steps
Using git_branch_create, it is possible to create branches with invalid names.

There is a function called git_branch_name_is_valid but it's not used inside git_branch_create. Presumably we can either:

1) call git_branch_name_is_valid
2) do just the branch specific name checks in git_branch_create, and let the reference creation part check for a valid reference name

Let me know either the rationale for allowing invalid names, or a preferred solution and I can create a pull request.

### Expected behavior
The behaviour should be the same as command-line Git:

$ git checkout -b -notvalid
fatal: '-notvalid' is not a valid branch name.

$ git checkout -b HEAD
fatal: 'HEAD' is not a valid branch name.

### Actual behavior
git_branch_create will create branches starting with a hyphen or called HEAD.

### Version of libgit2 (release number or SHA1)
v1.3.0

### Operating system(s) tested
Windows and Linux

**Comment by ethomson** [comment]
I think that it makes sense to avoid creating invalid branch names - users can always go to `git_reference_create` if they think that they really want to do this.

I think that I would create a helper method that validates just the branch portion of the name and make `git_branch_create` and `git_branch_name_is_valid` call it.

We'll probably need to do the same with tags.

**Comment by ethomson** [comment]
Fixed via #6348
