### ISSUE TITLE
git_branch_move always deletes the reflog instead of renaming it

### ISSUE THREAD

**Issue by arroz** [libgit2/libgit2#6344]
### Reproduction steps
1. For a branch that has an existing reflog, call `git_branch_move` to rename the branch.
2. Notice the reflog was deleted and a new one created, with only a single line recording the rename.

### Expected behavior
The reflog should be renamed and the rename record appended.

### Actual behavior
The reflog is deleted and re-created.

### Version of libgit2 (release number or SHA1)
Main (currently `1a94d97e5f5668d25d677471a81dba384267a428` at the time of this writing).

### Operating system(s) tested
macOS 12.4

**Comment by arroz** [comment]
## Diagnostic

`refdb_fs_backend__rename` calls `refdb_fs_backend__delete` to delete the old reference. This function also deletes the reflog, which is not ideal in this situation.

**Comment by ethomson** [comment]
🙁  Indeed, this is not the correct behavior. Thanks for letting me know.
