### ISSUE TITLE
Update libssh

### ISSUE THREAD

**Issue by darakeon** [libgit2/libgit2#6381]
### Reproduction steps

Create a SSH key to communicate with github.

```bash
ssh-keygen -t ecdsa -C "your-email"
```

Create a rust program with cargo that tries to pull a repository using fetch. Use the callback as:

```rust
fn git_credentials_callback(
	_url: &str,
	username: Option<&str>,
	_cred_type: CredentialType,
) -> Result<Cred, Error> {
	let public = get_key_path(Some("pub"));
	let private = get_key_path(None);

	let password = env::var("GIT_PASSWORD")
		.expect("No GIT_PASSWORD environment variable found"); // or some hardcoded password

	println!("{:?}", _cred_type);

	let cred = Cred::ssh_key(
		username.unwrap(),
		Some(public.as_path()),
		private.as_path(),
		Some(&password),
	);

	let result = cred.unwrap();
	println!("{:?}", result.credtype());

	return Ok(result);
}
```

The fetch:

```rust
pub fn update_local() {
	let repo = Repository::open("..").unwrap();
	let mut remote = repo.find_remote("origin").unwrap();

	let mut callbacks = RemoteCallbacks::new();
	callbacks.credentials(&git_credentials_callback);

	let mut options = FetchOptions::new();
	options.remote_callbacks(callbacks);
	options.prune(FetchPrune::On);

	remote.fetch(
		&[] as &[&str],
		Some(&mut options),
		Some("updating local")
	).unwrap();
}
```

The get_key_path of mine:

```rust
fn get_key_path(extension: Option<&str>) -> PathBuf {
	let mut path = home_dir().unwrap();
	path.push(".ssh");
	path.push("cargo");

	if let Some(extension_value) = extension {
		path.set_extension(extension_value);
	}

	return path;
}
```

The entire code: https://github.com/darakeon/dfm/blob/main/version/src/git.rs

### Expected behavior

Pull succeeds.

### Actual behavior

Call the credentials function a bunch of times and gives the error:
```
 { code: -16, klass: 23, message: "Failed to retrieve list of SSH authentication methods: Failed getting response" }
```

This message does not comes from rust library, I checked the source code of it.

### Version of libgit2 (release number or SHA1)

Compiling libssh2-sys v0.2.23
Compiling libgit2-sys v0.14.0+1.5.0

### Operating system(s) tested

Windows 10 (yeah, I now, almost every dev hates it). Trying to pull from github.

### More details

Github updated their way to handle SSH in Sep 2021, and they recommend to use version 1.9.0 of libssh. Seems like the library here is using 0.2.23.

Github article: https://github.blog/2021-09-01-improving-git-protocol-security-github/#libgit2-and-other-git-clients

**Comment by ethomson** [comment]
> Seems like the library here is using 0.2.23.

It does look like that, but libgit2 doesn't actually vendor libssh2, we require our users to bring their own. In this case, I think it's the git2 crate. Would you be so kind as to report this to them? Hopefully between the two projects we can get this sorted for you.

**Comment by darakeon** [comment]
Thanks. I will "talk" to them.

**Comment by darakeon** [comment]
@ethomson , I don't understand that much of Rust. I checked libssh2 in cargo library (https://crates.io/crates/libssh2-sys) and its latest version if 0.2.23. But github page talks about a 1.9.0 . I found the dependency in the repo and thought about a PR instead of an issue, but got lost.
