### ISSUE TITLE
cant get Repository::status_file working

### ISSUE THREAD

**Issue by Masber** [libgit2/libgit2#6411]
You are opening a _bug report_ against the libgit2 project: we use
GitHub Issues for tracking bug reports and feature requests.  If you
have a question about an API or usage, please ask on StackOverflow:
http://stackoverflow.com/questions/tagged/libgit2.  If you want to
have high-level discussions about the libgit2 project itself, visit
https://github.com/libgit2/discussions.

Otherwise, to report a bug, please fill out the reproduction steps
(below) and delete these introductory paragraphs.  Thanks!

### Reproduction steps
run code below
```
    pub fn untracked_changed_local_files(repo: Repository) -> core::result::Result<bool, Box<dyn std::error::Error>> {
        
        use walkdir::WalkDir;

        // Check tree/indexes Adding all files (git add)
        for file in WalkDir::new(std::env::current_dir().unwrap()).into_iter().filter_map(|file| file.ok()) {

            if file.metadata().unwrap().is_file() {

                println!("{}", file.path().display());

                let status = repo.status_file(file.path()).unwrap();

                if status.contains(git2::Status::WT_MODIFIED) || status.contains(git2::Status::WT_NEW) {
                    return Ok(false);
                }
            }
        }

        Ok(true)
    }
```
### Expected behavior

to run and return true if pwd has not been changed or false otherwise

### Actual behavior

code crashes with following error
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { code: -1, klass: 0, message: "repo path `/home/.../.gitignore` should be relative" }'
```

### Version of libgit2 (release number or SHA1)

git2 = "0.15.0"

### Operating system(s) tested

Ubuntu 20.04.4 LTS

**Comment by ethomson** [comment]
Which line of code is returning that error? Once you've identified the line of code that produces it, is the error message not helpful in resolving the problem?
