### ISSUE TITLE
[Feature Request] Expose `load_config` for use in git extension

### ISSUE THREAD

**Issue by oxr463** [libgit2/libgit2#6412]
### Reproduction steps

A git extension might use a special filename but still contain a git-compatible config. An example of this is the `.lfsconfig` file for git-lfs. As a developer, I would like to use libgit2 to develop a git extension, and I would like for the `static int load_config` function found in [`src/libgit2/repository.c`](https://github.com/libgit2/libgit2/blob/main/src/libgit2/repository.c#L1115) to be exposed externally (`GIT_EXTERN(int)`) so that I can pass a custom filename into libgit2 to load additional configuration values.

### Expected behavior

```c
GIT_EXTERN(int) load_config(
```

### Actual behavior

```c
static int load_config(
```

### Version of libgit2 (release number or SHA1)

`main`

### Operating system(s) tested

Alpine Linux 3.16.1

**Comment by carlosmn** [comment]
What are you missing from the [`git_config_` family of functions](https://libgit2.org/libgit2/#v1.5.0/group/config) for you to read a git-config-format file?

**Comment by oxr463** [comment]
> What are you missing from the [`git_config_` family of functions](https://libgit2.org/libgit2/#v1.5.0/group/config) for you to read a git-config-format file?

Would I be able to use [`git_config_add_file_ondisk`](https://libgit2.org/libgit2/#v1.5.0/group/config/git_config_add_file_ondisk) to read an `.lfsconfig` config file in the top-level directory of a git repository? If so, then maybe that would be preferred to exposing `load_config`.

**Comment by carlosmn** [comment]
You can use that function to parse any file that has the git-config format.

**Comment by oxr463** [comment]
That's great! I think this is what I'm looking for.
