### ISSUE TITLE
known_hosts fail to load on Windows

### ISSUE THREAD

**Issue by ehuss** [libgit2/libgit2#6453]
Fetching a repo over SSH fails on Windows because it fails to find the home directory. This can happen when launching from Windows Powershell, Cmd, or other environments that do not set HOME.

### Reproduction steps

Fetch an SSH repo from github.com using Windows Powershell or Cmd.

### Expected behavior

libgit2 should be able to find the user's home directory.  There are multiple ways to do that, though I'm not sure of the benefits of different approaches. Checking for USERPROFILE would probably be the easiest. The Powershell port of OpenSSH uses `ProfileImagePath` in the registry, falling back to `GetWindowsDirectoryW` if that fails.  (Another option is `SHGetFolderPathW`, though I'm not sure I would recommend that.)

Also, I think a failure to load or process the known_hosts should not be a hard error if the user has also defined their own `certificate_check_cb` callback. That is, the code [here](https://github.com/libgit2/libgit2/blob/036fe1afba37d9b20509671d3048c6088f018134/src/libgit2/transports/ssh.c#L544-L558) shouldn't be a hard error.

### Actual behavior

The error is:

```
invalid or unknown remote ssh hostkey
```

### Version of libgit2 (release number or SHA1)

1.5.1

### Operating system(s) tested

Windows 10 Pro

**Comment by ethomson** [comment]
Ugh, yes. We should be using our typical home directory lookup routines which look at `HOME` on posix and `HOME` / `HOMEPATH` / `USERPROFILE` on Windows. Unfortunately, this complicates our tests -- especially in CI -- but it's the right thing to do. I've started attacking this but the CI changes need some more work.

Apologies for the inconvenience.
