### ISSUE TITLE
Does not work on WSL shares

### ISSUE THREAD

**Issue by csware** [libgit2/libgit2#6468]
### Reproduction steps
Have a WSL share and open a repository on it

Seems to be a regression https://github.com/libgit2/libgit2/pull/6349.

### Expected behavior
open_repository works as did with older versions

### Actual behavior
Cannot open the repository: "failed to get security information: Incorrect function."

Seems to come from: https://github.com/libgit2/libgit2/blob/f02bcf721105d3dfb0a7d12dec2816b495451c45/src/util/fs_path.c#L1852

### Version of libgit2 (release number or SHA1)
v1.5
fbea439d4b6fc91c6b619d01b85ab3b7746e4c19

### Operating system(s) tested
Windows 10

cross-ref: https://gitlab.com/tortoisegit/tortoisegit/-/issues/3997

**Comment by csware** [comment]
Git for Windows seems to ignore errors from that function (https://github.com/git-for-windows/git/blob/b3665b1bf46b33c3917012c2798e74f2add47088/compat/mingw.c#L3560)

**Comment by ethomson** [comment]
Hmm... I think that we're going to need to dig a little deeper here. It doesn't look like they're ignoring errors -- it looks like they also call `GetNamedSecurityInfoW` and then only proceed if it returns `ERROR_SUCCESS`? So either I'm misreading the code or there's a different indirection for WSL.

https://github.com/git-for-windows/git/blob/b3665b1bf46b33c3917012c2798e74f2add47088/compat/mingw.c#L3589

**Comment by csware** [comment]
See the following if-statement. It is not entered if the return value of `GetNamedSecurityInfoW` is not `ERROR_SUCCESS` and then `result` is returned (which should be 0).

**Comment by ethomson** [comment]
But it's a boolean, and a `result` of 0 indicates that the path is _not_ owned by the current user? (It's set to `1` when the current user matches the ownership -- https://github.com/git-for-windows/git/blob/b3665b1bf46b33c3917012c2798e74f2add47088/compat/mingw.c#L3605)

**Comment by ethomson** [comment]
No worries. I'll try to dig in.

**Comment by csware** [comment]
Maybe this needs to read "doesn't work on UNC paths", cf. https://gitlab.com/tortoisegit/tortoisegit/-/issues/4002

**Comment by maplion** [comment]
I am also getting this issue.  It is regressive and I temporarily solved by reverting back to 12.13.x.

**Comment by ethomson** [comment]
Looking into this a bit more, it looks like Git for Windows doesn't do anything too clever. It doesn't understand the mapping between WSL 2 users and Windows users (if there's even such a mapping that exists). Instead, if the system calls fail, it just marks the file as not-owned by the current user (instead of treating the system call failure as a fatal error). In #6393, we match that behavior.

```
fatal: unsafe repository ('//wsl.localhost/Debian/tmp/TestGitRepository' is owned by someone else)
To add an exception for this directory, call:

        git config --global --add safe.directory '%(prefix)///wsl.localhost/Debian/tmp/TestGitRepository'

Set the environment variable GIT_TEST_DEBUG_UNSAFE_DIRECTORIES=true and run
again for more information.
```

**Comment by csware** [comment]
Fine for me as long as the exception works ;)

**Comment by milos-milicevic** [comment]
This is an issue for me too.

With the environment variable GIT_TEST_DEBUG_UNSAFE_DIRECTORIES set to true the safe directory error is solved, but the error: **failed to get security information: Incorrect function.** keeps popping up.
I had to downgrade to 2.13.0.1 to make it work again.

**Comment by csware** [comment]
@ethomson How to match unc network paths? `//` is not handled as an UNC path...

**Comment by ethomson** [comment]
What does git do? It looks like neither of those will work from reading the source.

**Comment by csware** [comment]
Issue `git status \\192.168.0.1\c$\dir` on the CLI and Git will show the exception path it expects: `%(prefix)///192.168.0.1/c$/dir/` for vanilla Git.
Why did you add an exception for ``\\wsl.localhost\`` how does that work? (I don't have WSL and, thus, cannot test)
