### ISSUE TITLE
CLI state and contributions possibility

### ISSUE THREAD

**Issue by iliakan** [libgit2/libgit2#6469]
- [ ] What's the current state of CLI implementation? Is it a solid foundation that just needs more commands?
 - [ ] Would it be a good idea to contribute new git commands into the current CLI framework?
 - [ ] Is there any ongoing unmerged work in progress regarding CLI?
 - [x] Also, is the CLI supposed to be compatible with `git/git`? (yes)

**Comment by boretrk** [comment]
The initial [commit](https://github.com/libgit2/libgit2/commit/3a3ab065f0685202c854e13708ddfd2a93d75e2c) for it might give a pretty good answer in the commit message.
The corresponding PR #6133 have some more thoughts about it.

> The goal is for it to be git-compatible.

**Comment by ethomson** [comment]
>  What's the current state of CLI implementation? Is it a solid foundation that just needs more commands?

I think so, yes.

>  Would it be a good idea to contribute new git commands into the current CLI framework?

Sit tight, because:

>  Is there any ongoing unmerged work in progress regarding CLI?

Yes - let me push up a branch for review. It's on my personal (at home) computer, so please hold. ⏸️ 🔜

**Comment by jakirkham** [comment]
Am curious, how things are looking now?

**Comment by ethomson** [comment]
Contributions are definitely welcome!

**Comment by jakirkham** [comment]
Glad to hear that

> Yes - let me push up a branch for review. It's on my personal (at home) computer, so please hold. ⏸️ 🔜

Was wondering about this statement. Were these changes pushed? If so, where are they now?

No worries if not. Just wasn't clear on what happened next

**Comment by ethomson** [comment]
I think that most of the things that I had in flight are merged.
