### ISSUE TITLE
git_repository_open_bare isn't setting oid_type

### ISSUE THREAD

**Issue by arroz** [libgit2/libgit2#6491]
When opening a repository with `git_repository_open_bare`, the `oid_type` isn't set. This causes all the code that relies on it (like loading packed refs) to fail, since `GIT_OID_SHA1` has value of 1, but the memory contents will be 0 if not set to any value.

**Comment by arroz** [comment]
@ethomson I guess the best way to fix this is extract the code that loads config, checks version, loads and sets the oid_type from `git_repository_open_ext` into a separate function and calling it from both loading functions. Let me know if you want a patch (it's broken in main right now) or if you can handle that as part of the ongoing SHA256 effort (thank you for that, btw!).

**Comment by ethomson** [comment]
Oops! I'd welcome a patch. I won't be able to look at this until tomorrow at the earliest.

**Comment by arroz** [comment]
Here it is: https://github.com/libgit2/libgit2/pull/6492
