### ISSUE TITLE
libgit2 pkgconfig file now named git2.pc

### ISSUE THREAD

**Issue by nekopsykose** [libgit2/libgit2#6507]
### Reproduction steps
build 1.6.1 on linux

### Expected behavior
it outputs a libgit2.pc, like before

### Actual behavior
it outputs a git2.pc

### Version of libgit2 (release number or SHA1)
1.6.1

### Operating system(s) tested
linux

this is caused by 6c57bac6b18f6a30e1a8c8272a8dc367f202aa88  

before, there was:

```cmake
pkg_build_config(NAME libgit2
	VERSION ${libgit2_VERSION}
	DESCRIPTION "The git library, take 2"
	LIBS_SELF git2
	PRIVATE_LIBS ${LIBGIT2_PC_LIBS}
	REQUIRES ${LIBGIT2_PC_REQUIRES}
)
```

now, there is

```cmake
pkg_build_config(NAME "${LIBGIT2_FILENAME}"
	VERSION ${libgit2_VERSION}
	DESCRIPTION "The git library, take 2"
	LIBS_SELF git2
	PRIVATE_LIBS ${LIBGIT2_PC_LIBS}
	REQUIRES ${LIBGIT2_PC_REQUIRES})
```

of course, LIBGIT2_FILENAME is `git2`. this causes the rename.

this does not break finding libgit2 via cmake- cmake finds the .so file (afaik) via cmake magic:tm:, but any consumer of the .pc files (meson without cmake, autotools, manual scripts..) is broken by this rename, because libgit2 is found by (generally speaking) calling `pkg-config --libs --cflags libgit2` in that case.

**Comment by ethomson** [comment]
Oops. Thanks for the report. I'll fix this and we'll ship another point release. 😢
