### ISSUE TITLE
git_odb_backend_loose removed

### ISSUE THREAD

**Issue by ehuss** [libgit2/libgit2#6509]
The `git_odb_backend_loose` function was removed in the 1.6 release via #6354, but it is not clear if that was intended. It appears to have been renamed to `git_odb__backend_loose`, but the old header definition was retained with:

https://github.com/libgit2/libgit2/blob/8a871d13b7f4e186b8ad943ae5a7fcf30be52e67/include/git2/odb_backend.h#L139-L152

Additionally, the signature was changed in #6191. The header seems to imply that there was an intent to support the old signature, but that support doesn't seem to exist.

I don't think I actually need this function, so I'm ultimately fine with its removal. However, this caused an API break to our bindings. If it is indeed intended to be removed, I would suggest removing it from the header file as well.

**Comment by ethomson** [comment]
Oops. I'll fix this. Thanks for the report.
