### ISSUE TITLE
Brew install salt@{pinned version} is broken since 1.6.3

### ISSUE THREAD

**Issue by Esysc** [libgit2/libgit2#6538]
This happens since new version is out and Salt formula is update accordingly. I'm using `brew` here because on Apple Silicon is the recommended way to install Salt package. The new version removed needed headers file that are needed to compile `pygit2`.

### Reproduction steps

Tap a pinned version
```shell
brew tap-new $USER/salt
brew extract --version=3004.2 salt $USER/salt
```
Install Salt
```shell
brew install salt@3004.2
```
### Expected behavior

salt installation is successful

### Actual behavior

```shell
  In file included from src/blob.c:30:
  src/diff.h:33:10: fatal error: 'git2.h' file not found
  #include <git2.h>
           ^~~~~~~~
  1 error generated.
  error: command '/usr/bin/clang' failed with exit code 1
  error: subprocess-exited-with-error
  
  × Building wheel for pygit2 (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
```
And Salt installation fails. It seems that some needed header files have been removed.

### Version of libgit2 (release number or SHA1)

Version `1.6.3`

### Operating system(s) tested

```
ProductName:	macOS
ProductVersion:	12.6
BuildVersion:	21G115
```

### Workaround

Patch the Salt Brew Formula pinning `libgit2` to version `1.5`. I first tried using `1.6.2` that I know it works since last week but i got this error in Brew:
```
Warning: No available formula with the name "libgit2@1.6.2" (dependency of anka/salt/salt@3004.2). Did you mean libgit2@1.5?
```

**Comment by ethomson** [comment]
I don't know what salt is or how to even start debugging this. I think opening an issue in the pygit2 repo would be a good start.

**Comment by Esysc** [comment]
> I don't know what salt is or how to even start debugging this. I think opening an issue in the pygit2 repo would be a good start.

Thanks @ethomson for you reply.

Salt is https://saltproject.io/, but  you can reproduce just trying to install `pygit2` wheel, `pip install pygit2` that is what `brew` is doing under the hood. During the installation, it tries including `git2.h`  that has been removed in https://github.com/libgit2/libgit2/pull/6529, here is the line: https://github.com/libgit2/pygit2/blob/75f8fcd3dfa86d12d0861f93d540c61fa5718c0d/src/diff.h#L33.

I will open the issue on pygit2 repo and eventually close this one.

**Comment by Esysc** [comment]
Thinking about a little more, it should be an issue with the `brew` formula that should be updated. They basically set the version of `libgit2` to 1.6.3 without any other change.

**Comment by Esysc** [comment]
Thinking about a little more, it should be an issue with the `brew` formula that should be updated. They basically set the version of `libgit2` to 1.6.3 without any other change.

**Comment by ethomson** [comment]
Thanks for the update - since this is an issue with the brew formula, I'm going to close this. Please let me know if there's anything we can do to help.
