### ISSUE TITLE
Android版本 无法正常编译,甚至无法生成MakeFile配置文件

### ISSUE THREAD

**Issue by BaY1251** [libgit2/libgit2#6546]
如题,使用Android-ndk-r25c + CMake-3.26.3-windows-x86_64,无法编译通过. android-ndk-r25c已废弃独立工具链,并且删除了GCC,使用Clang兼容脚本,无法正常使用.
改用android-ndk-r17b + CMake-3.6 等其它版本,发现NDK的GCC版本较低,仍无法正常编译. 

一些背景:
我计划在Android系统上使用MAUI+LibGit2Sharp,发现缺少Android系统对应的动态库,故尝试自己编译,但是失败了.

**Comment by leleliu008** [comment]
You could use My GitHub Actions workflow to build libgit2 : https://github.com/leleliu008/ndk-pkg-package-manually-build

**Comment by BaY1251** [comment]
非常感谢

**Comment by BaY1251** [comment]
非常感谢
