### ISSUE TITLE
Instructions for Building examples

### ISSUE THREAD

**Issue by mslinn** [libgit2/libgit2#6571]
The `examples/` directory contains one `.h` file and almost 3 dozen `.c` files, plus `CMakeLists.txt`.

`GIT_OID_SHA1_HEXSIZE` is referenced by the examples, but is not defined within `examples/`. Instead, it is defined in the `libgit2` code itself, in `/include/git2/oid.h`. Thus, running `cmake` from with `examples/` directory fails.

Would a kind soul please write up instructions for compiling the examples? I would rather not compile all of `libgit2`, just the examples.

**Comment by ethomson** [comment]
To build the examples, you need to `cmake -DBUILD_EXAMPLES=ON` at the top-level. There is currently no way to build the examples outside of the libgit2 build.
