### ISSUE TITLE
1.7.0: missing import for git_oidarray

### ISSUE THREAD

**Issue by dvzrv** [libgit2/libgit2#6607]
Hi! I'm currently attempting the rebuild of projects against libgit2 1.7.0 on Arch Linux (https://archlinux.org/todo/libgit2-17/).

### Reproduction steps

Attempting to build recent jami-daemon against libgit2 (see https://git.jami.net/savoirfairelinux/jami-daemon/-/issues/876) fails due to a missing import for `git_oidarray`.
See recent [PKGBUILD](https://gitlab.archlinux.org/archlinux/packaging/packages/jami-daemon/-/blob/6abb5dade3527c562e29adada2f613c568dc0897/PKGBUILD) for an overview on how we build jami-daemon.

### Expected behavior

The build succeeds.

### Actual behavior

Many instances of 

```
/usr/include/git2/sys/transport.h:116:17: error: ‘git_oidarray’ has not been declared
  116 |                 git_oidarray *out,
      |                 ^~~~~~~~~~~~
```

Full build log:
[jami-daemon-20230620-1-x86_64-build.log](https://github.com/libgit2/libgit2/files/12129406/jami-daemon-20230620-1-x86_64-build.log)

### Version of libgit2 (release number or SHA1)
1.7.0

### Operating system(s) tested
Arch Linux

**Comment by vincenzopalazzo** [comment]
Mh this is strange! I am on arch and I do not have any problem a compile last `main`

**Comment by vincenzopalazzo** [comment]
Ah ok I build with cmake but you looks like you are using ninja?

**Comment by dvzrv** [comment]
> Mh this is strange! I am on arch and I do not have any problem a compile last `main`

You will have to be more specific than this to help me understand what you are referring to here. :)

In the meantime I have pushed a fixed version of libgit2 to extra-staging: https://gitlab.archlinux.org/archlinux/packaging/packages/libgit2/-/commit/e84d2778de5936988f34e2d6bbc46105d4a1e9e9
This fixes the issues observed when building against jami-daemon (which uses a custom transport, what seems to trigger the issue with the missing include).

**Comment by dvzrv** [comment]
> Ah ok I build with cmake but you looks like you are using ninja?

I don't use ninja for the package: https://gitlab.archlinux.org/archlinux/packaging/packages/libgit2/-/blob/e84d2778de5936988f34e2d6bbc46105d4a1e9e9/PKGBUILD#L45-54

**Comment by vincenzopalazzo** [comment]
Ah ok I am building it in another way, I will try to reproduce the problem in a cloud machine with arch and see if I can get your error
