### ISSUE TITLE
git2 crashes when invoked without any arguments

### ISSUE THREAD

**Issue by roboknight** [libgit2/libgit2#6630]
You are opening a _bug report_ against the libgit2 project: we use
GitHub Issues for tracking bug reports and feature requests.  If you
have a question about an API or usage, please ask on StackOverflow:
http://stackoverflow.com/questions/tagged/libgit2.  If you want to
have high-level discussions about the libgit2 project itself, visit
https://github.com/libgit2/discussions.

Otherwise, to report a bug, please fill out the reproduction steps
(below) and delete these introductory paragraphs.  Thanks!

### Reproduction steps
1) type "git2" at the command line
2) observe segmentation fault

### Expected behavior
some kind of help text, or at least quitting without crashing.

### Actual behavior
segfaults in a strcmp operation.

### Version of libgit2 (release number or SHA1)
da265cdf2ed7f7338178b9ed5768af211656e50b

### Operating system(s) tested
Ubuntu 22.04

**Comment by ethomson** [comment]
Fixed via #6673
