### ISSUE TITLE
Ownership checks make Android usage impossible

### ISSUE THREAD

**Issue by jakubslaby09** [libgit2/libgit2#6639]
Hi,
I'm trying to use libgit2 on android in an external storage directory. Libgit2 checks the ownership of directories it opens.
On android, anything under `/storage/emulated/0/*/` is owned by the `media_rw` group and has `rwxrwx---`,
so these checks give a false negative.

### Reproduction steps
In an android app, try to open a repo in `/storage/emulated/0/Documents/` with `git_repository_open`

### Expected behavior
If the app was given permissions to that directory and the git repo isn't broken, it should open it and return `0`.

### Actual behavior
It exits with `-36` (`GIT_EOWNER`)

### Version of libgit2
4939fa740aba2d7f2392b88e67e563eadd32e58c

### Operating system tested
Stock Android 13 (`T1TN33.14-90-9`) with kernel `5.10.168-android12-9-00002-gf3c080171fd5-ab10346004`

**Comment by ethomson** [comment]
You can turn off ownership checks. But are you asserting that we just shouldn't do ownership checks on Android?

I'm not familiar enough with Android to know whether that's sensible or not. It seems like a _de facto_ single user system indeed shouldn't do single user checks, but I don't know enough about the android ecosystem to really know if that's true. eg, is there any user separation?

**Comment by ethomson** [comment]
Closing as stale.
