### ISSUE TITLE
Returning non-zero from push_negotiation callback causes git_remote_push to fail with missing config errors

### ISSUE THREAD

**Issue by brennie** [libgit2/libgit2#6672]
### Reproduction steps

1. Create a repository
2. Create a push_options object with a push_negotiation member that returns -1
3. Call git_remote_push with any refspec

See the MWE https://gist.github.com/brennie/72afc8e0d61a490023392e6b31608540

### Expected behavior

Not sure. At the very least, the errors about missing config values should be cleared. Perhaps the error set from inside the callback should be cached (if git_error_set was called) and restored.

### Actual behavior

`git_error_last()` will report errors about missing configuration option `pack.windowMemory`. The error is set in [`packbuilder_config`](https://github.com/libgit2/libgit2/blob/b49b8dbe19ba2ec5c4949de67b444879e386bc84/src/libgit2/pack-objects.c#L97) in `pack-objects.c`.

### Version of libgit2 (release number or SHA1)

v1.7.1, v1.6.4

### Operating system(s) tested

Linux

**Comment by ethomson** [comment]
Thanks for reporting this. Question: are you setting an error in the callback?

**Comment by ethomson** [comment]
Never mind - I see the example you linked. Thanks!

We should indeed clear the error / set it to a generic value if you don't set one. We use this pattern elsewhere for user callbacks but must have missed this one.
