### ISSUE TITLE
Win32: CMake missing secur32 link dependency for auth_sspi

### ISSUE THREAD

**Issue by mrjoel** [libgit2/libgit2#6710]
### Reproduction steps

Build on Windows using `USE_HTTPS=OpenSSL`

### Expected behavior

Build succeeds

### Actual behavior

Link error due to missing symbols, including `FreeContextBuffer` and `CompleteAuthToken`. These are added in https://github.com/libgit2/libgit2/pull/6533 with `src/libgit2/transports/auth_sspi.c` being included unconditionally, and yet not added to `LIBGIT2_SYSTEM_LIBS` in `cmake/SelectHTTPSBackend.cmake`.

Either inclusion of system libs for the OpenSSL path, or conditional building of auth_sspi seems workable.

### Version of libgit2 (release number or SHA1)

1.7.0 or later

### Operating system(s) tested

Windows 10

**Comment by mrjoel** [comment]
Looking further at master for reference in writeup, this turns out to already be fixed with https://github.com/libgit2/libgit2/commit/86872834c5f but hasn't yet made a release. Any chance of a release soon including that fix?

**Comment by ethomson** [comment]
Yes - we're past due for a release. I'm looking forward to v1.8 early in the new year. I'd like to land #6679 first. 🙏

**Comment by mrjoel** [comment]
Sounds good, thanks. In the meantime I'll close this with the reference to the commit fixing it, I can backport it onto our internal branch for the time being.
