### ISSUE TITLE
libgit2 1.7.x into conan 2

### ISSUE THREAD

**Issue by callmerockett** [libgit2/libgit2#6750]
When searching for package of libgit2 in conan center we see the message 

> It has not been possible to load this information. Please, check if [this recipe version](https://github.com/conan-io/conan-center-index/tree/master/recipes/libgit2) is compatible with Conan v2.x.

There are plans to upload newer libgit2 versions like 1.7.x with conan 2 recipes?

**Comment by ethomson** [comment]
This has never been something that the libgit2 maintainers have done — someone was kind enough to handle this for us. I have no conan expertise — I've never used it, and I've certainly never authored a conan package.

It looks _relatively_ straightforward, but there is obviously some work to be done to fit our cmake configuration into the conan ecosystem.

Ideally, someone with some conan expertise will volunteer to help out. 🙏

**Comment by callmerockett** [comment]
Hey @ethomson , thanks for the reply!

I'm experimenting with conan2 and interested in libgit2 as well. Not a promise, but I'll look into that in the next weeks or so for learning purposes.

Thanks again!

**Comment by callmerockett** [comment]
Actually, there is an ongoing effort for quite a while now in this PR https://github.com/conan-io/conan-center-index/pull/18458.

**Comment by ethomson** [comment]
Looks like https://github.com/conan-io/conan-center-index/pull/18458 was merged! I'm going to close this but let me know if there's anything else that we can do to help. 🙏
