### ISSUE TITLE
`----` in commit message breaks trailer parsing

### ISSUE THREAD

**Issue by robertlacroix** [libgit2/libgit2#6760]
`git_message_trailers` fails to return trailers when the commit message contains 3 or more dashes, because `find_patch_start` erroneously just looks for `---` instead of `--- ` (with a trailing space, like Git does).

### Reproduction steps
Try to parse trailers from a commit message like

```
Commit title

Header
------
Lorem ipsum

Signed-off-by: test@test.com
```

### Expected behavior
`git_message_trailers` returns `Signed-off-by` trailer

### Actual behavior
`git_message_trailers` returns no trailers

### Version of libgit2 (release number or SHA1)
1.7.2 (a418d9d4ab87bae16b87d8f37143a4687ae0e4b2)

### Operating system(s) tested
macOS

**Comment by ethomson** [comment]
Thanks for the report!
