### ISSUE TITLE
test failures

### ISSUE THREAD

**Issue by wafaking** [libgit2/libgit2#6799]
You are opening a _bug report_ against the libgit2 project: we use
GitHub Issues for tracking bug reports and feature requests.  If you
have a question about an API or usage, please ask on StackOverflow:
http://stackoverflow.com/questions/tagged/libgit2.  If you want to
have high-level discussions about the libgit2 project itself, visit
https://github.com/libgit2/discussions.

Otherwise, to report a bug, please fill out the reproduction steps
(below) and delete these introductory paragraphs.  Thanks!

### Operating system(s) tested

after execute `ctest -V`
there has failures in result in "libgit2-1.5.0/build/tests/libgit2":
<img width="497" alt="image" src="https://github.com/libgit2/libgit2/assets/29891348/fec80a1b-d728-4e0b-a0ce-f9c6c4390834">

**Comment by wafaking** [comment]
Start testing: Apr 25 19:32 CST
----------------------------------------------------------
1/10 Testing: offline
1/10 Test: offline
Command: "/Users/zhunannan/temp/libgit2-1.5.0/build/libgit2_tests" "-v" "-xonline"
Directory: /Users/zhunannan/temp/libgit2-1.5.0/build/tests/libgit2
"offline" start time: Apr 25 19:32 CST
Output:
----------------------------------------------------------
Loaded 374 suites: 
Started (test status codes: OK='.' FAILURE='F' SKIPPED='S')

apply::both...........................
apply::callbacks...
apply::check....
apply::fromdiff..........................
apply::fromfile..........................................
apply::index.........
apply::partial............
apply::tree..
apply::workdir...........
attr::file.....
attr::flags...
attr::lookup.....
attr::macro.........
attr::repo.............
blame::buffer.......
blame::getters..
blame::harder....
blame::simple..SS.......
checkout::binaryunicode..
checkout::conflict.................
checkout::crlf..............
checkout::head...........
checkout::icase.............
checkout::index........SS......................
checkout::nasty................................
checkout::tree..............................................
checkout::typechange...
cherrypick::bare...
cherrypick::workdir..........
clone::empty....
clone::local....
clone::nonetwork..................
clone::transport.
commit::commit.....
commit::parent.
commit::parse........
commit::signature............
commit::write........
config::add..
config::backend.
config::conditionals.....
config::configlevel....
config::global.....
config::include................
config::memory.......
config::multivar.........
config::new.
config::read..................................................
config::readonly...
config::rename...
config::snapshot.....
config::stress........S
config::validkeyname.
config::write...........................
core::buf...
core::env....
core::features.
core::hashsig..
core::oid....
core::oidmap......
core::opts.....
core::pool.
core::structinit.
core::useragent.
date::date..
date::rfc2822...
delta::apply..
describe::describe..
describe::t6120.......
diff::binary............
diff::blob.....................
diff::diffiter.........
diff::drivers....
diff::externalmodifications....
diff::format::email.........
diff::index.......
diff::notify.......
diff::parse.................
diff::patch.......
diff::patchid...........
diff::pathspec.
diff::racediffiter..
diff::rename..............................
diff::stats.................
diff::submodules.........
diff::tree............
diff::userdiff.
diff::workdir............................S..
email::create.......
fetch::local..
fetchhead::nonetwork.................
filter::bare......
filter::blob....
filter::crlf......
filter::custom......
filter::file..
filter::ident..
filter::query....
filter::stream.S
filter::systemattrs..
filter::wildcard...
graph::ahead::behind.
graph::commitgraph...
graph::descendant::of..
graph::reachable::from::any..
ignore::path....................................
ignore::status......................................
index::add.
index::addall......
index::bypath............S
index::cache.....
index::collision....
index::conflicts............
index::crlf..........
index::filemodes......
index::inmemory..
index::names.......
index::nsec...
index::racy.........
index::read::index....
index::read::tree.
index::rename..
index::reuc..............
index::splitindex.
index::stage..
index::tests..................................
index::version...
iterator::index.......................
iterator::tree........................
iterator::workdir.................S............
mailmap::basic.....
mailmap::blame..
mailmap::parsing.......
merge::analysis (with bare repository).........
merge::analysis (with nonbare repository).........
merge::annotated::commit.
merge::driver............
merge::files............
merge::trees::automerge....
merge::trees::commits....
merge::trees::modeconflict.
merge::trees::recursive..................
merge::trees::renames....
merge::trees::treediff.....
merge::trees::trivial.............
merge::trees::whitespace...
merge::workdir::dirty......
merge::workdir::recursive..
merge::workdir::renames...
merge::workdir::setup................................
merge::workdir::simple..................
merge::workdir::submodules...
merge::workdir::trivial.............
message::trailer.........
network::cred...
network::fetchlocal.............
network::matchhost.
network::refspecs.........
network::remote::defaultbranch......
network::remote::delete...
network::remote::isvalidname..
network::remote::local...................
network::remote::push..
network::remote::remotes..........................
network::remote::rename.............
network::url::joinpath......
network::url::parse.....................................
network::url::pattern..
network::url::redirect...........
network::url::scp.....................
network::url::valid.
notes::notes.......................
notes::notesref.
object::blob::filter...
object::blob::fromstream..
object::blob::write...
object::cache (cache no blobs)...
object::cache (cache tiny blobs)...
object::cache (cache all blobs)...
object::cache (cache no trees)...
object::commit::commitstagedfile..
object::commit::parse...........
object::lookup......
object::lookupbypath....
object::message................
object::peel......
object::raw::chars..
object::raw::compare.......
object::raw::convert...
object::raw::fromstr..
object::raw::hash...........
object::raw::short...
object::raw::size.
object::raw::type2string...
object::raw::write.......
object::shortid.
object::tag::list..
object::tag::parse............
object::tag::peel...
object::tag::read.....
object::tag::write...........
object::tree::attributes.....
object::tree::duplicateentries..
object::tree::frompath..
object::tree::parse..............
object::tree::read..S
object::tree::update.........
object::tree::walk...
object::tree::write.........
object::validate..
odb::alternates..
odb::backend::mempack.....
odb::backend::multiple.....
odb::backend::nobackend.
odb::backend::nonrefreshing.........
odb::backend::refreshing...........
odb::backend::simple..............
odb::emptyobjects...
odb::foreach....
odb::freshen.....
odb::largefilesSSSSSS
odb::loose...........
odb::mixed....
odb::packed...
odb::packed::one..
odb::sorting...
odb::streamwrite...
pack::filelimit (tiny).
pack::filelimit (medium).
pack::filelimit (unlimited).
pack::indexer........
pack::midx....
pack::packbuilder............
pack::sharing.
pack::threadsafetyS
patch::parse.................
patch::print...........................
path::validate..
rebase::abort.......
rebase::inmemory....
rebase::iterator..
rebase::merge...................
rebase::setup..............
rebase::sign......
rebase::submodule.
refs::basic..
refs::branches::checkedout....
refs::branches::create..........
refs::branches::delete.........
refs::branches::ishead......
refs::branches::iterator.....
refs::branches::lookup........
refs::branches::move..........
refs::branches::name....
refs::branches::remote....
refs::branches::upstream...........
refs::branches::upstreamname..
refs::crashes..
refs::create.............
refs::delete....
refs::dup..
refs::foreachglob......
refs::isvalidname..
refs::iterator........
refs::list..
refs::listall...
refs::lookup.....
refs::namespaces..
refs::normalize......
refs::overwrite....
refs::pack...
refs::peel.......
refs::races......
refs::read...............
refs::reflog::drop.......
refs::reflog::messages..............
refs::reflog::reflog..................
refs::rename...........
refs::revparse...................................
refs::setter....
refs::shorthand.
refs::tags::name.
refs::transactions.........
refs::unicode.
refs::update.
remote::create......................
remote::fetch..
remote::httpproxy....
remote::insteadof..........
remote::list.
repo::config...
repo::discover..........
repo::env.
repo::extensions....
repo::getters....
repo::hashfile...
repo::head...............
repo::headtree....
repo::init..........SS...........S.S....
repo::message..
repo::new..
repo::open....................
repo::pathspec..........
repo::reservedname.....
repo::setters.....
repo::shallow....
repo::state.............
repo::template........
reset::default.....
reset::hard......
reset::mixed...
reset::soft.........
revert::bare...
revert::rename.
revert::workdir...............
revwalk::basic.......................
revwalk::hidecb.......
revwalk::mergebase..............
revwalk::signatureparsing.
revwalk::simplify.
stash::apply...................
stash::drop.......
stash::foreach..
stash::save..................
stash::submodules..
status::renames..................
status::single..
status::submodules...........
status::worktree............................................
status::worktree::init........
stream::deprecated.
stream::registration...
submodule::add.........
submodule::escape..
submodule::init...
submodule::inject::option..
submodule::lookup...............
submodule::modify........
submodule::nosubs.....
submodule::open...
submodule::repository::init.
submodule::status.......
submodule::update.......
threads::atomic.............
threads::basic....
threads::diff..
threads::iterator.
threads::refdb.
threads::tlsdata..
trace::traceSSSSSS
trace::windows::stacktrace...
transport::register.....
transports::smart::packet.............
win32::forbidden..........
win32::longpath....
win32::systemdir........
worktree::bare...
worktree::config..
worktree::merge...
worktree::open........
worktree::reflog....
worktree::refs............
worktree::repository....
worktree::submodule....
worktree::worktree...................................

<end of output>
Test time = 138.61 sec
----------------------------------------------------------
Test Passed.
"offline" end time: Apr 25 19:34 CST
"offline" time elapsed: 00:02:18
----------------------------------------------------------

2/10 Testing: invasive
2/10 Test: invasive
Command: "/Users/zhunannan/temp/libgit2-1.5.0/build/libgit2_tests" "-v" "-score::ftruncate" "-sfilter::stream::bigfile" "-sodb::largefiles" "-siterator::workdir::filesystem_gunk" "-srepo::init" "-srepo::init::at_filesystem_root"
Directory: /Users/zhunannan/temp/libgit2-1.5.0/build/tests/libgit2
"invasive" start time: Apr 25 19:34 CST
Output:
----------------------------------------------------------
No suite matching 'core::ftruncate' found.
<end of output>
Test time =   0.02 sec
----------------------------------------------------------
Test Failed.
"invasive" end time: Apr 25 19:34 CST
"invasive" time elapsed: 00:00:00
----------------------------------------------------------

3/10 Testing: online
3/10 Test: online
Command: "/Users/zhunannan/temp/libgit2-1.5.0/build/libgit2_tests" "-v" "-sonline" "-xonline::customcert"
Directory: /Users/zhunannan/temp/libgit2-1.5.0/build/tests/libgit2
"online" start time: Apr 25 19:34 CST
Output:
----------------------------------------------------------
Loaded 374 suites: 
Started (test status codes: OK='.' FAILURE='F' SKIPPED='S')

online::badssl....
online::clone.........S...SF.SSSSS...SSSS.S..SSSSS
online::fetch..........SS..
online::fetchhead.......
online::pushSSSSSSSSSSSSSSSSSSSSS
online::remotes......

  1) Failure:
online::clone::googlesource [/Users/zhunannan/temp/libgit2-1.5.0/tests/libgit2/online/clone.c:487]
  Function call failed: (git_clone(&g_repo, "https://chromium.googlesource.com/external/github.com/sergi/go-diff", "./foo", &g_options))
  error -1 - SecureTransport error: (null)

<end of output>
Test time = 328.51 sec
----------------------------------------------------------
Test Failed.
"online" end time: Apr 25 19:40 CST
"online" time elapsed: 00:05:28
----------------------------------------------------------

4/10 Testing: online_customcert
4/10 Test: online_customcert
Command: "/Users/zhunannan/temp/libgit2-1.5.0/build/libgit2_tests" "-v" "-sonline::customcert"
Directory: /Users/zhunannan/temp/libgit2-1.5.0/build/tests/libgit2
"online_customcert" start time: Apr 25 19:40 CST
Output:
----------------------------------------------------------
Loaded 374 suites: 
Started (test status codes: OK='.' FAILURE='F' SKIPPED='S')

online::customcert..

<end of output>
Test time =   0.04 sec
----------------------------------------------------------
Test Passed.
"online_customcert" end time: Apr 25 19:40 CST
"online_customcert" time elapsed: 00:00:00
----------------------------------------------------------

5/10 Testing: gitdaemon
5/10 Test: gitdaemon
Command: "/Users/zhunannan/temp/libgit2-1.5.0/build/libgit2_tests" "-v" "-sonline::push"
Directory: /Users/zhunannan/temp/libgit2-1.5.0/build/tests/libgit2
"gitdaemon" start time: Apr 25 19:40 CST
Output:
----------------------------------------------------------
Loaded 374 suites: 
Started (test status codes: OK='.' FAILURE='F' SKIPPED='S')

online::pushSSSSSSSSSSSSSSSSSSSSS

<end of output>
Test time =   0.97 sec
----------------------------------------------------------
Test Passed.
"gitdaemon" end time: Apr 25 19:40 CST
"gitdaemon" time elapsed: 00:00:00
----------------------------------------------------------

6/10 Testing: ssh
6/10 Test: ssh
Command: "/Users/zhunannan/temp/libgit2-1.5.0/build/libgit2_tests" "-v" "-sonline::push" "-sonline::clone::ssh_cert" "-sonline::clone::ssh_with_paths" "-sonline::clone::path_whitespace_ssh"
Directory: /Users/zhunannan/temp/libgit2-1.5.0/build/tests/libgit2
"ssh" start time: Apr 25 19:40 CST
Output:
----------------------------------------------------------
Loaded 374 suites: 
Started (test status codes: OK='.' FAILURE='F' SKIPPED='S')

online::pushSSSSSSSSSSSSSSSSSSSSS
online::cloneS
online::cloneS
online::clone

<end of output>
Test time =   0.98 sec
----------------------------------------------------------
Test Passed.
"ssh" end time: Apr 25 19:40 CST
"ssh" time elapsed: 00:00:00
----------------------------------------------------------

7/10 Testing: proxy
7/10 Test: proxy
Command: "/Users/zhunannan/temp/libgit2-1.5.0/build/libgit2_tests" "-v" "-sonline::clone::proxy"
Directory: /Users/zhunannan/temp/libgit2-1.5.0/build/tests/libgit2
"proxy" start time: Apr 25 19:40 CST
Output:
----------------------------------------------------------
Loaded 374 suites: 
Started (test status codes: OK='.' FAILURE='F' SKIPPED='S')

online::cloneSSSS.S

<end of output>
Test time =   1.84 sec
----------------------------------------------------------
Test Passed.
"proxy" end time: Apr 25 19:40 CST
"proxy" time elapsed: 00:00:01
----------------------------------------------------------

8/10 Testing: auth_clone
8/10 Test: auth_clone
Command: "/Users/zhunannan/temp/libgit2-1.5.0/build/libgit2_tests" "-v" "-sonline::clone::cred"
Directory: /Users/zhunannan/temp/libgit2-1.5.0/build/tests/libgit2
"auth_clone" start time: Apr 25 19:40 CST
Output:
----------------------------------------------------------
Loaded 374 suites: 
Started (test status codes: OK='.' FAILURE='F' SKIPPED='S')

online::clone..S.

<end of output>
Test time =   6.53 sec
----------------------------------------------------------
Test Passed.
"auth_clone" end time: Apr 25 19:40 CST
"auth_clone" time elapsed: 00:00:06
----------------------------------------------------------

9/10 Testing: auth_clone_and_push
9/10 Test: auth_clone_and_push
Command: "/Users/zhunannan/temp/libgit2-1.5.0/build/libgit2_tests" "-v" "-sonline::clone::push" "-sonline::push"
Directory: /Users/zhunannan/temp/libgit2-1.5.0/build/tests/libgit2
"auth_clone_and_push" start time: Apr 25 19:40 CST
Output:
----------------------------------------------------------
Loaded 374 suites: 
Started (test status codes: OK='.' FAILURE='F' SKIPPED='S')

online::clone
online::pushSSSSSSSSSSSSSSSSSSSSS

<end of output>
Test time =   1.00 sec
----------------------------------------------------------
Test Passed.
"auth_clone_and_push" end time: Apr 25 19:40 CST
"auth_clone_and_push" time elapsed: 00:00:00
----------------------------------------------------------

10/10 Testing: util
10/10 Test: util
Command: "/Users/zhunannan/temp/libgit2-1.5.0/build/util_tests" "-v"
Directory: /Users/zhunannan/temp/libgit2-1.5.0/build/tests/util
"util" start time: Apr 25 19:40 CST
Output:
----------------------------------------------------------
Loaded 43 suites: 
Started (test status codes: OK='.' FAILURE='F' SKIPPED='S')

array.
assert.....
bitvec.
copy...
dirent.........
encoding..
errors........
filebuf......S...S.
ftruncateSS
futils.S..
gitstr..........................
hex.
iconv...
init...
integer...
link........................
memmem...
mkdir......
path.................
path::core..............
path::win32............
pool...
posix......
pqueue.....
qsort......
regexp.............
rmdir.....
sha1...
sha256....
sortedcache...
stat..
str::basic...
str::oom..
str::percent..
str::quote...
str::splice.........
string........
strmap...........
strtol........
utf8.
vector..........
wildmatch........
zstream....

<end of output>
Test time =   1.40 sec
----------------------------------------------------------
Test Passed.
"util" end time: Apr 25 19:40 CST
"util" time elapsed: 00:00:01
----------------------------------------------------------

End testing: Apr 25 19:40 CST

**Comment by ethomson** [comment]
v1.5 is no longer maintained. Are you seeing problems with v1.8?

**Comment by ethomson** [comment]
Indeed, this was fixed in cbd5319
