### ISSUE TITLE
1.8.0: alloca not portable

### ISSUE THREAD

**Issue by 0-wiz-0** [libgit2/libgit2#6807]
We've updated libgit2 to 1.8.0 in pkgsrc. Now the [build on Illumos](https://us-central.manta.mnx.io/pkgsrc/public/reports/upstream-trunk/20240507.0509/libgit2-1.8.0/build.log) fails with:
```
[ 29%] Building C object src/cli/CMakeFiles/git2_cli.dir/opt.c.o
/home/pbulk/build/devel/libgit2/work/libgit2-1.8.0/src/cli/opt.c: In function 'cli_opt_parse':
/home/pbulk/build/devel/libgit2/work/libgit2-1.8.0/src/cli/opt.c:560:23: warning: implicit declaration of function 'alloca'; did you mean 'valloc'? [-Wimplicit-function-declaration]
  560 |         given_specs = alloca(sizeof(const cli_opt_spec *) * (args_len + 1));
      |                       ^~~~~~
      |                       valloc
/home/pbulk/build/devel/libgit2/work/libgit2-1.8.0/src/cli/opt.c:560:21: warning: assignment to 'const cli_opt_spec **' from 'int' makes pointer from integer without a cast [-Wint-conversion]
  560 |         given_specs = alloca(sizeof(const cli_opt_spec *) * (args_len + 1));
      |                     ^
At top level:
cc1: note: unrecognized command-line option '-Wno-documentation-deprecated-sync' may have been intended to silence earlier diagnostics
[ 29%] Building C object src/cli/CMakeFiles/git2_cli.dir/opt_usage.c.o
[ 29%] Building C object src/cli/CMakeFiles/git2_cli.dir/progress.c.o
[ 29%] Building C object src/cli/CMakeFiles/git2_cli.dir/unix/sighandler.c.o
[ 30%] Linking C executable ../../git2
Undefined			first referenced
 symbol  			    in file
alloca                              CMakeFiles/git2_cli.dir/opt.c.o
ld: fatal: symbol referencing errors. No output written to ../../git2
collect2: error: ld returned 1 exit status
*** [git2] Error code 1
```

The [NetBSD man](https://man.netbsd.org/alloca.3) page lists a lot of limitations for `alloca` and recommend it not be used in portable code. Also, on NetBSD it's provided by `stdlib.h`, while on Illumos it's in `alloca.h`. The [Illumos man](https://www.illumos.org/man/3C/malloc) page also strongly discourages its use.

**Comment by ethomson** [comment]
Do you know offhand whether MSVC supports VLA and if so, when that support started? `alloca` sort of sucks, but it's _mostly_ portable. (Having to include `alloc.h` is hardly a deal-breaker. Once the AmigaOS folks start trying to use this, though, that's when we'll need to deal with this.)

Anyway, v1.8.1 should properly support Illumos, Solaris, SunOS and include `alloc.h` (@0-wiz-0 please let me know if it does not).

I'll leave this open since no, it's not really that portable, as the issue title describes. It's something to chew on but it's pretty low-priority.

**Comment by boretrk** [comment]
Oh, my bad, I honestly thought MSVC had full C99 support but it seems like they never made any such claim.
It does however seem like [they have deprecated `alloca`](https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/alloca?view=msvc-170) but as you say it still compiles.

**Comment by ethomson** [comment]
They've been slowly chipping away at improving their C compiler. I'll take a look and see where VLA support starts and we can decide how we should attack this. (Could be ifdefs, even.)

Could also just do a malloc. Might be the simplest path forward.

**Comment by ethomson** [comment]
I'm going to close this for now; if / when we run into an architecture that lacks `alloca` we should figure this out for reals.

**Comment by dvklopfenstein** [comment]
> I'm going to close this for now; if / when we run into an architecture that lacks `alloca` we should figure this out for reals.

Thanks for the libgit2 project. It is a pleasure to work with...

FYI: Except I just ran into alloc not being portable as well resulting in a failed build (stopping at 30%) if I clone the libgit2 repo. But thankfully, when I download libgit2-1.8.4, the build is working. I  wanted to add this note to let you know others are running into the error regarding alloc

**Comment by ethomson** [comment]
Hi @dvklopfenstein - sorry, you're saying that a build out of `main` isn't working but building v1.8.4 _does_ work?

What platform are you building on? Can you paste the build output?
