### ISSUE TITLE
diff print patch_header fmt get nothing

### ISSUE THREAD

**Issue by attila-lin** [libgit2/libgit2#6868]
Hello. I come from git2-rs.

I have the same issue [here](https://github.com/rust-lang/git2-rs/issues/1064).

I think it relate with this [PR](https://github.com/libgit2/libgit2/commit/d704046712a762a79689c00767ef7602e86d630f)

`pi->print_cb` never called.

### Reproduction steps

use git2 lib.

### Expected behavior

Worked before

### Actual behavior

now print nothing

### Version of libgit2 (release number or SHA1)

1.8.1

**Comment by ethomson** [comment]
Should have been fixed by https://github.com/libgit2/libgit2/pull/6888
