### ISSUE TITLE
Error: not able to open repository “unsupported extension name extensions.preciousobjects”.

### ISSUE THREAD

**Issue by ao2** [libgit2/libgit2#6873]
libgit2 does not seem to handle AOSP manifest repositories.

I experienced the issue both with [gitg](https://gitlab.gnome.org/GNOME/gitg) which used `libgit2`, and with the `lg2` example command.

### Reproduction steps

```
$ cd /tmp
$ mkdir AOSP
$ cd AOSP
$ repo init -u https://android.googlesource.com/platform/manifest -b main
Downloading Repo source from https://gerrit.googlesource.com/git-repo
repo has been initialized in /tmp/AOSP
$ cd .repo/manifests
$ /tmp/examples/build/lg2 status
Unable to open repository '%s' '.' [-1] - unsupported extension name extensions.preciousobjects
$ gitg 
Error: not able to open repository “unsupported extension name extensions.preciousobjects”.
```

### Expected behavior

`libgit2` is able to open the repo and list all the branches and commits.

### Actual behavior

`libgit2` fails to open the repository with the following error:

```
Unable to open repository '%s' '.' [-1] - unsupported extension name extensions.preciousobjects
```

### Version of libgit2 (release number or SHA1)

1.7.2

### Operating system(s) tested

Debian Unstable / Linux

**Comment by ethomson** [comment]
In this case, this feels like a useful thing to report to gitg, if you haven't already.

The `preciousObjects` extension is a bit of an oddity. It has nothing to do with client support; instead, it indicates that the client should not do any deletion of objects. We do not implicitly include this extension, since we don't know what the client itself is going to do.

If gitg understands this extension -- either because they don't do any object deletion (ever), or because they understand and obey `preciousObjects` then they should [indicate to libgit2 that they understand the extension](https://github.com/libgit2/libgit2/blob/782e29c906f6e44b120843356f286b6a97d89f88/include/git2/common.h#L474).

Probably our example should, too, so that people see how to use it. (Do note that lg2 is _example code_, though, it's not for production.)

**Comment by ao2** [comment]
Thanks @ethomson I will report to `gitg` too.

Does a similar reasoning also apply for extensions like `extensions.partialclone`? Is that also supposed to be handled by the client?

I ask because this is also something that libgit2 complains about in AOSP project repositories:

```
$ cd /tmp/AOSP
$ repo sync -c -j8 --optimize --no-tags
$ cd build/core/
$ gitg 
Error: not able to open repository “unsupported extension name extensions.partialclone”.
```

If this is a different story I will open a separate issue for it.

Thanks again, Antonio

**Comment by ethomson** [comment]
> Does a similar reasoning also apply for extensions like extensions.partialclone? Is that also supposed to be handled by the client?

No, in this case, we simply don't support partial clones. Apologies!

**Comment by ao2** [comment]
I reported the `parialclone` issue in https://github.com/libgit2/libgit2/issues/6880

And I am closing this issue since the `preciousObjects` extension is supposed to be handled by the client.

**Comment by albfan** [comment]
@ethomson as this is an extension to git itself, is not possible to ignore this extensions section? In example provided, just removing the extensions group allows gitg to see the repo.

I suppose this user needs whatever those extensions does (so apart from act like a viewer, gitg might be useless)

gitg is enxtensible by plugins, so someone might implement whatever this extensions.* does, but first step would be to ignore extensions group at all, or accept any of this extensions with an empty imolementation (don't do anything for those extensions)

Current approach to workaround this is to allow gitg to pass this extensions as accepted, but just config libgit2 to ignore it would be helpful

**Comment by ethomson** [comment]
In general - no, libgit2 can't just ignore extensions. Extensions are how git indicates that something significant has changed with the repository. For example: moving from sha1 to sha256 is indicated by an _extension_. If a repository uses sha256 then it sets the extension to indicate that. If we (for example) didn't support sha256 and ignored that option and tried to open a repository, we'd (at best) not be able to read any of the data, (probably) also corrupt the repository and (possibly) worse.

This _particular_ extension is a bit odd though. It doesn't indicate that there's something changed about the repository format, but that the application makes a contract that it won't delete objects. libgit2 could honor that and not allow you to delete an object (and indeed, we don't). But I don't know what _you_ do outside of that.

To extrapolate - even if _you_ don't delete git objects, one of _your_ extensions might. So... it's hard to reason about this particular extension. (The `preciousObjects` extension was not well-designed for libraries to use.)

**Comment by albfan** [comment]
Sorry, I don't even know this was a git thing:

https://git-scm.com/docs/git-config

https://public-inbox.org/git/20150623105411.GB12518@peff.net/

Any example of a working extension to understand it. gitg do not plan to support any extension, just bypass and probably warn about unsupported (but not fail to load the repository)

**Comment by ethomson** [comment]
Yeah, it's a git thing; I have gone back and forth on this. One option is that we honor the preciousObjects extension and don't delete anything nor allow callers to delete anything. (Simple enough.)

I think that this is probably the right thing. The risk is that there's some app that uses libgit2 and deletes objects *on its own* going outside of the libgit2 apis. But I think that if they are going outside our apis then they should be thoughtful about that and the burden is on them.

(Deleting objects when somebody explicitly tells you not to is a Big Deal, though, so I wanted to be thoughtful and conservative about this.)

**Comment by albfan** [comment]
I see the complexity related with allow several custom extensions.

There there's a basic support for this feature in gitg:

https://gitlab.gnome.org/GNOME/gitg/-/issues/473#note_2230334

but appart from saying gitg support a custom extension "preciousObjects" is unclear what are the implications of this setup. libgit2 is not modified in any way.

Is there any example where an extension is added and libgit2 behaviour is modified?

@ao2 my current idea is to detect custom extensions allowed but without implementation provided to warn user about that situation (you are allowed to see the repo, but don't expect that extensions is honored)

**Comment by ethomson** [comment]
No; most extensions are a communication that the repository version is not version 0. For example: SHA256. And it really requires _libgit2_ understanding the extension, not an end user. That's true in this case, too.

I think that it makes sense for libgit2 to just say "yes, we support preciousObjects" and if you're doing a fsck outside of libgit2, then you should pay attention to this configuration _as well_. So I opened #6886 with that in mind.

**Comment by ao2** [comment]
Thanks a lot @ethomson
