### ISSUE TITLE
Use of bundled http-parser due to change in cmake integration

### ISSUE THREAD

**Issue by dvzrv** [libgit2/libgit2#6923]
Hi! :wave: 

I package libgit2 for Arch Linux.
With 1.8.1 I noticed, that the library is no longer built using the system-provided http-parser, when using the relevant cmake option as documented:
https://github.com/libgit2/libgit2/blob/533ec839bda9a3774cd653ba87224e962b97d680/CMakeLists.txt#L38

Instead `-D USE_HTTP_PARSER=http-parser` must be used to build against a system-provided http-parser.

This regression was introduced in https://github.com/libgit2/libgit2/commit/d396819101a67c652af0fa0ae65cda19a2c0430a (from what I can tell).

It would be good to a) consolidate the documentation accordingly, or change the way the new integration interacts with `USE_HTTP_PARSER`, b) fail if a wrong value is provided to an option and  c) not silently choose a bundled version but instead hard fail (silently building with something different is never what downstreams want, if they explicitly selected to build against a system version).

### Reproduction steps
Use cmake option `-D USE_HTTP_PARSER=system` to build with system provided http-parser, as documented in CMakeLists.txt.

### Expected behavior
libgit2 is built with system provided http-parser.

### Actual behavior
libgit2 is (silently!) built with bundled http-parser.

### Version of libgit2 (release number or SHA1)
1.8.2 (1.8.1 is also affected).

### Operating system(s) tested
Arch Linux

**Comment by ethomson** [comment]
Thanks for the report!
