### ISSUE TITLE
Read access violation against parser_settings in http_parser.c>http_parser_execute()

### ISSUE THREAD

**Issue by rshewaga** [libgit2/libgit2#6935]
### Reproduction steps

1. Add `libgit2/1.8.2` as a Conan and CMake project dependency in a C++ project
2. In `main.cpp`, clone an online repository. Much of this code was taken from the [clone.c](https://github.com/libgit2/libgit2/blob/c6111ec06cc0b0126cd67bdab78f8091e4cfaa10/tests/libgit2/online/clone.c) from `tests`
```
#include <memory>
#include <git2/global.h>
#include <git2/repository.h>
#include <git2/clone.h>
#include <git2/errors.h>

static int R_git_transport_certificate_check_cb(git_cert *cert, int valid, const char *host, void *payload)
{
    (void)cert;
    (void)valid;
    (void)host;
    (void)payload;
    return 0;
}

int main(int argc, char** argv)
{
    (void)argc;
    (void)argv;

    int _initResult = git_libgit2_init();
    if(_initResult < 0)
    {
        const git_error* initErr = git_error_last();
        (void)initErr;
    }

    git_checkout_options dummy_opts = GIT_CHECKOUT_OPTIONS_INIT;
    git_fetch_options dummy_fetch = GIT_FETCH_OPTIONS_INIT;

    git_repository* g_repo = NULL;

    static git_clone_options g_options;
    memset(&g_options, 0, sizeof(git_clone_options));
    g_options.version = GIT_CLONE_OPTIONS_VERSION;
    g_options.checkout_opts = dummy_opts;
    g_options.fetch_opts = dummy_fetch;
    g_options.fetch_opts.callbacks.certificate_check = R_git_transport_certificate_check_cb;
    
    int _cloneResult = git_clone(&g_repo, "https://github.com/maxcleme/beadcolors.git", "./test", &g_options);
    (void)_cloneResult;
    
    const git_error* cloneErr = git_error_last();
    (void)cloneErr;

    git_libgit2_shutdown();
}
```

### Expected behavior

1. The `beadcolors` repository should be cloned to `[executable path]/test`

### Actual behavior

1. Only the following files are cloned before the read access violation occurs
```
\test\.git\config
\test\.git\description
\test\.git\HEAD
\test\.git\hooks
\test\.git\info
\test\.git\objects
\test\.git\refs
\test\.git\hooks\README.sample
\test\.git\info\exclude
\test\.git\objects\info
\test\.git\objects\pack
\test\.git\refs\heads
\test\.git\refs\tags
```
2. Read access violation in `http_parser.c`
![Untitled-1](https://github.com/user-attachments/assets/2c7c2c64-20ba-4417-b6ce-152ed0d82972)

### Version of libgit2 (release number or SHA1)
[1.8.2 from Conan](https://conan.io/center/recipes/libgit2)

### Operating system(s) tested
Win 10 Pro, 22H2, 19045.5073

### Other

1. Manually cloning libgit2, building it, installing it, and linking to that install instead of using Conan works for me for the same code. Running the test suite here does succeed on all of the `online` tests which weren't skipped. 
[tests_online.txt](https://github.com/user-attachments/files/17579183/tests_online.txt)

**Comment by ethomson** [comment]
Thanks for reporting this. Could you please update to v1.8.4? 🙏

**Comment by rshewaga** [comment]
I've made a [pull request in the conan-center-index](https://github.com/conan-io/conan-center-index/pull/25780) to get libgit2 updated to 1.8.4. Using the updated package locally fixes my problem.
