### ISSUE TITLE
CMake find

### ISSUE THREAD

**Issue by bmarques1995** [libgit2/libgit2#6976]
I believe that a `find_package` config file will be useful, specially for other projects

### Expected behavior

```cmake
find_package(libgit2)
```

`libgit2 was found`
### Actual behavior

```cmake
find_package(libgit2)
```

`libgit2 was not found, please tell a dir of libgit2Config.cmake`

**Comment by bmarques1995** [comment]
I've added a PR to solve this #6840

**Comment by ethomson** [comment]
Thanks for the fix! This will be included in v1.9
