### ISSUE TITLE
Could not find executable libgit2_clar

### ISSUE THREAD

**Issue by marcdebeer** [libgit2/libgit2#742]
I've followed through the steps described on https://github.com/libgit2/libgit2/wiki/Building-libgit2-on-Windows but receive the following error when executing ctest -V. Any idea as to how I may resolve this? I've tried searching the system for a "libgit2_clar" file, but to no avail.

UpdateCTestConfiguration  from :C:/wamp/bin/php/extensions/libgit2/build/DartConfiguration.tcl
Start processing tests
UpdateCTestConfiguration  from :C:/wamp/bin/php/extensions/libgit2/build/DartConfiguration.tcl
Test project C:/wamp/bin/php/extensions/libgit2/build
Constructing a list of tests
Done constructing a list of tests
Changing directory into C:/wamp/bin/php/extensions/libgit2/build
  1/  1 Testing libgit2_clar                  Could not find executable libgit2_clar
Looked in the following places:
libgit2_clar
libgit2_clar.exe
Release/libgit2_clar
Release/libgit2_clar.exe
Debug/libgit2_clar
Debug/libgit2_clar.exe
MinSizeRel/libgit2_clar
MinSizeRel/libgit2_clar.exe
RelWithDebInfo/libgit2_clar
RelWithDebInfo/libgit2_clar.exe
Deployment/libgit2_clar
Deployment/libgit2_clar.exe
Development/libgit2_clar
Development/libgit2_clar.exe
Unable to find executable: libgit2_clar

0% tests passed, 1 tests failed out of 1

The following tests FAILED:
          1 - libgit2_clar (Not Run)
Errors while running CTest

c:\wamp\bin\php\extensions\libgit2\build>

**Comment by hoseinfilootasisat-byte** [comment]
س
