### ISSUE TITLE
Please add a function to write an index as a tree rather than a commit

### ISSUE THREAD

**Issue by joshtriplett** [libgit2/libgit2#75]
As far as I can tell, libgit2 allows committing an index, but not writing one as a tree without committing it (the equivalent of git write-tree).  Please consider adding a function to write a tree object from an index.

**Comment by chenjw1015** [comment]
oohh... all right, I did not knew the tree cache was persistent, learnt something new about Git today, thanks
 @carlosmn
 Owner
