### ISSUE TITLE
Support mergetag header field

### ISSUE THREAD

**Issue by arrbee** [libgit2/libgit2#762]
When pulling a signed tag, recent versions of git will automatically verify the signature and create a multi-line "mergetag" header field in the merge commit with the signature information. You may want to read @gitster's [blog entry about this](http://git-blame.blogspot.com/2011/11/helping-kernel-workflow-redux.html).  You can see an example of the header [here](http://trac.edgewall.org/ticket/10676). We should make libgit2 support the correct parsing of and access to the multi-line payload.

**Comment by carlosmn** [comment]
I'm going to consider this fixed with #3240. Looking at the contents and verifying them would be a wholly different effort.
