### ISSUE TITLE
git_status_file returns GIT_ENOTFOUND for files within symbolic link directories on Windows

### ISSUE THREAD

**Issue by aroben** [libgit2/libgit2#792]
Given the following directory tree:
- `target`
  - `file.txt`
- `repo`
  - `.git`
  - `link`  (symbolic link to `target`)

Calling `git_status_file("link/file.txt")` returns `GIT_ENOTFOUND`.

(Looks like core git doesn't like this either: running `git add link/file.txt` reports `fatal: 'link/file.txt' is behind a symbolic link`.)

At the very least it would be nice to have a more specific error code for this situation. It would be even more awesome to fully support this kind of setup, but I'm not sure exactly how that should work.

**Comment by ethomson** [comment]
This isn't something that we want to support.
