### ISSUE TITLE
Reference count git_repository

### ISSUE THREAD

**Issue by joshtriplett** [libgit2/libgit2#808]
Please consider making git_repository (and anything else with a _free function) use reference counting or similar.  Language bindings for garbage-collected languages would prove much simpler to write if they could automatically call the appropriate type-specific _free function when something becomes unreferenced.  However, many structures in libgit2 keep internal pointers to other structures; for instance, git_revwalk keeps a pointer to git_repository.  Those internal pointers would become invalid after a git_repository_free.

**Comment by ethomson** [comment]
So.  I'm afraid that I'm going to close this.  I agree that all of the binding authors (myself included) sometimes wish that `git_repository` was refcounted.  We do (as you probably know) refcount everything *except* `git_repository`.

With the current architecture, the lifecycle of a `git_repository` is not easily refcounted in this manner and most GC'd languages have ways to work around this successfully.  We don't anticipate any major changes around this before a 1.0 release.
