### ISSUE TITLE
Writing object should not overwrite existing objects

### ISSUE THREAD

**Issue by hanwen** [libgit2/libgit2#855]
When writing out objects,  filebuf does 

	if (p_rename(file->path_lock, file->path_original) < 0) {
		giterr_set(GITERR_OS, "Failed to rename lockfile to '%s'", file->path_original);
		goto on_error;
	}
..

int p_rename(const char *from, const char *to)
{
	if (!link(from, to)) {
		p_unlink(from);
		return 0;
	}

	if (!rename(from, to))
		return 0;

	return -1;
}

for the ODB, this is very risky.  The ODB should do a link, and if the dest already exists, it should not do the rename.

The currently libgit2 approach is to always overwrite; if there is some data corruption bug (like https://github.com/libgit2/libgit2/issues/853) this can cause existing objects to go bad.

**Comment by carlosmn** [comment]
This is indeed what `git_filebuf` does, but this class is not what determines what gets written. It is `git_odb_write()` and `git_odb_stream_finalize_write()` who do and both check for an object's existence before writing out the object. It is therefore not true that libgit2 always overwrites. It would only overwrite in case of concurrent writing, in which case we already have the same code writing out anyhow.
