### ISSUE TITLE
OID prefixes should include a length

### ISSUE THREAD

**Issue by joshtriplett** [libgit2/libgit2#865]
Currently, both full-length OIDs and OID prefixes use the git_oid type.  However, OID prefixes also require an associated length, and OID prefixes will not work correctly with functions that expect full-length OIDs.

For better type safety, I think it would make sense to make OID prefixes a separate type, git_oid_prefix, which includes a length.  Functions expecting an OID prefix and length (such as git_object_lookup_prefix) could take a git_oid_prefix instead, while functions expecting a full-length OID will continue to take a git_oid.

This would also make OIDs much simpler to handle in language bindings.

If this sounds like a sensible idea, I'll happily prepare a pull request.

**Comment by carlosmn** [comment]
Sorry it's taken so long to get back to you on this, but there does seem to be a lack of interest for this feature.

I do not think we want to make prefixes a first-class data structure. A prefix should only be used at the edges of the system. The prefix lookups are for the case of "this is how much I could get form the user" and should not be used internally as a way to store the data.

**Comment by joshtriplett** [comment]
@carlosmn: I agree completely that prefixes shouldn't be something used for internal storage or similar. That wasn't the issue here. I'm attempting to produce bindings for libgit2, and using git_oid to store both prefixes and full-size OIDs is the kind of type-fuzziness that's more painful in languages that aren't C, at least if trying to provide a safe interface.

If OID prefixes are something only to be used as part of user input and never stored, how about just always storing them as nul-terminated hex strings rather than as binary hash prefixes?  That would make it *really* easy to work with them and to handle prefixes provided by the user.  That would eliminate the need to pass around a length along with a partially initialized git_oid, make it easier to process user input without packing it into a partial git_oid, make it easier to work with prefixes that have an odd number of characters, and make language bindings *much* easier.  Then, git_oid would *always* contain a fully initialized 20-byte OID.

**Comment by carlosmn** [comment]
That's something that would work for bindings. libgit2sharp does something similar. You can pass it a string and it will figure out what the full id is for you before passing it down to whatever function you wanted to call.
