### ISSUE TITLE
Diff is-binary does not consider encoding

### ISSUE THREAD

**Issue by jessevdk** [libgit2/libgit2#880]
It seems that when requesting diffs, any non-ascii content is considered to be binary. This is much too strict. It would be nice to improve the binary content check in git_buf or to use mime type detection.

**Comment by xiaofuhub** [comment]
@carlosmn Now, Git Support working-tree-encoding attribute if you cannot store a file in UTF-8 encoding and if you want Git to be able to process the content as text.
Does libgit2 plan to support this attribute?
