### ISSUE TITLE
Add archive option

### ISSUE THREAD

**Issue by matutetandil** [libgit2/libgit2#918]
It would be wonderful if you can add the git archive functionality.

**Comment by DavHau** [comment]
> This is also quite easy to do with whatever programming language you're using.

@carlosmn The hard part about accurately reproducing `git-archive` is not creating the archive itself, but applying substitutions as configured via the git attribute [export-subst](https://git-scm.com/docs/git-archive#Documentation/git-archive.txt-export-subst).

### from the docs:
If the attribute export-subst is set for a file then Git will expand several placeholders when adding this file to an archive. See [gitattributes[5]](https://git-scm.com/docs/gitattributes) for details.

[according to the gitattributes docs](https://git-scm.com/docs/gitattributes#_export_subst) export-subst uses the same [placeholder replacement logic from git-log](https://git-scm.com/docs/git-log#Documentation/git-log.txt-emnem)

I'm not too familiar with libgit2 yet. What would be a good way of reproducing that behavior with libgit2?
Any pointers are appreciated.
