### ISSUE TITLE
support for hooks (pre-commit / post-commit / post-merge)

### ISSUE THREAD

**Issue by fbergmann** [libgit2/libgit2#964]
It seems that libgit2 does not allow the processing of hooks, that git would perform. Any chance for adding this to the api in a future version?

**Comment by ethomson** [comment]
We've discussed this back and forth a lot.  We will *not* be executing any hooks directly.  We don't want the library to suddenly start forking and executing processes and such.  This is firmly the territory of the application.

However, we do want to have the right callbacks in the right places to make sure that it's easy for people to execute hooks if they want to.

**Comment by lukeapage** [comment]
@ethomson why was this closed? should there not be a new issue for allowing applications to find hooks?

**Comment by carlosmn** [comment]
Finding hooks amounts to getting the contents of the `$gitdir/hooks/` directory and seeing what files are executable (if the system has this). This is not something which you need the library to do. While we could provide an accessor to the hooks directory, there's nothing the library can do better than you using your language's features to look at a directory.

**Comment by lukeapage** [comment]
Makes sense, thanks for answering.

**Comment by knocte** [comment]
This is very sad, as it renders basically all IDEs (at least all of them using libgit2) unable to integrate with commit hooks workflows.

The point of git commit hooks is that they are respected, not that they may ignored depending on the tool you use to interact with git.

**Comment by ethomson** [comment]
> This is very sad, as it renders basically all IDEs (at least all of them using libgit2) unable to integrate with commit hooks workflows.

No, there's nothing stopping your IDE from running hooks.  If your IDE does not support git hooks, then that's a bug / missing feature in the IDE.  As has been mentioned previously in this issue:  libgit2 is not going to run external commands magically.  There are a plurality of reasons for this, but primarily, running programs is a concern of the IDE.  For instance:  Visual Studio has very specific mechanisms for running external commands and if libgit2 simply starts running things, this would be a trainwreck.  No cancellation, no way to get output to the console window, etc.

Thus, this is a concern of the IDE, not a concern of libgit2.

If you are an IDE author and we can help improve this for you, then please let us know how.  If not, please file an issue with your IDE.

**Comment by linquize** [comment]
"Using callback functions as hooks" vs "executing bash shell scripts directly"?

**Comment by ethomson** [comment]
> "Using callback functions as hooks" vs "executing bash shell scripts directly"?

Indeed, we try to provide callbacks at all the states in the workflow so that you can invoke the necessary callbacks at that time, with the necessary information so that you can emulate running the hooks.

If there is something that is missing then please let us know.

**Comment by carlosmn** [comment]
Even if we wanted to run the hooks for you, the library would not know when to run them. The hooks are described in terms of git commands, which neither libgit2 or the IDE are running; and libgit2 does not know when you're e.g. creating a commit in the `git commit` sense or for any other reason. The one where we do know to call is the pre-push hook, and we do have a callback for that. Any others would require code in the library's caller.
